ConvertFrom-StringData -StringData @'
	# th-TH
	# Thai (Thailand)

	FontsUI                         = Leelawadee UI

	# Main page
	Dashboard                       = แดชบอร์ด
	Learn                           = ศึกษา
	Menu                            = เมนู
	Short_Cmd                       = คำสั่งทางลัด
	Shortcut                        = ทางลัด
	Update                          = ต่ออายุ
	CUpdate                         = การปรับปรุงสะสม
	Rebuild                         = การฟื้นฟู
	AddTo                           = เพิ่มไปที่
	Del                             = ลบ
	Copy                            = สำเนา
	Rename                          = เปลี่ยนชื่อ
	Refresh                         = รีเฟรช
	RefreshModules                  = รีเฟรชทุกโมดูลอย่างรวดเร็ว
	Done                            = เสร็จ
	OK                              = แน่นอน
	Cancel                          = ยกเลิก
	AllSel                          = เลือกทั้งหมด
	AllClear                        = เคลียร์ทั้งหมด
	Setting                         = ตั้งค่า
	Change                          = เปลี่ยน
	Help                            = ช่วย
	Logging                         = บันทึก
	AvailableLanguages              = ภาษาที่ใช้ได้
	SwitchLanguage                  = เปลี่ยนภาษา
	LanguageSelRegion               = เลือกประเทศหรือภูมิภาคของคุณ
	LanguageRemember                = จำภาษาที่เลือก
	LanguageSearchNo                = ไม่พบภาษาที่ใช้ได้
	LanguageNoPack                  = หากไม่มีชุดภาษาในเครื่อง ระบบจะออกโดยอัตโนมัติ
	LanguageNoSel                   = โปรดเลือกภูมิภาค
	Search                          = ค้นหา
	PleaseChoose                    = กรุณาเลือก
	Options                         = ตัวเลือก
	Choose                          = เลือกแล้ว
	NoChoose                        = ไม่ได้เลือก
	AdvOption                       = คุณสมบัติเสริม
	ExcludeItem                     = ยกเว้นตามกฎ
	DeDuplication                   = ไม่รวมรายการที่ซ้ำกัน
	DeDuplication_Unlock            = ปลดล็อกรายการที่ซ้ำกันที่ถูกปิดใช้งาน
	Existed                         = มีอยู่แล้ว
	FailedCreateFolder              = ไม่สามารถสร้างไดเร็กทอรี
	FailedCreateFile                = ไม่สามารถสร้างไฟล์ได้
	ToMsg                           = {0} กลับสู่เมนูหลักโดยอัตโนมัติหลังจากผ่านไปไม่กี่วินาที
	OnDemandPlanTask                = การมอบหมายเหตุการณ์ที่ทราบแบบกำหนดเอง
	Operable                        = ใช้งานได้
	Inoperable                      = ใช้ไม่ได้
	Hide                            = ซ่อน
	CuringUpdate                    = การอัปเดตที่มั่นคง
	CuringUpdateTips                = เมื่อการอัปเดตได้รับการเสริมกำลังแล้ว จะไม่สามารถถอนการติดตั้งได้
	Healthy                         = สุขภาพดี
	HealthyTips                     = การตรวจสอบสถานะความสมบูรณ์เป็นสิ่งสำคัญอย่างยิ่ง เมื่อ "สามารถซ่อมแซมได้" หรือ "ไม่สามารถซ่อมแซมได้" ปรากฏขึ้น: ในระหว่างกระบวนการแปลง ESD ระบบจะแจ้งข้อผิดพลาด 13 และข้อมูลไม่ถูกต้องเมื่อติดตั้งระบบ
	Healthy_Save                    = เมื่อปรากฏขึ้นว่าสามารถซ่อมแซมได้หรือแก้ไขไม่ได้ อย่าบันทึก
	Repair                          = ซ่อมแซม
	IsAuto_Repair                   = อนุญาตการซ่อมแซมอัตโนมัติเมื่อไม่ได้ใช้งาน
	IsAuto_Repair_Tips              = ตรวจสอบโดยอัตโนมัติว่ามีงานติดตั้งใดๆ หลังจากการรันสคริปต์บรรจุภัณฑ์แต่ละครั้งหรือไม่ หากติดตั้งไว้ จะไม่มีการซ่อมแซม หากไม่ได้ติดตั้ง การซ่อมแซมอัตโนมัติจะดำเนินการ
	Repairable                      = ปรับปรุง
	NonRepairable                   = ซ่อมไม่ได้
	HealthyForceStop                = ขณะประมวลผลเหตุการณ์ พบข้อผิดพลาดที่ไม่สามารถย้อนกลับได้ และเหตุการณ์ถูกบังคับให้ยุติ\n\n   ทำให้เกิดปัญหาหลัก: \n\n      1. ฮาร์ดแวร์ทางกายภาพเสียหาย ฮาร์ดดิสก์\n\n      2. หากคุณใช้ดิสก์เสมือนหน่วยความจำ RAMDISK (รวมถึงไฮบริด) โปรดตรวจสอบหน่วยความจำกายภาพ\n\n      3. ตรวจสอบ SHA256 ดั้งเดิมของ MVS (MSDN) หากสอดคล้องกัน โปรดเปลี่ยนไดเร็กทอรีและลองอีกครั้ง หาก SHA256 ไม่สอดคล้องกัน โปรดดาวน์โหลดอีกครั้งแล้วลองอีกครั้ง\n\n      4. รายการอื่นๆ ไม่อยู่ในรายการในตัวอย่างนี้
	Superseded                      = ทำความสะอาดที่เปลี่ยนแล้ว
	SupersededTips                  = รวมถึงการอัปเดตที่ล้าสมัย ส่วนประกอบ ฯลฯ
	UnmountFailed                   = ฉันลองมาหลายวิธีแล้ว แต่ก็ไม่สามารถทำได้ ฉันทำได้เพียงหยุด ฉันอยากจะพบคุณในครั้งต่อไป
	SaveTo                          = บันทึกไปที่
	WorkDone                        = เสร็จแล้วกดปุ่มใดก็ได้เพื่อกลับสู่หน้าจอหลัก...
	UserCanel                       = ผู้ใช้ได้ยกเลิกคำขอแล้ว
	Uping                           = กำลังสร้าง
	Exclude_View                    = ดูกฎการยกเว้น
	User_Interaction                = ปฏิสัมพันธ์ของผู้ใช้
	Ok_Go_To                        = มีจำหน่ายที่
	Ok_Go_To_No                     = ไม่ไป

	Detailed                        = รายละเอียด
	Detailed_View                   = ดูรายละเอียดกฎที่เลือก

	AddEnv                          = เพิ่มฟังก์ชันการกำหนดเส้นทางให้กับตัวแปรระบบ
	AddEnvTips                      = หลังจากเพิ่มแล้ว ให้ป้อน Yi ในเซสชัน PowerShell ใดๆ ที่จะตอบสนอง ตัวอย่างเช่น ป้อน "Yi -SIP" เพื่อเรียกใช้การห่อหุ้ม

	Unzip_ISO                       = แยก ISO
	Unzip_Search_Type               = ค้นหาไดเร็กทอรี ( {0} )
	ISO_Other                       = เอกสารอื่นๆ
	Unzip_Language                  = ชุดภาษา
	Unzip_Fod                       = ชุดคุณลักษณะ
	FileName                        = ชื่อไฟล์

	UserCancel                      = ผู้ใช้ได้ยกเลิกการดำเนินการ
	MatchMode                       = จับคู่
	Failed                          = ล้มเหลว
	RandomSelect                    = สุ่มเลือก
	RulePre                         = กฎที่กำหนดไว้ล่วงหน้า
	RuleOther                       = กฎเกณฑ์อื่นๆ
	RuleCustomize                   = กฎที่กำหนดเอง
	RuleCustomize_Dont              = อย่าใช้กฎที่กำหนดเองของไดเรกทอรีหลายระดับ
	RuleCustomize_Dont_Tips         = หลังจากลบไดเร็กทอรีเก่าแล้วให้คลิก "ตรวจสอบกฎการตั้งชื่อ"
	RuleMultistage                  = กฎไดเรกทอรีหลายระดับ
	RuleMultistageFindFailed        = ไม่พบกฎไดเรกทอรีหลายระดับ คลิกฉันเพื่อสร้างเทมเพลต
	RuleMultistageFindCreateNew     = สร้างเทมเพลตกฎไดเรกทอรีหลายระดับใหม่
	RuleMultistageTips              = ปรับกฎไดเรกทอรีหลายระดับโดยอัตโนมัติ กฎไดเรกทอรี {0} ถูกปิดใช้งาน
	RuleCustomizeNot                = ไม่พบชื่อส่วนขยาย (Solutions.Custom.Extension) โปรดดูเอกสารวิธีใช้
	RuleCustomizeTips               = ไม่มีการสร้างกฎที่กำหนดเอง โปรดดูเอกสารช่วยเหลือ
	RuleMatchNoFindFolder           = ไม่สามารถจับคู่ไดเร็กทอรี คลิกฉันเพื่อสร้างไดเร็กทอรี
	RuleNoFindFile                  = ไม่พบไฟล์ที่ใช้ได้ โปรดเพิ่มและรีเฟรช
	RuleFindFolder                  = ไดเร็กทอรีจะถูกเลือกโดยอัตโนมัติเมื่อพร้อมใช้งาน
	RuleNameNewChange               = ซิงค์อัตโนมัติหลังการอัปเดต
	RuleNewTempate                  = สร้างเทมเพลต
	RuleSkipFolderCheck             = ไม่ต้องตรวจสอบว่ามีไฟล์อยู่ในไดเร็กทอรีและประเภทไฟล์อีกต่อไป
	RuleAuthon                      = ผู้สร้างกฎ
	RuleGUID                        = GUID ตัวระบุที่ไม่ซ้ำกันทั่วโลก
	RuleName                        = ชื่อกฎ
	RuleDescription                 = อธิบาย
	RuleNameUse                     = ซิงค์ชื่อกฎกับ: {0}
	RuleISO                         = ตรงกับแพ็คเกจการติดตั้ง ISO ดั้งเดิม
	RuleInBoxApps                   = แอปพลิเคชันที่กำหนดค่าไว้ล่วงหน้าเสร็จสมบูรณ์
	RuleFileType                    = ชื่อแพ็คเกจ
	RuleFileFind                    = ชื่อการค้นหาคลุมเครือ
	RuleFindError                   = พบ {0} รายการที่ต้องดำเนินการ คลิก "ตรวจสอบการอ้างอิง" เพื่อดูรายละเอียด
	RuleSelectApps                  = แอพพลิเคชั่นที่ผู้ใช้เลือก
	DependencyPackage               = แพ็คเกจการพึ่งพา
	RuleDependenciesRequired        = การพึ่งพาที่จำเป็น
	RuleDependenciesUnselected      = การอ้างอิงที่ไม่ได้เลือก
	RuleDependenciesNoCheck         = การขึ้นต่อกันจะไม่ถูกตรวจสอบอีกต่อไป
	RuleDependenciesFix             = ไม่ได้เลือกการอ้างอิงการแก้ไข
	Extract_Tips                    = คำใบ้\n\n   1. ผลลัพธ์หลังจากแยกแพ็คเกจภาษาไม่สามารถใช้เป็นออบเจ็กต์อ้างอิงหลักได้\n\n   2. โปรดใช้รายการส่วนประกอบเป็นวัตถุอ้างอิงหลัก วิธีสร้าง:\n\n       เลือกส่วนประกอบที่สร้างขึ้น (รับแพ็คเกจในอิมเมจที่ติดตั้ง) ใน Functions เลือกพิมพ์หรือดูทันที\n\n   3. หลังจากติดตั้งชุดภาษาแล้ว โปรดสร้างรายงานส่วนประกอบใหม่เพื่อตรวจสอบว่าสอดคล้องกันหรือไม่

	DescendingRuleLang              = ลบชุดภาษาในลำดับย้อนกลับ
	OrderRuleLang                   = ติดตั้งชุดภาษาตามลำดับที่กำหนดไว้ล่วงหน้า
	OrderRuleLangTips               = เพิ่มตามลำดับ: พื้นฐาน, แบบอักษร, การรู้จำอักขระด้วยแสง, การรู้จำลายมือ, การอ่านออกเสียงข้อความ, การรู้จำเสียง, ประสบการณ์การสาธิตการขายปลีก, อื่นๆ
	RuleLanguageTips                = แสดงให้เห็น: \n\n   หลังจากใช้ "ติดตั้งชุดภาษาตามลำดับที่กำหนดไว้ล่วงหน้า" ไฟล์จะถูกจับคู่โดยอัตโนมัติตามชื่อที่ไม่ชัดเจนตามลำดับต่อไปนี้:\n
	Match_installed_List            = เมื่อติดตั้งชุดภาษา ให้ไวด์การ์ดจากรายการที่ติดตั้ง
	Match_installed_List_Tips       = ตรงกันเฉพาะเมื่อติดตั้งแล้ว: พื้นฐาน, การรู้จำอักขระด้วยแสง, การรู้จำลายมือ, การแปลงข้อความเป็นคำพูด, การรู้จำเสียง
	RuleLanguageTipsExt             = \n   เมื่อไม่ได้ใช้ "ติดตั้งชุดภาษาตามลำดับที่กำหนดไว้ล่วงหน้า":\n   ค้นหาไฟล์ทั้งหมดในไดเร็กทอรีโดยอัตโนมัติตามประเภทไฟล์และติดตั้ง\n\n   คุณสมบัติภาษาและภูมิภาคตามความต้องการ (FOD)\n   https://learn.microsoft.com/th-th/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = หมวดหมู่
	Basic                           = ขั้นพื้นฐาน
	Fonts                           = แบบอักษร
	OCR                             = การรู้จำอักขระด้วยแสง
	Handwriting                     = การรู้จำลายมือ
	TextToSpeech                    = ข้อความเป็นคำพูด
	Speech                          = การรู้จำเสียงพูด
	Retail                          = ประสบการณ์การสาธิตการค้าปลีก
	Features_On_Demand              = คุณสมบัติตามความต้องการ
	RegionSpecific                  = ข้อกำหนดเฉพาะภูมิภาคอื่นๆ
	UnassignedLangFiles             = ไฟล์เบ็ดเตล็ดที่ยังไม่ได้กำหนด

	ProcessingImage                 = ประมวลผลภาพ:
	NoInstallImage                  = ไม่มีอยู่ในท้องถิ่น
	ConvertChk                      = ตรวจสอบไฟล์
	WindowsFeature                  = คุณสมบัติของวินโดวส์
	Enable                          = เปิดใช้งาน
	Disable                         = ปิดการใช้งาน
	EnableFeatureTips               = คำใบ้\n\n    1. แสดง NetFx3 และ TelnetClient เป็นรายการฟังก์ชันที่เปิดใช้งานที่ตั้งไว้ล่วงหน้า\n\n    2. หลังจาก "ติดตั้ง" แล้ว สามารถเปิดใช้งานเพิ่มเติมได้
	ViewLanguage                    = ดูการตั้งค่าภาษาของภาพ
	ImageLanguage                   = การตั้งค่าภาษาของภาพ
	OnlyLangCleanup                 = ทำความสะอาดส่วนประกอบ: แท็กตามภาษา
	Matched_Component_Names         = ชื่อส่วนประกอบที่ตรงกัน:
	BootProcess                     = เมื่อประมวลผล {0}.wim
	Sync_Language_To                = ซิงค์ไปที่
	BootSyncToISO                   = ซิงโครไนซ์ชุดภาษากับตัวติดตั้ง
	BootSyncToISOTips               = ชุดภาษาที่ติดตั้งของอิมเมจออฟไลน์จะซิงโครไนซ์กับตัวติดตั้ง ISO
	LangIni                         = สร้าง Lang.ini ใหม่
	LangIniTips                     = หลังจากการซิงโครไนซ์เสร็จสิ้นแล้ว Lang.ini ใน ISO จะต้องถูกสร้างขึ้นใหม่
	LangNewAutoSelect               = เลือกรายการที่แนะนำโดยอัตโนมัติเมื่อมีเหตุการณ์เกิดขึ้น
	LangNewAutoSelectTips           = มีกิจกรรมใหม่ เลือก "ซิงค์ชุดภาษากับตัวติดตั้ง" เลือก "สร้าง Lang.ini ใหม่"
	LangNewAutoNoSelect             = มีเหตุการณ์ใหม่ ขอแนะนำให้คุณเลือก "ซิงโครไนซ์ชุดภาษากับตัวติดตั้ง" และ "สร้าง Lang.ini ใหม่"
	LangNewAutoNoNewSelect          = ไม่มีเหตุการณ์ใหม่ ขอแนะนำไม่ให้คุณเลือก "ซิงโครไนซ์ชุดภาษากับตัวติดตั้ง" หรือ "สร้าง Lang.ini ใหม่"
	Drive                           = ขับ
	ViewDrive                       = ดูไดรเวอร์ที่ติดตั้ง
	EditionsProductKey              = รหัสผลิตภัณฑ์
	Editions                        = เวอร์ชันรูปภาพ
	Assign_Editions                 = แจกจ่ายแอปพลิเคชันโดยอัตโนมัติตามเวอร์ชันของรูปภาพ
	EditionsChangeTips              = คำเตือน โปรดทำความเข้าใจก่อนที่จะเปลี่ยนเวอร์ชันรูปภาพ:\n\nMicrosoft ข้อตกลงการบริการ\nhttps://www.microsoft.com/th-th/servicesagreement/default.aspx\n\nภาพรวมภาษา\nhttps://learn.microsoft.com/th-th/windows-hardware/manufacture/desktop/languages-overview\n\nคุณไม่ได้รับอนุญาตให้สร้างเวอร์ชันของ: \n   1. เฉพาะประเทศ\n       ProfessionalCountrySpecific\n\n   2. เวอร์ชันโฮมเฉพาะภูมิภาค\n       ProfessionalSingleLanguage\n\nโปรดปฏิบัติตามอย่างเคร่งครัด เนื่องจากคุณอาจถูกดำเนินคดีหากฝ่าฝืน\n\nหากคุณยืนยันที่จะแปลง ให้คลิกเพื่อยอมรับคำเตือน และคลิก "ปลดล็อกเวอร์ชันรูปภาพที่ซ่อนอยู่"
	EditionsChangeHide              = ปลดล็อกเวอร์ชันรูปภาพที่ซ่อนอยู่
	EditionsChangeAccect            = ฉันได้อ่านคำเตือนแล้วและต้องรับผิดชอบต่อกฎหมายที่เกี่ยวข้องที่มีอยู่ในคำเตือน

	SelFile                         = เลือกไฟล์
	Rebuilding                      = อยู่ระหว่างการบูรณะใหม่
	RebuildAll                      = สร้างใหม่ทั้งหมด
	Export_Image                    = ส่งออก
	SelectFromError                 = ความผิดพลาด
	SelectFileFormatError           = รูปแบบไฟล์ไม่ถูกต้อง

	SearchDrive                     = ขับเคลื่อนการค้นหา
	SearchUpdate                    = ค้นหาการอัปเดต ประเภท ( {0} ) แหล่งที่มา:
	SelectFolder                    = เลือกไดเรกทอรี
	DropFolder                      = สามารถลากไดเร็กทอรีไปยังหน้าต่างปัจจุบันได้
	DropFile                        = สามารถลากไฟล์ไปยังหน้าต่างปัจจุบันได้
	Sparse                          = หายาก
	CRCSHA                          = ตรวจสอบ
	Alternative                     = ชื่อไฟล์ทางเลือก
	ChangeInstallDisk               = เปลี่ยนการเลือกดิสก์อัตโนมัติ

	# View
	ExportToLogs                    = พิมพ์รายงานเพื่อเข้าสู่ระบบ
	ExportShow                      = แสดงรายงานได้ทันที
	MoreFeature                     = คุณสมบัติเพิ่มเติม
	OpenFolder                      = เปิดไดเรกทอรี
	OpenFile                        = เปิดไฟล์
	Running                         = วิ่ง
	Paste                           = คัดลอกเส้นทาง
	Clipboard_Copy                  = คัดลอกไปยังคลิปบอร์ดแล้ว
	ViewWIMFileInfo                 = ดูภาพ
	GetInBoxApps                    = InBox Apps แพ็คเกจแอปพลิเคชันที่ติดตั้ง
	GetImagePackage                 = ส่วนประกอบ: แพ็คเกจทั้งหมดที่ติดตั้งในอิมเมจ
	ViewMounted                     = รับข้อมูลเกี่ยวกับรูปภาพที่ติดตั้งทั้งหมด
'@