ConvertFrom-StringData -StringData @'
	# it-IT
	# Italian (Italy)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Pannello di controllo
	Learn                           = Studio
	Menu                            = Menu
	Short_Cmd                       = Comando di scelta rapida
	Shortcut                        = Scorciatoia
	Update                          = Rinnovare
	CUpdate                         = Aggiornamenti cumulativi
	Rebuild                         = Ricostruzione
	AddTo                           = Aggiungere a
	Del                             = Eliminare
	Copy                            = Copia
	Rename                          = Rinominare
	Refresh                         = Aggiornare
	RefreshModules                  = Aggiornamento a caldo di tutti i moduli
	Done                            = Fine
	OK                              = Sicuro
	Cancel                          = Cancellare
	AllSel                          = Seleziona tutto
	AllClear                        = Cancella tutto
	Setting                         = Impostare
	Change                          = Modifica
	Help                            = Aiuto
	Logging                         = Tronco d'albero
	AvailableLanguages              = Lingue disponibili
	SwitchLanguage                  = Cambiare lingua
	LanguageSelRegion               = Seleziona il tuo paese o regione
	LanguageRemember                = Ricorda la lingua selezionata
	LanguageSearchNo                = Nessuna lingua disponibile trovata
	LanguageNoSel                   = Seleziona una regione
	Search                          = Ricerca
	SearchAllDrives                 = Cerca in tutte le unità
	MountCategory                   = Tutte le ISO trovate, montate
	PleaseChoose                    = Seleziona
	Options                         = Opzioni
	Choose                          = Selezionato
	NoChoose                        = Non selezionato
	AdvOption                       = Funzionalità opzionali
	ExcludeItem                     = Escludi per regola
	DeDuplication                   = Escludi duplicati
	DeDuplication_Unlock            = Sblocca i duplicati disabilitati
	Existed                         = Esiste già
	FailedCreateFolder              = Impossibile creare la directory
	FailedCreateFile                = Impossibile creare il file
	ToMsg                           = {0} Ritorna automaticamente al menu principale dopo secondi.
	OnDemandPlanTask                = Assegnazione personalizzata di eventi noti
	Operable                        = Operabile
	Inoperable                      = Inoperabile
	Hide                            = Nascondere
	CuringUpdate                    = Aggiornamento solido
	CuringUpdateTips                = Una volta consolidato l'aggiornamento, non è possibile disinstallarlo.
	Healthy                         = Salutare
	Healthy_Save                    = Quando appare riparabile o irreparabile, non salvare.
	Repair                          = Riparazione
	IsAuto_Repair                   = Consenti la riparazione automatica quando inattivo
	IsAuto_Repair_Tips              = Controlla automaticamente se sono presenti attività di montaggio dopo ogni esecuzione dello script di confezionamento. Se è montato, non verrà eseguita alcuna riparazione; se non è montato, verrà eseguita la riparazione automatica.
	Repairable                      = Riparabile
	NonRepairable                   = Non riparabile
	HealthyForceStop                = Durante l'elaborazione dell'evento, è stato riscontrato un errore irreversibile e l'evento è stato interrotto forzatamente.\n\n   Causa principali problemi: \n\n      1. L'hardware fisico è danneggiato, disco rigido;\n\n      2. Se si utilizza il disco virtuale di memoria RAMDISK (incluso quello ibrido), controllare la memoria fisica;\n\n      3. Verificare l'originale SHA256 di MVS (MSDN). Se è coerente, modificare la directory e riprovare. Se SHA256 non è coerente, scaricarlo di nuovo e riprovare.\n\n      4. Altri non sono elencati in questo esempio.
	Superseded                      = Pulisci quello sostituito
	SupersededTips                  = Include aggiornamenti, componenti, ecc. obsoleti.
	UnmountFailed                   = Ho provato diversi metodi, ma non si può fare nulla, posso solo farla finita. Vorrei vederti la prossima volta.
	SaveTo                          = Salva in
	WorkDone                        = Completato, premere un tasto qualsiasi per tornare all'interfaccia principale...
	UserCanel                       = L'utente ha annullato la richiesta.
	Uping                           = Generazione
	Exclude_View                    = Visualizza le regole di esclusione
	User_Interaction                = Interazione dell'utente
	Ok_Go_To                        = Disponibile a
	Ok_Go_To_No                     = Non andrò

	Detailed                        = Dettagliato
	View                            = Visualizza
	Detailed_View                   = Visualizza i dettagli della regola selezionata

	AddEnv                          = Aggiungi funzionalità di routing alle variabili di sistema
	AddEnvTips                      = Dopo l'aggiunta, inserisci Yi in qualsiasi sessione di PowerShell per rispondere. Ad esempio, inserisci "Yi -SIP" per eseguire l'incapsulamento.

	Unzip_ISO                       = Estrai ISO
	Unzip_Search_Type               = Directory di ricerca ( {0} )
	ISO_Other                       = Altri documenti
	Unzip_Language                  = Pacchetto linguistico
	Unzip_Fod                       = Pacchetto funzionalità
	FileName                        = Nome del file

	UserCancel                      = L'utente ha annullato l'operazione.
	MatchMode                       = Incontro
	Failed                          = Fallire
	RandomSelect                    = Selezionato casualmente
	RulePre                         = Regole preimpostate
	RuleOther                       = Altre regole
	RuleCustomize                   = Regole personalizzate
	RuleCustomize_Dont              = Non utilizzare regole personalizzate di directory multilivello
	RuleCustomize_Dont_Tips         = Dopo aver eliminato la vecchia directory, fai clic su "Verifica regole di denominazione".
	RuleMultistage                  = Regole di directory multilivello
	RuleMultistageFindFailed        = Nessuna regola della directory multilivello trovata, fai clic su di me per creare un modello.
	RuleMultistageFindCreateNew     = Crea un nuovo modello di regola di directory multilivello
	RuleMultistageTips              = Adatta automaticamente le regole della directory multilivello, la regola della directory {0} è stata disabilitata.
	RuleCustomizeNot                = Nome dell'estensione (Solutions.Custom.Extension) non trovato, consulta la documentazione della guida.
	RuleCustomizeTips               = Nessuna regola personalizzata creata, consulta la documentazione della guida.
	RuleMatchNoFindFolder           = Impossibile abbinare la directory, fai clic su di me per creare la directory.
	RuleNoFindFile                  = Nessun file disponibile trovato, aggiungi e aggiorna.
	RuleFindFolder                  = Directory selezionata automaticamente quando disponibile
	RuleNameNewChange               = Sincronizza automaticamente dopo gli aggiornamenti
	RuleNewTempate                  = Crea modello
	RuleSkipFolderCheck             = Non controlla più se il file esiste nella directory e nel tipo di file
	RuleAuthon                      = Creatore di regole
	RuleGUID                        = GUID identificatore univoco globale
	RuleName                        = Nome della regola
	RuleDescription                 = Descrivere
	RuleNameUse                     = Sincronizza il nome della regola su: {0}
	RuleISO                         = Corrisponde al pacchetto di installazione ISO originale
	RuleInBoxApps                   = Applicazione completa e preconfigurata
	RuleFileType                    = Nome del pacchetto
	RuleFileFind                    = Nome di ricerca fuzzy
	RuleFindError                   = Trovati {0} elementi da elaborare, fai clic su "Verifica dipendenze" per visualizzare i dettagli.
	RuleSelectApps                  = Applicazioni selezionate dall'utente
	DependencyPackage               = Pacchetto di dipendenze
	RuleDependenciesRequired        = Dipendenze richieste
	RuleDependenciesUnselected      = Dipendenze non selezionate
	RuleDependenciesNoCheck         = Le dipendenze non vengono più controllate
	RuleDependenciesFix             = Correggi le dipendenze non selezionate
	Extract_Tips                    = Suggerimento\n\n   1. Il risultato dopo l'estrazione del pacchetto linguistico non può essere utilizzato come oggetto di riferimento principale;\n\n   2. Utilizzare l'elenco dei componenti come oggetto di riferimento principale. Come generare:\n\n       In Funzioni, seleziona Genera componente (ottieni il pacchetto nell'immagine installata), seleziona Stampa o Visualizza immediatamente;\n\n   3. Dopo aver installato il pacchetto lingua, rigenerare un report del componente per verificare se è corrispondente;

	DescendingRuleLang              = Rimuovere i Language Pack in ordine inverso
	OrderRuleLang                   = Installa i pacchetti lingua nell'ordine prestabilito
	OrderRuleLangTips               = Aggiungi in ordine: Base, Caratteri, Riconoscimento ottico dei caratteri, Riconoscimento della grafia, Sintesi vocale, Riconoscimento vocale, Esperienza demo al dettaglio, Altro
	RuleLanguageTips                = Nota:\n\n    Dopo aver utilizzato "Installa i pacchetti lingua nell'ordine prestabilito", i file verranno automaticamente abbinati con nomi fuzzy nel seguente ordine:\n
	Match_installed_List            = Quando si installa un pacchetto lingua, inserirlo come carattere jolly dall'elenco installato
	Match_installed_List_Tips       = Corrisponde solo una volta installato: Base, Riconoscimento ottico dei caratteri, Riconoscimento della grafia, Sintesi vocale, Riconoscimento vocale.
	RuleLanguageTipsExt             = \n   Quando non si utilizza "Installa i pacchetti lingua in ordine predefinito": \n   Cerca automaticamente tutti i file nella directory per tipo di file e installali.\n\n   Funzionalità su richiesta per lingua e regione (FOD)\n   https://learn.microsoft.com/it-it/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Categoria
	Basic                           = Di base
	Fonts                           = Font
	OCR                             = Riconoscimento ottico dei caratteri
	Handwriting                     = Riconoscimento della grafia
	TextToSpeech                    = Testo in parlato
	Speech                          = Riconoscimento vocale
	Retail                          = Esperienza dimostrativa al dettaglio
	Features_On_Demand              = Funzionalità su richiesta
	RegionSpecific                  = Altri requisiti specifici della regione
	UnassignedLangFiles             = File vari non assegnati

	ProcessingImage                 = Elabora l'immagine:
	NoInstallImage                  = Non esiste localmente
	ConvertChk                      = Controlla il file
	WindowsFeature                  = Funzionalità di Windows
	Enable                          = Abilitare
	Disable                         = Disabilita
	EnableFeatureTips               = Suggerimento\n\n    1. Visualizza NetFx3 e TelnetClient come elementi di funzione abilitati preimpostati;\n\n    2. Dopo il "montaggio", è possibile abilitarne altre.
	ViewLanguage                    = Visualizza le impostazioni della lingua dell'immagine
	ImageLanguage                   = Impostazioni della lingua dell'immagine
	OnlyLangCleanup                 = Componenti puliti: tag per lingua
	Matched_Component_Names         = Nome del componente corrispondente:
	BootProcess                     = Durante l'elaborazione di {0}.wim
	Sync_Language_To                = Sincronizza con
	BootSyncToISO                   = Sincronizza i pacchetti lingua con il programma di installazione
	BootSyncToISOTips               = Il Language Pack installato dell'immagine offline è sincronizzato con il programma di installazione ISO.
	LangIni                         = Rigenera Lang.ini
	LangIniTips                     = Una volta completata la sincronizzazione, Lang.ini nell'ISO deve essere ricostruito.
	LangNewAutoSelect               = Seleziona automaticamente gli elementi suggeriti quando si verifica un evento
	LangNewAutoSelectTips           = Sono presenti nuovi eventi, "Sincronizza il pacchetto lingua con il programma di installazione", "Ricostruisci Lang.ini" selezionato.
	LangNewAutoNoSelect             = Sono presenti nuovi eventi, si consiglia di selezionare "Sincronizza il pacchetto lingua con il programma di installazione" e "Ricostruisci Lang.ini".
	LangNewAutoNoNewSelect          = Non sono presenti nuovi eventi. Si consiglia di non selezionare "Sincronizza il pacchetto lingua con il programma di installazione" o "Ricostruisci Lang.ini".
	Drive                           = Guidare
	ViewDrive                       = Visualizza i driver installati
	Editions                        = Versione dell'immagine
	Assign_Editions                 = Distribuisci automaticamente le applicazioni in base alle versioni delle immagini

	SelFile                         = Seleziona file
	Rebuilding                      = In fase di ricostruzione
	RebuildAll                      = Ricostruisci tutto
	Export_Image                    = Esportare
	SelectFromError                 = Errore
	SelectFileFormatError           = Il formato del file non è corretto

	SearchDrive                     = Guidato dalla ricerca
	SearchUpdate                    = Cerca aggiornamenti, tipo ( {0} ), fonte:
	SelectFolder                    = Seleziona la directory
	DropFolder                      = Può trascinare le directory nella finestra corrente
	DropFile                        = I file possono essere trascinati nella finestra corrente
	Sparse                          = Raro
	CRCSHA                          = Controllo
	Alternative                     = Nome file alternativo
	ChangeInstallDisk               = Modifica la selezione automatica del disco
	Backup                          = Backup
	Restore                         = Ripristino
	Import                          = Importare

	# View
	ExportToLogs                    = Stampa il rapporto per accedere
	ExportShow                      = Visualizza i report istantaneamente
	MoreFeature                     = Più funzionalità
	OpenFolder                      = Apri la rubrica
	OpenFile                        = Aprire il file
	Running                         = Correre
	Paste                           = Percorso di copia
	Clipboard_Copy                  = Copiato negli appunti
	ViewWIMFileInfo                 = Visualizza l'immagine
	GetInBoxApps                    = App InBox: pacchetti di applicazioni installati
	GetImagePackage                 = Componenti: tutti i pacchetti installati nell'immagine
	ViewMounted                     = Ottieni informazioni su tutte le immagini montate
'@