ConvertFrom-StringData -StringData @'
	# nb-NO
	# Norwegian, Bokmål (Norway)

	IsCreate                        = Skape
	Solution                        = Løsning
	EnabledSoftwarePacker           = Samling
	EnabledUnattend                 = Må svare på forhånd
	EnabledEnglish                  = Implementeringsmotor
	UnattendSelectVer               = Velg 'Svar til' løsningsspråk
	UnattendLangPack                = Velg 'Løsning' språkpakke
	UnattendSelectSingleInstl       = Flerspråklig, valgfritt under installasjon
	UnattendSelectMulti             = Flerspråklig
	UnattendSelectDisk              = Velg Autounattend.xml-løsningen
	UnattendSelectSemi              = Halvautomatisk er gyldig for alle installasjonsmetoder
	UnattendSelectUefi              = UEFI installeres automatisk og må spesifiseres
	UnattendSelectLegacy            = Legacy installeres automatisk og må spesifiseres
	NeedSpecified                   = Velg hva som skal spesifiseres:
	OOBESetupOS                     = Installasjonsgrensesnitt
	OOBEProductKey                  = Produktnøkkel
	OOBEOSImage                     = Velg operativsystemet som skal installeres
	OOBEEula                        = Godta lisensvilkårene
	OOBEDoNotServerManager          = Server Manager starter ikke automatisk ved pålogging
	OOBEIE                          = Internet Explorer forbedret sikkerhetskonfigurasjon
	OOBEIEAdmin                     = Lukk "Administrator"
	OObeIEUser                      = Lukk "Brukere"

	OOBE_Init_User                  = Første bruker under unboxing-opplevelse
	OOBE_init_Create                = Opprett tilpassede brukere
	OOBE_init_Specified             = Spesifiser bruker
	OOBE_Init_Autologin             = Automatisk pålogging

	InstlMode                       = Installasjonsmetode
	Business                        = Business versjon
	BusinessTips                    = Avhenger av EI.cfg, indeksnummeret må spesifiseres for automatisk installasjon.
	Consumer                        = Forbrukerversjon
	ConsumerTips                    = Den er ikke avhengig av EI.cfg. Serienummeret må spesifiseres for automatisk installasjon.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [montere til]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Legg til på systemdiskens navn på hjemmekatalogen
	VerifyNameUse                   = Bekreft at katalognavnet ikke kan inneholde
	VerifyNameTips                  = Bare en kombinasjon av engelske bokstaver og tall er tillatt, og kan ikke inneholde: mellomrom, lengde kan ikke være større enn 260 tegn, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Bekreftelsen mislyktes, skriv inn riktig nummer.
	VerifyNameSync                  = Angi katalognavn som primært brukernavn
	VerifyNameSyncTips              = Administrator brukes ikke lenger.
	ManualKey                       = Velg eller skriv inn produktnøkkelen manuelt
	ManualKeyTips                   = Skriv inn en gyldig produktnøkkel Hvis den valgte regionen ikke er tilgjengelig, gå til Microsofts offisielle nettsted for å sjekke.
	ManualKeyError                  = Produktnøkkelen du skrev inn er ugyldig.
	KMSLink1                        = KMS-klientinnstillingsnøkkel
	KMSUnlock                       = Vis alle kjente KMS-serienumre
	KMSSelect                       = Vennligst velg VOL serienummer
	KMSKey                          = Serienummer
	KMSKeySelect                    = Endre produktets serienummer
	ClearOld                        = Rydd opp i gamle filer
	SolutionsSkip                   = Hopp over å lage løsning
	SolutionsTo                     = Legg til 'løsning' til:
	SolutionsToMount                = Montert eller lagt til i kø
	SolutionsToError                = Noen funksjoner er deaktivert Hvis du trenger å tvinge dem til å bruke, klikker du på "Lås opp".\n\n
	UnlockBoot                      = Låse opp
	SolutionsToSources              = Hjemmekatalog, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Velg 'Deployment Engine'-versjon
	SolutionsEngineRegionaUTF8      = Beta: Global språkstøtte ved bruk av Unicode UTF-8
	SolutionsEngineRegionaUTF8Tips  = Det ser ut til at det kan forårsake nye problemer etter å ha åpnet det. Ikke anbefalt.
	SolutionsEngineRegionaling      = Bytt til ny lokalitet:
	SolutionsEngineRegionalingTips  = Endre systemlokale, som påvirker alle brukerkontoer på datamaskinen.
	SolutionsEngineRegional         = Endre systemlokalitet
	SolutionsEngineRegionalTips     = Global standard: {0}, endret til: {1}
	SolutionsEngineCopyPublic       = Kopier offentlig {0} til distribusjon
	SolutionsEngineCopyOpen         = Bla gjennom offentlig depot {0} plassering
	EnglineDoneReboot               = Start datamaskinen på nytt
	SolutionsTipsArm64              = Arm64-pakken foretrekkes, og du velger i rekkefølge: x64, x86.
	SolutionsTipsAMD64              = Foretrekk x64-pakker, i rekkefølge: x86.
	SolutionsTipsX86                = Bare x86-pakker legges til.
	SolutionsReport                 = Generer rapport før distribusjon
	SolutionsDeployOfficeInstall    = Distribuer installasjonspakken for Microsoft Office
	SolutionsDeployOfficeChange     = Endre distribusjonskonfigurasjonen
	SolutionsDeployOfficePre        = Forhåndsinstallert pakkeversjon
	SolutionsDeployOfficeNoSelect   = Ingen forhåndsinstallasjonspakke for Office er valgt
	SolutionsDeployOfficeVersion    = {0} versjon
	SolutionsDeployOfficeOnly       = Behold spesifiserte språkpakker
	SolutionsDeployOfficeSync       = Bevar språksynkronisering til distribusjonskonfigurasjon
	SolutionsDeployOfficeSyncTips   = Etter synkronisering kan ikke installasjonsskriptet bestemme det foretrukne språket.
	DeploySyncMainLanguage          = Synkroniser med hovedspråket
	SolutionsDeployOfficeTo         = Distribuer installasjonspakken til
	SolutionsDeployOfficeToPublic   = Offentlig skrivebord
	DeployPackage                   = Distribuer en tilpasset samlingspakke
	DeployPackageSelect             = Velg en forhåndshentingspakke
	DeployPackageTo                 = Distribuer forhåndssamlingspakken til
	DeployToRoot                    = Systemdisk
	DeployPackageToSolutions        = I løsningens hjemmekatalog
	DeployTimeZone                  = Tidssone
	DeployTimeZoneChange            = Endre tidssone
	DeployTimeZoneChangeTips        = Angi standard tidsområde der forhåndssvar skal besvares, etter språkområde.

	Deploy_Tags                     = Implementeringstag
	FirstExpProcess                 = Førstegangserfaring, under distribusjon, forutsetninger:
	FirstExpProcessTips             = Etter å ha fullført forutsetningene, start datamaskinen på nytt for å løse problemet med å kreve omstart for å tre i kraft.
	FirstExpFinish                  = Førstegangserfaring, etter å ha fullført forutsetninger
	FirstExpSyncMark                = Tillat globalt søk og synkronisering av distribusjonstagger
	FirstExpDefender                = Legg til hjemmekatalog til Forsvar ekskluderte kataloger
	FirstExpSyncLabel               = Systemdiskvolumetikett: Hjemmekatalognavnet er det samme
	MultipleLanguages               = Når du møter flere språk:
	NetworkLocationWizard           = Veiviser for nettverksplassering
	PreAppxCleanup                  = Blokker Appx opprydding vedlikeholdsoppgaver
	LanguageComponents              = Forhindre opprydding av ubrukte språkpakker for funksjoner på forespørsel
	PreventCleaningUnusedLP         = Forhindre rengjøring av ubrukte språkpakker
	FirstExpContextCustomize        = Legg til en personlig "kontekstmeny"
	FirstExpContextCustomizeShift   = Hold nede Shift-tasten og høyreklikk

	FirstExpFinishTips              = Det er ingen viktige hendelser etter at distribusjonen er fullført. Det anbefales at du avbryter.
	FirstExpFinishPopup             = Pop opp distribusjonsmotorens hovedgrensesnitt
	FirstExpFinishOnDemand          = Tillat første forhåndsvisning, som planlagt
	SolutionsEngineRestricted       = Gjenopprett Powershell-utførelsespolicy: begrenset
	EnglineDoneClearFull            = Slett hele løsningen
	EnglineDoneClear                = Slett distribusjonsmotoren og behold de andre

	Unattend_Auto_Fix_Next          = Neste gang du støter på det, velger du automatisk de nødvendige elementene for å fikse det automatisk.
	Unattend_Auto_Fix               = Reparer automatisk når forutsetninger ikke er valgt
	Unattend_Auto_Fix_Tips          = Når du legger til distribusjonsmotoren og ikke velger den første kjøringskommandoen, blir den automatisk reparert og valgt: Powershell-utførelsespolicy: kjør distribusjonsmotoren uten noen begrensninger.
	Unattend_Version_Tips           = Alternativt inkluderer kun, bruk standard for å støtte ARM64, x64, x86.
	First_Run_Commmand              = Kommandoer som skal kjøres når du distribuerer for første gang
	First_Run_Commmand_Setting      = Velg kommandoen som skal kjøres
	Command_Not_Class               = Ikke lenger automatisk kategorisert ved filtrering
	Command_WinSetup                = Windows installasjon
	Command_WinPE                   = Windows PE
	Command_Tips                    = Vennligst tilordne First Run-appen til: Windows Installation, Windows PE\n\nMerk at når en distribusjonsmotor legges til, må du sjekke følgende når du kjører for første gang: Powershell Execution Policy: Begrenset, tillat at distribusjonsmotorskript kjøres.
	Waring_Not_Select_Command       = Når du legger til en distribusjonsmotor, ble ikke Powershell-utførelsespolicyen valgt: Ikke angi noen begrensninger og la distribusjonsmotorskriptet kjøres. Velg det og prøv igjen, eller klikk på "Hurtigløsning er ikke valgt".
	Quic_Fix_Not_Select_Command     = Quick fix ikke alternativ

	PowerShell_Unrestricted         = Powershell-utførelsespolicy: ingen begrensninger
	Allow_Running_Deploy_Engine     = Tillat skript for distribusjonsmotor å kjøre
'@