ConvertFrom-StringData -StringData @'
	# nb-NO
	# Norwegian, Bokmål (Norway)

	UnpackISO                       = Generer ISO
	ISOLabel                        = Volumetikett er satt:
	ISOCustomize                    = ISO-volumetikettnavn
	ISO9660                         = Bekreft navneregler
	ISO9660Tips                     = Det unike navnet kan ikke overstige 260 tegn, ISO-volumnavnet kan ikke overstige 16 tegn, og kan ikke inneholde: innledende og etterfølgende mellomrom, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Egendefinert unik navngivning
	ISOAddFlagsLang                 = Legg til flerspråklig markering
	ISOAddFlagsLangGet              = Få kjente installasjonsspråk
	ISOAddFlagsVer                  = Legg til tag for flere versjoner
	ISOAddFlagsVerGet               = Få kjent bildeversjon
	ISOAddEICFG                     = Legg til versjonstype
	ISOAddEICFGTips                 = Når du stoler på EI.cfg, er det en kommersiell versjon.
	ISO9660TipsErrorSpace           = Kan ikke inneholde: førende og etterfølgende mellomrom
	ISO9660TipsErrorOther           = Kan ikke inneholde: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Velg språktype
	SelLabel                        = Kodenavn
	ISOVerLabel                     = Velg ISO-volumnavn
	NoSetLabel                      = Egendefinert ISO-volumetikett ikke angitt
	ISOLengthError                  = Volumetiketten kan ikke være lengre enn {0} tegn
	RenameFailed                    = Samme som gammel katalog, endre navn mislyktes
	ISOCreateAfter                  = Hva du må gjøre før du oppretter en ISO
	ISOCreateRear                   = Hva du trenger å gjøre etter å ha opprettet ISO
	BypassTPM                       = Omgå TPM-installasjonssjekk
	Disable_BitLocker               = Deaktiver BitLocker-enhetskryptering under installasjonen
	PublicDate                      = Utstedelsesdato
	PublicDateGetCurrent            = Synkroniser gjeldende dato
	PublicYear                      = År
	PublicMonth                     = Måne
	PublicYMSorting                 = Sortering: Endre "måned_år" til "år_måned"
	PublicYMSortingTips             = AB: Ikke legg til understrek _ når du bruker tall.
	PublicYMUseShortNames           = Bruk korte navn
	PublicYMUseNumbers              = Bruk tall
	ISOCreateFailed                 = Opprettelsen mislyktes, katalogen er ikke lesbar eller skrivbar.
	ISORefreshAuto                  = Oppdater ISO-tagger hver gang
	ISOSaveTo                       = ISO standard lagringssted
	ISOSaveSameGlobal               = Bruk global ISO standard lagringssted
	ISOSaveSync                     = Synkroniser automatisk den nye plasseringen etter å ha valgt bildekildesøkedisken
	ISOSaveSame                     = Søk diskbane ved hjelp av bildekilde
	ISOFolderWrite                  = Bekreft at katalogen er lesbar og skrivbar
	SelectAutoAvailable             = Når du automatisk velger en tilgjengelig disk
	SelectCheckAvailable            = Sjekk minimum tilgjengelig gjenværende plass
	ISOStructure                    = Ny katalogstruktur
	ISOOSLevel                      = Legg til installasjonstype
	ISOUniqueNameDirectory          = Legg til en unik navnekatalog
	NextDoOperate                   = Ikke lag ISO
	SelCreateISO                    = Generer ISO, utfør på forespørsel
	Reconstruction                  = Gjenoppbygg {0}.wim med maksimal komprimering
	Reconstruction_Tips_Select      = Før gjenoppbygging vil den bare bli utført når den ikke er lastet. Det vil tvinge lagringen til å bli aktivert og deretter avmontere den monterte filen.
	ReconstructionTips              = Over 520 MB, ombygging anbefales
	CreateASC                       = Legg til PGP-signatur til ISO
	NoPGPKey                        = Det finnes ingen brukbar privat nøkkel i PGP.
	CreateASCPwd                    = Sertifikatpassord
	PasswordRenter                  = Skriv inn passordet på nytt
	ShowPassword                    = Vis passord
	NewPasswordSome                 = Passordet samsvarer ikke.
	PwdPermanent                    = Permanent lagring
	PwdDecfailed                    = Dekryptering mislyktes
	CreateASCAuthor                 = Underskriver
	CreateASCAuthorTips             = Ingen underskrivere er valgt.
	ISO_Sparse_Rename               = Legg til hash i filnavnet
	GenerateRandom                  = Generer tilfeldige tall
	RandomNumberReset               = Regenerer
'@