ConvertFrom-StringData -StringData @'
	# pt-PT
	# Portuguese (Portugal)

	UnpackISO                       = Gerar ISO
	ISOLabel                        = O rótulo do volume foi definido:
	ISOCustomize                    = Nome do rótulo do volume ISO
	ISO9660                         = Verifique as regras de nomenclatura
	ISO9660Tips                     = O nome exclusivo não pode exceder 260 caracteres, o nome do volume ISO não pode exceder 16 caracteres e não pode conter: espaços à esquerda e à direita, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Nomenclatura exclusiva personalizada
	ISOAddFlagsLang                 = Adicionar marcação multilingue
	ISOAddFlagsLangGet              = Obtenha idiomas de instalação conhecidos
	ISOAddFlagsVer                  = Adicionar tag de várias versões
	ISOAddFlagsVerGet               = Obter a versão da imagem conhecida
	ISOAddEICFG                     = Adicionar tipo de versão
	ISOAddEICFGTips                 = Ao contar com o EI.cfg, é uma versão comercial.
	ISO9660TipsErrorSpace           = Não pode conter: espaços iniciais e finais
	ISO9660TipsErrorOther           = Não pode conter: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Selecione o tipo de idioma
	SelLabel                        = Codinome
	ISOVerLabel                     = Selecione o nome do volume ISO
	NoSetLabel                      = Rótulo de volume ISO personalizado não definido
	ISOLengthError                  = O rótulo do volume não pode ter mais de {0} caracteres
	RenameFailed                    = Igual ao diretório antigo, falha ao renomear
	ISOCreateAfter                  = O que precisa de fazer antes de criar uma ISO
	ISOCreateRear                   = O que precisa de fazer depois de criar o ISO
	BypassTPM                       = Ignorar a verificação de instalação do TPM
	Disable_BitLocker               = Desative a encriptação do dispositivo BitLocker durante a instalação
	PublicDate                      = Data de emissão
	PublicDateGetCurrent            = Sincronizar data atual
	PublicYear                      = Ano
	PublicMonth                     = Lua
	PublicYMSorting                 = Ordenar: Alterar "mês_ano" para "ano_mês"
	PublicYMSortingTips             = AB: Não adicionar o sublinhado _ quando se utilizam números.
	PublicYMUseShortNames           = Usar nomes curtos
	PublicYMUseNumbers              = Usar números
	ISOCreateFailed                 = Falha na criação, o diretório não é legível nem gravável.
	ISORefreshAuto                  = Atualize as etiquetas ISO sempre
	ISOSaveTo                       = Local de salvamento padrão ISO
	ISOSaveSameGlobal               = Utilize o local de gravação padrão ISO global
	ISOSaveSync                     = Sincronizar automaticamente o novo local após selecionar o disco de pesquisa de origem da imagem
	ISOSaveSame                     = Pesquise o caminho do disco utilizando a fonte da imagem
	ISOFolderWrite                  = Verifique se o diretório está legível e gravável
	SelectAutoAvailable             = Ao selecionar automaticamente um disco disponível
	SelectCheckAvailable            = Verifique o espaço restante mínimo disponível
	ISOStructure                    = Nova estrutura de diretórios
	ISOOSLevel                      = Adicionar tipo de instalação
	ISOUniqueNameDirectory          = Adicionar diretório de nome exclusivo
	NextDoOperate                   = Não crie ISO
	SelCreateISO                    = Gere ISO, execute sob demanda
	Reconstruction                  = Reconstruir {0}.wim com compressão máxima
	Reconstruction_Tips_Select      = Antes da reconstrução, só será executado quando não estiver carregado. Isto forçará a ativação do guardar e a desmontagem do ficheiro montado.
	ReconstructionTips              = Mais de 520 MB, reconstrução recomendada
	CreateASC                       = Adicionar assinatura PGP ao ISO
	NoPGPKey                        = Não existe uma chave privada utilizável no PGP.
	CreateASCPwd                    = Palavra-passe do certificado
	PasswordRenter                  = Introduza a senha novamente
	ShowPassword                    = Mostrar palavra-passe
	NewPasswordSome                 = A palavra-passe não coincide.
	PwdPermanent                    = Armazenamento permanente
	PwdDecfailed                    = Falha na desencriptação
	CreateASCAuthor                 = Signatário
	CreateASCAuthorTips             = Nenhum signatário selecionado.
	ISO_Sparse_Rename               = Adicione o símbolo de cerquilha (#) à extensão do nome do ficheiro
	GenerateRandom                  = Gerar números aleatórios
	RandomNumberReset               = Regenerado
'@