ConvertFrom-StringData -StringData @'
	# hu-HU
	# Hungarian (Hungary)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Műszerfal
	Learn                           = Tanulmány
	Menu                            = Menü
	Short_Cmd                       = Gyorsbillentyű parancsot
	Shortcut                        = Parancsikont
	Update                          = Megújítani
	CUpdate                         = Kumulatív frissítések
	Rebuild                         = Újjáépítés
	AddTo                           = Hozzáadás
	Del                             = Töröl
	Copy                            = Másolat
	Rename                          = Átnevezés
	Refresh                         = Frissíteni
	RefreshModules                  = Az összes modul gyors frissítése
	Done                            = Befejezés
	OK                              = Persze
	Cancel                          = Mégsem
	AllSel                          = Válassza ki az összeset
	AllClear                        = Mindent törölni
	Setting                         = Felállítani
	Change                          = Változás
	Help                            = Segítség
	Logging                         = Log
	AvailableLanguages              = Elérhető nyelvek
	SwitchLanguage                  = Nyelvet váltani
	LanguageSelRegion               = Válassza ki országát vagy régióját
	LanguageRemember                = Emlékezzen a kiválasztott nyelvre
	LanguageSearchNo                = Nem található elérhető nyelv
	LanguageNoPack                  = Ha nincs helyi nyelvi csomag, akkor az automatikusan kilép.
	LanguageNoSel                   = Kérjük, válasszon régiót
	Search                          = Keresés
	PleaseChoose                    = Kérem válasszon
	Options                         = Opciók
	Choose                          = Kiválasztott
	NoChoose                        = Nincs kiválasztva
	AdvOption                       = Választható funkciók
	ExcludeItem                     = Kizárás szabály szerint
	DeDuplication                   = Az ismétlődések kizárása
	DeDuplication_Unlock            = A letiltott ismétlődések feloldása
	Existed                         = Már létezik
	FailedCreateFolder              = Nem sikerült létrehozni a könyvtárat
	FailedCreateFile                = Nem sikerült létrehozni a fájlt
	ToMsg                           = {0} Másodpercek után automatikusan visszatér a főmenübe.
	OnDemandPlanTask                = Ismert események egyedi hozzárendelése
	Operable                        = Működtethető
	Inoperable                      = Működésképtelen
	Hide                            = Elrejt
	CuringUpdate                    = Szilárd frissítés
	CuringUpdateTips                = Miután a frissítés megszilárdult, nem távolítható el.
	Healthy                         = Egészséges
	HealthyTips                     = Különösen fontos az állapot ellenőrzése, amikor megjelenik a "javítható" vagy a "javíthatatlan" üzenet: Az ESD átalakítási folyamat során a rendszer a 13-as hibát jelzi, és a rendszer telepítésekor hibát jelez.
	Healthy_Save                    = Ha javítható vagy javíthatatlan jelenik meg, ne mentse el.
	Repair                          = Javítás
	IsAuto_Repair                   = Engedélyezze az automatikus javítást üresjáratban
	IsAuto_Repair_Tips              = A csomagoló szkript minden egyes futtatása után automatikusan ellenőrizze, hogy vannak-e beszerelési feladatok. Ha fel van szerelve, akkor nem történik javítás, ha nincs felszerelve, akkor az automatikus javítás fut.
	Repairable                      = Javítható
	NonRepairable                   = Nem javítható
	HealthyForceStop                = Az esemény feldolgozása során visszafordíthatatlan hiba lépett fel, és az eseményt erőszakkal megszakították.\n\n   Fő problémákat okoz:\n\n      1. Fizikai hardver sérült, merevlemez;\n\n      2. Ha RAMDISK memória virtuális lemezt használ (beleértve a hibridet is), ellenőrizze a fizikai memóriát;\n\n      3. Ellenőrizze az MVS (MSDN) eredeti SHA256-át, ha konzisztens, módosítsa a könyvtárat, és próbálja újra.\n\n      4. Mások nem szerepelnek ebben a példában.
	Superseded                      = Tisztítsa meg a cserélt
	SupersededTips                  = Tartalmazza az elavult frissítéseket, összetevőket stb.
	UnmountFailed                   = Több módszert is kipróbáltam, de semmit sem tudok tenni, csak annyit, hogy legközelebb találkozunk.
	SaveTo                          = Mentse ide
	WorkDone                        = Befejezve, nyomja meg bármelyik gombot, hogy visszatérjen a fő felületre...
	UserCanel                       = A felhasználó visszavonta a kérést.
	Uping                           = Generálás
	Exclude_View                    = Kizárási szabályok megtekintése
	User_Interaction                = Felhasználói interakció
	Ok_Go_To                        = Elérhető
	Ok_Go_To_No                     = Nem megy

	Detailed                        = Részletes
	Detailed_View                   = A kiválasztott szabály részleteinek megtekintése

	AddEnv                          = Adjon hozzá útválasztási funkciókat a rendszerváltozókhoz
	AddEnvTips                      = Hozzáadás után írja be az Yi értéket bármelyik PowerShell-munkamenetbe, hogy válaszoljon. Például a beágyazás futtatásához írja be a "Yi -SIP" parancsot.

	Unzip_ISO                       = ISO kibontása
	Unzip_Search_Type               = Keresés a könyvtárban ( {0} )
	ISO_Other                       = Egyéb dokumentumok
	Unzip_Language                  = Nyelvi csomag
	Unzip_Fod                       = Funkciócsomag
	FileName                        = Fájlnév

	UserCancel                      = A felhasználó megszakította a műveletet.
	MatchMode                       = Mérkőzés
	Failed                          = Nem sikerül
	RandomSelect                    = Véletlenszerűen kiválasztott
	RulePre                         = Előre beállított szabályok
	RuleOther                       = Egyéb szabályok
	RuleCustomize                   = Egyedi szabályok
	RuleCustomize_Dont              = Ne használjon többszintű címtár egyéni szabályokat
	RuleCustomize_Dont_Tips         = A régi könyvtár törlése után kattintson az "Elnevezési szabályok ellenőrzése" gombra.
	RuleMultistage                  = Többszintű címtárszabályok
	RuleMultistageFindFailed        = Nem található többszintű címtárszabály. Kattintson rám a sablon létrehozásához.
	RuleMultistageFindCreateNew     = Hozzon létre egy új többszintű címtárszabály-sablont
	RuleMultistageTips              = A többszintű címtárszabályok automatikus adaptálása, a(z) {0} címtárszabály letiltva.
	RuleCustomizeNot                = A bővítmény neve (Solutions.Custom.Extension) nem található, kérjük, tekintse meg a súgódokumentációt.
	RuleCustomizeTips               = Nem jött létre egyéni szabály, kérjük, tekintse meg a súgódokumentációt.
	RuleMatchNoFindFolder           = Nem sikerült megegyezni a könyvtárral, kattintson rám a könyvtár létrehozásához.
	RuleNoFindFile                  = Nem található elérhető fájl. Kérjük, adja hozzá és frissítse.
	RuleFindFolder                  = A könyvtár automatikusan kiválasztódik, ha elérhető
	RuleNameNewChange               = Automatikus szinkronizálás a frissítések után
	RuleNewTempate                  = Sablon létrehozása
	RuleSkipFolderCheck             = A továbbiakban nem ellenőrzi, hogy a fájl létezik-e a könyvtárban és a fájltípust
	RuleAuthon                      = Szabályalkotó
	RuleGUID                        = GUID globálisan egyedi azonosító
	RuleName                        = Szabály neve
	RuleDescription                 = Leírni
	RuleNameUse                     = Szabálynév szinkronizálása a következővel: {0}
	RuleISO                         = Illessze az eredeti ISO telepítőcsomagot
	RuleInBoxApps                   = Komplett, előre konfigurált alkalmazás
	RuleFileType                    = Csomag neve
	RuleFileFind                    = Homályos keresési név
	RuleFindError                   = {0} feldolgozásra váró elemet talált. A részletek megtekintéséhez kattintson a "Függőségek ellenőrzése" gombra.
	RuleSelectApps                  = A felhasználó által kiválasztott alkalmazások
	DependencyPackage               = Függőségi csomag
	RuleDependenciesRequired        = Szükséges függőségek
	RuleDependenciesUnselected      = Kijelöletlen függőségek
	RuleDependenciesNoCheck         = A függőségeket már nem ellenőrzik
	RuleDependenciesFix             = A nem kiválasztott függőségek javítása
	Extract_Tips                    = Célzás\n\n   1. A nyelvi csomag kibontása után kapott eredmény nem használható fő hivatkozási objektumként;\n\n   2. Kérjük, használja a komponenslistát fő hivatkozási objektumként Hogyan készítsünk:\n\n       A Funkcióknál válassza az Összetevő generálása lehetőséget (a csomag lekérése a telepített képfájlban), majd válassza a Nyomtatás vagy az Azonnali megtekintés lehetőséget;\n\n   3. A nyelvi csomag telepítése után generáljon újra egy komponens jelentést, hogy ellenőrizze, megfelel-e;

	DescendingRuleLang              = Távolítsa el a nyelvi csomagokat fordított sorrendben
	OrderRuleLang                   = Telepítse a nyelvi csomagokat előre meghatározott sorrendben
	OrderRuleLangTips               = Hozzáadás sorrendben: Alapszintű, Betűtípusok, Optikai karakterfelismerés, Kézírás-felismerés, Szövegfelolvasó, Beszédfelismerés, Kiskereskedelmi bemutató élmény, Egyéb
	RuleLanguageTips                = Szemléltet:\n\n   A "Nyelvcsomagok telepítése előre meghatározott sorrendben" használata után a fájlokat a rendszer automatikusan homályos nevekkel párosítja a következő sorrendben:\n
	Match_installed_List            = Nyelvi csomag telepítésekor helyettesítő karakterrel írja be a telepített listából
	Match_installed_List_Tips       = Csak telepített állapotban egyezik: Alapszintű, Optikai karakterfelismerés, Kézírás-felismerés, Szövegfelolvasó, Beszédfelismerés.
	RuleLanguageTipsExt             = \n   Ha nem használja a "Nyelvcsomagok telepítése előre meghatározott sorrendben" funkciót: \n   Automatikusan megkeresi az összes fájlt a könyvtárban fájltípus szerint, és telepíti őket.\n\n   Nyelvi és régió igény szerinti funkciók (FOD)\n   https://learn.microsoft.com/hu-hu/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategória
	Basic                           = Alapvető
	Fonts                           = Betűtípus
	OCR                             = Optikai karakterfelismerés
	Handwriting                     = Kézírás felismerés
	TextToSpeech                    = Szöveget beszédté
	Speech                          = Beszédfelismerés
	Retail                          = Kiskereskedelmi bemutató élmény
	Features_On_Demand              = Funkciók igény szerint
	RegionSpecific                  = Egyéb régióspecifikus követelmények
	UnassignedLangFiles             = Hozzá nem rendelt különféle fájlok

	ProcessingImage                 = A kép feldolgozása:
	NoInstallImage                  = Helyben nem létezik
	ConvertChk                      = Ellenőrizze a fájlt
	WindowsFeature                  = Windows funkciók
	Enable                          = Engedélyezze
	Disable                         = Letiltás
	EnableFeatureTips               = Célzás\n\n    1. A NetFx3 és a TelnetClient megjelenítése előre beállított engedélyezett funkcióelemként;\n\n    2. "Felszerelés" után több is engedélyezhető.
	ViewLanguage                    = A kép nyelvi beállításainak megtekintése
	ImageLanguage                   = Kép nyelvi beállításai
	OnlyLangCleanup                 = Tiszta alkatrészek: címkézés nyelv szerint
	Matched_Component_Names         = Egyező komponens neve:
	BootProcess                     = A {0}.wim
	Sync_Language_To                = Szinkronizálás a következővel:
	BootSyncToISO                   = Szinkronizálja a nyelvi csomagokat a telepítővel
	BootSyncToISOTips               = Az offline kép telepített nyelvi csomagja szinkronizálva van az ISO telepítővel.
	LangIni                         = A Lang.ini újragenerálása
	LangIniTips                     = A szinkronizálás befejezése után az ISO Lang.ini fájlját újra kell építeni.
	LangNewAutoSelect               = A javasolt elemek automatikus kiválasztása esemény bekövetkezésekor
	LangNewAutoSelectTips           = Új események vannak, a "Nyelvcsomag szinkronizálása a telepítővel", a "Lang.ini újraépítése" kiválasztva.
	LangNewAutoNoSelect             = Új események vannak, javasoljuk, hogy válassza ki a "Nyelvcsomag szinkronizálása a telepítővel" és a "Lang.ini újraépítése" lehetőséget.
	LangNewAutoNoNewSelect          = Nincsenek új események. Javasoljuk, hogy ne válassza a "Nyelvcsomag szinkronizálása a telepítővel" vagy a "Lang.ini újraépítése" lehetőséget.
	Drive                           = Hajtás
	ViewDrive                       = Telepített illesztőprogramok megtekintése
	EditionsProductKey              = Termékkulcs
	Editions                        = Képes verzió
	Assign_Editions                 = Alkalmazások automatikus terjesztése képverziók alapján
	EditionsChangeTips              = Figyelem! Kérjük, értse meg, mielőtt képverziót váltana: \n\nMicrosoft Szolgáltatási szerződés\nhttps://www.microsoft.com/hu-hu/servicesagreement/default.aspx\n\nNyelvi áttekintés\nhttps://learn.microsoft.com/hu-hu/windows-hardware/manufacture/desktop/languages-overview\n\nNem készíthet verziókat: \n   1. Országspecifikus\n       ProfessionalCountrySpecific\n\n   2. Régióspecifikus otthoni verzió\n       ProfessionalSingleLanguage\n\nKérjük, szigorúan tartsa be, mert megsértése esetén büntetőeljárás indulhat ellene.\n\nHa ragaszkodik az átalakításhoz, kattintson a gombra a figyelmeztetés elfogadásához, majd kattintson a "Rejtett kép verziójának feloldása" gombra.
	EditionsChangeHide              = Oldja fel a rejtett képverziókat
	EditionsChangeAccect            = A figyelmeztetést elolvastam, és felelősséget vállalok a figyelmeztetésben foglalt vonatkozó jogszabályokért

	SelFile                         = Válassza ki a fájlt
	Rebuilding                      = Rekonstrukció alatt
	RebuildAll                      = Építsd újra az összeset
	Export_Image                    = Export
	SelectFromError                 = Hiba
	SelectFileFormatError           = A fájl formátuma nem megfelelő

	SearchDrive                     = Keresés vezérelte
	SearchUpdate                    = Frissítések keresése, típus ( {0} ), forrás:
	SelectFolder                    = Válassza ki a könyvtárat
	DropFolder                      = Könyvtárakat húzhat az aktuális ablakba
	DropFile                        = A fájlok áthúzhatók az aktuális ablakba
	Sparse                          = Ritka
	CRCSHA                          = Ellenőrzés
	Alternative                     = Alternatív fájlnév
	ChangeInstallDisk               = Az automatikus lemezkiválasztás módosítása

	# View
	ExportToLogs                    = Jelentés nyomtatása a naplóhoz
	ExportShow                      = Jelentések azonnali megjelenítése
	MoreFeature                     = További funkciók
	OpenFolder                      = Nyissa meg a könyvtárat
	OpenFile                        = Fájl megnyitása
	Running                         = Fut
	Paste                           = Útvonal másolása
	Clipboard_Copy                  = Vágólapra másolva
	ViewWIMFileInfo                 = Kép megtekintése
	GetInBoxApps                    = InBox Apps: Telepített alkalmazáscsomagok
	GetImagePackage                 = Összetevők: A képbe telepített összes csomag
	ViewMounted                     = Információkat kaphat az összes csatlakoztatott képről
'@