ConvertFrom-StringData -StringData @'
	# fr-FR
	# French (France)

	UnpackISO                       = Générer un ISO
	ISOLabel                        = L'étiquette de volume a été définie:
	ISOCustomize                    = Nom du label de volume ISO
	ISO9660                         = Vérifier les règles de dénomination
	ISO9660Tips                     = Le nom unique ne peut pas dépasser 260 caractères, le nom du volume ISO ne peut pas dépasser 16 caractères et ne peut pas contenir: des espaces de début et de fin, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Dénomination unique personnalisée
	ISOAddFlagsLang                 = Ajouter un balisage multilingue
	ISOAddFlagsLangGet              = Obtenez des langues d'installation connues
	ISOAddFlagsVer                  = Ajouter une balise multiversion
	ISOAddFlagsVerGet               = Obtenir une version d'image connue
	ISOAddEICFG                     = Ajouter un type de version
	ISOAddEICFGTips                 = Lorsque l'on s'appuie sur EI.cfg, il s'agit d'une version commerciale.
	ISO9660TipsErrorSpace           = Ne peut pas contenir: des espaces de début et de fin
	ISO9660TipsErrorOther           = Ne peut pas contenir: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Sélectionnez le type de langue
	SelLabel                        = Nom de code
	ISOVerLabel                     = Sélectionnez le nom du volume ISO
	NoSetLabel                      = Étiquette de volume ISO personnalisée non définie
	ISOLengthError                  = Le libellé du volume ne peut pas comporter plus de {0} caractères
	RenameFailed                    = Identique à l'ancien répertoire, le changement de nom a échoué
	ISOCreateAfter                  = Ce que vous devez faire avant de créer un ISO
	ISOCreateRear                   = Ce que vous devez faire après avoir créé l'ISO
	BypassTPM                       = Contourner la vérification de l'installation du TPM
	Disable_BitLocker               = Désactiver le chiffrement de l'appareil BitLocker pendant l'installation
	PublicDate                      = Date d'émission
	PublicDateGetCurrent            = Synchroniser la date actuelle
	PublicYear                      = Année
	PublicMonth                     = Lune
	PublicYMSorting                 = Tri: Remplacez "mois_année" par "année_mois".
	PublicYMSortingTips             = AB: N'ajoutez pas de trait de soulignement _ avec les nombres.
	PublicYMUseShortNames           = Utilisez des noms courts
	PublicYMUseNumbers              = Utilisez des nombres
	ISOCreateFailed                 = La création a échoué, le répertoire n'est ni lisible ni inscriptible.
	ISORefreshAuto                  = Actualiser les balises ISO à chaque fois
	ISOSaveTo                       = Emplacement de sauvegarde ISO par défaut
	ISOSaveSameGlobal               = Utiliser l'emplacement de sauvegarde ISO global par défaut
	ISOSaveSync                     = Synchronisez automatiquement le nouvel emplacement après avoir sélectionné le disque de recherche de source d'image
	ISOSaveSame                     = Rechercher le chemin du disque à l'aide de la source de l'image
	ISOFolderWrite                  = Vérifier que le répertoire est lisible et accessible en écriture
	SelectAutoAvailable             = Lors de la sélection automatique d'un disque disponible
	SelectCheckAvailable            = Vérifiez l'espace restant minimum disponible
	ISOStructure                    = Nouvelle structure de répertoires
	ISOOSLevel                      = Ajouter un type d'installation
	ISOUniqueNameDirectory          = Ajouter un répertoire de noms uniques
	NextDoOperate                   = Ne pas créer d'ISO
	SelCreateISO                    = Générez des ISO, exécutez à la demande
	Reconstruction                  = Reconstruire {0}.wim avec une compression maximale
	Reconstruction_Tips_Select      = Avant la reconstruction, il ne sera exécuté que lorsqu'il n'est pas chargé. Il forcera l'activation de la sauvegarde puis démontera le fichier monté.
	ReconstructionTips              = Plus de 520 Mo, reconstruction recommandée
	CreateASC                       = Ajouter la signature PGP à l'ISO
	NoPGPKey                        = Il n'existe pas de clé privée utilisable dans PGP.
	CreateASCPwd                    = Mot de passe du certificat
	PasswordRenter                  = Confirmer le mot de passe
	ShowPassword                    = Afficher le mot de passe
	NewPasswordSome                 = Le mot de passe est incorrect.
	PwdPermanent                    = Stockage permanent
	PwdDecfailed                    = Échec du déchiffrement
	CreateASCAuthor                 = Signataire
	CreateASCAuthorTips             = Aucun signataire sélectionné.
	ISO_Sparse_Rename               = Ajouter un hachage à l'extension du nom de fichier
	GenerateRandom                  = Générer des nombres aléatoires
	RandomNumberReset               = Régénérer
'@