ConvertFrom-StringData -StringData @'
	# lv-LV
	# Latvian (Latvia)

	Main_quests                     = Galvenie uzdevumi
	Side_quests                     = Apakšuzdevumi
	SaveModeClear                   = Notīrīt atlasīto vēsturi
	SaveModeTipsClear               = Vēsture ir saglabāta, un to var notīrīt
	SelectTips                      = Mājienu\n\n    1. Lūdzu, izvēlieties apstrādājamā attēla nosaukumu;\n    2. Pēc atcelšanas uzdevumi, kuru darbībai nepieciešama "montāža", vairs nespēs darboties.
	CacheDisk                       = Diska kešatmiņa
	CacheDiskCustomize              = Pielāgots kešatmiņas ceļš
	AutoSelectRAMDISK               = Atļaut automātisku diska sējuma etiķetes atlasi
	AutoSelectRAMDISKFailed         = Sējuma etiķete neatbilst
	ReFS_Find_Volume                = Ja tiek konstatēts diska formāts REFS, izslēdziet
	ReFS_Exclude                    = ReFS nodalījums izslēgts
	Disk_Not_satisfied_Exclude      = Nav izpildītas minimālās diska prasības
	RAMDISK_Change                  = Mainiet sējuma etiķetes nosaukumu
	RAMDISK_Search                  = Meklēt sējuma etiķetes nosaukumu
	RAMDISK_Restore                 = Atjaunot inicializēto sējuma nosaukumu: {0}
	AllowTopMost                    = Atļaut atvērtos logus piespraust augšpusē
	History                         = Skaidra vēsture
	History_Del_Tips                = Ja ir iekapsulēšanas uzdevums, neizpildiet tālāk norādītās izvēles opcijas, pretējā gadījumā iekapsulēšanas skripta darbības laikā tas radīs nezināmas problēmas.
	History_View                    = Skatīt vēsturi
	HistoryLog                      = Atļaut automātisku baļķu tīrīšanu, kas vecāki par 7 dienām
	HistorySaveFolder               = Citi attēlu avota ceļi
	HistoryClearappxStage           = InBox Apps: izdzēsiet pagaidu failus, kas ģenerēti instalēšanas laikā
	DoNotCheckBoot                  = Ja faila Boot.wim izmērs pārsniedz 520 MB, ģenerējot ISO, automātiski tiek atlasīta pārbūve.
	HistoryClearDismSave            = Dzēsiet reģistrā saglabātos DISM montāžas ierakstus
	ImageSourcesClickShowKey        = Atļaut izvēlnes "Atlasīt primāro atslēgu" attēlošanu
	ImageSourcesClickShowKeyTips    = Pēc tam, kad lietotājs ir atlasījis attēla avotu: labajā pusē pievienojiet izvēlni "Atlasīt primāro atslēgu" un pievienojiet opcijas "Doties uz": Pievienošana, Saglabāšana, Uznirstošais logs.
	Clear_Bad_Mount                 = Dzēsiet visus resursus, kas saistīti ar bojāto pievienoto attēlu
	ShowCommand                     = Parādiet visu komandrindas palaišanu
	Command                         = Komandrinda
	SelectSettingImage              = Attēla avots
	NoSelectImageSource             = Nav atlasīts neviens attēla avots
	SettingImageRestore             = Atjaunot noklusējuma stiprinājuma vietu
	SettingImage                    = Mainiet attēla avota stiprinājuma vietu
	SelectImageMountStatus          = Iegūstiet stiprinājuma statusu pēc attēla avota izvēles
	SettingImageTempFolder          = Pagaidu direktorijs
	SettingImageToTemp              = Pagaidu direktorijs ir tāds pats kā vieta, kur tas tika pievienots
	SettingImagePathTemp            = Izmantojot Temp direktoriju
	SettingImageLow                 = Pārbaudiet minimālo pieejamo vietu
	SettingImageNewPath             = Izvēlieties montāžas disku
	SettingImageNewPathTips         = Ieteicams to pievienot atmiņas diskā, kas ir ātrākais. Varat izmantot virtuālās atmiņas programmatūru, piemēram, Ultra RAMDisk un ImDisk.
	SelectImageSource               = Ir atlasīts "Izvietot dzinēja risinājumu", noklikšķiniet uz Labi.
	NoImagePreSource                = Nav atrasts neviens pieejams avots, jums vajadzētu:\n\n     1. Pievienojiet citus attēlu avotus: \n          {0}\n\n     2. Izvēlieties "Iestatījumi" un atkārtoti atlasiet attēla avota meklēšanas disku;\n\n     3. Atlasiet "ISO" un atlasiet ISO, kas jāsaspiež, uzstādāmos vienumus utt.
	NoImageOtherSource              = Noklikšķiniet uz manis, lai "Pievienot" citus ceļus vai "Velciet direktoriju" uz pašreizējo logu.
	SearchImageSource               = Attēla avota meklēšanas disks
	Kernel                          = Kodols
	Architecture                    = Arhitektūra
	ArchitecturePack                = Pakotņu arhitektūra, pievienošanas noteikumu izpratne
	ImageLevel                      = Uzstādīšanas veids
	LevelDesktop                    = Darbvirsma
	LevelServer                     = Serveris
	ImageCodename                   = Koda nosaukums
	ImageCodenameNo                 = Nav atpazīts
	MainImageFolder                 = Mājas direktorijs
	MountImageTo                    = Piestiprināt pie
	Image_Path                      = Attēla ceļš
	MountedIndex                    = Rādītājs
	MountedIndexSelect              = Izvēlieties indeksa numuru
	AutoSelectIndexFailed           = Automātiskā indeksa {0} atlase neizdevās. Lūdzu, mēģiniet vēlreiz.
	Apply                           = Pieteikumu
	Eject                           = Uznirst
	Mount                           = Mount
	ReMount                         = Pārmonterēt
	Unmount                         = Atinstalēt
	Mounted                         = Uzmontēts
	NotMounted                      = Nav uzstādīts
	NotMountedSpecify               = Nav uzstādīts, jūs varat norādīt montāžas vietu
	MountedIndexError               = Nepareiza montāža, izdzēsiet un mēģiniet vēlreiz.
	NeedsRemount                    = Nepieciešama atkārtota uzstādīšana
	Invalid                         = Nederīgs
	ImageSouresNoSelect             = Rādīt sīkāku informāciju pēc attēla avota izvēles
	Mounted_Mode                    = Montāžas režīms
	Mounted_Status                  = Montāžas statuss
	Status                          = Statuss
	Image_Popup_Default             = Saglabāt kā noklusējumu
	Image_Restore_Default           = Atgriezties uz noklusējuma vērtību
	Image_Popup_Tips                = Mājiens:\n\nPiešķirot notikumu, jūs nenorādījāt indeksa numuru, kas jāapstrādā {0};\n\nAtlases interfeiss pašlaik ir parādīts. Lūdzu, norādiet indeksa numuru.
	Rule_Show_Full                  = Rādīt visu
	Rule_Show_Only                  = Rādīt tikai noteikumus
	Rule_Show_Only_Select           = Izvēlieties no noteikumiem
	Image_Unmount_After             = Atinstalējiet visus uzstādītos

	Wim_Rule_Update                 = Izņemiet un atjauniniet failus attēlā
	Wim_Rule_Extract                = Izvilkt failus
	Wim_Rule_Extract_Tips           = Pēc ceļa noteikuma izvēles izvelciet norādīto failu un saglabājiet to lokāli.

	Wim_Rule_Verify                 = Pārbaudīt
	Wim_Rule_Check                  = Pārbaudīt
	Wim_Rule_CheckIntegrity         = Sjekk integritet
	Wim_Rule_ReadOnly               = Tikai lasīšanas atļauja
	Wim_Rule_Optimize               = Optimizācija
	ResetBase                       = Dziļā tīrīšana
	Wim_Rule_SupportEa              = Lietot attēlus ar paplašinātiem atribūtiem
	Wim_Rule_WIMBoot                = Oppstartbar
	Wim_Rule_Compact                = Komprimer operativsystemfiler
	Win_Rule_Setbootable            = Merk volumbilde som oppstartbar
	Win_Rule_Setbootable_Tips       = Denne parameteren gjelder bare for Windows PE-bilder.\nBare ett volumbilde kan merkes som oppstartbart i en .wim-fil.
	Destination                     = Galamērķis

	Wim_Append                      = Legg til
	Wim_Capture                     = Hent
	Wim_Capture_Tips                = Hent stasjonsbildet til en ny WIM-fil.
	Wim_Capture_Sources             = Hent kilde
	Wim_Capture_Sources_Tips        = Den hentede katalogen inneholder alle undermapper og data.\nDu kan ikke hente en tom katalog. Katalogen må inneholde minst én fil.
	Wim_Config_File                 = Konfigurasjonsfilbane ( unntak )
	Wim_Config_Edit                 = Rediger
	Wim_Config_Learn                = Studer konfigurasjonslisten og WimScript.ini-filen

	Wim_Rename                      = Mainiet attēla informāciju
	Wim_Image_Name                  = Attēla nosaukums
	Wim_Image_Description           = Attēla apraksts
	Wim_Display_Name                = Parādāmais vārds
	Wim_Display_Description         = Parādīt aprakstu
	Wim_Edition                     = Attēla zīme
	Wim_Edition_Select_Know         = Atlasiet zināmos attēlu karogus
	Wim_CreatedTime                 = Izveidošanas datums
	Wim_ModifiedTime                = Pēdējās modificēšanas laiks
	Wim_FileCount                   = Failu skaits
	Wim_DirectoryCount              = Direktoriju skaits
	Wim_Expander_Space              = Izplešanās telpa

	IABSelectNo                     = Primārā atslēga nav atlasīta: Install, WinRE, Boot
	Unique_Name                     = Unikāls nosaukums
	Select_Path                     = Ceļš
	Setting_Pri_Key                 = Iestatiet šo atjaunināšanas failu kā galveno veidni
	Pri_Key_Update_To               = Pēc tam atjauniniet uz
	Pri_Key_Template                = Iestatiet šo failu kā vēlamo veidni, kas jāsinhronizē ar atlasītajiem vienumiem
	Pri_key_Running                 = Primārās atslēgas uzdevums ir sinhronizēts un ir izlaists.
	ShowAllExclude                  = Rādīt visus novecojušos izņēmumus

	Index_Process_All               = Apstrādājiet visus zināmos indeksa numurus
	Index_Is_Event_Select           = Kad ir notikums, tiek parādīts indeksa numura atlases interfeiss.
	Index_Pre_Select                = Iepriekš piešķirts indeksa numurs
	Index_Select_Tips               = Mājiens:\n\n{0}.wim pašlaik nav uzstādīts, jūs varat:\n\n   1. Izvēlieties "Apstrādāt visus zināmos indeksa numurus";\n\n   2. Izvēlieties "Kad ir notikums, tiks parādīts indeksa numura atlases interfeiss";\n\n   3. Iepriekš noteikts indeksa numurs\n      Ir norādīts indeksa numurs 6, indeksa numurs apstrādes laikā nepastāv, un apstrāde tiek izlaista.

	Index_Tips_Custom_Expand        = Grupa: {0}\n\nApstrādājot {1}, ir jāpiešķir indeksa numurs {2}, pretējā gadījumā to nevar apstrādāt.\n\nPēc atlases "Sinhronizēt atjaunināšanas noteikumus ar visiem indeksa numuriem", jums tikai jāatzīmē jebkura kā galvenā veidne.

	DefenderExclude                 = Windows antivīrusu izņēmumi
	DefenderFolder                  = Pievienot šo direktoriju Windows antivīrusu izņēmumu sarakstam.
	DefenderVolume                  = Pēc atbilstoša sējuma etiķetes nosaukuma atrašanas pievienojiet šo disku Windows antivīrusu izņēmumu sarakstam.
	DefenderIsAdd                   = Pievienots Windows antivīrusu izņēmumu sarakstam
'@