ConvertFrom-StringData -StringData @'
	# nb-NO
	# Norwegian, Bokmål (Norway)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Dashbord
	Learn                           = Studere
	Menu                            = Meny
	Short_Cmd                       = Snarveiskommando
	Shortcut                        = Snarvei
	Update                          = Fornye
	CUpdate                         = Kumulative oppdateringer
	Rebuild                         = Gjenoppbygging
	AddTo                           = Legg til
	Del                             = Slette
	Copy                            = Kopiere
	Rename                          = Gi nytt navn
	Refresh                         = Forfriske
	RefreshModules                  = Varm oppdater alle moduler
	Done                            = Fullfør
	OK                              = Sikker
	Cancel                          = Kansellere
	AllSel                          = Velg alle
	AllClear                        = Fjern alt
	Setting                         = Sette opp
	Change                          = Endre
	Help                            = Hjelp
	Logging                         = Logg
	AvailableLanguages              = Tilgjengelige språk
	SwitchLanguage                  = Bytte språk
	LanguageSelRegion               = Velg ditt land eller din region
	LanguageRemember                = Husk valgt språk
	LanguageSearchNo                = Ingen tilgjengelige språk funnet
	LanguageNoPack                  = Hvis det ikke er noen språkpakke lokalt, avsluttes den automatisk.
	LanguageNoSel                   = Vennligst velg en region
	Search                          = Søk
	PleaseChoose                    = Vennligst velg
	Options                         = Alternativer
	Choose                          = Valgt
	NoChoose                        = Ikke valgt
	AdvOption                       = Valgfrie funksjoner
	ExcludeItem                     = Ekskluder etter regel
	DeDuplication                   = Ekskluder duplikater
	DeDuplication_Unlock            = Lås opp deaktiverte duplikater
	Existed                         = Eksisterer allerede
	FailedCreateFolder              = Kunne ikke opprette katalog
	FailedCreateFile                = Kunne ikke opprette filen
	ToMsg                           = {0} Gå automatisk tilbake til hovedmenyen etter sekunder.
	OnDemandPlanTask                = Egendefinert tilordning av kjente hendelser
	Operable                        = Brukbar
	Inoperable                      = Ubrukelig
	Hide                            = Gjemme
	CuringUpdate                    = Solid oppdatering
	CuringUpdateTips                = Når oppdateringen er størknet, kan den ikke avinstalleres.
	Healthy                         = Sunn
	HealthyTips                     = Det er spesielt viktig å sjekke helsestatusen Når "reparerbar" eller "unrepairable" vises: Under ESD-konverteringsprosessen blir feil 13 spurt, og dataene er ugyldige når systemet installeres.
	Healthy_Save                    = Når reparerbare eller uopprettelige vises, ikke lagre.
	Repair                          = Reparere
	IsAuto_Repair                   = Tillat automatisk reparasjon ved tomgang
	IsAuto_Repair_Tips              = Sjekk automatisk om det er noen monteringsoppgaver etter hver kjøring av pakkeskriptet. Hvis den er montert, vil ingen reparasjon bli utført hvis den ikke er montert, vil automatisk reparasjon bli utført.
	Repairable                      = Reparerbar
	NonRepairable                   = Kan ikke repareres
	HealthyForceStop                = Under behandlingen av hendelsen ble det oppdaget en irreversibel feil og hendelsen ble tvangsavbrutt.\n\n   Forårsaker hovedproblemer: \n\n      1. Fysisk maskinvare er skadet, harddisk;\n\n      2. Hvis du bruker virtuell disk med RAMDISK-minne (inkludert hybrid), vennligst sjekk det fysiske minnet;\n\n      3. Bekreft den originale SHA256 av MVS (MSDN) Hvis den er konsistent, vennligst endre katalogen og prøv igjen Hvis SHA256 er inkonsekvent, last den ned igjen og prøv igjen.\n\n      4. Andre er ikke oppført i dette eksemplet.
	Superseded                      = Rydd opp i den utskiftede
	SupersededTips                  = Inkluderer utdaterte oppdateringer, komponenter osv.
	UnmountFailed                   = Jeg har prøvd flere metoder, men ingenting kan gjøres. Jeg kan bare slutte å se deg neste gang.
	SaveTo                          = Lagre til
	WorkDone                        = Fullført, trykk på en tast for å gå tilbake til hovedgrensesnittet...
	UserCanel                       = Brukeren har kansellert forespørselen.
	Uping                           = Genererer
	Exclude_View                    = Se ekskluderingsregler
	User_Interaction                = Brukerinteraksjon
	Ok_Go_To                        = Tilgjengelig for
	Ok_Go_To_No                     = Går ikke

	Detailed                        = Detaljert
	Detailed_View                   = Se valgte regeldetaljer

	AddEnv                          = Legg til rutingfunksjonalitet til systemvariabler
	AddEnvTips                      = Etter å ha lagt til, skriv inn Yi i en hvilken som helst PowerShell-økt for å svare For eksempel, skriv inn "Yi -SIP" for å kjøre innkapslingen.

	Unzip_ISO                       = Pakk ut ISO
	Unzip_Search_Type               = Søk i katalogen ( {0} )
	ISO_Other                       = Andre dokumenter
	Unzip_Language                  = Språkpakke
	Unzip_Fod                       = Funksjonspakke
	FileName                        = Filnavn

	UserCancel                      = Brukeren har avbrutt operasjonen.
	MatchMode                       = Kamp
	Failed                          = Mislykkes
	RandomSelect                    = Tilfeldig valgt
	RulePre                         = Forhåndsinnstilte regler
	RuleOther                       = Andre regler
	RuleCustomize                   = Egendefinerte regler
	RuleCustomize_Dont              = Ikke bruk tilpassede katalogregler på flere nivåer
	RuleCustomize_Dont_Tips         = Etter å ha slettet den gamle katalogen, klikk "Bekreft navneregler."
	RuleMultistage                  = Katalogregler på flere nivåer
	RuleMultistageFindFailed        = Fant ingen katalogregler på flere nivåer. Klikk meg for å lage en mal.
	RuleMultistageFindCreateNew     = Opprett en ny katalogregelmal på flere nivåer
	RuleMultistageTips              = Tilpass katalogregler på flere nivåer automatisk, {0} katalogregel er deaktivert.
	RuleCustomizeNot                = Finner ikke utvidelsesnavnet (Solutions.Custom.Extension), se hjelpedokumentasjonen.
	RuleCustomizeTips               = Ingen egendefinert regel opprettet. Se hjelpedokumentasjonen.
	RuleMatchNoFindFolder           = Kunne ikke matche katalogen, klikk meg for å opprette katalogen.
	RuleNoFindFile                  = Ingen tilgjengelige filer funnet, vennligst legg til og oppdater.
	RuleFindFolder                  = Katalog velges automatisk når tilgjengelig
	RuleNameNewChange               = Synkroniser automatisk etter oppdateringer
	RuleNewTempate                  = Lag mal
	RuleSkipFolderCheck             = Sjekker ikke lenger om filen finnes i katalogen og filtypen
	RuleAuthon                      = Regelskaper
	RuleGUID                        = GUID globalt unik identifikator
	RuleName                        = Regelnavn
	RuleDescription                 = Beskrive
	RuleNameUse                     = Synkroniser regelnavn til: {0}
	RuleISO                         = Match original ISO-installasjonspakke
	RuleInBoxApps                   = Komplett, forhåndskonfigurert applikasjon
	RuleFileType                    = Pakkenavn
	RuleFileFind                    = Uklart søkenavn
	RuleFindError                   = Fant {0} elementer som skal behandles, klikk "Kontroller avhengigheter" for å se detaljer.
	RuleSelectApps                  = Applikasjoner valgt av brukeren
	DependencyPackage               = Avhengighetspakke
	RuleDependenciesRequired        = Nødvendige avhengigheter
	RuleDependenciesUnselected      = Uvalgte avhengigheter
	RuleDependenciesNoCheck         = Avhengighetene kontrolleres ikke lenger
	RuleDependenciesFix             = Fix avhengigheter er ikke valgt
	Extract_Tips                    = Hint\n\n   1. Resultatet etter utpakking av språkpakken kan ikke brukes som hovedreferanseobjekt;\n\n   2. Bruk komponentlisten som hovedreferanseobjekt. Slik genererer du:\n\n       I Funksjoner, velg Generer komponent (hent pakken i det installerte bildet), velg Skriv ut eller Vis øyeblikkelig;\n\n   3. Etter å ha installert språkpakken, vennligst generer en komponentrapport for å sjekke om den stemmer overens;

	DescendingRuleLang              = Fjern språkpakker i omvendt rekkefølge
	OrderRuleLang                   = Installer språkpakker i forhåndsbestemt rekkefølge
	OrderRuleLangTips               = Legg til i rekkefølge: Grunnleggende, Fonter, Optisk tegngjenkjenning, Håndskriftsgjenkjenning, Tekst-til-tale, Talegjenkjenning, Retail Demo Experience, Annet
	RuleLanguageTips                = Illustrere:\n\n   Etter å ha brukt "Installer språkpakker i forhåndsbestemt rekkefølge", blir filene automatisk matchet med uklare navn i følgende rekkefølge: \n
	Match_installed_List            = Når du installerer en språkpakke, må du jokertegne den fra installeringslisten
	Match_installed_List_Tips       = Matcher bare når installert: Grunnleggende, Optisk tegngjenkjenning, Håndskriftsgjenkjenning, Tekst-til-tale, Talegjenkjenning.
	RuleLanguageTipsExt             = \n   Når du ikke bruker "Installer språkpakker i forhåndsbestemt rekkefølge": \n   Søk automatisk i alle filer i katalogen etter filtype og installer dem.\n\n   Språk og region on-demand funksjoner (FOD)\n   https://learn.microsoft.com/nb-no/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategori
	Basic                           = Grunnleggende
	Fonts                           = Font
	OCR                             = Optisk tegngjenkjenning
	Handwriting                     = Håndskriftgjenkjenning
	TextToSpeech                    = Tekst til tale
	Speech                          = Talegjenkjenning
	Retail                          = Retail Demo Experience
	Features_On_Demand              = Funksjoner på forespørsel
	RegionSpecific                  = Andre regionspesifikke krav
	UnassignedLangFiles             = Utildelte diverse filer

	ProcessingImage                 = Behandle bildet:
	NoInstallImage                  = Finnes ikke lokalt
	ConvertChk                      = Sjekk filen
	WindowsFeature                  = Windows-funksjoner
	Enable                          = Aktivere
	Disable                         = Deaktiver
	EnableFeatureTips               = Hint\n\n    1. Vis NetFx3 og TelnetClient som forhåndsinnstilte funksjonselementer;\n\n    2. Etter "montering" kan flere aktiveres.
	ViewLanguage                    = Se innstillinger for bildespråk
	ImageLanguage                   = Innstillinger for bildespråk
	OnlyLangCleanup                 = Rengjør komponenter: tag etter språk
	Matched_Component_Names         = Matchende komponentnavn:
	BootProcess                     = Ved behandling av {0}.wim
	Sync_Language_To                = Synkroniser til
	BootSyncToISO                   = Synkroniser språkpakker til installasjonsprogrammet
	BootSyncToISOTips               = Den installerte språkpakken til det frakoblede bildet synkroniseres med ISO-installasjonsprogrammet.
	LangIni                         = Regenerer Lang.ini
	LangIniTips                     = Etter at synkroniseringen er fullført, må Lang.ini i ISO bygges om.
	LangNewAutoSelect               = Velg foreslåtte elementer automatisk når en hendelse inntreffer
	LangNewAutoSelectTips           = Det er nye hendelser, "Synkroniser språkpakke til installatør", "Rebuild Lang.ini" valgt.
	LangNewAutoNoSelect             = Det er nye hendelser, det anbefales at du velger "Synchronize language pack to installer" og "Rebuild Lang.ini".
	LangNewAutoNoNewSelect          = Det er ingen nye hendelser. Det anbefales at du ikke velger "Synkroniser språkpakke til installasjonsprogram" eller "Rebuild Lang.ini".
	Drive                           = Kjøre
	ViewDrive                       = Se installerte drivere
	EditionsProductKey              = Produktnøkkel
	Editions                        = Bildeversjon
	Assign_Editions                 = Distribuer applikasjoner automatisk basert på bildeversjoner
	EditionsChangeTips              = Advarsel, vennligst forstå før du bytter bildeversjon: \n\nMicrosoft Tjenesteavtale\nhttps://www.microsoft.com/nb-no/servicesagreement/default.aspx\n\nSpråkoversikt\nhttps://learn.microsoft.com/nb-no/windows-hardware/manufacture/desktop/languages-overview\n\nDu har ikke lov til å lage versjoner av: \n   1. Landsspesifikk\n       ProfessionalCountrySpecific\n\n   2. Regionspesifikk hjemmeversjon\n       ProfessionalSingleLanguage\n\nVennligst følg strengt ettersom du kan bli utsatt for rettsforfølgelse hvis du brytes.\n\nHvis du insisterer på å konvertere, klikk for å godta advarselen og klikk "Lås opp skjult bildeversjon".
	EditionsChangeHide              = Lås opp skjulte bildeversjoner
	EditionsChangeAccect            = Jeg har lest advarselen og er ansvarlig for de relevante lovene i advarselen

	SelFile                         = Velg fil
	Rebuilding                      = Under rekonstruksjon
	RebuildAll                      = Bygg alle sammen
	Export_Image                    = Eksport
	SelectFromError                 = Feil
	SelectFileFormatError           = Filformatet er feil

	SearchDrive                     = Søkedrevet
	SearchUpdate                    = Søk etter oppdateringer, type ( {0} ), kilde:
	SelectFolder                    = Velg katalog
	DropFolder                      = Kan dra kataloger til gjeldende vindu
	DropFile                        = Filer kan dras til gjeldende vindu
	Sparse                          = Sjelden
	CRCSHA                          = Sjekke
	Alternative                     = Alternativt filnavn
	ChangeInstallDisk               = Endre automatisk diskvalg
	Backup                          = Sikkerhetskopiering
	Restore                         = Gjenopprett

	# View
	ExportToLogs                    = Skriv ut rapport for å logge
	ExportShow                      = Vis rapporter umiddelbart
	MoreFeature                     = Flere funksjoner
	OpenFolder                      = Åpne katalogen
	OpenFile                        = Åpne filen
	Running                         = Løp
	Paste                           = Kopibane
	Clipboard_Copy                  = Kopiert til utklippstavlen
	ViewWIMFileInfo                 = Se bilde
	GetInBoxApps                    = InBox Apps: Installerte applikasjonspakker
	GetImagePackage                 = Komponenter: Alle pakker installert i bildet
	ViewMounted                     = Få informasjon om alle monterte bilder
'@