ConvertFrom-StringData -StringData @'
	# pl-PL
	# Polish (Poland)

	FontsUI                   = Segoe UI
	Mainname                  = Silnik wdrażania: pakiet Yi
	Learn                     = Badanie
	MainHisName               = Rozwiązanie bonusowe
	Location                  = Otwarta lokalizacja
	About                     = O
	Reset                     = Nastawić
	AddTo                     = Dodaj do
	Instl                     = Zainstalować
	ItInstalled               = Zainstalowany
	Close                     = Zamknięcie
	Auto                      = Automatyczny
	Disable                   = Wyłączyć
	Enable                    = Włączać
	Setting                   = Organizować coś
	Restore                   = Odzyskiwać
	CLearn                    = Posprzątać
	Operable                  = Wykonalny
	Inoperable                = Nieoperacyjny
	Optimize                  = Optymalizacja
	Hide                      = Ukrywać
	Show                      = Pokazywać
	Del                       = Usuwać
	Done                      = Skończyć
	OK                        = Jasne
	Cancel                    = Anulować
	AllSel                    = Zaznacz wszystko
	AllClear                  = Wyczyść wszystko
	Refresh                   = Odświeżać
	RefreshModules            = Gorące odświeżenie wszystkich modułów
	Necessary                 = Niezbędne oprogramowanie
	MostUsedSoftware          = Często używane oprogramowanie
	System                    = System
	Service                   = Podawać
	TaskBar                   = Wszystkie ikony na pasku zadań
	DeskIcon                  = Ikony pulpitu
	InstallFonts              = Zainstaluj czcionki
	SettingTo                 = Ustaw na {0}
	AvailableLanguages        = Dostępne języki
	SwitchLanguage            = Zmień język
	LanguageReset             = Zresetuj ustawienia języka
	LanguageCode              = Znak strefy
	LanguageSelRegion         = Wybierz swój kraj lub region
	LanguageRemember          = Zapamiętaj wybrany język
	LanguageSearchNo          = Nie znaleziono dostępnych języków
	LanguageNoPack            = Jeśli lokalnie nie ma pakietu językowego, zostanie on zamknięty automatycznie.
	LanguageNoSel             = Wybierz region
	Search                    = Szukaj
	PleaseChoose              = Proszę wybrać
	FailedCreateFolder        = Nie udało się utworzyć katalogu
	Failed                    = Ponieść porażkę
	ToMsg                     = {0} Automatycznie powróć do menu głównego po sekundach.
	Restart                   = Ponowne uruchomienie zaczyna obowiązywać
	AdvOption                 = Funkcje opcjonalne

	StartDown                 = Rozpocznij pobieranie
	ConnectTo                 = Połącz się z
	FileName                  = Nazwa pliku
	SaveTo                    = Zapisz w
	NotAvailable              = Stan: Niedostępne
	ExistingPacker            = Masz już pakiet instalacyjny
	ExistingInstlPacker       = Masz już skompresowany pakiet
	Unpacking                 = Rozpakowanie
	QucikRun                  = Szybki bieg:
	WaitDone                  = Oczekiwanie na ukończenie:
	Parameter                 = Parametr:
	ErrorDown                 = Podczas pobierania wystąpił błąd
	UserCancel                = Użytkownik anulował operację.

	VerifyNameTips            = Dozwolona jest wyłącznie kombinacja angielskich liter i cyfr. Żadne inne znaki nie są dozwolone: spacje, długość nie może być większa niż 16 znaków, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Niestandardowy prefiks katalogu
	NoSetFolderLabel          = Nie ustawiono niestandardowego prefiksu katalogu
	ISO9660TipsErrorSpace     = Nie może zawierać: spacji początkowych i końcowych
	ISO9660TipsErrorOther     = Nie może zawierać: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Etykieta woluminu nie może być dłuższa niż {0} znaków
	Help                      = Pomoc
	WorkDone                  = Zakończono, naciśnij dowolny klawisz, aby powrócić do głównego interfejsu...
	Short_Cmd                 = Skróty
	Options                   = Opcje
'@