ConvertFrom-StringData -StringData @'
	# es-mx
	# Spanish (Mexico)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Panel
	Learn                           = Estudiar
	Menu                            = Menú
	Short_Cmd                       = Atajos
	Shortcut                        = Atajo
	Update                          = Renovar
	CUpdate                         = Actualizaciones acumulativas
	Rebuild                         = Reconstrucción
	AddTo                           = Añadir
	Del                             = Borrar
	Copy                            = Copiar
	Rename                          = Rebautizar
	Refresh                         = Refrescar
	RefreshModules                  = Actualización en caliente de todos los módulos
	Done                            = Finalizar
	OK                              = Seguro
	Cancel                          = Cancelar
	AllSel                          = Seleccionar todo
	AllClear                        = Borrar todo
	Setting                         = Configuración
	Change                          = Cambiar
	Help                            = Ayuda
	Logging                         = Registro
	AvailableLanguages              = Idiomas disponibles
	SwitchLanguage                  = Cambiar de idioma
	LanguageSelRegion               = Seleccione su país o región
	LanguageRemember                = Recordar idioma seleccionado
	LanguageSearchNo                = No se encontraron idiomas disponibles
	LanguageNoPack                  = Si no hay ningún paquete de idioma localmente, se cerrará automáticamente.
	LanguageNoSel                   = Por favor seleccione una región
	Search                          = Buscar
	PleaseChoose                    = Por favor seleccione
	Options                         = Opciones
	Choose                          = Seleccionado
	NoChoose                        = No seleccionado
	AdvOption                       = Características opcionales
	ExcludeItem                     = Excluir por regla
	DeDuplication                   = Excluir duplicados
	DeDuplication_Unlock            = Desbloquear duplicados deshabilitados
	Existed                         = Ya existe
	FailedCreateFolder              = No se pudo crear el directorio
	FailedCreateFile                = No se pudo crear el archivo
	ToMsg                           = {0} Regresa automáticamente al menú principal después de unos segundos.
	OnDemandPlanTask                = Asignación personalizada de eventos conocidos
	Operable                        = Operable
	Inoperable                      = Inoperable
	Hide                            = Esconder
	CuringUpdate                    = Actualización sólida
	CuringUpdateTips                = Una vez que la actualización se ha solidificado, no se puede desinstalar.
	Healthy                         = Saludable
	HealthyTips                     = Es particularmente importante verificar el estado de salud. Cuando aparece "reparable" o "irreparable": durante el proceso de conversión de ESD, aparece el error 13 y los datos no son válidos y se informa un error al instalar el sistema.
	Healthy_Save                    = Cuando aparezca reparable o irreparable, no guardar.
	Repair                          = Reparar
	IsAuto_Repair                   = Permitir reparación automática cuando esté inactivo
	IsAuto_Repair_Tips              = Verifique automáticamente si hay tareas de montaje después de cada ejecución del script de empaquetado. Si está montado, no se realizará ninguna reparación; si no está montado, se ejecutará la reparación automática.
	Repairable                      = Reparable
	NonRepairable                   = No reparable
	HealthyForceStop                = Mientras se procesaba el evento, se encontró un error irreversible y el proceso se terminó por la fuerza.\n\n   Causa principales problemas: \n\n      1. El hardware físico está dañado, el disco duro;\n\n      2. Si utiliza un disco virtual de memoria RAMDISK (incluido el híbrido), verifique la memoria física;\n\n      3. Verifique el SHA256 original de MVS (MSDN). Si es consistente, cambie el directorio e inténtelo nuevamente. Si el SHA256 no es consistente, descárguelo nuevamente e inténtelo nuevamente.\n\n      4. Otros no figuran en este ejemplo.
	Superseded                      = Limpiar lo reemplazado
	SupersededTips                  = Incluye actualizaciones, componentes, etc. desactualizados.
	UnmountFailed                   = He probado varios métodos, pero no se puede hacer nada. Solo puedo dejarlo. Me gustaría verte la próxima vez.
	SaveTo                          = Guardar en
	WorkDone                        = Completado, presione cualquier tecla para regresar a la interfaz principal...
	UserCanel                       = El usuario ha cancelado la solicitud.
	Uping                           = Generando
	Exclude_View                    = Ver reglas de exclusión
	User_Interaction                = Interacción del usuario
	Ok_Go_To                        = Disponible para
	Ok_Go_To_No                     = No ir

	Detailed                        = Detallado
	Detailed_View                   = Ver detalles de la regla seleccionada

	AddEnv                          = Agregar funcionalidad de enrutamiento a las variables del sistema
	AddEnvTips                      = Después de agregar, ingrese Yi en cualquier sesión de PowerShell para responder. Por ejemplo, ingrese "Yi -SIP" para ejecutar la encapsulación.

	Unzip_ISO                       = Extraer ISO
	Unzip_Search_Type               = Directorio de búsqueda ( {0} )
	ISO_Other                       = Otros documentos
	Unzip_Language                  = Paquete de idiomas
	Unzip_Fod                       = Paquete de funciones
	FileName                        = Nombre del archivo

	UserCancel                      = El usuario ha cancelado la operación.
	MatchMode                       = Fósforo
	Failed                          = Fallar
	RandomSelect                    = Seleccionado al azar
	RulePre                         = Reglas preestablecidas
	RuleOther                       = Otras reglas
	RuleCustomize                   = Reglas personalizadas
	RuleCustomize_Dont              = No utilice reglas personalizadas de directorio de varios niveles
	RuleCustomize_Dont_Tips         = Después de eliminar el directorio anterior, haga clic en "Verificar reglas de nombres".
	RuleMultistage                  = Reglas de directorio multinivel
	RuleMultistageFindFailed        = No se encontraron reglas de directorio de varios niveles, haga clic en mí para crear una plantilla.
	RuleMultistageFindCreateNew     = Crear una nueva plantilla de regla de directorio de varios niveles
	RuleMultistageTips              = Adapte automáticamente las reglas de directorio de varios niveles; la regla de directorio {0} se ha deshabilitado.
	RuleCustomizeNot                = Nombre de extensión (Solutions.Custom.Extension) no encontrado; consulte la documentación de ayuda.
	RuleCustomizeTips               = No se creó ninguna regla personalizada; consulte la documentación de ayuda.
	RuleMatchNoFindFolder           = No se pudo hacer coincidir el directorio, haga clic en mí para crear el directorio.
	RuleNoFindFile                  = No se encontraron archivos disponibles, agréguelos y actualícelos.
	RuleFindFolder                  = Directorio seleccionado automáticamente cuando esté disponible
	RuleNameNewChange               = Sincronizar automáticamente después de las actualizaciones
	RuleNewTempate                  = Crear plantilla
	RuleSkipFolderCheck             = Ya no comprueba si el archivo existe en el directorio y el tipo de archivo
	RuleAuthon                      = Creador de reglas
	RuleGUID                        = Identificador único global GUID
	RuleName                        = Nombre de la regla
	RuleDescription                 = Describir
	RuleNameUse                     = Sincronizar el nombre de la regla con: {0}
	RuleISO                         = Coincide con el paquete de instalación ISO original
	RuleInBoxApps                   = Aplicación completa y preconfigurada
	RuleFileType                    = Nombre del paquete
	RuleFileFind                    = Nombre de búsqueda difusa
	RuleFindError                   = Se encontraron {0} elementos para procesar. Haga clic en "Verificar dependencias" para ver los detalles.
	RuleSelectApps                  = Aplicaciones seleccionadas por el usuario
	DependencyPackage               = Paquete de dependencia
	RuleDependenciesRequired        = Dependencias requeridas
	RuleDependenciesUnselected      = Dependencias no seleccionadas
	RuleDependenciesNoCheck         = Las dependencias ya no se verifican
	RuleDependenciesFix             = Reparar dependencias no seleccionadas
	Extract_Tips                    = Pista\n\n   1. El resultado después de extraer el paquete de idioma no se puede utilizar como objeto de referencia principal;\n\n   2. Utilice la lista de componentes como objeto de referencia principal. Cómo generar:\n\n       En Funciones, seleccione Generar componente (obtenga el paquete en la imagen instalada), seleccione Imprimir o Ver al instante;\n\n   3. Después de instalar el paquete de idioma, vuelva a generar un informe de componente para verificar si corresponde;

	DescendingRuleLang              = Eliminar paquetes de idiomas en orden inverso
	OrderRuleLang                   = Instalar paquetes de idiomas en el orden preestablecido
	OrderRuleLangTips               = Agregue en orden: Básico, Fuentes, Reconocimiento óptico de caracteres, Reconocimiento de escritura a mano, Texto a voz, Reconocimiento de voz, Experiencia de demostración minorista, Otros
	RuleLanguageTips                = Ilustrar: \n\n   Después de usar "Instalar paquetes de idiomas en el orden preestablecido", los archivos coinciden automáticamente con nombres difusos en el siguiente orden:\n
	Match_installed_List            = Al instalar un paquete de idioma, añádalo como comodín de la lista instalada
	Match_installed_List_Tips       = Solo coincide cuando está instalado: Básico, Reconocimiento óptico de caracteres, Reconocimiento de escritura a mano, Texto a voz, Reconocimiento de voz.
	RuleLanguageTipsExt             = \n   Cuando no se utiliza "Instalar paquetes de idiomas en el orden predeterminado": \n   Busque automáticamente todos los archivos en el directorio por tipo de archivo e instálelos.\n\n   Funciones bajo demanda de idioma y región (FOD)\n   https://learn.microsoft.com/es-mx/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Categoría
	Basic                           = Básico
	Fonts                           = Fuente
	OCR                             = Reconocimiento óptico de caracteres
	Handwriting                     = Reconocimiento de escritura a mano
	TextToSpeech                    = Texto a voz
	Speech                          = Reconocimiento de voz
	Retail                          = Experiencia de demostración minorista
	Features_On_Demand              = Funciones bajo demanda
	RegionSpecific                  = Otros requisitos específicos de la región
	UnassignedLangFiles             = Archivos varios no asignados

	ProcessingImage                 = Procesar la imagen: 
	NoInstallImage                  = No existe localmente
	ConvertChk                      = Revisa el archivo
	WindowsFeature                  = Características de Windows
	Enable                          = Permitir
	Disable                         = Desactivar
	EnableFeatureTips               = Pista\n\n    1. Mostrar NetFx3 y TelnetClient como elementos de función preestablecidos habilitados;\n\n    2. Después de "montar", se pueden habilitar más.
	ViewLanguage                    = Ver configuración de idioma de la imagen
	ImageLanguage                   = Configuración de idioma de la imagen
	OnlyLangCleanup                 = Componentes limpios: etiquetar por idioma
	Matched_Component_Names         = Nombre del componente coincidente:
	BootProcess                     = Al procesar {0}.wim
	Sync_Language_To                = Sincronizar con
	BootSyncToISO                   = Sincronizar paquetes de idiomas con el instalador
	BootSyncToISOTips               = El paquete de idioma instalado de la imagen sin conexión se sincroniza con el instalador ISO.
	LangIni                         = Regenerar Lang.ini
	LangIniTips                     = Una vez completada la sincronización, es necesario reconstruir Lang.ini en la ISO.
	LangNewAutoSelect               = Seleccionar automáticamente elementos sugeridos cuando ocurre un evento
	LangNewAutoSelectTips           = Hay nuevos eventos, "Sincronizar paquetes de idiomas con el instalador", "Reconstruir Lang.ini" seleccionado.
	LangNewAutoNoSelect             = Hay nuevos eventos, se recomienda seleccionar "Sincronizar paquete de idioma con el instalador" y "Reconstruir Lang.ini".
	LangNewAutoNoNewSelect          = No hay eventos nuevos. Se recomienda que no seleccione "Sincronizar el paquete de idioma con el instalador" y "Reconstruir Lang.ini".
	Drive                           = Conducir
	ViewDrive                       = Ver controladores instalados
	EditionsProductKey              = Clave de producto
	Editions                        = Versión de imagen
	Assign_Editions                 = Distribuya automáticamente aplicaciones basadas en versiones de imágenes.
	EditionsChangeTips              = Advertencia, comprenda antes de cambiar las versiones de la imagen: \n\nMicrosoft Acuerdo de servicio\nhttps://www.microsoft.com/es-mx/servicesagreement/default.aspx\n\nDescripción general del idioma\nhttps://learn.microsoft.com/es-mx/windows-hardware/manufacture/desktop/languages-overview\n\nNo está permitido realizar versiones de:\n   1. Específico del país\n       ProfessionalCountrySpecific\n\n   2. Versión doméstica específica de la región\n       ProfessionalSingleLanguage\n\nCumpla estrictamente, ya que puede estar sujeto a procesamiento si se infringe.\n\nSi insiste en realizar la conversión, haga clic para aceptar la advertencia y haga clic en "Desbloquear versión de imagen oculta".
	EditionsChangeHide              = Desbloquear versiones de imágenes ocultas
	EditionsChangeAccect            = He leído la advertencia y soy responsable de las leyes pertinentes contenidas en la advertencia.

	SelFile                         = Seleccionar archivo
	Rebuilding                      = En reconstrucción
	RebuildAll                      = Reconstruir todo
	Export_Image                    = Exportar
	SelectFromError                 = Error
	SelectFileFormatError           = El formato del archivo es incorrecto

	SearchDrive                     = Impulsado por búsqueda
	SearchUpdate                    = Actualizaciones de búsqueda, escriba ( {0} ), fuente:
	SelectFolder                    = Seleccionar directorio
	DropFolder                      = Puede arrastrar directorios a la ventana actual.
	DropFile                        = Los archivos se pueden arrastrar a la ventana actual.
	Sparse                          = Extraño
	CRCSHA                          = Controlar
	Alternative                     = Nombre de archivo alternativo
	ChangeInstallDisk               = Cambiar la selección automática de disco

	# View
	ExportToLogs                    = Imprimir informe para iniciar sesión
	ExportShow                      = Mostrar informes al instante
	MoreFeature                     = Más funciones
	OpenFolder                      = Directorio abierto
	OpenFile                        = Abrir archivo
	Running                         = Correr
	Paste                           = Copiar ruta
	Clipboard_Copy                  = Copiado al portapapeles
	ViewWIMFileInfo                 = Ver imagen
	GetInBoxApps                    = InBox Apps: paquetes de aplicaciones instaladas
	GetImagePackage                 = Componentes: todos los paquetes instalados en la imagen.
	ViewMounted                     = Obtener información sobre todas las imágenes montadas
'@