ConvertFrom-StringData -StringData @'
	# uk-UA
	# Ukrainian (Ukraine)

	FontsUI                   = Segoe UI
	Mainname                  = Механізм розгортання: комплект Yi
	Learn                     = Вивчення
	MainHisName               = Бонусне рішення
	Location                  = Відкрита локація
	About                     = Приблизно
	Reset                     = Скинути
	AddTo                     = Додати до
	Instl                     = Встановити
	ItInstalled               = Встановлено
	Close                     = Закриття
	Auto                      = Автоматичний
	Disable                   = Вимкнути
	Enable                    = Включити
	Setting                   = Налаштувати
	Restore                   = Одужувати
	CLearn                    = Прибирати
	Operable                  = Працездатний
	Inoperable                = Неоперабельний
	Optimize                  = Оптимізація
	Hide                      = Приховати
	Show                      = Показати
	Del                       = Видалити
	Done                      = Закінчити
	OK                        = Звичайно
	Cancel                    = Скасувати
	AllSel                    = Вибрати все
	AllClear                  = Очистити все
	Refresh                   = Оновити
	RefreshModules            = Гаряче оновлення всіх модулів
	Necessary                 = Основне програмне забезпечення
	MostUsedSoftware          = Поширене програмне забезпечення
	System                    = Система
	Service                   = Подавайте
	TaskBar                   = Усі значки панелі завдань
	DeskIcon                  = Іконки робочого столу
	InstallFonts              = Встановити шрифти
	SettingTo                 = Установлено на {0}
	AvailableLanguages        = Доступні мови
	SwitchLanguage            = Змінити мову
	LanguageReset             = Скинути налаштування мови
	LanguageCode              = Знак зони
	LanguageSelRegion         = Виберіть свою країну або регіон
	LanguageRemember          = Запам'ятати вибрану мову
	LanguageSearchNo          = Доступні мови не знайдено
	LanguageNoPack            = Якщо локально немає мовного пакета, він автоматично закриється.
	LanguageNoSel             = Виберіть регіон
	Search                    = Пошук
	PleaseChoose              = Будь ласка, виберіть
	FailedCreateFolder        = Не вдалося створити каталог
	Failed                    = Провал
	ToMsg                     = {0} Автоматичне повернення до головного меню через кілька секунд.
	Restart                   = Перезапуск вступає в силу
	AdvOption                 = Додаткові функції

	StartDown                 = Почати завантаження
	ConnectTo                 = Підключитися до
	FileName                  = Ім'я файлу
	SaveTo                    = Зберегти в
	NotAvailable              = Статус: недоступний
	ExistingPacker            = Вже є інсталяційний пакет
	ExistingInstlPacker       = Уже є стислий пакет
	Unpacking                 = Розпакування
	QucikRun                  = Швидкий біг:
	WaitDone                  = В очікуванні завершення:
	Parameter                 = Параметр:
	ErrorDown                 = Під час завантаження сталася помилка
	UserCancel                = Користувач скасував операцію.

	VerifyNameTips            = Допускається лише комбінація англійських літер і цифр, інші символи не допускаються: пробіли, довжина не може перевищувати 16 символів, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Користувацький префікс каталогу
	NoSetFolderLabel          = Не встановлено користувацький префікс каталогу
	ISO9660TipsErrorSpace     = Не може містити: пробіли на початку та в кінці
	ISO9660TipsErrorOther     = Не може містити: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Мітка тому не може містити більше {0} символів
	Help                      = Допомогти
	WorkDone                  = Завершено, натисніть будь-яку клавішу, щоб повернутися до основного інтерфейсу...
	Short_Cmd                 = Ярлики
	Options                   = Опції
'@