ConvertFrom-StringData -StringData @'
	# da-dk
	# Danish (Denmark)

	UnpackISO                       = Generer ISO
	ISOLabel                        = Lydstyrketiket er indstillet:
	ISOCustomize                    = ISO volume label navn
	ISO9660                         = Bekræft navngivningsregler
	ISO9660Tips                     = Det unikke navn må ikke overstige 260 tegn, ISO volumenet må ikke overstige 16 tegn og kan ikke indeholde: indledende og efterfølgende mellemrum, \\ / : * ?
	ISOFolderName                   = Tilpasset unik navngivning
	ISOAddFlagsLang                 = Tilføj flersproget markering
	ISOAddFlagsLangGet              = Få kendte installationssprog
	ISOAddFlagsVer                  = Tilføj tag i flere versioner
	ISOAddFlagsVerGet               = Få kendt billedversion
	ISOAddEICFG                     = Tilføj versionstype
	ISOAddEICFGTips                 = Når man stoler på EI.cfg, er det en kommerciel version.
	ISO9660TipsErrorSpace           = Må ikke indeholde: førende og efterfølgende mellemrum
	ISO9660TipsErrorOther           = Kan ikke indeholde: \\ / : * & @ !
	SelOSver                        = Vælg sprogtype
	SelLabel                        = Kodenavn
	ISOVerLabel                     = Vælg navn på ISO volumenetiketten
	NoSetLabel                      = Brugerdefineret ISO lydstyrketiket er ikke indstillet
	ISOLengthError                  = Volumeetiketten må ikke være længere end {0} tegn
	RenameFailed                    = Samme som gammel mappe, omdøb mislykkedes
	ISOCreateAfter                  = Hvad du skal gøre, før du opretter en ISO
	ISOCreateRear                   = Hvad du skal gøre efter oprettelse af ISO
	BypassTPM                       = Omgå TPM installationskontrol
	Disable_BitLocker               = Deaktiver BitLocker enhedskryptering under installationen
	PublicDate                      = Udstedelsesdato
	PublicDateGetCurrent            = Synkroniser den aktuelle dato
	PublicYear                      = År
	PublicMonth                     = Måne
	PublicYMSorting                 = Sortér: Skift "måned_år" til "år_måned"
	PublicYMSortingTips             = AB: Undlad at tilføje understregning _, når du bruger tal.
	PublicYMUseShortNames           = Brug korte navne
	PublicYMUseNumbers              = Brug tal
	ISOCreateFailed                 = Oprettelsen mislykkedes, mappen kan ikke læses eller skrives.
	ISORefreshAuto                  = Opdater ISO tags hver gang
	ISOSaveTo                       = ISO standard gemmeplacering
	ISOSaveSameGlobal               = Brug den globale ISO standardlagringsplacering
	ISOSaveSync                     = Synkroniser automatisk den nye placering efter valg af billedkildesøgningsdisken
	ISOSaveSame                     = Søg disksti ved hjælp af billedkilde
	ISOFolderWrite                  = Bekræft, at mappen er læsbar og skrivbar
	SelectAutoAvailable             = Når du automatisk vælger en tilgængelig disk
	SelectCheckAvailable            = Kontroller den mindste ledige plads
	ISOStructure                    = Ny mappestruktur
	ISOOSLevel                      = Tilføj installationstype
	ISOUniqueNameDirectory          = Tilføj en unik navnemappe
	NextDoOperate                   = Opret ikke ISO
	SelCreateISO                    = Generer ISO, eksekver efter behov
	Reconstruction                  = Genopbyg {0}.wim med maksimal komprimering
	Reconstruction_Tips_Select      = Før genopbygning vil den kun blive udført, når den ikke er indlæst. Det vil tvinge lagringen til at blive aktiveret og derefter afmontere den monterede fil.
	ReconstructionTips              = Over 520 MB, genopbygning anbefales
	CreateASC                       = Tilføj PGP signatur til ISO
	NoPGPKey                        = Der er ingen brugbar privat nøgle i PGP.
	CreateASCPwd                    = Certifikat adgangskode
	PasswordRenter                  = Indtast adgangskode igen
	ShowPassword                    = Vis adgangskode
	NewPasswordSome                 = Adgangskoden stemmer ikke overens.
	PwdPermanent                    = Permanent lagring
	PwdDecfailed                    = Dekryptering mislykkedes
	CreateASCAuthor                 = Underskriver
	CreateASCAuthorTips             = Ingen underskrivere valgt.
	ISO_Sparse_Rename               = Tilføj hash til filnavneudvidelsen
	GenerateRandom                  = Generer tilfældige tal
	RandomNumberReset               = Regenerer
'@