ConvertFrom-StringData -StringData @'
	# pt-BR
	# Portuguese (Brazil)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Painel
	Learn                           = Estudar
	Menu                            = Menu
	Short_Cmd                       = Comando de atalho
	Shortcut                        = Atalho
	Update                          = Renovar
	CUpdate                         = Atualizações cumulativas
	Rebuild                         = Reconstrução
	AddTo                           = Adicionar à
	Del                             = Excluir
	Copy                            = Cópia
	Rename                          = Renomear
	Refresh                         = Atualizar
	RefreshModules                  = Atualização a quente de todos os módulos
	Done                            = Terminar
	OK                              = Claro
	Cancel                          = Cancelar
	AllSel                          = Selecionar tudo
	AllClear                        = Limpar tudo
	Setting                         = Configurar
	Change                          = Mudar
	Help                            = Ajuda
	Logging                         = Registro
	AvailableLanguages              = Idiomas disponíveis
	SwitchLanguage                  = Mudar de idioma
	LanguageSelRegion               = Selecione seu país ou região
	LanguageRemember                = Lembrar o idioma selecionado
	LanguageSearchNo                = Nenhum idioma disponível encontrado
	LanguageNoPack                  = Se não houver nenhum pacote de idiomas localmente, ele será encerrado automaticamente.
	LanguageNoSel                   = Selecione uma região
	Search                          = Procurar
	PleaseChoose                    = Selecione
	Options                         = Opções
	Choose                          = Selecionado
	NoChoose                        = Não selecionado
	AdvOption                       = Recursos opcionais
	ExcludeItem                     = Excluir por regra
	DeDuplication                   = Excluir duplicatas
	DeDuplication_Unlock            = Desbloquear duplicatas desativadas
	Existed                         = Já existe
	FailedCreateFolder              = Falha ao criar diretório
	FailedCreateFile                = Falha ao criar arquivo
	ToMsg                           = {0} Retorne automaticamente ao menu principal após segundos.
	OnDemandPlanTask                = Atribuição personalizada de eventos conhecidos
	Operable                        = Operável
	Inoperable                      = Inoperável
	Hide                            = Esconder
	CuringUpdate                    = Atualização sólida
	CuringUpdateTips                = Depois que a atualização for solidificada, ela não poderá ser desinstalada.
	Healthy                         = Saudável
	HealthyTips                     = É particularmente importante verificar o estado de saúde Quando aparece "reparável" ou "irreparável": Durante o processo de conversão ESD, o erro 13 é solicitado e os dados são inválidos, um erro é relatado durante a instalação do sistema;
	Healthy_Save                    = Quando aparecer reparável ou irreparável, não salve.
	Repair                          = Reparar
	IsAuto_Repair                   = Permitir reparo automático quando ocioso
	IsAuto_Repair_Tips              = Verifique automaticamente se há alguma tarefa de montagem após cada execução do script de empacotamento. Se estiver montado, nenhum reparo será realizado; se não estiver montado, o reparo automático será executado.
	Repairable                      = Reparável
	NonRepairable                   = Não reparável
	HealthyForceStop                = Durante o processamento do evento, foi encontrado um erro irreversível e o evento foi encerrado à força.\n\n   Causa os principais problemas: \n\n      1. O hardware físico está danificado, disco rígido;\n\n      2. Se você usar disco virtual de memória RAMDISK (incluindo híbrido), verifique a memória física;\n\n      3. Verifique o SHA256 original do MVS (MSDN). Se estiver consistente, altere o diretório e tente novamente. Se o SHA256 estiver inconsistente, baixe-o novamente e tente novamente;\n\n      4. Outros não estão listados neste exemplo.
	Superseded                      = Limpe o substituído
	SupersededTips                  = Inclui atualizações desatualizadas, componentes, etc.
	UnmountFailed                   = Eu tentei vários métodos, mas nada pode ser feito, só posso desistir. Gostaria de ver você na próxima vez.
	SaveTo                          = Salvar em
	WorkDone                        = Concluído, pressione qualquer tecla para retornar à interface principal...
	UserCanel                       = O usuário cancelou a solicitação.
	Uping                           = Gerando
	Exclude_View                    = Ver regras de exclusão
	User_Interaction                = Interação do usuário
	Ok_Go_To                        = Disponível para
	Ok_Go_To_No                     = Não vou

	Detailed                        = Detalhado
	Detailed_View                   = Ver detalhes da regra selecionada

	AddEnv                          = Adicione funcionalidade de roteamento às variáveis do sistema
	AddEnvTips                      = Após adicionar, insira Yi em qualquer sessão do PowerShell para responder. Por exemplo, insira "Yi -SIP" para executar o encapsulamento.

	Unzip_ISO                       = Extrair ISO
	Unzip_Search_Type               = Diretório de pesquisa ( {0} )
	ISO_Other                       = Outros documentos
	Unzip_Language                  = Pacote de idiomas
	Unzip_Fod                       = Pacote de recursos
	FileName                        = Nome do arquivo

	UserCancel                      = O usuário cancelou a operação.
	MatchMode                       = Corresponder
	Failed                          = Falhar
	RandomSelect                    = Selecionado aleatoriamente
	RulePre                         = Regras predefinidas
	RuleOther                       = Outras regras
	RuleCustomize                   = Regras personalizadas
	RuleCustomize_Dont              = Não use regras personalizadas de diretório multinível
	RuleCustomize_Dont_Tips         = Após excluir o diretório antigo, clique em "Verificar regras de nomenclatura".
	RuleMultistage                  = Regras de diretório multinível
	RuleMultistageFindFailed        = Nenhuma regra de diretório multinível encontrada. Clique em mim para criar um modelo.
	RuleMultistageFindCreateNew     = Crie um novo modelo de regra de diretório multinível
	RuleMultistageTips              = Adapte automaticamente regras de diretório multinível, a regra de diretório {0} foi desativada.
	RuleCustomizeNot                = Nome da extensão (Solutions.Custom.Extension) não encontrado, consulte a documentação de ajuda.
	RuleCustomizeTips               = Nenhuma regra personalizada foi criada. Consulte a documentação de ajuda.
	RuleMatchNoFindFolder           = Falha ao corresponder ao diretório, clique em mim para criar o diretório.
	RuleNoFindFile                  = Nenhum arquivo disponível encontrado. Adicione e atualize.
	RuleFindFolder                  = Diretório selecionado automaticamente quando disponível
	RuleNameNewChange               = Sincronizar automaticamente após atualizações
	RuleNewTempate                  = Criar modelo
	RuleSkipFolderCheck             = Não verifica mais se o arquivo existe no diretório e no tipo de arquivo
	RuleAuthon                      = Criador de regras
	RuleGUID                        = GUID identificador globalmente exclusivo
	RuleName                        = Nome da regra
	RuleDescription                 = Descrever
	RuleNameUse                     = Nome da regra de sincronização para: {0}
	RuleISO                         = Combine o pacote de instalação ISO original
	RuleInBoxApps                   = Aplicativo completo e pré-configurado
	RuleFileType                    = Nome do pacote
	RuleFileFind                    = Nome de pesquisa difuso
	RuleFindError                   = Encontrados {0} itens a serem processados, clique em "Verificar dependências" para ver os detalhes.
	RuleSelectApps                  = Aplicativos selecionados pelo usuário
	DependencyPackage               = Pacote de dependência
	RuleDependenciesRequired        = Dependências necessárias
	RuleDependenciesUnselected      = Dependências não selecionadas
	RuleDependenciesNoCheck         = As dependências não são mais verificadas
	RuleDependenciesFix             = Corrigir dependências não selecionadas
	Extract_Tips                    = Dica\n\n   1. O resultado após a extração do pacote de idiomas não pode ser usado como objeto de referência principal;\n\n   2. Use a lista de componentes como objeto de referência principal. Como gerar:\n\n       Em Funções, selecione Gerar Componente (obtenha o pacote na imagem instalada), selecione Imprimir ou Visualizar Instantaneamente;\n\n   3. Após instalar o pacote de idiomas, gere novamente um relatório do componente para verificar se ele é correspondente;

	DescendingRuleLang              = Remova os pacotes de idiomas na ordem inversa
	OrderRuleLang                   = Instale pacotes de idiomas em ordem pré-regulada
	OrderRuleLangTips               = Adicione em ordem: Básico, Fontes, Reconhecimento Óptico de Caracteres, Reconhecimento de Caligrafia, Conversão de Texto para Fala, Reconhecimento de Fala, Experiência de Demonstração de Varejo, Outros
	RuleLanguageTips                = Ilustrar:\n\n   Depois de usar "Instalar pacotes de idiomas em ordem pré-regulada", os arquivos são automaticamente correspondidos por nomes difusos na seguinte ordem:\n
	Match_installed_List            = Ao instalar um pacote de idiomas, coloque-o como curinga na lista de instalados
	Match_installed_List_Tips       = Corresponde apenas quando instalado: Básico, Reconhecimento Óptico de Caracteres, Reconhecimento de Manuscrito, Conversão de Texto para Fala, Reconhecimento de Fala.
	RuleLanguageTipsExt             = \n   Quando não estiver usando "Instalar pacotes de idiomas em ordem pré-regulada": \n   Pesquise automaticamente todos os arquivos no diretório por tipo de arquivo e instale-os.\n\n   Recursos sob demanda de idioma e região (FOD)\n   https://learn.microsoft.com/pt-br/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Categoria
	Basic                           = Básico
	Fonts                           = Fonte
	OCR                             = Reconhecimento óptico de caracteres
	Handwriting                     = Reconhecimento de escrita
	TextToSpeech                    = Texto para fala
	Speech                          = Reconhecimento de fala
	Retail                          = Experiência de demonstração de varejo
	Features_On_Demand              = Recursos sob demanda
	RegionSpecific                  = Outros requisitos específicos da região
	UnassignedLangFiles             = Arquivos diversos não atribuídos

	ProcessingImage                 = Processe a imagem:
	NoInstallImage                  = Não existe localmente
	ConvertChk                      = Verifique o arquivo
	WindowsFeature                  = Recursos do Windows
	Enable                          = Habilitar
	Disable                         = Desativar
	EnableFeatureTips               = Dica\n\n    1. Exibir NetFx3 e TelnetClient como itens de função habilitados predefinidos;\n\n    2. Após a "montagem", mais podem ser habilitados.
	ViewLanguage                    = Ver configurações de idioma da imagem
	ImageLanguage                   = Configurações de idioma da imagem
	OnlyLangCleanup                 = Componentes limpos: tag por idioma
	Matched_Component_Names         = Nome do componente correspondente:
	BootProcess                     = Ao processar {0}.wim
	Sync_Language_To                = Sincronizar com
	BootSyncToISO                   = Sincronize pacotes de idiomas com o instalador
	BootSyncToISOTips               = O pacote de idiomas instalado da imagem offline é sincronizado com o instalador ISO.
	LangIni                         = Regenerar Lang.ini
	LangIniTips                     = Após a sincronização ser concluída, o Lang.ini no ISO precisa ser reconstruído.
	LangNewAutoSelect               = Selecionar automaticamente itens sugeridos quando ocorrer um evento
	LangNewAutoSelectTips           = Existem novos eventos, "Sincronizar pacote de idiomas com o instalador", "Reconstruir Lang.ini" selecionado.
	LangNewAutoNoSelect             = Existem novos eventos, é recomendado que você selecione "Sincronizar pacote de idiomas com o instalador" e "Reconstruir Lang.ini".
	LangNewAutoNoNewSelect          = Não há novos eventos. É recomendável não selecionar "Sincronizar pacote de idiomas com o instalador" ou "Reconstruir Lang.ini".
	Drive                           = Dirigir
	ViewDrive                       = Ver drivers instalados
	EditionsProductKey              = Chave do produto
	Editions                        = Versão da imagem
	Assign_Editions                 = Distribua aplicativos automaticamente com base em versões de imagem
	EditionsChangeTips              = Aviso, por favor entenda antes de mudar de versão de imagem: \n\nMicrosoft Contrato de serviço\nhttps://www.microsoft.com/pt-br/servicesagreement/default.aspx\n\nVisão geral do idioma\nhttps://learn.microsoft.com/pt-br/windows-hardware/manufacture/desktop/languages-overview\n\nVocê não tem permissão para fazer versões de: \n   1. Específico do país\n       ProfessionalCountrySpecific\n\n   2. Versão inicial específica da região\n       ProfessionalSingleLanguage\n\nPor favor, cumpra rigorosamente, pois você pode estar sujeito a processo se violado.\n\nSe você insiste em converter, clique para aceitar o aviso e clique em "Desbloquear versão da imagem oculta".
	EditionsChangeHide              = Desbloqueie versões de imagens ocultas
	EditionsChangeAccect            = Li o aviso e sou responsável pelas leis relevantes contidas no aviso

	SelFile                         = Selecione o arquivo
	Rebuilding                      = Em reconstrução
	RebuildAll                      = Reconstruir tudo
	Export_Image                    = Exportar
	SelectFromError                 = Erro
	SelectFileFormatError           = O formato do arquivo está incorreto

	SearchDrive                     = Orientado por pesquisa
	SearchUpdate                    = Atualizações de pesquisa, tipo ( {0} ), fonte:
	SelectFolder                    = Selecione o diretório
	DropFolder                      = Pode arrastar diretórios para a janela atual
	DropFile                        = Os arquivos podem ser arrastados para a janela atual
	Sparse                          = Cru
	CRCSHA                          = Verificar
	Alternative                     = Nome de arquivo alternativo
	ChangeInstallDisk               = Alterar seleção automática de disco

	# View
	ExportToLogs                    = Imprimir relatório para registrar
	ExportShow                      = Exibir relatórios instantaneamente
	MoreFeature                     = Mais recursos
	OpenFolder                      = Abrir diretório
	OpenFile                        = Abrir arquivo
	Running                         = Correr
	Paste                           = Copiar caminho
	Clipboard_Copy                  = Copiado para a área de transferência
	ViewWIMFileInfo                 = Ver imagem
	GetInBoxApps                    = InBox Apps: pacotes de aplicativos instalados
	GetImagePackage                 = Componentes: Todos os pacotes instalados na imagem
	ViewMounted                     = Obtenha informações sobre todas as imagens montadas
'@