ConvertFrom-StringData -StringData @'
	# tr-TR
	# Turkish (Turkey)

	Main_quests                     = Ana Görevler
	Side_quests                     = Alt Görevler
	SaveModeClear                   = Seçilen geçmişi temizle
	SaveModeTipsClear               = Geçmiş kaydedildi ve temizlenebilir
	SelectTips                      = Ipucu\n\n    1. Lütfen işlenecek görüntünün adını seçin;\n    2. İptal ettiğinizde, işlem öncesi "montaj" gerektiren görevler artık geçerli olmayacaktır.
	CacheDisk                       = Disk önbelleği
	CacheDiskCustomize              = Özel önbellek yolu
	AutoSelectRAMDISK               = Otomatik disk birimi etiketi seçimine izin ver
	AutoSelectRAMDISKFailed         = Birim etiketi eşleşmedi
	ReFS_Find_Volume                = Disk formatı REFS ile karşılaşıldığında hariç tutun
	ReFS_Exclude                    = ReFS bölümü hariç tutuldu
	Disk_Not_satisfied_Exclude      = Minimum disk gereksinimleri karşılanmadı
	RAMDISK_Change                  = Birim etiketi adını değiştirin
	RAMDISK_Search                  = Disk Etiketi Adını Ara
	RAMDISK_Restore                 = Başlatılan birim adını geri yükle: {0}
	AllowTopMost                    = Açık pencerelerin üste sabitlenmesine izin ver
	History                         = Geçmişi temizle
	History_Del_Tips                = Bir kapsülleme görevi olduğunda aşağıdaki isteğe bağlı seçenekleri çalıştırmayın, aksi takdirde kapsülleme komut dosyasının çalıştırılması sırasında bilinmeyen sorunlara neden olur.
	History_View                    = Geçmişi görüntüle
	HistoryLog                      = 7 günden eski günlüklerin otomatik olarak temizlenmesine izin ver
	HistorySaveFolder               = Diğer görüntü kaynağı yolları
	HistoryClearappxStage           = InBox Apps: Kurulum sırasında oluşturulan geçici dosyaları silin
	DoNotCheckBoot                  = Boot.wim dosyasının boyutu 520 MB'ı aştığında, ISO oluşturulurken otomatik olarak yeniden oluşturma seçilir.
	HistoryClearDismSave            = Kayıt defterinde kayıtlı DISM bağlama kayıtlarını silin
	ImageSourcesClickShowKey        = "Birincil Anahtar Seç" menüsünün görüntülenmesine izin ver
	ImageSourcesClickShowKeyTips    = Kullanıcı görüntü kaynağını seçtikten sonra: Sağ tarafa bir "Birincil Anahtar Seç" menüsü ekleyin ve "Git" seçeneklerini ekleyin: Bağla, Kaydet, Açılır Pencere.
	Clear_Bad_Mount                 = Bozuk monte edilmiş görüntüyle ilişkili tüm kaynakları silin
	ShowCommand                     = Komut satırı çalışmasının tamamını göster
	Command                         = Komut satırı
	SelectSettingImage              = Görüntü kaynağı
	NoSelectImageSource             = Resim kaynağı seçilmedi
	SettingImageRestore             = Varsayılan bağlama konumunu geri yükle
	SettingImage                    = Görüntü kaynağı bağlama konumunu değiştir
	SelectImageMountStatus          = Görüntü kaynağını seçtikten sonra bağlama durumunu alın
	SettingImageTempFolder          = Geçici dizin
	SettingImageToTemp              = Geçici dizin, bağlandığı konumla aynıdır
	SettingImagePathTemp            = Temp dizinini kullanma
	SettingImageLow                 = Mevcut minimum kalan alanı kontrol edin
	SettingImageNewPath             = Bağlama diskini seçin
	SettingImageNewPathTips         = En hızlı olan hafıza diskine bağlamanız tavsiye edilir. Ultra RAMDisk ve ImDisk gibi sanal hafıza yazılımlarını kullanabilirsiniz.
	SelectImageSource               = "Motor Çözümünü Dağıt" seçildi, Tamam'a tıklayın.
	NoImagePreSource                = Kullanılabilir kaynak bulunamadı. Yapmanız gerekenler: \n\n     1. Şuraya daha fazla resim kaynağı ekleyin: \n          {0}\n\n     2. "Ayarlar"ı seçin ve görüntü kaynağı arama diskini yeniden seçin;\n\n     3. "ISO"yu seçin ve sıkıştırılacak ISO'yu, monte edilecek öğeleri vb. seçin.
	NoImageOtherSource              = Diğer yolları "Ekle" veya geçerli pencereye "Dizini Sürükle" için beni tıklayın.
	SearchImageSource               = Resim kaynağı arama diski
	Kernel                          = Çekirdek
	Architecture                    = Mimarlık
	ArchitecturePack                = Paket mimarisi, kural eklemeyi anlama
	ImageLevel                      = Kurulum türü
	LevelDesktop                    = Masaüstü
	LevelServer                     = Sunucu
	ImageCodename                   = Kod adı
	ImageCodenameNo                 = Tanınmadı
	MainImageFolder                 = Ana dizin
	MountImageTo                    = Monte etmek
	Image_Path                      = Görüntü yolu
	MountedIndex                    = Dizin
	MountedIndexSelect              = Dizin numarasını seçin
	AutoSelectIndexFailed           = {0} dizininin otomatik seçimi başarısız oldu, lütfen tekrar deneyin.
	Apply                           = Başvuru
	Eject                           = Aniden belirmek
	Mount                           = Montaj
	ReMount                         = Yeniden monte et
	Unmount                         = Kaldır
	Mounted                         = Monte edilmiş
	NotMounted                      = Monte edilmemiş
	NotMountedSpecify               = Monte edilmemiş, montaj yerini belirtebilirsiniz
	MountedIndexError               = Anormal montaj, silin ve tekrar deneyin.
	NeedsRemount                    = Yeniden monte edilmesi gerekiyor
	Invalid                         = Geçersiz
	ImageSouresNoSelect             = Görüntü kaynağını seçtikten sonra daha fazla ayrıntı göster
	Mounted_Mode                    = Montaj modu
	Mounted_Status                  = Montaj durumu
	Status                          = Durum
	Image_Popup_Default             = Varsayılan olarak kaydet
	Image_Restore_Default           = Varsayılana geri dön
	Image_Popup_Tips                = Ipucu: \n\nEtkinliği atadığınızda, {0} işleminin gerçekleştirileceği dizin numarasını belirtmediniz;\n\nSeçim arayüzü şu anda açılmıştır. Lütfen indeks numarasını belirtin. Belirleme tamamlandıktan sonra "Varsayılan Olarak Kaydet" seçeneğini seçmeniz önerilir. Bir sonraki işleminizde tekrar açılmayacaktır.
	Rule_Show_Full                  = Tümünü göster
	Rule_Show_Only                  = Yalnızca kuralları göster
	Rule_Show_Only_Select           = Kurallar arasından seçim yapın
	Image_Unmount_After             = Monte edilenlerin tümünü kaldır

	Wim_Rule_Update                 = Görüntünün içindeki dosyaları çıkarın ve güncelleyin
	Wim_Rule_Extract                = Dosyaları çıkart
	Wim_Rule_Extract_Tips           = Yol kuralını seçtikten sonra belirtilen dosyayı çıkartın ve yerel olarak kaydedin.

	Wim_Rule_Verify                 = Doğrulamak
	Wim_Rule_Check                  = Incelemek
	Wim_Rule_CheckIntegrity         = Bütünlüğü Kontrol Et
	Wim_Rule_ReadOnly               = Salt okunur izin
	Wim_Rule_Optimize               = Optimizasyon
	ResetBase                       = Derinlemesine temizlik
	Wim_Rule_SupportEa              = Genişletilmiş özelliklere sahip görselleri uygulama
	Wim_Rule_WIMBoot                = Önyüklenebilir
	Wim_Rule_Compact                = İşletim Sistemi Dosyalarını Sıkıştır
	Win_Rule_Setbootable            = Birim Görüntüsünü Önyüklenebilir Olarak İşaretle
	Win_Rule_Setbootable_Tips       = Bu parametre yalnızca Windows PE görüntüleri için geçerlidir.\nBir .wim dosyasında yalnızca bir birim görüntüsü önyüklenebilir olarak işaretlenebilir.
	Destination                     = Varış noktası

	Wim_Append                      = Ekle
	Wim_Capture                     = Yakala
	Wim_Capture_Tips                = Sürücü görüntüsünü yeni bir WIM dosyasına yakala.
	Wim_Capture_Sources             = Kaynak Yakala
	Wim_Capture_Sources_Tips        = Yakalanan dizin tüm alt klasörleri ve verileri içerir.\nBoş bir dizini yakalayamazsınız. Dizin en az bir dosya içermelidir.
	Wim_Config_File                 = Yapılandırma Dosyası Yolu ( Hariç Tutmalar )
	Wim_Config_Edit                 = Düzenle
	Wim_Config_Learn                = Yapılandırma listesini ve WimScript.ini dosyasını inceleyin

	Wim_Rename                      = Resim bilgilerini değiştirin
	Wim_Image_Name                  = Resim adı
	Wim_Image_Description           = Resim açıklaması
	Wim_Display_Name                = Ekran adı
	Wim_Display_Description         = Açıklamayı göster
	Wim_Edition                     = Görüntü işareti
	Wim_Edition_Select_Know         = Bilinen resim bayraklarını seç
	Wim_CreatedTime                 = Oluşturulma tarihi
	Wim_ModifiedTime                = Son değiştirilme zamanı
	Wim_FileCount                   = Dosya sayısı
	Wim_DirectoryCount              = Dizin sayısı
	Wim_Expander_Space              = Genişleme alanı

	IABSelectNo                     = Birincil anahtar seçilmedi: Install, WinRE, Boot
	Unique_Name                     = Benzersiz adlandırma
	Select_Path                     = Yol
	Setting_Pri_Key                 = Bu güncelleme dosyasını ana şablon olarak ayarlayın
	Pri_Key_Update_To               = Daha sonra şuraya güncelleyin
	Pri_Key_Template                = Bu dosyayı seçilen öğelerle senkronize edilecek tercih edilen şablon olarak ayarlayın
	Pri_key_Running                 = Birincil anahtar görevi senkronize edildi ve atlandı.
	ShowAllExclude                  = Kullanımdan kaldırılan tüm hariç tutmaları göster

	Index_Process_All               = Bilinen tüm dizin numaralarını işle
	Index_Is_Event_Select           = Bir olay olduğunda indeks numarası seçim arayüzü açılır.
	Index_Pre_Select                = Önceden atanmış indeks numarası
	Index_Select_Tips               = Ipucu: \n\n{0}.wim şu anda takılı değil; şunları yapabilirsiniz: \n\n   1. "Bilinen tüm dizin numaralarını işle"yi seçin;\n\n   2. "Bir olay olduğunda indeks numarası seçim arayüzü açılacaktır" seçeneğini seçin;\n\n   3. Önceden belirlenmiş indeks numarası\n      Dizin numarası 6 belirtildi, işlem sırasında dizin numarası mevcut değil ve işlem atlanıyor.

	Index_Tips_Custom_Expand        = Grup: {0}\n\n{1} işlenirken {2} indeks numarasının atanması gerekir, aksi halde işlenemez.\n\n"Güncelleme kurallarını tüm dizin numaralarıyla senkronize et" seçeneğini seçtikten sonra, ana şablon olarak yalnızca herhangi birini işaretlemeniz gerekir.

	DefenderExclude                 = Windows Antivirüs Hariç Tutma Listesi
	DefenderFolder                  = Bu dizini Windows Antivirüs Hariç Tutma Listesine ekleyin.
	DefenderVolume                  = Eşleşen disk etiketi adını bulduktan sonra, bu diski Windows Antivirüs Hariç Tutma Listesine ekleyin.
	DefenderIsAdd                   = Windows Antivirüs Hariç Tutma Listesine Eklendi
'@