ConvertFrom-StringData -StringData @'
	# nl-NL
	# Dutch (Netherlands)

	IsCreate                        = creëren
	Solution                        = oplossing
	EnabledSoftwarePacker           = Verzameling
	EnabledUnattend                 = Moet vooraf antwoorden
	EnabledEnglish                  = Implementatie-engine
	UnattendSelectVer               = Selecteer de oplossingstaal 'Antwoord op'
	UnattendLangPack                = Selecteer 'Oplossing' taalpakket
	UnattendSelectSingleInstl       = Meertalig, optioneel tijdens installatie
	UnattendSelectMulti             = meertalig
	UnattendSelectDisk              = Selecteer de Autounattend.xml-oplossing
	UnattendSelectSemi              = Halfautomatisch is geldig voor alle installatiemethoden
	UnattendSelectUefi              = UEFI wordt automatisch geïnstalleerd en moet worden opgegeven
	UnattendSelectLegacy            = Legacy wordt automatisch geïnstalleerd en moet worden opgegeven
	NeedSpecified                   = Selecteer wat moet worden gespecificeerd:
	OOBESetupOS                     = Installatie-interface
	OOBEProductKey                  = productsleutel
	OOBEOSImage                     = Selecteer het besturingssysteem dat u wilt installeren
	OOBEEula                        = Accepteer licentievoorwaarden
	OOBEDoNotServerManager          = Serverbeheer start niet automatisch bij het inloggen
	OOBEIE                          = Verbeterde beveiligingsconfiguratie van Internet Explorer
	OOBEIEAdmin                     = Sluit "Beheerder"
	OObeIEUser                      = Sluit "Gebruikers"

	OOBE_Init_User                  = Eerste gebruiker tijdens het uitpakken
	OOBE_init_Create                = Aangepaste gebruikers maken
	OOBE_init_Specified             = Geef gebruiker op
	OOBE_Init_Autologin             = Automatisch inloggen

	InstlMode                       = Installatiemethode
	Business                        = Zakelijke versie
	BusinessTips                    = Afhankelijk van EI.cfg moet het indexnummer worden opgegeven voor automatische installatie.
	Consumer                        = Consumentenversie
	ConsumerTips                    = Het is niet afhankelijk van EI.cfg. Het serienummer moet worden opgegeven voor automatische installatie. Wanneer u pauzeert in de versieselectie-interface, moet het indexnummer worden opgegeven.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [ophangen]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Toevoegen aan de naam van de thuismap van de systeemschijf
	VerifyNameUse                   = Controleer of de mapnaam geen
	VerifyNameTips                  = Alleen een combinatie van Engelse letters en cijfers is toegestaan en mag het volgende niet bevatten: spaties, lengte mag niet groter zijn dan 260 tekens, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Verificatie mislukt. Voer het juiste nummer in.
	VerifyNameSync                  = Stel de mapnaam in als primaire gebruikersnaam
	VerifyNameSyncTips              = Beheerder wordt niet meer gebruikt.
	ManualKey                       = Selecteer of voer uw productsleutel handmatig in
	ManualKeyTips                   = Voer een geldige productsleutel in. Als de geselecteerde regio niet beschikbaar is, ga dan naar de officiële website van Microsoft om dit te controleren.
	ManualKeyError                  = De productsleutel die u heeft ingevoerd is ongeldig.
	KMSLink1                        = Sleutel voor KMS-clientinstellingen
	KMSUnlock                       = Toon alle bekende KMS-serienummers
	KMSSelect                       = Selecteer VOL-serienummer
	KMSKey                          = serienummer
	KMSKeySelect                    = Wijzig het serienummer van het product
	ClearOld                        = Ruim oude bestanden op
	SolutionsSkip                   = Sla het maken van een oplossing over
	SolutionsTo                     = Voeg 'oplossing' toe aan:
	SolutionsToMount                = Gekoppeld of toegevoegd aan wachtrij
	SolutionsToError                = Sommige functies zijn uitgeschakeld. Als u het gebruik ervan wilt forceren, klikt u op de knop 'Ontgrendelen'.\n\n
	UnlockBoot                      = Ontgrendelen
	SolutionsToSources              = Thuismap, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Selecteer de versie 'Deployment Engine'
	SolutionsEngineRegionaUTF8      = Bèta: wereldwijde taalondersteuning met Unicode UTF-8
	SolutionsEngineRegionaUTF8Tips  = Het lijkt erop dat het nieuwe problemen kan veroorzaken na het openen ervan. Niet aanbevolen.
	SolutionsEngineRegionaling      = Wijzigen naar nieuwe landinstelling:
	SolutionsEngineRegionalingTips  = Wijzig de landinstelling van het systeem, die van invloed is op alle gebruikersaccounts op de computer.
	SolutionsEngineRegional         = Wijzig de systeemlandinstelling
	SolutionsEngineRegionalTips     = Globale standaard: {0}, gewijzigd in: {1}
	SolutionsEngineCopyPublic       = Kopieer openbare {0} naar implementatie
	SolutionsEngineCopyOpen         = Blader door de openbare opslagplaats {0}
	EnglineDoneReboot               = Start uw computer opnieuw op
	SolutionsTipsArm64              = Het arm64-pakket heeft de voorkeur en u selecteert in volgorde: x64, x86.
	SolutionsTipsAMD64              = Geef de voorkeur aan x64-pakketten, in volgorde: x86.
	SolutionsTipsX86                = Er worden alleen x86-pakketten toegevoegd.
	SolutionsReport                 = Genereer een pre-implementatierapport
	SolutionsDeployOfficeInstall    = Implementeer het Microsoft Office-installatiepakket
	SolutionsDeployOfficeChange     = Wijzig de implementatieconfiguratie
	SolutionsDeployOfficePre        = Vooraf geïnstalleerde pakketversie
	SolutionsDeployOfficeNoSelect   = Er is geen Office-voorinstallatiepakket geselecteerd
	SolutionsDeployOfficeVersion    = {0} versie
	SolutionsDeployOfficeOnly       = Bewaar gespecificeerde taalpakketten
	SolutionsDeployOfficeSync       = Behoud de taalsynchronisatie met de implementatieconfiguratie
	SolutionsDeployOfficeSyncTips   = Na synchronisatie kan het installatiescript de voorkeurstaal niet bepalen.
	DeploySyncMainLanguage          = Synchroniseer met de hoofdtaal
	SolutionsDeployOfficeTo         = Implementeer het installatiepakket naar
	SolutionsDeployOfficeToPublic   = openbaar bureaublad
	DeployPackage                   = Implementeer een aangepast verzamelpakket
	DeployPackageSelect             = Kies voor een voor-ophaalpakket
	DeployPackageTo                 = Implementeer het pre-collectiepakket naar
	DeployPackageToRoot             = Systeemschijf:\\Package
	DeployPackageToSolutions        = In de thuismap van de oplossing
	DeployTimeZone                  = tijdzone
	DeployTimeZoneChange            = Tijdzone wijzigen
	DeployTimeZoneChangeTips        = Stel per taalgebied het standaardtijdgebied in waar pre-antwoorden moeten worden beantwoord.

	Deploy_Tags                     = Implementatietag
	FirstExpProcess                 = Eerste ervaring tijdens implementatievereisten:
	FirstExpProcessTips             = Nadat u aan de vereisten heeft voldaan, start u de computer opnieuw op om het probleem op te lossen dat een herstart nodig is om effect te sorteren.
	FirstExpFinish                  = Eerste ervaring, na het voltooien van de vereisten
	FirstExpSyncMark                = Sta globaal zoeken en synchronisatie van implementatietags toe
	FirstExpUpdate                  = Automatische updates toestaan
	FirstExpDefender                = Voeg een thuismap toe om uitgesloten mappen te verdedigen
	FirstExpSyncLabel               = Volumelabel van systeemschijf: De naam van de thuismap is hetzelfde
	MultipleLanguages               = Wanneer u meerdere talen tegenkomt:
	NetworkLocationWizard           = Netwerklocatiewizard
	PreAppxCleanup                  = Blokkeer onderhoudstaken voor het opschonen van Appx
	LanguageComponents              = Voorkom het opruimen van ongebruikte taalpakketten op aanvraag
	PreventCleaningUnusedLP         = Voorkom het opschonen van ongebruikte taalpakketten
	FirstExpContextCustomize        = Voeg een gepersonaliseerd "contextmenu" toe
	FirstExpContextCustomizeShift   = Houd de Shift-toets ingedrukt en klik met de rechtermuisknop

	FirstExpFinishTips              = Er zijn geen belangrijke gebeurtenissen nadat de implementatie is voltooid. Het wordt aanbevolen dat u annuleert.
	FirstExpFinishPopup             = Open de hoofdinterface van de implementatie-engine
	FirstExpFinishOnDemand          = Eerste voorbeeld toestaan, zoals gepland
	SolutionsEngineRestricted       = Powershell-uitvoeringsbeleid herstellen: beperkt
	EnglineDoneClearFull            = Verwijder de volledige oplossing
	EnglineDoneClear                = Verwijder de implementatie-engine en bewaar de andere

	Unattend_Auto_Fix_Next          = De volgende keer dat u het probleem tegenkomt, selecteert u automatisch de benodigde items om het probleem automatisch te verhelpen.
	Unattend_Auto_Fix               = Automatisch repareren als er geen vereisten zijn geselecteerd
	Unattend_Auto_Fix_Tips          = Wanneer u de implementatie-engine toevoegt en de opdracht voor eerste uitvoering niet selecteert, wordt deze automatisch gerepareerd en geselecteerd: Powershell-uitvoeringsbeleid: voer de implementatie-engine zonder enige beperking uit.
	Unattend_Version_Tips           = Optioneel alleen opnemen, gebruik standaard ter ondersteuning van ARM64, x64, x86.
	First_Run_Commmand              = Opdrachten die moeten worden uitgevoerd bij de eerste implementatie
	First_Run_Commmand_Setting      = Selecteer de opdracht die u wilt uitvoeren
	Command_Not_Class               = Niet langer automatisch gecategoriseerd tijdens het filteren
	Command_WinSetup                = Windows-installatie
	Command_WinPE                   = Windows PE
	Command_Tips                    = Wijs de First Run-app toe aan: Windows-installatie, Windows PE\n\nHoud er rekening mee dat wanneer een implementatie-engine wordt toegevoegd, u het volgende moet controleren wanneer u deze voor de eerste keer uitvoert: Powershell-uitvoeringsbeleid: beperkt, sta toe dat scripts voor de implementatie-engine worden uitgevoerd.
	Waring_Not_Select_Command       = Bij het toevoegen van een implementatie-engine is het Powershell-uitvoeringsbeleid niet geselecteerd: Stel geen beperkingen in en sta toe dat het implementatie-engine-script wordt uitgevoerd. Selecteer het en probeer het opnieuw, of klik op 'Snelle oplossing is niet geselecteerd'.
	Quic_Fix_Not_Select_Command     = Snelle oplossing geen optie

	PowerShell_Unrestricted         = Powershell-uitvoeringsbeleid: geen beperkingen
	Allow_Running_Deploy_Engine     = Sta toe dat implementatie-engine-scripts worden uitgevoerd
	Bypass_TPM                      = TPM-controles omzeilen tijdens de installatie
'@