ConvertFrom-StringData -StringData @'
	# uk-UA
	# Ukrainian (Ukraine)

	IsCreate                        = створити
	Solution                        = рішення
	EnabledSoftwarePacker           = Колекція
	EnabledUnattend                 = Треба відповісти заздалегідь
	EnabledEnglish                  = Механізм розгортання
	UnattendSelectVer               = Виберіть мову рішення "Відповідь на".
	UnattendLangPack                = Виберіть мовний пакет "Рішення".
	UnattendSelectSingleInstl       = Багатомовність, необов'язкова під час встановлення
	UnattendSelectMulti             = багатомовний
	UnattendSelectDisk              = Виберіть рішення Autounattend.xml
	UnattendSelectSemi              = Напівавтомат діє для всіх способів монтажу
	UnattendSelectUefi              = UEFI встановлюється автоматично, і його потрібно вказати
	UnattendSelectLegacy            = Legacy встановлюється автоматично, і його потрібно вказати
	NeedSpecified                   = Будь ласка, виберіть, що потрібно вказати:
	OOBESetupOS                     = Інтерфейс встановлення
	OOBEProductKey                  = ключ продукту
	OOBEOSImage                     = Виберіть операційну систему для встановлення
	OOBEEula                        = Прийміть умови ліцензії
	OOBEDoNotServerManager          = Диспетчер сервера не запускається автоматично після входу
	OOBEIE                          = Конфігурація підвищеної безпеки Internet Explorer
	OOBEIEAdmin                     = Закрити "Адміністратор"
	OObeIEUser                      = Закрити "Користувачі"

	OOBE_Init_User                  = Початковий користувач під час розпакування
	OOBE_init_Create                = Створення власних користувачів
	OOBE_init_Specified             = Вкажіть користувача
	OOBE_Init_Autologin             = Автоматичний вхід

	InstlMode                       = Спосіб установки
	Business                        = Бізнес-версія
	BusinessTips                    = Залежно від EI.cfg, номер індексу потрібно вказати для автоматичного встановлення.
	Consumer                        = Споживча версія
	ConsumerTips                    = Для автоматичного встановлення не потрібно вказувати серійний номер.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [монтувати до]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Додайте назву домашнього каталогу системного диска
	VerifyNameUse                   = Переконайтеся, що назва каталогу не може містити
	VerifyNameTips                  = Допускається лише комбінація англійських літер і цифр, яка не може містити: пробіли, довжина не може перевищувати 260 символів, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Не вдалося перевірити, введіть правильний номер.
	VerifyNameSync                  = Встановіть назву каталогу як основне ім'я користувача
	VerifyNameSyncTips              = administrator більше не використовується.
	ManualKey                       = Виберіть або введіть ключ продукту вручну
	ManualKeyTips                   = Введіть дійсний ключ продукту, якщо вибраний регіон недоступний, перейдіть на офіційний сайт Microsoft, щоб перевірити.
	ManualKeyError                  = Введений ключ продукту недійсний.
	KMSLink1                        = Ключ налаштувань клієнта KMS
	KMSUnlock                       = Показати всі відомі серійні номери KMS
	KMSSelect                       = Виберіть серійний номер VOL
	KMSKey                          = серійний номер
	KMSKeySelect                    = Змінити серійний номер продукту
	ClearOld                        = Очистіть старі файли
	SolutionsSkip                   = Пропустити створення рішення
	SolutionsTo                     = Додайте "рішення" до:
	SolutionsToMount                = Змонтовано або додано до черги
	SolutionsToError                = Деякі функції вимкнено. Якщо потрібно примусово їх використовувати, натисніть кнопку "Розблокувати".\n\n
	UnlockBoot                      = Розблокувати
	SolutionsToSources              = домашній каталог, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Виберіть версію "Deployment Engine".
	SolutionsEngineRegionaUTF8      = Бета: глобальна підтримка мови з використанням Unicode UTF-8
	SolutionsEngineRegionaUTF8Tips  = Схоже, що після відкриття це може викликати нові проблеми. Не рекомендується.
	SolutionsEngineRegionaling      = Змінити на нову мову:
	SolutionsEngineRegionalingTips  = Змініть локаль системи, що впливає на всі облікові записи користувачів на комп'ютері.
	SolutionsEngineRegional         = Змінити локаль системи
	SolutionsEngineRegionalTips     = Загальне значення за умовчанням: {0}, змінено на: {1}
	SolutionsEngineCopyPublic       = Скопіюйте загальнодоступний {0} для розгортання
	SolutionsEngineCopyOpen         = Перегляньте розташування загальнодоступного сховища {0}
	EnglineDoneReboot               = Перезавантажте комп'ютер
	SolutionsTipsArm64              = Пакет arm64 є кращим, і ви вибираєте в такому порядку: x64, x86.
	SolutionsTipsAMD64              = Віддавайте перевагу пакетам x64 у порядку: x86.
	SolutionsTipsX86                = Додаються лише пакети x86.
	SolutionsReport                 = Створіть звіт перед розгортанням
	SolutionsDeployOfficeInstall    = Розгорніть інсталяційний пакет Microsoft Office
	SolutionsDeployOfficeChange     = Змінити конфігурацію розгортання
	SolutionsDeployOfficePre        = Попередньо встановлена версія пакета
	SolutionsDeployOfficeNoSelect   = Пакет попередньої інсталяції Office не вибрано
	SolutionsDeployOfficeVersion    = {0} версія
	SolutionsDeployOfficeOnly       = Зберігайте вказані мовні пакети
	SolutionsDeployOfficeSync       = Зберегти синхронізацію мови з конфігурацією розгортання
	SolutionsDeployOfficeSyncTips   = Після синхронізації сценарій встановлення не може визначити потрібну мову.
	DeploySyncMainLanguage          = Синхронізувати з основною мовою
	SolutionsDeployOfficeTo         = Розгорніть інсталяційний пакет на
	SolutionsDeployOfficeToPublic   = публічний робочий стіл
	DeployPackage                   = Розгорніть спеціальний пакет колекції
	DeployPackageSelect             = Виберіть пакет попереднього збору
	DeployPackageTo                 = Розгорніть пакет попереднього збору в
	DeployToRoot                    = Системний диск
	DeployPackageToSolutions        = У домашньому каталозі рішення
	DeployTimeZone                  = часовий пояс
	DeployTimeZoneChange            = Змінити часовий пояс
	DeployTimeZoneChangeTips        = Встановіть зону часу за замовчуванням, де потрібно відповідати на попередні відповіді, за мовною областю.

	Deploy_Tags                     = Тег розгортання
	FirstExpProcess                 = Перший досвід під час розгортання передумови:
	FirstExpProcessTips             = Після виконання попередніх умов перезавантажте комп'ютер, щоб вирішити проблему, пов'язану з необхідністю перезавантаження.
	FirstExpFinish                  = Перший досвід, після виконання попередніх умов
	FirstExpSyncMark                = Дозволити глобальний пошук і синхронізацію тегів розгортання
	FirstExpDefender                = Додати домашній каталог до захисту виключених каталогів
	FirstExpSyncLabel               = Мітка тому системного диска: ім'я домашнього каталогу те саме
	MultipleLanguages               = При зустрічі з кількома мовами:
	NetworkLocationWizard           = Майстер розташування в мережі
	PreAppxCleanup                  = Заблокувати завдання з обслуговування очищення Appx
	LanguageComponents              = Запобігайте очищенню невикористаних мовних пакетів функцій на вимогу
	PreventCleaningUnusedLP         = Запобігайте очищенню невикористаних мовних пакетів
	FirstExpContextCustomize        = Додати персоналізоване "контекстне меню"
	FirstExpContextCustomizeShift   = Утримуючи клавішу Shift, клацніть правою кнопкою миші

	FirstExpFinishTips              = Немає важливих подій після завершення розгортання. Рекомендуємо скасувати.
	FirstExpFinishPopup             = Відкрийте головний інтерфейс механізму розгортання
	FirstExpFinishOnDemand          = Дозвольте перший попередній перегляд, як і планувалося
	SolutionsEngineRestricted       = Відновити політику виконання Powershell: обмежено
	EnglineDoneClearFull            = Видалити весь розчин
	EnglineDoneClear                = Видаліть механізм розгортання та збережіть інші

	Unattend_Auto_Fix_Next          = Наступного разу, коли ви зіткнетеся з ним, автоматично виберіть необхідні елементи, щоб автоматично виправити це.
	Unattend_Auto_Fix               = Автоматично виправляти, якщо не вибрано попередні умови
	Unattend_Auto_Fix_Tips          = Якщо додавати механізм розгортання й не вибирати першу команду запуску, він автоматично виправляється та вибирається: Політика виконання Powershell: запускайте механізм розгортання без будь-яких обмежень.
	Unattend_Version_Tips           = За бажанням можна лише включити, використовувати за умовчанням для підтримки ARM64, x64, x86.
	First_Run_Commmand              = Команди для виконання під час першого розгортання
	First_Run_Commmand_Setting      = Виберіть команду для запуску
	Command_Not_Class               = Більше не автоматично класифікується під час фільтрації
	Command_WinSetup                = Установка Windows
	Command_WinPE                   = Windows PE
	Command_Tips                    = Будь ласка, призначте програму першого запуску для: інсталяції Windows, Windows PE\n\nЗауважте, що коли додається механізм розгортання, під час першого запуску потрібно перевірити наступне: Політика виконання Powershell: обмежено, дозволити запуск сценаріїв механізму розгортання.
	Waring_Not_Select_Command       = Під час додавання механізму розгортання не було вибрано політику виконання Powershell: не встановлюйте жодних обмежень і дозвольте запустити сценарій механізму розгортання. Виберіть його та повторіть спробу або натисніть "Швидке виправлення не вибрано".
	Quic_Fix_Not_Select_Command     = Швидке вирішення не варіант

	PowerShell_Unrestricted         = Політика виконання Powershell: без обмежень
	Allow_Running_Deploy_Engine     = Дозволити запуск сценаріїв механізму розгортання
'@