ConvertFrom-StringData -StringData @'
	# hu-HU
	# Hungarian (Hungary)

	FontsUI                   = Segoe UI
	Mainname                  = Bevezetési motor: Yi programcsomagja
	Learn                     = Tanulmány
	MainHisName               = Bónusz megoldás
	Location                  = Hely megnyitása
	About                     = Körülbelül
	Reset                     = Reset
	AddTo                     = Hozzáadás
	Instl                     = Telepítés
	ItInstalled               = Telepítve
	Close                     = Bezárás
	Auto                      = Automatikus
	Disable                   = Letiltás
	Enable                    = Engedélyezze
	Setting                   = Felállítani
	Restore                   = Visszaszerez
	CLearn                    = Takarítani
	Operable                  = Működtethető
	Inoperable                = Működésképtelen
	Optimize                  = Optimalizálás
	Hide                      = Elrejt
	Show                      = Megmutat
	Del                       = Töröl
	Done                      = Befejezés
	OK                        = Persze
	Cancel                    = Mégsem
	AllSel                    = Válassza ki az összeset
	AllClear                  = Mindent törölni
	Refresh                   = Frissíteni
	RefreshModules            = Az összes modul gyors frissítése
	Necessary                 = Nélkülözhetetlen szoftver
	MostUsedSoftware          = Gyakran használt szoftver
	System                    = Rendszer
	Service                   = Szolgál
	TaskBar                   = Minden tálcaikon
	DeskIcon                  = Asztali ikonok
	InstallFonts              = Betűtípusok telepítése
	SettingTo                 = Beállítás erre: {0}
	AvailableLanguages        = Elérhető nyelvek
	SwitchLanguage            = Nyelvet váltani
	LanguageReset             = Nyelvi beállítások visszaállítása
	LanguageCode              = Zóna jel
	LanguageSelRegion         = Válassza ki országát vagy régióját
	LanguageRemember          = Emlékezzen a kiválasztott nyelvre
	LanguageSearchNo          = Nem található elérhető nyelv
	LanguageNoPack            = Ha nincs helyi nyelvi csomag, akkor az automatikusan kilép.
	LanguageNoSel             = Kérjük, válasszon régiót
	Search                    = Keresés
	PleaseChoose              = Kérem válasszon
	FailedCreateFolder        = Nem sikerült létrehozni a könyvtárat
	Failed                    = Uspjeti
	ToMsg                     = {0} Másodpercek után automatikusan visszatér a főmenübe.
	Restart                   = Az újraindítás életbe lép
	AdvOption                 = Választható funkciók

	StartDown                 = Indítsa el a letöltést
	ConnectTo                 = Csatlakozás a
	FileName                  = Fájlnév
	SaveTo                    = Mentse ide
	NotAvailable              = Állapot: Nem elérhető
	ExistingPacker            = Már van telepítő csomag
	ExistingInstlPacker       = Már van tömörített csomagod
	Unpacking                 = Kicsomagolás
	QucikRun                  = Gyors futás:
	WaitDone                  = Befejezésre vár:
	Parameter                 = Paraméter:
	ErrorDown                 = Hiba történt a letöltés során
	UserCancel                = A felhasználó megszakította a műveletet.

	VerifyNameTips            = Csak angol betűk és számok kombinációja engedélyezett, más karakterek nem megengedettek: szóközök, a hossza nem lehet hosszabb 16 karakternél, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Egyéni címtár előtag
	NoSetFolderLabel          = Az egyéni könyvtár előtagja nincs beállítva
	ISO9660TipsErrorSpace     = Nem tartalmazhat kezdő és záró szóközöket
	ISO9660TipsErrorOther     = Nem tartalmazhatja: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = A kötetcímke nem lehet hosszabb {0} karakternél
	Help                      = Segítség
	WorkDone                  = Befejezve, nyomja meg bármelyik gombot, hogy visszatérjen a fő felületre...
	Short_Cmd                 = Parancsikonok
	Options                   = Opciók
'@