ConvertFrom-StringData -StringData @'
	# ar-sa
	# Arabic (Saudi Arabia)

	UnpackISO                       = توليد ISO
	ISOLabel                        = تم تعيين تسمية الحجم:
	ISOCustomize                    = اسم تسمية وحدة تخزين ISO
	ISO9660                         = التحقق من قواعد التسمية
	ISO9660Tips                     = لا يمكن أن يتجاوز الاسم الفريد 260 حرفًا، ولا يمكن أن يتجاوز اسم وحدة تخزين ISO 16 حرفًا، ولا يمكن أن يحتوي على: مسافات بادئة وزائدة، \\ / : * ? & @ "" < > |
	ISOFolderName                   = تسمية فريدة مخصصة
	ISOAddFlagsLang                 = إضافة علامات متعددة اللغات
	ISOAddFlagsLangGet              = احصل على لغات التثبيت المعروفة
	ISOAddFlagsVer                  = إضافة علامة متعددة الإصدارات
	ISOAddFlagsVerGet               = الحصول على نسخة الصورة المعروفة
	ISOAddEICFG                     = إضافة نوع الإصدار
	ISOAddEICFGTips                 = عند الاعتماد على EI.cfg، فهو إصدار تجاري.
	ISO9660TipsErrorSpace           = لا يمكن أن تحتوي على: مسافات بادئة وزائدة
	ISO9660TipsErrorOther           = لا يمكن أن يحتوي على: \\ / : * & @ !
	SelOSver                        = اختر نوع اللغة
	SelLabel                        = اسم الرمز
	ISOVerLabel                     = حدد اسم تسمية وحدة تخزين ISO
	NoSetLabel                      = لم يتم تعيين تسمية حجم ISO المخصصة
	ISOLengthError                  = لا يمكن أن تكون تسمية وحدة التخزين أطول من {0} حرفًا
	RenameFailed                    = نفس الدليل القديم، فشلت إعادة التسمية
	ISOCreateAfter                  = ما عليك القيام به قبل إنشاء ISO
	ISOCreateRear                   = ما عليك القيام به بعد إنشاء ISO
	BypassTPM                       = تجاوز فحص تثبيت TPM
	Disable_BitLocker               = قم بتعطيل تشفير جهاز BitLocker أثناء التثبيت
	PublicDate                      = تاريخ الإصدار
	PublicDateGetCurrent            = مزامنة التاريخ الحالي
	PublicYear                      = سنة
	PublicMonth                     = قمر
	PublicYMSorting                 = فرز: غيّر "شهر_سنة" إلى "سنة_شهر"
	PublicYMSortingTips             = AB: لا تُضِف الشرطة السفلية _ عند استخدام الأرقام.
	PublicYMUseShortNames           = استخدم أسماءً مختصرة
	PublicYMUseNumbers              = استخدم الأرقام
	ISOCreateFailed                 = فشل الإنشاء، الدليل غير قابل للقراءة أو الكتابة.
	ISORefreshAuto                  = قم بتحديث علامات ISO في كل مرة
	ISOSaveTo                       = موقع الحفظ الافتراضي ISO
	ISOSaveSameGlobal               = استخدم موقع الحفظ الافتراضي العالمي ISO
	ISOSaveSync                     = قم بمزامنة الموقع الجديد تلقائيًا بعد تحديد قرص البحث عن مصدر الصورة
	ISOSaveSame                     = ابحث عن مسار القرص باستخدام مصدر الصورة
	ISOFolderWrite                  = التحقق من أن الدليل قابل للقراءة والكتابة
	SelectAutoAvailable             = عند اختيار القرص المتاح تلقائيًا
	SelectCheckAvailable            = تحقق من الحد الأدنى من المساحة المتبقية المتاحة
	ISOStructure                    = هيكل الدليل الجديد
	ISOOSLevel                      = إضافة نوع التثبيت
	ISOUniqueNameDirectory          = إضافة دليل اسم فريد
	NextDoOperate                   = لا تقم بإنشاء ISO
	SelCreateISO                    = توليد ISO وتنفيذها عند الطلب
	Reconstruction                  = إعادة البناء بأعلى ضغط {0}.wim
	Reconstruction_Tips_Select      = قبل إعادة البناء، سيتم تنفيذه فقط عندما لا يتم تحميله، وسيفرض تمكين الحفظ ثم إلغاء تحميل الملف المثبت.
	ReconstructionTips              = أكثر من 520 ميجابايت، يوصى بإعادة البناء
	CreateASC                       = أضف توقيع PGP إلى ISO
	NoPGPKey                        = لا يوجد مفتاح خاص قابل للاستخدام في PGP.
	CreateASCPwd                    = كلمة مرور الشهادة
	PasswordRenter                  = أعد إدخال كلمة المرور
	ShowPassword                    = عرض كلمة المرور
	NewPasswordSome                 = كلمة المرور غير صحيحة.
	PwdPermanent                    = التخزين الدائم
	PwdDecfailed                    = فشل فك التشفير
	CreateASCAuthor                 = الموقع
	CreateASCAuthorTips             = لم يتم تحديد أي موقعين.
	ISO_Sparse_Rename               = أضف علامة التجزئة (#) إلى امتداد اسم الملف
	GenerateRandom                  = توليد أرقام عشوائية
	RandomNumberReset               = تجديد
'@