ConvertFrom-StringData -StringData @'
	# zh-TW
	# Chinese (Traditional, Taiwan)

	IsCreate                        = 創建
	Solution                        = 解決方案
	EnabledSoftwarePacker           = 合集
	EnabledUnattend                 = 應預答
	EnabledEnglish                  = 部署引擎
	UnattendSelectVer               = 選擇 '應預答' 解決方案語言
	UnattendLangPack                = 選擇 '解決方案' 語言包
	UnattendSelectSingleInstl       = 多語言，安裝時可選
	UnattendSelectMulti             = 多語言
	UnattendSelectDisk              = 選擇 Autounattend.xml 解決方案
	UnattendSelectSemi              = 半自動對所有安裝方式有效
	UnattendSelectUefi              = UEFI 自動安裝，需要指定
	UnattendSelectLegacy            = Legacy 自動安裝，需要指定
	NeedSpecified                   = 請選擇需要指定的：
	OOBESetupOS                     = 安裝界面
	OOBEProductKey                  = 產品密鑰
	OOBEOSImage                     = 選擇要安裝的操作系統
	OOBEEula                        = 接受許可條款
	OOBEDoNotServerManager          = 登錄時不自動啟動服務器管理器
	OOBEIE                          = Internet Explorer 增強的安全配置
	OOBEIEAdmin                     = 關閉“管理員”
	OObeIEUser                      = 關閉“用戶”

	OOBE_Init_User                  = 開箱體驗時初始用戶
	OOBE_init_Create                = 自定義創建用戶
	OOBE_init_Specified             = 指定用戶
	OOBE_Init_Autologin             = 自動登錄

	InstlMode                       = 安裝方式
	Business                        = 商業版
	BusinessTips                    = 依賴 EI.cfg，自動安裝需指定索引號。
	Consumer                        = 消費者版
	ConsumerTips                    = 不依賴 EI.cfg，自動安裝需指定序列號，暫停在選擇版本界面時，需指定索引號。
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [掛載到]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = 添加到系統盤主目錄名稱
	VerifyNameUse                   = 驗證目錄名不能包含的
	VerifyNameTips                  = 只允許英文字母和數字組合，不能包含：空格、長度不能大於 260 字符、\\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = 驗證失敗，請輸入正確的數字。
	VerifyNameSync                  = 將目錄名設置為主用戶名
	VerifyNameSyncTips              = 不再使用 administrator。
	ManualKey                       = 選擇或手動輸入產品密鑰
	ManualKeyTips                   = 輸入有效產品密鑰，選擇區域沒有請前往微軟官方查閱。
	ManualKeyError                  = 你輸入的產品密鑰無效。
	KMSLink1                        = KMS 客戶端設置密鑰
	KMSUnlock                       = 顯示已知所有 KMS 序列號
	KMSSelect                       = 請選擇 VOL 序列號
	KMSKey                          = 序列號
	KMSKeySelect                    = 更改產品序列號
	ClearOld                        = 清理舊文件
	SolutionsSkip                   = 跳過創建解決方案
	SolutionsTo                     = 将 '解決方案' 添加到：
	SolutionsToMount                = 已掛載或添加到隊列中
	SolutionsToError                = 已禁用部分功能，如需強行使用，請點“解除鎖定”按鈕。\n\n
	UnlockBoot                      = 解除鎖定
	SolutionsToSources              = 主目錄，[ISO]:\\Sources\\$OEM$
	SolutionsScript                 = 選擇 '部署引擎' 版本
	SolutionsEngineRegionaUTF8      = Beta 版：使用 Unicode UTF-8 提供全球語言支持
	SolutionsEngineRegionaUTF8Tips  = 开開啟後彷佛、有可能會引發新的問題。不建議。
	SolutionsEngineRegionaling      = 更改為新的區域設置：
	SolutionsEngineRegionalingTips  = 更改系統區域設置，這個設置對計算機上的所有用戶帳號都有影響。
	SolutionsEngineRegional         = 更改系統區域設置
	SolutionsEngineRegionalTips     = 全局默認：{0}，更改為：{1}
	SolutionsEngineCopyPublic       = 複製公共 {0} 到部署裡
	SolutionsEngineCopyOpen         = 瀏覽公共存放 {0} 位置
	EnglineDoneReboot               = 重新啟動計算機
	SolutionsTipsArm64              = 首選 arm64 軟件包，依次按順序選擇：x64、x86。
	SolutionsTipsAMD64              = 首選 x64 軟件包，依次按順序選擇：x86。
	SolutionsTipsX86                = 僅添加 x86 軟件包。
	SolutionsReport                 = 生成預部署報告
	SolutionsDeployOfficeInstall    = 部署 Microsoft Office 安裝包
	SolutionsDeployOfficeChange     = 更改部署配置
	SolutionsDeployOfficePre        = 預安裝包版本
	SolutionsDeployOfficeNoSelect   = 未選擇 Office 預安裝包
	SolutionsDeployOfficeVersion    = {0} 版本
	SolutionsDeployOfficeOnly       = 保留指定的語言包
	SolutionsDeployOfficeSync       = 保留語言同步到部署配置
	SolutionsDeployOfficeSyncTips   = 同步後，安裝腳本無法判斷首選語言。
	DeploySyncMainLanguage          = 同步與主語言一致
	SolutionsDeployOfficeTo         = 將安裝包部署到
	SolutionsDeployOfficeToPublic   = 公共桌面
	DeployPackage                   = 部署自定義合集包
	DeployPackageSelect             = 選擇預合集包
	DeployPackageTo                 = 部署預合集包到
	DeployPackageToRoot             = 系統盤:\\Package
	DeployPackageToSolutions        = 解決方案主目錄下
	DeployTimeZone                  = 時間區域
	DeployTimeZoneChange            = 更改時間區域
	DeployTimeZoneChangeTips        = 設置應預答默認時間區域，按語言區域。

	Deploy_Tags                     = 部署標記
	FirstExpProcess                 = 首次體驗，部署先決條件過程中：
	FirstExpProcessTips             = 完成先決條件後重啟計算機，解決需重啟才生效問題。
	FirstExpFinish                  = 首次體驗，完成先決條件後
	FirstExpSyncMark                = 允許全盤搜索並同步部署標記
	FirstExpUpdate                  = 允許自動更新
	FirstExpDefender                = 添加主目錄到 Defend 排除目錄
	FirstExpSyncLabel               = 系統盤捲標：主目錄名相同
	MultipleLanguages               = 遇到多語言時：
	NetworkLocationWizard           = 網絡位置嚮導
	PreAppxCleanup                  = 阻止 Appx 清理維護任務
	LanguageComponents              = 阻止清理未使用的按需功能語言包
	PreventCleaningUnusedLP         = 阻止清理未使用的語言包
	FirstExpContextCustomize        = 添加個性化“上下文菜單”
	FirstExpContextCustomizeShift   = 按住 Shift 鍵後點擊右鍵

	FirstExpFinishTips              = 部署完成後沒有重要的事件，建議您取消。
	FirstExpFinishPopup             = 彈出部署引擎主界面
	FirstExpFinishOnDemand          = 允許首次預體驗，按計劃
	SolutionsEngineRestricted       = 恢復 Powershell 執行策略：受限
	EnglineDoneClearFull            = 刪除整個解決方案
	EnglineDoneClear                = 刪除部署引擎，保留其它

	Unattend_Auto_Fix_Next          = 下次遇到時，自動選擇必備項時自動修復
	Unattend_Auto_Fix               = 未選擇必備項時自動修復
	Unattend_Auto_Fix_Tips          = 添加部署引擎時未選擇首次運行命令時，自動修復並選擇：Powershell 執行策略：不設任何的限制、運行部署引擎。
	Unattend_Version_Tips           = 可選擇僅包含，使用默認可支持 ARM64、x64、x86。
	First_Run_Commmand              = 首次部署時運行的命令
	First_Run_Commmand_Setting      = 選擇待運行的命令
	Command_Not_Class               = 篩選時不再自動分類
	Command_WinSetup                = Windows 安裝
	Command_WinPE                   = Windows PE
	Command_Tips                    = 請分配首次運行應用於：Windows 安裝、Windows PE\n\n注意，添加了部署引擎時，首次運行時需要勾選：Powershell 執行策略：受限、允許運行部署引擎腳本。
	Waring_Not_Select_Command       = 添加部署引擎時，未選擇 Powershell 執行策略：不設任何的限制、允許運行部署引擎腳本，請選擇後重試，或點擊“快速修復未選項”。
	Quic_Fix_Not_Select_Command     = 快速修復未選項

	PowerShell_Unrestricted         = Powershell 執行策略：不設任何的限制
	Allow_Running_Deploy_Engine     = 允許運行部署引擎腳本
	Bypass_TPM                      = 安裝時繞過 TPM 檢查
'@