ConvertFrom-StringData -StringData @'
	# lv-LV
	# Latvian (Latvia)

	UnpackISO                       = Izveidojiet ISO
	ISOLabel                        = Sējuma etiķete ir iestatīta:
	ISOCustomize                    = ISO apjoma etiķetes nosaukums
	ISO9660                         = Pārbaudiet nosaukumu piešķiršanas noteikumus
	ISO9660Tips                     = Unikālais nosaukums nedrīkst pārsniegt 260 rakstzīmes, ISO sējuma nosaukums nedrīkst pārsniegt 16 rakstzīmes, un tajā nedrīkst būt: sākuma un beigu atstarpes, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Pielāgots unikāls nosaukums
	ISOAddFlagsLang                 = Pievienojiet daudzvalodu marķējumu
	ISOAddFlagsLangGet              = Iegūstiet zināmās instalēšanas valodas
	ISOAddFlagsVer                  = Pievienojiet vairāku versiju tagu
	ISOAddFlagsVerGet               = Iegūstiet zināmu attēla versiju
	ISOAddEICFG                     = Pievienojiet versijas veidu
	ISOAddEICFGTips                 = Paļaujoties uz EI.cfg, tā ir komerciāla versija.
	ISO9660TipsErrorSpace           = Nedrīkst saturēt: sākuma un beigu atstarpes
	ISO9660TipsErrorOther           = Nedrīkst saturēt: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Izvēlieties valodas veidu
	SelLabel                        = Koda nosaukums
	ISOVerLabel                     = Atlasiet ISO skaļuma nosaukumu
	NoSetLabel                      = Pielāgota ISO apjoma etiķete nav iestatīta
	ISOLengthError                  = Sējuma etiķete nedrīkst būt garāka par {0} rakstzīmēm
	RenameFailed                    = Tāpat kā vecajā direktorijā, pārdēvēšana neizdevās
	ISOCreateAfter                  = Kas jums jādara pirms ISO izveides
	ISOCreateRear                   = Kas jums jādara pēc ISO izveides
	BypassTPM                       = Apiet TPM instalācijas pārbaudi
	Disable_BitLocker               = Instalēšanas laikā atspējojiet BitLocker ierīces šifrēšanu
	PublicDate                      = Izdošanas datums
	PublicDateGetCurrent            = Sinhronizēt pašreizējo datumu
	PublicYear                      = Gads
	PublicMonth                     = Mēness
	PublicYMSorting                 = Kārtot: Nomainiet "month_year" uz "year_month"
	PublicYMSortingTips             = AB: Nelietojiet pasvītrojumu _, lietojot skaitļus.
	PublicYMUseShortNames           = Izmantojiet īsus nosaukumus
	PublicYMUseNumbers              = Izmantojiet skaitļus
	ISOCreateFailed                 = Izveidošana neizdevās, direktorijs nav lasāms vai rakstāms.
	ISORefreshAuto                  = Katru reizi atsvaidziniet ISO tagus
	ISOSaveTo                       = ISO noklusējuma saglabāšanas vieta
	ISOSaveSameGlobal               = Izmantojiet globālo ISO noklusējuma saglabāšanas vietu
	ISOSaveSync                     = Pēc attēla avota meklēšanas diska atlasīšanas automātiski sinhronizējiet jauno atrašanās vietu
	ISOSaveSame                     = Meklējiet diska ceļu, izmantojot attēla avotu
	ISOFolderWrite                  = Pārbaudiet, vai direktorijs ir lasāms un rakstāms
	SelectAutoAvailable             = Automātiski izvēloties pieejamo disku
	SelectCheckAvailable            = Pārbaudiet minimālo pieejamo vietu
	ISOStructure                    = Jauna direktoriju struktūra
	ISOOSLevel                      = Pievienojiet instalācijas veidu
	ISOUniqueNameDirectory          = Pievienojiet unikālu nosaukumu direktoriju
	NextDoOperate                   = Neveidojiet ISO
	SelCreateISO                    = Ģenerējiet ISO, izpildiet pēc pieprasījuma
	Reconstruction                  = Atjaunojiet {0}.wim ar maksimālu saspiešanu
	Reconstruction_Tips_Select      = Pirms atjaunošanas tas tiks izpildīts tikai tad, kad tas netiks ielādēts. Tas liks iespējot saglabāšanu un pēc tam atvienot pievienoto failu.
	ReconstructionTips              = Vairāk nekā 520 MB, ieteicams pārbūvēt
	CreateASC                       = Pievienojiet PGP parakstu ISO
	NoPGPKey                        = PGP nav izmantojamas privātās atslēgas.
	CreateASCPwd                    = Sertifikāta parole
	PasswordRenter                  = Atkārtoti ievadiet paroli
	ShowPassword                    = Rādīt paroli
	NewPasswordSome                 = Parole nesakrīt.
	PwdPermanent                    = Pastāvīga glabāšana
	PwdDecfailed                    = Atšifrēšana neizdevās
	CreateASCAuthor                 = Parakstītājs
	CreateASCAuthorTips             = Nav atlasīts neviens parakstītājs.
	ISO_Sparse_Rename               = Pievienot faila nosaukuma paplašinājumam jaucējkodu
	GenerateRandom                  = Ģenerējiet nejaušus skaitļus
	RandomNumberReset               = Atjaunot
'@