ConvertFrom-StringData -StringData @'
	# ko-KR
	# Korean (Korea)

	FontsUI                   = Malgun Gothic
	Mainname                  = 배포 엔진: Yi 의 제품군
	Learn                     = 공부하다
	MainHisName               = 보너스 솔루션
	Location                  = 오픈 위치
	About                     = 에 대한
	Reset                     = 초기화
	AddTo                     = 에 추가
	Instl                     = 설치
	ItInstalled               = 설치됨
	Close                     = 폐쇄
	Auto                      = 자동적 인
	Disable                   = 장애를 입히다
	Enable                    = 할 수있게하다
	Setting                   = 설정
	Restore                   = 다시 덮다
	CLearn                    = 청소
	Operable                  = 실시 가능한
	Inoperable                = 작동불능
	Optimize                  = 최적화
	Hide                      = 숨다
	Show                      = 보여 주다
	Del                       = 삭제
	Done                      = 완료
	OK                        = 확인
	Cancel                    = 취소
	AllSel                    = 모두 선택
	AllClear                  = 모두 지우기
	Refresh                   = 새로고침
	RefreshModules            = 모든 모듈을 핫 리프레시
	Necessary                 = 필요한 소프트웨어
	MostUsedSoftware          = 일반적으로 사용되는 소프트웨어
	System                    = 체계
	Service                   = 서비스
	TaskBar                   = 작업 표시줄의 모든 아이콘
	DeskIcon                  = 바탕 화면 아이콘
	InstallFonts              = 글꼴 설치
	SettingTo                 = 으로 설정 {0}
	AvailableLanguages        = 사용 가능한 언어입니다
	SwitchLanguage            = 언어 전환
	LanguageReset             = 언어 설정 재설정
	LanguageCode              = 구역 마커
	LanguageSelRegion         = 국가 또는 지역을 선택하세요.
	LanguageRemember          = 선택한 언어 기억
	LanguageSearchNo          = 사용 가능한 언어가 없습니다
	LanguageNoPack            = 로컬에 언어 팩이 없으면 자동으로 종료됩니다.
	LanguageNoSel             = 지역을 선택해주세요
	Search                    = 찾다
	PleaseChoose              = 선택해주세요
	FailedCreateFolder        = 디렉토리 생성 실패
	Failed                    = 실패했습니다
	ToMsg                     = {0} 초 후에 자동으로 메인 메뉴로 돌아갑니다.
	Restart                   = 다시 시작하여 적용
	AdvOption                 = 선택적 기능

	StartDown                 = 开始下载
	ConnectTo                 = 연결 대상
	FileName                  = 파일
	SaveTo                    = 저장 대상
	NotAvailable              = 상태: 사용할 수 없음
	ExistingPacker            = 기존 설치 패키지
	ExistingInstlPacker       = 기존 압축 패키지
	Unpacking                 = 풀다
	QucikRun                  = 빠른 실행: \
	WaitDone                  = 완료 대기: \
	Parameter                 = 매개변수: \
	ErrorDown                 = 다운로드 중 오류가 발생했습니다.
	UserCancel                = 사용자가 작업을 취소했습니다.

	VerifyNameTips            = 영문자와 숫자의 조합만 허용하고 다른 문자는 포함할 수 없습니다: 공백, 길이는 260자를 초과할 수 없습니다, \\ / : * ? & @ ! "" < > |
	FolderLabel               = 사용자 정의 디렉토리 접두사
	NoSetFolderLabel          = 사용자 정의 디렉토리 접두사가 설정되지 않았습니다
	ISO9660TipsErrorSpace     = 포함할 수 없음: 선행 및 후행 공백
	ISO9660TipsErrorOther     = 다음을 포함할 수 없음: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = 레이블 길이는 {0} 자를 초과할 수 없습니다.
	Help                      = 돕다
	WorkDone                  = 완료, 기본 인터페이스로 돌아가려면 아무 키나 누르십시오...
	Short_Cmd                 = 바로 가기 명령
	Options                   = 옵션
'@