ConvertFrom-StringData -StringData @'
	# zh-TW
	# Chinese (Traditional, Taiwan)

	FontsUI                         = Microsoft JhengHei UI

	# Main page
	Dashboard                       = 儀表板
	Learn                           = 學習
	Menu                            = 菜單
	Short_Cmd                       = 快捷指令
	Shortcut                        = 捷徑
	Update                          = 更新
	CUpdate                         = 累積更新
	Rebuild                         = 重建
	AddTo                           = 添加
	Del                             = 删除
	Copy                            = 复制
	Rename                          = 重新命名
	Refresh                         = 刷新
	RefreshModules                  = 熱刷新所有模組
	Done                            = 完成
	OK                              = 確定
	Cancel                          = 取消
	AllSel                          = 選擇所有
	AllClear                        = 清除所有
	Setting                         = 設置
	Change                          = 更改
	Help                            = 幫助
	Logging                         = 紀錄
	AvailableLanguages              = 可用語言
	SwitchLanguage                  = 切換語言
	LanguageSelRegion               = 選擇您的國家或地區
	LanguageRemember                = 記住所選語言
	LanguageSearchNo                = 未搜尋到可用的語言
	LanguageNoSel                   = 請選擇區域
	Search                          = 搜尋
	SearchAllDrives                 = 所有磁碟搜尋
	MountCategory                   = 已搜尋到的所有 ISO，掛載
	PleaseChoose                    = 請選擇
	Options                         = 選項
	Choose                          = 已選擇
	NoChoose                        = 未選擇
	AdvOption                       = 可選功能
	ExcludeItem                     = 按規則排除
	DeDuplication                   = 排除重複項
	DeDuplication_Unlock            = 解锁已禁用重复项
	Existed                         = 已存在
	FailedCreateFolder              = 創建目錄失敗
	FailedCreateFile                = 創建文件失敗
	ToMsg                           = {0} 秒後自動返回到主菜單。
	OnDemandPlanTask                = 自定義分配已知事件
	Operable                        = 可操作
	Inoperable                      = 不可操作
	Hide                            = 隱藏
	CuringUpdate                    = 固化更新
	CuringUpdateTips                = 已固化更新後將不可卸載。
	Healthy                         = 健康
	Healthy_Save                    = 出現可修復、不可修復時，不保存
	Repair                          = 修復
	IsAuto_Repair                   = 允許空閒時自動修復
	IsAuto_Repair_Tips              = 每次執行封裝腳本後自動檢查是否有任意掛載任務。如果有掛載就不執行修復；沒有掛載就執行自動修復工作。
	Repairable                      = 可修復
	NonRepairable                   = 不可修復
	HealthyForceStop                = 處理事件時，遇到不可逆的錯誤，已強行終止。\n\n   造成主要的問題：\n\n      1、物理硬件受損，硬盤；\n\n      2、如果您使用 RAMDISK 內存虛擬盤（含混合），請檢查物理內存；\n\n      3、校驗 MVS (MSDN) 原版 SHA256，如果一致，請重新換目錄後嘗試，如果 SHA256 不一致，請重新下載後嘗試；\n\n      4、其它，不在此例出的。
	Superseded                      = 清理取代的
	SupersededTips                  = 包括過時的更新、組件等
	UnmountFailed                   = 已經用過幾種方法了，無能為力，小弟只能就此罷工了，願與大俠下次江湖見。
	SaveTo                          = 保存到
	WorkDone                        = 完成，按任意鍵返回主界面...
	UserCanel                       = 用戶已取消了請求。
	Uping                           = 生成中
	Exclude_View                    = 查看排除規則
	User_Interaction                = 用戶交互
	Ok_Go_To                        = 可前往
	Ok_Go_To_No                     = 不前往

	Detailed                        = 詳細
	View                            = 查看
	Detailed_View                   = 查看已選規則詳細信息

	AddEnv                          = 將路由功能添加到系統變數
	AddEnvTips                      = 添加後在 PowerShell 任意會話里輸入 Yi 即可回應，例如輸入「Yi-SIP」即可運行封裝。

	Unzip_ISO                       = 提取 ISO
	Unzip_Search_Type               = 搜索目錄 ( {0} )
	ISO_Other                       = 其他文件
	Unzip_Language                  = 語言包
	Unzip_Fod                       = 功能包
	FileName                        = 檔案名稱

	UserCancel                      = 用戶已取消操作。
	MatchMode                       = 匹配
	Failed                          = 失败
	RandomSelect                    = 隨機選擇
	RulePre                         = 预置规则
	RuleOther                       = 其它規則
	RuleCustomize                   = 自定義規則
	RuleCustomize_Dont              = 不使用多级目录自定义规则
	RuleCustomize_Dont_Tips         = 删除旧目录后，点击“验证命名规则”。
	RuleMultistage                  = 多級目錄規則
	RuleMultistageFindFailed        = 未發現有多級目錄規則，點我創建糢闆。
	RuleMultistageFindCreateNew     = 創建新的多級目錄規則模板
	RuleMultistageTips              = 自動適配多級目錄規則，已禁用 {0} 目錄規則。
	RuleCustomizeNot                = 未發現擴展名稱（Solutions.Custom.Extension），請參閱幫助文檔。
	RuleCustomizeTips               = 未新建自定義規則，請參閱幫助文檔。
	RuleMatchNoFindFolder           = 優先匹配後，未發現，點我創建目錄。
	RuleNoFindFile                  = 未發現有可用的文件，請添加後刷新。
	RuleFindFolder                  = 目錄可用時，自動選擇
	RuleNameNewChange               = 更新後自動同步
	RuleNewTempate                  = 創建範本
	RuleSkipFolderCheck             = 不再檢查目錄裡是否存在檔，檔案類型
	RuleAuthon                      = 規則建立者
	RuleGUID                        = GUID 全域唯一標識碼
	RuleName                        = 規則名稱
	RuleDescription                 = 描述
	RuleNameUse                     = 同步規則名稱到：{0}
	RuleISO                         = 匹配原始 InBox Apps 安裝包
	RuleInBoxApps                   = 完整，預配的應用程式
	RuleFileType                    = 軟體包名稱
	RuleFileFind                    = 模糊查找名
	RuleFindError                   = 發現 {0} 項待處理，點擊「檢查依賴項」查看詳細。
	RuleSelectApps                  = 用戶已選取的應用程式
	DependencyPackage               = 依賴套件
	RuleDependenciesRequired        = 所需要的依賴項
	RuleDependenciesUnselected      = 未選擇的依賴項
	RuleDependenciesNoCheck         = 不再檢查依賴項
	RuleDependenciesFix             = 修復未選擇依賴項
	Extract_Tips                    = 提示\n\n   1、提取語言包後的結果，並不能做為主要參照對象；\n\n   2、請通過組件列表做為主要參照對象，如何生成：\n\n       在 Functions 裡選擇生成組件（獲取已安裝映像中的包），選擇打印或即時查看；\n\n   3、安裝完語言包後，請重新生成一份組件報告，查看是否已對應；

	DescendingRuleLang              = 按相反的順序刪除語言包
	OrderRuleLang                   = 按預規則順序安裝語言包
	OrderRuleLangTips               = 按順序添加：基本、字體、光學字符識別、手寫內容識別、文本轉語音、語音識別、零售演示體驗、其它
	RuleLanguageTips                = 說明：\n\n   使用“按預規則順序安裝語言包”後，按以下順序自動按模糊名匹配文件：\n
	Match_installed_List            = 安裝語言包時，從已安裝列表里通配
	Match_installed_List_Tips       = 安裝時僅匹配：基本、光學字符識別、手寫內容識別、文字轉語音、語音識別。
	RuleLanguageTipsExt             = \n   不使用“按預規則順序安裝語言包”時：\n   自動按文件類型，搜索目錄下的所有文件，並安裝。\n\n   語言和區域按需功能 (FOD)\n   https://learn.microsoft.com/zh-tw/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = 分類中
	Basic                           = 基本
	Fonts                           = 字體
	OCR                             = 光學字符識別
	Handwriting                     = 手寫內容識別
	TextToSpeech                    = 文本轉語音
	Speech                          = 語音識別
	Retail                          = 零售演示體驗
	Features_On_Demand              = 按需功能
	RegionSpecific                  = 其他區域特定的要求
	UnassignedLangFiles             = 未分配嘅雜項文件

	ProcessingImage                 = 處理映像：
	NoInstallImage                  = 本地不存在
	ConvertChk                      = 檢查文件
	WindowsFeature                  = Windows 功能
	Enable                          = 啟用
	Disable                         = 禁用
	EnableFeatureTips               = 提示\n\n    1、顯示 NetFx3、TelnetClient 是預置啟用功能項；\n\n    2、“掛載”後，可啟用更多的。
	ViewLanguage                    = 查看映像語言設置
	ImageLanguage                   = 映像語言設置
	OnlyLangCleanup                 = 清理元件：按語言標記
	Matched_Component_Names         = 已匹配組件名：
	BootProcess                     = 处理 {0}.wim 时
	Sync_Language_To                = 同步到
	BootSyncToISO                   = 同步語言包到安裝程式
	BootSyncToISOTips               = 離線映射已安裝的語言包，同步到 ISO 安裝程式裡。
	LangIni                         = 重新生成 Lang.ini
	LangIniTips                     = 同步完成后需重建 ISO 里的 Lang.ini。
	LangNewAutoSelect               = 有事件時自動選擇建議項
	LangNewAutoSelectTips           = 有新事件，已選擇「同步語言包到安裝程式」、“重建 Lang.ini”。
	LangNewAutoNoSelect             = 有新事件，建議你選擇「同步語言包到安裝程式」、“重建 Lang.ini”。
	LangNewAutoNoNewSelect          = 沒有新的事件，建議你不選擇「同步語言包到安裝程式」、“重建 Lang.ini”。
	Drive                           = 驅動
	ViewDrive                       = 查看已安裝驅動
	Editions                        = 映像版本
	Assign_Editions                 = 自動根據映像版本指派應用程式

	SelFile                         = 選擇文件
	Rebuilding                      = 重建中
	RebuildAll                      = 重建全部
	Export_Image                    = 匯出
	SelectFromError                 = 錯誤
	SelectFileFormatError           = 文件格式不正確

	SearchDrive                     = 搜索驅動
	SearchUpdate                    = 搜索更新，類型 ( {0} ), 來源：
	SelectFolder                    = 選擇目錄
	DropFolder                      = 可托動目錄到當前窗口
	DropFile                        = 可托動文件到當前窗口
	Sparse                          = 稀哈
	CRCSHA                          = 校驗
	Alternative                     = 替代檔名
	ChangeInstallDisk               = 更改自動選擇磁盤
	Backup                          = 備份
	Restore                         = 還原
	Import                          = 導入

	# View
	ExportToLogs                    = 打印報告到日誌裡
	ExportShow                      = 顯示報表
	MoreFeature                     = 更多功能
	OpenFolder                      = 打開目錄
	OpenFile                        = 開啟文件
	Running                         = 运行
	Paste                           = 複製路徑
	Clipboard_Copy                  = 已複製到剪貼板
	ViewWIMFileInfo                 = 檢視映像
	GetInBoxApps                    = InBox Apps: 已安裝的應用程式包
	GetImagePackage                 = 組件：映像中已安裝的所有包
	ViewMounted                     = 獲取有關所有已掛載映像的信息
'@