ConvertFrom-StringData -StringData @'
	# bg-BG
	# Bulgarian (Bulgaria)

	FontsUI                   = Segoe UI
	Mainname                  = Машина за внедряване: пакетът на Yi
	Learn                     = Проучване
	MainHisName               = Бонус решение
	Location                  = Отворено местоположение
	About                     = Около
	Reset                     = Нулиране
	AddTo                     = Добавете към
	Instl                     = Инсталирайте
	ItInstalled               = Инсталиран
	Close                     = Закриване
	Auto                      = Автоматичен
	Disable                   = Деактивиране
	Enable                    = Активирайте
	Setting                   = Настроен
	Restore                   = Възстанови се
	Clean                     = Почиствам
	Operable                  = Оперативен
	Inoperable                = Неработоспособен
	Optimize                  = Оптимизация
	Hide                      = Скрий се
	Show                      = Шоу
	Del                       = Изтрий
	Done                      = Завършете
	OK                        = Разбира се
	Cancel                    = Отказ
	AllSel                    = Изберете всички
	AllClear                  = Изчисти всичко
	Refresh                   = Опресняване
	RefreshModules            = Горещо опресняване на всички модули
	Necessary                 = Основен софтуер
	MostUsedSoftware          = Често използван софтуер
	System                    = Система
	Service                   = Сервирайте
	TaskBar                   = Всички икони в лентата на задачите
	DeskIcon                  = Икони на работния плот
	InstallFonts              = Инсталиране на шрифтове
	SettingTo                 = Задаване на {0}
	Command                   = Команден ред
	RuleName                  = Име на правилото
	Language                  = Език
	AvailableLanguages        = Налични езици
	SwitchLanguage            = Превключване на езика
	LanguageReset             = Нулиране на езиковите настройки
	LanguageCode              = Знак за зона
	LanguageSelRegion         = Изберете вашата страна или регион
	LanguageRemember          = Запомнете избрания език
	LanguageSearchNo          = Няма намерени налични езици
	LanguageNoSel             = Моля, изберете регион
	Search                    = Търсене
	PleaseChoose              = Моля изберете
	FailedCreateFolder        = Неуспешно създаване на директория
	Failed                    = Провалят се
	ToMsg                     = {0} Автоматично връщане към главното меню след секунди.
	Restart                   = Рестартирането влиза в сила
	AdvOption                 = Функции по избор

	StartDown                 = Започнете да изтегляте
	ConnectTo                 = Свържете се с
	FileName                  = Име на файл
	SaveTo                    = Запази в
	NotAvailable              = Състояние: Не е налично
	ExistingPacker            = Вече има инсталационен пакет
	ExistingInstlPacker       = Вече имате компресиран пакет
	Unpacking                 = Разархивиране
	QucikRun                  = Бързо бягане:
	WaitDone                  = В очакване на завършване:
	Parameter                 = Параметър:
	ErrorDown                 = Възникна грешка по време на изтеглянето
	UserCancel                = Потребителят е отменил операцията.

	VerifyNameTips            = Допуска се само комбинация от английски букви и цифри и не се допускат други знаци: интервали, дължината не може да надвишава 16 знака, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Персонализиран префикс на директория
	NoSetFolderLabel          = Персонализираният префикс на директорията не е зададен
	ISO9660TipsErrorSpace     = Не може да съдържа: водещи и завършващи интервали
	ISO9660TipsErrorOther     = Не може да съдържа: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Етикетът на тома не може да бъде по-дълъг от {0} знака
	Help                      = Помощ
	WorkDone                  = Завършено, натиснете произволен клавиш, за да се върнете към основния интерфейс...
	Short_Cmd                 = Преки пътища
	Options                   = Опции
	LXPsWaitAssign            = Да бъдат разпределени
	Running                   = Тичам
	SpecialFunction           = Функции на PowerShell
'@