ConvertFrom-StringData -StringData @'
	# nb-NO
	# Norwegian, Bokmål (Norway)

	FontsUI                   = Segoe UI
	Mainname                  = Utrullingsmotor: Yi's suite
	Learn                     = Studere
	MainHisName               = Bonusløsning
	Location                  = Åpen plassering
	About                     = Ca
	Reset                     = Tilbakestille
	AddTo                     = Legg til
	Instl                     = Installer
	ItInstalled               = Installert
	Close                     = Stenging
	Auto                      = Automatisk
	Disable                   = Deaktiver
	Enable                    = Aktivere
	Setting                   = Sette opp
	Restore                   = Komme seg
	Clean                     = Rydde opp
	Operable                  = Brukbar
	Inoperable                = Ubrukelig
	Optimize                  = Optimalisering
	Hide                      = Gjemme
	Show                      = Vise
	Del                       = Slette
	Done                      = Fullfør
	OK                        = Sikker
	Cancel                    = Kansellere
	AllSel                    = Velg alle
	AllClear                  = Fjern alt
	Refresh                   = Forfriske
	RefreshModules            = Varm oppdater alle moduler
	Necessary                 = Essensiell programvare
	MostUsedSoftware          = Vanlig brukt programvare
	System                    = System
	Service                   = Tjene
	TaskBar                   = Alle ikoner på oppgavelinjen
	DeskIcon                  = Skrivebordsikoner
	InstallFonts              = Installer fonter
	SettingTo                 = Sett til {0}
	Command                   = Kommandolinje
	RuleName                  = Regelnavn
	Language                  = Språk
	AvailableLanguages        = Tilgjengelige språk
	SwitchLanguage            = Bytte språk
	LanguageReset             = Tilbakestill språkinnstillinger
	LanguageCode              = Sonemerke
	LanguageSelRegion         = Velg ditt land eller din region
	LanguageRemember          = Husk valgt språk
	LanguageSearchNo          = Ingen tilgjengelige språk funnet
	LanguageNoSel             = Vennligst velg en region
	Search                    = Søk
	PleaseChoose              = Vennligst velg
	FailedCreateFolder        = Kunne ikke opprette katalog
	Failed                    = Mislykkes
	ToMsg                     = {0} Gå automatisk tilbake til hovedmenyen etter sekunder.
	Restart                   = Omstart trer i kraft
	AdvOption                 = Valgfrie funksjoner

	StartDown                 = Start nedlastingen
	ConnectTo                 = Koble til
	FileName                  = Filnavn
	SaveTo                    = Lagre til
	NotAvailable              = Status: Ikke tilgjengelig
	ExistingPacker            = Har allerede installasjonspakken
	ExistingInstlPacker       = Har allerede en komprimert pakke
	Unpacking                 = Pakning ut
	QucikRun                  = Raskt løp:
	WaitDone                  = Venter på ferdigstillelse:
	Parameter                 = Parameter:
	ErrorDown                 = Det oppsto en feil under nedlasting
	UserCancel                = Brukeren har avbrutt operasjonen.

	VerifyNameTips            = Bare en kombinasjon av engelske bokstaver og tall er tillatt, og ingen andre tegn er tillatt: mellomrom, lengden kan ikke være større enn 16 tegn, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Egendefinert katalogprefiks
	NoSetFolderLabel          = Egendefinert katalogprefiks ikke angitt
	ISO9660TipsErrorSpace     = Kan ikke inneholde: førende og etterfølgende mellomrom
	ISO9660TipsErrorOther     = Kan ikke inneholde: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Volumetiketten kan ikke være lengre enn {0} tegn
	Help                      = Hjelp
	WorkDone                  = Fullført, trykk på en tast for å gå tilbake til hovedgrensesnittet...
	Short_Cmd                 = Snarveier
	Options                   = Alternativer
	LXPsWaitAssign            = Skal tildeles
	Running                   = Løp
	SpecialFunction           = PowerShell-funksjoner
'@