ConvertFrom-StringData -StringData @'
	# sk-SK
	# Slovak (Slovakia)

	FontsUI                   = Segoe UI
	Mainname                  = Nasadzovací motor: Yiho sada
	Learn                     = Štúdium
	MainHisName               = Bonusové riešenie
	Location                  = Otvoriť umiestnenie
	About                     = O
	Reset                     = Resetovať
	AddTo                     = Pridať do
	Instl                     = Inštalovať
	ItInstalled               = Nainštalované
	Close                     = Uzavretie
	Auto                      = Automatické
	Disable                   = Zakázať
	Enable                    = Povoliť
	Setting                   = Nastaviť
	Restore                   = Zotaviť sa
	CLearn                    = Upratať
	Operable                  = Funkčné
	Inoperable                = Nefunkčné
	Optimize                  = Optimalizácia
	Hide                      = Skryť
	Show                      = Ukázať
	Del                       = Vymazať
	Done                      = Dokončiť
	OK                        = Jasné
	Cancel                    = Zrušiť
	AllSel                    = Vybrať všetko
	AllClear                  = Vymazať všetko
	Refresh                   = Osviežiť
	RefreshModules            = Horúca obnova všetkých modulov
	Necessary                 = Nevyhnutný softvér
	MostUsedSoftware          = Bežne používaný softvér
	System                    = Systém
	Service                   = Podávajte
	TaskBar                   = Všetky ikony na paneli úloh
	DeskIcon                  = Ikony na ploche
	InstallFonts              = Nainštalujte písma
	SettingTo                 = Nastaviť na {0}
	AvailableLanguages        = Dostupné jazyky
	SwitchLanguage            = Prepnúť jazyk
	LanguageReset             = Obnovte nastavenia jazyka
	LanguageCode              = Zónová značka
	LanguageSelRegion         = Vyberte svoju krajinu alebo región
	LanguageRemember          = Zapamätať si vybraný jazyk
	LanguageSearchNo          = Nenašli sa žiadne dostupné jazyky
	LanguageNoPack            = Ak lokálny jazykový balík neexistuje, automaticky sa ukončí.
	LanguageNoSel             = Vyberte región
	Search                    = Hľadať
	PleaseChoose              = Vyberte
	FailedCreateFolder        = Nepodarilo sa vytvoriť adresár
	Failed                    = Zlyhať
	ToMsg                     = {0} Po niekoľkých sekundách sa automaticky vráti do hlavnej ponuky.
	Restart                   = Reštart sa prejaví
	AdvOption                 = Voliteľné funkcie

	StartDown                 = Začnite sťahovať
	ConnectTo                 = Pripojte sa k
	FileName                  = Názov súboru
	SaveTo                    = Uložiť do
	NotAvailable              = Stav: Nie je k dispozícii
	ExistingPacker            = Už máte inštalačný balík
	ExistingInstlPacker       = Už máte komprimovaný balík
	Unpacking                 = Rozopínanie
	QucikRun                  = Rýchly beh:
	WaitDone                  = Čaká sa na dokončenie:
	Parameter                 = Parameter:
	ErrorDown                 = Počas sťahovania sa vyskytla chyba
	UserCancel                = Používateľ zrušil operáciu.

	VerifyNameTips            = Je povolená iba kombinácia anglických písmen a číslic a nie sú povolené žiadne iné znaky: medzery, dĺžka nemôže byť väčšia ako 16 znakov, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Vlastná predpona adresára
	NoSetFolderLabel          = Vlastná predpona adresára nie je nastavená
	ISO9660TipsErrorSpace     = Nemôže obsahovať: medzery na začiatku a na konci
	ISO9660TipsErrorOther     = Nemôže obsahovať: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Menovka zväzku nemôže byť dlhšia ako {0} znakov
	Help                      = Pomôcť
	WorkDone                  = Dokončené, stlačením ľubovoľného klávesu sa vrátite do hlavného rozhrania...
	Short_Cmd                 = Skratky
	Options                   = Možnosti
'@