ConvertFrom-StringData -StringData @'
	# et-EE
	# Estonian (Estonia)

	FontsUI                   = Segoe UI
	Mainname                  = Juurutusmootor: Yi komplekt
	Learn                     = Uuring
	MainHisName               = Boonuslahendus
	Location                  = Ava asukoht
	About                     = Umbes
	Reset                     = Lähtestada
	AddTo                     = Lisa juurde
	Instl                     = Installige
	ItInstalled               = Paigaldatud
	Close                     = Sulgemine
	Auto                      = Automaatne
	Disable                   = Keela
	Enable                    = Lubada
	Setting                   = Üles seada
	Restore                   = Taastuda
	CLearn                    = Koristama
	Operable                  = Kasutatav
	Inoperable                = Kasutuskõlbmatu
	Optimize                  = Optimeerimine
	Hide                      = Peita
	Show                      = Näidata
	Del                       = Kustutada
	Done                      = Lõpeta
	OK                        = Muidugi
	Cancel                    = Tühista
	AllSel                    = Valige kõik
	AllClear                  = Tühjenda kõik
	Refresh                   = Värskenda
	RefreshModules            = Kõigi moodulite kuumvärskendus
	Necessary                 = Oluline tarkvara
	MostUsedSoftware          = Tavaliselt kasutatav tarkvara
	System                    = Süsteem
	Service                   = Serveeri
	TaskBar                   = Kõik tegumiriba ikoonid
	DeskIcon                  = Töölaua ikoonid
	InstallFonts              = Installige fondid
	SettingTo                 = Määra väärtusele {0}
	AvailableLanguages        = Saadaolevad keeled
	SwitchLanguage            = Keelt vahetada
	LanguageReset             = Keeleseadete lähtestamine
	LanguageCode              = Tsooni märk
	LanguageSelRegion         = Valige oma riik või piirkond
	LanguageRemember          = Jäta valitud keel meelde
	LanguageSearchNo          = Saadaolevaid keeli ei leitud
	LanguageNoPack            = Kui kohalikku keelepaketti pole, suletakse see automaatselt.
	LanguageNoSel             = Valige piirkond
	Search                    = Otsida
	PleaseChoose              = Palun valige
	FailedCreateFolder        = Kataloogi loomine ebaõnnestus
	Failed                    = Ebaõnnestuda
	ToMsg                     = {0} Naaske sekundite pärast automaatselt peamenüüsse.
	Restart                   = Taaskäivitamine jõustub
	AdvOption                 = Valikulised funktsioonid

	StartDown                 = Alusta allalaadimist
	ConnectTo                 = Ühendage
	FileName                  = Faili nimi
	SaveTo                    = Salvestada
	NotAvailable              = Olek: Pole saadaval
	ExistingPacker            = Installimispakett on juba olemas
	ExistingInstlPacker       = Sul on juba kokkusurutud pakend
	Unpacking                 = Lahtipakkimine
	QucikRun                  = Kiire jooks:
	WaitDone                  = Ootan valmimist:
	Parameter                 = Parameeter:
	ErrorDown                 = Allalaadimise ajal ilmnes viga
	UserCancel                = Kasutaja on toimingu tühistanud.

	VerifyNameTips            = Lubatud on ainult ingliskeelsete tähtede ja numbrite kombinatsioon ning muud tähemärgid pole lubatud: tühikud, pikkus ei tohi olla pikem kui 16 tähemärki, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Kohandatud kataloogi eesliide
	NoSetFolderLabel          = Kohandatud kataloogi eesliide pole määratud
	ISO9660TipsErrorSpace     = Ei tohi sisaldada ees- ja lõpptühikuid
	ISO9660TipsErrorOther     = Ei tohi sisaldada: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Köite silt ei tohi olla pikem kui {0} tähemärki
	Help                      = Abi
	WorkDone                  = Lõpetatud, vajutage põhiliidesele naasmiseks suvalist klahvi...
	Short_Cmd                 = Otseteed
	Options                   = Valikud
'@