ConvertFrom-StringData -StringData @'
	# pl-PL
	# Polish (Poland)

	UnpackISO                       = Wygeneruj ISO
	ISOLabel                        = Ustawiono etykietę woluminu:
	ISOCustomize                    = Nazwa etykiety woluminu ISO
	ISO9660                         = Sprawdź zasady nazewnictwa
	ISO9660Tips                     = Unikalna nazwa nie może przekraczać 260 znaków, nazwa woluminu ISO nie może przekraczać 16 znaków i nie może zawierać: spacji początkowych i końcowych, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Niestandardowe, unikalne nazewnictwo
	ISOAddFlagsLang                 = Dodaj wielojęzyczne znaczniki
	ISOAddFlagsLangGet              = Poznaj znane języki instalacji
	ISOAddFlagsVer                  = Dodaj tag wielu wersji
	ISOAddFlagsVerGet               = Uzyskaj znaną wersję obrazu
	ISOAddEICFG                     = Dodaj typ wersji
	ISOAddEICFGTips                 = W przypadku korzystania z pliku EI.cfg jest to wersja komercyjna.
	ISO9660TipsErrorSpace           = Nie może zawierać: spacji początkowych i końcowych
	ISO9660TipsErrorOther           = Nie może zawierać: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Wybierz typ języka
	SelLabel                        = Nazwa kodowa
	ISOVerLabel                     = Wybierz nazwę woluminu ISO
	NoSetLabel                      = Nie ustawiono niestandardowej etykiety woluminu ISO
	ISOLengthError                  = Etykieta woluminu nie może być dłuższa niż {0} znaków
	RenameFailed                    = Taki sam jak stary katalog, zmiana nazwy nie powiodła się
	ISOCreateAfter                  = Co należy zrobić przed utworzeniem obrazu ISO
	ISOCreateRear                   = Co należy zrobić po utworzeniu obrazu ISO
	BypassTPM                       = Pomiń kontrolę instalacji modułu TPM
	Disable_BitLocker               = Wyłącz szyfrowanie urządzenia funkcją BitLocker podczas instalacji
	PublicDate                      = Data wydania
	PublicDateGetCurrent            = Synchronizuj bieżącą datę
	PublicYear                      = Rok
	PublicMonth                     = Księżyc
	PublicYMSorting                 = Sortuj: Zmień "miesiąc_rok" na "rok_miesiąc"
	PublicYMSortingTips             = AB: Nie dodawaj znaku podkreślenia _ podczas używania liczb.
	PublicYMUseShortNames           = Używaj krótkich nazw
	PublicYMUseNumbers              = Używaj liczb
	ISOCreateFailed                 = Utworzenie nie powiodło się, katalogu nie można odczytać ani zapisać.
	ISORefreshAuto                  = Odśwież znaczniki ISO za każdym razem
	ISOSaveTo                       = Domyślna lokalizacja zapisu ISO
	ISOSaveSameGlobal               = Użyj globalnej domyślnej lokalizacji zapisu ISO
	ISOSaveSync                     = Automatycznie synchronizuj nową lokalizację po wybraniu dysku wyszukiwania źródła obrazu
	ISOSaveSame                     = Wyszukaj ścieżkę dysku, korzystając ze źródła obrazu
	ISOFolderWrite                  = Sprawdź, czy katalog jest czytelny i zapisywalny
	SelectAutoAvailable             = Podczas automatycznego wybierania dostępnego dysku
	SelectCheckAvailable            = Sprawdź minimalną pozostałą ilość wolnego miejsca
	ISOStructure                    = Nowa struktura katalogów
	ISOOSLevel                      = Dodaj typ instalacji
	ISOUniqueNameDirectory          = Dodaj unikalny katalog nazw
	NextDoOperate                   = Nie twórz ISO
	SelCreateISO                    = Wygeneruj ISO, wykonaj na żądanie
	Reconstruction                  = Odbuduj plik {0}.wim z maksymalną kompresją
	Reconstruction_Tips_Select      = Przed przebudowaniem zostanie wykonany tylko wtedy, gdy nie jest załadowany. Wymusi to włączenie zapisu, a następnie odmontowanie zamontowanego pliku.
	ReconstructionTips              = Ponad 520 MB, zalecana jest odbudowa
	CreateASC                       = Dodaj podpis PGP do ISO
	NoPGPKey                        = W PGP nie ma użytecznego klucza prywatnego.
	CreateASCPwd                    = Hasło certyfikatu
	PasswordRenter                  = Wprowadź ponownie hasło
	ShowPassword                    = Pokaż hasło
	NewPasswordSome                 = Hasło nie pasuje.
	PwdPermanent                    = Pamięć trwała
	PwdDecfailed                    = Odszyfrowanie nie powiodło się
	CreateASCAuthor                 = Podpisujący
	CreateASCAuthorTips             = Nie wybrano sygnatariuszy.
	ISO_Sparse_Rename               = Dodaj skrót do rozszerzenia nazwy pliku
	GenerateRandom                  = Generuj liczby losowe
	RandomNumberReset               = Zregenerować
'@