ConvertFrom-StringData -StringData @'
	# ar-sa
	# Arabic (Saudi Arabia)

	IsCreate                        = يخلق
	Solution                        = حل
	EnabledSoftwarePacker           = مجموعة
	EnabledUnattend                 = ينبغي الإجابة مقدما
	EnabledEnglish                  = محرك النشر
	UnattendSelectVer               = حدد لغة الحل "الإجابة على".
	UnattendLangPack                = حدد حزمة اللغة "الحل".
	UnattendSelectSingleInstl       = متعدد اللغات، اختياري أثناء التثبيت
	UnattendSelectMulti             = متعدد اللغات
	UnattendSelectDisk              = حدد الحل Autounattend.xml
	UnattendSelectSemi              = نصف تلقائي صالح لجميع طرق التثبيت
	UnattendSelectUefi              = UEFI التثبيت التلقائي، تحتاج إلى تحديد
	UnattendSelectLegacy            = Legacy التثبيت التلقائي، تحتاج إلى تحديد
	NeedSpecified                   = الرجاء تحديد ما يجب تحديده:
	OOBESetupOS                     = واجهة التثبيت
	OOBEProductKey                  = مفتاح المنتج
	OOBEOSImage                     = حدد نظام التشغيل المراد تثبيته
	OOBEEula                        = قبول شروط الترخيص
	OOBEDoNotServerManager          = لا يبدأ تشغيل Server Manager تلقائيًا عند تسجيل الدخول
	OOBEIE                          = تكوين الأمان المحسّن لبرنامج Internet Explorer
	OOBEIEAdmin                     = إغلاق "المسؤول"
	OObeIEUser                      = إغلاق "المستخدمون"

	OOBE_Init_User                  = المستخدم الأولي أثناء تجربة فتح العلبة
	OOBE_init_Create                = إنشاء مستخدمين مخصصين
	OOBE_init_Specified             = تحديد المستخدم
	OOBE_Init_Autologin             = تسجيل الدخول التلقائي

	InstlMode                       = طريقة التثبيت
	Business                        = نسخة الأعمال
	BusinessTips                    = اعتمادًا على EI.cfg، يجب تحديد رقم الفهرس للتثبيت التلقائي.
	Consumer                        = نسخة المستهلك
	ConsumerTips                    = لا يعتمد على EI.cfg. يتطلب التثبيت التلقائي تحديد الرقم التسلسلي عند الإيقاف المؤقت في واجهة اختيار الإصدار، ويجب تحديد رقم الفهرس.。
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [جبل ل]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = إضافة إلى اسم الدليل الرئيسي لقرص النظام
	VerifyNameUse                   = تحقق من أن اسم الدليل لا يمكن أن يحتوي على
	VerifyNameTips                  = يُسمح فقط بمزيج من الأحرف والأرقام الإنجليزية، ولا يمكن أن يحتوي على: مسافات، ولا يمكن أن يزيد الطول عن 260 حرفًا، \\ / : * & @ "" < > |
	VerifyNumberFailed              = فشل التحقق، الرجاء إدخال الرقم الصحيح.
	VerifyNameSync                  = قم بتعيين اسم الدليل كاسم مستخدم أساسي
	VerifyNameSyncTips              = لم يعد administrator مستخدمًا
	ManualKey                       = حدد أو أدخل مفتاح المنتج الخاص بك يدويًا
	ManualKeyTips                   = أدخل مفتاح منتج صالحًا. إذا كانت المنطقة المحددة غير متوفرة، فيرجى الانتقال إلى موقع Microsoft الرسمي للتحقق.
	ManualKeyError                  = مفتاح المنتج الذي أدخلته غير صالح.
	KMSLink1                        = مفتاح إعدادات عميل KMS
	KMSUnlock                       = إظهار كافة الأرقام التسلسلية KMS المعروفة
	KMSSelect                       = الرجاء تحديد الرقم التسلسلي VOL
	KMSKey                          = رقم سري
	KMSKeySelect                    = تغيير الرقم التسلسلي للمنتج
	ClearOld                        = تنظيف الملفات القديمة
	SolutionsSkip                   = تخطي إنشاء الحل
	SolutionsTo                     = أضف "الحل" إلى:
	SolutionsToMount                = تم تركيبه أو إضافته إلى قائمة الانتظار
	SolutionsToError                = تم تعطيل بعض الوظائف إذا كنت بحاجة إلى إجبارهم على الاستخدام، يرجى النقر على زر "فتح".\n\n
	UnlockBoot                      = فتح
	SolutionsToSources              = الدليل الرئيسي، [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = حدد إصدار "محرك النشر".
	SolutionsEngineRegionaUTF8      = الإصدار التجريبي: دعم اللغة العالمية باستخدام Unicode UTF-8
	SolutionsEngineRegionaUTF8Tips  = ويبدو أنه قد يسبب مشاكل جديدة بعد فتحه. غير مستحسن.
	SolutionsEngineRegionaling      = التغيير إلى لغة جديدة:
	SolutionsEngineRegionalingTips  = قم بتغيير لغة النظام، التي تؤثر على كافة حسابات المستخدمين على الكمبيوتر.
	SolutionsEngineRegional         = تغيير لغة النظام
	SolutionsEngineRegionalTips     = الافتراضي العام: {0}، تم التغيير إلى: {1}
	SolutionsEngineCopyPublic       = انسخ {0} العام للنشر
	SolutionsEngineCopyOpen         = تصفح موقع المستودع العام {0}.
	EnglineDoneReboot               = أعد تشغيل جهاز الكمبيوتر الخاص بك
	SolutionsTipsArm64              = يُفضل استخدام حزمة Arm64، وقم بالاختيار بالترتيب: x64، x86.
	SolutionsTipsAMD64              = تفضل حزم x64، بالترتيب: x86.
	SolutionsTipsX86                = تتم إضافة حزم x86 فقط.
	SolutionsReport                 = إنشاء تقرير ما قبل النشر
	SolutionsDeployOfficeInstall    = نشر حزمة تثبيت Microsoft Office
	SolutionsDeployOfficeChange     = تغيير تكوين النشر
	SolutionsDeployOfficePre        = إصدار الحزمة المثبتة مسبقًا
	SolutionsDeployOfficeNoSelect   = لم يتم تحديد حزمة التثبيت المسبق لـ Office
	SolutionsDeployOfficeVersion    = نسخة {0}.
	SolutionsDeployOfficeOnly       = احتفظ بحزم اللغات المحددة
	SolutionsDeployOfficeSync       = الحفاظ على مزامنة اللغة لتكوين النشر
	SolutionsDeployOfficeSyncTips   = بعد المزامنة، لا يمكن لبرنامج التثبيت النصي تحديد اللغة المفضلة.
	DeploySyncMainLanguage          = تزامن مع اللغة الرئيسية
	SolutionsDeployOfficeTo         = نشر حزمة التثبيت ل
	SolutionsDeployOfficeToPublic   = سطح المكتب العام
	DeployPackage                   = نشر حزمة مجموعة مخصصة
	DeployPackageSelect             = حدد حزمة ما قبل التجميع
	DeployPackageTo                 = قم بنشر حزمة التجميع المسبق لـ
	DeployToRoot                    = قرص النظام
	DeployPackageToSolutions        = في الدليل الرئيسي للحل
	DeployTimeZone                  = المنطقة الزمنية
	DeployTimeZoneChange            = تغيير المنطقة الزمنية
	DeployTimeZoneChangeTips        = قم بتعيين المنطقة الزمنية الافتراضية حيث يجب الرد على الإجابات المسبقة، حسب منطقة اللغة.

	Deploy_Tags                     = علامة النشر
	FirstExpProcess                 = تجربة المرة الأولى، أثناء متطلبات النشر:
	FirstExpProcessTips             = بعد الانتهاء من المتطلبات الأساسية، قم بإعادة تشغيل الكمبيوتر لحل مشكلة طلب إعادة التشغيل حتى تصبح نافذة المفعول.
	FirstExpFinish                  = تجربة لأول مرة بعد استكمال المتطلبات الأساسية
	FirstExpSyncMark                = السماح بالبحث العالمي ومزامنة علامات النشر
	FirstExpDefender                = أضف الدليل الرئيسي للدفاع عن الدلائل المستبعدة
	FirstExpSyncLabel               = تسمية وحدة تخزين قرص النظام: اسم الدليل الرئيسي هو نفسه
	MultipleLanguages               = عند مواجهة لغات متعددة:
	NetworkLocationWizard           = معالج موقع الشبكة
	PreAppxCleanup                  = حظر مهام صيانة تنظيف Appx
	LanguageComponents              = منع تنظيف حزم اللغات المميزة عند الطلب غير المستخدمة
	PreventCleaningUnusedLP         = منع تنظيف حزم اللغات غير المستخدمة
	FirstExpContextCustomize        = إضافة "قائمة سياق" مخصصة
	FirstExpContextCustomizeShift   = اضغط باستمرار على مفتاح Shift وانقر بزر الماوس الأيمن

	FirstExpFinishTips              = لا توجد أحداث مهمة بعد اكتمال النشر، ومن المستحسن أن تقوم بالإلغاء.
	FirstExpFinishPopup             = انبثاق الواجهة الرئيسية لمحرك النشر
	FirstExpFinishOnDemand          = السماح بالمعاينة الأولى، كما هو مخطط له
	SolutionsEngineRestricted       = استعادة سياسة تنفيذ Powershell: مقيدة
	EnglineDoneClearFull            = حذف الحل بأكمله
	EnglineDoneClear                = احذف محرك النشر واحتفظ بالمحرك الآخر

	Unattend_Auto_Fix_Next          = في المرة التالية التي تواجه فيها هذه المشكلة، حدد العناصر الضرورية تلقائيًا لإصلاحها تلقائيًا.
	Unattend_Auto_Fix               = يتم الإصلاح تلقائيًا عند عدم تحديد المتطلبات الأساسية
	Unattend_Auto_Fix_Tips          = عند إضافة محرك النشر وعدم تحديد أمر التشغيل الأول، يتم إصلاحه وتحديده تلقائيًا: سياسة تنفيذ Powershell: تشغيل محرك النشر دون أي قيود.
	Unattend_Version_Tips           = اختياريًا، قم بالتضمين فقط، استخدم الإعداد الافتراضي لدعم ARM64 وx64 وx86.
	First_Run_Commmand              = أوامر للتشغيل عند النشر لأول مرة
	First_Run_Commmand_Setting      = حدد الأمر للتشغيل
	Command_Not_Class               = لا مزيد من التصنيف التلقائي عند التصفية
	Command_WinSetup                = تثبيت ويندوز
	Command_WinPE                   = ويندوز بي
	Command_Tips                    = يرجى تعيين التشغيل الأول لتطبيقه على: تثبيت Windows، Windows PE\n\nلاحظ أنه عند إضافة محرك نشر، يجب عليك التحقق من التشغيل الأول: سياسة تنفيذ Powershell: مقيدة، تسمح بتشغيل البرامج النصية لمحرك النشر.
	Waring_Not_Select_Command       = عند إضافة محرك نشر، لم يتم تحديد سياسة تنفيذ Powershell: لا تقم بتعيين أي قيود والسماح بتشغيل البرنامج النصي لمحرك النشر، يرجى تحديده والمحاولة مرة أخرى، أو النقر فوق "لم يتم تحديد الإصلاح السريع".
	Quic_Fix_Not_Select_Command     = الحل السريع ليس خيارا

	PowerShell_Unrestricted         = سياسة تنفيذ Powershell: لا توجد قيود
	Allow_Running_Deploy_Engine     = السماح بتشغيل البرامج النصية لمحرك النشر
'@