ConvertFrom-StringData -StringData @'
	# de-DE
	# German (Germany)

	FontsUI                   = Segoe UI
	Mainname                  = Bereitstellungs-Engine: Yi's Suite
	Learn                     = Studie
	MainHisName               = Bonuslösung
	Location                  = Offener Standort
	About                     = Über
	Reset                     = Zurücksetzen
	AddTo                     = Hinzufügen
	Instl                     = Installieren
	ItInstalled               = Installiert
	Close                     = Schließen
	Auto                      = Automatisch
	Disable                   = Deaktivieren
	Enable                    = Aktivieren
	Setting                   = Einstellung
	Restore                   = Wiederherstellen
	Clean                     = Sauber
	Operable                  = Betriebsfähig
	Inoperable                = Funktionsunfähig
	Optimize                  = Optimierung
	Hide                      = Verstecken
	Show                      = Zeigen
	Del                       = Löschen
	Done                      = Fertig
	OK                        = OK
	Cancel                    = Abbrechen
	AllSel                    = Alles auswählen
	AllClear                  = Alles löschen
	Refresh                   = Auffrischen
	RefreshModules            = Hot-Refresh aller Module
	Necessary                 = Notwendige Software
	MostUsedSoftware          = Häufig verwendete Software
	System                    = System
	Service                   = Dienst
	TaskBar                   = Alle Icons in der Taskleiste
	DeskIcon                  = Desktop Symbol
	InstallFonts              = Schriftarten installieren
	SettingTo                 = Auf {0} gesetzt
	Command                   = Befehlszeile
	RuleName                  = Regelname
	Language                  = Sprache
	AvailableLanguages        = Verfügbare Sprachen
	SwitchLanguage            = Prache wechseln
	LanguageReset             = Spracheinstellungen zurücksetzen
	LanguageCode              = Zonenmarkierung
	LanguageSelRegion         = Wählen Sie Ihr Land oder Ihre Region aus
	LanguageRemember          = Ausgewählte Sprache merken
	LanguageSearchNo          = Keine verfügbaren Sprachen gefunden
	LanguageNoSel             = Bitte wählen Sie eine Region aus
	Search                    = Suchen
	PleaseChoose              = Bitte wählen
	FailedCreateFolder        = Fehler beim Erstellen des Verzeichnisses
	Failed                    = scheitern
	ToMsg                     = Nach {0} Sekunden automatisch zum Hauptmenü zurückkehren.
	Restart                   = Neustart, um wirksam zu werden
	AdvOption                 = Optionale Funktion

	StartDown                 = Download starten
	ConnectTo                 = Verbinden mit
	FileName                  = Dateiname
	SaveTo                    = Speichern unter
	NotAvailable              = Status: Nicht verfügbar
	ExistingPacker            = Vorhandenes Installationspaket
	ExistingInstlPacker       = Vorhandenes komprimiertes Paket
	Unpacking                 = Auspacken
	QucikRun                  = Schnelllauf:
	WaitDone                  = Auf Abschluss warten:
	Parameter                 = Parameter:
	ErrorDown                 = Beim Herunterladen ist ein Fehler aufgetreten
	UserCancel                = Der Benutzer hat den Vorgang abgebrochen.

	VerifyNameTips            = Lassen Sie nur die Kombination aus englischen Buchstaben und Zahlen zu und dürfen keine anderen Zeichen enthalten: Leerzeichen und die Länge darf nicht mehr als 260 Zeichen betragen, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Benutzerdefiniertes Verzeichnispräfix
	NoSetFolderLabel          = Das benutzerdefinierte Verzeichnispräfix ist nicht festgelegt
	ISO9660TipsErrorSpace     = Darf nicht enthalten: führende und nachgestellte Leerzeichen
	ISO9660TipsErrorOther     = Darf nicht enthalten: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Die Etikettenlänge darf nicht mehr als {0} Zeichen betragen
	Help                      = Helfen
	WorkDone                  = Wenn Sie fertig sind, drücken Sie eine beliebige Taste, um zur Hauptoberfläche zurückzukehren ...
	Short_Cmd                 = Verknüpfungen
	Options                   = Optionen
	LXPsWaitAssign            = Zuzuordnen
	Running                   = Laufen
	SpecialFunction           = PowerShell Funktion
'@