ConvertFrom-StringData -StringData @'
	# de-DE
	# German (Germany)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Armaturenbrett
	Learn                           = Studie
	Menu                            = Speisekarte
	Short_Cmd                       = Verknüpfungsbefehl
	Shortcut                        = Abkürzung
	Update                          = Erneuern
	CUpdate                         = kumulative Updates
	Rebuild                         = Wiederaufbau
	AddTo                           = Hinzufügen
	Del                             = Löschen
	Copy                            = Kopieren
	Rename                          = Umbenennen
	Refresh                         = Aktualisierung
	RefreshModules                  = Hot Refresh aller Module
	Done                            = Ziel
	OK                              = Sicher
	Cancel                          = Stornieren
	AllSel                          = Wählen Sie Alle
	AllClear                        = Alles löschen
	Setting                         = Einrichten
	Change                          = Veränderung
	Help                            = Helfen
	Logging                         = Protokoll
	AvailableLanguages              = Verfügbare Sprachen
	SwitchLanguage                  = Sprache wechseln
	LanguageSelRegion               = Wählen Sie Ihr Land oder Ihre Region aus
	LanguageRemember                = Ausgewählte Sprache merken
	LanguageSearchNo                = Keine verfügbaren Sprachen gefunden
	LanguageNoPack                  = Wenn lokal kein Sprachpaket vorhanden ist, wird es automatisch beendet.
	LanguageNoSel                   = Bitte wählen Sie eine Region aus
	Search                          = Suchen
	PleaseChoose                    = Bitte auswählen
	Options                         = Optionen
	Choose                          = Gewählt
	NoChoose                        = Nicht ausgewählt
	AdvOption                       = Optionale Funktionen
	ExcludeItem                     = Per Regel ausschließen
	DeDuplication                   = Duplikate ausschließen
	DeDuplication_Unlock            = Deaktivierte Duplikate freischalten
	Existed                         = Existierte
	FailedCreateFolder              = Verzeichnis konnte nicht erstellt werden
	FailedCreateFile                = Erstellen der Datei fehlgeschlagen
	ToMsg                           = {0} Kehrt nach Sekunden automatisch zum Hauptmenü zurück.
	OnDemandPlanTask                = Bekannte Ereignisse benutzerdefiniert zuweisen
	Operable                        = Betriebsbereit
	Inoperable                      = Funktionsunfähig
	Hide                            = Verstecken
	CuringUpdate                    = Heilungs Update
	CuringUpdateTips                = Es kann nicht deinstalliert werden, nachdem die Firmware aktualisiert wurde.
	Healthy                         = Gesund
	HealthyTips                     = Besonders wichtig ist die Überprüfung des Health Status Bei Anzeige "reparierbar" oder "nicht reparierbar": Während der ESD Konvertierung wird Fehler 13 angezeigt, die Daten sind ungültig, bei der Installation des Systems wird ein Fehler gemeldet.
	Healthy_Save                    = Wenn reparierbar oder nicht reparierbar angezeigt wird, speichern Sie nicht
	Repair                          = Reparatur
	IsAuto_Repair                   = Automatische Reparatur im Leerlauf zulassen
	IsAuto_Repair_Tips              = Überprüfen Sie nach jeder Ausführung des Paketierungsskripts automatisch, ob Montageaufgaben anstehen. Wenn es gemountet ist, wird keine Reparatur durchgeführt; wenn es nicht gemountet ist, wird eine automatische Reparatur ausgeführt.
	Repairable                      = Reparierbar
	NonRepairable                   = Nicht reparierbar
	HealthyForceStop                = Beim Verarbeiten des Ereignisses ist ein irreversibler Fehler aufgetreten und wurde zwangsweise beendet.\n\n   Verursacht das Hauptproblem:\n\n      1. Physischer Hardwareschaden, Festplatte;\n\n      2. Wenn Sie eine virtuelle Festplatte mit RAMDISK Speicher (einschließlich Hybrid) verwenden,\n         überprüfen Sie bitte den physischen Speicher;\n\n      3. Überprüfen Sie den SHA256 der ursprünglichen MVS (MSDN) Version. Wenn derselbe ist,\n         ändern Sie bitte das Verzeichnis und versuchen Sie es erneut.\n         Wenn der SHA256 inkonsistent ist, laden Sie ihn bitte herunter und versuchen Sie es erneut.\n\n      4. Andere, die in diesem Beispiel nicht aufgeführt sind.
	Superseded                      = Aufräumen ersetzt
	SupersededTips                  = Beinhaltet veraltete Updates, Komponenten usw
	UnmountFailed                   = Ich habe bereits mehrere Methoden angewendet, aber ich kann nichts tun. Der jüngere Bruder kann an dieser Stelle nur zuschlagen. Ich bin bereit, dich das nächste Mal mit den Helden zu sehen.
	SaveTo                          = Speichern unter
	WorkDone                        = Fertig, drücken Sie eine beliebige Taste, um zur Hauptschnittstelle zurückzukehren...
	UserCanel                       = Der Benutzer hat die Anfrage abgebrochen.
	Uping                           = Erstellen
	Exclude_View                    = Ausschlussregeln anzeigen
	User_Interaction                = Benutzerinteraktion
	Ok_Go_To                        = Verfügbar für
	Ok_Go_To_No                     = Geht nicht

	Detailed                        = Detailliert
	Detailed_View                   = Anzeigen der Details der ausgewählten Regel

	AddEnv                          = Hinzufügen von Routingfunktionen zu Systemvariablen
	AddEnvTips                      = Geben Sie nach dem Hinzufügen Yi in einer beliebigen PowerShell Sitzung ein, um zu antworten, geben Sie beispielsweise "Yi -SIP" ein, um die Kapselung auszuführen.

	Unzip_ISO                       = Extrakt ISO
	Unzip_Search_Type               = Suchverzeichnis ( {0} )
	ISO_Other                       = Andere Dateien
	Unzip_Language                  = Sprachpaket
	Unzip_Fod                       = Funktionspaket
	FileName                        = Dateiname

	UserCancel                      = Der Benutzer hat den Vorgang abgebrochen.
	MatchMode                       = Passen
	Failed                          = Scheitern
	RandomSelect                    = Zufällige Auswahl
	RulePre                         = Voreingestellte Regeln
	RuleOther                       = Sonstige Regeln
	RuleCustomize                   = Benutzerdefinierte Regeln
	RuleCustomize_Dont              = Keine benutzerdefinierten Regeln für mehrstufige Kataloge verwenden
	RuleCustomize_Dont_Tips         = Nachdem Sie das alte Verzeichnis gelöscht haben, klicken Sie auf "Benennungsregeln validieren".
	RuleMultistage                  = Mehrstufige Verzeichnisregeln
	RuleMultistageFindFailed        = Es wurden keine mehrstufigen Verzeichnisregeln gefunden, klicken Sie auf Ich erstelle eine Vorlage.
	RuleMultistageFindCreateNew     = Erstellen Sie eine neue mehrstufige Verzeichnisregelvorlage
	RuleMultistageTips              = Automatische Anpassung von mehrstufigen Verzeichnisregeln, {0} Verzeichnisregeln sind deaktiviert.
	RuleCustomizeNot                = Kein Erweiterungsname gefunden (Solutions.Custom.Extension), siehe Hilfedokumentation.
	RuleCustomizeTips               = Es werden keine neuen benutzerdefinierten Regeln erstellt, siehe Hilfedokumentation.
	RuleMatchNoFindFolder           = Nachdem die Prioritätsübereinstimmung nicht gefunden wurde, klicken Sie auf Ich erstelle ein Verzeichnis.
	RuleNoFindFile                  = Es sind keine Dateien verfügbar, bitte nach dem Hinzufügen aktualisieren.
	RuleFindFolder                  = Wenn ein Katalog verfügbar ist, wird er automatisch ausgewählt
	RuleNameNewChange               = Nach Updates automatisch synchronisieren
	RuleNewTempate                  = Vorlage erstellen
	RuleSkipFolderCheck             = Keine Suche mehr nach Dateien im Verzeichnis, Dateityp
	RuleAuthon                      = Regelersteller
	RuleGUID                        = GUID Ein global eindeutiger Bezeichner
	RuleName                        = Regelname
	RuleDescription                 = Beschreibung
	RuleNameUse                     = Regelnamen synchronisieren mit: {0}
	RuleISO                         = Entspricht dem ursprünglichen Installationspaket für Posteingangs Apps
	RuleInBoxApps                   = Vollständige, bereitgestellte Anwendung
	RuleFileType                    = Name des Pakets
	RuleFileFind                    = Fuzzy Nachschlagename
	RuleFindError                   = Wenn Sie {0} ausstehenden Elemente gefunden haben, klicken Sie auf "Abhängigkeiten prüfen", um die Details anzuzeigen.
	RuleSelectApps                  = Der Benutzer hat die Anwendung ausgewählt
	DependencyPackage               = Abhängigkeitspaket
	RuleDependenciesRequired        = Erforderliche Abhängigkeiten
	RuleDependenciesUnselected      = Nicht ausgewählte Abhängigkeiten
	RuleDependenciesNoCheck         = Abhängigkeiten werden nicht mehr geprüft
	RuleDependenciesFix             = Beheben, dass Abhängigkeiten nicht ausgewählt sind
	Extract_Tips                    = Hinweis\n\n   1. Das Ergebnis nach dem Extrahieren des Sprachpakets kann nicht als Hauptreferenzobjekt verwendet werden;\n\n   2. Bitte verwenden Sie die Komponentenliste als Hauptbezugsobjekt, um zu generieren: \n\n       Wählen Sie Komponenten generieren in Funktionen aus (um die Pakete im installierten Image zu erhalten), wählen Sie Drucken oder Sofortansicht;\n\n   3. Generieren Sie nach der Installation des Sprachpakets bitte erneut einen Komponentenbericht, um zu sehen, ob er übereinstimmt;

	DescendingRuleLang              = Entfernen Sie Sprachpakete in umgekehrter Reihenfolge
	OrderRuleLang                   = Installieren Sie Sprachpakete in einer vorgegebenen Reihenfolge
	OrderRuleLangTips               = Der Reihe nach hinzugefügt: Basic, Fonts, Optical Character Recognition, Handwriting Recognition, Text to Speech, Speech Recognition, Retail Demo Experience, Other
	RuleLanguageTips                = Veranschaulichen:\n\n   Nach der Verwendung von "Install language packs in pre rule order" werden die Dateien automatisch mit mehrdeutigen Namen in der folgenden Reihenfolge abgeglichen:\n
	Match_installed_List            = Setzen Sie bei der Installation eines Sprachpakets einen Platzhalter aus der installierten Liste
	Match_installed_List_Tips       = Nur passend installiert: Basic, optische Zeichenerkennung, Handschrifterkennung, Text to Speech, Spracherkennung.
	RuleLanguageTipsExt             = \n   Wenn "Sprachpakete in der Reihenfolge der Vorregel installieren" nicht verwendet wird: \n   Alle Dateien im Verzeichnis automatisch nach Dateityp durchsuchen und installieren.\n\n   Sprache und regionale On Demand Funktionen (FOD)\n   https://learn.microsoft.com/de-de/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Bei der Klassifizierung
	Basic                           = Basic
	Fonts                           = Schriftart
	OCR                             = Optische Zeichenerkennung
	Handwriting                     = Handschrifterkennung
	TextToSpeech                    = Text zu Sprache
	Speech                          = Spracherkennung
	Retail                          = Demo Erfahrung für den Einzelhandel
	Features_On_Demand              = On Demand Funktionen
	RegionSpecific                  = Weitere regionalspezifische Anforderungen
	UnassignedLangFiles             = Nicht zugewiesene verschiedene Dateien

	ProcessingImage                 = Bearbeiten Sie das Bild: \
	NoInstallImage                  = Existiert nicht lokal
	ConvertChk                      = Überprüfen Sie die Datei
	WindowsFeature                  = Windows Funktion
	Enable                          = Ermöglichen
	Disable                         = Behinderte
	EnableFeatureTips               = Hinweis\n\n    1. Zeigen Sie, dass NetFx3 und TelnetClient voreingestellte aktivierte Funktionselemente sind;\n\n    2. Nach dem "Mounten" können weitere aktiviert werden.
	ViewLanguage                    = Anzeigen der Spracheinstellungen für Bilder
	ImageLanguage                   = Einstellung der Bildsprache
	OnlyLangCleanup                 = Bereinigungskomponenten: Tag nach Sprache
	Matched_Component_Names         = Übereinstimmende Komponentennamen: \
	BootProcess                     = Beim Verarbeiten von {0}.wim
	Sync_Language_To                = Synchronisieren mit
	BootSyncToISO                   = Synchronisieren Sie Sprachpakete mit dem Installationsprogramm
	BootSyncToISOTips               = Offline Image der installierten Sprachpakete, synchronisiert mit dem ISO Installationsprogramm.
	LangIni                         = Lang.ini neu generieren
	LangIniTips                     = Nachdem die Synchronisierung abgeschlossen ist, müssen Sie die Lang.ini in der ISO neu erstellen.
	LangNewAutoSelect               = Wählen Sie automatisch Vorschläge aus, wenn es ein Ereignis gibt
	LangNewAutoSelectTips           = Es gibt ein neues Ereignis, "Sync Language Packs to Installer", "Rebuild Lang.ini" ist ausgewählt.
	LangNewAutoNoSelect             = Es gibt ein neues Ereignis, es wird empfohlen, dass Sie "Sync Language Pack to Installer", "Rebuild Lang.ini" auswählen.
	LangNewAutoNoNewSelect          = Wenn es kein neues Ereignis gibt, wird empfohlen, dass Sie "Sprachpaket mit Installationsprogramm synchronisieren", "Lang.ini neu erstellen" nicht auswählen.
	Drive                           = Treiber
	ViewDrive                       = Installierte Treiber anzeigen
	EditionsProductKey              = Produktschlüssel
	Editions                        = Image Version
	Assign_Editions                 = Verteilen Sie Anwendungen automatisch basierend auf Image Versionen
	EditionsChangeTips              = Achtung, vor dem Wechseln der Image Versionen wissen: \n\nMicrosoft Dienstleistungsvertrag\nhttps://www.microsoft.com/de-de/servicesagreement/default.aspx\n\nSprachübersicht\nhttps://learn.microsoft.com/de-de/windows-hardware/manufacture/desktop/languages-overview\n\nFolgende Versionen dürfen nicht erstellt werden:\n   1. Länderspezifisch\n       ProfessionalCountrySpecific\n\n   2. Regionsspezifische Heimversion\n       ProfessionalSingleLanguage\n\nWenn Sie dagegen verstoßen, können Sie strafrechtlich verfolgt werden, bitte halten Sie sich strikt daran.\n\nWenn Sie auf der Konvertierung bestehen, klicken Sie, um die Warnung zu akzeptieren, und klicken Sie dann auf "Versteckte Bildversionen entsperren".
	EditionsChangeHide              = Entsperren Sie versteckte Bildversionen
	EditionsChangeAccect            = Ich habe die Warnung gelesen und bin allein verantwortlich für die relevanten Gesetze in der Warnung

	SelFile                         = Wählen Sie die Datei aus
	Rebuilding                      = im Umbau
	RebuildAll                      = Alles wieder aufbauen
	Export_Image                    = Exportieren
	SelectFromError                 = Fehler
	SelectFileFormatError           = Das Dateiformat ist falsch

	SearchDrive                     = Suche getrieben
	SearchUpdate                    = Suchaktualisierung, Typ ( {0} ), Quelle: \
	SelectFolder                    = Verzeichnis auswählen
	DropFolder                      = Sie können das Verzeichnis in das aktuelle Fenster ziehen
	DropFile                        = Dateien können in das aktuelle Fenster gezogen werden
	Sparse                          = Dünn
	CRCSHA                          = überprüfen
	Alternative                     = Alternativer Dateiname
	ChangeInstallDisk               = Ändern Sie die automatische Datenträgerauswahl
	Backup                          = Sicherung
	Restore                         = Wiederherstellung

	# View
	ExportToLogs                    = Drucken Sie den Bericht zum Protokoll
	ExportShow                      = Bericht zeigen
	MoreFeature                     = Mehr Funktionen
	OpenFolder                      = Verzeichnis öffnen
	OpenFile                        = Datei öffnen
	Running                         = Laufen
	Paste                           = Pfad kopieren
	Clipboard_Copy                  = In die Zwischenablage kopiert
	ViewWIMFileInfo                 = Bild ansehen
	GetInBoxApps                    = InBox Apps: Installierte Anwendungspakete
	GetImagePackage                 = Komponenten: Alle im Image installierten Pakete
	ViewMounted                     = Rufen Sie Informationen zu allen gemounteten Images ab
'@