ConvertFrom-StringData -StringData @'
	# lt-LT
	# Lithuanian (Lithuania)

	UnpackISO                       = Sukurti ISO
	ISOLabel                        = Tomo etiketė nustatyta:
	ISOCustomize                    = ISO tomo etiketės pavadinimas
	ISO9660                         = Patikrinkite pavadinimo taisykles
	ISO9660Tips                     = Unikalus pavadinimas negali būti ilgesnis nei 260 simbolių, ISO apimties pavadinimas negali viršyti 16 simbolių ir jame negali būti: tarpų priekyje ir gale, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Individualus unikalus pavadinimas
	ISOAddFlagsLang                 = Pridėti daugiakalbį žymėjimą
	ISOAddFlagsLangGet              = Gaukite žinomas diegimo kalbas
	ISOAddFlagsVer                  = Pridėti kelių versijų žymą
	ISOAddFlagsVerGet               = Gaukite žinomą vaizdo versiją
	ISOAddEICFG                     = Pridėti versijos tipą
	ISOAddEICFGTips                 = Kai remiamasi EI.cfg, tai yra komercinė versija.
	ISO9660TipsErrorSpace           = Negali būti tarpų priekyje ir gale
	ISO9660TipsErrorOther           = Negali būti: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Pasirinkite kalbos tipą
	SelLabel                        = Kodinis pavadinimas
	ISOVerLabel                     = Pasirinkite ISO garsumo pavadinimą
	NoSetLabel                      = Pasirinktinė ISO garsumo etiketė nenustatyta
	ISOLengthError                  = Tomo etiketė negali būti ilgesnė nei {0} simboliai
	RenameFailed                    = Tas pats, kas sename kataloge, pervardyti nepavyko
	ISOCreateAfter                  = Ką reikia padaryti prieš kuriant ISO
	ISOCreateRear                   = Ką reikia padaryti sukūrus ISO
	BypassTPM                       = Apeiti TPM diegimo patikrinimą
	Disable_BitLocker               = Diegimo metu išjunkite BitLocker įrenginio šifravimą
	PublicDate                      = Išleidimo data
	PublicDateGetCurrent            = Sinchronizuoti dabartinę datą
	PublicYear                      = Metai
	PublicMonth                     = Mėnulis
	PublicYMSorting                 = Rūšiuoti: Pakeiskite "month_year" į "year_month"
	PublicYMSortingTips             = AB: Nenaudokite pabraukimo _ naudodami skaičius.
	PublicYMUseShortNames           = Naudokite trumpus pavadinimus
	PublicYMUseNumbers              = Naudokite skaičius
	ISOCreateFailed                 = Sukurti nepavyko, katalogas neįskaitomas arba neįrašomas.
	ISORefreshAuto                  = Kiekvieną kartą atnaujinkite ISO žymas
	ISOSaveTo                       = ISO numatytoji išsaugojimo vieta
	ISOSaveSameGlobal               = Naudokite visuotinę ISO numatytąją išsaugojimo vietą
	ISOSaveSync                     = Pasirinkę vaizdo šaltinio paieškos diską, automatiškai sinchronizuokite naują vietą
	ISOSaveSame                     = Ieškokite disko kelio naudodami vaizdo šaltinį
	ISOFolderWrite                  = Patikrinkite, ar katalogas yra skaitomas ir įrašomas
	SelectAutoAvailable             = Kai automatiškai pasirenkamas turimas diskas
	SelectCheckAvailable            = Patikrinkite mažiausią laisvą vietą
	ISOStructure                    = Nauja katalogo struktūra
	ISOOSLevel                      = Pridėti diegimo tipą
	ISOUniqueNameDirectory          = Pridėkite unikalių pavadinimų katalogą
	NextDoOperate                   = Nekurkite ISO
	SelCreateISO                    = Sukurkite ISO, vykdykite pagal poreikį
	Reconstruction                  = Atkurkite {0}.wim su maksimaliu suspaudimu
	Reconstruction_Tips_Select      = Prieš atkuriant, jis bus vykdomas tik tada, kai jis nebus įkeltas. Tai privers įjungti išsaugojimą ir atjungti prijungtą failą.
	ReconstructionTips              = Daugiau nei 520 MB, rekomenduojama perdaryti
	CreateASC                       = Pridėkite PGP parašą prie ISO
	NoPGPKey                        = PGP nėra tinkamo naudoti privataus rakto.
	CreateASCPwd                    = Sertifikato slaptažodis
	PasswordRenter                  = Įveskite slaptažodį dar kartą
	ShowPassword                    = Rodyti slaptažodį
	NewPasswordSome                 = Slaptažodis nesutampa.
	PwdPermanent                    = Nuolatinė saugykla
	PwdDecfailed                    = Iššifravimas nepavyko
	CreateASCAuthor                 = Signataras
	CreateASCAuthorTips             = Nepasirinkta pasirašiusiųjų.
	ISO_Sparse_Rename               = Pridėti maišos kodą prie failo pavadinimo plėtinio
	GenerateRandom                  = Sukurkite atsitiktinius skaičius
	RandomNumberReset               = Regeneruoti
'@