ConvertFrom-StringData -StringData @'
	# he-IL
	# Hebrew (Israel)

	FontsUI                   = Segoe UI
	Mainname                  = מנוע פריסה: החבילה של Yi
	Learn                     = לִלמוֹד
	MainHisName               = פתרון בונוס
	Location                  = מיקום פתוח
	About                     = אוֹדוֹת
	Reset                     = אִתחוּל
	AddTo                     = הוסף ל
	Instl                     = לְהַתְקִין
	ItInstalled               = מוּתקָן
	Close                     = סֶגֶר
	Auto                      = אוֹטוֹמָטִי
	Disable                   = השבת
	Enable                    = לְאַפשֵׁר
	Setting                   = לְהַקִים
	Restore                   = לְהַחלִים
	Clean                     = לנקות
	Operable                  = נָתִיחַ
	Inoperable                = בלתי ניתן להפעלה
	Optimize                  = אופטימיזציה
	Hide                      = לְהַסתִיר
	Show                      = לְהַצִיג
	Del                       = לִמְחוֹק
	Done                      = סִיוּם
	OK                        = בַּטוּחַ
	Cancel                    = לְבַטֵל
	AllSel                    = בחר הכל
	AllClear                  = לנקות הכל
	Refresh                   = לְרַעֲנֵן
	RefreshModules            = רענון חם של כל המודולים
	Necessary                 = תוכנה חיונית
	MostUsedSoftware          = תוכנה נפוצה
	System                    = מַעֲרֶכֶת
	Service                   = לְשָׁרֵת
	TaskBar                   = כל הסמלים של שורת המשימות
	DeskIcon                  = סמלי שולחן העבודה
	InstallFonts              = התקן גופנים
	SettingTo                 = הגדר ל {0}
	Command                   = שורת הפקודה
	RuleName                  = שם כלל
	Language                  = שָׂפָה
	AvailableLanguages        = שפות זמינות
	SwitchLanguage            = להחליף שפה
	LanguageReset             = אפס את הגדרות השפה
	LanguageCode              = סימן אזור
	LanguageSelRegion         = בחר את המדינה או האזור שלך
	LanguageRemember          = זכור את השפה שנבחרה
	LanguageSearchNo          = לא נמצאו שפות זמינות
	LanguageNoSel             = אנא בחר אזור
	Search                    = לְחַפֵּשׂ
	PleaseChoose              = נא לבחור
	FailedCreateFolder        = יצירת הספרייה נכשלה
	Failed                    = לְהִכָּשֵׁל
	ToMsg                     = {0} חזור אוטומטית לתפריט הראשי לאחר שניות.
	Restart                   = הפעלה מחדש נכנסת לתוקף
	AdvOption                 = תכונות אופציונליות

	StartDown                 = התחל להוריד
	ConnectTo                 = התחבר ל
	FileName                  = שם הקובץ
	SaveTo                    = לשמור ל
	NotAvailable              = סטטוס: לא זמין
	ExistingPacker            = יש כבר חבילת התקנה
	ExistingInstlPacker       = יש כבר חבילה דחוסה
	Unpacking                 = פותח רוכסן
	QucikRun                  = ריצה מהירה:
	WaitDone                  = ממתין להשלמה:
	Parameter                 = פָּרָמֶטֶר:
	ErrorDown                 = אירעה שגיאה במהלך ההורדה
	UserCancel                = המשתמש ביטל את הפעולה.

	VerifyNameTips            = מותר רק שילוב של אותיות ומספרים באנגלית, ואסור להשתמש בתווים אחרים: רווחים, האורך לא יכול להיות גדול מ-16 תווים, \\ / : * ? & @ ! "" < > |
	FolderLabel               = קידומת ספרייה מותאמת אישית
	NoSetFolderLabel          = קידומת ספרייה מותאמת אישית לא הוגדרה
	ISO9660TipsErrorSpace     = לא יכול להכיל: חללים מובילים ונגררים
	ISO9660TipsErrorOther     = לא יכול להכיל: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = תווית נפח לא יכולה להיות ארוכה מ-{0} תווים
	Help                      = עֶזרָה
	WorkDone                  = הושלם, הקש על מקש כלשהו כדי לחזור לממשק הראשי...
	Short_Cmd                 = קיצורי דרך
	Options                   = אפשרויות
	LXPsWaitAssign            = יש להקצות
	Running                   = לָרוּץ
	SpecialFunction           = פונקציות PowerShell
'@