ConvertFrom-StringData -StringData @'
	# hr-HR
	# Croatian (Croatia)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Nadzorna ploča
	Learn                           = Studija
	Menu                            = Jelovnik
	Short_Cmd                       = Naredba prečaca
	Shortcut                        = Prečac
	Update                          = Obnoviti
	CUpdate                         = Kumulativna ažuriranja
	Rebuild                         = Rekonstrukcija
	AddTo                           = Dodaj u
	Del                             = Izbrisati
	Copy                            = Kopirati
	Rename                          = Preimenovati
	Refresh                         = Osvježiti
	RefreshModules                  = Vruće osvježite sve module
	Done                            = Završiti
	OK                              = Naravno
	Cancel                          = Otkazati
	AllSel                          = Odaberite sve
	AllClear                        = Jasno sve
	Setting                         = Postaviti
	Change                          = Promijeniti
	Help                            = Pomoć
	Logging                         = Spremi zapisnik u
	AvailableLanguages              = Dostupni jezici
	SwitchLanguage                  = Promijeniti jezik
	LanguageSelRegion               = Odaberite svoju zemlju ili regiju
	LanguageRemember                = Zapamti odabrani jezik
	LanguageSearchNo                = Nije pronađen nijedan dostupan jezik
	LanguageNoPack                  = Ako lokalno ne postoji jezični paket, automatski će se zatvoriti.
	LanguageNoSel                   = Odaberite regiju
	Search                          = Pretraživanje
	PleaseChoose                    = Odaberite
	Options                         = Mogućnosti
	Choose                          = Odabrano
	NoChoose                        = Nije odabrano
	AdvOption                       = Izborne značajke
	ExcludeItem                     = Isključi pravilom
	DeDuplication                   = Isključi duplikate
	DeDuplication_Unlock            = Otključaj onemogućene duplikate
	Existed                         = Već postoji
	FailedCreateFolder              = Stvaranje imenika nije uspjelo
	FailedCreateFile                = Izrada datoteke nije uspjela
	ToMsg                           = {0} Automatski povratak na glavni izbornik nakon nekoliko sekundi.
	OnDemandPlanTask                = Prilagođeno dodjeljivanje poznatih događaja
	Operable                        = Operabilan
	Inoperable                      = Neoperabilan
	Hide                            = Sakriti
	CuringUpdate                    = Solidno ažuriranje
	CuringUpdateTips                = Nakon što se ažuriranje učvrsti, ne može se deinstalirati.
	Healthy                         = Zdrav
	HealthyTips                     = Posebno je važno provjeriti stanje ispravnosti. Kada se pojavi "popravljivo" ili "nepopravljivo": tijekom procesa konverzije ESD-a prikazuje se pogreška 13 i podaci su nevažeći; prilikom instaliranja sustava javlja se pogreška.
	Healthy_Save                    = Kad se pojavi popravljivo ili nepopravljivo, nemojte štedjeti.
	Repair                          = Popravak
	IsAuto_Repair                   = Omogući automatski popravak kada je u stanju mirovanja
	IsAuto_Repair_Tips              = Automatski provjeri ima li zadataka montiranja nakon svakog pokretanja skripte za pakiranje. Ako je montiran, popravak se neće izvršiti; ako nije montiran, pokrenut će se automatski popravak.
	Repairable                      = Opravljiv
	NonRepairable                   = Ne može se popraviti
	HealthyForceStop                = Tijekom obrade događaja došlo je do nepopravljive pogreške i događaj je prisilno prekinut.\n\n   Uzrokuje glavne probleme: \n\n      1. Fizički hardver je oštećen, tvrdi disk;\n\n      2. Ako koristite RAMDISK memorijski virtualni disk (uključujući hibridni), provjerite fizičku memoriju;\n\n      3. Provjerite izvorni SHA256 MVS-a (MSDN), promijenite direktorij i pokušajte ponovno.\n\n      4. Ostali nisu navedeni u ovom primjeru.
	Superseded                      = Očistite zamijenjeno
	SupersededTips                  = Uključuje zastarjela ažuriranja, komponente itd.
	UnmountFailed                   = Probao sam nekoliko metoda, ali ništa se ne može učiniti. Volio bih te vidjeti sljedeći put.
	SaveTo                          = Spremiti u
	WorkDone                        = Završeno, pritisnite bilo koju tipku za povratak na glavno sučelje...
	UserCanel                       = Korisnik je poništio zahtjev.
	Uping                           = Generiranje
	Exclude_View                    = Pogledajte pravila izuzimanja
	User_Interaction                = Interakcija s korisnikom
	Ok_Go_To                        = Na raspolaganju
	Ok_Go_To_No                     = Ne ide

	Detailed                        = Detaljan
	Detailed_View                   = Pogledajte pojedinosti o odabranom pravilu

	AddEnv                          = Dodajte funkciju usmjeravanja sistemskim varijablama
	AddEnvTips                      = Nakon dodavanja, unesite Yi u bilo koju PowerShell sesiju da biste odgovorili. Na primjer, unesite "Yi -SIP" za pokretanje enkapsulacije.

	Unzip_ISO                       = Ekstrakt ISO
	Unzip_Search_Type               = Pretraži imenik ( {0} )
	ISO_Other                       = Ostali dokumenti
	Unzip_Language                  = Jezični paket
	Unzip_Fod                       = Paket značajki
	FileName                        = Naziv datoteke

	UserCancel                      = Korisnik je otkazao operaciju.
	MatchMode                       = Odgovarati
	Failed                          = Uspjeti
	RandomSelect                    = Slučajno odabrani
	RulePre                         = Unaprijed postavljena pravila
	RuleOther                       = Ostala pravila
	RuleCustomize                   = Prilagođena pravila
	RuleCustomize_Dont              = Nemojte koristiti višerazinska prilagođena pravila imenika
	RuleCustomize_Dont_Tips         = Nakon brisanja starog imenika, kliknite "Provjeri pravila imenovanja."
	RuleMultistage                  = Pravila imenika na više razina
	RuleMultistageFindFailed        = Nisu pronađena pravila direktorija s više razina, kliknite me za izradu predloška.
	RuleMultistageFindCreateNew     = Stvorite novi predložak pravila imenika na više razina
	RuleMultistageTips              = Automatski prilagodi višerazinska pravila imenika, {0} pravilo imenika je onemogućeno.
	RuleCustomizeNot                = Naziv proširenja (Solutions.Custom.Extension) nije pronađen, pogledajte dokumentaciju pomoći.
	RuleCustomizeTips               = Nije stvoreno prilagođeno pravilo, pogledajte dokumentaciju pomoći.
	RuleMatchNoFindFolder           = Neuspješno uparivanje imenika, kliknite me za stvaranje imenika.
	RuleNoFindFile                  = Nisu pronađene dostupne datoteke, dodajte i osvježite.
	RuleFindFolder                  = Imenik je automatski odabran kada je dostupan
	RuleNameNewChange               = Automatski sinkroniziraj nakon ažuriranja
	RuleNewTempate                  = Izradi predložak
	RuleSkipFolderCheck             = Više ne provjerava postoji li datoteka u direktoriju i vrsti datoteke
	RuleAuthon                      = Kreator pravila
	RuleGUID                        = GUID globalni jedinstveni identifikator
	RuleName                        = Naziv pravila
	RuleDescription                 = Opisati
	RuleNameUse                     = Sinkroniziraj naziv pravila s: {0}
	RuleISO                         = Odgovara originalnom ISO instalacijskom paketu
	RuleInBoxApps                   = Potpuna, unaprijed konfigurirana aplikacija
	RuleFileType                    = Naziv paketa
	RuleFileFind                    = Naziv nejasnog pretraživanja
	RuleFindError                   = Pronađeno je {0} stavki za obradu, kliknite "Provjeri ovisnosti" za pregled pojedinosti.
	RuleSelectApps                  = Aplikacije po izboru korisnika
	DependencyPackage               = Paket ovisnosti
	RuleDependenciesRequired        = Potrebne ovisnosti
	RuleDependenciesUnselected      = Neodabrane ovisnosti
	RuleDependenciesNoCheck         = Ovisnosti se više ne provjeravaju
	RuleDependenciesFix             = Popravi ovisnosti koje nisu odabrane
	Extract_Tips                    = Savjet\n\n   1. Rezultat nakon izdvajanja jezičnog paketa ne može se koristiti kao glavni referentni objekt;\n\n   2. Koristite popis komponenti kao glavni referentni objekt. Kako generirati:\n\n       U Funkcijama odaberite Generiraj komponentu (dobijte paket u instaliranoj slici), odaberite Ispis ili Pregled odmah;\n\n   3. Nakon instaliranja jezičnog paketa, ponovno generirajte izvješće o komponenti kako biste provjerili odgovara li;

	DescendingRuleLang              = Uklonite jezične pakete obrnutim redoslijedom
	OrderRuleLang                   = Instalirajte jezične pakete prema unaprijed utvrđenom redoslijedu
	OrderRuleLangTips               = Dodajte redom: Osnovno, Fontovi, Optičko prepoznavanje znakova, Prepoznavanje rukopisa, Pretvaranje teksta u govor, Prepoznavanje govora, Retail Demo Experience, Ostalo
	RuleLanguageTips                = Ilustrirati:\n\n   Nakon korištenja opcije "Instaliraj jezične pakete u unaprijed utvrđenom redoslijedu", datoteke se automatski povezuju nejasnim nazivima sljedećim redoslijedom:\n
	Match_installed_List            = Kada instalirate jezični paket, označite ga zamjenskim znakom s instaliranog popisa
	Match_installed_List_Tips       = Odgovara samo kada je instalirano: Osnovno, optičko prepoznavanje znakova, prepoznavanje rukopisa, pretvaranje teksta u govor, prepoznavanje govora.
	RuleLanguageTipsExt             = \n   Kada ne koristite "Instalirajte jezične pakete prema unaprijed utvrđenom redoslijedu": \n   Automatski pretražite sve datoteke u direktoriju prema vrsti datoteke i instalirajte ih.\n\n   Značajke jezika i regije na zahtjev (FOD)\n   https://learn.microsoft.com/hr-hr/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategorija
	Basic                           = Osnovni
	Fonts                           = Font
	OCR                             = Optičko prepoznavanje znakova
	Handwriting                     = Prepoznavanje rukopisa
	TextToSpeech                    = Teksta u govor
	Speech                          = Prepoznavanje govora
	Retail                          = Maloprodajno demo iskustvo
	Features_On_Demand              = Značajke na zahtjev
	RegionSpecific                  = Ostali zahtjevi specifični za regiju
	UnassignedLangFiles             = Nedodijeljene razne datoteke

	ProcessingImage                 = Obradite sliku:
	NoInstallImage                  = Ne postoji lokalno
	ConvertChk                      = Provjerite datoteku
	WindowsFeature                  = Značajke sustava Windows
	Enable                          = Omogućiti
	Disable                         = Onemogući
	EnableFeatureTips               = Savjet\n\n    1. Prikažite NetFx3 i TelnetClient kao unaprijed omogućene funkcijske stavke;\n\n    2. Nakon "montaže", više se može omogućiti.
	ViewLanguage                    = Pogledajte postavke jezika slike
	ImageLanguage                   = Postavke jezika slike
	OnlyLangCleanup                 = Čiste komponente: oznaka prema jeziku
	Matched_Component_Names         = Podudarni naziv komponente:
	BootProcess                     = Prilikom obrade {0}.wim
	Extract_Rule_Only_And_Full      = Ekstrahirajte samo odabrane jezike
	Sync_Language_To                = Sinkronizacija s
	BootSyncToISO                   = Sinkronizirajte jezične pakete s programom za instalaciju
	BootSyncToISOTips               = Instalirani jezični paket izvanmrežne slike sinkroniziran je s ISO instalacijskim programom.
	Setup_Fix_Missing               = Automatski popravi stavke programa za instalaciju koje nedostaju
	Setup_Fix_Missing_Tips          = Ako instalacijskom programu nedostaje arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui, otvorite "Extract", odaberite "Rules" i kliknite "Extract Installer Missing Items".
	Setup_Fix_Missing_Extract       = Izdvojite stavke programa za instalaciju koje nedostaju
	Setup_Fix_Missing_Extract_Tips  = Izdvojite stavke koje nedostaju u instalacijskom programu iz svih lokalnih jezičnih paketa: arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui.
	LangIni                         = Regeneriraj Lang.ini
	LangIniTips                     = Nakon dovršetka sinkronizacije potrebno je ponovno izgraditi Lang.ini u ISO.
	LangNewAutoSelect               = Automatski odaberite predložene stavke kada se dogodi događaj
	LangNewAutoSelectTips           = Postoje novi događaji, odabrano je "Sinkroniziraj jezični paket s programom za instalaciju", "Ponovo izgradi Lang.ini".
	LangNewAutoNoSelect             = Postoje novi događaji, preporučuje se da odaberete "Sinkroniziraj jezični paket s instalacijskim programom" i "Ponovo izgradi Lang.ini".
	LangNewAutoNoNewSelect          = Nema novih događaja. Preporučuje se da ne odaberete "Sinkroniziraj jezični paket s instalacijskim programom" ili "Ponovo izgradi Lang.ini".
	Drive                           = Pogon
	ViewDrive                       = Pogledajte instalirane upravljačke programe
	EditionsProductKey              = Ključ proizvoda
	Editions                        = Slikovna verzija
	Assign_Editions                 = Automatski distribuirati aplikacije na temelju verzija slika
	EditionsChangeTips              = Upozorenje, razumite prije promjene verzije slike: \n\nMicrosoft Ugovor o pružanju usluga\nhttps://www.microsoft.com/hr-hr/servicesagreement/default.aspx\n\nJezični pregled\nhttps://learn.microsoft.com/hr-hr/windows-hardware/manufacture/desktop/languages-overview\n\nNije vam dopušteno izrađivati verzije:\n   1. Specifično za zemlju\n       ProfessionalCountrySpecific\n\n   2. Kućna verzija specifična za regiju\n       ProfessionalSingleLanguage\n\nMolimo vas da se striktno pridržavate jer biste mogli biti podvrgnuti kaznenom progonu ako ih prekršite.\n\nAko inzistirate na pretvorbi, kliknite kako biste prihvatili upozorenje i kliknite "Otključaj verziju skrivene slike".
	EditionsChangeHide              = Otključajte verzije skrivenih slika
	EditionsChangeAccect            = Pročitao sam upozorenje i odgovoran sam za relevantne zakone sadržane u upozorenju

	SelFile                         = Odaberite datoteku
	Rebuilding                      = U rekonstrukciji
	RebuildAll                      = Ponovo izgraditi sve
	Export_Image                    = Izvoz
	SelectFromError                 = Pogreška
	SelectFileFormatError           = Format datoteke nije ispravan

	SearchDrive                     = Potaknut pretraživanjem
	SearchUpdate                    = Traži ažuriranja, vrsta ( {0} ), izvor:
	SelectFolder                    = Odaberite imenik
	DropFolder                      = Može povući direktorije u trenutni prozor
	DropFile                        = Datoteke se mogu povući u trenutni prozor
	Sparse                          = Rijetko
	CRCSHA                          = Provjeriti
	Alternative                     = Alternativni naziv datoteke
	ChangeInstallDisk               = Promjena automatskog odabira diska

	# View
	ExportToLogs                    = Ispis izvješća u zapisnik
	ExportShow                      = Prikaz izvješća odmah
	MoreFeature                     = Više značajki
	OpenFolder                      = Otvori imenik
	OpenFile                        = Otvorena datoteka
	Running                         = Trčanje
	Paste                           = Put kopiranja
	Clipboard_Copy                  = Kopirano u međuspremnik
	ViewWIMFileInfo                 = Pogledaj sliku
	GetInBoxApps                    = InBox Apps: instalirani paketi aplikacija
	GetImagePackage                 = Komponente: Svi paketi instalirani na slici
	ViewMounted                     = Dobijte informacije o svim montiranim slikama
'@