ConvertFrom-StringData -StringData @'
	# ro-RO
	# Romanian (Romania)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Bord
	Learn                           = Studiu
	Menu                            = Meniu
	Short_Cmd                       = Comandă de comandă rapidă
	Shortcut                        = Scurtătură
	Update                          = Reînnoi
	CUpdate                         = Actualizări cumulate
	Rebuild                         = Reconstrucţie
	AddTo                           = Adaugă la
	Del                             = Şterge
	Copy                            = Copie
	Rename                          = Redenumiți
	Refresh                         = Reîmprospăta
	RefreshModules                  = Actualizează la cald toate modulele
	Done                            = Termina
	OK                              = Sigur
	Cancel                          = Anula
	AllSel                          = Selectați toate
	AllClear                        = Șterge totul
	Setting                         = Înființat
	Change                          = Schimba
	Help                            = Ajutor
	Logging                         = Jurnal
	AvailableLanguages              = Limbi disponibile
	SwitchLanguage                  = Schimba limba
	LanguageSelRegion               = Selectați țara sau regiunea dvs
	LanguageRemember                = Amintiți-vă limba selectată
	LanguageSearchNo                = Nu s-au găsit limbi disponibile
	LanguageNoPack                  = Dacă nu există un pachet de limbă local, acesta va ieși automat.
	LanguageNoSel                   = Vă rugăm să selectați o regiune
	Search                          = Căutare
	PleaseChoose                    = Vă rugăm să selectați
	Options                         = Opțiuni
	Choose                          = Selectat
	NoChoose                        = Neselectat
	AdvOption                       = Caracteristici opționale
	ExcludeItem                     = Excludeți prin regulă
	DeDuplication                   = Excludeți duplicatele
	DeDuplication_Unlock            = Deblocați duplicatele dezactivate
	Existed                         = Există deja
	FailedCreateFolder              = Nu s-a putut crea directorul
	FailedCreateFile                = Nu s-a putut crea fișierul
	ToMsg                           = {0} Reveniți automat la meniul principal după câteva secunde.
	OnDemandPlanTask                = Atribuire personalizată a evenimentelor cunoscute
	Operable                        = Operabil
	Inoperable                      = Inoperabil
	Hide                            = Ascunde
	CuringUpdate                    = Actualizare solidă
	CuringUpdateTips                = Odată ce actualizarea a fost solidificată, nu poate fi dezinstalată.
	Healthy                         = Sănătos
	HealthyTips                     = Este deosebit de important să verificați starea de sănătate Când apare "reparabil" sau "nereparabil": în timpul procesului de conversie ESD, este semnalată eroarea 13, iar datele sunt raportate la instalarea sistemului.
	Healthy_Save                    = Când apare reparabil sau ireparabil, nu salvați.
	Repair                          = Repara
	IsAuto_Repair                   = Permite repararea automată când este inactiv
	IsAuto_Repair_Tips              = Verificați automat dacă există sarcini de montare după fiecare rulare a scriptului de ambalare. Dacă este montat, nu se va efectua nicio reparație dacă nu este montat, se va executa reparația automată.
	Repairable                      = Reparabil
	NonRepairable                   = Nu se poate repara
	HealthyForceStop                = În timpul procesării evenimentului, a fost întâlnită o eroare ireversibilă și evenimentul a fost încheiat forțat.\n\n   Cauza probleme principale:\n\n      1. Hard diskul fizic este deteriorat;\n\n      2. Dacă utilizați un disc virtual cu memorie RAMDISK (inclusiv hibrid), vă rugăm să verificați memoria fizică;\n\n      3. Verificați SHA256 original al MVS (MSDN), vă rugăm să schimbați directorul și să încercați din nou. Dacă SHA256 este inconsecvent, vă rugăm să îl descărcați din nou.\n\n      4. Altele nu sunt enumerate în acest exemplu.
	Superseded                      = Curățați cel înlocuit
	SupersededTips                  = Include actualizări învechite, componente etc.
	UnmountFailed                   = Am încercat mai multe metode, dar nu se poate face nimic.
	SaveTo                          = Salva la
	WorkDone                        = Finalizat, apăsați orice tastă pentru a reveni la interfața principală...
	UserCanel                       = Utilizatorul a anulat cererea.
	Uping                           = Generarea
	Exclude_View                    = Vedeți regulile de excludere
	User_Interaction                = Interacțiunea utilizatorului
	Ok_Go_To                        = Disponibil pentru
	Ok_Go_To_No                     = Nu merg

	Detailed                        = Detaliat
	Detailed_View                   = Vedeți detaliile regulii selectate

	AddEnv                          = Adăugați funcționalitate de rutare la variabilele de sistem
	AddEnvTips                      = După adăugare, introduceți Yi în orice sesiune PowerShell pentru a răspunde De exemplu, introduceți "Yi -SIP" pentru a rula încapsularea.

	Unzip_ISO                       = Extrage ISO
	Unzip_Search_Type               = Căutare în director ( {0} )
	ISO_Other                       = Alte documente
	Unzip_Language                  = Pachetul lingvistic
	Unzip_Fod                       = Pachet de caracteristici
	FileName                        = Nume de fișier

	UserCancel                      = Utilizatorul a anulat operația.
	MatchMode                       = Meci
	Failed                          = Eșuează
	RandomSelect                    = Selectate aleatoriu
	RulePre                         = Reguli prestabilite
	RuleOther                       = Alte reguli
	RuleCustomize                   = Reguli personalizate
	RuleCustomize_Dont              = Nu utilizați reguli personalizate de directoare pe mai multe niveluri
	RuleCustomize_Dont_Tips         = După ștergerea vechiului director, faceți clic pe "Verificați regulile de denumire".
	RuleMultistage                  = Reguli de directoare pe mai multe niveluri
	RuleMultistageFindFailed        = Nu s-au găsit reguli de directoare pe mai multe niveluri, dați clic pe mine pentru a crea un șablon.
	RuleMultistageFindCreateNew     = Creați un nou șablon de regulă de director pe mai multe niveluri
	RuleMultistageTips              = Adaptați automat regulile de director pe mai multe niveluri, regula de director {0} a fost dezactivată.
	RuleCustomizeNot                = Numele extensiei (Solutions.Custom.Extension) nu a fost găsit, consultați documentația de ajutor.
	RuleCustomizeTips               = Nu a fost creată nicio regulă personalizată, consultați documentația de ajutor.
	RuleMatchNoFindFolder           = Nu s-a putut potrivi directorul, dați clic pe mine pentru a crea directorul.
	RuleNoFindFile                  = Nu s-au găsit fișiere disponibile, vă rugăm să adăugați și să reîmprospătați.
	RuleFindFolder                  = Director selectat automat când este disponibil
	RuleNameNewChange               = Sincronizare automată după actualizări
	RuleNewTempate                  = Creați șablon
	RuleSkipFolderCheck             = Nu mai verifică dacă fișierul există în director și tipul fișierului
	RuleAuthon                      = Creator de reguli
	RuleGUID                        = GUID identificator unic la nivel global
	RuleName                        = Numele regulii
	RuleDescription                 = Descrie
	RuleNameUse                     = Sincronizați numele regulii cu: {0}
	RuleISO                         = Se potrivește cu pachetul de instalare ISO original
	RuleInBoxApps                   = Aplicație completă, preconfigurată
	RuleFileType                    = Numele pachetului
	RuleFileFind                    = Nume de căutare neclară
	RuleFindError                   = S-au găsit {0} articole de procesat, faceți clic pe "Verificați dependențele" pentru a vedea detalii.
	RuleSelectApps                  = Aplicații selectate de utilizator
	DependencyPackage               = Pachet de dependență
	RuleDependenciesRequired        = Dependențe necesare
	RuleDependenciesUnselected      = Dependențe neselectate
	RuleDependenciesNoCheck         = Dependențele nu mai sunt verificate
	RuleDependenciesFix             = Remediați dependențele neselectate
	Extract_Tips                    = Aluzie\n\n   1. Rezultatul după extragerea pachetului de limbă nu poate fi folosit ca obiect de referință principal;\n\n   2. Vă rugăm să utilizați lista de componente ca obiect de referință principal Cum se generează:\n\n       În Funcții, selectați Generare componentă (obțineți pachetul în imaginea instalată), selectați Imprimare sau Vizualizare instantanee;\n\n   3. După instalarea pachetului de limbă, vă rugăm să regenerați un raport de componentă pentru a verifica dacă este corespunzător;

	DescendingRuleLang              = Eliminați pachetele de limbi în ordine inversă
	OrderRuleLang                   = Instalați pachetele lingvistice în ordine prealabilă
	OrderRuleLangTips               = Adăugați în ordine: De bază, Fonturi, Recunoaștere optică a caracterelor, Recunoaștere a scrisului de mână, Text-to-Speech, Recunoaștere vorbire, Experiență demonstrativă de vânzare cu amănuntul, Altele
	RuleLanguageTips                = Notă:\n\n    După ce ați folosit "Instalați pachetele de limbi în ordine prealabilă", fișierele vor fi asociate automat cu nume neclare, în următoarea ordine:\n
	Match_installed_List            = Când instalați un pachet de limbă, introduceți-l cu wildcard din lista instalată
	Match_installed_List_Tips       = Se potrivește numai când este instalat: de bază, recunoaștere optică a caracterelor, recunoaștere a scrisului de mână, text în vorbire, recunoaștere a vorbirii.
	RuleLanguageTipsExt             = \n   Când nu utilizați "Instalați pachetele lingvistice în ordinea prealabilă": \n   Căutați automat toate fișierele din director după tipul de fișier și instalați-le.\n\n   Funcții la cerere pentru limbă și regiune (FOD)\n   https://learn.microsoft.com/ro-ro/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Categorie
	Basic                           = De bază
	Fonts                           = Font
	OCR                             = Recunoașterea optică a caracterelor
	Handwriting                     = Recunoașterea scrisului de mână
	TextToSpeech                    = Text în vorbire
	Speech                          = Recunoașterea vorbirii
	Retail                          = Experiență demonstrativă în retail
	Features_On_Demand              = Caracteristici la cerere
	RegionSpecific                  = Alte cerințe specifice regiunii
	UnassignedLangFiles             = Fișiere diverse nealocate

	ProcessingImage                 = Procesați imaginea:
	NoInstallImage                  = Nu există la nivel local
	ConvertChk                      = Verificați fișierul
	WindowsFeature                  = Caracteristicile Windows
	Enable                          = Permite
	Disable                         = Dezactivați
	EnableFeatureTips               = Aluzie\n\n    1. Display NetFx3 și TelnetClient sunt elemente de funcții prestabilite;\n\n    2. După "montare", mai multe pot fi activate.
	ViewLanguage                    = Vizualizați setările pentru limba imaginii
	ImageLanguage                   = Setări pentru limba imaginii
	OnlyLangCleanup                 = Componente curate: etichetați după limbă
	Matched_Component_Names         = Numele componentei potrivite:
	BootProcess                     = La procesarea {0}.wim
	Sync_Language_To                = Sincronizare cu
	BootSyncToISO                   = Sincronizați pachetele de limbi cu programul de instalare
	BootSyncToISOTips               = Pachetul de limbă instalat al imaginii offline este sincronizat cu programul de instalare ISO.
	LangIni                         = Regenerați Lang.ini
	LangIniTips                     = După finalizarea sincronizării, Lang.ini în ISO trebuie reconstruit.
	LangNewAutoSelect               = Selectați automat elementele sugerate atunci când are loc un eveniment
	LangNewAutoSelectTips           = Există evenimente noi, "Sincronizați pachetul de limbă cu programul de instalare", "Rebuild Lang.ini" selectat.
	LangNewAutoNoSelect             = Sunt evenimente noi, este recomandat să selectați "Sincronizare pachet lingvistic cu programul de instalare" și "Reconstruiți Lang.ini".
	LangNewAutoNoNewSelect          = Nu există evenimente noi. Este recomandat să nu selectați "Synchronize language pack to installer" sau "Rebuild Lang.ini".
	Drive                           = Conduce
	ViewDrive                       = Vizualizați driverele instalate
	EditionsProductKey              = Cheia produsului
	Editions                        = Versiune imagine
	Assign_Editions                 = Distribuiți automat aplicații pe baza versiunilor de imagini
	EditionsChangeTips              = Atenție, vă rugăm să înțelegeți înainte de a schimba versiunile imaginii: \n\nMicrosoft Acord de servicii\nhttps://www.microsoft.com/ro-ro/servicesagreement/default.aspx\n\nPrezentare generală a limbii\nhttps://learn.microsoft.com/ro-ro/windows-hardware/manufacture/desktop/languages-overview\n\nNu aveți voie să faceți versiuni ale:\n   1. Specific țării\n       ProfessionalCountrySpecific\n\n   2. Versiunea de acasă specifică regiunii\n       ProfessionalSingleLanguage\n\nVă rugăm să respectați cu strictețe, deoarece puteți fi supus urmăririi penale dacă ați încălcat.\n\nDacă insistați să faceți conversie, faceți clic pentru a accepta avertismentul și faceți clic pe "Deblocați versiunea imaginii ascunse".
	EditionsChangeHide              = Deblocați versiunile de imagini ascunse
	EditionsChangeAccect            = Am citit avertismentul și sunt responsabil pentru legile relevante conținute în avertisment

	SelFile                         = Selectați fișierul
	Rebuilding                      = În reconstrucție
	RebuildAll                      = Reconstruiește totul
	Export_Image                    = Export
	SelectFromError                 = Greşeală
	SelectFileFormatError           = Formatul fișierului este incorect

	SearchDrive                     = Condus de căutare
	SearchUpdate                    = Căutați actualizări, tip ( {0} ), sursă:
	SelectFolder                    = Selectați directorul
	DropFolder                      = Poate trage directoare în fereastra curentă
	DropFile                        = Fișierele pot fi trase în fereastra curentă
	Sparse                          = Rar
	CRCSHA                          = Verifica
	Alternative                     = Nume alternativ de fișier
	ChangeInstallDisk               = Schimbați selecția automată a discului
	Backup                          = Copiere de rezervă
	Restore                         = Restaurare

	# View
	ExportToLogs                    = Imprimați raportul pentru a înregistra
	ExportShow                      = Afișează rapoarte instantaneu
	MoreFeature                     = Mai multe caracteristici
	OpenFolder                      = Deschide directorul
	OpenFile                        = Deschide fișierul
	Running                         = Alerga
	Paste                           = Copiați calea
	Clipboard_Copy                  = Copiat în clipboard
	ViewWIMFileInfo                 = Vizualizați imaginea
	GetInBoxApps                    = InBox Apps: pachete de aplicații instalate
	GetImagePackage                 = Componente: Toate pachetele instalate în imagine
	ViewMounted                     = Obțineți informații despre toate imaginile montate
'@