ConvertFrom-StringData -StringData @'
	# sl-SI
	# Slovenian (Slovenia)

	IsCreate                        = Ustvariti
	Solution                        = Rešitev
	EnabledSoftwarePacker           = Zbirka
	EnabledUnattend                 = Odgovoriti je treba vnaprej
	EnabledEnglish                  = Motor za uvajanje
	UnattendSelectVer               = Izberite jezik rešitve 'Odgovori na'
	UnattendLangPack                = Izberite jezikovni paket 'Rešitev'
	UnattendSelectSingleInstl       = Več jezikov, neobvezno med namestitvijo
	UnattendSelectMulti             = Večjezični
	UnattendSelectDisk              = Izberite rešitev Autounattend.xml
	UnattendSelectSemi              = Polavtomatsko velja za vse načine namestitve
	UnattendSelectUefi              = UEFI se samodejno namesti in ga je treba določiti
	UnattendSelectLegacy            = Legacy je samodejno nameščen in ga je treba določiti
	NeedSpecified                   = Prosimo izberite, kaj je treba navesti:
	OOBESetupOS                     = Namestitveni vmesnik
	OOBEProductKey                  = Ključ izdelka
	OOBEOSImage                     = Izberite operacijski sistem za namestitev
	OOBEEula                        = Sprejmite licenčne pogoje
	OOBEDoNotServerManager          = Server Manager se ne zažene samodejno ob prijavi
	OOBEIE                          = Konfiguracija izboljšane varnosti Internet Explorerja
	OOBEIEAdmin                     = Zapri "Administrator"
	OObeIEUser                      = Zapri "Uporabniki"

	OOBE_Init_User                  = Začetni uporabnik med izkušnjo razpakiranja
	OOBE_init_Create                = Ustvarite uporabnike po meri
	OOBE_init_Specified             = Določite uporabnika
	OOBE_Init_Autologin             = Samodejna prijava

	InstlMode                       = Način namestitve
	Business                        = Poslovna različica
	BusinessTips                    = Za samodejno namestitev je odvisno od EI.cfg treba določiti številko indeksa.
	Consumer                        = Potrošniška različica
	ConsumerTips                    = Za samodejno namestitev je treba navesti serijsko številko EI.cfg.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [pritrditi na]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Dodaj v ime domačega imenika sistemskega diska
	VerifyNameUse                   = Preverite, ali ime imenika ne sme vsebovati
	VerifyNameTips                  = Dovoljena je samo kombinacija angleških črk in številk in ne sme vsebovati: presledkov, dolžina ne sme biti večja od 260 znakov, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Preverjanje ni uspelo, vnesite pravilno številko.
	VerifyNameSync                  = Nastavite ime imenika kot primarno uporabniško ime
	VerifyNameSyncTips              = Administrator se ne uporablja več.
	ManualKey                       = Ročno izberite ali vnesite ključ izdelka
	ManualKeyTips                   = Vnesite veljaven ključ izdelka. Če izbrana regija ni na voljo, obiščite Microsoftovo uradno spletno mesto in preverite.
	ManualKeyError                  = Ključ izdelka, ki ste ga vnesli, ni veljaven.
	KMSLink1                        = Ključ za nastavitve odjemalca KMS
	KMSUnlock                       = Pokaži vse znane serijske številke KMS
	KMSSelect                       = Izberite serijsko številko VOL
	KMSKey                          = Serijsko številko
	KMSKeySelect                    = Spremenite serijsko številko izdelka
	ClearOld                        = Očistite stare datoteke
	SolutionsSkip                   = Preskoči ustvarjanje rešitve
	SolutionsTo                     = Dodaj 'rešitev' v:
	SolutionsToMount                = Vpet ali dodan v čakalno vrsto
	SolutionsToError                = Nekatere funkcije so bile onemogočene. Če jih morate vsiliti, kliknite gumb "Odkleni".\n\n
	UnlockBoot                      = Odkleni
	SolutionsToSources              = Domači imenik, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Izberite različico "Deployment Engine".
	SolutionsEngineRegionaUTF8      = Beta: Globalna jezikovna podpora z uporabo Unicode UTF-8
	SolutionsEngineRegionaUTF8Tips  = Zdi se, da lahko po odprtju povzroči nove težave. Ni priporočljivo.
	SolutionsEngineRegionaling      = Spremeni na novo področno nastavitev:
	SolutionsEngineRegionalingTips  = Spremenite jezik sistema, kar vpliva na vse uporabniške račune v računalniku.
	SolutionsEngineRegional         = Spremenite jezik sistema
	SolutionsEngineRegionalTips     = Globalna privzeta vrednost: {0}, spremenjena v: {1}
	SolutionsEngineCopyPublic       = Kopiraj javni {0} v razmestitev
	SolutionsEngineCopyOpen         = Prebrskaj javno skladišče {0} na lokaciji
	EnglineDoneReboot               = Znova zaženite računalnik
	SolutionsTipsArm64              = Prednosten je paket arm64, vi pa izberete po vrstnem redu: x64, x86.
	SolutionsTipsAMD64              = Prednost imajo paketi x64, po vrstnem redu: x86.
	SolutionsTipsX86                = Dodani so samo paketi x86.
	SolutionsReport                 = Ustvarite poročilo pred uvedbo
	SolutionsDeployOfficeInstall    = Razmestite namestitveni paket Microsoft Office
	SolutionsDeployOfficeChange     = Spremenite konfiguracijo uvajanja
	SolutionsDeployOfficePre        = Prednameščena različica paketa
	SolutionsDeployOfficeNoSelect   = Izbran ni noben prednamestitveni paket Office
	SolutionsDeployOfficeVersion    = Različica {0}
	SolutionsDeployOfficeOnly       = Ohranite določene jezikovne pakete
	SolutionsDeployOfficeSync       = Ohranite jezikovno sinhronizacijo s konfiguracijo uvajanja
	SolutionsDeployOfficeSyncTips   = Po sinhronizaciji namestitveni skript ne more določiti želenega jezika.
	DeploySyncMainLanguage          = Sinhroniziraj z glavnim jezikom
	SolutionsDeployOfficeTo         = Razmestite namestitveni paket v
	SolutionsDeployOfficeToPublic   = Javno namizje
	DeployPackage                   = Namestite paket zbiranja po meri
	DeployPackageSelect             = Izberite paket pred zbiranjem
	DeployPackageTo                 = Namestite paket pred zbiranjem na
	DeployToRoot                    = istemski disk
	DeployPackageToSolutions        = V domačem imeniku rešitve
	DeployTimeZone                  = Časovni pas
	DeployTimeZoneChange            = Spremenite časovni pas
	DeployTimeZoneChangeTips        = Nastavite privzeto časovno območje, kjer naj se odgovori na predhodne odgovore, glede na jezikovno območje.

	Deploy_Tags                     = Oznaka za uvajanje
	FirstExpProcess                 = Prva izkušnja med predpogoji za uvajanje:
	FirstExpProcessTips             = Ko izpolnite predpogoje, znova zaženite računalnik, da rešite težavo, ki zahteva ponovni zagon, da začne veljati.
	FirstExpFinish                  = Prva izkušnja, po opravljenih predpogojih
	FirstExpSyncMark                = Dovoli globalno iskanje in sinhronizacijo oznak za uvajanje
	FirstExpDefender                = Dodaj domači imenik v Zaščiti izključene imenike
	FirstExpSyncLabel               = Oznaka nosilca sistemskega diska: ime domačega imenika je enako
	MultipleLanguages               = Ko naletite na več jezikov:
	NetworkLocationWizard           = Čarovnik za omrežno lokacijo
	PreAppxCleanup                  = Blokirajte naloge vzdrževanja čiščenja Appx
	LanguageComponents              = Preprečite čiščenje neuporabljenih jezikovnih paketov funkcij na zahtevo
	PreventCleaningUnusedLP         = Preprečite čiščenje neuporabljenih jezikovnih paketov
	FirstExpContextCustomize        = Dodajte prilagojeni "kontekstni meni"
	FirstExpContextCustomizeShift   = Držite tipko Shift in kliknite z desno miškino tipko

	FirstExpFinishTips              = Po končani uvedbi ni pomembnih dogodkov. Priporočljivo je, da prekličete.
	FirstExpFinishPopup             = Pojavno okno glavnega vmesnika mehanizma za uvajanje
	FirstExpFinishOnDemand          = Dovoli prvi predogled, kot je bilo načrtovano
	SolutionsEngineRestricted       = Obnovi pravilnik izvajanja Powershell: omejeno
	EnglineDoneClearFull            = Izbrišite celotno rešitev
	EnglineDoneClear                = Izbrišite mehanizem za uvajanje in obdržite druge

	Unattend_Auto_Fix_Next          = Ko naslednjič naletite na to, samodejno izberite potrebne elemente, da jo samodejno popravite.
	Unattend_Auto_Fix               = Samodejno popravi, ko predpogoji niso izbrani
	Unattend_Auto_Fix_Tips          = Ko dodate mehanizem za uvajanje in ne izberete prvega ukaza za zagon, se samodejno popravi in izbere: Politika izvajanja Powershell: zaženite mehanizem za uvajanje brez kakršnih koli omejitev.
	Unattend_Version_Tips           = Po želji vključite samo, uporabite privzeto za podporo ARM64, x64, x86.
	First_Run_Commmand              = Ukazi za zagon ob prvi uvedbi
	First_Run_Commmand_Setting      = Izberite ukaz za zagon
	Command_Not_Class               = Ni več samodejno kategorizirano pri filtriranju
	Command_WinSetup                = Namestitev sistema Windows
	Command_WinPE                   = Windows PE
	Command_Tips                    = Prosimo, dodelite prvi zagon aplikaciji: Windows Installation, Windows PE\n\nUpoštevajte, da ko dodate mehanizem za uvajanje, morate ob prvem zagonu preveriti naslednje: Politika izvajanja Powershell: Omejeno, dovoli izvajanje skriptov mehanizma za uvajanje.
	Waring_Not_Select_Command       = Pri dodajanju mehanizma za uvajanje ni bil izbran pravilnik o izvajanju Powershell: Ne nastavite nobenih omejitev in dovolite zagon skripta mehanizma za uvajanje. Izberite ga in poskusite znova ali kliknite "Hitri popravek ni izbran".
	Quic_Fix_Not_Select_Command     = Hitra rešitev ni možnost

	PowerShell_Unrestricted         = Politika izvajanja Powershell: brez omejitev
	Allow_Running_Deploy_Engine     = Dovoli izvajanje skriptov mehanizma za uvajanje
'@