ConvertFrom-StringData -StringData @'
	# pt-BR
	# Portuguese (Brazil)

	FontsUI                   = Segoe UI
	Mainname                  = Mecanismo de implantação: suíte de Yi
	Learn                     = Estudar
	MainHisName               = Solução bônus
	Location                  = Abrir local
	About                     = Sobre
	Reset                     = Reiniciar
	AddTo                     = Adicionar à
	Instl                     = Instalar
	ItInstalled               = Instalado
	Close                     = Encerramento
	Auto                      = Automático
	Disable                   = Desativar
	Enable                    = Habilitar
	Setting                   = Configurar
	Restore                   = Recuperar
	CLearn                    = Limpar
	Operable                  = Operável
	Inoperable                = Inoperável
	Optimize                  = Otimização
	Hide                      = Esconder
	Show                      = Mostrar
	Del                       = Excluir
	Done                      = Terminar
	OK                        = Claro
	Cancel                    = Cancelar
	AllSel                    = Selecionar tudo
	AllClear                  = Limpar tudo
	Refresh                   = Atualizar
	RefreshModules            = Atualização a quente de todos os módulos
	Necessary                 = Software essencial
	MostUsedSoftware          = Software comumente usado
	System                    = Sistema
	Service                   = Servir
	TaskBar                   = Todos os ícones da barra de tarefas
	DeskIcon                  = Ícones da área de trabalho
	InstallFonts              = Instalar fontes
	SettingTo                 = Definir como {0}
	AvailableLanguages        = Idiomas disponíveis
	SwitchLanguage            = Mudar de idioma
	LanguageReset             = Redefinir configurações de idioma
	LanguageCode              = Marca de zona
	LanguageSelRegion         = Selecione seu país ou região
	LanguageRemember          = Lembrar o idioma selecionado
	LanguageSearchNo          = Nenhum idioma disponível encontrado
	LanguageNoPack            = Se não houver nenhum pacote de idiomas localmente, ele será encerrado automaticamente.
	LanguageNoSel             = Selecione uma região
	Search                    = Procurar
	PleaseChoose              = Selecione
	FailedCreateFolder        = Falha ao criar diretório
	Failed                    = Falhar
	ToMsg                     = {0} Retorne automaticamente ao menu principal após segundos.
	Restart                   = A reinicialização entra em vigor
	AdvOption                 = Recursos opcionais

	StartDown                 = Comece a baixar
	ConnectTo                 = Conecte-se a
	FileName                  = Nome do arquivo
	SaveTo                    = Salvar em
	NotAvailable              = Situação: Não disponível
	ExistingPacker            = Já tem pacote de instalação
	ExistingInstlPacker       = Já tem um pacote compactado
	Unpacking                 = Descompactando
	QucikRun                  = Execução rápida:
	WaitDone                  = Aguardando conclusão:
	Parameter                 = Parâmetro:
	ErrorDown                 = Ocorreu um erro durante o download
	UserCancel                = O usuário cancelou a operação.

	VerifyNameTips            = Somente uma combinação de letras e números em inglês é permitida e nenhum outro caractere é permitido: espaços, o comprimento não pode ser superior a 16 caracteres, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Prefixo de diretório personalizado
	NoSetFolderLabel          = Prefixo de diretório personalizado não definido
	ISO9660TipsErrorSpace     = Não pode conter: espaços iniciais e finais
	ISO9660TipsErrorOther     = Não pode conter: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = O rótulo do volume não pode ter mais de {0} caracteres
	Help                      = Ajuda
	WorkDone                  = Concluído, pressione qualquer tecla para retornar à interface principal...
	Short_Cmd                 = Atalhos
	Options                   = Opções
'@