ConvertFrom-StringData -StringData @'
	# sv-SE
	# Swedish (Sweden)

	FontsUI                   = Segoe UI
	Mainname                  = Implementeringsmotor: Yi's suite
	Learn                     = Studera
	MainHisName               = Bonuslösning
	Location                  = Öppen plats
	About                     = Om
	Reset                     = Återställa
	AddTo                     = Lägg till
	Instl                     = Installera
	ItInstalled               = Installerad
	Close                     = Stängning
	Auto                      = Automatisk
	Disable                   = Inaktivera
	Enable                    = Aktivera
	Setting                   = Inrätta
	Restore                   = Återvinna
	CLearn                    = Städa upp
	Operable                  = Manövrerbar
	Inoperable                = Inoperabel
	Optimize                  = Optimering
	Hide                      = Dölja
	Show                      = Visa
	Del                       = Radera
	Done                      = Avsluta
	OK                        = Säker
	Cancel                    = Avboka
	AllSel                    = Välj alla
	AllClear                  = Rensa allt
	Refresh                   = Uppdatera
	RefreshModules            = Varmuppdatera alla moduler
	Necessary                 = Viktig programvara
	MostUsedSoftware          = Vanligt använda programvara
	System                    = System
	Service                   = Tjäna
	TaskBar                   = Alla ikoner i aktivitetsfältet
	DeskIcon                  = Skrivbordsikoner
	InstallFonts              = Installera teckensnitt
	SettingTo                 = Ställ in på {0}
	AvailableLanguages        = Tillgängliga språk
	SwitchLanguage            = Byta språk
	LanguageReset             = Återställ språkinställningar
	LanguageCode              = Zonmärke
	LanguageSelRegion         = Välj ditt land eller din region
	LanguageRemember          = Kom ihåg valt språk
	LanguageSearchNo          = Inga tillgängliga språk hittades
	LanguageNoPack            = Om det inte finns något språkpaket lokalt kommer det att avslutas automatiskt.
	LanguageNoSel             = Välj en region
	Search                    = Söka
	PleaseChoose              = Vänligen välj
	FailedCreateFolder        = Det gick inte att skapa katalogen
	Failed                    = Misslyckas
	ToMsg                     = {0} Återgå automatiskt till huvudmenyn efter några sekunder.
	Restart                   = Omstart träder i kraft
	AdvOption                 = Valfria funktioner

	StartDown                 = Börja ladda ner
	ConnectTo                 = Anslut till
	FileName                  = Filnamn
	SaveTo                    = Spara till
	NotAvailable              = Status: Ej tillgängligt
	ExistingPacker            = Har redan installationspaket
	ExistingInstlPacker       = Har redan ett komprimerat paket
	Unpacking                 = Dra upp blixtlåset
	QucikRun                  = Snabbkörning:
	WaitDone                  = Väntar på slutförande:
	Parameter                 = Parameter:
	ErrorDown                 = Ett fel uppstod under nedladdningen
	UserCancel                = Användaren har avbrutit åtgärden.

	VerifyNameTips            = Endast en kombination av engelska bokstäver och siffror är tillåten, och inga andra tecken är tillåtna: mellanslag, längden får inte vara längre än 16 tecken, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Anpassat katalogprefix
	NoSetFolderLabel          = Anpassat katalogprefix inte inställt
	ISO9660TipsErrorSpace     = Kan inte innehålla: ledande och efterföljande utrymmen
	ISO9660TipsErrorOther     = Kan inte innehålla: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Volymetiketten får inte vara längre än {0} tecken
	Help                      = Hjälp
	WorkDone                  = Slutfört, tryck på valfri tangent för att återgå till huvudgränssnittet...
	Short_Cmd                 = Genvägar
	Options                   = Alternativ
'@