ConvertFrom-StringData -StringData @'
	# it-IT
	# Italian (Italy)

	UnpackISO                       = Genera ISO
	ISOLabel                        = L'etichetta del volume è stata impostata:
	ISOCustomize                    = Nome dell'etichetta del volume ISO
	ISO9660                         = Verificare le regole di denominazione
	ISO9660Tips                     = Il nome univoco non può superare i 260 caratteri, il nome del volume ISO non può superare i 16 caratteri e non può contenere: spazi iniziali e finali, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Denominazione univoca personalizzata
	ISOAddFlagsLang                 = Aggiungi markup multilingue
	ISOAddFlagsLangGet              = Ottieni le lingue di installazione conosciute
	ISOAddFlagsVer                  = Aggiungi tag multiversione
	ISOAddFlagsVerGet               = Ottieni la versione dell'immagine conosciuta
	ISOAddEICFG                     = Aggiungi tipo di versione
	ISOAddEICFGTips                 = Quando si fa affidamento su EI.cfg, si tratta di una versione commerciale.
	ISO9660TipsErrorSpace           = Non può contenere: spazi iniziali e finali
	ISO9660TipsErrorOther           = Non può contenere: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Seleziona il tipo di lingua
	SelLabel                        = nome in codice
	ISOVerLabel                     = Seleziona il nome del volume ISO
	NoSetLabel                      = Etichetta del volume ISO personalizzata non impostata
	ISOLengthError                  = L'etichetta del volume non può contenere più di {0} caratteri
	RenameFailed                    = Uguale alla vecchia directory, ridenominazione non riuscita
	ISOCreateAfter                  = Cosa devi fare prima di creare una ISO
	ISOCreateRear                   = Cosa devi fare dopo aver creato l'ISO
	BypassTPM                       = Ignorare il controllo dell'installazione del TPM
	Disable_BitLocker               = Disattiva la crittografia del dispositivo BitLocker durante l'installazione
	PublicDate                      = data di emissione
	PublicDateGetCurrent            = Sincronizza la data corrente
	PublicYear                      = Anno
	PublicMonth                     = luna
	PublicYMSorting                 = Ordina: cambia "mese_anno" in "anno_mese"
	PublicYMSortingTips             = AB: non aggiungere il trattino basso _ quando si usano i numeri.
	PublicYMUseShortNames           = Usa nomi brevi
	PublicYMUseNumbers              = Usa numeri
	ISOCreateFailed                 = Creazione non riuscita, la directory non è leggibile o scrivibile.
	ISORefreshAuto                  = Aggiorna i tag ISO ogni volta
	ISOSaveTo                       = Posizione di salvataggio predefinita ISO
	ISOSaveSameGlobal               = Utilizza la posizione di salvataggio predefinita ISO globale
	ISOSaveSync                     = Sincronizza automaticamente la nuova posizione dopo aver selezionato il disco di ricerca dell'origine dell'immagine
	ISOSaveSame                     = Cerca il percorso del disco utilizzando l'origine dell'immagine
	ISOFolderWrite                  = Verificare che la directory sia leggibile e scrivibile
	SelectAutoAvailable             = Quando si seleziona automaticamente un disco disponibile
	SelectCheckAvailable            = Controlla lo spazio minimo rimanente disponibile
	ISOStructure                    = nuova struttura di directory
	ISOOSLevel                      = Aggiungi tipo di installazione
	ISOUniqueNameDirectory          = Aggiungi directory con nomi univoci
	NextDoOperate                   = Non creare ISO
	SelCreateISO                    = Genera ISO, esegui su richiesta
	Reconstruction                  = Ricostruisci {0}.wim con la massima compressione
	Reconstruction_Tips_Select      = Prima della ricostruzione, verrà eseguito solo quando non è caricato. Forza l'abilitazione del salvataggio e quindi smonta il file montato.
	ReconstructionTips              = Oltre 520 MB, si consiglia la ricostruzione
	CreateASC                       = Aggiungi la firma PGP all'ISO
	NoPGPKey                        = In PGP non esiste una chiave privata utilizzabile.
	CreateASCPwd                    = Password del certificato
	PasswordRenter                  = Reinserisci la password
	ShowPassword                    = Mostra password
	NewPasswordSome                 = La password non corrisponde.
	PwdPermanent                    = Archiviazione permanente
	PwdDecfailed                    = Decrittografia non riuscita
	CreateASCAuthor                 = firmatario
	CreateASCAuthorTips             = Nessun firmatario selezionato.
	ISO_Sparse_Rename               = Aggiungere hash all'estensione del nome del file
	GenerateRandom                  = Genera numeri casuali
	RandomNumberReset               = Rigenerare
'@