ConvertFrom-StringData -StringData @'
	# he-IL
	# Hebrew (Israel)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = לוּחַ מַחווָנִים
	Learn                           = לִלמוֹד
	Menu                            = תַפרִיט
	Short_Cmd                       = פקודת קיצור
	Shortcut                        = קיצור דרך
	Update                          = לְחַדֵשׁ
	CUpdate                         = עדכונים מצטברים
	Rebuild                         = שִׁחזוּר
	AddTo                           = הוסף ל
	Del                             = לִמְחוֹק
	Copy                            = לְהַעְתִיק
	Rename                          = שנה שם
	Refresh                         = לְרַעֲנֵן
	RefreshModules                  = רענון חם של כל המודולים
	Done                            = סִיוּם
	OK                              = בַּטוּחַ
	Cancel                          = לְבַטֵל
	AllSel                          = בחר הכל
	AllClear                        = לנקות הכל
	Setting                         = לְהַקִים
	Change                          = לְשַׁנוֹת
	Help                            = עֶזרָה
	Logging                         = שמור יומן ב
	AvailableLanguages              = שפות זמינות
	SwitchLanguage                  = להחליף שפה
	LanguageSelRegion               = בחר את המדינה או האזור שלך
	LanguageRemember                = זכור את השפה שנבחרה
	LanguageSearchNo                = לא נמצאו שפות זמינות
	LanguageNoPack                  = אם אין ערכת שפה מקומית, היא תצא אוטומטית.
	LanguageNoSel                   = אנא בחר אזור
	Search                          = לְחַפֵּשׂ
	PleaseChoose                    = נא לבחור
	Options                         = אפשרויות
	Choose                          = נִבחָר
	NoChoose                        = לא נבחר
	AdvOption                       = תכונות אופציונליות
	ExcludeItem                     = אל תכלול לפי כלל
	DeDuplication                   = אל תכלול כפילויות
	DeDuplication_Unlock            = בטל את הנעילה של כפילויות מושבתות
	Existed                         = כבר קיים
	FailedCreateFolder              = יצירת הספרייה נכשלה
	FailedCreateFile                = יצירת הקובץ נכשלה
	ToMsg                           = {0} חזור אוטומטית לתפריט הראשי לאחר שניות.
	OnDemandPlanTask                = הקצאה מותאמת אישית של אירועים ידועים
	Operable                        = נָתִיחַ
	Inoperable                      = בלתי ניתן להפעלה
	Hide                            = לְהַסתִיר
	CuringUpdate                    = עדכון מוצק
	CuringUpdateTips                = לאחר שהעדכון התגבש לא ניתן להסירו.
	Healthy                         = בָּרִיא
	HealthyTips                     = חשוב במיוחד לבדוק את מצב התקינות כאשר "ניתן לתיקון" או "לא ניתן לתיקון" מופיעה: במהלך תהליך המרת ESD, שגיאה 13 מדווחת על שגיאה בעת התקנת המערכת.
	Healthy_Save                    = כאשר מופיע בר תיקון או בלתי ניתן לתיקון, אל תשמור.
	Repair                          = לְתַקֵן
	IsAuto_Repair                   = אפשר תיקון אוטומטי במצב סרק
	IsAuto_Repair_Tips              = בדוק באופן אוטומטי אם יש משימות הרכבה לאחר כל הפעלה של סקריפט האריזה. אם הוא מותקן, לא יבוצע תיקון אם הוא לא מותקן, יופעל תיקון אוטומטי.
	Repairable                      = ניתן לתיקון
	NonRepairable                   = לא ניתן לתיקון
	HealthyForceStop                = במהלך עיבוד האירוע, אירעה שגיאה בלתי הפיכה והאירוע הופסק בכוח.\n\n   גורם לבעיות עיקריות:\n\n      1. חומרה פיזית פגומה, דיסק קשיח;\n\n      2. אם אתה משתמש בדיסק וירטואלי בזיכרון RAMDISK (כולל היברידי), אנא בדוק את הזיכרון הפיזי;\n\n      3. ודא את ה-SHA256 המקורי של MVS (MSDN) אם הוא עקבי, אנא שנה את הספרייה ונסה שוב אם ה-SHA256 אינו עקבי, אנא הורד אותו שוב ונסה שוב.\n\n      4. אחרים אינם מופיעים בדוגמה זו.
	Superseded                      = נקה את המוחלף
	SupersededTips                  = כולל עדכונים מיושנים, רכיבים וכו'.
	UnmountFailed                   = ניסיתי כמה שיטות, אבל שום דבר לא יכול להיעשות אני יכול רק להפסיק אני רוצה לראות אותך בפעם הבאה.
	SaveTo                          = לשמור ל
	WorkDone                        = הושלם, הקש על מקש כלשהו כדי לחזור לממשק הראשי...
	UserCanel                       = המשתמש ביטל את הבקשה.
	Uping                           = יוצר
	Exclude_View                    = הצג כללי אי הכללה
	User_Interaction                = אינטראקציה של משתמשים
	Ok_Go_To                        = זמין ל
	Ok_Go_To_No                     = לא הולך

	Detailed                        = מְפוֹרָט
	Detailed_View                   = הצג את פרטי הכלל שנבחרו

	AddEnv                          = הוסף פונקציונליות ניתוב למשתני מערכת
	AddEnvTips                      = לאחר ההוספה, הזן Yi בכל הפעלת PowerShell כדי להגיב. לדוגמה, הזן "Yi -SIP" כדי להפעיל את האנקפסולציה.

	Unzip_ISO                       = חלץ ISO
	Unzip_Search_Type               = חפש בספריית ( {0} )
	ISO_Other                       = מסמכים אחרים
	Unzip_Language                  = ערכת שפה
	Unzip_Fod                       = חבילת תכונות
	FileName                        = שם הקובץ

	UserCancel                      = המשתמש ביטל את הפעולה.
	MatchMode                       = לְהַתְאִים
	Failed                          = לְהִכָּשֵׁל
	RandomSelect                    = נבחר באקראי
	RulePre                         = כללים מוגדרים מראש
	RuleOther                       = כללים אחרים
	RuleCustomize                   = כללים מותאמים אישית
	RuleCustomize_Dont              = אל תשתמש בכללים מותאמים אישית של ספריות מרובות רמות
	RuleCustomize_Dont_Tips         = לאחר מחיקת הספרייה הישנה, לחץ על "אמת כללי שמות".
	RuleMultistage                  = כללי ספרייה מרובת רמות
	RuleMultistageFindFailed        = לא נמצאו חוקי ספרייה מרובים, לחץ עליי כדי ליצור תבנית.
	RuleMultistageFindCreateNew     = צור תבנית חדשה של כלל ספרייה מרובת רמות
	RuleMultistageTips              = התאם אוטומטית כללי ספרייה מרובת רמות, כלל ספרייה {0} הושבת.
	RuleCustomizeNot                = שם התוסף (Solutions.Custom.Extension) לא נמצא, אנא עיין בתיעוד העזרה.
	RuleCustomizeTips               = לא נוצר כלל מותאם אישית, אנא עיין בתיעוד העזרה.
	RuleMatchNoFindFolder           = לא הצליח להתאים את הספרייה, לחץ עליי כדי ליצור את הספרייה.
	RuleNoFindFile                  = לא נמצאו קבצים זמינים, אנא הוסף ורענן.
	RuleFindFolder                  = ספרייה נבחרה אוטומטית כאשר היא זמינה
	RuleNameNewChange               = סנכרון אוטומטי לאחר עדכונים
	RuleNewTempate                  = צור תבנית
	RuleSkipFolderCheck             = כבר לא בודק אם הקובץ קיים בספרייה ובסוג הקובץ
	RuleAuthon                      = יוצר כללים
	RuleGUID                        = מזהה ייחודי עולמי של GUID
	RuleName                        = שם כלל
	RuleDescription                 = לְתַאֵר
	RuleNameUse                     = סנכרן את שם הכלל ל: {0}
	RuleISO                         = התאם חבילת התקנת ISO מקורית
	RuleInBoxApps                   = יישום שלם ומוגדר מראש
	RuleFileType                    = שם החבילה
	RuleFileFind                    = שם חיפוש מעורפל
	RuleFindError                   = נמצאו {0} פריטים לעיבוד, לחץ על "בדוק תלות" כדי להציג פרטים.
	RuleSelectApps                  = יישומים שנבחרו על ידי המשתמש
	DependencyPackage               = חבילת תלות
	RuleDependenciesRequired        = תלות נדרשת
	RuleDependenciesUnselected      = תלות לא נבחרה
	RuleDependenciesNoCheck         = התלות כבר לא נבדקת
	RuleDependenciesFix             = תקן תלות שלא נבחרה
	Extract_Tips                    = רֶמֶז\n\n   1. התוצאה לאחר חילוץ חבילת השפה לא יכולה לשמש כאובייקט הפניה הראשי;\n\n   2. אנא השתמש ברשימת הרכיבים כאובייקט ההתייחסות הראשי כיצד ליצור:\n\n       ב בחר את הרכיב שנוצר ב- Functions (קבל את החבילה בתמונה המותקנת), בחר הדפס או הצג מיד; בחר Generate Component (קבל את החבילה בתמונה המותקנת), בחר Print או View Instantly;\n\n   3. לאחר התקנת ערכת השפה, נא ליצור מחדש דוח רכיבים כדי לבדוק אם הוא מתאים;

	DescendingRuleLang              = הסר חבילות שפה בסדר הפוך
	OrderRuleLang                   = התקן חבילות שפה בסדר שנקבע מראש
	OrderRuleLangTips               = הוסף לפי הסדר: בסיסי, גופנים, זיהוי תווים אופטי, זיהוי כתב יד, טקסט לדיבור, זיהוי דיבור, חוויית הדגמה קמעונאית, אחר
	RuleLanguageTips                = לְהַדגִים: \n\n   לאחר השימוש ב"התקן חבילות שפה בסדר שנקבע מראש", קבצים מותאמים אוטומטית בשמות מטושטשים בסדר הבא: \n
	Match_installed_List            = בעת התקנת ערכת שפה, תווים כלליים לחיפוש מהרשימה המותקנת
	Match_installed_List_Tips       = מתאים רק כאשר מותקן: בסיסי, זיהוי תווים אופטי, זיהוי כתב יד, טקסט לדיבור, זיהוי דיבור.
	RuleLanguageTipsExt             = \n   כאשר לא משתמשים ב"התקן חבילות שפה בסדר שנקבע מראש": \n   חפש אוטומטית בכל הקבצים בספריה לפי סוג קובץ והתקן אותם.\n\n   תכונות שפה ואזור לפי דרישה (FOD)\n   https://learn.microsoft.com/he-il/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = קָטֵגוֹרִיָה
	Basic                           = בְּסִיסִי
	Fonts                           = גוֹפָן
	OCR                             = זיהוי תווים אופטי
	Handwriting                     = זיהוי כתב יד
	TextToSpeech                    = טקסט לדיבור
	Speech                          = זיהוי דיבור
	Retail                          = חווית הדגמה קמעונאית
	Features_On_Demand              = תכונות לפי דרישה
	RegionSpecific                  = דרישות אחרות ספציפיות לאזור
	UnassignedLangFiles             = קבצים שונים שלא הוקצו

	ProcessingImage                 = עבד את התמונה:
	NoInstallImage                  = לא קיים במקום
	ConvertChk                      = בדוק את הקובץ
	WindowsFeature                  = תכונות של Windows
	Enable                          = לְאַפשֵׁר
	Disable                         = השבת
	EnableFeatureTips               = רֶמֶז\n\n    1. הצג את NetFx3 ו-TelnetClient כפריטי פונקציה מופעלים מראש;\n\n    2. לאחר "הרכבה", ניתן להפעיל יותר.
	ViewLanguage                    = הצג את הגדרות שפת התמונה
	ImageLanguage                   = הגדרות שפת תמונה
	OnlyLangCleanup                 = רכיבים נקיים: תג לפי שפה
	Matched_Component_Names         = שם רכיב תואם:
	BootProcess                     = בעת עיבוד {0}.wim
	Extract_Rule_Only_And_Full      = חלץ רק שפות נבחרות
	Sync_Language_To                = סנכרן עם
	BootSyncToISO                   = סנכרן חבילות שפה למתקין
	BootSyncToISOTips               = ערכת השפה המותקנת של התמונה הלא מקוונת מסונכרנת למתקין ISO.
	Setup_Fix_Missing               = תקן אוטומטית פריטי התקנה חסרים
	Setup_Fix_Missing_Tips          = אם לתוכנית ההתקנה חסר arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui, פתח את "חלץ", בחר "כללים" ולחץ על "חלץ פריטים חסרים של מתקין".
	Setup_Fix_Missing_Extract       = חלץ פריטים חסרים במתקין
	Setup_Fix_Missing_Extract_Tips  = חלץ את הפריטים החסרים של המתקין מכל חבילות השפה המקומיות: arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui.
	LangIni                         = צור מחדש את Lang.ini
	LangIniTips                     = לאחר השלמת הסנכרון, יש לבנות מחדש את Lang.ini ב-ISO.
	LangNewAutoSelect               = בחר אוטומטית פריטים מוצעים כאשר מתרחש אירוע
	LangNewAutoSelectTips           = ישנם אירועים חדשים, "סנכרן ערכת שפה למתקין", "בנה מחדש את Lang.ini" נבחר.
	LangNewAutoNoSelect             = ישנם אירועים חדשים, מומלץ לבחור "סנכרן ערכת שפה למתקין" ו"בנה מחדש את Lang.ini".
	LangNewAutoNoNewSelect          = אין אירועים חדשים. מומלץ לא לבחור "סנכרן ערכת שפה למתקין" או "בנה מחדש את Lang.ini".
	Drive                           = לִנְהוֹג
	ViewDrive                       = הצג מנהלי התקנים מותקנים
	EditionsProductKey              = מפתח מוצר
	Editions                        = גרסת תמונה
	Assign_Editions                 = הפצה אוטומטית של יישומים על סמך גרסאות תמונה
	EditionsChangeTips              = אזהרה, אנא הבינו לפני החלפת גרסאות תמונה:\n\nMicrosoft הסכם שירות\nhttps://www.microsoft.com/he-il/servicesagreement/default.aspx\n\nסקירת שפה\nhttps://learn.microsoft.com/he-il/windows-hardware/manufacture/desktop/languages-overview\n\nאינך רשאי ליצור גרסאות של:\n   1. ספציפי למדינה\n       ProfessionalCountrySpecific\n\n   2. גרסה ביתית ספציפית לאזור\n       ProfessionalSingleLanguage\n\nנא לציית בקפדנות מכיוון שאתה עלול להיות נתון לתביעה אם תופר.\n\nאם אתה מתעקש להמיר, לחץ כדי לקבל את האזהרה ולחץ על "בטל נעילת גרסת תמונה נסתרת".
	EditionsChangeHide              = בטל את הנעילה של גרסאות תמונה נסתרות
	EditionsChangeAccect            = קראתי את האזהרה ואני אחראי לחוקים הרלוונטיים הכלולים באזהרה

	SelFile                         = בחר קובץ
	Rebuilding                      = בשחזור
	RebuildAll                      = בנה הכל מחדש
	Export_Image                    = יְצוּא
	SelectFromError                 = טָעוּת
	SelectFileFormatError           = פורמט הקובץ שגוי

	SearchDrive                     = מונע חיפוש
	SearchUpdate                    = חפש עדכונים, סוג ( {0} ), מקור:
	SelectFolder                    = בחר ספרייה
	DropFolder                      = יכול לגרור ספריות לחלון הנוכחי
	DropFile                        = ניתן לגרור קבצים לחלון הנוכחי
	Sparse                          = נָדִיר
	CRCSHA                          = לִבדוֹק
	Alternative                     = שם קובץ חלופי
	ChangeInstallDisk               = שנה בחירת דיסק אוטומטי

	# View
	ExportToLogs                    = הדפס דוח ליומן
	ExportShow                      = הצג דוחות באופן מיידי
	MoreFeature                     = תכונות נוספות
	OpenFolder                      = פתח את הספרייה
	OpenFile                        = לפתוח קובץ
	Running                         = לָרוּץ
	Paste                           = העתק נתיב
	Clipboard_Copy                  = הועתק ללוח
	ViewWIMFileInfo                 = צפה בתמונה
	GetInBoxApps                    = InBox Apps: חבילות יישומים מותקנות
	GetImagePackage                 = רכיבים: כל החבילות המותקנות בתמונה
	ViewMounted                     = קבל מידע על כל התמונות המותקנות
'@