ConvertFrom-StringData -StringData @'
	# pt-BR
	# Portuguese (Brazil)

	Main_quests                     = Tarefas Principais
	Side_quests                     = Subtarefas
	SaveModeClear                   = Limpar histórico selecionado
	SaveModeTipsClear               = O histórico foi salvo e pode ser apagado
	SelectTips                      = Dica\n\n    1. Selecione o nome da imagem a ser processada;\n    2. Após o cancelamento, as tarefas que requerem "montagem" antes da operação não terão mais efeito.
	CacheDisk                       = Cache de disco
	CacheDiskCustomize              = Caminho de cache personalizado
	AutoSelectRAMDISK               = Permitir seleção automática de rótulo de volume de disco
	AutoSelectRAMDISKFailed         = Rótulo do volume não correspondido
	ReFS_Find_Volume                = Quando o formato de disco REFS for encontrado, exclua
	ReFS_Exclude                    = Partição ReFS excluída
	Disk_Not_satisfied_Exclude      = Requisitos mínimos de disco não atendidos
	RAMDISK_Change                  = Alterar o nome do rótulo do volume
	RAMDISK_Search                  = Pesquisar nome do rótulo do volume
	RAMDISK_Restore                 = Restaurar nome do volume inicializado: {0}
	AllowTopMost                    = Permitir que janelas abertas sejam fixadas na parte superior
	History                         = Limpar histórico
	History_Del_Tips                = Quando houver uma tarefa de encapsulamento, não execute as seguintes opções opcionais, caso contrário causará problemas desconhecidos durante a execução do script de encapsulamento.
	History_View                    = Ver histórico
	HistoryLog                      = Permitir limpeza automática de registros com mais de 7 dias
	HistorySaveFolder               = Outros caminhos de origem da imagem
	HistoryClearappxStage           = Aplicativos InBox: exclua arquivos temporários gerados durante a instalação
	DoNotCheckBoot                  = Quando o tamanho do arquivo Boot.wim excede 520 MB, a reconstrução é selecionada automaticamente ao gerar o ISO.
	HistoryClearDismSave            = Exclua os registros de montagem DISM salvos no registro
	ImageSourcesClickShowKey        = Permitir a exibição do menu "Selecionar chave primária"
	ImageSourcesClickShowKeyTips    = Após o usuário selecionar a origem da imagem: Adicione um menu "Selecionar chave primária" à direita e adicione as opções "Ir para": Montar, Salvar, Janela pop-up.
	Clear_Bad_Mount                 = Exclua todos os recursos associados à imagem montada corrompida
	ShowCommand                     = Mostrar a execução completa da linha de comando
	Command                         = Linha de comando
	SelectSettingImage              = Fonte da imagem
	NoSelectImageSource             = Nenhuma fonte de imagem selecionada
	SettingImageRestore             = Restaurar local de montagem padrão
	SettingImage                    = Alterar local de montagem da fonte da imagem
	SelectImageMountStatus          = Obtenha o status de montagem após selecionar a fonte da imagem
	SettingImageTempFolder          = Diretório temporário
	SettingImageToTemp              = O diretório temporário é o mesmo local onde foi montado
	SettingImagePathTemp            = Usando o diretório Temp
	SettingImageLow                 = Verifique o espaço restante mínimo disponível
	SettingImageNewPath             = Selecione o disco de montagem
	SettingImageNewPathTips         = É recomendável montá-lo em um disco de memória, que é o mais rápido. Você pode usar software de memória virtual como Ultra RAMDisk e ImDisk.
	SelectImageSource               = "Deploy Engine Solution" foi selecionado, clique em OK.
	NoImagePreSource                = Nenhuma fonte disponível encontrada, você deve: \n\n     1. Adicione mais fontes de imagem a: \n          {0}\n\n     2. Selecione "Configurações" e selecione novamente o disco de pesquisa de origem da imagem;\n\n     3. Selecione "ISO" e selecione o ISO a ser descompactado, os itens a serem montados, etc.
	NoImageOtherSource              = Clique em mim para "Adicionar" outros caminhos ou "Arrastar Diretório" para a janela atual.
	SearchImageSource               = Disco de pesquisa de origem de imagem
	Kernel                          = Núcleo
	Architecture                    = Arquitetura
	ArchitecturePack                = Arquitetura de pacotes, entendendo regras de adição
	ImageLevel                      = Tipo de instalação
	LevelDesktop                    = Área de trabalho
	LevelServer                     = Servidor
	ImageCodename                   = Codinome
	ImageCodenameNo                 = Não reconhecido
	MainImageFolder                 = Diretório inicial
	MountImageTo                    = Montar em
	Image_Path                      = Caminho da imagem
	MountedIndex                    = Índice
	MountedIndexSelect              = Selecione o número do índice
	AutoSelectIndexFailed           = A seleção automática do índice {0} falhou. Tente novamente.
	Apply                           = Aplicativo
	Eject                           = Aparecer
	Mount                           = Montar
	ReMount                         = Remontar
	Unmount                         = Desinstalar
	Mounted                         = Montado
	NotMounted                      = Não montado
	NotMountedSpecify               = Não montado, você pode especificar o local de montagem
	MountedIndexError               = Montagem anormal, exclua e tente novamente.
	NeedsRemount                    = Requer remontagem
	Invalid                         = Inválido
	ImageSouresNoSelect             = Mostrar mais detalhes após selecionar a fonte da imagem
	Mounted_Mode                    = Modo de montagem
	Mounted_Status                  = Status da montagem
	Status                          = Status
	Image_Popup_Default             = Salvar como padrão
	Image_Restore_Default           = Reverter para o padrão
	Image_Popup_Tips                = Dica:\n\nAo atribuir o evento, você não especificou o número de índice para processar {0};\n\nA interface de seleção apareceu. Especifique o número do índice. Após a conclusão da especificação, é recomendável selecionar "Salvar como padrão. Ele não aparecerá novamente na próxima vez que você processá-lo".
	Rule_Show_Full                  = Mostrar tudo
	Rule_Show_Only                  = Mostrar apenas regras
	Rule_Show_Only_Select           = Escolha entre as regras
	Image_Unmount_After             = Desinstalar tudo montado

	Wim_Rule_Update                 = Extraia e atualize arquivos dentro da imagem
	Wim_Rule_Extract                = Extrair arquivos
	Wim_Rule_Extract_Tips           = Após selecionar a regra de caminho, extraia o arquivo especificado e salve-o localmente.

	Wim_Rule_Verify                 = Verificar
	Wim_Rule_Check                  = Examinar
	Wim_Rule_CheckIntegrity         = Verificar Integridade
	Wim_Rule_ReadOnly               = Permissão somente leitura
	Wim_Rule_Optimize               = Otimização
	ResetBase                       = Limpeza profunda
	Wim_Rule_SupportEa              = Aplicar imagens com atributos estendidos
	Wim_Rule_WIMBoot                = Inicializável
	Wim_Rule_Compact                = Compactar Arquivos do Sistema Operacional
	Win_Rule_Setbootable            = Marcar Imagem de Volume como Inicializável
	Win_Rule_Setbootable_Tips       = Este parâmetro aplica-se apenas a imagens do Windows PE.\nApenas uma imagem de volume pode ser marcada como inicializável em um arquivo .wim.
	Destination                     = Destino

	Wim_Append                      = Anexar
	Wim_Capture                     = Capturar
	Wim_Capture_Tips                = Capturar a imagem da unidade para um novo arquivo WIM.
	Wim_Capture_Sources             = Origem da Captura
	Wim_Capture_Sources_Tips        = O diretório capturado contém todas as subpastas e dados.\nNão é possível capturar um diretório vazio. O diretório deve conter pelo menos um arquivo.
	Wim_Config_File                 = Caminho do Arquivo de Configuração ( Exclusões )
	Wim_Config_Edit                 = Editar
	Wim_Config_Learn                = Consulte a lista de configurações e o arquivo WimScript.ini

	Wim_Rename                      = Modificar informações da imagem
	Wim_Image_Name                  = Nome da imagem
	Wim_Image_Description           = Descrição da imagem
	Wim_Display_Name                = Nome de exibição
	Wim_Display_Description         = Mostrar descrição
	Wim_Edition                     = Marca de imagem
	Wim_Edition_Select_Know         = Selecione sinalizadores de imagem conhecidos
	Wim_CreatedTime                 = Data de criação
	Wim_ModifiedTime                = Data da última modificação
	Wim_FileCount                   = Número de arquivos
	Wim_DirectoryCount              = Número de diretórios
	Wim_Expander_Space              = Espaço de expansão

	IABSelectNo                     = Nenhuma chave primária selecionada: Install, WinRE, Boot
	Unique_Name                     = Nomenclatura única
	Select_Path                     = Caminho
	Setting_Pri_Key                 = Defina este arquivo de atualização como modelo principal
	Pri_Key_Update_To               = Em seguida, atualize para
	Pri_Key_Template                = Defina este arquivo como o modelo preferido para ser sincronizado com os itens selecionados
	Pri_key_Running                 = A tarefa de chave primária foi sincronizada e ignorada.
	ShowAllExclude                  = Mostrar todas as exclusões obsoletas

	Index_Process_All               = Processe todos os números de índice conhecidos
	Index_Is_Event_Select           = Quando há um evento, a interface de seleção do número de índice é exibida.
	Index_Pre_Select                = Número de índice pré-atribuído
	Index_Select_Tips               = Dica: \n\n{0}.wim não está ativado no momento, você pode: \n\n   1. Selecione "Processar todos os números de índice conhecidos";\n\n   2. Selecione "Quando houver um evento, a interface de seleção do número de índice aparecerá";\n\n   3. Número de índice pré-especificado\n      O número de índice 6 é especificado, o número de índice não existe durante o processamento e o processamento é ignorado.

	Index_Tips_Custom_Expand        = Grupo: {0}\n\nAo processar {1}, o número de índice {2} precisa ser atribuído, caso contrário não poderá ser processado.\n\nDepois de selecionar "Sincronizar regras de atualização para todos os números de índice", você só precisa marcar qualquer um como modelo principal.

	DefenderExclude                 = Exclusões do antivírus do Windows
	DefenderFolder                  = Adicionar este diretório às exclusões do antivírus do Windows.
	DefenderVolume                  = Após encontrar um nome de rótulo de volume correspondente, adicione este disco às exclusões do antivírus do Windows.
	DefenderIsAdd                   = Adicionado às exclusões do antivírus do Windows
'@