ConvertFrom-StringData -StringData @'
	# et-ee
	# Estonian (Estonia)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Armatuurlaud
	Learn                           = Uuring
	Menu                            = Menüü
	Short_Cmd                       = Otseteed
	Shortcut                        = Otsetee
	Update                          = Uuendada
	CUpdate                         = Kumulatiivsed värskendused
	Rebuild                         = Rekonstrueerimine
	AddTo                           = Lisa juurde
	Del                             = Kustutada
	Copy                            = Kopeerida
	Rename                          = Nimeta ümber
	Refresh                         = Värskenda
	RefreshModules                  = Kõigi moodulite kuumvärskendus
	Done                            = Lõpeta
	OK                              = Muidugi
	Cancel                          = Tühista
	AllSel                          = Valige kõik
	AllClear                        = Tühjenda kõik
	Setting                         = Üles seada
	Change                          = Muuda
	Help                            = Abi
	Logging                         = Logi
	AvailableLanguages              = Saadaolevad keeled
	SwitchLanguage                  = Keelt vahetada
	LanguageSelRegion               = Valige oma riik või piirkond
	LanguageRemember                = Jäta valitud keel meelde
	LanguageSearchNo                = Saadaolevaid keeli ei leitud
	LanguageNoSel                   = Valige piirkond
	Search                          = Otsida
	SearchAllDrives                 = Otsi kõikidelt draividelt
	MountCategory                   = Kõik ISO-d leitud, paigaldatud
	PleaseChoose                    = Palun valige
	Options                         = Valikud
	Choose                          = Valitud
	NoChoose                        = Pole valitud
	AdvOption                       = Valikulised funktsioonid
	ExcludeItem                     = Välista reegli järgi
	DeDuplication                   = Välista duplikaadid
	DeDuplication_Unlock            = Avage keelatud duplikaadid
	Existed                         = Juba olemas
	FailedCreateFolder              = Kataloogi loomine ebaõnnestus
	FailedCreateFile                = Faili loomine ebaõnnestus
	ToMsg                           = {0} Naaske sekundite pärast automaatselt peamenüüsse.
	OnDemandPlanTask                = Teadaolevate sündmuste kohandatud määramine
	Operable                        = Kasutatav
	Inoperable                      = Kasutuskõlbmatu
	Hide                            = Peita
	CuringUpdate                    = Kindel värskendus
	CuringUpdateTips                = Kui värskendus on kinnitatud, ei saa seda desinstallida.
	Healthy                         = Terved
	Healthy_Save                    = Kui ilmub parandatav või parandamatu, ärge salvestage.
	Repair                          = Remont
	IsAuto_Repair                   = Lubage tühikäigul automaatset remonti
	IsAuto_Repair_Tips              = Kontrollige pärast pakkimisskripti iga käitamist automaatselt, kas on installimisülesandeid. Kui see on paigaldatud, siis remonti ei tehta, kui see pole paigaldatud, käivitatakse automaatne remont.
	Repairable                      = Parandatav
	NonRepairable                   = Pole parandatav
	HealthyForceStop                = Sündmuse töötlemisel ilmnes pöördumatu viga ja protsess peatati sunniviisiliselt.\n\n   Põhjustab peamisi probleeme: \n\n      1. Füüsiline riistvara on kahjustatud, kõvaketas;\n\n      2. Kui kasutate RAMDISK mälu virtuaalset ketast (sh hübriid), kontrollige füüsilist mälu;\n\n      3. Kontrollige MVS-i (MSDN) algset SHA256-d. Kui see on järjepidev, muutke kataloogi ja proovige uuesti.\n\n      4. Selles näites teisi ei ole loetletud.
	Superseded                      = Puhastage asendatud
	SupersededTips                  = Sisaldab aegunud värskendusi, komponente jne.
	UnmountFailed                   = Olen proovinud mitut meetodit, kuid midagi ei saa teha, ma tahan teid järgmisel korral näha.
	SaveTo                          = Salvestada
	WorkDone                        = Lõpetatud, vajutage põhiliidesele naasmiseks suvalist klahvi...
	UserCanel                       = Kasutaja on taotluse tühistanud.
	Uping                           = Tekitamine
	Exclude_View                    = Vaadake välistamisreegleid
	User_Interaction                = Kasutaja interaktsioon
	Ok_Go_To                        = Saadaval kuni
	Ok_Go_To_No                     = Ei lähe

	Detailed                        = Üksikasjalik
	View                            = Vaade
	Detailed_View                   = Vaadake valitud reegli üksikasju

	AddEnv                          = Lisage süsteemimuutujatele marsruutimisfunktsioonid
	AddEnvTips                      = Pärast lisamist sisestage vastamiseks mis tahes PowerShelli seansis Yi. Näiteks sisestage kapseldamise käivitamiseks "Yi -SIP".

	Unzip_ISO                       = ISO väljavõte
	Unzip_Search_Type               = Otsi kataloogist ( {0} )
	ISO_Other                       = Muud dokumendid
	Unzip_Language                  = Keelepakett
	Unzip_Fod                       = Funktsioonide pakett
	FileName                        = Faili nimi

	UserCancel                      = Kasutaja on toimingu tühistanud.
	MatchMode                       = Vaste
	Failed                          = Ebaõnnestuda
	RandomSelect                    = Juhuslikult valitud
	RulePre                         = Eelseadistatud reeglid
	RuleOther                       = Muud reeglid
	RuleCustomize                   = Kohandatud reeglid
	RuleCustomize_Dont              = Ärge kasutage mitmetasandilise kataloogi kohandatud reegleid
	RuleCustomize_Dont_Tips         = Pärast vana kataloogi kustutamist klõpsake nuppu "Kinnita nimereeglid".
	RuleMultistage                  = Mitmetasandilised kataloogireeglid
	RuleMultistageFindFailed        = Mitmetasandilisi kataloogireegleid ei leitud. Malli loomiseks klõpsake mind.
	RuleMultistageFindCreateNew     = Looge uus mitmetasandiline kataloogireegli mall
	RuleMultistageTips              = Kohandage automaatselt mitmetasandilisi kataloogireegleid, {0} kataloogireegel on keelatud.
	RuleCustomizeNot                = Laienduse nime (Solutions.Custom.Extension) ei leitud, vaadake abidokumentatsiooni.
	RuleCustomizeTips               = Kohandatud reeglit pole loodud, vaadake abidokumentatsiooni.
	RuleMatchNoFindFolder           = Kataloogi vastendamine ebaõnnestus, kataloogi loomiseks klõpsake mind.
	RuleNoFindFile                  = Saadaolevaid faile ei leitud, lisage ja värskendage.
	RuleFindFolder                  = Kataloog valitakse automaatselt, kui see on saadaval
	RuleNameNewChange               = Pärast värskendusi sünkroonitakse automaatselt
	RuleNewTempate                  = Loo mall
	RuleSkipFolderCheck             = Ei kontrolli enam, kas fail on kataloogis olemas ja failitüüpi
	RuleAuthon                      = Reegli looja
	RuleGUID                        = GUID globaalne kordumatu identifikaator
	RuleName                        = Reegli nimi
	RuleDescription                 = Kirjeldada
	RuleNameUse                     = Sünkrooni reegli nimi: {0}
	RuleISO                         = Sobitage originaal ISO installipakett
	RuleInBoxApps                   = Täielik, eelkonfigureeritud rakendus
	RuleFileType                    = Paketi nimi
	RuleFileFind                    = Ähmane otsingunimi
	RuleFindError                   = Leiti {0} üksust, mida töödelda, üksikasjade vaatamiseks klõpsake nuppu "Kontrolli sõltuvusi".
	RuleSelectApps                  = Kasutaja valitud rakendused
	DependencyPackage               = Sõltuvuspakett
	RuleDependenciesRequired        = Nõutavad sõltuvused
	RuleDependenciesUnselected      = Valimata sõltuvused
	RuleDependenciesNoCheck         = Sõltuvusi enam ei kontrollita
	RuleDependenciesFix             = Valimata sõltuvuste parandamine
	Extract_Tips                    = Vihje\n\n   1. Tulemust pärast keelepaketi väljavõtmist ei saa kasutada peamise viiteobjektina;\n\n   2. Kasutage peamise viiteobjektina komponentide loendit Kuidas luua:\n\n       Valige loodud komponent (hankige installitud pildil pakett) jaotises Functions, valige koheselt printimine või vaatamine;\n\n   3. Pärast keelepaketi installimist looge uuesti komponendi aruanne, et kontrollida, kas see vastab;

	DescendingRuleLang              = Eemaldage keelepaketid vastupidises järjekorras
	OrderRuleLang                   = Installige keelepaketid etteantud järjekorras
	OrderRuleLangTips               = Lisage järjekorras: põhi, Fondid, optiline märgituvastus, käekirjatuvastus, kõneks muutmine, kõnetuvastus, jaemüügi demo kogemus, muu
	RuleLanguageTips                = Illustreerima: \n\n   Pärast funktsiooni "Installi keelepaketid eelreeglistatud järjekorras kasutamist vastendatakse failid automaatselt ebaselgete nimedega järgmises järjekorras. \n
	Match_installed_List            = Keelepaketi installimisel lisage installiloendisse metamärk
	Match_installed_List_Tips       = Sobib ainult installimisel: põhiline, optiline märgituvastus, käekirjatuvastus, kõneks muutmine, kõnetuvastus.
	RuleLanguageTipsExt             = \n   Kui te ei kasuta valikut "Installi keelepaketid eelreeglistatud järjekorras": \n   Otsige automaatselt kõigist kataloogi failidest failitüübi järgi ja installige need.\n\n   Keele ja piirkonna nõudmisel funktsioonid (FOD)\n   https://learn.microsoft.com/et-ee/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategooria
	Basic                           = Põhilised
	Fonts                           = Font
	OCR                             = Optiline märgituvastus
	Handwriting                     = Käekirjatuvastus
	TextToSpeech                    = Tekst kõneks
	Speech                          = Kõnetuvastus
	Retail                          = Jaemüügi demo kogemus
	Features_On_Demand              = Funktsioonid nõudmisel
	RegionSpecific                  = Muud piirkonnapõhised nõuded
	UnassignedLangFiles             = Määramata mitmesugused failid

	ProcessingImage                 = Töötle pilti:
	NoInstallImage                  = Lokaalselt ei eksisteeri
	ConvertChk                      = Kontrolli faili
	WindowsFeature                  = Windowsi funktsioonid
	Enable                          = Lubada
	Disable                         = Keela
	EnableFeatureTips               = Vihje\n\n    1. Kuva NetFx3 ja TelnetClient eelseadistatud lubatud funktsiooniüksustena;\n\n    2. Pärast "monteerimist" saab rohkem lubada.
	ViewLanguage                    = Kuva pildi keeleseaded
	ImageLanguage                   = Pildi keele seaded
	OnlyLangCleanup                 = Puhtad komponendid: sildi keele järgi
	Matched_Component_Names         = Sobiva komponendi nimi:
	BootProcess                     = Faili {0}.wim töötlemisel
	Sync_Language_To                = Sünkrooni
	BootSyncToISO                   = Sünkroonige keelepaketid installiprogrammiga
	BootSyncToISOTips               = Võrguühenduseta pildi installitud keelepakett sünkroonitakse ISO installijaga.
	LangIni                         = Taastage Lang.ini
	LangIniTips                     = Pärast sünkroonimise lõpetamist tuleb ISO-s Lang.ini uuesti üles ehitada.
	LangNewAutoSelect               = Valige sündmuse toimumisel automaatselt soovitatud üksused
	LangNewAutoSelectTips           = On uusi sündmusi, "Sünkrooni keelepaketid installijaga", "Ehita uuesti Lang.ini".
	LangNewAutoNoSelect             = On uusi sündmusi, soovitatav on valida "Sünkrooni keelepakett installijaga" ja "Ehita uuesti Lang.ini".
	LangNewAutoNoNewSelect          = Uusi sündmusi pole. Soovitatav on mitte valida "Sünkrooni keelepakett installijaga" ja "Lang.ini uuesti koostamine".
	Drive                           = Sõita
	ViewDrive                       = Vaadake installitud draivereid
	Editions                        = Pildi versioon
	Assign_Editions                 = Rakenduste automaatne levitamine pildiversioonide põhjal

	SelFile                         = Valige fail
	Rebuilding                      = Rekonstrueerimisel
	RebuildAll                      = Ehitage kõik uuesti
	Export_Image                    = Ekspordi
	SelectFromError                 = Viga
	SelectFileFormatError           = Failivorming on vale

	SearchDrive                     = Otsinguga juhitud
	SearchUpdate                    = Otsi värskendusi, tüüp ( {0} ), allikas:
	SelectFolder                    = Valige kataloog
	DropFolder                      = Saab lohistada katalooge praegusesse aknasse
	DropFile                        = Faile saab lohistada praegusesse aknasse
	Sparse                          = Harv
	CRCSHA                          = Kontrollige
	Alternative                     = Alternatiivne failinimi
	ChangeInstallDisk               = Muutke automaatset kettavalikut
	Backup                          = Varundamine
	Restore                         = Taasta
	Import                          = Importida

	# View
	ExportToLogs                    = Printige logimiseks aruanne
	ExportShow                      = Kuva aruanded koheselt
	MoreFeature                     = Rohkem funktsioone
	OpenFolder                      = Ava kataloog
	OpenFile                        = Ava fail
	Running                         = Jooksma
	Paste                           = Kopeeri tee
	Clipboard_Copy                  = Kopeeriti lõikelauale
	ViewWIMFileInfo                 = Vaata pilti
	GetInBoxApps                    = Inboxi rakendused: installitud rakenduste paketid
	GetImagePackage                 = Komponendid: kõik pildile installitud paketid
	ViewMounted                     = Hankige teavet kõigi paigaldatud piltide kohta
'@