ConvertFrom-StringData -StringData @'
	# pt-PT
	# Portuguese (Portugal)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Painel
	Learn                           = Estudar
	Menu                            = Menu
	Short_Cmd                       = Comando de atalho
	Shortcut                        = Atalho
	Update                          = Renovar
	CUpdate                         = Atualizações cumulativas
	Rebuild                         = Reconstrução
	AddTo                           = Adicionar à
	Del                             = Excluir
	Copy                            = Cópia
	Rename                          = Renomear
	Refresh                         = Atualizar
	RefreshModules                  = Atualização a quente de todos os módulos
	Done                            = Terminar
	OK                              = Claro
	Cancel                          = Cancelar
	AllSel                          = Selecionar tudo
	AllClear                        = Limpar tudo
	Setting                         = Configurar
	Change                          = Mudar
	Help                            = Ajuda
	Logging                         = Guardar registo em
	AvailableLanguages              = Idiomas disponíveis
	SwitchLanguage                  = Mudar de idioma
	LanguageSelRegion               = Selecione o seu país ou região
	LanguageRemember                = Lembrar o idioma selecionado
	LanguageSearchNo                = Nenhum idioma disponível encontrado
	LanguageNoPack                  = Se não existir nenhum pacote de idioma localmente, será automaticamente terminado.
	LanguageNoSel                   = Selecione uma região
	Search                          = Procurar
	PleaseChoose                    = Selecione
	Options                         = Opções
	Choose                          = Selecionado
	NoChoose                        = Não selecionado
	AdvOption                       = Recursos opcionais
	ExcludeItem                     = Eliminar por regra
	DeDuplication                   = Apagar duplicatas
	DeDuplication_Unlock            = Desbloquear duplicados desativados
	Existed                         = Já existe
	FailedCreateFolder              = Falha ao criar diretório
	FailedCreateFile                = Falha ao criar ficheiro
	ToMsg                           = {0} Regresse automaticamente ao menu principal após segundos.
	OnDemandPlanTask                = Atribuição personalizada de eventos conhecidos
	Operable                        = Operável
	Inoperable                      = Inoperável
	Hide                            = Esconder
	CuringUpdate                    = Atualização sólida
	CuringUpdateTips                = Assim que a atualização for solidificada, não poderá ser desinstalada.
	Healthy                         = Saudável
	HealthyTips                     = É particularmente importante verificar o estado de saúde Quando aparece "reparável" ou "irreparável": Durante o processo de conversão ESD, é solicitado o erro 13 e os dados são inválidos, é reportado um erro durante a instalação do sistema;
	Healthy_Save                    = Quando aparecer reparável ou irreparável, não guarde.
	Repair                          = Reparar
	IsAuto_Repair                   = Permitir reparação automática quando ocioso
	IsAuto_Repair_Tips              = Verifique automaticamente se existe alguma tarefa de montagem após cada execução do script de empacotamento. Se estiver montado, não será realizado qualquer reparo;
	Repairable                      = Reparável
	NonRepairable                   = Não reparável
	HealthyForceStop                = Durante o processamento do evento, foi encontrado um erro irreversível e o evento foi terminado à força.\n\n   Causa os principais problemas: \n\n      1. O hardware físico está danificado, disco rígido;\n\n      2.Se utilizar disco virtual de memória RAMDISK (incluindo híbrido), verifique a memória física;\n\n      3. Verifique o SHA256 original do MVS (MSDN).\n\n      4. Outros não estão listados neste exemplo.
	Superseded                      = Limpe o substituído
	SupersededTips                  = Inclui atualizações desatualizadas, componentes, etc.
	UnmountFailed                   = Já tentei vários métodos, mas nada pode ser feito, só posso desistir.
	SaveTo                          = Guardar em
	WorkDone                        = Concluído, prima qualquer tecla para voltar à interface principal...
	UserCanel                       = O utilizador cancelou a solicitação.
	Uping                           = Gerando
	Exclude_View                    = Ver regras de exclusão
	User_Interaction                = Interação do utilizador
	Ok_Go_To                        = Disponível para
	Ok_Go_To_No                     = Não vou

	Detailed                        = Detalhado
	Detailed_View                   = Ver detalhes da regra selecionada

	AddEnv                          = Adicione a funcionalidade de encaminhamento às variáveis do sistema
	AddEnvTips                      = Após adicionar, introduza Yi em qualquer sessão PowerShell para responder. Por exemplo, introduza "Yi -SIP" para executar o encapsulamento.

	Unzip_ISO                       = Extrair ISO
	Unzip_Search_Type               = Diretório de pesquisa ( {0} )
	ISO_Other                       = Outros documentos
	Unzip_Language                  = Pacote de idiomas
	Unzip_Fod                       = Pacote de recursos
	FileName                        = Nome do ficheiro

	UserCancel                      = O utilizador cancelou a operação.
	MatchMode                       = Corresponder
	Failed                          = Falhar
	RandomSelect                    = Selecionado aleatoriamente
	RulePre                         = Regras predefinidas
	RuleOther                       = Outras regras
	RuleCustomize                   = Regras personalizadas
	RuleCustomize_Dont              = Não utilize regras personalizadas de diretório multinível
	RuleCustomize_Dont_Tips         = Após eliminar o diretório antigo, clique em "Verificar regras de nomenclatura".
	RuleMultistage                  = Regras de diretório multinível
	RuleMultistageFindFailed        = Nenhuma regra de diretório multinível encontrada.
	RuleMultistageFindCreateNew     = Crie um novo modelo de regra de diretório multinível
	RuleMultistageTips              = Adaptar automaticamente as regras de diretório multinível, a regra de diretório {0} foi desativada.
	RuleCustomizeNot                = Nome da extensão (Solutions.Custom.Extension) não encontrado, consulte a documentação de ajuda.
	RuleCustomizeTips               = Não foi criada nenhuma regra personalizada.
	RuleMatchNoFindFolder           = Falha ao corresponder ao diretório, clique em mim para criar o diretório.
	RuleNoFindFile                  = Nenhum ficheiro disponível encontrado.
	RuleFindFolder                  = Diretório selecionado automaticamente quando disponível
	RuleNameNewChange               = Sincronizar automaticamente após atualizações
	RuleNewTempate                  = Criar modelo
	RuleSkipFolderCheck             = Já não verifica se o ficheiro existe no diretório e no tipo de ficheiro
	RuleAuthon                      = Criador de regras
	RuleGUID                        = GUID identificador globalmente único
	RuleName                        = Nome da regra
	RuleDescription                 = Descrever
	RuleNameUse                     = Nome da regra de sincronização para: {0}
	RuleISO                         = Combine o pacote de instalação ISO original
	RuleInBoxApps                   = Aplicação completa e pré-configurado
	RuleFileType                    = Nome do pacote
	RuleFileFind                    = Nome de pesquisa difuso
	RuleFindError                   = Encontrados {0} itens a processar, clique em "Verificar dependências" para ver os detalhes.
	RuleSelectApps                  = Aplicações selecionadas pelo usuário
	DependencyPackage               = Pacote de dependências
	RuleDependenciesRequired        = Dependências necessárias
	RuleDependenciesUnselected      = Dependências não selecionadas
	RuleDependenciesNoCheck         = As dependências já não são verificadas
	RuleDependenciesFix             = Corrigir dependências não selecionadas
	Extract_Tips                    = Dica\n\n   1. O resultado após a extração do pacote de idioma não pode ser utilizado como objeto de referência principal;\n\n   2. Utilize a lista de componentes como objeto de referência principal.\n\n       Em Funções, selecione Gerar Componente (obter o pacote na imagem instalada), selecione Imprimir ou Visualizar Instantaneamente;\n\n   3. Após instalar o pacote de idioma, gere novamente um relatório do componente para verificar se é correspondente;

	DescendingRuleLang              = Remova os pacotes de idiomas pela ordem inversa
	OrderRuleLang                   = Instale os pacotes de idiomas em ordem pré-regulada
	OrderRuleLangTips               = Adicionar por ordem: Básico, Fontes, Reconhecimento Óptico de Caracteres, Reconhecimento de Caligrafia, Conversão de Texto para Fala, Reconhecimento de Fala, Experiência de Demonstração de Retalho, Outros
	RuleLanguageTips                = Ilustrar:\n\n   Depois de utilizar "Instalar pacotes de idiomas numa ordem pré-regulada", os ficheiros são automaticamente correspondidos por nomes difusos na seguinte ordem:\n
	Match_installed_List            = Ao instalar um pacote de idiomas, coloque-o como um curinga na lista de instalados
	Match_installed_List_Tips       = Corresponde apenas quando instalado: Básico, Reconhecimento Óptico de Caracteres, Reconhecimento de Manuscrito, Conversão de Texto para Fala, Reconhecimento de Fala.
	RuleLanguageTipsExt             = \n   Quando não estiver a utilizar "Instalar pacotes de idiomas em ordem pré-regulada":\n   Pesquise automaticamente todos os ficheiros no diretório por tipo de ficheiro e instale-os.\n\n   Recursos on-demand de idioma e região (FOD)\n   https://learn.microsoft.com/pt-pt/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Categoria
	Basic                           = Básico
	Fonts                           = Fonte
	OCR                             = Reconhecimento óptico de caracteres
	Handwriting                     = Reconhecimento de escrita
	TextToSpeech                    = Texto para fala
	Speech                          = Reconhecimento de fala
	Retail                          = Experiência de demonstração de retalho
	Features_On_Demand              = Recursos sob demanda
	RegionSpecific                  = Outros requisitos específicos da região
	UnassignedLangFiles             = Ficheiros diversos não atribuídos

	ProcessingImage                 = Processe a imagem:
	NoInstallImage                  = Não existe localmente
	ConvertChk                      = Verifique o ficheiro
	WindowsFeature                  = Recursos do Windows
	Enable                          = Habilitar
	Disable                         = Desativar
	EnableFeatureTips               = Dica\n\n    1. Visualizar NetFx3 e TelnetClient como itens de função pré-definidos;\n\n    2. Após a "montagem", mais podem ser activados.
	ViewLanguage                    = Ver definições de idioma da imagem
	ImageLanguage                   = Definições de idioma da imagem
	OnlyLangCleanup                 = Componentes limpos: etiqueta por idioma
	Matched_Component_Names         = Nome do componente correspondente:
	BootProcess                     = Ao processar {0}.wim
	Extract_Rule_Only_And_Full      = Extraia apenas os idiomas selecionados
	Sync_Language_To                = Sincronizar com
	BootSyncToISO                   = Sincronize os pacotes de idioma com o instalador
	BootSyncToISOTips               = O pacote de idioma instalado a partir da imagem offline é sincronizado com o instalador ISO.
	Setup_Fix_Missing               = Corrija automaticamente os itens em falta do instalador
	Setup_Fix_Missing_Tips          = Se o programa de instalação estiver em falta arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui, abra "Extrair", seleccione "Regras" e clique em "Extrair itens em falta do instalador".
	Setup_Fix_Missing_Extract       = Extraia os itens em falta do instalador
	Setup_Fix_Missing_Extract_Tips  = Extraia os itens em falta do instalador de todos os pacotes de idiomas locais: arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui.
	LangIni                         = Regenerar Lang.ini
	LangIniTips                     = Após a sincronização estar concluída, o Lang. ini no ISO necessita de ser reconstruído.
	LangNewAutoSelect               = Selecionar automaticamente os itens sugeridos quando ocorre um evento
	LangNewAutoSelectTips           = Existem novos eventos, "Sincronizar pacote de idioma com o instalador", "Reconstruir Lang.ini" seleccionados.
	LangNewAutoNoSelect             = Existem novos eventos, é recomendado que selecione "Sincronizar pacote de idiomas com o instalador" e "Reconstruir Lang.ini".
	LangNewAutoNoNewSelect          = Não existem novos eventos. É recomendável não selecionar "Sincronizar pacote de idioma com o instalador" ou "Reconstruir Lang.ini".
	Drive                           = Conduzir
	ViewDrive                       = Ver drivers instalados
	EditionsProductKey              = Chave do produto
	Editions                        = Versão da imagem
	Assign_Editions                 = Distribuir aplicações automaticamente com base em versões de imagem
	EditionsChangeTips              = Aviso, por favor entenda antes de mudar de versão de imagem: \n\nMicrosoft Contrato de prestação de serviços\nhttps://www.microsoft.com/pt-pt/servicesagreement/default.aspx\n\nVisão geral do idioma\nhttps://learn.microsoft.com/pt-pt/windows-hardware/manufacture/desktop/languages-overview\n\nNão tem permissão para fazer versões de: \n   1. Específico do país\n       ProfessionalCountrySpecific\n\n   2. Versão inicial específica da região\n       ProfessionalSingleLanguage\n\nPor favor, cumpra rigorosamente, pois pode estar sujeito a um processo se violado.\n\nSe insistir em converter, clique para aceitar o aviso e clique em "Desbloquear versão da imagem oculta".
	EditionsChangeHide              = Desbloqueie versões de imagens ocultas
	EditionsChangeAccect            = Li o aviso e sou responsável pelas leis relevantes contidas no aviso

	SelFile                         = Selecione o ficheiro
	Rebuilding                      = Em reconstrução
	RebuildAll                      = Reconstruir tudo
	Export_Image                    = Exportar
	SelectFromError                 = Erro
	SelectFileFormatError           = O formato do ficheiro está incorreto

	SearchDrive                     = Orientado por pesquisa
	SearchUpdate                    = Atualizações de investigação, tipo ( {0} ), fonte:
	SelectFolder                    = Selecione o diretório
	DropFolder                      = Pode arrastar diretórios para a janela atual
	DropFile                        = Os ficheiros podem ser arrastados para a janela atual
	Sparse                          = Cru
	CRCSHA                          = Verificar
	Alternative                     = Nome de ficheiro alternativo
	ChangeInstallDisk               = Alterar a seleção automática de disco

	# View
	ExportToLogs                    = Imprimir relatório para registar
	ExportShow                      = Exibir relatórios instantaneamente
	MoreFeature                     = Mais recursos
	OpenFolder                      = Abrir diretório
	OpenFile                        = Abrir ficheiro
	Running                         = Correr
	Paste                           = Copiar caminho
	Clipboard_Copy                  = Copiado para a área de transferência
	ViewWIMFileInfo                 = Ver imagem
	GetInBoxApps                    = InBox Apps: pacotes de aplicações instalados
	GetImagePackage                 = Componentes: Todos os pacotes instalados na imagem
	ViewMounted                     = Obtenha informações sobre todas as imagens montadas
'@