ConvertFrom-StringData -StringData @'
	# zh-CN
	# Chinese (Simplified, China)

	FontsUI                   = Microsoft YaHei UI
	Mainname                  = 部署引擎：Yi's 套件
	Learn                     = 学习
	MainHisName               = 附赠解决方案
	Location                  = 打开所在位置
	About                     = 关于
	Reset                     = 重置
	AddTo                     = 添加
	Instl                     = 安装
	ItInstalled               = 已安装
	Close                     = 关闭
	Auto                      = 自动
	Disable                   = 禁用
	Enable                    = 启用
	Setting                   = 设置
	Restore                   = 恢复
	Clean                     = 清理
	Operable                  = 可操作
	Inoperable                = 不可操作
	Optimize                  = 优化
	Hide                      = 隐藏
	Show                      = 显示
	Del                       = 删除
	Done                      = 完成
	OK                        = 确定
	Cancel                    = 取消
	AllSel                    = 选择所有
	AllClear                  = 清除所有
	Refresh                   = 刷新
	RefreshModules            = 热刷新所有模块
	Necessary                 = 必备软件
	MostUsedSoftware          = 常用软件
	System                    = 系统
	Service                   = 服务
	TaskBar                   = 任务栏所有图标
	DeskIcon                  = 桌面图标
	InstallFonts              = 安装字体
	SettingTo                 = 设置为 {0}
	Command                   = 命令行
	RuleName                  = 规则名称
	Language                  = 语言
	AvailableLanguages        = 可用语言
	SwitchLanguage            = 切换语言
	LanguageReset             = 重置语言设置
	LanguageCode              = 区域标记
	LanguageSelRegion         = 选择您的国家或地区
	LanguageRemember          = 记住所选语言
	LanguageSearchNo          = 未搜索到可用的语言
	LanguageNoSel             = 请选择区域
	Search                    = 搜索
	PleaseChoose              = 请选择
	FailedCreateFolder        = 创建目录失败
	Failed                    = 失败
	ToMsg                     = {0} 秒后自动返回到主菜单。
	Restart                   = 重启生效
	AdvOption                 = 可选功能

	StartDown                 = 开始下载
	ConnectTo                 = 连接到
	FileName                  = 文件名
	SaveTo                    = 保存到
	NotAvailable              = 状态：不可用
	ExistingPacker            = 已有安装包
	ExistingInstlPacker       = 已有压缩包
	Unpacking                 = 解压中
	QucikRun                  = 快速运行：
	WaitDone                  = 等待完成：
	Parameter                 = 参数：
	ErrorDown                 = 下载过程中出现错误
	UserCancel                = 用户已取消操作。

	VerifyNameTips            = 只允许英文字母和数字组合，不能包含其它字符：空格、长度不能大于 16 字符、\\ / : * ? & @ ! "" < > |
	FolderLabel               = 自定义目录前缀
	NoSetFolderLabel          = 自定义目录前缀未设置
	ISO9660TipsErrorSpace     = 不能包含：前后空格
	ISO9660TipsErrorOther     = 不能包含：\\ / : * ? & @ ! "" < > |
	ISOLengthError            = 卷标长度不能大于 {0} 字符
	Help                      = 帮助
	WorkDone                  = 完成，按任意键返回主界面...
	Short_Cmd                 = 快捷指令
	Options                   = 選項
	LXPsWaitAssign            = 待分配
	Running                   = 运行
	SpecialFunction           = PowerShell 函数
'@