ConvertFrom-StringData -StringData @'
	# ja-JP
	# Japanese (Japan)

	IsCreate                        = 作成
	Solution                        = 解決
	EnabledSoftwarePacker           = コレクション
	EnabledUnattend                 = 事前に答えるべき
	EnabledEnglish                  = デプロイメントエンジン
	UnattendSelectVer               = 「回答回答」ソリューション言語を選択します
	UnattendLangPack                = 「ソリューション」言語パックを選択します
	UnattendSelectSingleInstl       = 多言語, インストール時にオプション
	UnattendSelectMulti             = 多言語
	UnattendSelectDisk              = Autounattend.xml ソリューションを選択します
	UnattendSelectSemi              = すべてのインストール方法で半自動有効
	UnattendSelectUefi              = UEFI 自動インストール, 指定する必要があります
	UnattendSelectLegacy            = Legacy 自動インストール, 指定する必要があります
	NeedSpecified                   = 指定する必要があるものを選択してください：
	OOBESetupOS                     = インストールインターフェイス
	OOBEProductKey                  = プロダクトキー
	OOBEOSImage                     = インストールするオペレーティングシステムを選択します
	OOBEEula                        = ライセンス条項に同意する
	OOBEDoNotServerManager          = ログイン時にサーバーマネージャーを自動的に起動しない
	OOBEIE                          = Internet Explorer のセキュリティ強化の構成
	OOBEIEAdmin                     = 「管理者」を閉じる
	OObeIEUser                      = 「ユーザー」を閉じる

	OOBE_Init_User                  = 開梱時の最初のユーザー
	OOBE_init_Create                = カスタム ユーザーを作成する
	OOBE_init_Specified             = 指定されたユーザー
	OOBE_Init_Autologin             = 自動ログイン

	InstlMode                       = 設置方法
	Business                        = 商用バージョン
	BusinessTips                    = EI.cfg によっては, 自動インストールでインデックス番号を指定する必要があります。
	Consumer                        = コンシューマーエディション
	ConsumerTips                    = EI.cfg に依存せず, 自動インストールの場合はシリアル番号を指定する必要があり, バージョン選択インターフェイスを一時停止する場合はインデックス番号を指定する必要があります。
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [にマウントする]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = システムディスクのホームディレクトリ名に追加
	VerifyNameUse                   = ディレクトリ名に次を含めることができないことを確認します
	VerifyNameTips                  = 英字と数字の組み合わせのみが許可され, 以下を含めることはできません: スペース, 長さは 260 文字を超えることはできません, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = 認証に失敗しました。正しい番号を入力してください。
	VerifyNameSync                  = ディレクトリ名をプライマリ ユーザー名に設定します
	VerifyNameSyncTips              = administrator は使用されなくなりました。
	ManualKey                       = プロダクト キーを選択または手動で入力します
	ManualKeyTips                   = 有効なプロダクト キーを入力し, 選択した地域はマイクロソフトの公式チェックに進みませんでした。
	ManualKeyError                  = 入力したプロダクト キーが無効です。
	KMSLink1                        = KMS クライアントはキーを設定します
	KMSUnlock                       = 既知のすべての KMS シリアル番号を表示します
	KMSSelect                       = VOL シリアル番号を選択してください
	KMSKey                          = シリアル番号
	KMSKeySelect                    = 製品のシリアル番号を変更します
	ClearOld                        = 古いファイルをクリーンアップします
	SolutionsSkip                   = ソリューションの作成をスキップします
	SolutionsTo                     = ソリューションを追加します：
	SolutionsToMount                = マウントされているか, キューに追加されています
	SolutionsToError                = 一部の機能が無効になっている場合は, [ロック解除] ボタンをクリックします。\n\n
	UnlockBoot                      = ロックを解除します
	SolutionsToSources              = ホームディレクトリ,[ISO]:\\Sources\\$OEM$
	SolutionsScript                 = [デプロイ エンジン] バージョンを選択します
	SolutionsEngineRegionaUTF8      = ベータ版: Unicode UTF-8 を使用したグローバル言語サポート
	SolutionsEngineRegionaUTF8Tips  = 開くと, 新しい問題を引き起こす可能性があるかのように開きます。 推奨されません。
	SolutionsEngineRegionaling      = 新しいロケールに変更します：
	SolutionsEngineRegionalingTips  = システム ロケールを変更すると, コンピュータ上のすべてのユーザー アカウントに影響します。
	SolutionsEngineRegional         = システム ロケールを変更します
	SolutionsEngineRegionalTips     = グローバルデフォルト: {0}, 変更: {1}
	SolutionsEngineCopyPublic       = パブリック {0} を展開にコピーします
	SolutionsEngineCopyOpen         = パブリック ストレージ {0} 場所を参照します
	EnglineDoneReboot               = コンピュータを再起動します
	SolutionsTipsArm64              = 好ましい arm64 パッケージは, 順に選択されます: x64, x86.
	SolutionsTipsAMD64              = x64 パッケージを優先し, 順に選択します: x86。
	SolutionsTipsX86                = x86 パッケージのみを追加します。
	SolutionsReport                 = 展開前のレポートを生成します
	SolutionsDeployOfficeInstall    = Microsoft Office インストール パッケージを展開します
	SolutionsDeployOfficeChange     = 配置構成を変更します
	SolutionsDeployOfficePre        = パッケージのバージョンをプレインストールします
	SolutionsDeployOfficeNoSelect   = Office プレインストール パッケージが選択されていません
	SolutionsDeployOfficeVersion    = {0} バージョン
	SolutionsDeployOfficeOnly       = 指定した言語パックを保持します
	SolutionsDeployOfficeSync       = 指定した言語パックを保持します
	SolutionsDeployOfficeSyncTips   = 同期後, インストール スクリプトは優先言語を判断できません。
	DeploySyncMainLanguage          = 同期はプライマリ言語と一致します
	SolutionsDeployOfficeTo         = インストール パッケージを展開します
	SolutionsDeployOfficeToPublic   = パブリック デスクトップ
	DeployPackage                   = カスタム コレクション パッケージを展開します
	DeployPackageSelect             = プリフィット セット パッケージを選択します
	DeployPackageTo                 = プリアンパック パッケージを展開します
	DeployToRoot                    = システム ディスク
	DeployPackageToSolutions        = ソリューションのホーム ディレクトリの下
	DeployTimeZone                  = 時間領域
	DeployTimeZoneChange            = 時間領域を変更します
	DeployTimeZoneChangeTips        = 言語ゾーン別に, 事前回答する既定の時間領域を設定します。

	Deploy_Tags                     = デプロイメントタグ
	FirstExpProcess                 = 最初のエクスペリエンス, 展開の前提条件プロセス:
	FirstExpProcessTips             = 前提条件が完了したら, コンピュータを再起動して, 再起動が有効になる必要がある問題を解決します。
	FirstExpFinish                  = 前提条件を完了した後の初めてのエクスペリエンス
	FirstExpSyncMark                = 展開タグを完全に検索して同期できます
	FirstExpDefender                = ホーム ディレクトリを Defend 除外ディレクトリに追加します
	FirstExpSyncLabel               = システム・ディスク・ボリューム・ラベル: ホーム・ディレクトリー名は同じです
	MultipleLanguages               = 複数の言語に遭遇した場合:
	NetworkLocationWizard           = ネットワークロケーションウィザード
	PreAppxCleanup                  = Appx によるメンテナンス タスクのクリーンアップを防止する
	LanguageComponents              = 未使用のフィーチャーオンデマンド言語パックのクリーンアップを防止する
	PreventCleaningUnusedLP         = 未使用の言語パックのクリーニングを防止する
	FirstExpContextCustomize        = パーソナライズされたコンテキストメニューを追加する
	FirstExpContextCustomizeShift   = Shift キーを押しながら右クリックします

	FirstExpFinishTips              = 展開が完了した後に重要なイベントがない場合は, キャンセルすることをお勧めします。
	FirstExpFinishPopup             = デプロイエンジンのメインインターフェイスをポップします
	FirstExpFinishOnDemand          = スケジュールに従って, 最初の事前エクスペリエンスを許可します
	SolutionsEngineRestricted       = Powershell 実行ポリシーの復元: 制限
	EnglineDoneClearFull            = ソリューション全体を削除します
	EnglineDoneClear                = デプロイ エンジンを削除し, 他のエンジンを保持します

	Unattend_Auto_Fix_Next          = 前提条件が選択されている場合, 次回その前提条件が発生したときに自動修正する
	Unattend_Auto_Fix               = 前提条件が選択されていない場合の自動修復
	Unattend_Auto_Fix_Tips          = デプロイ エンジンを追加するときに最初の実行コマンドが選択されていない場合は, 自動的に修復されて選択されます。 Powershell 実行戦略: デプロイ エンジンを制限なしで実行します。
	Unattend_Version_Tips           = のみを含めるように選択でき, デフォルトで ARM64, x64, および x86 をサポートできます。
	First_Run_Commmand              = 最初の展開時に実行するコマンド
	First_Run_Commmand_Setting      = 実行するコマンドを選択してください
	Command_Not_Class               = フィルタリング時に自動分類されなくなりました
	Command_WinSetup                = Windows インストール
	Command_WinPE                   = Windows PE
	Command_Tips                    = 最初の実行の適用先を割り当ててください：Windows インストール, Windows PE\n\nデプロイメント エンジンを追加する場合は, 次の点を確認する必要があることに注意してください。 Powershell 実行ポリシー: 制限付き, 初回実行時にデプロイメント エンジン スクリプトの実行を許可します。
	Waring_Not_Select_Command       = デプロイ エンジンを追加するときに, Powershell 実行ポリシーが選択されていませんでした。制限を設定せず, デプロイ エンジン スクリプトの実行を許可します。選択して再試行するか, [クイック フィックスが選択されていません] をクリックしてください。
	Quic_Fix_Not_Select_Command     = クイックフィックスが選択されていません

	PowerShell_Unrestricted         = Powershell 実行ポリシー: 制限なし
	Allow_Running_Deploy_Engine     = デプロイメントエンジンスクリプトの実行を許可する
'@