ConvertFrom-StringData -StringData @'
	# ro-RO
	# Romanian (Romania)

	UnpackISO                       = Generați ISO
	ISOLabel                        = Eticheta de volum a fost setată:
	ISOCustomize                    = Numele etichetei de volum ISO
	ISO9660                         = Verificați regulile de denumire
	ISO9660Tips                     = Numele unic nu poate depăși 260 de caractere, numele volumului ISO nu poate depăși 16 caractere și nu poate conține: spații de început și de final, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Denumirea unică personalizată
	ISOAddFlagsLang                 = Adăugați un marcaj multilingv
	ISOAddFlagsLangGet              = Obțineți limbi de instalare cunoscute
	ISOAddFlagsVer                  = Adăugați etichetă cu versiuni multiple
	ISOAddFlagsVerGet               = Obțineți versiunea de imagine cunoscută
	ISOAddEICFG                     = Adăugați tipul de versiune
	ISOAddEICFGTips                 = Când te bazezi pe EI.cfg, este o versiune comercială.
	ISO9660TipsErrorSpace           = Nu poate conține: spații de început și de final
	ISO9660TipsErrorOther           = Nu poate conține: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Selectați tipul de limbă
	SelLabel                        = Nume de cod
	ISOVerLabel                     = Selectați numele volumului ISO
	NoSetLabel                      = Eticheta de volum ISO personalizată nu este setată
	ISOLengthError                  = Eticheta de volum nu poate fi mai lungă de {0} caractere
	RenameFailed                    = La fel ca directorul vechi, redenumirea a eșuat
	ISOCreateAfter                  = Ce trebuie să faceți înainte de a crea un ISO
	ISOCreateRear                   = Ce trebuie să faceți după crearea ISO
	BypassTPM                       = Ocoliți verificarea instalării TPM
	Disable_BitLocker               = Dezactivați criptarea dispozitivului BitLocker în timpul instalării
	PublicDate                      = Data emiterii
	PublicDateGetCurrent            = Sincronizați data curentă
	PublicYear                      = An
	PublicMonth                     = Lună
	PublicYMSorting                 = Sortare: Schimbați "lună_an" în "an_lună"
	PublicYMSortingTips             = AB: Nu adăugați sublinierea _ atunci când folosiți numere.
	PublicYMUseShortNames           = Folosiți nume scurte
	PublicYMUseNumbers              = Folosiți numere
	ISOCreateFailed                 = Crearea a eșuat, directorul nu poate fi citit sau scris.
	ISORefreshAuto                  = Actualizează etichetele ISO de fiecare dată
	ISOSaveTo                       = Locația de salvare implicită ISO
	ISOSaveSameGlobal               = Utilizați locația de salvare implicită ISO globală
	ISOSaveSync                     = Sincronizați automat noua locație după selectarea discului de căutare a sursei imaginii
	ISOSaveSame                     = Căutați calea discului folosind sursa imaginii
	ISOFolderWrite                  = Verificați că directorul poate fi citit și scris
	SelectAutoAvailable             = Când selectați automat un disc disponibil
	SelectCheckAvailable            = Verificați spațiul minim disponibil rămas
	ISOStructure                    = Nouă structură de directoare
	ISOOSLevel                      = Adăugați tipul de instalare
	ISOUniqueNameDirectory          = Adăugați un director de nume unic
	NextDoOperate                   = Nu creați ISO
	SelCreateISO                    = Generați ISO, executați la cerere
	Reconstruction                  = Reconstruiți {0}.wim cu compresie maximă
	Reconstruction_Tips_Select      = Înainte de reconstrucție, acesta va fi executat numai când nu este încărcat.
	ReconstructionTips              = Peste 520 MB, reconstruire recomandată
	CreateASC                       = Adăugați semnătura PGP la ISO
	NoPGPKey                        = Nu există o cheie privată utilizabilă în PGP.
	CreateASCPwd                    = Parola certificatului
	PasswordRenter                  = Reintroduceți parola
	ShowPassword                    = Afișați parola
	NewPasswordSome                 = Parola nu se potrivește.
	PwdPermanent                    = Stocare permanentă
	PwdDecfailed                    = Decriptarea a eșuat
	CreateASCAuthor                 = Semnatar
	CreateASCAuthorTips             = Niciun semnatar selectat.
	ISO_Sparse_Rename               = Adăugați hash la extensia numelui fișierului
	GenerateRandom                  = Generați numere aleatorii
	RandomNumberReset               = Regenera
'@