ConvertFrom-StringData -StringData @'
	# en-US
	# English (United States)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Dashboard
	Learn                           = Learn
	Menu                            = Menu
	Short_Cmd                       = Shortcut command
	Shortcut                        = Shortcut
	Update                          = Updates
	CUpdate                         = Cumulative updates
	Rebuild                         = Rebuild
	AddTo                           = Add to
	Del                             = Delete
	Copy                            = Copy
	Rename                          = Rename
	Refresh                         = Refresh
	RefreshModules                  = Hot refresh all modules
	Done                            = Complete
	OK                              = Ok
	Cancel                          = Cancel
	AllSel                          = Select all
	AllClear                        = Clear all
	Setting                         = Settings
	Change                          = Change
	Help                            = Help
	Logging                         = Log
	AvailableLanguages              = Available languages
	SwitchLanguage                  = Switch language
	LanguageSelRegion               = Select your country or region
	LanguageRemember                = Remember the selected language
	LanguageSearchNo                = No available languages found
	LanguageNoPack                  = No local language pack, will exit automatically.
	LanguageNoSel                   = Please select region
	Search                          = Search
	PleaseChoose                    = Please choose
	Options                         = Options
	Choose                          = Chosen
	NoChoose                        = Not selected
	AdvOption                       = Optional function
	ExcludeItem                     = Exclude by rules
	DeDuplication                   = Exclude duplicates
	DeDuplication_Unlock            = Unlock Disabled Duplicates
	Existed                         = Existed
	FailedCreateFolder              = Failed to create directory
	FailedCreateFile                = Failed to create file
	ToMsg                           = Automatically return to the main menu after {0} seconds.
	OnDemandPlanTask                = Custom Assign Known Events
	Operable                        = Operable
	Inoperable                      = Inoperable
	Hide                            = Hide
	CuringUpdate                    = Curing update
	CuringUpdateTips                = After the update has been solidified, it cannot be uninstalled.
	Healthy                         = Healthy
	HealthyTips                     = It is particularly important to check the health status. When "repairable" or "unrepairable" appears: During the ESD conversion process, error 13 is displayed, the data is invalid; an error is reported when the system is installed.
	Healthy_Save                    = When repairable or unrepairable appears, do not save
	Repair                          = Repair
	IsAuto_Repair                   = Allow automatic repair during idle time
	IsAuto_Repair_Tips              = After each run of the encapsulation script, it will automatically check if there are any mount tasks. If there are mounts, it will not perform repairs; if there are no mounts, it will run the automatic repair work.
	Repairable                      = Repairable
	NonRepairable                   = Irreparable
	HealthyForceStop                = Encountered an irreversible error while processing\n   the event and was forcibly terminated.\n\n   Causes the main problem:\n\n      1. Physical hardware damage, hard disk;\n\n      2. If you use RAMDISK memory virtual disk (including hybrid),\n         please check the physical memory;\n\n      3. Verify the SHA256 of the original MVS (MSDN) version.\n         if the same, please change the directory and try again.\n         if the SHA256 is inconsistent, please download and try again;\n\n      4. Others are not listed in this example.
	Superseded                      = Superseded
	SupersededTips                  = Includes outdated updates, components, etc.
	UnmountFailed                   = I have used several methods, and there is nothing I can do. The younger brother can only strike out. I hope to see you next time with the heroes.
	SaveTo                          = Save to
	WorkDone                        = Finish, press any key to return to the main interface...
	UserCanel                       = The user has cancelled the request.
	Uping                           = Building
	Exclude_View                    = View exclusion rules
	User_Interaction                = User interaction
	Ok_Go_To                        = Available to
	Ok_Go_To_No                     = Not going

	Detailed                        = Details
	Detailed_View                   = View selected rule details

	AddEnv                          = Add routing capabilities to system variables
	AddEnvTips                      = After adding, enter Yi in any PowerShell session to respond, for example, enter "Yi -SIP" to run the encapsulation.

	Unzip_ISO                       = Extract the ISO
	Unzip_Search_Type               = Search directory for ( {0} )
	ISO_Other                       = Other files
	Unzip_Language                  = Language packs
	Unzip_Fod                       = Feature packs
	FileName                        = File name

	UserCancel                      = The user has cancelled the operation.
	MatchMode                       = Match
	Failed                          = Failed
	RandomSelect                    = Random selection
	RulePre                         = Preset rules
	RuleOther                       = Other rules
	RuleCustomize                   = Custom rules
	RuleCustomize_Dont              = Don't use multi-level catalog custom rules
	RuleCustomize_Dont_Tips         = Once you've deleted the old directory, click on "Verify Naming Rules".
	RuleMultistage                  = Multilevel Directory Rules
	RuleMultistageFindFailed        = No multi-level directory rules found, click me to create a template.
	RuleMultistageFindCreateNew     = Create a new multi-level directory rule template
	RuleMultistageTips              = Automatically adapt to multi-level directory rules, {0} directory rules are disabled.
	RuleCustomizeNot                = Extension name not found (Solutions.Custom.Extension), see help documentation.
	RuleCustomizeTips               = No custom rule was created. Please refer to the help document.
	RuleMatchNoFindFolder           = The matching directory failed, click me to create a directory.
	RuleNoFindFile                  = No available files were found, please refresh after adding them.
	RuleFindFolder                  = When a catalog is available, it is automatically selected
	RuleNameNewChange               = Automatically sync after updates
	RuleNewTempate                  = Create template
	RuleSkipFolderCheck             = No longer checks for files in the directory, file type
	RuleAuthon                      = Rule creator
	RuleGUID                        = GUID Globally Unique Identifier
	RuleName                        = Rule name
	RuleDescription                 = Description
	RuleNameUse                     = Sync rule names to: {0}
	RuleISO                         = Match the original ISO installation package
	RuleInBoxApps                   = Complete, provisioned application
	RuleFileType                    = Package name
	RuleFileFind                    = Fuzzy lookup name
	RuleFindError                   = Found that {0} items are pending, click "Check Dependencies" to view the details.
	RuleSelectApps                  = User selected application
	DependencyPackage               = Dependency package
	RuleDependenciesRequired        = Required dependencies
	RuleDependenciesUnselected      = Unselected dependencies
	RuleDependenciesNoCheck         = No longer check dependencies
	RuleDependenciesFix             = Fix unselected dependencies
	Extract_Tips                    = Hint\n\n   1. The result after extracting the language pack cannot be used as the main reference object;\n\n   2. Please use the component list as the main reference object, how to generate:\n\n       In Functions, select Build Components (get the packages in the installed image), select Print or Instant View;\n\n   3. After installing the language pack, please regenerate a component report to see if it corresponds;

	DescendingRuleLang              = Remove language packs in reverse order
	OrderRuleLang                   = Install the language packs in pre-rule order
	OrderRuleLangTips               = Add in order: Basic, Font, Optical Character Recognition, Handwriting Recognition, Text-to-Speech, Speech Recognition, Retail Presentation Experience, Other
	RuleLanguageTips                = Illustrate: \n\n   After using "Install language packs in pre-rule order", files are automatically matched by ambiguous name in the following order: \n
	Match_installed_List            = When installing a language pack, wildcard it from the installed list
	Match_installed_List_Tips       = Installed to match only: Basic, Optical Character Recognition, Handwriting Recognition, Text-to-Speech, Speech Recognition.
	RuleLanguageTipsExt             = \n   When not using "Install language packs in pre-rule order": \n   Automatically search all files in the directory by file type, and install it.\n\n\n   Language and region Features on Demand (FOD)\n   https://learn.microsoft.com/en-US/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = In category
	Basic                           = Basic
	Fonts                           = Fonts
	OCR                             = OCR
	Handwriting                     = Handwriting recognition
	TextToSpeech                    = Text-to-speech
	Speech                          = Speech recognition
	Retail                          = Retail Demo experience
	Features_On_Demand              = Features On Demand
	RegionSpecific                  = Other region-specific requirements
	UnassignedLangFiles             = Unassigned miscellaneous files

	ProcessingImage                 = Processing image: \
	NoInstallImage                  = Does not exist locally
	ConvertChk                      = Check the file
	WindowsFeature                  = Windows features
	Enable                          = Enable
	Disable                         = Disable
	EnableFeatureTips               = Tips\n\n    1. Show that NetFx3 and TelnetClient are preset enabled Function items;\n\n    2. After "mounting", more can be enabled.
	ViewLanguage                    = View image language settings
	ImageLanguage                   = Image language settings
	OnlyLangCleanup                 = Cleanup Components: Tag by Language
	Matched_Component_Names         = Matched component names: \
	BootProcess                     = When processing {0}.wim
	Sync_Language_To                = Sync to
	BootSyncToISO                   = Sync language packs to installer
	BootSyncToISOTips               = Offline image of installed language packs, synced to ISO installer.
	LangIni                         = Regenerate Lang.ini
	LangIniTips                     = After the synchronization is complete, you need to rebuild the Lang.ini in the ISO.
	LangNewAutoSelect               = Automatically select suggestions when there is an event
	LangNewAutoSelectTips           = There is a new event, "Sync Language Packs to Installer", "Rebuild Lang.ini" is selected.
	LangNewAutoNoSelect             = There is a new event, it is recommended that you select "Sync Language Pack to Installer", "Rebuild Lang.ini".
	LangNewAutoNoNewSelect          = If there is no new event, it is recommended that you do not select "Sync Language Pack to Installer", "Rebuild Lang.ini".
	Drive                           = Drive
	ViewDrive                       = View installed drivers
	EditionsProductKey              = Product key
	Editions                        = Image version
	Assign_Editions                 = Automatically assign applications based on image version
	EditionsChangeTips              = Warning, please understand before switching image version: \n\nMicrosoft Service Agreement\nhttps://www.microsoft.com/en-us/servicesagreement/default.aspx\n\nLanguage overview\nhttps://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/languages-overview\n\nYou are not allowed to make the following versions: \n   1. Country specific\n       ProfessionalCountrySpecific\n\n   2. Region-specific family version\n       ProfessionalSingleLanguage\n\nIf a violation may be prosecuted, please strictly comply with it.\n\nIf you insist on converting, click to accept the warning and click "Unlock hidden image version".
	EditionsChangeHide              = Unlock the hidden image version
	EditionsChangeAccect            = I have read the warning, and I am responsible for the relevant laws in the warning

	SelFile                         = Choose file
	Rebuilding                      = Rebuilding
	RebuildAll                      = Rebuild all
	Export_Image                    = Export
	SelectFromError                 = Error
	SelectFileFormatError           = Incorrect file format

	SearchDrive                     = Search driven
	SearchUpdate                    = Search update, type ( {0} ), source: \
	SelectFolder                    = Select directory
	DropFolder                      = You can drag the directory to the current window
	DropFile                        = Files can be dragged to the current window
	Sparse                          = Sparse
	CRCSHA                          = Calibration
	Alternative                     = Alternative file name
	ChangeInstallDisk               = Change auto select disk
	Backup                          = Backup
	Restore                         = Restore

	# View
	ExportToLogs                    = Print report to log
	ExportShow                      = Show report
	MoreFeature                     = More features
	OpenFolder                      = Open Directory
	OpenFile                        = Opening a file
	Running                         = Run
	Paste                           = Copy path
	Clipboard_Copy                  = Copied to clipboard
	ViewWIMFileInfo                 = View Image
	GetInBoxApps                    = InBox Apps: Installed application packages
	GetImagePackage                 = Components: All packages installed in the image
	ViewMounted                     = Get information about all mounted images
'@