ConvertFrom-StringData -StringData @'
	# th-TH
	# Thai (Thailand)

	Main_quests                     = งานหลัก
	Side_quests                     = งานย่อย
	SaveModeClear                   = ล้างประวัติที่เลือก
	SaveModeTipsClear               = ประวัติได้รับการบันทึกและสามารถล้างได้
	SelectTips                      = คำใบ้\n\n    1. โปรดเลือกชื่อของภาพที่จะประมวลผล\n    2. หลังจากที่คุณยกเลิก งานที่ต้องมี "การติดตั้ง" ก่อนการดำเนินการจะไม่มีผลอีกต่อไป
	CacheDisk                       = ดิสก์แคช
	CacheDiskCustomize              = เส้นทางแคชแบบกำหนดเอง
	AutoSelectRAMDISK               = อนุญาตให้เลือกเลเบลวอลุ่มดิสก์อัตโนมัติ
	AutoSelectRAMDISKFailed         = ป้ายกำกับปริมาณไม่ตรงกัน
	ReFS_Find_Volume                = เมื่อพบรูปแบบดิสก์ REFS ให้แยกออก
	ReFS_Exclude                    = ไม่รวมพาร์ติชัน ReFS
	Disk_Not_satisfied_Exclude      = ไม่เป็นไปตามข้อกำหนดขั้นต่ำของดิสก์
	RAMDISK_Change                  = เปลี่ยนชื่อป้ายกำกับปริมาณ
	RAMDISK_Search                  = ค้นหาชื่อป้ายชื่อไดรฟ์
	RAMDISK_Restore                 = เรียกคืนชื่อวอลุ่มที่เตรียมใช้งาน: {0}
	AllowTopMost                    = อนุญาตให้ตรึงหน้าต่างที่เปิดอยู่ไว้ด้านบน
	History                         = ประวัติศาสตร์ที่ชัดเจน
	History_Del_Tips                = เมื่อมีงานการห่อหุ้ม อย่าดำเนินการตัวเลือกเสริมต่อไปนี้ มิฉะนั้นจะทำให้เกิดปัญหาที่ไม่ทราบสาเหตุในระหว่างการรันสคริปต์การห่อหุ้ม
	History_View                    = ดูประวัติ
	HistoryLog                      = อนุญาตให้ทำความสะอาดบันทึกที่เก่ากว่า 7 วันโดยอัตโนมัติ
	HistorySaveFolder               = เส้นทางแหล่งรูปภาพอื่นๆ
	HistoryClearappxStage           = InBox Apps ลบไฟล์ชั่วคราวที่สร้างขึ้นระหว่างการติดตั้ง
	DoNotCheckBoot                  = เมื่อขนาดของไฟล์ Boot.wim เกิน 520MB การสร้างใหม่จะถูกเลือกโดยอัตโนมัติเมื่อสร้าง ISO
	HistoryClearDismSave            = ลบบันทึกการเมานต์ DISM ที่บันทึกไว้ในรีจิสทรี
	ImageSourcesClickShowKey        = อนุญาตให้แสดงเมนู "เลือกคีย์หลัก"
	ImageSourcesClickShowKeyTips    = หลังจากที่ผู้ใช้เลือกแหล่งที่มาของรูปภาพแล้ว: เพิ่มเมนู "เลือกคีย์หลัก" ทางด้านขวา และเพิ่มตัวเลือก "ไปที่": ติดตั้ง, บันทึก, ป๊อปอัป
	Clear_Bad_Mount                 = ลบทรัพยากรทั้งหมดที่เกี่ยวข้องกับอิมเมจที่เมาท์ที่เสียหาย
	ShowCommand                     = แสดงการรันบรรทัดคำสั่งที่สมบูรณ์
	Command                         = บรรทัดคำสั่ง
	SelectSettingImage              = แหล่งที่มาของภาพ
	NoSelectImageSource             = ไม่ได้เลือกแหล่งที่มาของภาพ
	SettingImageRestore             = คืนค่าตำแหน่งเมานต์เริ่มต้น
	SettingImage                    = เปลี่ยนตำแหน่งเมานต์แหล่งที่มาของรูปภาพ
	SelectImageMountStatus          = รับสถานะการเมานต์หลังจากเลือกแหล่งรูปภาพ
	SettingImageTempFolder          = ไดเร็กทอรีชั่วคราว
	SettingImageToTemp              = ไดเร็กทอรีชั่วคราวจะเหมือนกับตำแหน่งที่ติดตั้งไว้
	SettingImagePathTemp            = การใช้ไดเร็กทอรีชั่วคราว
	SettingImageLow                 = ตรวจสอบพื้นที่ว่างที่เหลืออยู่ขั้นต่ำ
	SettingImageNewPath             = เลือกเมานต์ดิสก์
	SettingImageNewPathTips         = ขอแนะนำให้คุณต่อเชื่อมเข้ากับดิสก์หน่วยความจำซึ่งเร็วที่สุด คุณสามารถใช้ซอฟต์แวร์หน่วยความจำเสมือน เช่น Ultra RAMDisk และ ImDisk
	SelectImageSource               = เลือก "Deploy Engine Solution" แล้ว คลิกตกลง
	NoImagePreSource                = ไม่พบแหล่งที่มา คุณควร: \n\n     1. เพิ่มแหล่งรูปภาพเพิ่มเติมไปที่: \n          {0}\n\n     2. เลือก "การตั้งค่า" และเลือกดิสก์ค้นหาแหล่งรูปภาพอีกครั้ง\n\n     3. เลือก "ISO" และเลือก ISO ที่จะขยาย รายการที่จะติดตั้ง ฯลฯ
	NoImageOtherSource              = คลิกฉันเพื่อ "เพิ่ม" เส้นทางอื่นหรือ "ลากไดเรกทอรี" ไปยังหน้าต่างปัจจุบัน
	SearchImageSource               = ดิสก์ค้นหาแหล่งรูปภาพ
	Kernel                          = เคอร์เนล
	Architecture                    = สถาปัตยกรรม
	ArchitecturePack                = สถาปัตยกรรมแพ็คเกจ ทำความเข้าใจกฎการเพิ่ม
	ImageLevel                      = ประเภทการติดตั้ง
	LevelDesktop                    = เดสก์ท็อป
	LevelServer                     = เซิร์ฟเวอร์
	ImageCodename                   = ชื่อรหัส
	ImageCodenameNo                 = ไม่ได้รับการยอมรับ
	MainImageFolder                 = โฮมไดเร็กตอรี่
	MountImageTo                    = ติดไปที่
	Image_Path                      = เส้นทางภาพ
	MountedIndex                    = ดัชนี
	MountedIndexSelect              = เลือกหมายเลขดัชนี
	AutoSelectIndexFailed           = การเลือกดัชนี {0} อัตโนมัติล้มเหลว โปรดลองอีกครั้ง
	Apply                           = แอปพลิเคชัน
	Eject                           = ปรากฏขึ้น
	Mount                           = เมานต์
	ReMount                         = ติดตั้งใหม่
	Unmount                         = ถอนการติดตั้ง
	Mounted                         = ติดแล้ว
	NotMounted                      = ไม่ได้ติด
	NotMountedSpecify               = ไม่ได้ติดตั้ง คุณสามารถระบุตำแหน่งการติดตั้งได้
	MountedIndexError               = การติดตั้งผิดปกติ ลบแล้วลองอีกครั้ง
	NeedsRemount                    = ต้องติดตั้งใหม่
	Invalid                         = ไม่ถูกต้อง
	ImageSouresNoSelect             = แสดงรายละเอียดเพิ่มเติมหลังจากเลือกแหล่งที่มาของภาพ
	Mounted_Mode                    = โหมดเมานต์
	Mounted_Status                  = สถานะเมานท์
	Status                          = สถานะ
	Image_Popup_Default             = บันทึกเป็นค่าเริ่มต้น
	Image_Restore_Default           = เปลี่ยนกลับเป็นค่าเริ่มต้น
	Image_Popup_Tips                = คำใบ้:\n\nเมื่อคุณกำหนดเหตุการณ์ คุณไม่ได้ระบุหมายเลขดัชนีเพื่อประมวลผล {0};\n\nขณะนี้อินเทอร์เฟซการเลือกปรากฏขึ้น โปรดระบุหมายเลขดัชนี หลังจากข้อกำหนดเสร็จสิ้น ขอแนะนำให้คุณเลือก "บันทึกเป็นค่าเริ่มต้น" และจะไม่ปรากฏขึ้นอีกในครั้งถัดไปที่คุณดำเนินการ
	Rule_Show_Full                  = แสดงทั้งหมด
	Rule_Show_Only                  = แสดงกฎเท่านั้น
	Rule_Show_Only_Select           = เลือกจากกฎ
	Image_Unmount_After             = ถอนการติดตั้งที่ติดตั้งทั้งหมด

	Wim_Rule_Update                 = แยกและอัปเดตไฟล์ภายในรูปภาพ
	Wim_Rule_Extract                = แยกไฟล์
	Wim_Rule_Extract_Tips           = หลังจากเลือกกฎเส้นทางแล้ว ให้แตกไฟล์ที่ระบุและบันทึกไว้ในเครื่อง

	Wim_Rule_Verify                 = ตรวจสอบ
	Wim_Rule_Check                  = พิจารณา
	Wim_Rule_CheckIntegrity         = ตรวจสอบความสมบูรณ์
	Wim_Rule_ReadOnly               = สิทธิ์การอ่านอย่างเดียว
	Wim_Rule_Optimize               = การเพิ่มประสิทธิภาพ
	ResetBase                       = การทำความสะอาดอย่างล้ำลึก
	Wim_Rule_SupportEa              = ใช้รูปภาพที่มีคุณสมบัติเพิ่มเติม
	Wim_Rule_WIMBoot                = บูตได้
	Wim_Rule_Compact                = บีบอัดไฟล์ระบบปฏิบัติการ
	Win_Rule_Setbootable            = ทำเครื่องหมายอิมเมจวอลุ่มเป็นบูตได้
	Win_Rule_Setbootable_Tips       = พารามิเตอร์นี้ใช้ได้กับอิมเมจ Windows PE เท่านั้น. \nสามารถทำเครื่องหมายอิมเมจวอลุ่มให้บูตได้เพียงหนึ่งอิมเมจในไฟล์ .wim.
	Destination                     = ปลายทาง

	Wim_Append                      = ผนวก
	Wim_Capture                     = จับภาพ
	Wim_Capture_Tips                = จับภาพอิมเมจไดรฟ์ไปยังไฟล์ WIM ใหม่
	Wim_Capture_Sources             = แหล่งที่มาของการบันทึก
	Wim_Capture_Sources_Tips        = ไดเร็กทอรีที่บันทึกประกอบด้วยโฟลเดอร์ย่อยและข้อมูลทั้งหมด.\nคุณไม่สามารถบันทึกไดเร็กทอรีว่างได้ ไดเร็กทอรีต้องมีไฟล์อย่างน้อยหนึ่งไฟล์
	Wim_Config_File                 = เส้นทางไฟล์การกำหนดค่า ( ข้อยกเว้น )
	Wim_Config_Edit                 = แก้ไข
	Wim_Config_Learn                = ศึกษารายการการกำหนดค่าและไฟล์ WimScript.ini

	Wim_Rename                      = แก้ไขข้อมูลรูปภาพ
	Wim_Image_Name                  = ชื่อรูปภาพ
	Wim_Image_Description           = คำอธิบายรูปภาพ
	Wim_Display_Name                = ชื่อที่แสดง
	Wim_Display_Description         = แสดงคำอธิบาย
	Wim_Edition                     = เครื่องหมายรูปภาพ
	Wim_Edition_Select_Know         = เลือกแฟล็กรูปภาพที่รู้จัก
	Wim_CreatedTime                 = วันที่สร้าง
	Wim_ModifiedTime                = เวลาที่แก้ไขล่าสุด
	Wim_FileCount                   = จำนวนไฟล์
	Wim_DirectoryCount              = จำนวนไดเรกทอรี
	Wim_Expander_Space              = การขยายพื้นที่

	IABSelectNo                     = ไม่ได้เลือกคีย์หลัก: Install, WinRE, Boot
	Unique_Name                     = การตั้งชื่อที่ไม่ซ้ำใคร
	Select_Path                     = เส้นทาง
	Setting_Pri_Key                 = ตั้งค่าไฟล์อัพเดตนี้เป็นเทมเพลตหลัก
	Pri_Key_Update_To               = จากนั้นอัปเดตเป็น
	Pri_Key_Template                = ตั้งค่าไฟล์นี้เป็นเทมเพลตที่ต้องการเพื่อซิงค์กับรายการที่เลือก
	Pri_key_Running                 = งานคีย์หลักได้รับการซิงโครไนซ์และถูกข้ามไป
	ShowAllExclude                  = แสดงการยกเว้นที่เลิกใช้แล้วทั้งหมด

	Index_Process_All               = ประมวลผลหมายเลขดัชนีที่รู้จักทั้งหมด
	Index_Is_Event_Select           = เมื่อมีเหตุการณ์ อินเทอร์เฟซการเลือกหมายเลขดัชนีจะปรากฏขึ้น
	Index_Pre_Select                = หมายเลขดัชนีที่กำหนดไว้ล่วงหน้า
	Index_Select_Tips               = คำใบ้:\n\n{0}.wim ไม่ได้เมานท์อยู่ในขณะนี้ คุณสามารถ:\n\n   1. เลือก "ประมวลผลหมายเลขดัชนีที่รู้จักทั้งหมด";\n\n   2. เลือก "เมื่อมีเหตุการณ์ อินเทอร์เฟซการเลือกหมายเลขดัชนีจะปรากฏขึ้น";\n\n   3. หมายเลขดัชนีที่กำหนดไว้ล่วงหน้า\n      ระบุหมายเลขดัชนี 6 ไม่มีหมายเลขดัชนีในระหว่างการประมวลผล และการประมวลผลถูกข้ามไป

	Index_Tips_Custom_Expand        = กลุ่ม: {0}\n\nเมื่อประมวลผล {1} จะต้องกำหนดหมายเลขดัชนี {2} ไม่เช่นนั้นจะไม่สามารถประมวลผลได้\n\nหลังจากเลือก "ซิงโครไนซ์กฎการอัปเดตกับหมายเลขดัชนีทั้งหมด" คุณจะต้องตรวจสอบเพียงรายการใดรายการหนึ่งเป็นเทมเพลตหลักเท่านั้น

	DefenderExclude                 = การยกเว้นของโปรแกรมป้องกันไวรัส Windows
	DefenderFolder                  = เพิ่มไดเร็กทอรีนี้ลงในการยกเว้นของโปรแกรมป้องกันไวรัส Windows
	DefenderVolume                  = หลังจากพบชื่อป้ายชื่อไดรฟ์ที่ตรงกันแล้ว ให้เพิ่มดิสก์นี้ลงในการยกเว้นของโปรแกรมป้องกันไวรัส Windows
	DefenderIsAdd                   = เพิ่มลงในการยกเว้นของโปรแกรมป้องกันไวรัส Windows แล้ว
'@