ConvertFrom-StringData -StringData @'
	# ru-RU
	# Russian (Russia)

	FontsUI                   = Segoe UI
	Mainname                  = Механизм развертывания: пакет Йи
	Learn                     = Изучать
	MainHisName               = Бонусное решение
	Location                  = Открытая локация
	About                     = О
	Reset                     = Перезагрузить
	AddTo                     = Добавить в
	Instl                     = Установить
	ItInstalled               = Установлено
	Close                     = Закрытие
	Auto                      = Автоматический
	Disable                   = Запрещать
	Enable                    = Давать возможность
	Setting                   = Настраивать
	Restore                   = Восстанавливаться
	CLearn                    = Убирать
	Operable                  = Работоспособный
	Inoperable                = Неработоспособный
	Optimize                  = Оптимизация
	Hide                      = Скрывать
	Show                      = Показывать
	Del                       = Удалить
	Done                      = Заканчивать
	OK                        = Конечно
	Cancel                    = Отмена
	AllSel                    = Выбрать все
	AllClear                  = Очистить все
	Refresh                   = Обновить
	RefreshModules            = Горячее обновление всех модулей
	Necessary                 = Основное программное обеспечение
	MostUsedSoftware          = Часто используемое программное обеспечение
	System                    = Система
	Service                   = Служить
	TaskBar                   = Все значки панели задач
	DeskIcon                  = Значки на рабочем столе
	InstallFonts              = Установить шрифты
	SettingTo                 = Установить на {0}
	AvailableLanguages        = Доступные языки
	SwitchLanguage            = Переключить язык
	LanguageReset             = Сбросить настройки языка
	LanguageCode              = Отметка зоны
	LanguageSelRegion         = Выберите вашу страну или регион
	LanguageRemember          = Запомнить выбранный язык
	LanguageSearchNo          = Доступные языки не найдены
	LanguageNoPack            = Если локально языкового пакета нет, он закроется автоматически.
	LanguageNoSel             = Пожалуйста, выберите регион
	Search                    = Поиск
	PleaseChoose              = Пожалуйста, выберите
	FailedCreateFolder        = Не удалось создать каталог
	Failed                    = Неудача
	ToMsg                     = {0} Автоматический возврат в главное меню через несколько секунд.
	Restart                   = Перезапуск вступает в силу
	AdvOption                 = Дополнительные функции

	StartDown                 = Начать загрузку
	ConnectTo                 = Подключиться к
	FileName                  = Имя файла
	SaveTo                    = Сохранить в
	NotAvailable              = Статус: Не доступен
	ExistingPacker            = Уже есть установочный пакет
	ExistingInstlPacker       = Уже есть сжатый пакет
	Unpacking                 = Разархивирование
	QucikRun                  = Быстрый бег:
	WaitDone                  = Ожидание завершения:
	Parameter                 = Параметр:
	ErrorDown                 = Во время загрузки произошла ошибка
	UserCancel                = Пользователь отменил операцию.

	VerifyNameTips            = Допускается только сочетание английских букв и цифр, другие символы не допускаются: пробелы, длина не может быть больше 16 символов, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Пользовательский префикс каталога
	NoSetFolderLabel          = Префикс пользовательского каталога не установлен.
	ISO9660TipsErrorSpace     = Не может содержать: начальные и конечные пробелы.
	ISO9660TipsErrorOther     = Не может содержать: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Метка тома не может содержать более {0} символов.
	Help                      = Помощь
	WorkDone                  = Завершено, нажмите любую клавишу, чтобы вернуться в основной интерфейс...
	Short_Cmd                 = Ярлыки
	Options                   = Параметры
'@