ConvertFrom-StringData -StringData @'
	# da-dk
	# Danish (Denmark)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Dashboard
	Learn                           = Studere
	Menu                            = Menu
	Short_Cmd                       = Genveje
	Shortcut                        = Genvej
	Update                          = Forny
	CUpdate                         = Kumulative opdateringer
	Rebuild                         = Rekonstruktion
	AddTo                           = Tilføj til
	Del                             = Slette
	Copy                            = Kopi
	Rename                          = Omdøb
	Refresh                         = Opfriske
	RefreshModules                  = Hot opdater alle moduler
	Done                            = Slutte
	OK                              = Sikker
	Cancel                          = Ophæve
	AllSel                          = Vælg alle
	AllClear                        = Ryd alt
	Setting                         = Sætte op
	Change                          = Forandring
	Help                            = Hjælp
	Logging                         = Gem log til
	AvailableLanguages              = Tilgængelige sprog
	SwitchLanguage                  = Skifte sprog
	LanguageSelRegion               = Vælg dit land eller område
	LanguageRemember                = Husk det valgte sprog
	LanguageSearchNo                = Ingen tilgængelige sprog fundet
	LanguageNoPack                  = Hvis der ikke er nogen sprogpakke lokalt, afsluttes den automatisk.
	LanguageNoSel                   = Vælg venligst en region
	Search                          = Søge
	PleaseChoose                    = Vælg venligst
	Options                         = Valgmuligheder
	Choose                          = Valgt
	NoChoose                        = Ikke valgt
	AdvOption                       = Valgfrie funktioner
	ExcludeItem                     = Udelukke ved regel
	DeDuplication                   = Udelad dubletter
	DeDuplication_Unlock            = Lås op for deaktiverede dubletter
	Existed                         = Eksisterer allerede
	FailedCreateFolder              = Det lykkedes ikke at oprette mappe
	FailedCreateFile                = Filen kunne ikke oprettes
	ToMsg                           = {0} Vend automatisk tilbage til hovedmenuen efter sekunder.
	OnDemandPlanTask                = Specialtildeling af kendte begivenheder
	Operable                        = Kan betjenes
	Inoperable                      = Ubrugelig
	Hide                            = Skjule
	CuringUpdate                    = Solid opdatering
	CuringUpdateTips                = Når opdateringen er blevet størknet, kan den ikke afinstalleres.
	Healthy                         = Sund
	HealthyTips                     = Det er især vigtigt at kontrollere sundhedsstatus. Når "reparable" eller "unrepairable" vises: Under ESD-konverteringsprocessen bliver der vist fejl 13, og dataene er ugyldige, når systemet installeres.
	Healthy_Save                    = Når reparationsbar eller uoprettelig vises, skal du ikke gemme.
	Repair                          = Reparation
	IsAuto_Repair                   = Tillad automatisk reparation i tomgang
	IsAuto_Repair_Tips              = Kontroller automatisk, om der er nogen monteringsopgaver efter hver kørsel af pakkescriptet. Hvis det er monteret, vil der ikke blive udført reparation, hvis det ikke er monteret, vil der blive kørt automatisk.
	Repairable                      = Kan repareres
	NonRepairable                   = Kan ikke repareres
	HealthyForceStop                = Under behandlingen af hændelsen opstod der en irreversibel fejl, og processen blev tvangsafbrudt.\n\n   Forårsager hovedproblemer: \n\n      1. Fysisk hardware er beskadiget, harddisk;\n\n      2. Hvis du bruger virtuel RAMDISK-hukommelsesdisk (inklusive hybrid), skal du kontrollere den fysiske hukommelse;\n\n      3. Bekræft den originale SHA256 af MVS (MSDN) Hvis den er konsistent, skift venligst mappen og prøv igen.\n\n      4. Andre er ikke anført i dette eksempel.
	Superseded                      = Ryd op i det udskiftede
	SupersededTips                  = Indeholder forældede opdateringer, komponenter osv.
	UnmountFailed                   = Jeg har prøvet flere metoder, men intet kan gøres, jeg kan kun stoppe. Jeg vil gerne se dig næste gang.
	SaveTo                          = Gemme til
	WorkDone                        = Fuldført, tryk på en vilkårlig tast for at vende tilbage til hovedgrænsefladen...
	UserCanel                       = Brugeren har annulleret anmodningen.
	Uping                           = Genererer
	Exclude_View                    = Se ekskluderingsregler
	User_Interaction                = Brugerinteraktion
	Ok_Go_To                        = Tilgængelig til
	Ok_Go_To_No                     = Går ikke

	Detailed                        = Detaljeret
	Detailed_View                   = Se valgte regeldetaljer

	AddEnv                          = Tilføj routingfunktionalitet til systemvariabler
	AddEnvTips                      = Efter tilføjelse skal du indtaste Yi i enhver PowerShell-session for at svare. Indtast f.eks. "Yi -SIP" for at køre indkapslingen.

	Unzip_ISO                       = Uddrag ISO
	Unzip_Search_Type               = Søg i mappen ( {0} )
	ISO_Other                       = Andre dokumenter
	Unzip_Language                  = Sprogpakke
	Unzip_Fod                       = Featurepakke
	FileName                        = Filnavn

	UserCancel                      = Brugeren har annulleret handlingen.
	MatchMode                       = Kamp
	Failed                          = Svigte
	RandomSelect                    = Tilfældigt udvalgt
	RulePre                         = Forudindstillede regler
	RuleOther                       = Andre regler
	RuleCustomize                   = Brugerdefinerede regler
	RuleCustomize_Dont              = Brug ikke brugerdefinerede regler for biblioteker på flere niveauer
	RuleCustomize_Dont_Tips         = Når du har slettet den gamle mappe, skal du klikke på "Bekræft navneregler".
	RuleMultistage                  = Biblioteksregler på flere niveauer
	RuleMultistageFindFailed        = Der blev ikke fundet nogen mapperegler på flere niveauer. Klik på mig for at oprette en skabelon.
	RuleMultistageFindCreateNew     = Opret en ny mapperegelskabelon på flere niveauer
	RuleMultistageTips              = Tilpas automatisk katalogregler på flere niveauer, {0} katalogreglen er blevet deaktiveret.
	RuleCustomizeNot                = Udvidelsesnavnet (Solutions.Custom.Extension) blev ikke fundet. Se venligst hjælpedokumentationen.
	RuleCustomizeTips               = Der er ikke oprettet nogen tilpasset regel. Se venligst hjælpedokumentationen.
	RuleMatchNoFindFolder           = Kunne ikke matche mappen. Klik på mig for at oprette mappen.
	RuleNoFindFile                  = Ingen tilgængelige filer fundet. Tilføj venligst og opdater.
	RuleFindFolder                  = Directory automatisk valgt, når den er tilgængelig
	RuleNameNewChange               = Synkroniser automatisk efter opdateringer
	RuleNewTempate                  = Opret skabelon
	RuleSkipFolderCheck             = Kontrollerer ikke længere, om filen findes i mappen og filtypen
	RuleAuthon                      = Regelskaber
	RuleGUID                        = GUID globalt unik identifikator
	RuleName                        = Regelnavn
	RuleDescription                 = Beskrive
	RuleNameUse                     = Synkroniser regelnavn til: {0}
	RuleISO                         = Match original ISO-installationspakke
	RuleInBoxApps                   = Komplet, prækonfigureret applikation
	RuleFileType                    = Pakkenavn
	RuleFileFind                    = Fuzzy søgenavn
	RuleFindError                   = Fandt {0} elementer, der skal behandles, klik på "Kontroller afhængigheder" for at se detaljer.
	RuleSelectApps                  = Applikationer valgt af brugeren
	DependencyPackage               = Afhængighedspakke
	RuleDependenciesRequired        = Nødvendige afhængigheder
	RuleDependenciesUnselected      = Ikke-valgte afhængigheder
	RuleDependenciesNoCheck         = Afhængigheder kontrolleres ikke længere
	RuleDependenciesFix             = Rette afhængigheder ikke valgt
	Extract_Tips                    = Antydning\n\n   1. Resultatet efter udtrækning af sprogpakken kan ikke bruges som hovedreferenceobjekt;\n\n   2. Brug venligst komponentlisten som hovedreferenceobjekt. Sådan genereres: \n\n       I Functions, vælg Generer komponent (hent pakken i det installerede billede), vælg Udskriv eller Vis øjeblikkeligt;\n\n   3. Efter installation af sprogpakken skal du genskabe en komponentrapport for at kontrollere, om den stemmer overens;

	DescendingRuleLang              = Fjern sprogpakker i omvendt rækkefølge
	OrderRuleLang                   = Installer sprogpakker i forudbestemt rækkefølge
	OrderRuleLangTips               = Tilføj i rækkefølge: Basic, Fonts, Optical Character Recognition, Håndskriftsgenkendelse, Tekst-til-tale, Talegenkendelse, Retail Demo Experience, Andet
	RuleLanguageTips                = Illustrere: \n\n   Efter brug af "Installer sprogpakker i forudbestemt rækkefølge", matches filer automatisk med fuzzy navne i følgende rækkefølge:\n
	Match_installed_List            = Når du installerer en sprogpakke, skal du jokertegne den fra den installerede liste
	Match_installed_List_Tips       = Matcher kun, når det er installeret: Basic, Optisk tegngenkendelse, Håndskriftsgenkendelse, Tekst-til-tale, Talegenkendelse.
	RuleLanguageTipsExt             = \n   Når du ikke bruger "Installer sprogpakker i forudbestemt rækkefølge": \n   Søg automatisk efter alle filer i mappen efter filtype og installer dem.\n\n   Sprog og region on-demand funktioner (FOD)\n   https://learn.microsoft.com/da-dk/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategori
	Basic                           = Grundlæggende
	Fonts                           = Skrifttype
	OCR                             = Optisk tegngenkendelse
	Handwriting                     = Håndskriftsgenkendelse
	TextToSpeech                    = Tekst til tale
	Speech                          = Talegenkendelse
	Retail                          = Detaildemooplevelse
	Features_On_Demand              = Funktioner på efterspørgsel
	RegionSpecific                  = Andre regionsspecifikke krav
	UnassignedLangFiles             = Ikke-tildelte diverse filer

	ProcessingImage                 = Bearbejd billedet: 
	NoInstallImage                  = Findes ikke lokalt
	ConvertChk                      = Tjek filen
	WindowsFeature                  = Windows-funktioner
	Enable                          = Aktivere
	Disable                         = Deaktiver
	EnableFeatureTips               = Antydning\n\n    1. Vis NetFx3 og TelnetClient som forudindstillede aktiverede funktionselementer;\n\n    2. Efter "montering" kan mere aktiveres.
	ViewLanguage                    = Se billedsprogindstillinger
	ImageLanguage                   = Indstillinger for billedsprog
	OnlyLangCleanup                 = Rengør komponenter: tag efter sprog
	Matched_Component_Names         = Matchet komponentnavn:
	BootProcess                     = Ved behandling af {0}.wim
	Extract_Rule_Only_And_Full      = Uddrag kun udvalgte sprog
	Sync_Language_To                = Synkroniser til
	BootSyncToISO                   = Synkroniser sprogpakker til installationsprogrammet
	BootSyncToISOTips               = Den installerede sprogpakke af offlinebilledet synkroniseres med ISO-installationsprogrammet.
	Setup_Fix_Missing               = Reparer automatisk manglende installationselementer
	Setup_Fix_Missing_Tips          = Hvis installationsprogrammet mangler arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui, åbn "Udpak", vælg "Regler", og klik på "Udtræk Installer Missing Items".
	Setup_Fix_Missing_Extract       = Udpak manglende elementer i installationsprogrammet
	Setup_Fix_Missing_Extract_Tips  = Udpak de manglende elementer fra installationsprogrammet fra alle lokale sprogpakker: arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui.
	LangIni                         = Gendan Lang.ini
	LangIniTips                     = Efter synkroniseringen er gennemført, skal Lang.ini i ISO'en genopbygges.
	LangNewAutoSelect               = Vælg automatisk foreslåede elementer, når en hændelse indtræffer
	LangNewAutoSelectTips           = Der er nye begivenheder, "Synkroniser sprogpakker til installationsprogram", "Genopbyg Lang.ini" valgt.
	LangNewAutoNoSelect             = Der er nye begivenheder, det anbefales at du vælger "Synkroniser sprogpakke til installatør" og "Genopbyg Lang.ini".
	LangNewAutoNoNewSelect          = Der er ingen nye hændelser. Det anbefales, at du ikke vælger "Synkroniser sprogpakke til installationsprogram" og "Genopbyg Lang.ini".
	Drive                           = Køre
	ViewDrive                       = Se installerede drivere
	EditionsProductKey              = Produktnøgle
	Editions                        = Billedversion
	Assign_Editions                 = Distribuer automatisk applikationer baseret på billedversioner
	EditionsChangeTips              = Advarsel, forstå venligst, før du skifter billedversion: \n\nMicrosoft Serviceaftale\nhttps://www.microsoft.com/da-dk/servicesagreement/default.aspx\n\nSprogoversigt\nhttps://learn.microsoft.com/da-dk/windows-hardware/manufacture/desktop/languages-overview\n\nDu må ikke lave versioner af:\n   1. Landespecifik\n       ProfessionalCountrySpecific\n\n   2. Regionsspecifik hjemmeversion\n       ProfessionalSingleLanguage\n\nOverhold venligst strengt, da du kan blive genstand for retsforfølgelse, hvis du bliver overtrådt.\n\nHvis du insisterer på at konvertere, skal du klikke for at acceptere advarslen og klikke på "Lås op for skjult billedversion".
	EditionsChangeHide              = Lås op for skjulte billedversioner
	EditionsChangeAccect            = Jeg har læst advarslen og er ansvarlig for de relevante love indeholdt i advarslen

	SelFile                         = Vælg fil
	Rebuilding                      = Under genopbygning
	RebuildAll                      = Genopbygg det hele
	Export_Image                    = Eksportere
	SelectFromError                 = Fejl
	SelectFileFormatError           = Filformatet er forkert

	SearchDrive                     = Søgedrevet
	SearchUpdate                    = Søg opdateringer, type ( {0} ), kilde:
	SelectFolder                    = Vælg bibliotek
	DropFolder                      = Kan trække mapper til det aktuelle vindue
	DropFile                        = Filer kan trækkes til det aktuelle vindue
	Sparse                          = Sjælden
	CRCSHA                          = Check
	Alternative                     = Alternativt filnavn
	ChangeInstallDisk               = Skift automatisk diskvalg

	# View
	ExportToLogs                    = Udskriv rapport til log
	ExportShow                      = Vis rapporter med det samme
	MoreFeature                     = Flere funktioner
	OpenFolder                      = Åbn mappe
	OpenFile                        = Åbne fil
	Running                         = Løbe
	Paste                           = Kopisti
	Clipboard_Copy                  = Kopieret til udklipsholder
	ViewWIMFileInfo                 = Se billede
	GetInBoxApps                    = InBox Apps: Installerede applikationspakker
	GetImagePackage                 = Komponenter: Alle pakker installeret i billedet
	ViewMounted                     = Få information om alle monterede billeder
'@