ConvertFrom-StringData -StringData @'
	# sv-SE
	# Swedish (Sweden)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Instrumentbräda
	Learn                           = Studera
	Menu                            = Meny
	Short_Cmd                       = Genvägskommando
	Shortcut                        = 捷径
	Update                          = Förnya
	CUpdate                         = Kumulativa uppdateringar
	Rebuild                         = Rekonstruktion
	AddTo                           = Lägg till
	Del                             = Radera
	Copy                            = Kopiera
	Rename                          = Döpa om
	Refresh                         = Uppdatera
	RefreshModules                  = Varmuppdatera alla moduler
	Done                            = Avsluta
	OK                              = Säker
	Cancel                          = Avboka
	AllSel                          = Välj alla
	AllClear                        = Rensa allt
	Setting                         = Inrätta
	Change                          = Ändra
	Help                            = Hjälp
	Logging                         = Logga
	AvailableLanguages              = Tillgängliga språk
	SwitchLanguage                  = Byta språk
	LanguageSelRegion               = Välj ditt land eller din region
	LanguageRemember                = Kom ihåg valt språk
	LanguageSearchNo                = Inga tillgängliga språk hittades
	LanguageNoPack                  = Om det inte finns något språkpaket lokalt kommer det att avslutas automatiskt.
	LanguageNoSel                   = Välj en region
	Search                          = Söka
	PleaseChoose                    = Vänligen välj
	Options                         = Alternativ
	Choose                          = Vald
	NoChoose                        = Ej vald
	AdvOption                       = Valfria funktioner
	ExcludeItem                     = Uteslut enligt regel
	DeDuplication                   = Uteslut dubbletter
	DeDuplication_Unlock            = Lås upp inaktiverade dubbletter
	Existed                         = Finns redan
	FailedCreateFolder              = Det gick inte att skapa katalogen
	FailedCreateFile                = Det gick inte att skapa filen
	ToMsg                           = {0} Återgå automatiskt till huvudmenyn efter några sekunder.
	OnDemandPlanTask                = Anpassad tilldelning av kända händelser
	Operable                        = Manövrerbar
	Inoperable                      = Inoperabel
	Hide                            = Dölja
	CuringUpdate                    = Solid uppdatering
	CuringUpdateTips                = När uppdateringen har stelnat kan den inte avinstalleras.
	Healthy                         = Hälsosam
	HealthyTips                     = Det är särskilt viktigt att kontrollera hälsostatus När "reparable" eller "unrepairable" visas: Under ESD-konverteringsprocessen uppmanas fel 13 och informationen är ogiltig när systemet installeras.
	Healthy_Save                    = Spara inte när reparationsbar eller irreparabel visas.
	Repair                          = Reparera
	IsAuto_Repair                   = "Tillåt automatisk reparation vid tomgång
	IsAuto_Repair_Tips              = "Kontrollera automatiskt om det finns några monteringsuppgifter efter varje körning av paketeringsskriptet. Om den är monterad kommer ingen reparation att utföras om den inte är monterad.
	Repairable                      = Reparerbar
	NonRepairable                   = Kan inte repareras
	HealthyForceStop                = Under bearbetningen av händelsen påträffades ett oåterkalleligt fel och händelsen avbröts med tvång.\n\n   Orsakar huvudproblem:\n\n      1. Fysisk hårdvara är skadad, hårddisk;\n\n      2. Om du använder virtuell disk med RAMDISK-minne (inklusive hybrid), kontrollera det fysiska minnet;\n\n      3. Verifiera den ursprungliga SHA256 av MVS (MSDN) Om den är konsekvent, ändra katalogen och försök igen Om SHA256 är inkonsekvent, ladda ner den igen och försök igen.\n\n      4. Andra är inte listade i detta exempel.
	Superseded                      = Rensa upp det utbytta
	SupersededTips                  = Inkluderar föråldrade uppdateringar, komponenter etc.
	UnmountFailed                   = Jag har provat flera metoder, men ingenting kan göras. Jag kan bara sluta.
	SaveTo                          = Spara till
	WorkDone                        = Slutfört, tryck på valfri tangent för att återgå till huvudgränssnittet...
	UserCanel                       = Användaren har avbrutit begäran.
	Uping                           = Alstrande
	Exclude_View                    = Se undantagsregler
	User_Interaction                = Användarinteraktion
	Ok_Go_To                        = Tillgänglig för
	Ok_Go_To_No                     = Går inte

	Detailed                        = Detaljerad
	Detailed_View                   = Visa vald regelinformation

	AddEnv                          = Lägg till routingfunktionalitet till systemvariabler
	AddEnvTips                      = När du har lagt till anger du Yi i valfri PowerShell-session för att svara. Ange till exempel "Yi -SIP" för att köra inkapslingen.

	Unzip_ISO                       = Extrahera ISO
	Unzip_Search_Type               = Sök i katalogen ( {0} )
	ISO_Other                       = Andra dokument
	Unzip_Language                  = Språkpaket
	Unzip_Fod                       = Funktionspaket
	FileName                        = Filnamn

	UserCancel                      = Användaren har avbrutit åtgärden.
	MatchMode                       = Match
	Failed                          = Misslyckas
	RandomSelect                    = Slumpmässigt utvalda
	RulePre                         = Förinställda regler
	RuleOther                       = Andra regler
	RuleCustomize                   = Anpassade regler
	RuleCustomize_Dont              = Använd inte anpassade regler för kataloger på flera nivåer
	RuleCustomize_Dont_Tips         = När du har tagit bort den gamla katalogen klickar du på "Verifiera namnregler".
	RuleMultistage                  = Katalogregler på flera nivåer
	RuleMultistageFindFailed        = Inga katalogregler på flera nivåer hittades. Klicka på mig för att skapa en mall.
	RuleMultistageFindCreateNew     = Skapa en ny katalogregelmall på flera nivåer
	RuleMultistageTips              = Anpassa katalogregler på flera nivåer automatiskt, katalogregeln {0} har inaktiverats.
	RuleCustomizeNot                = Tilläggsnamnet (Solutions.Custom.Extension) hittades inte, se hjälpdokumentationen.
	RuleCustomizeTips               = Ingen anpassad regel skapad, se hjälpdokumentationen.
	RuleMatchNoFindFolder           = Det gick inte att matcha katalogen, klicka på mig för att skapa katalogen.
	RuleNoFindFile                  = Inga tillgängliga filer hittades, lägg till och uppdatera.
	RuleFindFolder                  = Katalog väljs automatiskt när den är tillgänglig
	RuleNameNewChange               = Synkronisera automatiskt efter uppdateringar
	RuleNewTempate                  = Skapa mall
	RuleSkipFolderCheck             = Kontrollerar inte längre om filen finns i katalogen och filtypen
	RuleAuthon                      = Regelskapare
	RuleGUID                        = GUID globalt unik identifierare
	RuleName                        = Regelnamn
	RuleDescription                 = Beskriva
	RuleNameUse                     = Synkronisera regelnamn till: {0}
	RuleISO                         = Matcha original ISO-installationspaket
	RuleInBoxApps                   = Komplett, förkonfigurerad applikation
	RuleFileType                    = Paketnamn
	RuleFileFind                    = Luddigt söknamn
	RuleFindError                   = Hittade {0} objekt som ska bearbetas, klicka på "Kontrollera beroenden" för att se detaljer.
	RuleSelectApps                  = Applikationer som valts av användaren
	DependencyPackage               = Beroendepaket
	RuleDependenciesRequired        = Erforderliga beroenden
	RuleDependenciesUnselected      = Omarkerade beroenden
	RuleDependenciesNoCheck         = Beroenden kontrolleras inte längre
	RuleDependenciesFix             = Fixa beroenden som inte har valts
	Extract_Tips                    = Antydan\n\n   1. Resultatet efter extrahering av språkpaketet kan inte användas som huvudreferensobjekt;\n\n   2. Använd komponentlistan som huvudreferensobjekt. Så här genererar du:\n\n       I Funktioner, välj Generera komponent (hämta paketet i den installerade bilden), välj Skriv ut eller Visa direkt;\n\n   3. När du har installerat språkpaketet, generera en komponentrapport för att kontrollera om den stämmer överens;

	DescendingRuleLang              = Ta bort språkpaket i omvänd ordning
	OrderRuleLang                   = Installera språkpaket i förutbestämd ordning
	OrderRuleLangTips               = Lägg till i ordning: Grundläggande, Teckensnitt, Optisk teckenigenkänning, Handskriftsigenkänning, Text-till-tal, Taligenkänning, Retail Demo Experience, Övrigt
	RuleLanguageTips                = Illustrera:\n\n   Efter att ha använt "Installera språkpaket i förutbestämd ordning" matchas filer automatiskt med luddiga namn i följande ordning: \n
	Match_installed_List            = När du installerar ett språkpaket ska du använda det med jokertecken från den installerade listan
	Match_installed_List_Tips       = Matchar endast när det är installerat: Basic, Optisk teckenigenkänning, Handskriftsigenkänning, Text-till-tal, Taligenkänning.
	RuleLanguageTipsExt             = \n   När du inte använder "Installera språkpaket i förutbestämd ordning": \n   Sök automatiskt efter alla filer i katalogen efter filtyp och installera dem.\n\n   Språk och region on-demand funktioner (FOD)\n   https://learn.microsoft.com/sv-se/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategori
	Basic                           = Grundläggande
	Fonts                           = Font
	OCR                             = Optisk teckenigenkänning
	Handwriting                     = Handskriftsigenkänning
	TextToSpeech                    = Text till tal
	Speech                          = Taligenkänning
	Retail                          = Retail Demo Experience
	Features_On_Demand              = Funktioner på begäran
	RegionSpecific                  = Andra regionspecifika krav
	UnassignedLangFiles             = Otilldelade diverse filer

	ProcessingImage                 = Bearbeta bilden:
	NoInstallImage                  = Finns inte lokalt
	ConvertChk                      = Kontrollera filen
	WindowsFeature                  = Windows-funktioner
	Enable                          = Aktivera
	Disable                         = Inaktivera
	EnableFeatureTips               = Antydan\n\n    1. Visa NetFx3 och TelnetClient som förinställda aktiverade funktionsobjekt;\n\n    2. Efter "montering" kan fler aktiveras.
	ViewLanguage                    = Visa inställningar för bildspråk
	ImageLanguage                   = Inställningar för bildspråk
	OnlyLangCleanup                 = Rengör komponenter: tagga efter språk
	Matched_Component_Names         = Matchat komponentnamn:
	BootProcess                     = När du bearbetar {0}.wim
	Sync_Language_To                = Synkronisera till
	BootSyncToISO                   = Synkronisera språkpaket till installationsprogrammet
	BootSyncToISOTips               = Det installerade språkpaketet för offlineavbildningen synkroniseras med ISO-installationsprogrammet.
	LangIni                         = Återskapa Lang.ini
	LangIniTips                     = Efter att synkroniseringen är klar måste Lang.ini i ISO byggas om.
	LangNewAutoSelect               = Välj automatiskt föreslagna objekt när en händelse inträffar
	LangNewAutoSelectTips           = Det finns nya händelser, "Synkronisera språkpaket till installationsprogrammet", "Rebuild Lang.ini" har valts.
	LangNewAutoNoSelect             = Det finns nya händelser, det rekommenderas att du väljer "Synkronisera språkpaket till installationsprogrammet" och "Rebuild Lang.ini".
	LangNewAutoNoNewSelect          = Det finns inga nya händelser. Det rekommenderas att du inte väljer "Synkronisera språkpaketet till installationsprogrammet" eller "Rebuild Lang.ini".
	Drive                           = Köra
	ViewDrive                       = Visa installerade drivrutiner
	EditionsProductKey              = Produktnyckel
	Editions                        = Bildversion
	Assign_Editions                 = Automatiskt distribuera applikationer baserat på bildversioner
	EditionsChangeTips              = Varning, vänligen förstå innan du byter bildversion:\n\nMicrosoft Serviceavtal\nhttps://www.microsoft.com/sv-se/servicesagreement/default.aspx\n\nSpråköversikt\nhttps://learn.microsoft.com/sv-se/windows-hardware/manufacture/desktop/languages-overview\n\nDu får inte göra versioner av: \n   1. Landsspecifik\n       ProfessionalCountrySpecific\n\n   2. Regionspecifik hemversion\n       ProfessionalSingleLanguage\n\nVänligen följ strikt eftersom du kan bli föremål för åtal om du bryter mot det.\n\nOm du insisterar på att konvertera, klicka för att acceptera varningen och klicka på "Lås upp version av dold bild".
	EditionsChangeHide              = Lås upp versioner av dolda bilder
	EditionsChangeAccect            = Jag har läst varningen och är ansvarig för de relevanta lagarna i varningen

	SelFile                         = Välj fil
	Rebuilding                      = Under rekonstruktion
	RebuildAll                      = Bygg om allt
	Export_Image                    = Exportera
	SelectFromError                 = Misstag
	SelectFileFormatError           = Filformatet är felaktigt

	SearchDrive                     = Sökdriven
	SearchUpdate                    = Sök uppdateringar, typ ( {0} ), källa:
	SelectFolder                    = Välj katalog
	DropFolder                      = Kan dra kataloger till det aktuella fönstret
	DropFile                        = Filer kan dras till det aktuella fönstret
	Sparse                          = Sällsynt
	CRCSHA                          = Kontrollera
	Alternative                     = Alternativt filnamn
	ChangeInstallDisk               = Ändra automatiskt val av disk

	# View
	ExportToLogs                    = Skriv ut rapport för att logga
	ExportShow                      = Visa rapporter direkt
	MoreFeature                     = Fler funktioner
	OpenFolder                      = Öppna katalogen
	OpenFile                        = Öppna filen
	Running                         = Sikt
	Paste                           = Kopieringsväg
	Clipboard_Copy                  = Kopierade till urklipp
	ViewWIMFileInfo                 = Visa bild
	GetInBoxApps                    = InBox Apps: Installerade applikationspaket
	GetImagePackage                 = Komponenter: Alla paket installerade i bilden
	ViewMounted                     = Få information om alla monterade bilder
'@