ConvertFrom-StringData -StringData @'
	# zh-TW
	# Chinese (Traditional, Taiwan)

	FontsUI                   = Microsoft JhengHei UI
	Mainname                  = 部署引擎：Yi's 套件
	Learn                     = 學習
	MainHisName               = 附贈解決方案
	Location                  = 打開所在位置
	About                     = 關於
	Reset                     = 重置
	AddTo                     = 添加
	Instl                     = 安裝
	ItInstalled               = 已安裝
	Close                     = 關閉
	Auto                      = 自動
	Disable                   = 禁用
	Enable                    = 啟用
	Setting                   = 設置
	Restore                   = 恢復
	Clean                     = 清理
	Operable                  = 可操作
	Inoperable                = 不可操作
	Optimize                  = 優化
	Hide                      = 隱藏
	Show                      = 顯示
	Del                       = 刪除
	Done                      = 完成
	OK                        = 確定
	Cancel                    = 取消
	AllSel                    = 選擇所有
	AllClear                  = 清除所有
	Refresh                   = 刷新
	RefreshModules            = 熱刷新所有模組
	Necessary                 = 必備軟件
	MostUsedSoftware          = 常用軟體
	System                    = 系統
	Service                   = 服務
	TaskBar                   = 任務欄所有圖標
	DeskIcon                  = 桌面圖標
	InstallFonts              = 安裝字體
	SettingTo                 = 設置為 {0}
	Command                   = 命令行
	RuleName                  = 規則名稱
	Language                  = 語言
	AvailableLanguages        = 可用語言
	SwitchLanguage            = 切換語言
	LanguageReset             = 重置語言設定
	LanguageCode              = 區域標記
	LanguageSelRegion         = 選擇您的國家或地區
	LanguageRemember          = 記住所選語言
	LanguageSearchNo          = 未搜尋到可用的語言
	LanguageNoSel             = 請選擇區域
	Search                    = 搜尋
	PleaseChoose              = 請選擇
	FailedCreateFolder        = 創建目錄失敗
	Failed                    = 失敗
	ToMsg                     = {0} 秒後自動返回到主菜單。
	Restart                   = 重啟生效
	AdvOption                 = 可選功能

	StartDown                 = 開始下載
	ConnectTo                 = 連接到
	FileName                  = 檔案名稱
	SaveTo                    = 保存到
	NotAvailable              = 狀態：不可用
	ExistingPacker            = 已有安裝包
	ExistingInstlPacker       = 已有壓縮包
	Unpacking                 = 解壓中
	QucikRun                  = 快速運行：
	WaitDone                  = 等待完成：
	Parameter                 = 參數：
	ErrorDown                 = 下載過程中出現錯誤
	UserCancel                = 用戶已取消操作。

	VerifyNameTips            = 只允許英文字母和數字組合，不能包含其它字符：空格、長度不能大於 260 字符、\\ / : * ? & @ ! "" < > |
	FolderLabel               = 自定義目錄前綴
	NoSetFolderLabel          = 自定義目錄前綴未設置
	ISO9660TipsErrorSpace     = 不能包含：前後空格
	ISO9660TipsErrorOther     = 不能包含：\\ / : * ? & @ ! "" < > |
	ISOLengthError            = 卷標長度不能大於 {0} 字符
	Help                      = 幫助
	WorkDone                  = 完成，按任意鍵返回主界面...
	Short_Cmd                 = 快捷指令
	Options                   = 選項
	LXPsWaitAssign            = 待分配
	Running                   = 运行
	SpecialFunction           = PowerShell 函數
'@