ConvertFrom-StringData -StringData @'
	# fi-FI
	# Finnish (Finland)

	FontsUI                   = Segoe UI
	Mainname                  = Käyttöönottomoottori: Yin sviitti
	Learn                     = Opiskella
	MainHisName               = Bonusratkaisu
	Location                  = Avaa sijainti
	About                     = Noin
	Reset                     = Nollaa
	AddTo                     = Lisää
	Instl                     = Asentaa
	ItInstalled               = Asennettu
	Close                     = Päättäminen
	Auto                      = Automaattinen
	Disable                   = Poista käytöstä
	Enable                    = Ota käyttöön
	Setting                   = Perustaa
	Restore                   = Toipua
	Clean                     = Siivota
	Operable                  = Toimiva
	Inoperable                = Käyttökelvoton
	Optimize                  = Optimointi
	Hide                      = Piilottaa
	Show                      = Show
	Del                       = Poistaa
	Done                      = Valmis
	OK                        = Varma
	Cancel                    = Peruuttaa
	AllSel                    = Valitse kaikki
	AllClear                  = Tyhjentää kaikki
	Refresh                   = Päivitä
	RefreshModules            = Päivitä kaikki moduulit kuumana
	Necessary                 = Olennainen ohjelmisto
	MostUsedSoftware          = Yleisesti käytetty ohjelmisto
	System                    = Järjestelmä
	Service                   = Palvella
	TaskBar                   = Kaikki tehtäväpalkin kuvakkeet
	DeskIcon                  = Työpöydän kuvakkeet
	InstallFonts              = Asenna fontit
	SettingTo                 = Aseta arvoon {0}
	Command                   = Komentorivi
	RuleName                  = Säännön nimi
	Language                  = Kieli
	AvailableLanguages        = Saatavilla olevat kielet
	SwitchLanguage            = Vaihtaa kieltä
	LanguageReset             = Palauta kieliasetukset
	LanguageCode              = Vyöhykemerkki
	LanguageSelRegion         = Valitse maasi tai alueesi
	LanguageRemember          = Muista valittu kieli
	LanguageSearchNo          = Saatavilla olevia kieliä ei löytynyt
	LanguageNoSel             = Valitse alue
	Search                    = Haku
	PleaseChoose              = Ole hyvä ja valitse
	FailedCreateFolder        = Hakemiston luominen epäonnistui
	Failed                    = Epäonnistua
	ToMsg                     = {0} Palaa automaattisesti päävalikkoon sekunnin kuluttua.
	Restart                   = Uudelleenkäynnistys astuu voimaan
	AdvOption                 = Valinnaisia ominaisuuksia

	StartDown                 = Aloita lataaminen
	ConnectTo                 = Yhdistä
	FileName                  = Tiedoston nimi
	SaveTo                    = Tallenna kohteeseen
	NotAvailable              = Tila: Ei saatavilla
	ExistingPacker            = Asennuspaketti on jo olemassa
	ExistingInstlPacker       = Pakattu paketti on jo olemassa
	Unpacking                 = Purkaminen
	QucikRun                  = Pikajuoksu:
	WaitDone                  = Valmistumista odotellessa:
	Parameter                 = Parametri:
	ErrorDown                 = Latauksen aikana tapahtui virhe
	UserCancel                = Käyttäjä on peruuttanut toiminnon.

	VerifyNameTips            = Vain englanninkielisten kirjainten ja numeroiden yhdistelmä on sallittu, eikä muita merkkejä sallita: välilyönnit, pituus ei saa olla yli 16 merkkiä, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Mukautettu hakemiston etuliite
	NoSetFolderLabel          = Mukautetun hakemiston etuliitettä ei ole asetettu
	ISO9660TipsErrorSpace     = Ei voi sisältää alku- ja loppuvälilyöntejä
	ISO9660TipsErrorOther     = Ei voi sisältää: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Volyymitunniste ei voi olla pidempi kuin {0} merkkiä
	Help                      = Auttaa
	WorkDone                  = Valmis, palaa pääliittymään painamalla mitä tahansa näppäintä...
	Short_Cmd                 = Pikanäppäimet
	Options                   = Vaihtoehdot
	LXPsWaitAssign            = Jaetaan
	Running                   = Juosta
	SpecialFunction           = PowerShell toiminnot
'@