ConvertFrom-StringData -StringData @'
	# sk-SK
	# Slovak (Slovakia)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Dashboard
	Learn                           = Štúdium
	Menu                            = Menu
	Short_Cmd                       = Skratkový príkaz
	Shortcut                        = Skratka
	Update                          = Obnoviť
	CUpdate                         = Kumulatívne aktualizácie
	Rebuild                         = Rekonštrukcia
	AddTo                           = Pridať do
	Del                             = Vymazať
	Copy                            = Kopírovať
	Rename                          = Premenovať
	Refresh                         = Osviežiť
	RefreshModules                  = Horúca obnova všetkých modulov
	Done                            = Dokončiť
	OK                              = Jasné
	Cancel                          = Zrušiť
	AllSel                          = Vybrať všetko
	AllClear                        = Vymazať všetko
	Setting                         = Nastaviť
	Change                          = Zmeniť
	Help                            = Pomôcť
	Logging                         = Log
	AvailableLanguages              = Dostupné jazyky
	SwitchLanguage                  = Prepnúť jazyk
	LanguageSelRegion               = Vyberte svoju krajinu alebo región
	LanguageRemember                = Zapamätať si vybraný jazyk
	LanguageSearchNo                = Nenašli sa žiadne dostupné jazyky
	LanguageNoSel                   = Vyberte región
	Search                          = Hľadať
	SearchAllDrives                 = Prehľadať všetky disky
	MountCategory                   = Všetky nájdené a pripojené súbory ISO
	PleaseChoose                    = Vyberte
	Options                         = Možnosti
	Choose                          = Vybrané
	NoChoose                        = Nevybraté
	AdvOption                       = Voliteľné funkcie
	ExcludeItem                     = Vylúčiť podľa pravidla
	DeDuplication                   = Vylúčiť duplikáty
	DeDuplication_Unlock            = Odomknite zakázané duplikáty
	Existed                         = Už existuje
	FailedCreateFolder              = Nepodarilo sa vytvoriť adresár
	FailedCreateFile                = Súbor sa nepodarilo vytvoriť
	ToMsg                           = {0} Po niekoľkých sekundách sa automaticky vráti do hlavnej ponuky.
	OnDemandPlanTask                = Vlastné priraďovanie známych udalostí
	Operable                        = Funkčné
	Inoperable                      = Nefunkčné
	Hide                            = Skryť
	CuringUpdate                    = Solídna aktualizácia
	CuringUpdateTips                = Po potvrdení aktualizácie ju nemožno odinštalovať.
	Healthy                         = Zdravý
	Healthy_Save                    = Keď sa objaví opraviteľné alebo neopraviteľné, neukladajte.
	Repair                          = Oprava
	IsAuto_Repair                   = Povoliť automatickú opravu pri nečinnosti
	IsAuto_Repair_Tips              = Po každom spustení baliaceho skriptu automaticky skontrolujte, či existujú nejaké montážne úlohy. Ak je namontovaný, nevykoná sa žiadna oprava, ak nie je namontovaný, spustí sa automatická oprava.
	Repairable                      = Opraviteľné
	NonRepairable                   = Nie je možné opraviť
	HealthyForceStop                = Počas spracovania udalosti došlo k nezvratnej chybe a udalosť bola násilne ukončená.\n\n   Spôsobuje hlavné problémy: \n\n      1. Fyzický hardvér je poškodený, pevný disk;\n\n      2. Ak používate pamäťový virtuálny disk RAMDISK (vrátane hybridného), skontrolujte fyzickú pamäť;\n\n      3. Overte pôvodný SHA256 MVS (MSDN), zmeňte adresár a skúste to znova. Ak je SHA256 nekonzistentný, stiahnite si ho znova a skúste to znova.\n\n      4. Iné nie sú v tomto príklade uvedené.
	Superseded                      = Vyčistite vymenené
	SupersededTips                  = Zahŕňa zastarané aktualizácie, komponenty atď.
	UnmountFailed                   = Skúsil som niekoľko metód, ale nedá sa nič robiť.
	SaveTo                          = Uložiť do
	WorkDone                        = Dokončené, stlačením ľubovoľného klávesu sa vrátite do hlavného rozhrania...
	UserCanel                       = Používateľ zrušil žiadosť.
	Uping                           = Generovanie
	Exclude_View                    = Zobraziť pravidlá vylúčenia
	User_Interaction                = Interakcia používateľa
	Ok_Go_To                        = K dispozícii pre
	Ok_Go_To_No                     = Nechodím

	Detailed                        = Podrobne
	View                            = Zobraziť
	Detailed_View                   = Zobraziť podrobnosti o vybratom pravidle

	AddEnv                          = Pridajte funkciu smerovania do systémových premenných
	AddEnvTips                      = Po pridaní zadajte Yi v ľubovoľnej relácii PowerShell, aby ste odpovedali, napríklad zadaním "Yi -SIP" spustite zapuzdrenie.

	Unzip_ISO                       = Extrahujte ISO
	Unzip_Search_Type               = Hľadať v adresári ( {0} )
	ISO_Other                       = Ostatné dokumenty
	Unzip_Language                  = Jazykový balík
	Unzip_Fod                       = Balík funkcií
	FileName                        = Názov súboru

	UserCancel                      = Používateľ zrušil operáciu.
	MatchMode                       = Zápas
	Failed                          = Zlyhať
	RandomSelect                    = Náhodne vybrané
	RulePre                         = Prednastavené pravidlá
	RuleOther                       = Iné pravidlá
	RuleCustomize                   = Vlastné pravidlá
	RuleCustomize_Dont              = Nepoužívajte viacúrovňové vlastné pravidlá pre adresáre
	RuleCustomize_Dont_Tips         = Po odstránení starého adresára kliknite na "Overiť pravidlá pomenovania".
	RuleMultistage                  = Viacúrovňové pravidlá adresárov
	RuleMultistageFindFailed        = Nenašli sa žiadne viacúrovňové pravidlá adresára. Kliknutím na mňa vytvoríte šablónu.
	RuleMultistageFindCreateNew     = Vytvorte novú šablónu viacúrovňového pravidla adresára
	RuleMultistageTips              = Automaticky prispôsobiť viacúrovňové pravidlá adresára, pravidlo adresára {0} bolo zakázané.
	RuleCustomizeNot                = Názov rozšírenia (Solutions.Custom.Extension) sa nenašiel, pozrite si dokumentáciu pomocníka.
	RuleCustomizeTips               = Nevytvorilo sa žiadne vlastné pravidlo, pozrite si dokumentáciu pomocníka.
	RuleMatchNoFindFolder           = Nepodarilo sa nájsť zhodu s adresárom, kliknutím na mňa vytvorte adresár.
	RuleNoFindFile                  = Nenašli sa žiadne dostupné súbory, pridajte ich a obnovte.
	RuleFindFolder                  = Adresár sa vyberie automaticky, keď je dostupný
	RuleNameNewChange               = Automatická synchronizácia po aktualizáciách
	RuleNewTempate                  = Vytvorte šablónu
	RuleSkipFolderCheck             = Už nekontroluje, či súbor existuje v adresári a typ súboru
	RuleAuthon                      = Tvorca pravidiel
	RuleGUID                        = Globálny jedinečný identifikátor GUID
	RuleName                        = Názov pravidla
	RuleDescription                 = Popísať
	RuleNameUse                     = Synchronizovať názov pravidla s: {0}
	RuleISO                         = Zodpovedajte pôvodnému inštalačnému balíku ISO
	RuleInBoxApps                   = Kompletná, vopred nakonfigurovaná aplikácia
	RuleFileType                    = Názov balíka
	RuleFileFind                    = Fuzzy názov vyhľadávania
	RuleFindError                   = Našlo sa {0} položiek na spracovanie, kliknutím na "Skontrolovať závislosti" zobrazíte podrobnosti.
	RuleSelectApps                  = Aplikácie vybrané používateľom
	DependencyPackage               = Závislý balík
	RuleDependenciesRequired        = Požadované závislosti
	RuleDependenciesUnselected      = Nevybrané závislosti
	RuleDependenciesNoCheck         = Závislosti sa už nekontrolujú
	RuleDependenciesFix             = Oprava závislostí nie je vybratá
	Extract_Tips                    = Nápoveda\n\n   1. Výsledok po rozbalení jazykového balíka nemožno použiť ako hlavný referenčný objekt;\n\n   2. Použite zoznam komponentov ako hlavný referenčný objekt. Ako vygenerovať:\n\n       Vo Functions vyberte Generovať komponent (získajte balík v nainštalovanom obraze), vyberte Tlačiť alebo Okamžite zobraziť;\n\n   3. Po nainštalovaní jazykového balíka, prosím, vygenerujte správu o komponente, aby ste skontrolovali, či zodpovedá;

	DescendingRuleLang              = Jazykové balíky vyberte v opačnom poradí
	OrderRuleLang                   = Nainštalujte jazykové balíky vo vopred určenom poradí
	OrderRuleLangTips               = Pridajte v poradí: základné, písma, optické rozpoznávanie znakov, rozpoznávanie rukopisu, prevod textu na reč, rozpoznávanie reči, maloobchodné demo skúsenosti, iné
	RuleLanguageTips                = Ilustruj: \n\n   Po použití "Inštalovať jazykové balíky v predurčenom poradí" sa súbory automaticky priradia podľa nejasných názvov v nasledujúcom poradí:\n
	Match_installed_List            = Pri inštalácii jazykového balíka zadajte zástupný znak z nainštalovaného zoznamu
	Match_installed_List_Tips       = Zodpovedá iba pri inštalácii: Základné, Optické rozpoznávanie znakov, Rozpoznávanie rukopisu, Prevod textu na reč, Rozpoznávanie reči.
	RuleLanguageTipsExt             = \n   Ak nepoužívate možnosť "Inštalovať jazykové balíky vo vopred nastavenom poradí": \n   Automaticky vyhľadať všetky súbory v adresári podľa typu súboru a nainštalovať ich.\n\n   Funkcie jazyka a regiónu na vyžiadanie (FOD)\n   https://learn.microsoft.com/sk-sk/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategória
	Basic                           = Základné
	Fonts                           = Písmo
	OCR                             = Optické rozpoznávanie znakov
	Handwriting                     = Rozpoznávanie rukopisu
	TextToSpeech                    = Text na reč
	Speech                          = Rozpoznávanie reči
	Retail                          = Maloobchodné demo skúsenosti
	Features_On_Demand              = Funkcie na vyžiadanie
	RegionSpecific                  = Ďalšie požiadavky špecifické pre región
	UnassignedLangFiles             = Nepriradené rôzne súbory

	ProcessingImage                 = Spracujte obrázok:
	NoInstallImage                  = Neexistuje lokálne
	ConvertChk                      = Skontrolujte súbor
	WindowsFeature                  = Funkcie systému Windows
	Enable                          = Povoliť
	Disable                         = Zakázať
	EnableFeatureTips               = Nápoveda\n\n    1. Zobrazte NetFx3 a TelnetClient ako prednastavené povolené funkčné položky;\n\n    2. Po "namontovaní" možno povoliť ďalšie.
	ViewLanguage                    = Zobrazenie nastavení jazyka snímky
	ImageLanguage                   = Nastavenia jazyka obrázka
	OnlyLangCleanup                 = Čisté komponenty: tag podľa jazyka
	Matched_Component_Names         = Zhodný názov komponentu:
	BootProcess                     = Pri spracovaní {0}.wim
	Sync_Language_To                = Synchronizovať s
	BootSyncToISO                   = Synchronizujte jazykové balíky s inštalátorom
	BootSyncToISOTips               = Nainštalovaný jazykový balík offline obrazu sa synchronizuje s inštalátorom ISO.
	LangIni                         = Obnovte Lang.ini
	LangIniTips                     = Po dokončení synchronizácie je potrebné prebudovať Lang.ini v ISO.
	LangNewAutoSelect               = Automaticky vybrať navrhované položky, keď nastane udalosť
	LangNewAutoSelectTips           = Existujú nové udalosti, vybratá možnosť "Synchronizovať jazykový balík s inštalátorom", "Znovu zostaviť Lang.ini".
	LangNewAutoNoSelect             = Existujú nové udalosti, odporúča sa vybrať "Synchronizovať jazykový balík s inštalátorom" a "Znovu zostaviť Lang.ini".
	LangNewAutoNoNewSelect          = Neexistujú žiadne nové udalosti. Odporúča sa, aby ste nevybrali možnosť "Synchronizovať jazykový balík s inštalátorom" alebo "Znovu zostaviť Lang.ini".
	Drive                           = Riadiť
	ViewDrive                       = Pozrite si nainštalované ovládače
	Editions                        = Verzia obrázka
	Assign_Editions                 = Automaticky distribuujte aplikácie na základe verzií obrázkov

	SelFile                         = Vyberte súbor
	Rebuilding                      = V rekonštrukcii
	RebuildAll                      = Obnoviť všetky
	Export_Image                    = Exportovať
	SelectFromError                 = Omyl
	SelectFileFormatError           = Formát súboru je nesprávny

	SearchDrive                     = Riadené vyhľadávaním
	SearchUpdate                    = Hľadať aktualizácie, zadajte ( {0} ), zdroj:
	SelectFolder                    = Vyberte adresár
	DropFolder                      = Môžete presunúť adresáre do aktuálneho okna
	DropFile                        = Súbory je možné pretiahnuť do aktuálneho okna
	Sparse                          = Zriedkavé
	CRCSHA                          = Skontrolovať
	Alternative                     = Alternatívny názov súboru
	ChangeInstallDisk               = Zmeňte automatický výber disku
	Backup                          = Záloha
	Restore                         = Obnoviť
	Import                          = Importovať

	# View
	ExportToLogs                    = Vytlačte zostavu na prihlásenie
	ExportShow                      = Okamžité zobrazenie prehľadov
	MoreFeature                     = Viac funkcií
	OpenFolder                      = Otvorte adresár
	OpenFile                        = Otvoriť súbor
	Running                         = Behať
	Paste                           = Kopírovať cestu
	Clipboard_Copy                  = Skopírované do schránky
	ViewWIMFileInfo                 = Zobraziť obrázok
	GetInBoxApps                    = InBox Apps: Nainštalované balíky aplikácií
	GetImagePackage                 = Komponenty: Všetky balíky nainštalované v obraze
	ViewMounted                     = Získajte informácie o všetkých pripojených obrázkoch
'@