ConvertFrom-StringData -StringData @'
	# hr-HR
	# Croatian (Croatia)

	UnpackISO                       = Generiraj ISO
	ISOLabel                        = Oznaka volumena je postavljena:
	ISOCustomize                    = ISO naziv oznake volumena
	ISO9660                         = Provjerite pravila imenovanja
	ISO9660Tips                     = Jedinstveni naziv ne može premašiti 260 znakova, naziv ISO volumena ne može premašiti 16 znakova i ne može sadržavati: razmake na početku i na kraju, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Prilagođeno jedinstveno imenovanje
	ISOAddFlagsLang                 = Dodajte višejezične oznake
	ISOAddFlagsLangGet              = Nabavite poznate jezike instalacije
	ISOAddFlagsVer                  = Dodajte oznaku s više verzija
	ISOAddFlagsVerGet               = Dobijte poznatu verziju slike
	ISOAddEICFG                     = Dodajte vrstu verzije
	ISOAddEICFGTips                 = Kad se oslanjamo na EI.cfg, to je komercijalna verzija.
	ISO9660TipsErrorSpace           = Ne može sadržavati: razmake na početku i na kraju
	ISO9660TipsErrorOther           = Ne može sadržavati: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Odaberite vrstu jezika
	SelLabel                        = Kodno ime
	ISOVerLabel                     = Odaberite naziv ISO volumena
	NoSetLabel                      = Prilagođena ISO oznaka volumena nije postavljena
	ISOLengthError                  = Oznaka sveska ne može biti duža od {0} znakova
	RenameFailed                    = Isto kao stari imenik, preimenovanje nije uspjelo
	ISOCreateAfter                  = Što trebate učiniti prije stvaranja ISO-a
	ISOCreateRear                   = Što trebate učiniti nakon izrade ISO-a
	BypassTPM                       = Zaobiđite provjeru instalacije TPM-a
	Disable_BitLocker               = Onemogućite BitLocker šifriranje uređaja tijekom instalacije
	PublicDate                      = Datum izdavanja
	PublicDateGetCurrent            = Sinkroniziraj trenutni datum
	PublicYear                      = Godina
	PublicMonth                     = Mjesec
	PublicYMSorting                 = Sortiraj: Promijeni "mjesec_godina" u "godina_mjesec"
	PublicYMSortingTips             = AB: Ne dodavaj podcrtu _ kada koristiš brojeve.
	PublicYMUseShortNames           = Koristite kratka imena
	PublicYMUseNumbers              = Koristite brojeve
	ISOCreateFailed                 = Stvaranje nije uspjelo, direktorij nije čitljiv niti pisan.
	ISORefreshAuto                  = Svaki put osvježite ISO oznake
	ISOSaveTo                       = ISO zadana lokacija za spremanje
	ISOSaveSameGlobal               = Koristite globalnu ISO zadanu lokaciju za spremanje
	ISOSaveSync                     = Automatski sinkronizirajte novu lokaciju nakon odabira diska za pretraživanje izvora slike
	ISOSaveSame                     = Pretraživanje putanje diska pomoću izvora slike
	ISOFolderWrite                  = Provjerite je li direktorij čitljiv i pisan
	SelectAutoAvailable             = Prilikom automatskog odabira dostupnog diska
	SelectCheckAvailable            = Provjerite minimalni raspoloživi preostali prostor
	ISOStructure                    = Nova struktura imenika
	ISOOSLevel                      = Dodajte vrstu instalacije
	ISOUniqueNameDirectory          = Dodajte direktorij s jedinstvenim nazivom
	NextDoOperate                   = Nemojte stvarati ISO
	SelCreateISO                    = Generirajte ISO, izvršite na zahtjev
	Reconstruction                  = Ponovno izgradite {0}.wim s maksimalnom kompresijom
	Reconstruction_Tips_Select      = Prije ponovne izgradnje, izvršit će se samo ako se ne učita. Prisilno će se omogućiti spremanje i zatim demontirati montirana datoteka.
	ReconstructionTips              = Preko 520 MB, preporučuje se obnova
	CreateASC                       = Dodajte PGP potpis u ISO
	NoPGPKey                        = U PGP-u ne postoji upotrebljiv privatni ključ.
	CreateASCPwd                    = Lozinka certifikata
	PasswordRenter                  = Ponovno unesite lozinku
	ShowPassword                    = Prikaži lozinku
	NewPasswordSome                 = Lozinka se ne podudara.
	PwdPermanent                    = Trajna pohrana
	PwdDecfailed                    = Dešifriranje nije uspjelo
	CreateASCAuthor                 = Potpisnik
	CreateASCAuthorTips             = Nema odabranih potpisnika.
	ISO_Sparse_Rename               = Dodajte hash ekstenziji naziva datoteke
	GenerateRandom                  = Generiraj nasumične brojeve
	RandomNumberReset               = Regenerirati
'@