ConvertFrom-StringData -StringData @'
	# sv-SE
	# Swedish (Sweden)

	IsCreate                        = Skapa
	Solution                        = Lösning
	EnabledSoftwarePacker           = Samling
	EnabledUnattend                 = Bör svara i förväg
	EnabledEnglish                  = Implementeringsmotor
	UnattendSelectVer               = Välj "Svar på" lösningsspråk
	UnattendLangPack                = Välj språkpaket "Lösning".
	UnattendSelectSingleInstl       = Flerspråkig, valfri under installation
	UnattendSelectMulti             = Flerspråkig
	UnattendSelectDisk              = Välj lösningen Autounattend.xml
	UnattendSelectSemi              = Halvautomatisk är giltig för alla installationsmetoder
	UnattendSelectUefi              = UEFI installeras automatiskt och måste specificeras
	UnattendSelectLegacy            = Legacy installeras automatiskt och måste specificeras
	NeedSpecified                   = Välj vad som behöver specificeras:
	OOBESetupOS                     = Installationsgränssnitt
	OOBEProductKey                  = Produktnyckel
	OOBEOSImage                     = Välj det operativsystem som ska installeras
	OOBEEula                        = Acceptera licensvillkor
	OOBEDoNotServerManager          = Serverhanteraren startar inte automatiskt vid inloggning
	OOBEIE                          = Internet Explorer förbättrad säkerhetskonfiguration
	OOBEIEAdmin                     = Stäng "Administratör"
	OObeIEUser                      = Stäng "Användare"

	OOBE_Init_User                  = Första användare under uppackningsupplevelsen
	OOBE_init_Create                = Skapa anpassade användare
	OOBE_init_Specified             = Ange användare
	OOBE_Init_Autologin             = Automatisk inloggning

	InstlMode                       = Installationsmetod
	Business                        = Business version
	BusinessTips                    = Beroende på EI.cfg måste indexnumret anges för automatisk installation.
	Consumer                        = Konsumentversion
	ConsumerTips                    = Den förlitar sig inte på EI.cfg. Serienumret måste anges för automatisk installation.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [montera till]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Lägg till på systemdiskens hemkatalognamn
	VerifyNameUse                   = Kontrollera att katalognamnet inte kan innehålla
	VerifyNameTips                  = Endast en kombination av engelska bokstäver och siffror är tillåten och får inte innehålla: mellanslag, längden får inte vara större än 260 tecken, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Verifieringen misslyckades. Ange rätt nummer.
	VerifyNameSync                  = Ange katalognamn som primärt användarnamn
	VerifyNameSyncTips              = Administratör används inte längre.
	ManualKey                       = Välj eller ange din produktnyckel manuellt
	ManualKeyTips                   = Ange en giltig produktnyckel Om den valda regionen inte är tillgänglig, gå till Microsofts officiella webbplats för att kontrollera.
	ManualKeyError                  = Produktnyckeln du angav är ogiltig.
	KMSLink1                        = KMS klientinställningsnyckel
	KMSUnlock                       = Visa alla kända KMS-serienummer
	KMSSelect                       = Välj VOL serienummer
	KMSKey                          = Serienummer
	KMSKeySelect                    = Ändra produktens serienummer
	ClearOld                        = Rensa upp gamla filer
	SolutionsSkip                   = Hoppa över att skapa lösning
	SolutionsTo                     = Lägg till "lösning" till:
	SolutionsToMount                = Monteras eller läggs till i kö
	SolutionsToError                = Vissa funktioner har inaktiverats Om du behöver tvinga dem att använda, klicka på knappen "Lås upp".\n\n
	UnlockBoot                      = Låsa upp
	SolutionsToSources              = Hemkatalog, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Välj versionen "Deployment Engine".
	SolutionsEngineRegionaUTF8      = Beta: Globalt språkstöd med Unicode UTF-8
	SolutionsEngineRegionaUTF8Tips  = Det verkar som att det kan orsaka nya problem efter att ha öppnat det. Rekommenderas inte.
	SolutionsEngineRegionaling      = Ändra till ny lokal:
	SolutionsEngineRegionalingTips  = Ändra systemspråket, vilket påverkar alla användarkonton på datorn.
	SolutionsEngineRegional         = Ändra systemspråk
	SolutionsEngineRegionalTips     = Global standard: {0}, ändrad till: {1}
	SolutionsEngineCopyPublic       = Kopiera offentliga {0} till implementering
	SolutionsEngineCopyOpen         = Bläddra i den offentliga lagringsplatsen {0}
	EnglineDoneReboot               = Starta om datorn
	SolutionsTipsArm64              = Arm64-paketet är att föredra, och du väljer i ordning: x64, x86.
	SolutionsTipsAMD64              = Föredrar x64-paket, i ordning: x86.
	SolutionsTipsX86                = Endast x86-paket läggs till.
	SolutionsReport                 = Generera rapport före implementering
	SolutionsDeployOfficeInstall    = Distribuera installationspaketet för Microsoft Office
	SolutionsDeployOfficeChange     = Ändra distributionskonfigurationen
	SolutionsDeployOfficePre        = Förinstallerad paketversion
	SolutionsDeployOfficeNoSelect   = Inget Office-förinstallationspaket valt
	SolutionsDeployOfficeVersion    = {0} version
	SolutionsDeployOfficeOnly       = Behåll angivna språkpaket
	SolutionsDeployOfficeSync       = Bevara språksynkronisering till distributionskonfiguration
	SolutionsDeployOfficeSyncTips   = Efter synkronisering kan installationsskriptet inte avgöra vilket språk som önskas.
	DeploySyncMainLanguage          = Synkronisera med huvudspråket
	SolutionsDeployOfficeTo         = Distribuera installationspaketet till
	SolutionsDeployOfficeToPublic   = Offentligt skrivbord
	DeployPackage                   = Distribuera ett anpassat samlingspaket
	DeployPackageSelect             = Välj ett förinsamlingspaket
	DeployPackageTo                 = Distribuera förinsamlingspaketet till
	DeployPackageToRoot             = Systemdisk:\\Package
	DeployPackageToSolutions        = I lösningens hemkatalog
	DeployTimeZone                  = Tidszon
	DeployTimeZoneChange            = Ändra tidszon
	DeployTimeZoneChangeTips        = Ställ in standardtidområdet där försvar ska besvaras, efter språkområde.

	Deploy_Tags                     = Implementeringstagg
	FirstExpProcess                 = Förstagångserfarenhet, under implementeringsförutsättningar:
	FirstExpProcessTips             = När du har slutfört förutsättningarna startar du om datorn för att lösa problemet med att kräva en omstart för att träda i kraft.
	FirstExpFinish                  = Första gången erfarenhet, efter att ha genomfört förkunskaper
	FirstExpSyncMark                = Tillåt global sökning och synkronisering av implementeringstaggar
	FirstExpUpdate                  = Tillåt automatiska uppdateringar
	FirstExpDefender                = Lägg till hemkatalog till Försvara uteslutna kataloger
	FirstExpSyncLabel               = Systemdiskvolymetikett: Hemkatalognamnet är detsamma
	MultipleLanguages               = När du stöter på flera språk:
	NetworkLocationWizard           = Nätverksplatsguide
	PreAppxCleanup                  = Blockera Appx-rensningsunderhållsuppgifter
	LanguageComponents              = Förhindra rensning av oanvända on-demand-funktionsspråkpaket
	PreventCleaningUnusedLP         = Förhindra rengöring av oanvända språkpaket
	FirstExpContextCustomize        = Lägg till en personlig "sammanhangsmeny"
	FirstExpContextCustomizeShift   = Håll ned Skift-tangenten och högerklicka

	FirstExpFinishTips              = Det finns inga viktiga händelser efter att distributionen är klar. Det rekommenderas att du avbryter.
	FirstExpFinishPopup             = Pop up huvudgränssnittet för distributionsmotorn
	FirstExpFinishOnDemand          = Tillåt första förhandsgranskning, som planerat
	SolutionsEngineRestricted       = Återställ Powershell-exekveringspolicy: begränsad
	EnglineDoneClearFull            = Ta bort hela lösningen
	EnglineDoneClear                = Ta bort distributionsmotorn och behåll de andra

	Unattend_Auto_Fix_Next          = Nästa gång du stöter på det, välj automatiskt de nödvändiga objekten för att automatiskt fixa det.
	Unattend_Auto_Fix               = Reparera automatiskt när förutsättningar inte är valda
	Unattend_Auto_Fix_Tips          = När du lägger till driftsättningsmotorn och inte väljer det första körkommandot, repareras och väljs det automatiskt: Powershell-exekveringspolicy: kör driftsättningsmotorn utan några begränsningar.
	Unattend_Version_Tips           = Inkludera endast valfritt, använd standard för att stödja ARM64, x64, x86.
	First_Run_Commmand              = Kommandon att köra när du distribuerar för första gången
	First_Run_Commmand_Setting      = Välj kommandot som ska köras
	Command_Not_Class               = Kategoriseras inte längre automatiskt vid filtrering
	Command_WinSetup                = Windows Installera
	Command_WinPE                   = Windows PE
	Command_Tips                    = Vänligen tilldela First Run App till: Windows Installation, Windows PE\n\nObservera att när en distributionsmotor läggs till måste du kontrollera följande när du körs för första gången: Powershell Execution Policy: Begränsad, tillåt att skript för distributionsmotorn körs.
	Waring_Not_Select_Command       = När du lägger till en distributionsmotor valdes inte Powershell-exekveringspolicyn: Ställ inte in några begränsningar och låt implementeringsmotorns skript köras. Välj det och försök igen, eller klicka på "Snabbkorrigering är inte vald".
	Quic_Fix_Not_Select_Command     = Quick fix inte alternativ

	PowerShell_Unrestricted         = Powershell-exekveringspolicy: inga begränsningar
	Allow_Running_Deploy_Engine     = Tillåt driftsättningsmotorskript att köras
	Bypass_TPM                      = Förbigå TPM-kontroller under installationen
'@