ConvertFrom-StringData -StringData @'
	# pl-PL
	# Polish (Poland)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Panel
	Learn                           = Badanie
	Menu                            = Menu
	Short_Cmd                       = Polecenie skrótu
	Shortcut                        = Skrót
	Update                          = Odnowić
	CUpdate                         = Aktualizacje zbiorcze
	Rebuild                         = Rekonstrukcja
	AddTo                           = Dodaj do
	Del                             = Usuwać
	Copy                            = Kopia
	Rename                          = Przemianować
	Refresh                         = Odświeżać
	RefreshModules                  = Gorące odświeżenie wszystkich modułów
	Done                            = Skończyć
	OK                              = Jasne
	Cancel                          = Anulować
	AllSel                          = Zaznacz wszystko
	AllClear                        = Wyczyść wszystko
	Setting                         = Organizować coś
	Change                          = Zmiana
	Help                            = Pomoc
	Logging                         = Zapisz dziennik w
	AvailableLanguages              = Dostępne języki
	SwitchLanguage                  = Zmień język
	LanguageSelRegion               = Wybierz swój kraj lub region
	LanguageRemember                = Zapamiętaj wybrany język
	LanguageSearchNo                = Nie znaleziono dostępnych języków
	LanguageNoPack                  = Jeśli lokalnie nie ma pakietu językowego, zostanie on zamknięty automatycznie.
	LanguageNoSel                   = Wybierz region
	Search                          = Szukaj
	PleaseChoose                    = Proszę wybrać
	Options                         = Opcje
	Choose                          = Wybrany
	NoChoose                        = Nie wybrano
	AdvOption                       = Funkcje opcjonalne
	ExcludeItem                     = Wyklucz według reguły
	DeDuplication                   = Wyklucz duplikaty
	DeDuplication_Unlock            = Odblokuj wyłączone duplikaty
	Existed                         = Już istnieje
	FailedCreateFolder              = Nie udało się utworzyć katalogu
	FailedCreateFile                = Nie udało się utworzyć pliku
	ToMsg                           = {0} Automatycznie powróć do menu głównego po sekundach.
	OnDemandPlanTask                = Niestandardowe przypisanie znanych zdarzeń
	Operable                        = Wykonalny
	Inoperable                      = Nieoperacyjny
	Hide                            = Ukrywać
	CuringUpdate                    = Solidna aktualizacja
	CuringUpdateTips                = Po utrwaleniu aktualizacji nie można jej odinstalować.
	Healthy                         = Zdrowy
	HealthyTips                     = Szczególnie ważne jest sprawdzenie stanu technicznego, gdy pojawi się komunikat "naprawialny" lub "nienaprawialny": Podczas procesu konwersji ESD pojawia się komunikat o błędzie 13, a dane są nieprawidłowe;
	Healthy_Save                    = Gdy pojawi się informacja, że można ją naprawić lub nie można jej naprawić, nie zapisuj.
	Repair                          = Naprawa
	IsAuto_Repair                   = "Zezwalaj na automatyczną naprawę w stanie bezczynności
	IsAuto_Repair_Tips              = "Automatycznie sprawdzaj, czy po każdym uruchomieniu skryptu pakującego są jakieś zadania montowania. Jeśli jest zamontowany, żadna naprawa nie zostanie wykonana; jeśli nie zostanie zamontowany, zostanie uruchomiona automatyczna naprawa.
	Repairable                      = Możliwość naprawy
	NonRepairable                   = Nie do naprawy
	HealthyForceStop                = Podczas przetwarzania zdarzenia napotkano nieodwracalny błąd i zdarzenie zostało wymuszone. \n\n   Powoduje główne problemy: \n\n      1. Uszkodzony jest sprzęt fizyczny, dysk twardy; \n\n      2. Jeżeli korzystasz z dysku wirtualnego z pamięcią RAMDISK (w tym hybrydową), sprawdź pamięć fizyczną;\n\n      3. Sprawdź oryginalny SHA256 MVS (MSDN). Jeśli jest spójny, zmień katalog i spróbuj ponownie. Jeśli SHA256 jest niespójny, pobierz go ponownie i spróbuj ponownie.\n\n      4. Inne nie są wymienione w tym przykładzie.
	Superseded                      = Wyczyść wymienione
	SupersededTips                  = Zawiera nieaktualne aktualizacje, komponenty itp.
	UnmountFailed                   = Próbowałem kilku metod, ale nic nie da się zrobić. Mogę tylko zakończyć. Chciałbym cię zobaczyć następnym razem.
	SaveTo                          = Zapisz w
	WorkDone                        = Zakończono, naciśnij dowolny klawisz, aby powrócić do głównego interfejsu...
	UserCanel                       = Użytkownik anulował żądanie.
	Uping                           = Generowanie
	Exclude_View                    = Zobacz reguły wykluczeń
	User_Interaction                = Interakcja użytkownika
	Ok_Go_To                        = Dostępne dla
	Ok_Go_To_No                     = Nie idę

	Detailed                        = Szczegółowy
	Detailed_View                   = Wyświetl szczegóły wybranej reguły

	AddEnv                          = Dodaj funkcję routingu do zmiennych systemowych
	AddEnvTips                      = Po dodaniu wpisz Yi w dowolnej sesji PowerShell, aby odpowiedzieć. Na przykład wpisz "Yi -SIP", aby uruchomić enkapsulację.

	Unzip_ISO                       = Wyodrębnij ISO
	Unzip_Search_Type               = Przeszukaj katalog ( {0} )
	ISO_Other                       = Inne dokumenty
	Unzip_Language                  = Pakiet językowy
	Unzip_Fod                       = Pakiet funkcji
	FileName                        = Nazwa pliku

	UserCancel                      = Użytkownik anulował operację.
	MatchMode                       = Mecz
	Failed                          = Ponieść porażkę
	RandomSelect                    = Wybrane losowo
	RulePre                         = Wstępnie ustawione zasady
	RuleOther                       = Inne zasady
	RuleCustomize                   = Niestandardowe zasady
	RuleCustomize_Dont              = Nie używaj niestandardowych reguł katalogów wielopoziomowych
	RuleCustomize_Dont_Tips         = Po usunięciu starego katalogu kliknij "Sprawdź reguły nazewnictwa".
	RuleMultistage                  = Reguły katalogów wielopoziomowych
	RuleMultistageFindFailed        = Nie znaleziono reguł katalogów wielopoziomowych. Kliknij mnie, aby utworzyć szablon.
	RuleMultistageFindCreateNew     = Utwórz nowy szablon reguły katalogu wielopoziomowego
	RuleMultistageTips              = Automatycznie dostosowuj wielopoziomowe reguły katalogów, reguła katalogu {0} została wyłączona.
	RuleCustomizeNot                = Nie znaleziono nazwy rozszerzenia (Solutions.Custom.Extension). Zapoznaj się z dokumentacją pomocy.
	RuleCustomizeTips               = Nie utworzono żadnej niestandardowej reguły. Zapoznaj się z dokumentacją pomocy.
	RuleMatchNoFindFolder           = Nie udało się dopasować katalogu. Kliknij mnie, aby utworzyć katalog.
	RuleNoFindFile                  = Nie znaleziono dostępnych plików. Dodaj i odśwież.
	RuleFindFolder                  = Katalog wybierany automatycznie, jeśli jest dostępny
	RuleNameNewChange               = Automatycznie synchronizuj po aktualizacjach
	RuleNewTempate                  = Utwórz szablon
	RuleSkipFolderCheck             = Nie sprawdza już, czy plik istnieje w katalogu i typie pliku
	RuleAuthon                      = Twórca reguł
	RuleGUID                        = GUID globalnie unikalny identyfikator
	RuleName                        = Nazwa reguły
	RuleDescription                 = Opisać
	RuleNameUse                     = Zsynchronizuj nazwę reguły z: {0}
	RuleISO                         = Dopasuj oryginalny pakiet instalacyjny ISO
	RuleInBoxApps                   = Kompletna, wstępnie skonfigurowana aplikacja
	RuleFileType                    = Nazwa pakietu
	RuleFileFind                    = Rozmyta nazwa wyszukiwania
	RuleFindError                   = Znaleziono {0} elementów do przetworzenia. Kliknij "Sprawdź zależności", aby wyświetlić szczegóły.
	RuleSelectApps                  = Aplikacje wybrane przez użytkownika
	DependencyPackage               = Pakiet zależności
	RuleDependenciesRequired        = Wymagane zależności
	RuleDependenciesUnselected      = Niewybrane zależności
	RuleDependenciesNoCheck         = Zależności nie są już sprawdzane
	RuleDependenciesFix             = Napraw zależności, które nie zostały wybrane
	Extract_Tips                    = Wskazówka\n\n   1. Wynik po wyodrębnieniu pakietu językowego nie może być użyty jako główny obiekt odniesienia;\n\n   2. Użyj listy komponentów jako głównego obiektu referencyjnego. Jak wygenerować: \n\n       W obszarze Funkcje wybierz opcję Generuj komponent (pobierz pakiet z zainstalowanego obrazu), wybierz opcję Drukuj lub Wyświetl natychmiast;\n\n   3. Po zainstalowaniu pakietu językowego wygeneruj ponownie raport komponentów, aby sprawdzić, czy jest odpowiedni;

	DescendingRuleLang              = Usuń pakiety językowe w odwrotnej kolejności
	OrderRuleLang                   = Zainstaluj pakiety językowe w ustalonej kolejności
	OrderRuleLangTips               = Dodaj w kolejności: Podstawowe, Czcionki, Optyczne rozpoznawanie znaków, Rozpoznawanie pisma ręcznego, Zamiana tekstu na mowę, Rozpoznawanie mowy, Wersja demonstracyjna w handlu detalicznym, Inne
	RuleLanguageTips                = Zilustrować:\n\n   Po użyciu opcji "Zainstaluj pakiety językowe w ustalonej kolejności" pliki są automatycznie dopasowywane według rozmytych nazw w następującej kolejności:\n
	Match_installed_List            = Instalując pakiet językowy, zaznacz go symbolem wieloznacznym na liście zainstalowanych pakietów
	Match_installed_List_Tips       = Pasuje tylko po zainstalowaniu: podstawowe, optyczne rozpoznawanie znaków, rozpoznawanie pisma ręcznego, zamiana tekstu na mowę, rozpoznawanie mowy.
	RuleLanguageTipsExt             = \n   Jeśli nie używasz opcji "Zainstaluj pakiety językowe w ustalonej kolejności":\n   Automatycznie przeszukaj wszystkie pliki w katalogu według typu pliku i zainstaluj je.\n\n   Funkcje na żądanie dotyczące języka i regionu (FOD)\n   https://learn.microsoft.com/pl-pl/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategoria
	Basic                           = Podstawowy
	Fonts                           = Chrzcielnica
	OCR                             = Optyczne rozpoznawanie znaków
	Handwriting                     = Rozpoznawanie pisma ręcznego
	TextToSpeech                    = Tekstu na mowę
	Speech                          = Rozpoznawanie mowy
	Retail                          = Doświadczenie w wersji demonstracyjnej w handlu detalicznym
	Features_On_Demand              = Funkcje na żądanie
	RegionSpecific                  = Inne wymagania specyficzne dla regionu
	UnassignedLangFiles             = Nieprzypisane różne pliki

	ProcessingImage                 = Przetwórz obraz:
	NoInstallImage                  = Nie istnieje lokalnie
	ConvertChk                      = Sprawdź plik
	WindowsFeature                  = Funkcje systemu Windows
	Enable                          = Włączać
	Disable                         = Wyłączyć
	EnableFeatureTips               = Wskazówka\n\n    1. Wyświetl NetFx3 i TelnetClient jako wstępnie włączone elementy funkcji;\n\n    2. Po "zamontowaniu" można włączyć więcej.
	ViewLanguage                    = Wyświetl ustawienia języka obrazu
	ImageLanguage                   = Ustawienia języka obrazu
	OnlyLangCleanup                 = Wyczyść komponenty: oznacz według języka
	Matched_Component_Names         = Dopasowana nazwa komponentu:
	BootProcess                     = Podczas przetwarzania pliku {0}.wim
	Extract_Rule_Only_And_Full      = Wyodrębnij tylko wybrane języki
	Sync_Language_To                = Synchronizuj z
	BootSyncToISO                   = Zsynchronizuj pakiety językowe z instalatorem
	BootSyncToISOTips               = Zainstalowany pakiet językowy obrazu offline jest synchronizowany z instalatorem ISO.
	Setup_Fix_Missing               = Automatycznie napraw brakujące elementy instalatora
	Setup_Fix_Missing_Tips          = Jeśli w programie instalacyjnym brakuje plików arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui, otwórz "Wyodrębnij", wybierz "Reguły" i kliknij "Wyodrębnij brakujące elementy instalatora".
	Setup_Fix_Missing_Extract       = Wyodrębnij brakujące elementy instalatora
	Setup_Fix_Missing_Extract_Tips  = Wyodrębnij brakujące elementy instalatora ze wszystkich lokalnych pakietów językowych: arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui.
	LangIni                         = Zregeneruj plik Lang.ini
	LangIniTips                     = Po zakończeniu synchronizacji należy odbudować plik Lang.ini w ISO.
	LangNewAutoSelect               = Automatycznie wybieraj sugerowane elementy po wystąpieniu zdarzenia
	LangNewAutoSelectTips           = Pojawiły się nowe zdarzenia, wybrano opcję "Synchronizuj pakiet językowy z instalatorem", "Przebuduj Lang.ini".
	LangNewAutoNoSelect             = Pojawiły się nowe zdarzenia, zaleca się wybranie opcji "Synchronizuj pakiet językowy z instalatorem" i "Odbuduj Lang.ini".
	LangNewAutoNoNewSelect          = Nie ma nowych zdarzeń. Zaleca się, aby nie wybierać opcji "Synchronizuj pakiet językowy z instalatorem" ani "Przebuduj plik Lang.ini".
	Drive                           = Prowadzić
	ViewDrive                       = Wyświetl zainstalowane sterowniki
	EditionsProductKey              = Klucz produktu
	Editions                        = Wersja obrazu
	Assign_Editions                 = Automatycznie dystrybuuj aplikacje na podstawie wersji obrazu
	EditionsChangeTips              = Uwaga, proszę zrozumieć przed zmianą wersji obrazu:\n\nMicrosoft Umowa o świadczenie usług\nhttps://www.microsoft.com/pl-pl/servicesagreement/default.aspx\n\nPrzegląd języka\nhttps://learn.microsoft.com/pl-pl/windows-hardware/manufacture/desktop/languages-overview\n\nNie wolno tworzyć wersji: \n   1. Specyficzny dla kraju\n       ProfessionalCountrySpecific\n\n   2. Wersja domowa specyficzna dla regionu\n       ProfessionalSingleLanguage\n\nProsimy o ścisłe przestrzeganie tych zasad, ponieważ ich naruszenie może skutkować karą karną.\n\nJeśli nalegasz na konwersję, kliknij, aby zaakceptować ostrzeżenie i kliknij "Odblokuj wersję z ukrytym obrazem".
	EditionsChangeHide              = Odblokuj ukryte wersje obrazów
	EditionsChangeAccect            = Zapoznałem się z ostrzeżeniem i ponoszę odpowiedzialność za odpowiednie przepisy zawarte w ostrzeżeniu

	SelFile                         = Wybierz plik
	Rebuilding                      = W trakcie rekonstrukcji
	RebuildAll                      = Odbuduj wszystko
	Export_Image                    = Eksport
	SelectFromError                 = Błąd
	SelectFileFormatError           = Format pliku jest nieprawidłowy

	SearchDrive                     = Napędzany wyszukiwaniem
	SearchUpdate                    = Wyszukaj aktualizacje, wpisz ( {0} ), źródło:
	SelectFolder                    = Wybierz katalog
	DropFolder                      = Może przeciągać katalogi do bieżącego okna
	DropFile                        = Pliki można przeciągać do bieżącego okna
	Sparse                          = Rzadki
	CRCSHA                          = Sprawdzać
	Alternative                     = Alternatywna nazwa pliku
	ChangeInstallDisk               = Zmień automatyczny wybór dysku

	# View
	ExportToLogs                    = Wydrukuj raport do dziennika
	ExportShow                      = Natychmiast wyświetlaj raporty
	MoreFeature                     = Więcej funkcji
	OpenFolder                      = Otwórz katalog
	OpenFile                        = Otwórz plik
	Running                         = Uruchomić
	Paste                           = Skopiuj ścieżkę
	Clipboard_Copy                  = Skopiowano do schowka
	ViewWIMFileInfo                 = Zobacz obraz
	GetInBoxApps                    = InBox Apps: zainstalowane pakiety aplikacji
	GetImagePackage                 = Komponenty: Wszystkie pakiety zainstalowane w obrazie
	ViewMounted                     = Uzyskaj informacje o wszystkich zamontowanych obrazach
'@