ConvertFrom-StringData -StringData @'
	# lt-LT
	# Lithuanian (Lithuania)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Prietaisų skydelis
	Learn                           = Studijuoti
	Menu                            = Meniu
	Short_Cmd                       = Sparčiųjų klavišų komanda
	Shortcut                        = Snelkoppeling
	Update                          = Atnaujinti
	CUpdate                         = Kaupiamieji atnaujinimai
	Rebuild                         = Rekonstrukcija
	AddTo                           = Pridėti prie
	Del                             = Ištrinti
	Copy                            = Kopija
	Rename                          = Pervardyti
	Refresh                         = Atnaujinti
	RefreshModules                  = Karštas visų modulių atnaujinimas
	Done                            = Baigti
	OK                              = Žinoma
	Cancel                          = Atšaukti
	AllSel                          = Pasirinkite viską
	AllClear                        = Išvalyti viską
	Setting                         = Nustatyti
	Change                          = Keisti
	Help                            = Padėti
	Logging                         = Žurnalas
	AvailableLanguages              = Galimos kalbos
	SwitchLanguage                  = Pakeisti kalbą
	LanguageSelRegion               = Pasirinkite savo šalį arba regioną
	LanguageRemember                = Prisiminti pasirinktą kalbą
	LanguageSearchNo                = Galimų kalbų nerasta
	LanguageNoPack                  = Jei vietoje kalbos paketo nėra, jis automatiškai išeis.
	LanguageNoSel                   = Pasirinkite regioną
	Search                          = Paieška
	PleaseChoose                    = Prašome pasirinkti
	Options                         = Parinktys
	Choose                          = Pasirinkta
	NoChoose                        = Nepasirinkta
	AdvOption                       = Pasirenkamos funkcijos
	ExcludeItem                     = Išskirti pagal taisyklę
	DeDuplication                   = Išskirkite dublikatus
	DeDuplication_Unlock            = Atrakinkite išjungtus dublikatus
	Existed                         = Jau egzistuoja
	FailedCreateFolder              = Nepavyko sukurti katalogo
	FailedCreateFile                = Nepavyko sukurti failo
	ToMsg                           = {0} Po sekundžių automatiškai grįžkite į pagrindinį meniu.
	OnDemandPlanTask                = Pasirinktinis žinomų įvykių priskyrimas
	Operable                        = Veikiantis
	Inoperable                      = Neveikiantis
	Hide                            = Paslėpti
	CuringUpdate                    = Tvarkingas atnaujinimas
	CuringUpdateTips                = Patvirtinus naujinimą, jo pašalinti negalima.
	Healthy                         = Sveikas
	HealthyTips                     = Ypač svarbu patikrinti sveikatos būklę, kai pasirodo "pataisoma arba "nepataisoma: ESD konvertavimo metu pateikiama klaida 13 ir pranešama apie klaidą diegiant sistemą.
	Healthy_Save                    = Kai pasirodo taisomas arba nepataisomas, netaupykite.
	Repair                          = Remontas
	IsAuto_Repair                   = Leisti automatinį remontą, kai jis veikia tuščiąja eiga
	IsAuto_Repair_Tips              = Po kiekvieno pakavimo scenarijaus vykdymo automatiškai patikrinkite, ar nėra jokių montavimo užduočių. Jei jis sumontuotas, remontas nebus atliekamas, jei jis nėra sumontuotas, bus paleistas automatinis remontas.
	Repairable                      = Taisomas
	NonRepairable                   = Neremontuojamas
	HealthyForceStop                = Apdorojant įvykį, įvyko negrįžtama klaida ir įvykis buvo priverstinai nutrauktas.\n\n   Sukelia pagrindines problemas:\n\n      1. Sugadinta fizinė įranga, kietasis diskas;\n\n      2. Jei naudojate RAMDISK atminties virtualųjį diską (įskaitant hibridinį), patikrinkite fizinę atmintį;\n\n      3. Patikrinkite originalų MVS (MSDN) SHA256, pakeiskite katalogą ir bandykite dar kartą.\n\n      4. Kiti šiame pavyzdyje nenurodyti.
	Superseded                      = Išvalykite pakeistą
	SupersededTips                  = Apima pasenusius naujinimus, komponentus ir kt.
	UnmountFailed                   = Išbandžiau kelis būdus, bet nieko negaliu padaryti, tik norėčiau pasimatyti kitą kartą.
	SaveTo                          = Išsaugoti į
	WorkDone                        = Baigta, paspauskite bet kurį klavišą, kad grįžtumėte į pagrindinę sąsają...
	UserCanel                       = Vartotojas atšaukė užklausą.
	Uping                           = Generavimas
	Exclude_View                    = Peržiūrėkite pašalinimo taisykles
	User_Interaction                = Vartotojo sąveika
	Ok_Go_To                        = Galima
	Ok_Go_To_No                     = Nevažiuoja

	Detailed                        = Išsamiai
	Detailed_View                   = Peržiūrėkite pasirinktos taisyklės informaciją

	AddEnv                          = Pridėkite maršruto parinkimo funkciją prie sistemos kintamųjų
	AddEnvTips                      = Pridėję įveskite Yi bet kurioje "PowerShell" sesijoje, kad atsakytumėte. Pavyzdžiui, įveskite "Yi -SIP", kad paleistumėte inkapsuliavimą.

	Unzip_ISO                       = Ištraukite ISO
	Unzip_Search_Type               = Ieškoti kataloge ( {0} )
	ISO_Other                       = Kiti dokumentai
	Unzip_Language                  = Kalbos paketas
	Unzip_Fod                       = Funkcijų paketas
	FileName                        = Failo pavadinimas

	UserCancel                      = Vartotojas atšaukė operaciją.
	MatchMode                       = Rungtynės
	Failed                          = Nepavyks
	RandomSelect                    = Atsitiktinai parinktas
	RulePre                         = Iš anksto nustatytos taisyklės
	RuleOther                       = Kitos taisyklės
	RuleCustomize                   = Individualios taisyklės
	RuleCustomize_Dont              = Nenaudokite kelių lygių katalogų tinkintų taisyklių
	RuleCustomize_Dont_Tips         = Ištrynę senąjį katalogą, spustelėkite "Patvirtinti pavadinimo taisykles".
	RuleMultistage                  = Kelių lygių katalogų taisyklės
	RuleMultistageFindFailed        = Nerasta kelių lygių katalogo taisyklių, spustelėkite mane, kad sukurtumėte šabloną.
	RuleMultistageFindCreateNew     = Sukurkite naują kelių lygių katalogo taisyklės šabloną
	RuleMultistageTips              = Automatiškai pritaikyti kelių lygių katalogų taisykles, {0} katalogo taisyklė išjungta.
	RuleCustomizeNot                = Plėtinio pavadinimas (Solutions.Custom.Extension) nerastas, žr. pagalbos dokumentaciją.
	RuleCustomizeTips               = Jokia pasirinktinė taisyklė nesukurta, žr. pagalbos dokumentaciją.
	RuleMatchNoFindFolder           = Nepavyko suderinti katalogo, spustelėkite mane, kad sukurtumėte katalogą.
	RuleNoFindFile                  = Nerasta galimų failų, pridėkite ir atnaujinkite.
	RuleFindFolder                  = Katalogas automatiškai parenkamas, kai yra
	RuleNameNewChange               = Automatiškai sinchronizuoti po atnaujinimų
	RuleNewTempate                  = Sukurti šabloną
	RuleSkipFolderCheck             = Daugiau netikrina, ar failas yra kataloge, ir failo tipą
	RuleAuthon                      = Taisyklių kūrėjas
	RuleGUID                        = GUID visame pasaulyje unikalus identifikatorius
	RuleName                        = Taisyklės pavadinimas
	RuleDescription                 = Apibūdinti
	RuleNameUse                     = Sinchronizuoti taisyklės pavadinimą su: {0}
	RuleISO                         = Suderinkite originalų ISO diegimo paketą
	RuleInBoxApps                   = Pilna, iš anksto sukonfigūruota programa
	RuleFileType                    = Paketo pavadinimas
	RuleFileFind                    = Neaiškus paieškos pavadinimas
	RuleFindError                   = Rasta {0} elementų, kuriuos reikia apdoroti. Spustelėkite "Patikrinti priklausomybes", kad peržiūrėtumėte išsamią informaciją.
	RuleSelectApps                  = Vartotojo pasirinktos programos
	DependencyPackage               = Priklausomybės paketas
	RuleDependenciesRequired        = Reikalingos priklausomybės
	RuleDependenciesUnselected      = Nepasirinktos priklausomybės
	RuleDependenciesNoCheck         = Priklausomybės nebetikrinamos
	RuleDependenciesFix             = Ištaisyti nepasirinktas priklausomybes
	Extract_Tips                    = Užuomina\n\n   1. Rezultatas ištraukus kalbos paketą negali būti naudojamas kaip pagrindinis nuorodos objektas;\n\n   2. Kaip pagrindinį nuorodos objektą naudokite komponentų sąrašą. Kaip generuoti:\n\n       Funkcijose pasirinkite Generate Component (paketą gaukite įdiegtame paveikslėlyje), pasirinkite Print arba View Instantly;\n\n   3. Įdiegę kalbos paketą iš naujo sukurkite komponento ataskaitą, kad patikrintumėte, ar ji atitinka;

	DescendingRuleLang              = Pašalinkite kalbos paketus atvirkštine tvarka
	OrderRuleLang                   = Įdiekite kalbos paketus iš anksto nustatyta tvarka
	OrderRuleLangTips               = Pridėti eilės tvarka: pagrindinis, šriftai, optinis simbolių atpažinimas, rašysenos atpažinimas, tekstas į kalbą, kalbos atpažinimas, mažmeninės prekybos demonstracinė patirtis, kita
	RuleLanguageTips                = Pastaba:\n\n    naudojant parinktį "Įdiegti kalbų paketus iš anksto nustatyta tvarka", failai bus automatiškai suderinti su neaiškiais pavadinimais tokia tvarka:\n
	Match_installed_List            = Diegdami kalbos paketą, įdiegtų sąraše pažymėkite jį pakaitos simboliu
	Match_installed_List_Tips       = Atitinka tik įdiegus: pagrindinis, optinis simbolių atpažinimas, rašysenos atpažinimas, tekstas į kalbą, kalbos atpažinimas.
	RuleLanguageTipsExt             = \n   Kai nenaudojate parinkties "Įdiegti kalbos paketus iš anksto nustatyta tvarka": \n   Automatiškai ieškoti visų failų kataloge pagal failo tipą ir juos įdiegti.\n\n   Kalbos ir regiono funkcijos pagal poreikį (FOD)\n   https://learn.microsoft.com/lt-lt/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategorija
	Basic                           = Pagrindinis
	Fonts                           = Šriftas
	OCR                             = Optinis simbolių atpažinimas
	Handwriting                     = Rašysenos atpažinimas
	TextToSpeech                    = Tekstas į kalbą
	Speech                          = Kalbos atpažinimas
	Retail                          = Mažmeninės prekybos demonstracinė patirtis
	Features_On_Demand              = Funkcijos pagal pageidavimą
	RegionSpecific                  = Kiti regionui būdingi reikalavimai
	UnassignedLangFiles             = Nepriskirti įvairūs failai

	ProcessingImage                 = Apdorokite vaizdą:
	NoInstallImage                  = Vietoje neegzistuoja
	ConvertChk                      = Patikrinkite failą
	WindowsFeature                  = Windows funkcijos
	Enable                          = Įjungti
	Disable                         = Išjungti
	EnableFeatureTips               = Užuomina\n\n    1. Rodyti NetFx3 ir TelnetClient kaip iš anksto įgalintus funkcijų elementus;\n\n    2. Po "montavimo" galima įjungti daugiau.
	ViewLanguage                    = Peržiūrėkite vaizdo kalbos nustatymus
	ImageLanguage                   = Vaizdo kalbos nustatymai
	OnlyLangCleanup                 = Švarūs komponentai: pažymėkite pagal kalbą
	Matched_Component_Names         = Atitinkamas komponento pavadinimas:
	BootProcess                     = Apdorojant {0}.wim
	Sync_Language_To                = Sinchronizuoti su
	BootSyncToISO                   = Sinchronizuokite kalbos paketus su diegimo programa
	BootSyncToISOTips               = Įdiegtas neprisijungus pasiekiamo vaizdo kalbos paketas sinchronizuojamas su ISO diegimo programa.
	LangIni                         = Atkurti Lang.ini
	LangIniTips                     = Užbaigus sinchronizavimą, ISO Lang.ini reikia atkurti.
	LangNewAutoSelect               = Automatiškai pasirinkite siūlomus elementus, kai įvyksta įvykis
	LangNewAutoSelectTips           = Yra naujų įvykių, pasirinkta "Sinchronizuoti kalbos paketą su diegimo programa", "Rebuild Lang.ini".
	LangNewAutoNoSelect             = Yra naujų įvykių, rekomenduojama pasirinkti "Sinchronizuoti kalbos paketą su diegimo programa" ir "Rebuild Lang.ini".
	LangNewAutoNoNewSelect          = Naujų įvykių nėra. Rekomenduojama nepasirinkti "Sinchronizuoti kalbos paketą su diegimo programa" arba "Rebuild Lang.ini".
	Drive                           = Vairuoti
	ViewDrive                       = Peržiūrėkite įdiegtas tvarkykles
	EditionsProductKey              = Produkto raktas
	Editions                        = Vaizdo versija
	Assign_Editions                 = Automatiškai platinkite programas pagal vaizdo versijas
	EditionsChangeTips              = Įspėjimas, prieš keisdami vaizdo versijas supraskite:\n\nMicrosoft Paslaugos sutartis\nhttps://www.microsoft.com/lt-lt/servicesagreement/default.aspx\n\nKalbos apžvalga\nhttps://learn.microsoft.com/lt-lt/windows-hardware/manufacture/desktop/languages-overview\n\nJums neleidžiama kurti versijų: \n   1. Konkrečiai šaliai\n       ProfessionalCountrySpecific\n\n   2. Konkrečiam regionui skirta namų versija\n       ProfessionalSingleLanguage\n\nGriežtai laikykitės, nes pažeidus galite būti patrauktas baudžiamojon atsakomybėn.\n\nJei primygtinai reikalaujate konvertuoti, spustelėkite, kad priimtumėte įspėjimą, ir spustelėkite "Atrakinti paslėpto vaizdo versiją".
	EditionsChangeHide              = Atrakinkite paslėptų vaizdų versijas
	EditionsChangeAccect            = Aš perskaičiau įspėjimą ir esu atsakingas už atitinkamus įspėjime nurodytus įstatymus

	SelFile                         = Pasirinkite failą
	Rebuilding                      = Rekonstruojama
	RebuildAll                      = Viską atstatyti
	Export_Image                    = Eksportuoti
	SelectFromError                 = Klaida
	SelectFileFormatError           = Failo formatas neteisingas

	SearchDrive                     = Varomas paieškos
	SearchUpdate                    = Ieškoti naujinių, tipas ( {0} ), šaltinis:
	SelectFolder                    = Pasirinkite katalogą
	DropFolder                      = Gali vilkti katalogus į dabartinį langą
	DropFile                        = Failus galima vilkti į dabartinį langą
	Sparse                          = Retas
	CRCSHA                          = Patikrinti
	Alternative                     = Alternatyvus failo pavadinimas
	ChangeInstallDisk               = Pakeiskite automatinį disko pasirinkimą
	Backup                          = Atsarginė kopija
	Restore                         = Atkurti

	# View
	ExportToLogs                    = Spausdinkite ataskaitą į žurnalą
	ExportShow                      = Rodyti ataskaitas akimirksniu
	MoreFeature                     = Daugiau funkcijų
	OpenFolder                      = Atidaryti katalogą
	OpenFile                        = Atidaryti failą
	Running                         = Paleisti
	Paste                           = Kopijuoti kelią
	Clipboard_Copy                  = Nukopijuota į mainų sritį
	ViewWIMFileInfo                 = Žiūrėti vaizdą
	GetInBoxApps                    = InBox Apps: įdiegti programų paketai
	GetImagePackage                 = Komponentai: visi vaizde įdiegti paketai
	ViewMounted                     = Gaukite informacijos apie visus pritvirtintus vaizdus
'@