ConvertFrom-StringData -StringData @'
	# tr-TR
	# Turkish (Turkey)

	FontsUI                   = Segoe UI
	Mainname                  = Dağıtım motoru: Yi'nin paketi
	Learn                     = Çalışmak
	MainHisName               = Bonus çözümü
	Location                  = Konumu aç
	About                     = Hakkında
	Reset                     = Sıfırlama
	AddTo                     = A ekle
	Instl                     = Düzenlemek
	ItInstalled               = Yüklendi
	Close                     = Kapanış
	Auto                      = Otomatik
	Disable                   = Devre dışı bırakmak
	Enable                    = Olanak vermek
	Setting                   = Kurmak
	Restore                   = Iyileşmek
	CLearn                    = Temizlemek
	Operable                  = Çalıştırılabilir
	Inoperable                = Ameliyat edilemez
	Optimize                  = Optimizasyon
	Hide                      = Saklamak
	Show                      = Göstermek
	Del                       = Silmek
	Done                      = Sona ermek
	OK                        = Elbette
	Cancel                    = İptal etmek
	AllSel                    = Tümünü seç
	AllClear                  = Hepsini temizle
	Refresh                   = Yenileme
	RefreshModules            = Tüm modülleri sıcak yenileme
	Necessary                 = Temel yazılım
	MostUsedSoftware          = Yaygın olarak kullanılan yazılım
	System                    = Sistem
	Service                   = Sert
	TaskBar                   = Tüm görev çubuğu simgeleri
	DeskIcon                  = Masaüstü simgeleri
	InstallFonts              = Yazı tiplerini yükle
	SettingTo                 = {0} olarak ayarla
	AvailableLanguages        = Mevcut diller
	SwitchLanguage            = Dili değiştir
	LanguageReset             = Dil ayarlarını sıfırla
	LanguageCode              = Bölge işareti
	LanguageSelRegion         = Ülkenizi veya bölgenizi seçin
	LanguageRemember          = Seçilen dili hatırla
	LanguageSearchNo          = Kullanılabilir dil bulunamadı
	LanguageNoPack            = Yerel olarak dil paketi yoksa otomatik olarak çıkılacaktır.
	LanguageNoSel             = Lütfen bir bölge seçin
	Search                    = Aramak
	PleaseChoose              = Lütfen seçin
	FailedCreateFolder        = Dizin oluşturulamadı
	Failed                    = Hata
	ToMsg                     = {0} Saniyeler sonra otomatik olarak ana menüye dönün.
	Restart                   = Yeniden başlatma etkili olur
	AdvOption                 = Isteğe bağlı özellikler

	StartDown                 = İndirmeye başla
	ConnectTo                 = Bağlan
	FileName                  = Dosya adı
	SaveTo                    = Kaydet
	NotAvailable              = Durum: Mevcut değil
	ExistingPacker            = Zaten kurulum paketiniz var
	ExistingInstlPacker       = Zaten sıkıştırılmış bir paketiniz var
	Unpacking                 = Sıkıştırmayı açma
	QucikRun                  = Hızlı çalıştırma:
	WaitDone                  = Tamamlanması bekleniyor:
	Parameter                 = Parametre:
	ErrorDown                 = İndirme sırasında bir hata oluştu
	UserCancel                = Kullanıcı işlemi iptal etti.

	VerifyNameTips            = Yalnızca İngilizce harf ve rakamlardan oluşan bir kombinasyona izin verilir ve başka hiçbir karaktere izin verilmez: boşluklar, uzunluk 16 karakterden fazla olamaz, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Özel dizin öneki
	NoSetFolderLabel          = Özel dizin öneki ayarlanmadı
	ISO9660TipsErrorSpace     = Şunları içeremez: baştaki ve sondaki boşluklar
	ISO9660TipsErrorOther     = Şunları içeremez: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Birim etiketi {0} karakterden uzun olamaz
	Help                      = Yardım
	WorkDone                  = Tamamlandı, ana arayüze dönmek için herhangi bir tuşa basın...
	Short_Cmd                 = Kısayollar
	Options                   = Seçenekler
'@