ConvertFrom-StringData -StringData @'
	# sl-SI
	# Slovenian (Slovenia)

	FontsUI                   = Segoe UI
	Mainname                  = Mehanizem za uvajanje: Yijev paket
	Learn                     = Študija
	MainHisName               = Bonus rešitev
	Location                  = Odprta lokacija
	About                     = Približno
	Reset                     = Ponastaviti
	AddTo                     = Dodaj v
	Instl                     = Namestite
	ItInstalled               = Nameščeno
	Close                     = Zaprtje
	Auto                      = Samodejno
	Disable                   = Onemogoči
	Enable                    = Omogočiti
	Setting                   = Postaviti
	Restore                   = Okrevati
	CLearn                    = Pospraviti
	Operable                  = Operabilno
	Inoperable                = Neoperabilen
	Optimize                  = Optimizacija
	Hide                      = Skriti
	Show                      = Pokazati
	Del                       = Izbrisati
	Done                      = Končaj
	OK                        = Seveda
	Cancel                    = Prekliči
	AllSel                    = Izberi vse
	AllClear                  = Počisti vse
	Refresh                   = Osveži
	RefreshModules            = Vroča osvežitev vseh modulov
	Necessary                 = Bistvena programska oprema
	MostUsedSoftware          = Pogosto uporabljena programska oprema
	System                    = Sistem
	Service                   = Postrezite
	TaskBar                   = Vse ikone opravilne vrstice
	DeskIcon                  = Ikone na namizju
	InstallFonts              = Namestite pisave
	SettingTo                 = Nastavljeno na {0}
	AvailableLanguages        = Razpoložljivi jeziki
	SwitchLanguage            = Preklopi jezik
	LanguageReset             = Ponastavite jezikovne nastavitve
	LanguageCode              = Conska oznaka
	LanguageSelRegion         = Izberite svojo državo ali regijo
	LanguageRemember          = Zapomni si izbrani jezik
	LanguageSearchNo          = Ni razpoložljivih jezikov
	LanguageNoPack            = Če lokalno ni jezikovnega paketa, se samodejno zapre.
	LanguageNoSel             = Izberite regijo
	Search                    = Iskanje
	PleaseChoose              = Prosim izberite
	FailedCreateFolder        = Imenika ni bilo mogoče ustvariti
	Failed                    = Spodleteti
	ToMsg                     = {0} Samodejna vrnitev v glavni meni po nekaj sekundah.
	Restart                   = Ponovni zagon stopi v veljavo
	AdvOption                 = Neobvezne funkcije

	StartDown                 = Začnite prenašati
	ConnectTo                 = Poveži se z
	FileName                  = Ime datoteke
	SaveTo                    = Shrani v
	NotAvailable              = Status: Ni na voljo
	ExistingPacker            = Že imate namestitveni paket
	ExistingInstlPacker       = Že imate stisnjen paket
	Unpacking                 = Razpakiranje
	QucikRun                  = Hiter tek:
	WaitDone                  = Čakanje na dokončanje:
	Parameter                 = Parameter:
	ErrorDown                 = Med prenosom je prišlo do napake
	UserCancel                = Uporabnik je preklical operacijo.

	VerifyNameTips            = Dovoljena je samo kombinacija angleških črk in številk, nobeni drugi znaki pa niso dovoljeni: presledki, dolžina ne sme biti večja od 16 znakov, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Predpona imenika po meri
	NoSetFolderLabel          = Predpona imenika po meri ni nastavljena
	ISO9660TipsErrorSpace     = Ne sme vsebovati: začetnih in končnih presledkov
	ISO9660TipsErrorOther     = Ne sme vsebovati: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Oznaka nosilca ne sme biti daljša od {0} znakov
	Help                      = Pomoč
	WorkDone                  = Končano, pritisnite katero koli tipko za vrnitev v glavni vmesnik ...
	Short_Cmd                 = Bližnjice
	Options                   = Možnosti
'@