ConvertFrom-StringData -StringData @'
	# ko-KR
	# Korean (Korea)

	SaveModeClear                   = 선택한 기록 지우기
	SaveModeTipsClear               = 기록 저장, 정리 가능
	SelectTips                      = 힌트\n\n    1. 처리할 이미지 이름을 선택하십시오.\n    2. 취소한 후에는 "마운트"해야 하는 작업이 더 이상 적용되지 않습니다.
	CacheDisk                       = 디스크 캐시
	CacheDiskCustomize              = 사용자 지정 캐시 경로
	AutoSelectRAMDISK               = 디스크 레이블 자동 선택 허용
	AutoSelectRAMDISKFailed         = 볼륨 레이블과 일치하지 않습니다d
	ReFS_Find_Volume                = 디스크 형식 REFS가 발견되면 제외
	ReFS_Exclude                    = ReFS 파티션이 제외됨
	Disk_Not_satisfied_Exclude      = 최소 디스크 요구 사항이 충족되지 않았습니다.
	RAMDISK_Change                  = 볼륨 레이블 이름을 변경합니다
	RAMDISK_Search                  = 볼륨 레이블 이름을 검색하세요.
	RAMDISK_Restore                 = 볼륨 레이블 이름 초기화 복구: {0}
	AllowTopMost                    = 열린 창을 맨 위로 가져오도록 허용
	History                         = 명확한 역사
	History_Del_Tips                = 포장 작업이있는 경우 다음 옵션을 수행하지 마십시오. 그렇지 않으면 포장 스크립트가 작동 중에 알려지지 않은 문제가 발생합니다.
	History_View                    = 기록 보기
	HistoryLog                      = 7 일이 지난 로그 자동 정리 허용
	HistorySaveFolder               = 기타 이미지 소스 경로
	HistoryClearappxStage           = InBox Apps: 설치 중에 생성 된 임시 파일을 삭제하십시오
	DoNotCheckBoot                  = Boot.wim 파일 크기 초과 520MB, 재생성 선택
	HistoryClearDismSave            = 레지스트리에 저장된 DISM 마운트 레코드 삭제
	ImageSourcesClickShowKey        = "기본 키 선택" 메뉴 표시 허용
	ImageSourcesClickShowKeyTips    = 사용자가 이미지 소스를 선택한 후: 오른쪽에 "기본 키 선택" 메뉴를 추가하고, "이동" 옵션 ( 마운트, 저장, 팝업 ) 을 추가합니다.
	Clear_Bad_Mount                 = 손상된 이미지와 관련된 모든 리소스를 삭제하십시오
	ShowCommand                     = 실행할 전체 명령줄 표시
	Command                         = 명령줄
	SelectSettingImage              = 이미지 소스
	NoSelectImageSource             = 이미지 소스가 선택되지 않았습니다.
	SettingImageRestore             = 기본 마운트 위치 복원
	SettingImage                    = 이미지 소스 마운트 위치 변경
	SelectImageMountStatus          = 이미지 소스 선택 후 마운트 상태 가져오기
	SettingImageTempFolder          = 임시 디렉토리
	SettingImageToTemp              = 임시 디렉토리는 마운트된 위치와 동일합니다.
	SettingImagePathTemp            = Temp 디렉토리 사용
	SettingImageLow                 = 최소 여유 공간 확인
	SettingImageNewPath             = 디스크 마운트 선택
	SettingImageNewPathTips         = Ultra RAMDisk, ImDisk 및 기타 가상 메모리 소프트웨어를 사용할 수 있는 가장 빠른 메모리 디스크에 마운트하는 것이 좋습니다.
	SelectImageSource               = "엔진 솔루션 배포"를 선택하고 확인을 클릭합니다.
	NoImagePreSource                = 사용할 수 있는 소스를 찾을 수 없습니다: \n\n     1. 다음에 더 많은 이미지 원본 추가: \n          {0}\n\n     2. 설정을 선택하고 이미지 원본 검색 디스크를 다시 선택합니다.\n\n     3. "ISO" 를 선택하고 압축을 풀 ISO, 마운트할 항목 등을 선택합니다.
	NoImageOtherSource              = 다른 경로를 "추가" 하려면 클릭하거나 현재 창으로 "디렉토리를 드래그" 하십시오.
	SearchImageSource               = 이미지 소스 검색 디스크
	Kernel                          = 커널
	Architecture                    = 건축물
	ArchitecturePack                = 패키지 아키텍처, 추가 규칙 이해
	ImageLevel                      = 설치 유형
	LevelDesktop                    = 데스크탑
	LevelServer                     = 서버 수준
	ImageCodename                   = 암호
	ImageCodenameNo                 = 인식할 수 없는 
	MainImageFolder                 = 기본 디렉토리
	MountImageTo                    = 마운트
	Image_Path                      = 이미지 경로
	MountedIndex                    = 인덱스
	MountedIndexSelect              = 인덱스 번호 선택
	AutoSelectIndexFailed           = 색인 {0} 의 자동 선택에 실패했습니다. 다시 시도해 주세요.
	Apply                           = 이미지 적용
	Eject                           = 팝업
	Mount                           = 산
	Unmount                         = 제거
	Mounted                         = 탑재
	NotMounted                      = 장착되지 않음
	NotMountedSpecify               = 마운트되지 않음, 마운트 위치를 지정할 수 있습니다.
	MountedIndexError               = 마운트가 비정상적입니다. 삭제 후 다시 시도해 보세요.
	ImageSouresNoSelect             = 이미지 소스 선택 후 세부 정보 표시
	Mounted_Mode                    = 마운트 모드
	Mounted_Status                  = 마운트 상태
	Image_Popup_Default             = 기본값으로 저장
	Image_Restore_Default           = 기본값으로 되돌리기
	Image_Popup_Tips                = 힌트: \n\n이벤트를 할당할 때 {0}을(를) 처리할 색인 번호를 지정하지 않았습니다.\n\n선택 인터페이스가 이제 팝업되었습니다. 색인 번호를 지정하십시오. 지정이 완료된 후 "기본값으로 저장"을 선택하는 것이 좋습니다. 그러면 다음에 팝업되지 않습니다.
	Rule_Show_Full                  = 모두 표시
	Rule_Show_Only                  = 규칙만 표시
	Rule_Show_Only_Select           = 규칙에서 선택
	Image_Unmount_After             = 마운트된 모든 항목 제거

	Wim_Rule_Update                 = 이미지 내의 파일 추출, 업데이트
	Wim_Rule_Extract                = 파일을 추출합니다
	Wim_Rule_Extract_Tips           = 경로 규칙을 선택한 후 지정된 파일을 추출하여 로컬로 저장합니다.

	Wim_Rule_Verify                 = 확인하다
	Wim_Rule_Check                  = 조사하다
	Wim_Rule_CheckIntegrity         = 무결성 검사
	Wim_Rule_WIMBoot                = 부팅 가능
	Wim_Rule_Compact                = 운영 체제 파일 압축
	Win_Rule_Setbootable            = 볼륨 이미지를 부팅 가능으로 표시
	Win_Rule_Setbootable_Tips       = 이 매개변수는 Windows PE 이미지에만 적용됩니다.\n.wim 파일에서는 하나의 볼륨 이미지만 부팅 가능으로 표시할 수 있습니다.
	Destination                     = 목적지

	Wim_Append                      = 추가
	Wim_Capture                     = 캡처
	Wim_Capture_Tips                = 드라이브 이미지를 새 WIM 파일에 캡처합니다.
	Wim_Capture_Sources             = 소스 캡처
	Wim_Capture_Sources_Tips        = 캡처된 디렉터리에는 모든 하위 폴더와 데이터가 포함됩니다.\n빈 디렉터리는 캡처할 수 없습니다. 디렉터리에는 최소 하나의 파일이 있어야 합니다.
	Wim_Config_File                 = 구성 파일 경로 ( 제외 )
	Wim_Config_Edit                 = 편집
	Wim_Config_Learn                = 구성 목록 및 WimScript.ini 파일을 검토합니다.

	Wim_Rename                      = 이미지 정보 수정
	Wim_Image_Name                  = 이미지 이름
	Wim_Image_Description           = 이미지 설명
	Wim_Display_Name                = 쇼 이름
	Wim_Display_Description         = 설명 표시
	Wim_Edition                     = 이미지 로고
	Wim_Edition_Select_Know         = 알려진 이미지 플래그 선택
	Wim_CreatedTime                 = 생성 일자
	Wim_ModifiedTime                = 마지막 수정 시간
	Wim_FileCount                   = 파일 수
	Wim_DirectoryCount              = 디렉토리 수
	Wim_Expander_Space              = 공간 확장

	IABSelectNo                     = 기본 키가 선택되지 않았습니다: Install、WinRE、Boot
	Unique_Name                     = 고유한 이름 지정
	Select_Path                     = 경로입니다
	Setting_Pri_Key                 = 이 업데이트 파일을 기본 템플릿으로 설정합니다
	Pri_Key_Update_To               = 그런 다음 업데이트
	Pri_Key_Template                = 이 파일을 선택한 항목에 동기화할 기본 템플릿으로 설정합니다.
	Pri_key_Running                 = 기본 키 작업이 동기식으로 완료되어 건너뜁니다.
	ShowAllExclude                  = 사용되지 않는 모든 제외 표시

	Index_Process_All               = 알려진 모든 인덱스 번호 처리
	Index_Is_Event_Select           = 이벤트가 발생하면 선택 인터페이스가 팝업됩니다
	Index_Pre_Select                = 사전 할당된 색인 번호
	Index_Select_Tips               = 힌트: \n\n{0}.wim 이 현재 마운트되지 않은 경우 다음을 수행할 수 있습니다：\n\n   1. "알려진 모든 색인 번호 처리"를 선택하십시오.\n\n   2. "이벤트가 있을 때 인덱스 번호를 선택하는 인터페이스가 나타납니다"를 선택하십시오.\n\n   3. 미리 지정된 색인 번호.\n      색인 번호 6이 지정되고 처리 중에 색인 번호가 존재하지 않으며 처리를 건너뜁니다.

	DefenderExclude                 = Windows 바이러스 백신 제외 항목
	DefenderFolder                  = 이 디렉터리를 Windows 바이러스 백신 제외 항목에 추가합니다.
	DefenderVolume                  = 일치하는 볼륨 레이블 이름을 찾으면 이 디스크를 Windows 바이러스 백신 제외 항목에 추가합니다.
	DefenderIsAdd                   = Windows 바이러스 백신 제외 항목에 추가되었습니다.
'@