ConvertFrom-StringData -StringData @'
	# ro-RO
	# Romanian (Romania)

	IsCreate                        = Crea
	Solution                        = Soluţie
	EnabledSoftwarePacker           = Colectare
	EnabledUnattend                 = Ar trebui să răspundă în avans
	EnabledEnglish                  = Motor de implementare
	UnattendSelectVer               = Selectați limba soluției "Răspuns la".
	UnattendLangPack                = Selectați pachetul de limbi "Soluție".
	UnattendSelectSingleInstl       = Multi-limbi, opțional în timpul instalării
	UnattendSelectMulti             = Multilingv
	UnattendSelectDisk              = Selectați soluția Autounattend.xml
	UnattendSelectSemi              = Semiautomatul este valabil pentru toate metodele de instalare
	UnattendSelectUefi              = UEFI se instalează automat și trebuie specificat
	UnattendSelectLegacy            = Legacy este instalat automat și trebuie specificat
	NeedSpecified                   = Vă rugăm să selectați ceea ce trebuie specificat:
	OOBESetupOS                     = Interfață de instalare
	OOBEProductKey                  = Cheia produsului
	OOBEOSImage                     = Selectați sistemul de operare de instalat
	OOBEEula                        = Acceptați termenii licenței
	OOBEDoNotServerManager          = Server Manager nu pornește automat la conectare
	OOBEIE                          = Configurație de securitate îmbunătățită pentru Internet Explorer
	OOBEIEAdmin                     = Închideți "Administrator"
	OObeIEUser                      = Închideți "Utilizatori"

	OOBE_Init_User                  = Utilizator inițial în timpul experienței de despachetare
	OOBE_init_Create                = Creați utilizatori personalizați
	OOBE_init_Specified             = Specificați utilizatorul
	OOBE_Init_Autologin             = Conectare automată

	InstlMode                       = Metoda de instalare
	Business                        = Versiunea business
	BusinessTips                    = Depinde de EI.cfg, numărul de index trebuie specificat pentru instalarea automată.
	Consumer                        = Versiune pentru consumatori
	ConsumerTips                    = Nu se bazează pe EI.cfg. Numărul de serie trebuie specificat pentru instalarea automată.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [monta la]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Adăugați pe discul de sistem numele directorului principal
	VerifyNameUse                   = Verificați că numele directorului nu poate conține
	VerifyNameTips                  = Este permisă doar o combinație de litere și numere în limba engleză și nu poate conține: spații, lungimea nu poate fi mai mare de 260 de caractere, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Verificarea a eșuat, introduceți numărul corect.
	VerifyNameSync                  = Setați numele directorului ca nume de utilizator principal
	VerifyNameSyncTips              = Administratorul nu mai este folosit.
	ManualKey                       = Selectați sau introduceți manual cheia de produs
	ManualKeyTips                   = Introduceți o cheie de produs validă Dacă regiunea selectată nu este disponibilă, accesați site-ul oficial Microsoft pentru a verifica.
	ManualKeyError                  = Cheia de produs pe care ați introdus-o nu este validă.
	KMSLink1                        = Cheia de setări client KMS
	KMSUnlock                       = Afișați toate numerele de serie KMS cunoscute
	KMSSelect                       = Vă rugăm să selectați numărul de serie VOL
	KMSKey                          = Număr de serie
	KMSKeySelect                    = Schimbați numărul de serie al produsului
	ClearOld                        = Curățați fișierele vechi
	SolutionsSkip                   = Omiteți crearea soluției
	SolutionsTo                     = Adăugați "soluție" la:
	SolutionsToMount                = Montat sau adăugat la coadă
	SolutionsToError                = Unele funcții au fost dezactivate Dacă trebuie să le forțați, faceți clic pe butonul "Deblocare".\n\n
	UnlockBoot                      = Deblocați
	SolutionsToSources              = Directorul principal, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Selectați versiunea "Deployment Engine".
	SolutionsEngineRegionaUTF8      = Beta: suport global pentru limba folosind Unicode UTF-8
	SolutionsEngineRegionaUTF8Tips  = Se pare că poate cauza noi probleme după deschidere. Nerecomandat.
	SolutionsEngineRegionaling      = Schimbați la noua locație:
	SolutionsEngineRegionalingTips  = Schimbați localitatea sistemului, care afectează toate conturile de utilizator de pe computer.
	SolutionsEngineRegional         = Schimbați localitatea sistemului
	SolutionsEngineRegionalTips     = Implicit global: {0}, modificat în: {1}
	SolutionsEngineCopyPublic       = Copiați {0} public în implementare
	SolutionsEngineCopyOpen         = Răsfoiți locația depozitului public {0}
	EnglineDoneReboot               = Reporniți computerul
	SolutionsTipsArm64              = Se preferă pachetul arm64, iar tu selectezi în ordine: x64, x86.
	SolutionsTipsAMD64              = Prefer pachetele x64, în ordine: x86.
	SolutionsTipsX86                = Sunt adăugate doar pachete x86.
	SolutionsReport                 = Generați un raport înainte de implementare
	SolutionsDeployOfficeInstall    = Implementați pachetul de instalare Microsoft Office
	SolutionsDeployOfficeChange     = Modificați configurația de implementare
	SolutionsDeployOfficePre        = Versiunea pachetului preinstalat
	SolutionsDeployOfficeNoSelect   = Nu a fost selectat niciun pachet de preinstalare Office
	SolutionsDeployOfficeVersion    = Versiunea {0}
	SolutionsDeployOfficeOnly       = Păstrați pachetele de limbi specificate
	SolutionsDeployOfficeSync       = Păstrați sincronizarea limbii cu configurația de implementare
	SolutionsDeployOfficeSyncTips   = După sincronizare, scriptul de instalare nu poate determina limba preferată.
	DeploySyncMainLanguage          = Sincronizați cu limba principală
	SolutionsDeployOfficeTo         = Implementați pachetul de instalare la
	SolutionsDeployOfficeToPublic   = Desktop public
	DeployPackage                   = Implementați un pachet personalizat de colectare
	DeployPackageSelect             = Selectați un pachet de precolectare
	DeployPackageTo                 = Implementați pachetul de pre-colectare la
	DeployPackageToRoot             = Disc de sistem:\\Package
	DeployPackageToSolutions        = În directorul principal al soluției
	DeployTimeZone                  = Fus orar
	DeployTimeZoneChange            = Schimbați fusul orar
	DeployTimeZoneChangeTips        = Setați zona de timp implicită în care ar trebui să se răspundă pre-răspunsurile, în funcție de zona de limbă.

	Deploy_Tags                     = Eticheta de implementare
	FirstExpProcess                 = Prima experiență, în timpul implementării cerințelor preliminare:
	FirstExpProcessTips             = După finalizarea cerințelor preliminare, reporniți computerul pentru a rezolva problema necesității unei reporniri pentru a avea efect.
	FirstExpFinish                  = Prima dată experiență, după îndeplinirea cerințelor preliminare
	FirstExpSyncMark                = Permite căutarea globală și sincronizarea etichetelor de implementare
	FirstExpUpdate                  = Permite actualizări automate
	FirstExpDefender                = Adăugați directorul principal la directoarele excluse Defend
	FirstExpSyncLabel               = Eticheta volumului discului de sistem: numele directorului principal este același
	MultipleLanguages               = Când întâlniți mai multe limbi:
	NetworkLocationWizard           = Expertul pentru locație în rețea
	PreAppxCleanup                  = Blocați sarcinile de întreținere pentru curățarea Appx
	LanguageComponents              = Preveniți curățarea pachetelor de limbi cu funcții la cerere neutilizate
	PreventCleaningUnusedLP         = Preveniți curățarea pachetelor de limbi neutilizate
	FirstExpContextCustomize        = Adăugați un "meniu contextual" personalizat
	FirstExpContextCustomizeShift   = Țineți apăsată tasta Shift și faceți clic dreapta

	FirstExpFinishTips              = Nu există evenimente importante după finalizarea implementării. Se recomandă să anulați.
	FirstExpFinishPopup             = Afișează interfața principală a motorului de implementare
	FirstExpFinishOnDemand          = Permite prima previzualizare, așa cum a fost planificat
	SolutionsEngineRestricted       = Restabiliți politica de execuție Powershell: restricționată
	EnglineDoneClearFull            = Ștergeți întreaga soluție
	EnglineDoneClear                = Ștergeți motorul de implementare și păstrați celelalte

	Unattend_Auto_Fix_Next          = Data viitoare când îl întâlniți, selectați automat elementele necesare pentru a o remedia automat.
	Unattend_Auto_Fix               = Reparați automat când cerințele preliminare nu sunt selectate
	Unattend_Auto_Fix_Tips          = Când adăugați motorul de implementare și nu selectați prima comandă de rulare, aceasta este reparată și selectată automat: Politică de execuție Powershell: rulați motorul de implementare fără restricții.
	Unattend_Version_Tips           = Opțional, includeți numai, utilizați implicit pentru a accepta ARM64, x64, x86.
	First_Run_Commmand              = Comenzi de rulat la implementare pentru prima dată
	First_Run_Commmand_Setting      = Selectați comanda de rulat
	Command_Not_Class               = Nu mai este clasificat automat la filtrare
	Command_WinSetup                = Instalare Windows
	Command_WinPE                   = Windows PE
	Command_Tips                    = Vă rugăm să atribuiți First Run App la: Instalare Windows, Windows PE\n\nRețineți că atunci când se adaugă un motor de implementare, trebuie să verificați următoarele când rulați pentru prima dată: Politică de execuție Powershell: Restricționat, permiteți rularea scripturilor motorului de implementare.
	Waring_Not_Select_Command       = Când adăugați un motor de implementare, politica de execuție Powershell nu a fost selectată: nu setați nicio restricție și permiteți rularea scriptului motorului de implementare Vă rugăm să îl selectați și să încercați din nou sau să faceți clic pe "Remedierea rapidă nu este selectată".
	Quic_Fix_Not_Select_Command     = Remediere rapidă nu opțiune

	PowerShell_Unrestricted         = Politica de execuție Powershell: fără restricții
	Allow_Running_Deploy_Engine     = Permiteți rularea scripturilor motorului de implementare
	Bypass_TPM                      = Ocolirea verificărilor TPM în timpul instalării
'@