ConvertFrom-StringData -StringData @'
	# sr-latn-rs
	# Serbian (Latin, Serbia)

	FontsUI                   = Segoe UI
	Mainname                  = Механизам за имплементацију: Ии-ов пакет
	Learn                     = Студија
	MainHisName               = Бонус решење
	Location                  = Отворена локација
	About                     = О
	Reset                     = Ресетовати
	AddTo                     = Додај у
	Instl                     = Инсталирај
	ItInstalled               = Инсталиран
	Close                     = Затварање
	Auto                      = Аутоматски
	Disable                   = Онемогући
	Enable                    = Омогућити
	Setting                   = Поставити
	Restore                   = Опоравити се
	CLearn                    = Очистити
	Operable                  = Операабле
	Inoperable                = Неоперабилан
	Optimize                  = Оптимизација
	Hide                      = Сакрити
	Show                      = Схов
	Del                       = Избрисати
	Done                      = Заврши
	OK                        = Наравно
	Cancel                    = Откажи
	AllSel                    = Изаберите све
	AllClear                  = Очисти све
	Refresh                   = Освежити
	RefreshModules            = Вруће освежавање свих модула
	Necessary                 = Основни софтвер
	MostUsedSoftware          = Често коришћени софтвер
	System                    = Система
	Service                   = Послужите
	TaskBar                   = Све иконе на траци задатака
	DeskIcon                  = Иконе на радној површини
	InstallFonts              = Инсталирајте фонтове
	SettingTo                 = Подесите на {0}
	AvailableLanguages        = Доступни језици
	SwitchLanguage            = Промени језик
	LanguageReset             = Ресетујте подешавања језика
	LanguageCode              = Ознака зоне
	LanguageSelRegion         = Изаберите своју земљу или регион
	LanguageRemember          = Запамтите изабрани језик
	LanguageSearchNo          = Није пронађен ниједан доступан језик
	LanguageNoPack            = Ако локално не постоји језички пакет, аутоматски ће ce затворити.
	LanguageNoSel             = Изаберите регион
	Search                    = Тражи
	PleaseChoose              = Молимо изаберите
	FailedCreateFolder        = Креирање директоријума није успело
	Failed                    = Пропасти
	ToMsg                     = {0} Аутоматски се вратите у главни мени након неколико секунди.
	Restart                   = Поновно покретање ступа на снагу
	AdvOption                 = Опционе карактеристике

	StartDown                 = Започните преузимање
	ConnectTo                 = Повежите се са
	FileName                  = Назив датотеке
	SaveTo                    = Сачувати у
	NotAvailable              = Статус: Није доступно
	ExistingPacker            = Већ имате инсталациони пакет
	ExistingInstlPacker       = Већ имате компримовани пакет
	Unpacking                 = Распакивање
	QucikRun                  = Брзо трчање:
	WaitDone                  = Чека се завршетак:
	Parameter                 = Параметар:
	ErrorDown                 = Дошло је до грешке током преузимања
	UserCancel                = Корисник је отказао операцију.

	VerifyNameTips            = Дозвољена је само комбинација енглеских слова и бројева, а други знакови нису дозвољени: размаци, дужина не може бити већа од 16 знакова, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Прилагођени префикс директоријума
	NoSetFolderLabel          = Прилагођени префикс директоријума није подешен
	ISO9660TipsErrorSpace     = Не може да садржи: почетне и задње размаке
	ISO9660TipsErrorOther     = Не може да садржи: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Ознака волумена не може бити дужа од {0} знакова
	Help                      = Помоћ
	WorkDone                  = Завршено, притисните било који тастер да бисте се вратили на главни интерфејс...
	Short_Cmd                 = Пречице
	Options                   = Опције
'@