ConvertFrom-StringData -StringData @'
	# ja-JP
	# Japanese (Japan)

	FontsUI                         = Yu Gothic UI

	# Main page
	Dashboard                       = ダッシュボード
	Learn                           = 勉強
	Menu                            = メニュー
	Short_Cmd                       = ショートカットコマンド
	Shortcut                        = ショートカット
	Update                          = 更新する
	CUpdate                         = 累積的な更新
	Rebuild                         = 再建
	AddTo                           = 追加
	Del                             = 消去
	Copy                            = コピー
	Rename                          = 名前の変更
	Refresh                         = リフレッシュ
	RefreshModules                  = すべてのモジュールをホットリフレッシュします
	Done                            = 終了
	OK                              = もちろん
	Cancel                          = キャンセル
	AllSel                          = すべて選択
	AllClear                        = すべてクリア
	Setting                         = 設定
	Change                          = 変える
	Help                            = ヘルプ
	Logging                         = ログ
	AvailableLanguages              = 利用可能な言語
	SwitchLanguage                  = 言語を切り替える
	LanguageSelRegion               = 国または地域を選択してください
	LanguageRemember                = 選択した言語を記憶する
	LanguageSearchNo                = 利用可能な言語が見つかりません
	LanguageNoPack                  = ローカルに言語パックがない場合は、自動的に終了します。
	LanguageNoSel                   = 地域を選択してください
	Search                          = 検索
	PleaseChoose                    = 選んでください
	Options                         = オプション
	Choose                          = 選ばれた
	NoChoose                        = 選択されていない
	AdvOption                       = オプション機能
	ExcludeItem                     = ルールで除外する
	DeDuplication                   = 重複を除外する
	DeDuplication_Unlock            = 無効化された重複のロック解除
	Existed                         = 存在した
	FailedCreateFolder              = ディレクトリの作成に失敗しました
	FailedCreateFile                = ファイルの作成に失敗しました
	ToMsg                           = {0} 秒後に自動的にメインメニューに戻ります。
	OnDemandPlanTask                = 既知のイベントのカスタム割り当て
	Operable                        = 運用
	Inoperable                      = 動作不能
	Hide                            = 隠れる
	CuringUpdate                    = 硬化アップデート
	CuringUpdateTips                = ファームウェアの更新後はアンインストールできません。
	Healthy                         = 元気
	HealthyTips                     = ヘルスステータスを確認することは特に重要です。「修復可能」または「修復不能」が表示された場合：ESD 変換プロセス中にエラー 13 が表示され, データが無効になります。システムのインストール時にエラーが報告されます。
	Healthy_Save                    = 修復可能または修復不能が表示された場合は, 保存しないでください
	Repair                          = 修理
	IsAuto_Repair                   = アイドル時の自動修復を許可する
	IsAuto_Repair_Tips              = パッケージ化スクリプトを実行するたびに、マウント タスクがあるかどうかを自動的に確認します。マウントされている場合は修復は実行されません。マウントされていない場合は自動修復が実行されます。
	Repairable                      = 修理可能
	NonRepairable                   = 取り返しのつかない
	HealthyForceStop                = イベントの処理中に不可逆エラーが発生し, 強制的に終了しました。\n\n   主な問題の原因：\n\n      1. 物理的なハードウェアの損傷, ハードディスク。\n\n      2. RAMDISK メモリ仮想ディスク（ハイブリッドを含む）を使用する場合は, 物理メモリを確認してください。\n\n      3. 元の MVS (MSDN) バージョンのSHA256を確認します。同じ場合は, ディレクトリを変更して再試行してください。SHA256に一貫性がない場合は, ダウンロードして再試行してください。\n\n      4. その他, この例にはリストされていません。
	Superseded                      = クリーンアップ交換
	SupersededTips                  = 古いアップデート, コンポーネントなどが含まれます
	UnmountFailed                   = すでにいくつかの方法を使っていますが, 私にできることは何もありません。弟はこの時点でしか攻撃できません。次回はヒーローとお会いしましょう。
	SaveTo                          = 保存先
	WorkDone                        = 完了し, メインインターフェイスに戻って任意のキーを押します...
	UserCanel                       = ユーザーが要求をキャンセルしました。
	Uping                           = ビルド内
	Exclude_View                    = 除外ルールを確認します
	User_Interaction                = ユーザー インタラクション
	Ok_Go_To                        = 利用可能
	Ok_Go_To_No                     = 行きません

	Detailed                        = 詳細
	Detailed_View                   = 選択したルールの詳細を表示します

	AddEnv                          = システム変数にルーティング機能を追加します
	AddEnvTips                      = 追加後, PowerShell の任意のセッションに Yi と入力すると, カプセル化を実行するために "Yi -SIP" と入力して応答できます。

	Unzip_ISO                       = エキス ISO
	Unzip_Search_Type               = ディレクトリの検索 ( {0} )
	ISO_Other                       = その他のファイル
	Unzip_Language                  = 言語パック
	Unzip_Fod                       = 機能パック
	FileName                        = ファイル名

	UserCancel                      = ユーザーが操作をキャンセルしました。
	MatchMode                       = マッチ
	Failed                          = 失敗
	RandomSelect                    = ランダムに選択します
	RulePre                         = 事前設定ルール
	RuleOther                       = その他のルール
	RuleCustomize                   = カスタム ルール
	RuleCustomize_Dont              = マルチレベルカタログのカスタムルールを使用しない
	RuleCustomize_Dont_Tips         = 古いディレクトリを削除した後, "ネーミング・ルールの検証" をクリックします。
	RuleMultistage                  = マルチレベル ディレクトリ ルール
	RuleMultistageFindFailed        = 複数レベルのディレクトリ ルールは検出されず, テンプレートを作成します。
	RuleMultistageFindCreateNew     = 新しい複数レベルのディレクトリ ルール テンプレートを作成する
	RuleMultistageTips              = マルチレベル ディレクトリ ルールが自動的に適用され, {0} ディレクトリ ルールが無効になっています。
	RuleCustomizeNot                = 拡張機能名 (Solutions.Custom.Extension) は検出されませんでした。
	RuleCustomizeTips               = 新しいカスタム ルールは作成されていません。
	RuleMatchNoFindFolder           = 優先一致の後, 見つからなかった, 私はディレクトリを作成するポイント。
	RuleNoFindFile                  = 使用可能なファイルが見つからなかった場合は, 追加して更新します。
	RuleFindFolder                  = カタログが使用可能になると, 自動的に選択されます
	RuleNameNewChange               = 更新後に自動的に同期する
	RuleNewTempate                  = テンプレートの作成
	RuleSkipFolderCheck             = ディレクトリ内のファイルの存在をチェックしなくなりました，ファイルの種類
	RuleAuthon                      = ルールの作成者
	RuleGUID                        = GUID グローバル一意識別子
	RuleName                        = ルール名
	RuleDescription                 = 説明
	RuleNameUse                     = ルール名を次のものと同期します: {0}
	RuleISO                         = 元の InBox Apps インストール パッケージと一致します
	RuleInBoxApps                   = 完全でプロビジョニングされたアプリケーション
	RuleFileType                    = パッケージ名
	RuleFileFind                    = あいまいな検索名
	RuleFindError                   = {0} 項目が保留中であることが判明し, [依存関係の確認] をクリックして詳細を表示します。
	RuleSelectApps                  = ユーザーが選択したアプリケーション
	DependencyPackage               = 依存関係パッケージ
	RuleDependenciesRequired        = 必要な依存関係
	RuleDependenciesUnselected      = 選択されていない依存関係
	RuleDependenciesNoCheck         = 依存関係はチェックされなくなりました
	RuleDependenciesFix             = 選択されていない依存関係を修正します
	Extract_Tips                    = ヒント\n\n   1. 言語パックを抽出した結果は, メインの参照オブジェクトとして使用できません。\n\n   2. コンポーネント リストを主な参照オブジェクトとして使用してください。生成方法は次のとおりです：\n\n       [機能] で, [ビルド コンポーネント] (インストールされたイメージのパッケージを取得) を選択し, [印刷] または [インスタント ビュー] を選択します。\n\n   3. 言語パックをインストールしたら, コンポーネント レポートを再生成して, 対応しているかどうかを確認してください。

	DescendingRuleLang              = 逆の順序で言語パックを削除します
	OrderRuleLang                   = あらかじめ決められた順序で言語パックをインストールする
	OrderRuleLangTips               = 順に追加: 基本, フォント, 光学式文字認識, 手書き認識, テキスト読み上げ, 音声認識, 小売デモ体験, その他
	RuleLanguageTips                = 説明します: \n\n   「言語パックをルールの前の順序でインストールする」を使用した後, ファイルは次の順序であいまいな名前で自動的に照合されます。\n
	Match_installed_List            = 言語パックをインストールするときは, インストール済みリストからワイルドカードを使用してください
	Match_installed_List_Tips       = 一致するためにのみインストール: 基本, 光学式文字認識, 手書き認識, テキスト読み上げ, 音声認識。
	RuleLanguageTipsExt             = \n   「事前ルール順に言語パックをインストールする」を使用しない場合：\n   ディレクトリ内のすべてのファイルをファイルの種類で自動的に検索し, インストールします。\n\n   言語および地域のオンデマンド機能 (FOD)\n   https://learn.microsoft.com/ja-JP/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = 分類では
	Basic                           = 基本
	Fonts                           = フォント
	OCR                             = 光学式文字認識
	Handwriting                     = 手書き認識
	TextToSpeech                    = テキスト読み上げ
	Speech                          = 音声認識
	Retail                          = 小売デモ体験
	Features_On_Demand              = オンデマンド機能
	RegionSpecific                  = その他の地域固有の要件
	UnassignedLangFiles             = 割り当てられていないその他のファイル

	ProcessingImage                 = 画像を処理します：
	NoInstallImage                  = ローカルに存在しません
	ConvertChk                      = ファイルを確認してください
	WindowsFeature                  = Windows 関数
	Enable                          = 有効
	Disable                         = 無効
	EnableFeatureTips               = 提示\n\n    1, NetFx3 と TelnetClient が事前設定された有効な機能アイテムであることを示します。\n\n    2, 「マウント」後, さらに有効にすることができます。
	ViewLanguage                    = 画像の言語設定を表示する
	ImageLanguage                   = 画像言語設定
	OnlyLangCleanup                 = コンポーネントのクリーンアップ: 言語別にマークします
	Matched_Component_Names         = 一致したコンポーネント名: \
	BootProcess                     = {0}.wim を処理するとき
	Sync_Language_To                = 同期先
	BootSyncToISO                   = 言語パックをインストーラーに同期します
	BootSyncToISOTips               = オフライン イメージにインストールされている言語パックは, ISO インストーラに同期されます。
	LangIni                         = 再生する Lang.ini
	LangIniTips                     = 同期が完了したら, ISO の Lang .ini を再構築する必要があります。
	LangNewAutoSelect               = イベントが発生すると, 提案が自動的に選択されます
	LangNewAutoSelectTips           = [言語パックをインストーラーに同期する], [Lang .iniを再構築] が選択されている新しいイベントがあります。
	LangNewAutoNoSelect             = 新しいイベントがあり, [言語パックをインストーラに同期する], [Lang .iniを再構築] を選択することをお勧めします。
	LangNewAutoNoNewSelect          = 新しいイベントがない場合は, [言語パックをインストーラに同期する], [Lang .iniを再構築する] を選択しないことをお勧めします。
	Drive                           = ドライブ
	ViewDrive                       = インストールされているドライバーを表示する
	EditionsProductKey              = プロダクト キー
	Editions                        = 画像バージョン
	Assign_Editions                 = イメージのバージョンに基づいてアプリケーションを自動的に配布する
	EditionsChangeTips              = 警告, 画像バージョンを切り替える前に知っておいてください：\n\nMicrosoft 役務契約\nhttps://www.microsoft.com/ja-jp/servicesagreement/default.aspx\n\n言語の概要\nhttps://learn.microsoft.com/ja-jp/windows-hardware/manufacture/desktop/languages-overview\n\n次のバージョンを作成することは許可されていません。\n   1, 国別\n       ProfessionalCountrySpecific\n\n   2, 地域固有のホームバージョン\n       ProfessionalSingleLanguage\n\n違反した場合は起訴される可能性がありますので, 厳守してください。\n\n変換を主張する場合は, クリックして警告を受け入れ, [非表示の画像バージョンのロックを解除]をクリックします。
	EditionsChangeHide              = 非表示の画像バージョンのロックを解除する
	EditionsChangeAccect            = 私は警告を読み, 警告に関連する法律に対して単独で責任を負います

	SelFile                         = ファイルを選択します
	Rebuilding                      = 再建中
	RebuildAll                      = すべて再構築
	Export_Image                    = 輸出
	SelectFromError                 = エラー
	SelectFileFormatError           = ファイル形式が正しくありません

	SearchDrive                     = 検索ドライバ
	SearchUpdate                    = 検索の更新, 種類 ( {0} ), ソース:
	SelectFolder                    = ディレクトリを選択します
	DropFolder                      = ディレクトリを現在のウィンドウにドラッグできます
	DropFile                        = ファイルを現在のウィンドウにドラッグできます
	Sparse                          = 薄い
	CRCSHA                          = 確かめる
	Alternative                     = 代替ファイル名
	ChangeInstallDisk               = 自動選択ディスクを変更します
	Backup                          = バックアップ
	Restore                         = 復元

	# View
	ExportToLogs                    = ログにレポートを印刷する
	ExportShow                      = レポートを即座に表示
	MoreFeature                     = その他の機能
	OpenFolder                      = 開けるコンテンツ
	OpenFile                        = ファイルを開く
	Running                         = 走る
	Paste                           = コピーパス
	Clipboard_Copy                  = クリップボードにコピーされました
	ViewWIMFileInfo                 = 画像を見る
	GetInBoxApps                    = InBox Apps: インストールされたアプリケーション パッケージ
	GetImagePackage                 = コンポーネント: イメージにインストールされているすべてのパッケージ
	ViewMounted                     = マウントされたすべてのイメージに関する情報を取得します
'@