ConvertFrom-StringData -StringData @'
	# nl-NL
	# Dutch (Netherlands)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Dashboard
	Learn                           = Studie
	Menu                            = Menu
	Short_Cmd                       = Snelkoppeling commando
	Shortcut                        = Snelkoppeling
	Update                          = Vernieuwen
	CUpdate                         = Cumulatieve updates
	Rebuild                         = Wederopbouw
	AddTo                           = Toevoegen aan
	Del                             = Verwijderen
	Copy                            = Kopiëren
	Rename                          = Hernoemen
	Refresh                         = Vernieuwen
	RefreshModules                  = Heet vernieuw alle modules
	Done                            = Finish
	OK                              = Zeker
	Cancel                          = Annuleren
	AllSel                          = Selecteer alles
	AllClear                        = Alles wissen
	Setting                         = Opgezet
	Change                          = Wijziging
	Help                            = Hulp
	Logging                         = Logboek
	AvailableLanguages              = Beschikbare talen
	SwitchLanguage                  = Van taal wisselen
	LanguageSelRegion               = Selecteer uw land of regio
	LanguageRemember                = Onthoud de geselecteerde taal
	LanguageSearchNo                = Geen beschikbare talen gevonden
	LanguageNoPack                  = Als er lokaal geen taalpakket is, wordt het automatisch afgesloten.
	LanguageNoSel                   = Selecteer een regio
	Search                          = Zoekopdracht
	PleaseChoose                    = Selecteer alstublieft
	Options                         = Opties
	Choose                          = Gekozen
	NoChoose                        = Niet geselecteerd
	AdvOption                       = Optionele functies
	ExcludeItem                     = Uitsluiten per regel
	DeDuplication                   = Sluit duplicaten uit
	DeDuplication_Unlock            = Ontgrendel uitgeschakelde duplicaten
	Existed                         = Bestaat al
	FailedCreateFolder              = Kan map niet maken
	FailedCreateFile                = Kan bestand niet maken
	ToMsg                           = {0} Keer na enkele seconden automatisch terug naar het hoofdmenu.
	OnDemandPlanTask                = Aangepaste toewijzing van bekende gebeurtenissen
	Operable                        = Bedienbaar
	Inoperable                      = Onbruikbaar
	Hide                            = Verbergen
	CuringUpdate                    = Solide update
	CuringUpdateTips                = Zodra de update is bevestigd, kan deze niet meer worden verwijderd.
	Healthy                         = Gezond
	HealthyTips                     = Het is vooral belangrijk om de gezondheidsstatus te controleren. Wanneer "repareerbaar" of "onherstelbaar" verschijnt: Tijdens het ESD-conversieproces wordt fout 13 weergegeven en worden de gegevens ongeldig gerapporteerd bij het installeren van het systeem.
	Healthy_Save                    = Wanneer herstelbaar of onherstelbaar verschijnt, sla dan niet op.
	Repair                          = Reparatie
	IsAuto_Repair                   = Automatische reparatie toestaan ​​bij inactiviteit
	IsAuto_Repair_Tips              = Controleer automatisch of er montagetaken zijn na elke uitvoering van het verpakkingsscript. Als het is gemonteerd, wordt er geen reparatie uitgevoerd; als het niet is gemonteerd, wordt er automatisch gerepareerd.
	Repairable                      = Herstelbaar
	NonRepairable                   = Niet repareerbaar
	HealthyForceStop                = Tijdens het verwerken van de gebeurtenis is er een onomkeerbare fout opgetreden en is de gebeurtenis met geweld beëindigd.\n\n   Veroorzaakt belangrijkste problemen:\n\n      1. Fysieke hardware is beschadigd, harde schijf;\n\n      2. Als u een virtuele RAMDISK-geheugenschijf (inclusief hybride) gebruikt, controleer dan het fysieke geheugen;\n\n      3. Controleer de originele SHA256 van MVS (MSDN). Als deze consistent is, verander dan de map en probeer het opnieuw. Als de SHA256 inconsistent is, download deze dan opnieuw en probeer het opnieuw.\n\n      4. Anderen worden in dit voorbeeld niet vermeld.
	Superseded                      = Maak het vervangen schoon
	SupersededTips                  = Inclusief verouderde updates, componenten, enz.
	UnmountFailed                   = Ik heb verschillende methoden geprobeerd, maar er kan niets aan worden gedaan. Ik kan er alleen maar mee stoppen. Ik zou je graag de volgende keer willen zien.
	SaveTo                          = Opslaan naar
	WorkDone                        = Voltooid, druk op een willekeurige toets om terug te keren naar de hoofdinterface...
	UserCanel                       = De gebruiker heeft het verzoek geannuleerd.
	Uping                           = Genereren
	Exclude_View                    = Bekijk uitsluitingsregels
	User_Interaction                = Gebruikersinteractie
	Ok_Go_To                        = Beschikbaar voor
	Ok_Go_To_No                     = Ik ga niet

	Detailed                        = Gedetailleerd
	Detailed_View                   = Bekijk geselecteerde regeldetails

	AddEnv                          = Voeg routeringsfunctionaliteit toe aan systeemvariabelen
	AddEnvTips                      = Voer na het toevoegen Yi in een PowerShell-sessie in om te reageren. Voer bijvoorbeeld 'Yi -SIP' in om de inkapseling uit te voeren.

	Unzip_ISO                       = ISO uitpakken
	Unzip_Search_Type               = Zoekmap ( {0} )
	ISO_Other                       = Andere documenten
	Unzip_Language                  = Taalpakket
	Unzip_Fod                       = Functiepakket
	FileName                        = Bestandsnaam

	UserCancel                      = De gebruiker heeft de bewerking geannuleerd.
	MatchMode                       = Overeenkomst
	Failed                          = Mislukking
	RandomSelect                    = Willekeurig geselecteerd
	RulePre                         = Vooraf ingestelde regels
	RuleOther                       = Andere regels
	RuleCustomize                   = Aangepaste regels
	RuleCustomize_Dont              = Gebruik geen aangepaste directoryregels met meerdere niveaus
	RuleCustomize_Dont_Tips         = Nadat u de oude map hebt verwijderd, klikt u op 'Naamregels verifiëren'.
	RuleMultistage                  = Directoryregels op meerdere niveaus
	RuleMultistageFindFailed        = Er zijn geen directoryregels met meerdere niveaus gevonden. Klik op mij om een sjabloon te maken.
	RuleMultistageFindCreateNew     = Maak een nieuwe sjabloon voor directoryregels met meerdere niveaus
	RuleMultistageTips              = Mapregels op meerdere niveaus automatisch aanpassen, mapregel {0} is uitgeschakeld.
	RuleCustomizeNot                = Extensienaam (Solutions.Custom.Extension) niet gevonden. Raadpleeg de helpdocumentatie.
	RuleCustomizeTips               = Er is geen aangepaste regel gemaakt. Raadpleeg de Help-documentatie.
	RuleMatchNoFindFolder           = Kan de map niet matchen. Klik op mij om de map te maken.
	RuleNoFindFile                  = Geen beschikbare bestanden gevonden. Voeg toe en vernieuw.
	RuleFindFolder                  = Directory automatisch geselecteerd indien beschikbaar
	RuleNameNewChange               = Automatisch synchroniseren na updates
	RuleNewTempate                  = Sjabloon maken
	RuleSkipFolderCheck             = Er wordt niet langer gecontroleerd of het bestand in de directory bestaat en wat het bestandstype is
	RuleAuthon                      = Regelmaker
	RuleGUID                        = GUID wereldwijd unieke identificatie
	RuleName                        = Regelnaam
	RuleDescription                 = Beschrijven
	RuleNameUse                     = Regelnaam synchroniseren met: {0}
	RuleISO                         = Overeenkomen met het originele ISO-installatiepakket
	RuleInBoxApps                   = Volledige, vooraf geconfigureerde applicatie
	RuleFileType                    = Pakketnaam
	RuleFileFind                    = Vage zoeknaam
	RuleFindError                   = Er zijn {0} items gevonden die moeten worden verwerkt. Klik op 'Afhankelijkheden controleren' om de details te bekijken.
	RuleSelectApps                  = Applicaties geselecteerd door de gebruiker
	DependencyPackage               = Afhankelijkheidspakket
	RuleDependenciesRequired        = Vereiste afhankelijkheden
	RuleDependenciesUnselected      = Niet-geselecteerde afhankelijkheden
	RuleDependenciesNoCheck         = Afhankelijkheden worden niet meer gecontroleerd
	RuleDependenciesFix             = Afhankelijkheden repareren die niet zijn geselecteerd
	Extract_Tips                    = Hint\n\n   1. Het resultaat na het extraheren van het taalpakket kan niet als hoofdreferentieobject worden gebruikt;\n\n   2. Gebruik de componentenlijst als het belangrijkste referentieobject. Hoe te genereren:\n\n       In Functies selecteert u Component genereren (haal het pakket op in de geïnstalleerde image), selecteer Afdrukken of Direct bekijken;\n\n   3. Nadat u het taalpakket hebt geïnstalleerd, genereert u opnieuw een componentrapport om te controleren of dit overeenkomt;

	DescendingRuleLang              = Verwijder taalpakketten in omgekeerde volgorde
	OrderRuleLang                   = Installeer taalpakketten in een vooraf bepaalde volgorde
	OrderRuleLangTips               = Voeg in volgorde toe: Basis, Lettertypen, Optische tekenherkenning, Handschriftherkenning, Tekst-naar-spraak, Spraakherkenning, Retaildemo-ervaring, Overige
	RuleLanguageTips                = Opmerking:\n\n    Na het gebruik van "Installeer taalpakketten in vooraf bepaalde volgorde", worden bestanden automatisch gekoppeld aan vage namen in de volgende volgorde:\n
	Match_installed_List            = Wanneer u een taalpakket installeert, plaatst u dit in de geïnstalleerde lijst met jokertekens
	Match_installed_List_Tips       = Komt alleen overeen indien geïnstalleerd: Basis, Optische tekenherkenning, Handschriftherkenning, Tekst-naar-spraak, Spraakherkenning.
	RuleLanguageTipsExt             = \n   Wanneer u "Taalpakketten in vooraf bepaalde volgorde installeren" niet gebruikt: \n   Zoek automatisch alle bestanden in de map op bestandstype en installeer ze.\n\n   On-demand-functies voor taal en regio (FOD)\n   https://learn.microsoft.com/nl-nl/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Categorie
	Basic                           = Eenvoudig
	Fonts                           = Lettertype
	OCR                             = Optische karakterherkenning
	Handwriting                     = Handschriftherkenning
	TextToSpeech                    = Tekst naar spraak
	Speech                          = Spraakherkenning
	Retail                          = Retaildemo-ervaring
	Features_On_Demand              = Functies op aanvraag
	RegionSpecific                  = Andere regiospecifieke vereisten
	UnassignedLangFiles             = Niet-toegewezen diverse bestanden

	ProcessingImage                 = Verwerk de afbeelding:
	NoInstallImage                  = Bestaat lokaal niet
	ConvertChk                      = Controleer het bestand
	WindowsFeature                  = Windows-functies
	Enable                          = Inschakelen
	Disable                         = Uitzetten
	EnableFeatureTips               = Hint\n\n    1. Geef NetFx3 en TelnetClient weer als vooraf ingestelde functie-items;\n\n    2. Na het "monteren" kunnen er meer worden ingeschakeld.
	ViewLanguage                    = Bekijk de beeldtaalinstellingen
	ImageLanguage                   = Taalinstellingen voor afbeeldingen
	OnlyLangCleanup                 = Schone componenten: taggen op taal
	Matched_Component_Names         = Overeenkomende componentnaam:
	BootProcess                     = Bij het verwerken van {0}.wim
	Sync_Language_To                = Synchroniseren met
	BootSyncToISO                   = Synchroniseer taalpakketten met het installatieprogramma
	BootSyncToISOTips               = Het geïnstalleerde taalpakket van de offline-image wordt gesynchroniseerd met het ISO-installatieprogramma.
	LangIni                         = Lang.ini opnieuw genereren
	LangIniTips                     = Nadat de synchronisatie is voltooid, moet Lang.ini in de ISO opnieuw worden opgebouwd.
	LangNewAutoSelect               = Selecteer automatisch voorgestelde items wanneer er een gebeurtenis plaatsvindt
	LangNewAutoSelectTips           = Er zijn nieuwe evenementen, "Taalpakket synchroniseren met installatieprogramma", "Lang.ini opnieuw opbouwen" geselecteerd.
	LangNewAutoNoSelect             = Er zijn nieuwe evenementen. Het wordt aanbevolen dat u "Taalpakket synchroniseren met installatieprogramma" en "Lang.ini opnieuw opbouwen" selecteert.
	LangNewAutoNoNewSelect          = Er zijn geen nieuwe gebeurtenissen. Het wordt aanbevolen om niet "Taalpakket synchroniseren met installatieprogramma" of "Lang.ini opnieuw opbouwen" te selecteren.
	Drive                           = Drijfveer
	ViewDrive                       = Bekijk geïnstalleerde stuurprogramma's
	EditionsProductKey              = Productsleutel
	Editions                        = Afbeeldingsversie
	Assign_Editions                 = Applicaties automatisch distribueren op basis van afbeeldingsversies
	EditionsChangeTips              = Waarschuwing, begrijp het voordat u van afbeeldingsversie wisselt:\n\nMicrosoft Serviceovereenkomst\nhttps://www.microsoft.com/nl-nl/servicesagreement/default.aspx\n\nTaaloverzicht\nhttps://learn.microsoft.com/nl-nl/windows-hardware/manufacture/desktop/languages-overview\n\nJe mag geen versies maken van:\n   1. Landspecifiek\n       ProfessionalCountrySpecific\n\n   2. Regiospecifieke thuisversie\n       ProfessionalSingleLanguage\n\nHoud u hier strikt aan, want bij overtreding kunt u vervolgd worden.\n\nAls u toch wilt converteren, klikt u om de waarschuwing te accepteren en klikt u op "Ontgrendel versie van verborgen afbeeldingen".
	EditionsChangeHide              = Ontgrendel verborgen afbeeldingsversies
	EditionsChangeAccect            = Ik heb de waarschuwing gelezen en ben verantwoordelijk voor de relevante wetten in de waarschuwing

	SelFile                         = Selecteer bestand
	Rebuilding                      = Onder wederopbouw
	RebuildAll                      = Herbouw allemaal
	Export_Image                    = Exporteren
	SelectFromError                 = Fout
	SelectFileFormatError           = Bestandsformaat is onjuist

	SearchDrive                     = Zoek gedreven
	SearchUpdate                    = Zoekupdates, type ( {0} ), bron:
	SelectFolder                    = Selecteer map
	DropFolder                      = Kan mappen naar het huidige venster slepen
	DropFile                        = Bestanden kunnen naar het huidige venster worden gesleept
	Sparse                          = Zeldzaam
	CRCSHA                          = Rekening
	Alternative                     = Alternatieve bestandsnaam
	ChangeInstallDisk               = Wijzig de automatische schijfselectie

	# View
	ExportToLogs                    = Rapport afdrukken om te loggen
	ExportShow                      = Rapporten direct weergeven
	MoreFeature                     = Meer functies
	OpenFolder                      = Map openen
	OpenFile                        = Bestand openen
	Running                         = Loop
	Paste                           = Kopieer pad
	Clipboard_Copy                  = Gekopieerd naar klembord
	ViewWIMFileInfo                 = Bekijk afbeelding
	GetInBoxApps                    = InBox Apps: Geïnstalleerde applicatiepakketten
	GetImagePackage                 = Componenten: Alle pakketten die in de image zijn geïnstalleerd
	ViewMounted                     = Krijg informatie over alle gekoppelde afbeeldingen
'@