ConvertFrom-StringData -StringData @'
	# cs-cz
	# Czech (Czech Republic)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Dashboard
	Learn                           = Studie
	Menu                            = Menu
	Short_Cmd                       = Zkratky
	Shortcut                        = Zkratka
	Update                          = Obnovit
	CUpdate                         = Kumulativní aktualizace
	Rebuild                         = Rekonstrukce
	AddTo                           = Přidat do
	Del                             = Vymazat
	Copy                            = Kopie
	Rename                          = Přejmenovat
	Refresh                         = Osvěžit
	RefreshModules                  = Hot aktualizovat všechny moduly
	Done                            = Dokončit
	OK                              = Jasně
	Cancel                          = Zrušit
	AllSel                          = Vyberte vše
	AllClear                        = Vymazat vše
	Setting                         = Nastavit
	Change                          = Přeměna
	Help                            = Pomoc
	Logging                         = Log
	AvailableLanguages              = Dostupné jazyky
	SwitchLanguage                  = Přepnout jazyk
	LanguageSelRegion               = Vyberte svou zemi nebo oblast
	LanguageRemember                = Zapamatovat vybraný jazyk
	LanguageSearchNo                = Nebyly nalezeny žádné dostupné jazyky
	LanguageNoSel                   = Vyberte prosím region
	Search                          = Vyhledávání
	SearchAllDrives                 = Prohledat všechny disky
	MountCategory                   = Všechny nalezené a připojené ISO soubory
	PleaseChoose                    = Vyberte prosím
	Options                         = Možnosti
	Choose                          = Vybraný
	NoChoose                        = Nevybráno
	AdvOption                       = Volitelné funkce
	ExcludeItem                     = Vyloučit podle pravidla
	DeDuplication                   = Vyloučit duplikáty
	DeDuplication_Unlock            = Odemkněte zakázané duplikáty
	Existed                         = Již existuje
	FailedCreateFolder              = Vytvoření adresáře se nezdařilo
	FailedCreateFile                = Soubor se nepodařilo vytvořit
	ToMsg                           = {0} Po několika sekundách se automaticky vrátí do hlavní nabídky.
	OnDemandPlanTask                = Vlastní přiřazení známých událostí
	Operable                        = Operativní
	Inoperable                      = Nefunkční
	Hide                            = Skrýt
	CuringUpdate                    = Solidní aktualizace
	CuringUpdateTips                = Jakmile je aktualizace zpevněná, nelze ji odinstalovat.
	Healthy                         = Zdravý
	Healthy_Save                    = Když se objeví opravitelné nebo neopravitelné, neukládejte.
	Repair                          = Opravit
	IsAuto_Repair                   = Povolit automatickou opravu při nečinnosti
	IsAuto_Repair_Tips              = Po každém spuštění balícího skriptu automaticky zkontrolujte, zda existují nějaké montážní úlohy. Pokud je namontován, neprovede se žádná oprava, pokud nebude namontován, spustí se automatická oprava.
	Repairable                      = Opravitelné
	NonRepairable                   = Nelze opravit
	HealthyForceStop                = Při zpracování události došlo k nevratné chybě a proces byl násilně ukončen.\n\n   Způsobuje hlavní problémy: \n\n      1. Fyzický hardware je poškozen, pevný disk;\n\n      2. Pokud používáte paměťový virtuální disk RAMDISK (včetně hybridního), zkontrolujte fyzickou paměť;\n\n      3. Ověřte původní SHA256 MVS (MSDN), pokud je konzistentní, změňte adresář a zkuste to znovu. Pokud je SHA256 nekonzistentní, stáhněte si jej znovu a zkuste to znovu.\n\n      4. Ostatní nejsou v tomto příkladu uvedeny.
	Superseded                      = Vyčistěte vyměněné
	SupersededTips                  = Zahrnuje zastaralé aktualizace, komponenty atd.
	UnmountFailed                   = Zkoušel jsem několik metod, ale nedá se nic dělat.
	SaveTo                          = Uložit do
	WorkDone                        = Dokončeno, stisknutím libovolné klávesy se vraťte do hlavního rozhraní...
	UserCanel                       = Uživatel zrušil požadavek.
	Uping                           = Generování
	Exclude_View                    = Zobrazit pravidla vyloučení
	User_Interaction                = Interakce uživatele
	Ok_Go_To                        = K dispozici pro
	Ok_Go_To_No                     = Nechodím

	Detailed                        = Detailní
	View                            = Zobrazit
	Detailed_View                   = Zobrazit podrobnosti vybraného pravidla

	AddEnv                          = Přidejte do systémových proměnných funkci směrování
	AddEnvTips                      = Po přidání zadejte Yi v jakékoli relaci PowerShellu, abyste odpověděli, například zadejte "Yi -SIP" pro spuštění zapouzdření.

	Unzip_ISO                       = Extrahujte ISO
	Unzip_Search_Type               = Hledat v adresáři ( {0} )
	ISO_Other                       = Jiné dokumenty
	Unzip_Language                  = Jazykový balíček
	Unzip_Fod                       = Balíček funkcí
	FileName                        = Název souboru

	UserCancel                      = Uživatel operaci zrušil.
	MatchMode                       = Zápas
	Failed                          = Selhat
	RandomSelect                    = Náhodně vybrané
	RulePre                         = Přednastavená pravidla
	RuleOther                       = Jiná pravidla
	RuleCustomize                   = Vlastní pravidla
	RuleCustomize_Dont              = Nepoužívejte vlastní pravidla víceúrovňového adresáře
	RuleCustomize_Dont_Tips         = Po smazání starého adresáře klikněte na "Ověřit pravidla pojmenování".
	RuleMultistage                  = Víceúrovňová pravidla adresářů
	RuleMultistageFindFailed        = Nebyla nalezena žádná víceúrovňová pravidla pro adresář, kliknutím na mě vytvořte šablonu.
	RuleMultistageFindCreateNew     = Vytvořte novou šablonu víceúrovňového pravidla adresáře
	RuleMultistageTips              = Automaticky přizpůsobit víceúrovňová pravidla adresáře, pravidlo adresáře {0} bylo zakázáno.
	RuleCustomizeNot                = Název rozšíření (Solutions.Custom.Extension) nebyl nalezen, prostudujte si dokumentaci nápovědy.
	RuleCustomizeTips               = Nebylo vytvořeno žádné vlastní pravidlo, přečtěte si dokumentaci nápovědy.
	RuleMatchNoFindFolder           = Nepodařilo se najít shodu s adresářem, kliknutím na mě vytvořte adresář.
	RuleNoFindFile                  = Nebyly nalezeny žádné dostupné soubory, přidejte je a obnovte.
	RuleFindFolder                  = Adresář je automaticky vybrán, když je k dispozici
	RuleNameNewChange               = Automatická synchronizace po aktualizacích
	RuleNewTempate                  = Vytvořit šablonu
	RuleSkipFolderCheck             = Již nekontroluje, zda soubor existuje v adresáři a typ souboru
	RuleAuthon                      = Tvůrce pravidel
	RuleGUID                        = Globálně jedinečný identifikátor GUID
	RuleName                        = Název pravidla
	RuleDescription                 = Popsat
	RuleNameUse                     = Synchronizovat název pravidla do: {0}
	RuleISO                         = Odpovídají původnímu instalačnímu balíčku ISO
	RuleInBoxApps                   = Kompletní, předem nakonfigurovaná aplikace
	RuleFileType                    = Název balíčku
	RuleFileFind                    = Fuzzy vyhledávací jméno
	RuleFindError                   = Bylo nalezeno {0} položek ke zpracování, kliknutím na "Zkontrolovat závislosti" zobrazíte podrobnosti.
	RuleSelectApps                  = Aplikace vybrané uživatelem
	DependencyPackage               = Závislostní balíček
	RuleDependenciesRequired        = Požadované závislosti
	RuleDependenciesUnselected      = Nevybrané závislosti
	RuleDependenciesNoCheck         = Závislosti již nejsou kontrolovány
	RuleDependenciesFix             = Oprava závislostí není vybrána
	Extract_Tips                    = Náznak\n\n   1. Výsledek po extrahování jazykového balíčku nelze použít jako hlavní referenční objekt;\n\n   2. Použijte prosím seznam komponent jako hlavní referenční objekt Jak vygenerovat: \n\n       Vyberte vygenerovanou komponentu (získejte balíček v nainstalovaném obrazu) v Functions, vyberte tisk nebo zobrazení okamžitě;\n\n   3. Po instalaci jazykového balíčku prosím znovu vygenerujte sestavu komponent a zkontrolujte, zda odpovídá;

	DescendingRuleLang              = Vyjměte jazykové balíčky v opačném pořadí
	OrderRuleLang                   = Instalujte jazykové balíčky v předem určeném pořadí
	OrderRuleLangTips               = Přidejte v pořadí: Základní, Písma, Optické rozpoznávání znaků, Rozpoznávání rukopisu, Převod textu na řeč, Rozpoznávání řeči, Prodejní ukázka, Jiné
	RuleLanguageTips                = Ilustrovat: \n\n   Po použití "Instalovat jazykové balíčky v předem stanoveném pořadí" jsou soubory automaticky porovnávány s nejasnými názvy v následujícím pořadí:\n
	Match_installed_List            = Při instalaci jazykového balíčku použijte zástupný znak z nainstalovaného seznamu
	Match_installed_List_Tips       = Odpovídá pouze při instalaci: Základní, Optické rozpoznávání znaků, Rozpoznávání rukopisu, Převod textu na řeč, Rozpoznávání řeči.
	RuleLanguageTipsExt             = \n   Pokud nepoužíváte "Instalovat jazykové balíčky v předem stanoveném pořadí":\n   Automaticky vyhledat všechny soubory v adresáři podle typu souboru a nainstalovat je.\n\n   Funkce jazyka a regionu na vyžádání (FOD)\n   https://learn.microsoft.com/cs-cz/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategorie
	Basic                           = Základní
	Fonts                           = Písmo
	OCR                             = Optické rozpoznávání znaků
	Handwriting                     = Rozpoznávání rukopisu
	TextToSpeech                    = Textu na řeč
	Speech                          = Rozpoznávání řeči
	Retail                          = Maloobchodní demo zkušenost
	Features_On_Demand              = Funkce na vyžádání
	RegionSpecific                  = Další požadavky specifické pro region
	UnassignedLangFiles             = Nepřiřazené různé soubory

	ProcessingImage                 = Zpracujte obrázek: 
	NoInstallImage                  = Lokálně neexistuje
	ConvertChk                      = Zkontrolujte soubor
	WindowsFeature                  = Funkce Windows
	Enable                          = Umožnit
	Disable                         = Zakázat
	EnableFeatureTips               = Náznak\n\n    1. Zobrazte NetFx3 a TelnetClient jako přednastavené povolené funkční položky;\n\n    2. Po "připojení" lze povolit další.
	ViewLanguage                    = Zobrazení nastavení jazyka obrázku
	ImageLanguage                   = Nastavení jazyka obrázku
	OnlyLangCleanup                 = Čisté komponenty: tag podle jazyka
	Matched_Component_Names         = Odpovídající název komponenty:
	BootProcess                     = Při zpracování souboru {0}.wim
	Sync_Language_To                = Synchronizovat do
	BootSyncToISO                   = Synchronizujte jazykové balíčky s instalačním programem
	BootSyncToISOTips               = Nainstalovaný jazykový balíček offline obrazu je synchronizován s instalačním programem ISO.
	LangIni                         = Regenerujte Lang.ini
	LangIniTips                     = Po dokončení synchronizace je třeba znovu sestavit Lang.ini v ISO.
	LangNewAutoSelect               = Automaticky vybrat navrhované položky, když dojde k události
	LangNewAutoSelectTips           = Jsou zde nové události, vybráno "Synchronizovat jazykové balíčky s instalačním programem", "Znovu vytvořit Lang.ini".
	LangNewAutoNoSelect             = Jsou nové události, doporučujeme vybrat "Synchronizovat jazykový balíček s instalačním programem" a "Znovu vytvořit Lang.ini".
	LangNewAutoNoNewSelect          = Neexistují žádné nové události. Doporučuje se, abyste nevybírali "Synchronizovat jazykový balíček s instalačním programem" a "Přebudovat Lang.ini".
	Drive                           = Řídit
	ViewDrive                       = Zobrazit nainstalované ovladače
	Editions                        = Verze obrázku
	Assign_Editions                 = Automaticky distribuovat aplikace na základě verzí obrázků

	SelFile                         = Vyberte soubor
	Rebuilding                      = V rekonstrukci
	RebuildAll                      = Vše znovu postavit
	Export_Image                    = Vývozní
	SelectFromError                 = Chyba
	SelectFileFormatError           = Formát souboru je nesprávný

	SearchDrive                     = Řízený hledáním
	SearchUpdate                    = Hledat aktualizace, zadejte ( {0} ), zdroj: 
	SelectFolder                    = Vyberte adresář
	DropFolder                      = Může přetáhnout adresáře do aktuálního okna
	DropFile                        = Soubory lze přetáhnout do aktuálního okna
	Sparse                          = Vzácný
	CRCSHA                          = Kontrola
	Alternative                     = Alternativní název souboru
	ChangeInstallDisk               = Změňte automatický výběr disku
	Backup                          = Záloha
	Restore                         = Obnovení
	Import                          = Importovat

	# View
	ExportToLogs                    = Tisk sestavy k přihlášení
	ExportShow                      = Okamžité zobrazení zpráv
	MoreFeature                     = Další funkce
	OpenFolder                      = Otevřete adresář
	OpenFile                        = Otevřít soubor
	Running                         = Běh
	Paste                           = Kopírovat cestu
	Clipboard_Copy                  = Zkopírováno do schránky
	ViewWIMFileInfo                 = Zobrazit obrázek
	GetInBoxApps                    = InBox Apps: Nainstalované balíčky aplikací
	GetImagePackage                 = Komponenty: Všechny balíčky nainstalované v obrazu
	ViewMounted                     = Získejte informace o všech připojených obrazech
'@