ConvertFrom-StringData -StringData @'
	# tr-TR
	# Turkish (Turkey)

	UnpackISO                       = ISO oluştur
	ISOLabel                        = Birim etiketi ayarlandı:
	ISOCustomize                    = ISO birim etiketi adı
	ISO9660                         = Adlandırma kurallarını doğrulayın
	ISO9660Tips                     = Benzersiz ad 260 karakteri aşamaz, ISO birimi adı 16 karakteri aşamaz ve şunları içeremez: başta ve sonda boşluklar, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Özel benzersiz adlandırma
	ISOAddFlagsLang                 = Çok dilli işaretleme ekle
	ISOAddFlagsLangGet              = Bilinen kurulum dillerini edinin
	ISOAddFlagsVer                  = Çoklu sürüm etiketi ekle
	ISOAddFlagsVerGet               = Bilinen resim sürümünü edinin
	ISOAddEICFG                     = Sürüm türünü ekle
	ISOAddEICFGTips                 = EI.cfg'ye güvenildiğinde, bu ticari bir versiyondur.
	ISO9660TipsErrorSpace           = Şunları içeremez: baştaki ve sondaki boşluklar
	ISO9660TipsErrorOther           = Şunları içeremez: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Dil türünü seçin
	SelLabel                        = Kod adı
	ISOVerLabel                     = ISO birimi adını seçin
	NoSetLabel                      = Özel ISO birimi etiketi ayarlanmadı
	ISOLengthError                  = Birim etiketi {0} karakterden uzun olamaz
	RenameFailed                    = Eski dizinle aynı, yeniden adlandırma başarısız oldu
	ISOCreateAfter                  = ISO oluşturmadan önce yapmanız gerekenler
	ISOCreateRear                   = ISO oluşturduktan sonra yapmanız gerekenler
	BypassTPM                       = TPM kurulum kontrolünü atla
	Disable_BitLocker               = Kurulum sırasında BitLocker cihaz şifrelemesini devre dışı bırakın
	PublicDate                      = Veriliş tarihi
	PublicDateGetCurrent            = Geçerli tarihi senkronize et
	PublicYear                      = Yıl
	PublicMonth                     = Ay
	PublicYMSorting                 = Sıralama yaparken "ay-yıl" formatını "yıl-ay" olarak değiştirin.
	PublicYMSortingTips             = AB formatında sayı kullanırken alt çizgi _ eklemeyin.
	PublicYMUseShortNames           = Kısa isimler kullanın
	PublicYMUseNumbers              = Sayılar kullanın
	ISOCreateFailed                 = Oluşturma başarısız oldu, dizin okunamıyor veya yazılabilir değil.
	ISORefreshAuto                  = ISO etiketlerini her seferinde yenileyin
	ISOSaveTo                       = ISO varsayılan kaydetme konumu
	ISOSaveSameGlobal               = Genel ISO varsayılan kaydetme konumunu kullan
	ISOSaveSync                     = Görüntü kaynağı arama diskini seçtikten sonra yeni konumu otomatik olarak senkronize edin
	ISOSaveSame                     = Görüntü kaynağını kullanarak disk yolunu arayın
	ISOFolderWrite                  = Dizinin okunabilir ve yazılabilir olduğunu doğrulayın
	SelectAutoAvailable             = Kullanılabilir bir diski otomatik olarak seçerken
	SelectCheckAvailable            = Mevcut minimum kalan alanı kontrol edin
	ISOStructure                    = Yeni dizin yapısı
	ISOOSLevel                      = Kurulum türünü ekle
	ISOUniqueNameDirectory          = Benzersiz ad dizini ekle
	NextDoOperate                   = ISO oluşturmayın
	SelCreateISO                    = ISO oluşturun, talep üzerine çalıştırın
	Reconstruction                  = {0}.wim'i maksimum sıkıştırmayla yeniden oluşturun
	Reconstruction_Tips_Select      = Yeniden oluşturmadan önce, yalnızca yüklenmediğinde yürütülecektir. Kaydetmenin etkinleştirilmesini zorlayacak ve ardından bağlanan dosyanın bağlantısını kesecektir.
	ReconstructionTips              = 520 MB'ın üzerinde, yeniden oluşturma önerilir
	CreateASC                       = ISO'ya PGP imzası ekleme
	NoPGPKey                        = PGP'de kullanılabilir bir özel anahtar bulunmamaktadır.
	CreateASCPwd                    = Sertifika şifresi
	PasswordRenter                  = Şifreyi tekrar girin
	ShowPassword                    = Şifreyi göster
	NewPasswordSome                 = Şifre eşleşmiyor.
	PwdPermanent                    = Kalıcı depolama
	PwdDecfailed                    = Şifre çözme başarısız oldu
	CreateASCAuthor                 = Imzalayan
	CreateASCAuthorTips             = İmzalayan seçilmedi.
	ISO_Sparse_Rename               = Dosya adı uzantısına karma (hash) ekleyin.
	GenerateRandom                  = Rastgele sayılar oluştur
	RandomNumberReset               = Yenile
'@