ConvertFrom-StringData -StringData @'
	# lv-LV
	# Latvian (Latvia)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Informācijas panelis
	Learn                           = Pētījums
	Menu                            = Izvēlne
	Short_Cmd                       = Īsinājumtaustiņu komanda
	Shortcut                        = Īsceļu
	Update                          = Atjaunot
	CUpdate                         = Kumulatīvie atjauninājumi
	Rebuild                         = Rekonstrukcija
	AddTo                           = Pievienot
	Del                             = Dzēst
	Copy                            = Kopiju
	Rename                          = Pārdēvēt
	Refresh                         = Atsvaidzināt
	RefreshModules                  = Visu moduļu karstā atsvaidzināšana
	Done                            = Pabeigt
	OK                              = Protams
	Cancel                          = Atcelt
	AllSel                          = Atlasiet visu
	AllClear                        = Notīrīt visu
	Setting                         = Izveidot
	Change                          = Mainīt
	Help                            = Palīdzēt
	Logging                         = Saglabāt žurnālu uz
	AvailableLanguages              = Pieejamās valodas
	SwitchLanguage                  = Mainīt valodu
	LanguageSelRegion               = Izvēlieties savu valsti vai reģionu
	LanguageRemember                = Atcerieties izvēlēto valodu
	LanguageSearchNo                = Nav atrasta neviena pieejama valoda
	LanguageNoPack                  = Ja lokāli nav valodas pakotnes, tā tiks automātiski aizvērta.
	LanguageNoSel                   = Lūdzu, atlasiet reģionu
	Search                          = Meklēt
	PleaseChoose                    = Lūdzu, atlasiet
	Options                         = Iespējas
	Choose                          = Atlasīts
	NoChoose                        = Nav atlasīts
	AdvOption                       = Izvēles funkcijas
	ExcludeItem                     = Izslēgt ar noteikumu
	DeDuplication                   = Izslēdziet dublikātus
	DeDuplication_Unlock            = Atbloķējiet atspējotos dublikātus
	Existed                         = Jau pastāv
	FailedCreateFolder              = Neizdevās izveidot direktoriju
	FailedCreateFile                = Neizdevās izveidot failu
	ToMsg                           = {0} Pēc sekundēm automātiski atgriezieties galvenajā izvēlnē.
	OnDemandPlanTask                = Zināmo notikumu pielāgota piešķiršana
	Operable                        = Darbināms
	Inoperable                      = Nederīgs
	Hide                            = Paslēpties
	CuringUpdate                    = Stingrs atjauninājums
	CuringUpdateTips                = Kad atjauninājums ir nostiprināts, to nevar atinstalēt.
	Healthy                         = Vesels
	HealthyTips                     = Īpaši svarīgi ir pārbaudīt veselības stāvokli, kad parādās uzraksts "labojams" vai "nelabojams": ESD pārveidošanas procesa laikā tiek parādīta kļūda 13, un, instalējot sistēmu, tiek ziņots par kļūdu.
	Healthy_Save                    = Kad parādās labojams vai nelabojams, nesaglabājiet.
	Repair                          = Remonts
	IsAuto_Repair                   = Atļaut automātisku remontu tukšgaitā
	IsAuto_Repair_Tips              = Pēc katras pakotnes skripta izpildes automātiski pārbaudiet, vai ir kādi montāžas uzdevumi. Ja tas ir uzstādīts, remonts netiks veikts, ja tas nav uzstādīts, tiks palaists automātiskais remonts.
	Repairable                      = Remontējams
	NonRepairable                   = Nav labojams
	HealthyForceStop                = Apstrādājot notikumu, tika konstatēta neatgriezeniska kļūda, un notikums tika piespiedu kārtā pārtraukts. \n\n   Izraisa galvenās problēmas: \n\n      1. Bojāta fiziskā aparatūra, cietais disks;\n\n      2. Ja izmantojat RAMDISK atmiņas virtuālo disku (ieskaitot hibrīdu), lūdzu, pārbaudiet fizisko atmiņu;\n\n      3. Pārbaudiet MVS (MSDN) sākotnējo SHA256, lūdzu, mainiet direktoriju un mēģiniet vēlreiz.\n\n      4. Citi šajā piemērā nav minēti.
	Superseded                      = Notīriet nomainīto
	SupersededTips                  = Ietver novecojušus atjauninājumus, komponentus utt.
	UnmountFailed                   = Esmu izmēģinājis vairākas metodes, bet neko nevaru izdarīt. Es gribētu jūs redzēt nākamreiz.
	SaveTo                          = Saglabāt uz
	WorkDone                        = Pabeigts, nospiediet jebkuru taustiņu, lai atgrieztos galvenajā saskarnē...
	UserCanel                       = Lietotājs ir atcēlis pieprasījumu.
	Uping                           = Ģenerēšana
	Exclude_View                    = Skatiet izslēgšanas noteikumus
	User_Interaction                = Lietotāja mijiedarbība
	Ok_Go_To                        = Pieejams līdz
	Ok_Go_To_No                     = Neiet

	Detailed                        = Detalizēti
	Detailed_View                   = Skatiet atlasītās kārtulas informāciju

	AddEnv                          = Pievienojiet sistēmas mainīgajiem maršrutēšanas funkcionalitāti
	AddEnvTips                      = Pēc pievienošanas ievadiet Yi jebkurā PowerShell sesijā, lai atbildētu. Piemēram, ievadiet "Yi -SIP", lai palaistu iekapsulēšanu.

	Unzip_ISO                       = Izvilkt ISO
	Unzip_Search_Type               = Meklēt direktorijā ( {0} )
	ISO_Other                       = Citi dokumenti
	Unzip_Language                  = Valodu pakotne
	Unzip_Fod                       = Funkciju pakotne
	FileName                        = Faila nosaukums

	UserCancel                      = Lietotājs ir atcēlis darbību.
	MatchMode                       = Atbilst
	Failed                          = Neizdoties
	RandomSelect                    = Nejauši izvēlēts
	RulePre                         = Iepriekš iestatīti noteikumi
	RuleOther                       = Citi noteikumi
	RuleCustomize                   = Pielāgoti noteikumi
	RuleCustomize_Dont              = Neizmantojiet daudzlīmeņu direktoriju pielāgotās kārtulas
	RuleCustomize_Dont_Tips         = Pēc vecā direktorija dzēšanas noklikšķiniet uz "Pārbaudīt nosaukumu piešķiršanas noteikumus".
	RuleMultistage                  = Daudzlīmeņu direktoriju noteikumi
	RuleMultistageFindFailed        = Nav atrasts neviens vairāku līmeņu direktoriju kārtulas. Noklikšķiniet uz manis, lai izveidotu veidni.
	RuleMultistageFindCreateNew     = Izveidojiet jaunu daudzlīmeņu direktorija kārtulas veidni
	RuleMultistageTips              = Automātiski pielāgot vairāku līmeņu direktoriju kārtulas, {0} direktoriju kārtula ir atspējota.
	RuleCustomizeNot                = Paplašinājuma nosaukums (Solutions.Custom.Extension) nav atrasts, lūdzu, skatiet palīdzības dokumentāciju.
	RuleCustomizeTips               = Nav izveidota pielāgota kārtula. Lūdzu, skatiet palīdzības dokumentāciju.
	RuleMatchNoFindFolder           = Neizdevās saskaņot direktoriju. Noklikšķiniet uz manis, lai izveidotu direktoriju.
	RuleNoFindFile                  = Nav atrasts neviens pieejams fails, lūdzu, pievienojiet un atsvaidziniet.
	RuleFindFolder                  = Automātiski atlasīts direktorijs, kad tas ir pieejams
	RuleNameNewChange               = Automātiski sinhronizēt pēc atjauninājumiem
	RuleNewTempate                  = Izveidot veidni
	RuleSkipFolderCheck             = Vairs nepārbauda, vai fails pastāv direktorijā un faila tipu
	RuleAuthon                      = Noteikumu veidotājs
	RuleGUID                        = GUID globāli unikāls identifikators
	RuleName                        = Noteikuma nosaukums
	RuleDescription                 = Aprakstīt
	RuleNameUse                     = Sinhronizēt kārtulas nosaukumu ar: {0}
	RuleISO                         = Atbilst oriģinālajai ISO instalācijas pakotnei
	RuleInBoxApps                   = Pilnīga, iepriekš konfigurēta lietojumprogramma
	RuleFileType                    = Pakas nosaukums
	RuleFileFind                    = Neskaidrs meklēšanas nosaukums
	RuleFindError                   = Atrasti {0} apstrādājamie vienumi. Noklikšķiniet uz "Pārbaudīt atkarības", lai skatītu detalizētu informāciju.
	RuleSelectApps                  = Lietotāja atlasītās lietojumprogrammas
	DependencyPackage               = Atkarības pakete
	RuleDependenciesRequired        = Nepieciešamās atkarības
	RuleDependenciesUnselected      = Neatlasītas atkarības
	RuleDependenciesNoCheck         = Atkarības vairs netiek pārbaudītas
	RuleDependenciesFix             = Labot atkarības, kas nav atlasītas
	Extract_Tips                    = Mājienu\n\n   1. Rezultātu pēc valodas pakotnes izvilkšanas nevar izmantot kā galveno atsauces objektu;\n\n   2. Lūdzu, izmantojiet komponentu sarakstu kā galveno atsauces objektu. Kā ģenerēt:\n\n       Sadaļā Functions atlasiet Generate Component (iegūstiet pakotni instalētajā attēlā), atlasiet Drukāt vai Skatīt uzreiz;\n\n   3. Pēc valodas pakotnes instalēšanas, lūdzu, ģenerējiet komponenta ziņojumu, lai pārbaudītu, vai tas atbilst;

	DescendingRuleLang              = Noņemiet valodu pakotnes apgrieztā secībā
	OrderRuleLang                   = Instalējiet valodu pakotnes iepriekš noteiktā secībā
	OrderRuleLangTips               = Pievienot secībā: pamata, fonti, optiskā rakstzīmju atpazīšana, rokraksta atpazīšana, teksta pārveidošana runā, runas atpazīšana, mazumtirdzniecības demonstrācijas pieredze, cits
	RuleLanguageTips                = Ilustrēt:\n\n   Pēc opcijas "Valodu pakotņu instalēšana iepriekš noteiktā secībā" izmantošanas faili tiek automātiski saskaņoti ar neskaidriem nosaukumiem šādā secībā:\n
	Match_installed_List            = Instalējot valodas pakotni, instalētajā sarakstā izmantojiet aizstājējzīmi
	Match_installed_List_Tips       = Atbilst tikai pēc instalēšanas: pamata, optiskā rakstzīmju atpazīšana, rokraksta atpazīšana, teksta pārveidošana runā, runas atpazīšana。
	RuleLanguageTipsExt             = \n   Ja neizmantojat opciju Instalējiet valodu pakotnes iepriekš noteiktā secībā:\n   Automātiski meklējiet visus failus direktorijā pēc faila veida un instalējiet tos.\n\n   Valodas un reģiona funkcijas pēc pieprasījuma (FOD)\n   https://learn.microsoft.com/lv-lv/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategorija
	Basic                           = Pamata
	Fonts                           = Fontu
	OCR                             = Optiskā rakstzīmju atpazīšana
	Handwriting                     = Rokraksta atpazīšana
	TextToSpeech                    = Teksts uz runu
	Speech                          = Runas atpazīšana
	Retail                          = Mazumtirdzniecības demonstrācijas pieredze
	Features_On_Demand              = Funkcijas pēc pieprasījuma
	RegionSpecific                  = Citas reģionam specifiskas prasības
	UnassignedLangFiles             = Nepiešķirti dažādi faili

	ProcessingImage                 = Apstrādājiet attēlu:
	NoInstallImage                  = Lokāli nepastāv
	ConvertChk                      = Pārbaudiet failu
	WindowsFeature                  = Windows funkcijas
	Enable                          = Iespējot
	Disable                         = Atspējot
	EnableFeatureTips               = Mājienu\n\n    1. Parādīt NetFx3 un TelnetClient kā iepriekš iestatītus iespējotus funkciju elementus;\n\n    2. Pēc "montāžas" var iespējot vairāk.
	ViewLanguage                    = Skatiet attēla valodas iestatījumus
	ImageLanguage                   = Attēlu valodas iestatījumi
	OnlyLangCleanup                 = Tīri komponenti: atzīmējiet pēc valodas
	Matched_Component_Names         = Atbilstošs komponenta nosaukums:
	BootProcess                     = Apstrādājot failu {0}.wim
	Extract_Rule_Only_And_Full      = Izvilkt tikai atlasītās valodas
	Sync_Language_To                = Sinhronizēt ar
	BootSyncToISO                   = Sinhronizējiet valodu pakotnes ar instalētāju
	BootSyncToISOTips               = Bezsaistes attēla instalētā valodas pakotne tiek sinhronizēta ar ISO instalēšanas programmu.
	Setup_Fix_Missing               = Automātiski labojiet trūkstošos instalēšanas vienumus
	Setup_Fix_Missing_Tips          = Ja instalēšanas programmā trūkst arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui, atveriet "Extract", atlasiet "Rules" un noklikšķiniet uz "Extract Installer Missing Items".
	Setup_Fix_Missing_Extract       = Izvilkt instalētāja trūkstošos vienumus
	Setup_Fix_Missing_Extract_Tips  = Izņemiet instalētāja trūkstošos vienumus no visām vietējo valodu pakotnēm: arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui.
	LangIni                         = Atjaunot Lang.ini
	LangIniTips                     = Kad sinhronizācija ir pabeigta, ISO ir jāpārveido Lang.ini.
	LangNewAutoSelect               = Automātiski atlasīt ieteiktos vienumus, kad notiek notikums
	LangNewAutoSelectTips           = Ir jauni notikumi, atlasīts "Sinhronizēt valodas pakotni ar instalētāju", "Rebuild Lang.ini".
	LangNewAutoNoSelect             = Ir jauni notikumi, ieteicams atlasīt "Sinhronizēt valodas pakotni ar instalētāju" un "Rebuild Lang.ini".
	LangNewAutoNoNewSelect          = Nav jaunu notikumu. Ieteicams neatlasīt "Sinhronizēt valodas pakotni ar instalētāju" vai "Rebuild Lang.ini".
	Drive                           = Braukt
	ViewDrive                       = Skatīt instalētos draiverus
	EditionsProductKey              = Produkta atslēga
	Editions                        = Attēla versija
	Assign_Editions                 = Automātiski izplatīt lietojumprogrammas, pamatojoties uz attēlu versijām
	EditionsChangeTips              = Brīdinājums! Pirms attēla versiju maiņas, lūdzu, izprotiet:\n\nMicrosoft Pakalpojuma līgums\nhttps://www.microsoft.com/lv-lv/servicesagreement/default.aspx\n\nValodas pārskats\nhttps://learn.microsoft.com/lv-lv/windows-hardware/manufacture/desktop/languages-overview\n\nJums nav atļauts izveidot šādas versijas: \n   1. Konkrētas valsts\n       ProfessionalCountrySpecific\n\n   2. Reģionam raksturīga mājas versija\n       ProfessionalSingleLanguage\n\nLūdzu, stingri ievērojiet, jo pārkāpuma gadījumā pret jums var tikt ierosināta kriminālvajāšana.\n\nJa uzstājat uz konvertēšanu, noklikšķiniet, lai pieņemtu brīdinājumu, un noklikšķiniet uz "Atbloķēt slēptā attēla versiju".
	EditionsChangeHide              = Atbloķējiet slēpto attēlu versijas
	EditionsChangeAccect            = Esmu iepazinies ar brīdinājumu un esmu atbildīgs par attiecīgajiem likumiem, kas ietverti brīdinājumā

	SelFile                         = Izvēlieties failu
	Rebuilding                      = Rekonstrukcijas stadijā
	RebuildAll                      = Pārbūvēt visu
	Export_Image                    = Eksportēt
	SelectFromError                 = Kļūda
	SelectFileFormatError           = Faila formāts nav pareizs

	SearchDrive                     = Meklēšanu virza
	SearchUpdate                    = Meklēt atjauninājumus, veids ( {0} ), avots:
	SelectFolder                    = Izvēlieties direktoriju
	DropFolder                      = Var vilkt direktorijus uz pašreizējo logu
	DropFile                        = Failus var vilkt uz pašreizējo logu
	Sparse                          = Reti
	CRCSHA                          = Pārbaudīt
	Alternative                     = Alternatīvs faila nosaukums
	ChangeInstallDisk               = Mainiet automātisko diska izvēli

	# View
	ExportToLogs                    = Drukāt atskaiti, lai reģistrētos
	ExportShow                      = Tūlītēji parādiet pārskatus
	MoreFeature                     = Vairāk funkciju
	OpenFolder                      = Atvērt direktoriju
	OpenFile                        = Atvērt failu
	Running                         = Palaist
	Paste                           = Kopēt ceļu
	Clipboard_Copy                  = Kopēts starpliktuvē
	ViewWIMFileInfo                 = Skatīt attēlu
	GetInBoxApps                    = InBox Apps: instalētās lietojumprogrammu pakotnes
	GetImagePackage                 = Sastāvdaļas: visas attēlā instalētās pakotnes
	ViewMounted                     = Iegūstiet informāciju par visiem uzstādītajiem attēliem
'@