ConvertFrom-StringData -StringData @'
	# ar-SA
	# Arabic (Saudi Arabia)

	FontsUI                   = Segoe UI
	Mainname                  = محرك النشر: جناح Yi
	Learn                     = يذاكر
	MainHisName               = حل المكافأة
	Location                  = فتح الموقع
	About                     = عن
	Reset                     = إعادة ضبط
	AddTo                     = اضف إليه
	Instl                     = ثَبَّتَ
	ItInstalled               = تم التثبيت
	Close                     = إنهاء
	Auto                      = تلقائي
	Disable                   = إبطال
	Enable                    = يُمكَِن
	Setting                   = يثبت
	Restore                   = يتعافى
	Clean                     = تنظيف
	Operable                  = قابلة للتشغيل
	Inoperable                = غير صالح للعمل
	Optimize                  = تحسين
	Hide                      = يخفي
	Show                      = يعرض
	Del                       = يمسح
	Done                      = ينهي
	OK                        = بالتأكيد
	Cancel                    = يلغي
	AllSel                    = حدد الكل
	AllClear                  = مسح الكل
	Refresh                   = ينعش
	RefreshModules            = التحديث الساخن لجميع الوحدات
	Necessary                 = البرامج الأساسية
	MostUsedSoftware          = البرامج شائعة الاستخدام
	System                    = نظام
	Service                   = يخدم
	TaskBar                   = جميع أيقونات شريط المهام
	DeskIcon                  = أيقونات سطح المكتب
	InstallFonts              = تثبيت الخطوط
	SettingTo                 = اضبط على {0}
	Command                   = سطر الأوامر
	RuleName                  = اسم القاعدة
	Language                  = لغة
	AvailableLanguages        = اللغات المتاحة
	SwitchLanguage            = تبديل اللغة
	LanguageReset             = إعادة ضبط إعدادات اللغة
	LanguageCode              = علامة المنطقة
	LanguageSelRegion         = اختر بلدك أو منطقتك
	LanguageRemember          = تذكر اللغة المحددة
	LanguageSearchNo          = لم يتم العثور على اللغات المتاحة
	LanguageNoSel             = الرجاء تحديد المنطقة
	Search                    = يبحث
	PleaseChoose              = الرجاء التحديد
	FailedCreateFolder        = فشل في إنشاء الدليل
	Failed                    = يفشل
	ToMsg                     = {0} العودة تلقائيا إلى القائمة الرئيسية بعد ثواني.
	Restart                   = إعادة التشغيل تصبح نافذة المفعول
	AdvOption                 = ميزات اختيارية

	StartDown                 = ابدأ التنزيل
	ConnectTo                 = الاتصال ب
	FileName                  = اسم الملف
	SaveTo                    = حفظ ل
	NotAvailable              = الحالة: غير متوفر
	ExistingPacker            = لديك بالفعل حزمة التثبيت
	ExistingInstlPacker       = لديك بالفعل حزمة مضغوطة
	Unpacking                 = فك الضغط
	QucikRun                  = تشغيل سريع:
	WaitDone                  = في انتظار الانتهاء:
	Parameter                 = المعلمة:
	ErrorDown                 = حدث خطأ أثناء التنزيل
	UserCancel                = لقد ألغى المستخدم العملية.

	VerifyNameTips            = يُسمح فقط بمزيج من الحروف والأرقام الإنجليزية، ولا يُسمح بأي أحرف أخرى: مسافات، ولا يمكن أن يزيد الطول عن 16 حرفًا., \\ / : * ? & @ ! "" < > |
	FolderLabel               = بادئة الدليل المخصصة
	NoSetFolderLabel          = لم يتم تعيين بادئة الدليل المخصصة
	ISO9660TipsErrorSpace     = لا يمكن أن تحتوي على: مسافات بادئة وزائدة
	ISO9660TipsErrorOther     = لا يمكن أن تحتوي على: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = لا يمكن أن تزيد تسمية وحدة التخزين عن {0} حرفًا
	Help                      = يساعد
	WorkDone                  = اكتمل، اضغط على أي مفتاح للعودة إلى الواجهة الرئيسية...
	Short_Cmd                 = الاختصارات
	Options                   = خيارات
	LXPsWaitAssign            = ليتم تخصيصها
	Running                   = يجري
	SpecialFunction           = وظيفة PowerShell
'@