ConvertFrom-StringData -StringData @'
	# es-ES
	# Spanish (Spain)

	FontsUI                   = Segoe UI
	Mainname                  = Motor de implementación: suite de Yi
	Learn                     = Estudiar
	MainHisName               = Solución extra
	Location                  = Ubicación abierta
	About                     = Acerca de
	Reset                     = Reiniciar
	AddTo                     = Añadir
	Instl                     = Instalar
	ItInstalled               = Instalado
	Close                     = Cierre
	Auto                      = Automático
	Disable                   = Desactivar
	Enable                    = Permitir
	Setting                   = Configuración
	Restore                   = Recuperar
	CLearn                    = Limpiar
	Operable                  = Operable
	Inoperable                = Inoperable
	Optimize                  = Mejoramiento
	Hide                      = Esconder
	Show                      = Espectáculo
	Del                       = Borrar
	Done                      = Finalizar
	OK                        = Seguro
	Cancel                    = Cancelar
	AllSel                    = Seleccionar todo
	AllClear                  = Borrar todo
	Refresh                   = Refrescar
	RefreshModules            = Actualización en caliente de todos los módulos
	Necessary                 = Software esencial
	MostUsedSoftware          = Software de uso común
	System                    = Sistema
	Service                   = Atender
	TaskBar                   = Todos los iconos de la barra de tareas
	DeskIcon                  = Iconos de escritorio
	InstallFonts              = Instalar fuentes
	SettingTo                 = Establecer en {0}
	AvailableLanguages        = Idiomas disponibles
	SwitchLanguage            = Cambiar de idioma
	LanguageReset             = Restablecer la configuración de idioma
	LanguageCode              = Marca de zona
	LanguageSelRegion         = Seleccione su país o región
	LanguageRemember          = Recordar idioma seleccionado
	LanguageSearchNo          = No se encontraron idiomas disponibles
	LanguageNoPack            = Si no hay ningún paquete de idioma localmente, se cerrará automáticamente.
	LanguageNoSel             = Por favor seleccione una región
	Search                    = Buscar
	PleaseChoose              = Por favor seleccione
	FailedCreateFolder        = No se pudo crear el directorio
	Failed                    = Fallar
	ToMsg                     = {0} Regresa automáticamente al menú principal después de unos segundos.
	Restart                   = El reinicio tiene efecto
	AdvOption                 = Características opcionales

	StartDown                 = Empezar a descargar
	ConnectTo                 = Conéctate a
	FileName                  = Nombre del archivo
	SaveTo                    = Guardar en
	NotAvailable              = Estado: No disponible
	ExistingPacker            = Ya tengo el paquete de instalación.
	ExistingInstlPacker       = Ya tengo un paquete comprimido
	Unpacking                 = Descomprimiendo
	QucikRun                  = Ejecución rápida:
	WaitDone                  = Esperando finalización:
	Parameter                 = Parámetro:
	ErrorDown                 = Se produjo un error durante la descarga.
	UserCancel                = El usuario ha cancelado la operación.

	VerifyNameTips            = Solo se permite una combinación de letras y números en inglés, y no se permiten otros caracteres: espacios, la longitud no puede ser mayor a 16 caracteres, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Prefijo de directorio personalizado
	NoSetFolderLabel          = Prefijo de directorio personalizado no establecido
	ISO9660TipsErrorSpace     = No puede contener: espacios iniciales y finales
	ISO9660TipsErrorOther     = No puede contener: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = La etiqueta del volumen no puede tener más de {0} caracteres
	Help                      = Ayuda
	WorkDone                  = Completado, presione cualquier tecla para regresar a la interfaz principal...
	Short_Cmd                 = Atajos
	Options                   = Opciones
'@