ConvertFrom-StringData -StringData @'
	# ro-RO
	# Romanian (Romania)

	FontsUI                   = Segoe UI
	Mainname                  = Motor de implementare: suita lui Yi
	Learn                     = studiu
	MainHisName               = Soluție bonus
	Location                  = Deschide locația
	About                     = despre
	Reset                     = resetare
	AddTo                     = Adaugă la
	Instl                     = Instala
	ItInstalled               = Instalat
	Close                     = închidere
	Auto                      = automat
	Disable                   = Dezactivați
	Enable                    = permite
	Setting                   = înființat
	Restore                   = recupera
	CLearn                    = curăță
	Operable                  = Operabil
	Inoperable                = Inoperabil
	Optimize                  = optimizare
	Hide                      = ascunde
	Show                      = spectacol
	Del                       = şterge
	Done                      = Termina
	OK                        = Sigur
	Cancel                    = Anula
	AllSel                    = Selectați toate
	AllClear                  = șterge totul
	Refresh                   = reîmprospăta
	RefreshModules            = Actualizează la cald toate modulele
	Necessary                 = Software esențial
	MostUsedSoftware          = Software utilizat în mod obișnuit
	System                    = sistem
	Service                   = Servi
	TaskBar                   = Toate pictogramele din bara de activități
	DeskIcon                  = pictograme de pe desktop
	InstallFonts              = Instalați fonturi
	SettingTo                 = Setați la {0}
	AvailableLanguages        = Limbi disponibile
	SwitchLanguage            = schimba limba
	LanguageReset             = Resetați setările de limbă
	LanguageCode              = marcajul zonei
	LanguageSelRegion         = Selectați țara sau regiunea dvs
	LanguageRemember          = Amintiți-vă limba selectată
	LanguageSearchNo          = Nu s-au găsit limbi disponibile
	LanguageNoPack            = Dacă nu există un pachet de limbă local, acesta va ieși automat.
	LanguageNoSel             = Vă rugăm să selectați o regiune
	Search                    = Căutare
	PleaseChoose              = Vă rugăm să selectați
	FailedCreateFolder        = Nu s-a putut crea directorul
	Failed                    = Eșuează
	ToMsg                     = {0} Reveniți automat la meniul principal după câteva secunde.
	Restart                   = Repornirea are efect
	AdvOption                 = caracteristici opționale

	StartDown                 = Începeți descărcarea
	ConnectTo                 = Conectați-vă la
	FileName                  = nume de fișier
	SaveTo                    = salva la
	NotAvailable              = Stare: Indisponibil
	ExistingPacker            = Aveți deja pachetul de instalare
	ExistingInstlPacker       = Aveți deja un pachet comprimat
	Unpacking                 = Dezarhivare
	QucikRun                  = Executare rapidă:
	WaitDone                  = În așteptarea finalizării:
	Parameter                 = parametru:
	ErrorDown                 = A apărut o eroare în timpul descărcării
	UserCancel                = Utilizatorul a anulat operația.

	VerifyNameTips            = Este permisă doar o combinație de litere și numere în limba engleză și nu sunt permise alte caractere: spații, lungimea nu poate fi mai mare de 16 caractere, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Prefix de director personalizat
	NoSetFolderLabel          = Prefixul de director personalizat nu este setat
	ISO9660TipsErrorSpace     = Nu poate conține: spații de început și de final
	ISO9660TipsErrorOther     = Nu poate conține: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Eticheta de volum nu poate fi mai lungă de {0} caractere
	Help                      = Ajutor
	WorkDone                  = Finalizat, apăsați orice tastă pentru a reveni la interfața principală...
	Short_Cmd                 = Comenzi rapide
	Options                   = Opțiuni
'@