ConvertFrom-StringData -StringData @'
	# zh-CN
	# Chinese (Simplified, China)

	FontsUI                         = Microsoft YaHei UI

	# Main page
	Dashboard                       = 仪表板
	Learn                           = 学习
	Menu                            = 菜单
	Short_Cmd                       = 快捷指令
	Shortcut                        = 捷径
	Update                          = 更新
	CUpdate                         = 累积更新
	Rebuild                         = 重建
	AddTo                           = 添加
	Del                             = 删除
	Copy                            = 复制
	Rename                          = 重命名
	Refresh                         = 刷新
	RefreshModules                  = 热刷新所有模块
	Done                            = 完成
	OK                              = 确定
	Cancel                          = 取消
	AllSel                          = 选择所有
	AllClear                        = 清除所有
	Setting                         = 设置
	Change                          = 更改
	Help                            = 帮助
	Logging                         = 日志
	AvailableLanguages              = 可用语言
	SwitchLanguage                  = 切换语言
	LanguageSelRegion               = 选择您的国家或地区
	LanguageRemember                = 记住所选语言
	LanguageSearchNo                = 未搜索到可用的语言
	LanguageNoSel                   = 请选择区域
	Search                          = 搜索
	SearchAllDrives                 = 所有盘搜索
	MountCategory                   = 已搜索到的所有 ISO，挂载
	PleaseChoose                    = 请选择
	Options                         = 选项
	Choose                          = 已选择
	NoChoose                        = 未选择
	AdvOption                       = 可选功能
	ExcludeItem                     = 按规则排除
	DeDuplication                   = 排除重复项
	DeDuplication_Unlock            = 解锁已禁用重复项
	Existed                         = 已存在
	FailedCreateFolder              = 创建目录失败
	FailedCreateFile                = 创建文件失败
	ToMsg                           = {0} 秒后自动返回到主菜单。
	OnDemandPlanTask                = 自定义分配已知事件
	Operable                        = 可操作
	Inoperable                      = 不可操作
	Hide                            = 隐藏
	CuringUpdate                    = 固化更新
	CuringUpdateTips                = 已固化更新后将不可卸载。
	Healthy                         = 健康
	Healthy_Save                    = 出现可修复、不可修复时，不保存
	Repair                          = 修复
	IsAuto_Repair                   = 允许空闲时自动修复
	IsAuto_Repair_Tips              = 每次运行封装脚本后自动检查是否有任意挂载任务。如果有挂载就不执行修复；没有挂载就运行自动修复工作。
	Repairable                      = 可修复
	NonRepairable                   = 不可修复
	HealthyForceStop                = 处理事件时，遇到不可逆的错误，已强行终止。\n\n   造成主要的问题：\n\n      1、物理硬件受损，硬盘；\n\n      2、如果您使用 RAMDISK 内存虚拟盘（含混合），请检查物理内存；\n\n      3、校验 MVS (MSDN) 原版 SHA256，如果一致，请重新换目录后尝试，如果 SHA256 不一致，请重新下载后尝试；\n\n      4、其它，不在此例出的。
	Superseded                      = 清理取代的
	SupersededTips                  = 包括过时的更新、组件等
	UnmountFailed                   = 已经用过几种方法了，无能为力，小弟只能就此罢工了，愿与大侠下次江湖见。
	SaveTo                          = 保存到
	WorkDone                        = 完成，按任意键返回主界面...
	UserCanel                       = 用户已取消了请求。
	Uping                           = 生成中
	Exclude_View                    = 查看排除规则
	User_Interaction                = 用户交互
	Ok_Go_To                        = 可前往
	Ok_Go_To_No                     = 不前往

	Detailed                        = 详细
	View                            = 查看
	Detailed_View                   = 查看已选规则详细信息

	AddEnv                          = 将路由功能添加到系统变量
	AddEnvTips                      = 添加后在 PowerShell 任意会话里输入 Yi 即可响应，例如输入“Yi -SIP”即可运行封装。

	Unzip_ISO                       = 提取 ISO
	Unzip_Search_Type               = 搜索目录 ( {0} )
	ISO_Other                       = 其他文件
	Unzip_Language                  = 语言包
	Unzip_Fod                       = 功能包
	FileName                        = 文件名

	UserCancel                      = 用户已取消操作。
	MatchMode                       = 匹配
	Failed                          = 失败
	RandomSelect                    = 随机选择
	RulePre                         = 预置规则
	RuleOther                       = 其它规则
	RuleCustomize                   = 自定义规则
	RuleCustomize_Dont              = 不使用多级目录自定义规则
	RuleCustomize_Dont_Tips         = 删除旧目录后，点击“验证命名规则”。
	RuleMultistage                  = 多级目录规则
	RuleMultistageFindFailed        = 未发现有多级目录规则，点我创建模板。
	RuleMultistageFindCreateNew     = 创建新的多级目录规则模板
	RuleMultistageTips              = 自动适配多级目录规则，已禁用 {0} 目录规则。
	RuleCustomizeNot                = 未发现扩展名称（Solutions.Custom.Extension），请参阅帮助文档。
	RuleCustomizeTips               = 未创建自定义规则，请参阅帮助文档。
	RuleMatchNoFindFolder           = 匹配目录失败，点我创建目录。
	RuleNoFindFile                  = 未发现有可用的文件，请添加后刷新。
	RuleFindFolder                  = 目录可用时，自动选择
	RuleNameNewChange               = 更新后自动同步
	RuleNewTempate                  = 创建模板
	RuleSkipFolderCheck             = 不再检查目录里是否存在文件，文件类型
	RuleAuthon                      = 规则创建者
	RuleGUID                        = GUID 全局唯一标识符
	RuleName                        = 规则名称
	RuleDescription                 = 描述
	RuleNameUse                     = 同步规则名称到：{0}
	RuleISO                         = 匹配原始 ISO 安装包
	RuleInBoxApps                   = 完整，预配的应用程序
	RuleFileType                    = 软件包名称
	RuleFileFind                    = 模糊查找名
	RuleFindError                   = 发现 {0} 项待处理，点击“检查依赖项”查看详细。
	RuleSelectApps                  = 用户已选的应用程序
	DependencyPackage               = 依赖包
	RuleDependenciesRequired        = 所需要的依赖项
	RuleDependenciesUnselected      = 未选择的依赖项
	RuleDependenciesNoCheck         = 不再检查依赖项
	RuleDependenciesFix             = 修复未选择依赖项
	Extract_Tips                    = 提示\n\n   1、提取语言包后的结果，并不能做为主要参照对象；\n\n   2、请通过组件列表做为主要参照对象，如何生成：\n\n       在 Functions 里选择生成组件（获取已安装映像中的包），选择打印或即时查看；\n\n   3、安装完语言包后，请重新生成一份组件报告，查看是否已对应；

	DescendingRuleLang              = 按相反的顺序删除语言包
	OrderRuleLang                   = 按预规则顺序安装语言包
	OrderRuleLangTips               = 按顺序添加：基本、字体、光学字符识别、手写内容识别、文本转语音、语音识别、零售演示体验、其它
	RuleLanguageTips                = 说明：\n\n   使用“按预规则顺序安装语言包”后，按以下顺序自动按模糊名匹配文件：\n
	Match_installed_List            = 安装语言包时，从已安装列表里通配
	Match_installed_List_Tips       = 安装时仅匹配：基本、光学字符识别、手写内容识别、文字转语音、语音识别。
	RuleLanguageTipsExt             = \n   不使用“按预规则顺序安装语言包”时：\n   自动按文件类型，搜索目录下的所有文件，并安装。\n\n   语言和区域按需功能 (FOD)\n   https://learn.microsoft.com/zh-cn/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = 分类中
	Basic                           = 基本
	Fonts                           = 字体
	OCR                             = 光学字符识别
	Handwriting                     = 手写内容识别
	TextToSpeech                    = 文本转语音
	Speech                          = 语音识别
	Retail                          = 零售演示体验
	Features_On_Demand              = 按需功能
	RegionSpecific                  = 其他区域特定的要求
	UnassignedLangFiles             = 未分配的杂项文件

	ProcessingImage                 = 处理映像：
	NoInstallImage                  = 本地不存在
	ConvertChk                      = 检查文件
	WindowsFeature                  = Windows 功能
	Enable                          = 启用
	Disable                         = 禁用
	EnableFeatureTips               = 提示\n\n    1、显示 NetFx3、TelnetClient 是预置启用功能项；\n\n    2、“挂载”后，可启用更多的。
	ViewLanguage                    = 查看映像语言设置
	ImageLanguage                   = 映像语言设置
	OnlyLangCleanup                 = 清理组件：按语言标记
	Matched_Component_Names         = 已匹配组件名：
	BootProcess                     = 处理 {0}.wim 时
	Sync_Language_To                = 同步到
	BootSyncToISO                   = 同步语言包到安装程序
	BootSyncToISOTips               = 离线映像已安装的语言包，同步到 ISO 安装程序里。
	LangIni                         = 重新生成 Lang.ini
	LangIniTips                     = 同步完成后需重建 ISO 里的 Lang.ini。
	LangNewAutoSelect               = 有事件时自动选择建议项
	LangNewAutoSelectTips           = 有新事件，已选择“同步语言包到安装程序”、“重建 Lang.ini”。
	LangNewAutoNoSelect             = 有新事件，建议你选择“同步语言包到安装程序”、“重建 Lang.ini”。
	LangNewAutoNoNewSelect          = 没有新的事件，建议你不选择“同步语言包到安装程序”、“重建 Lang.ini”。
	Drive                           = 驱动
	ViewDrive                       = 查看已安装驱动
	Editions                        = 映像版本
	Assign_Editions                 = 自动根据映像版本分配应用程序

	SelFile                         = 选择文件
	Rebuilding                      = 重建中
	RebuildAll                      = 重建全部
	Export_Image                    = 导出
	SelectFromError                 = 错误
	SelectFileFormatError           = 文件格式不正确

	SearchDrive                     = 搜索驱动
	SearchUpdate                    = 搜索更新，类型 ( {0} ), 来源：
	SelectFolder                    = 选择目录
	DropFolder                      = 可托动目录到当前窗口
	DropFile                        = 可托动文件到当前窗口
	Sparse                          = 稀哈
	CRCSHA                          = 校验
	Alternative                     = 替代文件名
	ChangeInstallDisk               = 更改自动选择磁盘
	Backup                          = 备份
	Restore                         = 还原
	Import                          = 导入

	# View
	ExportToLogs                    = 打印报告到日志里
	ExportShow                      = 即时显示报表
	MoreFeature                     = 更多功能
	OpenFolder                      = 打开目录
	OpenFile                        = 打开文件
	Running                         = 运行
	Paste                           = 复制路径
	Clipboard_Copy                  = 已复制到剪贴板
	ViewWIMFileInfo                 = 查看映像
	GetInBoxApps                    = InBox Apps：已安装的应用程序包
	GetImagePackage                 = 组件：映像中已安装的所有包
	ViewMounted                     = 获取有关所有已挂载映像的信息
'@