ConvertFrom-StringData -StringData @'
	# sk-SK
	# Slovak (Slovakia)

	IsCreate                        = Vytvoriť
	Solution                        = Riešenie
	EnabledSoftwarePacker           = Zbierka
	EnabledUnattend                 = Treba odpovedať vopred
	EnabledEnglish                  = Motor nasadenia
	UnattendSelectVer               = Vyberte jazyk riešenia "Odpovedať".
	UnattendLangPack                = Vyberte jazykový balík "Riešenie".
	UnattendSelectSingleInstl       = Viacjazyčné, voliteľné počas inštalácie
	UnattendSelectMulti             = Viacjazyčný
	UnattendSelectDisk              = Vyberte riešenie Autounattend.xml
	UnattendSelectSemi              = Poloautomatický je platný pre všetky spôsoby inštalácie
	UnattendSelectUefi              = UEFI sa nainštaluje automaticky a je potrebné ho špecifikovať
	UnattendSelectLegacy            = Legacy sa automaticky nainštaluje a je potrebné ho špecifikovať
	NeedSpecified                   = Vyberte, čo je potrebné špecifikovať:
	OOBESetupOS                     = Inštalačné rozhranie
	OOBEProductKey                  = Produktový kľúč
	OOBEOSImage                     = Vyberte operačný systém, ktorý chcete nainštalovať
	OOBEEula                        = Prijmite licenčné podmienky
	OOBEDoNotServerManager          = Server Manager sa nespustí automaticky pri prihlásení
	OOBEIE                          = Konfigurácia rozšíreného zabezpečenia programu Internet Explorer
	OOBEIEAdmin                     = Zatvorte "Správca"
	OObeIEUser                      = Zavrieť "Používatelia"

	OOBE_Init_User                  = Prvý používateľ počas rozbaľovania
	OOBE_init_Create                = Vytvorte si vlastných používateľov
	OOBE_init_Specified             = Zadajte používateľa
	OOBE_Init_Autologin             = Automatické prihlásenie

	InstlMode                       = Spôsob inštalácie
	Business                        = Obchodná verzia
	BusinessTips                    = V závislosti od EI.cfg je potrebné zadať indexové číslo pre automatickú inštaláciu.
	Consumer                        = Spotrebiteľská verzia
	ConsumerTips                    = Nespolieha sa na EI.cfg Pri automatickej inštalácii je potrebné zadať sériové číslo.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [挂载到]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Pridať do systémového disku názov domovského adresára
	VerifyNameUse                   = Overte, či názov adresára nemôže obsahovať
	VerifyNameTips                  = Povolená je iba kombinácia anglických písmen a číslic a nesmie obsahovať: medzery, dĺžka nemôže byť väčšia ako 260 znakov, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Overenie zlyhalo, zadajte správne číslo.
	VerifyNameSync                  = Nastavte názov adresára ako primárne meno používateľa
	VerifyNameSyncTips              = Správca sa už nepoužíva.
	ManualKey                       = Vyberte alebo zadajte kód Product Key manuálne
	ManualKeyTips                   = Zadajte platný kód Product Key. Ak vybraný región nie je dostupný, skontrolujte ho na oficiálnej webovej lokalite spoločnosti Microsoft.
	ManualKeyError                  = Zadaný kód Product Key je neplatný.
	KMSLink1                        = Kľúč nastavení klienta KMS
	KMSUnlock                       = Zobraziť všetky známe sériové čísla KMS
	KMSSelect                       = Vyberte sériové číslo VOL
	KMSKey                          = Sériové číslo
	KMSKeySelect                    = Zmeňte sériové číslo produktu
	ClearOld                        = Vyčistite staré súbory
	SolutionsSkip                   = Preskočiť vytváranie riešenia
	SolutionsTo                     = Pridať "riešenie" do:
	SolutionsToMount                = Namontované alebo pridané do frontu
	SolutionsToError                = Niektoré funkcie boli deaktivované, ak ich potrebujete vynútiť, kliknite na tlačidlo "Odomknúť". \n\n
	UnlockBoot                      = Odomknúť
	SolutionsToSources              = Domovský adresár, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Vyberte verziu 'Deployment Engine'
	SolutionsEngineRegionaUTF8      = Beta: Globálna podpora jazykov pomocou Unicode UTF-8
	SolutionsEngineRegionaUTF8Tips  = Zdá sa, že po otvorení môže spôsobiť nové problémy. Neodporúča sa.
	SolutionsEngineRegionaling      = Zmeniť na nové miestne nastavenie:
	SolutionsEngineRegionalingTips  = Zmeňte miestne nastavenie systému, čo ovplyvní všetky používateľské účty v počítači.
	SolutionsEngineRegional         = Zmeňte miestne nastavenie systému
	SolutionsEngineRegionalTips     = Globálne predvolené: {0}, zmenené na: {1}
	SolutionsEngineCopyPublic       = Skopírujte verejné {0} do nasadenia
	SolutionsEngineCopyOpen         = Prehliadať umiestnenie verejného úložiska {0}
	EnglineDoneReboot               = Reštartujte počítač
	SolutionsTipsArm64              = Uprednostňuje sa balík arm64, ktorý si vyberáte v poradí: x64, x86.
	SolutionsTipsAMD64              = Uprednostňujte balíčky x64 v poradí: x86.
	SolutionsTipsX86                = Pridávajú sa iba balíčky x86.
	SolutionsReport                 = Vygenerujte správu pred nasadením
	SolutionsDeployOfficeInstall    = Nasaďte inštalačný balík balíka Microsoft Office
	SolutionsDeployOfficeChange     = Zmeňte konfiguráciu nasadenia
	SolutionsDeployOfficePre        = Predinštalovaná verzia balíka
	SolutionsDeployOfficeNoSelect   = Nie je vybratý žiadny predinštalačný balík balíka Office
	SolutionsDeployOfficeVersion    = Verzia {0}
	SolutionsDeployOfficeOnly       = Ponechajte si špecifikované jazykové balíčky
	SolutionsDeployOfficeSync       = Zachovať synchronizáciu jazyka s konfiguráciou nasadenia
	SolutionsDeployOfficeSyncTips   = Po synchronizácii inštalačný skript nedokáže určiť preferovaný jazyk.
	DeploySyncMainLanguage          = Synchronizujte s hlavným jazykom
	SolutionsDeployOfficeTo         = Nasaďte inštalačný balík na
	SolutionsDeployOfficeToPublic   = Verejná pracovná plocha
	DeployPackage                   = Nasaďte vlastný balík zbierky
	DeployPackageSelect             = Vyberte si predzbierkový balíček
	DeployPackageTo                 = Nasaďte predzbierkový balík do
	DeployToRoot                    = Systémový disk
	DeployPackageToSolutions        = V domovskom adresári riešenia
	DeployTimeZone                  = Časové pásmo
	DeployTimeZoneChange            = Zmeňte časové pásmo
	DeployTimeZoneChangeTips        = Nastavte predvolenú časovú oblasť, v ktorej sa má odpovedať na predbežné odpovede, podľa jazykovej oblasti.

	Deploy_Tags                     = Značka nasadenia
	FirstExpProcess                 = Prvá skúsenosť, predpoklady počas nasadenia:
	FirstExpProcessTips             = Po splnení predpokladov reštartujte počítač, aby sa vyriešil problém vyžadujúci reštart.
	FirstExpFinish                  = Prvá skúsenosť po splnení predpokladov
	FirstExpSyncMark                = Povoliť globálne vyhľadávanie a synchronizáciu značiek nasadenia
	FirstExpDefender                = Pridať domovský adresár do Defend vylúčené adresáre
	FirstExpSyncLabel               = Menovka systémového disku: Názov domovského adresára je rovnaký
	MultipleLanguages               = Pri stretnutí s viacerými jazykmi:
	NetworkLocationWizard           = Sprievodca umiestnením siete
	PreAppxCleanup                  = Blokujte úlohy údržby vyčistenia Appx
	LanguageComponents              = Zabráňte vyčisteniu nepoužívaných jazykových balíkov funkcií na požiadanie
	PreventCleaningUnusedLP         = Zabráňte čisteniu nepoužívaných jazykových balíkov
	FirstExpContextCustomize        = Pridať prispôsobené "kontextové menu"
	FirstExpContextCustomizeShift   = Podržte stlačený kláves Shift a kliknite pravým tlačidlom myši

	FirstExpFinishTips              = Po dokončení nasadenia nie sú žiadne dôležité udalosti. Odporúča sa zrušiť.
	FirstExpFinishPopup             = Otvorte hlavné rozhranie nástroja nasadenia
	FirstExpFinishOnDemand          = Povoliť prvý náhľad podľa plánu
	SolutionsEngineRestricted       = Obnoviť politiku vykonávania Powershell: obmedzené
	EnglineDoneClearFull            = Odstráňte celé riešenie
	EnglineDoneClear                = Odstráňte modul nasadenia a ponechajte ostatné

	Unattend_Auto_Fix_Next          = Keď na to nabudúce narazíte, automaticky vyberte potrebné položky, aby ste to automaticky opravili.
	Unattend_Auto_Fix               = Automaticky opraviť, keď nie sú vybrané predpoklady
	Unattend_Auto_Fix_Tips          = Keď pridáte nástroj nasadenia a nevyberiete príkaz prvého spustenia, automaticky sa opraví a vyberie: Politika vykonávania Powershell: spúšťajte nástroj nasadenia bez akýchkoľvek obmedzení.
	Unattend_Version_Tips           = Voliteľne zahrnúť iba, použiť predvolené na podporu ARM64, x64, x86.
	First_Run_Commmand              = Príkazy, ktoré sa majú spustiť pri prvom nasadení
	First_Run_Commmand_Setting      = Vyberte príkaz, ktorý chcete spustiť
	Command_Not_Class               = Pri filtrovaní už nie je automaticky kategorizované
	Command_WinSetup                = Inštalácia systému Windows
	Command_WinPE                   = Windows PE
	Command_Tips                    = Aplikáciu First Run App priraďte k: Inštalácia systému Windows, Windows PE\n\nVšimnite si, že po pridaní nástroja nasadenia musíte pri prvom spustení skontrolovať nasledovné: Politika vykonávania prostredia Powershell: Obmedzené, povoľte spúšťanie skriptov nástroja nasadenia.
	Waring_Not_Select_Command       = Pri pridávaní nástroja nasadenia nebola vybratá politika spúšťania Powershell: Nenastavujte žiadne obmedzenia a povoľte spustenie skriptu nástroja nasadenia, vyberte ho a skúste to znova, alebo kliknite na možnosť "Rýchla oprava nie je vybratá".
	Quic_Fix_Not_Select_Command     = Rýchla oprava nie je možnosť

	PowerShell_Unrestricted         = Politika vykonávania Powershell: žiadne obmedzenia
	Allow_Running_Deploy_Engine     = Povoliť spustenie skriptov nástroja nasadenia
'@