ConvertFrom-StringData -StringData @'
	# hu-HU
	# Hungarian (Hungary)

	Main_quests                     = Fő feladatok
	Side_quests                     = Alfeladatok
	SaveModeClear                   = A kiválasztott előzmények törlése
	SaveModeTipsClear               = Az előzmények mentésre kerültek, és törölhetők
	SelectTips                      = Célzás\n\n    1. Kérjük, válassza ki a feldolgozandó kép nevét;\n    2. A törlést követően azok a feladatok, amelyek működése előtt "beszerelést" igényelnek, nem lépnek életbe.
	CacheDisk                       = Lemez gyorsítótár
	CacheDiskCustomize              = Egyéni gyorsítótár elérési útja
	AutoSelectRAMDISK               = Automatikus lemezkötetcímke-választás engedélyezése
	AutoSelectRAMDISKFailed         = A kötetcímke nem egyezik
	ReFS_Find_Volume                = Ha a REFS lemezformátumot észleli, zárja ki
	ReFS_Exclude                    = ReFS partíció kizárva
	Disk_Not_satisfied_Exclude      = A minimális lemezterület-követelmények nem teljesülnek
	RAMDISK_Change                  = A kötetcímke nevének módosítása
	RAMDISK_Search                  = Kötetcímke nevének keresése
	RAMDISK_Restore                 = Az inicializált kötetnév visszaállítása: {0}
	AllowTopMost                    = Engedélyezze a nyitott ablakok rögzítését a tetejére
	History                         = Tiszta történelem
	History_Del_Tips                = Ha van egy beágyazási feladat, ne hajtsa végre a következő választható beállításokat, különben az ismeretlen problémákat okoz a beágyazási parancsfájl futtatása során.
	History_View                    = Előzmények megtekintése
	HistoryLog                      = Engedélyezze a 7 napnál régebbi rönkök automatikus tisztítását
	HistorySaveFolder               = Egyéb képforrás útvonalak
	HistoryClearappxStage           = InBox Apps: Törölje a telepítés során generált ideiglenes fájlokat
	DoNotCheckBoot                  = Ha a Boot.wim fájl mérete meghaladja az 520 MB-ot, az ISO generálásakor a rendszer automatikusan kiválasztja az újraépítést.
	HistoryClearDismSave            = Törölje a rendszerleíró adatbázisban mentett DISM csatolási rekordokat
	ImageSourcesClickShowKey        = "Elsődleges kulcs kiválasztása" menü megjelenítésének engedélyezése
	ImageSourcesClickShowKeyTips    = Miután a felhasználó kiválasztotta a kép forrását: Adjon hozzá egy "Elsődleges kulcs kiválasztása" menüt a jobb oldalon, és adjon hozzá "Ugrás" opciókat: Csatlakoztatás, Mentés, Felugró ablak.
	Clear_Bad_Mount                 = Törölje a sérült csatolt képfájlhoz tartozó összes erőforrást
	ShowCommand                     = Mutassa meg a teljes parancssori futtatást
	Command                         = Parancssor
	SelectSettingImage              = Képforrás
	NoSelectImageSource             = Nincs kiválasztva képforrás
	SettingImageRestore             = Az alapértelmezett beillesztési hely visszaállítása
	SettingImage                    = Módosítsa a képforrás rögzítési helyét
	SelectImageMountStatus          = A képforrás kiválasztása után kapja meg a csatlakoztatási állapotot
	SettingImageTempFolder          = Ideiglenes címtár
	SettingImageToTemp              = Az ideiglenes könyvtár megegyezik azzal a hellyel, ahová csatolták
	SettingImagePathTemp            = A Temp könyvtár használata
	SettingImageLow                 = Ellenőrizze a rendelkezésre álló minimális szabad helyet
	SettingImageNewPath             = Válassza ki a rögzítőlemezt
	SettingImageNewPathTips         = Javasoljuk, hogy memórialemezre csatlakoztassa, amely a leggyorsabb. Használhat olyan virtuális memóriaszoftvert, mint az Ultra RAMDisk és az ImDisk.
	SelectImageSource               = A "Motormegoldás telepítése" lehetőséget választotta, kattintson az OK gombra.
	NoImagePreSource                = Nem található elérhető forrás, a következőket kell tennie: \n\n     1. További képforrások hozzáadása a következőhöz:\n          {0}\n\n     2. Válassza a "Beállítások" lehetőséget, és válassza ki újra a képforrás keresőlemezét;\n\n     3. Válassza az "ISO" lehetőséget, és válassza ki a kicsomagolni kívánt ISO-t, a felhelyezni kívánt elemeket stb.
	NoImageOtherSource              = Kattintson rám más elérési utak "hozzáadásához" vagy "Drag Directory"-hoz az aktuális ablakhoz.
	SearchImageSource               = Képforrás kereső lemez
	Kernel                          = Kernel
	Architecture                    = Építészet
	ArchitecturePack                = Csomag architektúra, a hozzáadási szabályok megértése
	ImageLevel                      = Telepítés típusa
	LevelDesktop                    = Asztali
	LevelServer                     = Szerver
	ImageCodename                   = Kódnév
	ImageCodenameNo                 = Nem ismerik fel
	MainImageFolder                 = Főkönyvtár
	MountImageTo                    = Szerelje fel
	Image_Path                      = Képútvonal
	MountedIndex                    = Index
	MountedIndexSelect              = Válassza ki az indexszámot
	AutoSelectIndexFailed           = A(z) {0} index automatikus kiválasztása nem sikerült, próbálkozzon újra.
	Apply                           = Alkalmazás
	Eject                           = Felugrik
	Mount                           = Hegy
	ReMount                         = Újraszerelés
	Unmount                         = Távolítsa el
	Mounted                         = Felszerelt
	NotMounted                      = Nincs felszerelve
	NotMountedSpecify               = Nincs felszerelve, a rögzítési hely megadható
	MountedIndexError               = Rendellenes szerelés, törölje és próbálja újra.
	NeedsRemount                    = Újratelepítést igényel
	Invalid                         = Érvénytelen
	ImageSouresNoSelect             = További részletek megjelenítése a képforrás kiválasztása után
	Mounted_Mode                    = Mount mód
	Mounted_Status                  = Felszerelés állapota
	Status                          = Állapot
	Image_Popup_Default             = Mentse alapértelmezettként
	Image_Restore_Default           = Visszaállítás az alapértelmezettre
	Image_Popup_Tips                = Célzás:\n\nAz esemény hozzárendelésekor nem adja meg a feldolgozandó indexszámot {0};\n\nA kiválasztási felület jelenleg felbukkant. Kérjük, adja meg az indexszámot.
	Rule_Show_Full                  = Összes megjelenítése
	Rule_Show_Only                  = Csak szabályokat mutasson
	Rule_Show_Only_Select           = Válassz a szabályok közül
	Image_Unmount_After             = Távolítsa el az összes csatlakoztatott elemet

	Wim_Rule_Update                 = Fájlok kibontása és frissítése a képen belül
	Wim_Rule_Extract                = Fájlok kibontása
	Wim_Rule_Extract_Tips           = Az elérési útszabály kiválasztása után csomagolja ki a megadott fájlt, és mentse el helyileg.

	Wim_Rule_Verify                 = Ellenőrizni
	Wim_Rule_Check                  = Megvizsgálni
	Wim_Rule_CheckIntegrity         = Integritás ellenőrzése
	Wim_Rule_ReadOnly               = Csak olvasási jogosultság
	Wim_Rule_Optimize               = Optimalizálás
	ResetBase                       = Alapos tisztítás
	Wim_Rule_SupportEa              = Képek alkalmazása kiterjesztett attribútumokkal
	Wim_Rule_WIMBoot                = Indítható
	Wim_Rule_Compact                = Operációs rendszerfájlok tömörítése
	Win_Rule_Setbootable            = Kötetkép megjelölése indíthatóként
	Win_Rule_Setbootable_Tips       = Ez a paraméter csak Windows PE képekre vonatkozik.\nCsak egy kötetkép jelölhető meg indíthatóként egy .wim fájlban.
	Destination                     = Rendeltetési hely

	Wim_Append                      = Hozzáfűzés
	Wim_Capture                     = Rögzítés
	Wim_Capture_Tips                = A meghajtókép rögzítése egy új WIM fájlba.
	Wim_Capture_Sources             = Rögzítés forrása
	Wim_Capture_Sources_Tips        = A rögzített könyvtár tartalmazza az összes almappát és adatot.\nNem rögzíthet üres könyvtárat. A könyvtárnak legalább egy fájlt kell tartalmaznia.
	Wim_Config_File                 = Konfigurációs fájl elérési útja ( kizárások )
	Wim_Config_Edit                 = Szerkesztés
	Wim_Config_Learn                = A konfigurációs lista és a WimScript.ini fájl tanulmányozása

	Wim_Rename                      = Módosítsa a kép adatait
	Wim_Image_Name                  = Kép neve
	Wim_Image_Description           = Kép leírása
	Wim_Display_Name                = Megjelenített név
	Wim_Display_Description         = Leírás megjelenítése
	Wim_Edition                     = Képjel
	Wim_Edition_Select_Know         = Válassza ki az ismert képjelzőket
	Wim_CreatedTime                 = Létrehozás dátuma
	Wim_ModifiedTime                = Utolsó módosítás ideje
	Wim_FileCount                   = Fájlok száma
	Wim_DirectoryCount              = Könyvtárak száma
	Wim_Expander_Space              = Tágulási tér

	IABSelectNo                     = Nincs kiválasztva elsődleges kulcs: Install, WinRE, Boot
	Unique_Name                     = Egyedi elnevezés
	Select_Path                     = Útvonal
	Setting_Pri_Key                 = Állítsa be ezt a frissítési fájlt fő sablonként
	Pri_Key_Update_To               = Majd frissítsd a következőre
	Pri_Key_Template                = Állítsa be ezt a fájlt a kiválasztott elemekkel szinkronizálandó preferált sablonként
	Pri_key_Running                 = Az elsődleges kulcsfeladat szinkronizálása megtörtént, és kimaradt.
	ShowAllExclude                  = Az összes elavult kizárás megjelenítése

	Index_Process_All               = Az összes ismert indexszám feldolgozása
	Index_Is_Event_Select           = Esemény esetén felugrik az indexszám kiválasztási felület.
	Index_Pre_Select                = Előre hozzárendelt indexszám
	Index_Select_Tips               = Célzás:\n\nA {0}.wim jelenleg nincs felszerelve, a következőket teheti: \n\n   1. Válassza a "Minden ismert indexszám feldolgozása" lehetőséget;\n\n   2. Válassza ki a "Ha van esemény, megjelenik az indexszám kiválasztási felület";\n\n   3. Előre megadott indexszám\n      A 6 os indexszám van megadva, az indexszám nem létezik a feldolgozás során, és a feldolgozás kimarad.

	Index_Tips_Custom_Expand        = Csoport: {0}\n\nA(z) {1} feldolgozásakor a(z) {2} indexszámot hozzá kell rendelni, különben nem lehet feldolgozni.\n\nMiután kiválasztotta a "Frissítési szabályok szinkronizálása az összes indexszámhoz" lehetőséget, csak bármelyiket kell bejelölnie fősablonként.

	DefenderExclude                 = Windows víruskereső kizárások
	DefenderFolder                  = Adja hozzá ezt a könyvtárat a Windows víruskereső kizárásokhoz.
	DefenderVolume                  = Miután megtalálta a megfelelő kötetcímke nevet, adja hozzá ezt a lemezt a Windows víruskereső kizárásokhoz.
	DefenderIsAdd                   = Hozzáadva a Windows víruskereső kizárásokhoz
'@