ConvertFrom-StringData -StringData @'
	# fr-CA
	# French (Canada)

	FontsUI                   = Segoe UI
	Mainname                  = Moteur de déploiement: la suite Yi
	Learn                     = Étude
	MainHisName               = Solution boni
	Location                  = Emplacement ouvert
	About                     = À propos
	Reset                     = Réinitialiser
	AddTo                     = Ajouter à
	Instl                     = Installer
	ItInstalled               = Installé
	Close                     = Fermeture
	Auto                      = Automatique
	Disable                   = Désactiver
	Enable                    = Activer
	Setting                   = Installation
	Restore                   = Récupérer
	CLearn                    = Nettoyer
	Operable                  = Opérable
	Inoperable                = Inopérable
	Optimize                  = Optimisation
	Hide                      = Cacher
	Show                      = Montrer
	Del                       = Supprimer
	Done                      = Finition
	OK                        = Bien sûr
	Cancel                    = Annuler
	AllSel                    = Sélectionner tout
	AllClear                  = Effacer tout
	Refresh                   = Rafraîchir
	RefreshModules            = Rafraîchir à chaud tous les modules
	Necessary                 = Logiciel essentiel
	MostUsedSoftware          = Logiciels couramment utilisés
	System                    = Système
	Service                   = Servir
	TaskBar                   = Toutes les icônes de la barre des tâches
	DeskIcon                  = Icônes de bureau
	InstallFonts              = Installer les polices
	SettingTo                 = Définir à {0}
	AvailableLanguages        = Langues offertes
	SwitchLanguage            = Changer de langue
	LanguageReset             = Réinitialiser les paramètres de langue
	LanguageCode              = Marque de zone
	LanguageSelRegion         = Choisissez votre pays ou région
	LanguageRemember          = Mémoriser la langue sélectionnée
	LanguageSearchNo          = Aucune langue disponible trouvée
	LanguageNoPack            = S'il n'y a pas de module linguistique localement, il se fermera automatiquement.
	LanguageNoSel             = Veuillez choisir une région
	Search                    = Recherche
	PleaseChoose              = Veuillez choisir
	FailedCreateFolder        = Échec de la création du répertoire
	Failed                    = Échouer
	ToMsg                     = {0} Retour automatique au menu principal après quelques secondes.
	Restart                   = Le redémarrage entre en vigueur
	AdvOption                 = Fonctionnalités optionnelles

	StartDown                 = Commencer le téléchargement
	ConnectTo                 = Connectez-vous à
	FileName                  = Nom du fichier
	SaveTo                    = Enregistrer dans
	NotAvailable              = Statut: Non disponible
	ExistingPacker            = Vous disposez déjà d'un progiciel d'installation
	ExistingInstlPacker       = Vous avez déjà un paquet compressé
	Unpacking                 = Décompression
	QucikRun                  = Exécution rapide:
	WaitDone                  = En attente de finalisation:
	Parameter                 = Paramètre:
	ErrorDown                 = Une erreur s'est produite lors du téléchargement
	UserCancel                = L'utilisateur a annulé l'opération.

	VerifyNameTips            = Seule une combinaison de lettres et de chiffres anglais est permise, et aucun autre caractère n'est permis : espaces, la longueur ne peut pas dépasser 16 caractères, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Préfixe de répertoire personnalisé
	NoSetFolderLabel          = Préfixe de répertoire personnalisé non défini
	ISO9660TipsErrorSpace     = Ne peut pas contenir: des espaces de début et de fin
	ISO9660TipsErrorOther     = Ne peut pas contenir: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Le libellé du volume ne peut comporter plus de {0} caractères
	Help                      = Aide
	WorkDone                  = Terminé, appuyez sur n'importe quelle touche pour retourner à l'interface principale...
	Short_Cmd                 = Raccourcis
	Options                   = Possibilités
'@