ConvertFrom-StringData -StringData @'
	# pt-PT
	# Portuguese (Portugal)

	IsCreate                        = Criar
	Solution                        = Solução
	EnabledSoftwarePacker           = Coleção
	EnabledUnattend                 = Deveria responder com antecedência
	EnabledEnglish                  = Mecanismo de implantação
	UnattendSelectVer               = Selecione o idioma da solução 'Responder a'
	UnattendLangPack                = Selecione o pacote de idioma 'Solução'
	UnattendSelectSingleInstl       = Multilingue, opcional durante a instalação
	UnattendSelectMulti             = Multilíngue
	UnattendSelectDisk              = Selecione a solução Autounattend.xml
	UnattendSelectSemi              = Semiautomático é válido para todos os métodos de instalação
	UnattendSelectUefi              = O UEFI é instalado automaticamente e necessita de ser especificado
	UnattendSelectLegacy            = O legado é instalado automaticamente e necessita de ser especificado
	NeedSpecified                   = Selecione o que precisa de ser especificado:
	OOBESetupOS                     = Interface de instalação
	OOBEProductKey                  = Chave do produto
	OOBEOSImage                     = Selecione o sistema operativo para instalar
	OOBEEula                        = Aceite os termos da licença
	OOBEDoNotServerManager          = O Gestor do Servidor não inicia automaticamente no login
	OOBEIE                          = Configuração de segurança melhorada do Internet Explorer
	OOBEIEAdmin                     = Fechar "Administrador"
	OObeIEUser                      = Fechar "Utilizadores"

	OOBE_Init_User                  = Utilizador inicial durante a experiência de unboxing
	OOBE_init_Create                = Crie utilizadores personalizados
	OOBE_init_Specified             = Especifique o utilizador
	OOBE_Init_Autologin             = Login automático

	InstlMode                       = Método de instalação
	Business                        = Versão empresarial
	BusinessTips                    = Depende de EI.cfg, o número do índice necessita de ser especificado para a instalação automática.
	Consumer                        = Versão do consumidor
	ConsumerTips                    = Não depende de EI.cfg. O número de série necessita de ser especificado para a instalação automática.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [montar em]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Adicionar ao nome do diretório inicial do disco do sistema
	VerifyNameUse                   = Verifique se o nome do diretório não pode conter
	VerifyNameTips                  = Apenas é permitida uma combinação de letras e números em inglês e não pode conter: espaços, o comprimento não pode ser superior a 260 caracteres, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Falha na verificação.
	VerifyNameSync                  = Definir o nome do diretório como nome de utilizador principal
	VerifyNameSyncTips              = O administrador já não é usado.
	ManualKey                       = Selecione ou introduza a sua chave de produto manualmente
	ManualKeyTips                   = Introduza uma chave de produto válida Se a região selecionada não estiver disponível, aceda ao site oficial da Microsoft para verificar.
	ManualKeyError                  = A chave do produto que introduziu é inválida.
	KMSLink1                        = Chave de definições do cliente KMS
	KMSUnlock                       = Mostrar todos os números de série KMS conhecidos
	KMSSelect                       = Selecione o número de série do VOL
	KMSKey                          = Número de série
	KMSKeySelect                    = Alterar o número de série do produto
	ClearOld                        = Limpe os ficheiros antigos
	SolutionsSkip                   = Saltar a criação da solução
	SolutionsTo                     = Adicione 'solução' a:
	SolutionsToMount                = Montado ou adicionado à fila
	SolutionsToError                = Algumas funções foram desativadas. Se precisar de as forçar a utilizar, clique no botão "Desbloquear".\n\n
	UnlockBoot                      = Desbloquear
	SolutionsToSources              = Diretório inicial, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Selecione a versão do 'Deployment Engine'
	SolutionsEngineRegionaUTF8      = Beta: suporte global de idiomas utilizando Unicode UTF-8
	SolutionsEngineRegionaUTF8Tips  = Parece que pode causar novos problemas após a sua abertura. Não recomendado.
	SolutionsEngineRegionaling      = Mude para a nova localidade:
	SolutionsEngineRegionalingTips  = Altere a localidade do sistema, que afeta todas as contas de utilizador no computador.
	SolutionsEngineRegional         = Alterar localidade do sistema
	SolutionsEngineRegionalTips     = Padrão global: {0}, alterado para: {1}
	SolutionsEngineCopyPublic       = Copiar público {0} para implantação
	SolutionsEngineCopyOpen         = Procure o local do repositório público {0}
	EnglineDoneReboot               = Reinicie o seu computador
	SolutionsTipsArm64              = O pacote arm64 é o preferido e seleciona-se pela ordem: x64, x86.
	SolutionsTipsAMD64              = Prefira os pacotes x64, pela ordem: x86.
	SolutionsTipsX86                = Apenas os pacotes x86 são adicionados.
	SolutionsReport                 = Gerar relatório de pré-implantação
	SolutionsDeployOfficeInstall    = Implementar o pacote de instalação do Microsoft Office
	SolutionsDeployOfficeChange     = Alterar configuração de implementação
	SolutionsDeployOfficePre        = Versão do pacote pré-instalado
	SolutionsDeployOfficeNoSelect   = Nenhum pacote de pré-instalação do Office selecionado
	SolutionsDeployOfficeVersion    = {0} versão
	SolutionsDeployOfficeOnly       = Mantenha os pacotes de idiomas especificados
	SolutionsDeployOfficeSync       = Preservar a sincronização do idioma com a configuração de implementação
	SolutionsDeployOfficeSyncTips   = Após a sincronização, o script de instalação não consegue determinar o idioma preferencial.
	DeploySyncMainLanguage          = Sincronizar com o idioma principal
	SolutionsDeployOfficeTo         = Implemente o pacote de instalação em
	SolutionsDeployOfficeToPublic   = Área de trabalho pública
	DeployPackage                   = Implementar um pacote de recolha personalizado
	DeployPackageSelect             = Selecione um pacote de pré-recolha
	DeployPackageTo                 = Implemente o pacote de pré-recolha para
	DeployToRoot                    = Disco do sistema
	DeployPackageToSolutions        = No diretório inicial da solução
	DeployTimeZone                  = Fuso horário
	DeployTimeZoneChange            = Alterar fuso horário
	DeployTimeZoneChangeTips        = Defina o intervalo de tempo padrão onde as pré-respostas devem ser respondidas, por área de idioma.

	Deploy_Tags                     = Etiqueta de implantação
	FirstExpProcess                 = Primeira experiência, durante os pré-requisitos de implementação:
	FirstExpProcessTips             = Depois de cumprir os pré-requisitos, reinicie o computador para resolver o problema de exigir um reinício para entrar em vigor.
	FirstExpFinish                  = Experiência pela primeira vez, após completar os pré-requisitos
	FirstExpSyncMark                = Permitir pesquisa global e sincronização de tags de implementação
	FirstExpDefender                = Adicionar diretório inicial para defender diretórios eliminados
	FirstExpSyncLabel               = Rótulo do volume do disco do sistema: o nome do directório inicial é o mesmo
	MultipleLanguages               = Ao encontrar vários idiomas:
	NetworkLocationWizard           = Assistente de localização de rede
	PreAppxCleanup                  = Bloquear tarefas de manutenção de limpeza Appx
	LanguageComponents              = Impedir a limpeza de pacotes de idiomas de recursos on-demand não utilizados
	PreventCleaningUnusedLP         = Impedir a limpeza de pacotes de idiomas não utilizados
	FirstExpContextCustomize        = Adicione um "menu de contexto" personalizado
	FirstExpContextCustomizeShift   = Mantenha pressionada a tecla Shift e clique com o botão direito

	FirstExpFinishTips              = Não existem eventos importantes após a conclusão da implementação.
	FirstExpFinishPopup             = Abra a interface principal do motor de implementação
	FirstExpFinishOnDemand          = Permitir a primeira visualização, conforme planeado
	SolutionsEngineRestricted       = Política de execução de restauro do Powershell: restrita
	EnglineDoneClearFull            = Apague toda a solução
	EnglineDoneClear                = Apague o mecanismo de implantação e mantenha os outros

	Unattend_Auto_Fix_Next          = Da próxima vez que encontrar isto, selecione automaticamente os itens necessários para o corrigir automaticamente.
	Unattend_Auto_Fix               = Reparar automaticamente quando os pré-requisitos não são selecionados
	Unattend_Auto_Fix_Tips          = Ao adicionar o mecanismo de implementação e não selecionar o primeiro comando de execução, este é automaticamente reparado e selecionado: Política de execução do Powershell: executar o mecanismo de implementação sem quaisquer restrições.
	Unattend_Version_Tips           = Opcionalmente, inclua apenas, utilize o padrão para suportar ARM64, x64, x86.
	First_Run_Commmand              = Comandos a executar ao implantar pela primeira vez
	First_Run_Commmand_Setting      = Selecione o comando a executar
	Command_Not_Class               = Já não é categorizado automaticamente ao filtrar
	Command_WinSetup                = Instalação do Windows
	Command_WinPE                   = Windows PE
	Command_Tips                    = Atribua a aplicação First Run a: Instalação do Windows, Windows PE\n\nNote que quando um motor de implementação é adicionado, é necessário verificar o seguinte ao executar pela primeira vez: Política de execução do Powershell: Restrita, permite a execução de scripts do motor de implementação.
	Waring_Not_Select_Command       = Ao adicionar um mecanismo de implementação, a política de execução do Powershell não foi selecionada: Não defina nenhuma restrição e permita a execução do script do mecanismo de implementação.
	Quic_Fix_Not_Select_Command     = Correção rápida, não opção

	PowerShell_Unrestricted         = Política de execução do Powershell: sem restrições
	Allow_Running_Deploy_Engine     = Permitir a execução de scripts do motor de implementação
'@