ConvertFrom-StringData -StringData @'
	# tr-TR
	# Turkish (Turkey)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Kontrol Paneli
	Learn                           = Çalışmak
	Menu                            = Menü
	Short_Cmd                       = Kısayol komutu
	Shortcut                        = Kısayol
	Update                          = Yenilemek
	CUpdate                         = Toplu güncellemeler
	Rebuild                         = Yeniden yapılanma
	AddTo                           = A ekle
	Del                             = Silmek
	Copy                            = Kopyala
	Rename                          = Yeniden isimlendirmek
	Refresh                         = Yenileme
	RefreshModules                  = Tüm modülleri sıcak yenileme
	Done                            = Sona ermek
	OK                              = Elbette
	Cancel                          = İptal etmek
	AllSel                          = Tümünü seç
	AllClear                        = Hepsini temizle
	Setting                         = Kurmak
	Change                          = Değiştirmek
	Help                            = Yardım
	Logging                         = Kayıt
	AvailableLanguages              = Mevcut diller
	SwitchLanguage                  = Dili değiştir
	LanguageSelRegion               = Ülkenizi veya bölgenizi seçin
	LanguageRemember                = Seçilen dili hatırla
	LanguageSearchNo                = Kullanılabilir dil bulunamadı
	LanguageNoPack                  = Yerel olarak dil paketi yoksa otomatik olarak çıkılacaktır.
	LanguageNoSel                   = Lütfen bir bölge seçin
	Search                          = Aramak
	PleaseChoose                    = Lütfen seçin
	Options                         = Seçenekler
	Choose                          = Seçildi
	NoChoose                        = Seçilmedi
	AdvOption                       = Isteğe bağlı özellikler
	ExcludeItem                     = Kurala göre hariç tut
	DeDuplication                   = Yinelenenleri hariç tut
	DeDuplication_Unlock            = Devre dışı bırakılan kopyaların kilidini açın
	Existed                         = Zaten var
	FailedCreateFolder              = Dizin oluşturulamadı
	FailedCreateFile                = Dosya oluşturulamadı
	ToMsg                           = {0} Saniyeler sonra otomatik olarak ana menüye dönün.
	OnDemandPlanTask                = Bilinen olayların özel atanması
	Operable                        = Çalıştırılabilir
	Inoperable                      = Ameliyat edilemez
	Hide                            = Saklamak
	CuringUpdate                    = Sağlam güncelleme
	CuringUpdateTips                = Güncelleme sağlamlaştırıldıktan sonra kaldırılamaz.
	Healthy                         = Sağlıklı
	HealthyTips                     = Sağlık durumunu kontrol etmek özellikle önemlidir. "Onarılabilir" veya "onarılamaz" göründüğünde: ESD dönüştürme işlemi sırasında hata 13 istenir ve sistem kurulurken veriler geçersizdir;
	Healthy_Save                    = Onarılabilir veya onarılamaz göründüğünde kaydetmeyin.
	Repair                          = Tamirat
	IsAuto_Repair                   = Boştayken otomatik onarıma izin ver
	IsAuto_Repair_Tips              = Paketleme komut dosyasının her çalıştırılmasından sonra herhangi bir montaj görevinin olup olmadığını otomatik olarak kontrol edin. Takılıysa onarım yapılmaz, takılı değilse otomatik onarım yapılır.
	Repairable                      = Tamir edilebilir
	NonRepairable                   = Tamir edilemez
	HealthyForceStop                = Olay işlenirken geri dönüşü olmayan bir hatayla karşılaşıldı ve olay zorla sonlandırıldı.\n\n   Ana sorunlara neden olur: \n\n      1. Fiziksel donanım hasar görmüş, sabit disk;\n\n      2. RAMDISK bellek sanal diski (hibrit dahil) kullanıyorsanız, lütfen fiziksel belleği kontrol edin;\n\n      3. MVS'nin orijinal SHA256'sını (MSDN) doğrulayın. Tutarlıysa lütfen dizini değiştirin ve yeniden deneyin. SHA256 tutarsızsa lütfen yeniden indirin ve yeniden deneyin;\n\n      4. Diğerleri bu örnekte listelenmemiştir.
	Superseded                      = Değiştirilenleri temizleyin
	SupersededTips                  = Eski güncellemeler, bileşenler vb. içerir.
	UnmountFailed                   = Birkaç yöntem denedim ama hiçbir şey yapılamaz. Sadece vazgeçebilirim. Bir dahaki sefere seni görmek isterim.
	SaveTo                          = Kaydet
	WorkDone                        = Tamamlandı, ana arayüze dönmek için herhangi bir tuşa basın...
	UserCanel                       = Kullanıcı isteği iptal etti.
	Uping                           = Üretiliyor
	Exclude_View                    = Hariç tutma kurallarını görüntüle
	User_Interaction                = Kullanıcı etkileşimi
	Ok_Go_To                        = Şunun için mevcut:
	Ok_Go_To_No                     = Gitmiyorum

	Detailed                        = Ayrıntılı
	Detailed_View                   = Seçilen kural ayrıntılarını görüntüle

	AddEnv                          = Sistem değişkenlerine yönlendirme işlevi ekleyin
	AddEnvTips                      = Ekledikten sonra yanıt vermek için herhangi bir PowerShell oturumuna Yi girin. Örneğin, kapsüllemeyi çalıştırmak için "Yi -SIP" yazın.

	Unzip_ISO                       = ISO'yu çıkart
	Unzip_Search_Type               = Dizin Arama ( {0} )
	ISO_Other                       = Diğer belgeler
	Unzip_Language                  = Dil paketi
	Unzip_Fod                       = Özellik paketi
	FileName                        = Dosya adı

	UserCancel                      = Kullanıcı işlemi iptal etti.
	MatchMode                       = Kibrit
	Failed                          = Hata
	RandomSelect                    = Rastgele seçilmiş
	RulePre                         = Önceden belirlenmiş kurallar
	RuleOther                       = Diğer kurallar
	RuleCustomize                   = Özel kurallar
	RuleCustomize_Dont              = Çok düzeyli dizin özel kurallarını kullanmayın
	RuleCustomize_Dont_Tips         = Eski dizini sildikten sonra "Adlandırma Kurallarını Doğrula"yı tıklayın.
	RuleMultistage                  = Çok düzeyli dizin kuralları
	RuleMultistageFindFailed        = Çok düzeyli dizin kuralı bulunamadı, şablon oluşturmak için beni tıklayın.
	RuleMultistageFindCreateNew     = Yeni bir çok düzeyli dizin kuralı şablonu oluşturun
	RuleMultistageTips              = Çok düzeyli dizin kurallarını otomatik olarak uyarlayın, {0} dizin kuralı devre dışı bırakıldı.
	RuleCustomizeNot                = Uzantı adı (Solutions.Custom.Extension) bulunamadı, lütfen yardım belgelerine bakın.
	RuleCustomizeTips               = Özel kural oluşturulmadı, lütfen yardım belgelerine bakın.
	RuleMatchNoFindFolder           = Dizin eşleştirilemedi, dizini oluşturmak için beni tıklayın.
	RuleNoFindFile                  = Kullanılabilir dosya bulunamadı, lütfen ekleyin ve yenileyin.
	RuleFindFolder                  = Mevcut olduğunda otomatik olarak seçilen dizin
	RuleNameNewChange               = Güncellemelerden sonra otomatik olarak senkronize et
	RuleNewTempate                  = Şablon oluştur
	RuleSkipFolderCheck             = Artık dosyanın dizinde bulunup bulunmadığını ve dosya türünü kontrol etmiyor
	RuleAuthon                      = Kural oluşturucu
	RuleGUID                        = GUID genel olarak benzersiz tanımlayıcı
	RuleName                        = Kural adı
	RuleDescription                 = Betimlemek
	RuleNameUse                     = Kural adını şununla senkronize et: {0}
	RuleISO                         = Orijinal ISO kurulum paketini eşleştirin
	RuleInBoxApps                   = Eksiksiz, önceden yapılandırılmış uygulama
	RuleFileType                    = Paket adı
	RuleFileFind                    = Bulanık arama adı
	RuleFindError                   = İşlenecek {0} öğe bulundu, ayrıntıları görüntülemek için "Bağımlılıkları Kontrol Et"i tıklayın.
	RuleSelectApps                  = Kullanıcı tarafından seçilen uygulamalar
	DependencyPackage               = Bağımlılık paketi
	RuleDependenciesRequired        = Gerekli bağımlılıklar
	RuleDependenciesUnselected      = Seçilmemiş bağımlılıklar
	RuleDependenciesNoCheck         = Bağımlılıklar artık kontrol edilmiyor
	RuleDependenciesFix             = Seçili olmayan bağımlılıkları düzeltin
	Extract_Tips                    = Ipucu\n\n   1. Dil paketinin çıkarılmasından sonraki sonuç ana referans nesnesi olarak kullanılamaz;\n\n   2. Lütfen bileşen listesini ana referans nesnesi olarak kullanın. Nasıl oluşturulur:\n\n       İşlevler'de, Bileşen Oluştur'u seçin (kurulu görüntüdeki paketi edinin), Yazdır'ı veya Anında Görüntüle'yi seçin;\n\n   3. Dil paketini yükledikten sonra lütfen ilgili olup olmadığını kontrol etmek için bir bileşen raporu oluşturun;

	DescendingRuleLang              = Dil paketlerini ters sırayla kaldırın
	OrderRuleLang                   = Dil paketlerini önceden belirlenmiş sıraya göre yükleyin
	OrderRuleLangTips               = Sırayla ekleyin: Temel, Yazı Tipleri, Optik Karakter Tanıma, El Yazısı Tanıma, Metinden Konuşmaya, Konuşma Tanıma, Perakende Demo Deneyimi, Diğer
	RuleLanguageTips                = Örnek:\n\n   "Dil paketlerini önceden belirlenmiş sırayla yükle" seçeneğini kullandıktan sonra, dosyalar bulanık adlara göre aşağıdaki sırayla otomatik olarak eşleştirilir: \n
	Match_installed_List            = Bir dil paketi yüklerken yüklü listeden joker karakter ekleyin
	Match_installed_List_Tips       = Yalnızca yüklendiğinde eşleşir: Temel, Optik Karakter Tanıma, El Yazısı Tanıma, Metinden Konuşmaya, Konuşma Tanıma.
	RuleLanguageTipsExt             = \n   "Dil paketlerini önceden belirlenmiş sırayla yükle" seçeneğini kullanmadığınızda: \n   Dizindeki tüm dosyaları dosya türüne göre otomatik olarak arayın ve yükleyin.\n\n   İsteğe bağlı dil ve bölge özellikleri (FOD)\n   https://learn.microsoft.com/tr-tr/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategori
	Basic                           = Temel
	Fonts                           = Yazı tipi
	OCR                             = Optik karakter tanıma
	Handwriting                     = El yazısı tanıma
	TextToSpeech                    = Metinden konuşmaya
	Speech                          = Konuşma tanıma
	Retail                          = Perakende Demo Deneyimi
	Features_On_Demand              = İsteğe bağlı özellikler
	RegionSpecific                  = Bölgeye özgü diğer gereksinimler
	UnassignedLangFiles             = Atanmamış çeşitli dosyalar

	ProcessingImage                 = Görüntüyü işleyin:
	NoInstallImage                  = Yerel olarak mevcut değil
	ConvertChk                      = Dosyayı kontrol edin
	WindowsFeature                  = Windows özellikleri
	Enable                          = Olanak vermek
	Disable                         = Devre dışı bırakmak
	EnableFeatureTips               = Ipucu\n\n    1. NetFx3 ve TelnetClient'i önceden ayarlanmış etkin işlev öğeleri olarak görüntüleyin;\n\n    2. "Montaj" sonrasında daha fazlası etkinleştirilebilir.
	ViewLanguage                    = Görüntü dili ayarlarını görüntüle
	ImageLanguage                   = Görüntü dili ayarları
	OnlyLangCleanup                 = Bileşenleri temizleyin: dile göre etiketleyin
	Matched_Component_Names         = Eşleşen bileşen adı:
	BootProcess                     = {0}.wim işlenirken
	Sync_Language_To                = Senkronizasyon
	BootSyncToISO                   = Dil paketlerini yükleyiciyle senkronize edin
	BootSyncToISOTips               = Çevrimdışı görüntünün yüklü dil paketi, ISO yükleyiciyle senkronize edilir.
	LangIni                         = Lang.ini'yi yeniden oluştur
	LangIniTips                     = Senkronizasyon tamamlandıktan sonra ISO'daki Lang.ini'nin yeniden oluşturulması gerekiyor.
	LangNewAutoSelect               = Bir etkinlik meydana geldiğinde önerilen öğeleri otomatik olarak seç
	LangNewAutoSelectTips           = Yeni etkinlikler var, "Dil paketini yükleyiciye senkronize et", "Lang.ini'yi Yeniden Oluştur" seçili.
	LangNewAutoNoSelect             = Yeni etkinlikler var, "Dil paketini yükleyiciyle senkronize et" ve "Lang.ini'yi Yeniden Oluştur" seçeneğini seçmeniz önerilir.
	LangNewAutoNoNewSelect          = Yeni etkinlik yok "Dil paketini yükleyiciyle senkronize et" veya "Lang.ini'yi yeniden oluştur" seçeneğini seçmemeniz önerilir.
	Drive                           = Sürmek
	ViewDrive                       = Yüklü sürücüleri görüntüle
	EditionsProductKey              = Ürün anahtarı
	Editions                        = Resim sürümü
	Assign_Editions                 = Uygulamaları görüntü sürümlerine göre otomatik olarak dağıtın
	EditionsChangeTips              = Uyarı, resim versiyonlarını değiştirmeden önce lütfen şunu anlayın:\n\nMicrosoft 服务协议\nhttps://www.microsoft.com/tr-tr/servicesagreement/default.aspx\n\nDile genel bakış\nhttps://learn.microsoft.com/tr-tr/windows-hardware/manufacture/desktop/languages-overview\n\nAşağıdakilerin sürümlerini oluşturmanıza izin verilmiyor: \n   1. Ülkeye özgü\n       ProfessionalCountrySpecific\n\n   2. Bölgeye özgü ev sürümü\n       ProfessionalSingleLanguage\n\nİhlal etmeniz durumunda kovuşturmaya maruz kalabileceğiniz için lütfen kurallara harfiyen uyun.\n\nDönüştürme konusunda ısrarcıysanız, uyarıyı kabul etmek için tıklayın ve "Gizli resim sürümünün kilidini aç" seçeneğine tıklayın.
	EditionsChangeHide              = Gizli resim sürümlerinin kilidini açın
	EditionsChangeAccect            = Uyarıyı okudum ve uyarıda yer alan ilgili yasalardan sorumluyum.

	SelFile                         = Dosya seç
	Rebuilding                      = Yeniden yapılanma aşamasında
	RebuildAll                      = Hepsini yeniden oluştur
	Export_Image                    = İhracat
	SelectFromError                 = Hata
	SelectFileFormatError           = Dosya formatı yanlış

	SearchDrive                     = Arama odaklı
	SearchUpdate                    = Güncellemeleri arayın, ( {0} ) yazın, kaynak:
	SelectFolder                    = Dizin seçin
	DropFolder                      = Dizinleri geçerli pencereye sürükleyebilir
	DropFile                        = Dosyalar geçerli pencereye sürüklenebilir
	Sparse                          = Nadir
	CRCSHA                          = Kontrol etmek
	Alternative                     = Alternatif dosya adı
	ChangeInstallDisk               = Otomatik disk seçimini değiştir

	# View
	ExportToLogs                    = Günlüğe rapor yazdır
	ExportShow                      = Raporları anında görüntüleyin
	MoreFeature                     = Daha fazla özellik
	OpenFolder                      = Dizini aç
	OpenFile                        = Dosyayı aç
	Running                         = Koşmak
	Paste                           = Yolu kopyala
	Clipboard_Copy                  = Panoya kopyalandı
	ViewWIMFileInfo                 = Resmi görüntüle
	GetInBoxApps                    = InBox Apps: Yüklü uygulama paketleri
	GetImagePackage                 = Bileşenler: Görüntüde kurulu tüm paketler
	ViewMounted                     = Monte edilen tüm görüntüler hakkında bilgi alın
'@