ConvertFrom-StringData -StringData @'
	# nl-NL
	# Dutch (Netherlands)

	UnpackISO                       = ISO genereren
	ISOLabel                        = Volumelabel is ingesteld:
	ISOCustomize                    = ISO-volumelabelnaam
	ISO9660                         = Controleer de naamgevingsregels
	ISO9660Tips                     = De unieke naam mag niet langer zijn dan 260 tekens, de ISO-volumenaam mag niet langer zijn dan 16 tekens en mag niet het volgende bevatten: voorloop- en volgspaties, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Aangepaste unieke naamgeving
	ISOAddFlagsLang                 = Voeg meertalige opmaak toe
	ISOAddFlagsLangGet              = Zorg dat u bekende installatietalen krijgt
	ISOAddFlagsVer                  = Voeg een tag voor meerdere versies toe
	ISOAddFlagsVerGet               = Bekende afbeeldingsversie verkrijgen
	ISOAddEICFG                     = Versietype toevoegen
	ISOAddEICFGTips                 = Als u op EI.cfg vertrouwt, is het een commerciële versie.
	ISO9660TipsErrorSpace           = Mag niet bevatten: voorloop- en volgspaties
	ISO9660TipsErrorOther           = Mag niet bevatten: \\ / : * ? & @ "" < > |
	SelOSver                        = Selecteer taaltype
	SelLabel                        = Codenaam
	ISOVerLabel                     = Selecteer ISO volumenaam
	NoSetLabel                      = Aangepast ISO volumelabel niet ingesteld
	ISOLengthError                  = Volumelabel mag niet langer zijn dan {0} tekens
	RenameFailed                    = Hetzelfde als de oude map, hernoemen mislukt
	ISOCreateAfter                  = Wat u moet doen voordat u een ISO maakt
	ISOCreateRear                   = Wat u moet doen nadat u de ISO hebt gemaakt
	BypassTPM                       = Omzeil de TPM-installatiecontrole
	Disable_BitLocker               = Schakel BitLocker-apparaatversleuteling uit tijdens de installatie
	PublicDate                      = Uitgiftedatum
	PublicDateGetCurrent            = Synchroniseer de huidige datum
	PublicYear                      = Jaar
	PublicMonth                     = Maan
	PublicYMSorting                 = Sorteren: Wijzig "maand_jaar" in "jaar_maand"
	PublicYMSortingTips             = AB: Voeg geen underscore _ toe bij het gebruik van getallen.
	PublicYMUseShortNames           = Gebruik korte namen
	PublicYMUseNumbers              = Gebruik getallen
	ISOCreateFailed                 = Het maken is mislukt, de map is niet leesbaar of beschrijfbaar.
	ISORefreshAuto                  = Vernieuw ISO-tags elke keer
	ISOSaveTo                       = ISO standaard opslaglocatie
	ISOSaveSameGlobal               = Gebruik de algemene ISO-standaardopslaglocatie
	ISOSaveSync                     = Synchroniseer automatisch de nieuwe locatie na het selecteren van de zoekschijf voor de beeldbron
	ISOSaveSame                     = Zoek schijfpad met behulp van de afbeeldingsbron
	ISOFolderWrite                  = Controleer of de directory leesbaar en beschrijfbaar is
	SelectAutoAvailable             = Bij het automatisch selecteren van een beschikbare schijf
	SelectCheckAvailable            = Controleer de minimaal beschikbare resterende ruimte
	ISOStructure                    = Nieuwe mapstructuur
	ISOOSLevel                      = Installatietype toevoegen
	ISOUniqueNameDirectory          = Voeg een unieke naammap toe
	NextDoOperate                   = Maak geen ISO
	SelCreateISO                    = ISO genereren, uitvoeren op aanvraag
	Reconstruction                  = Herbouw {0}.wim met maximale compressie
	Reconstruction_Tips_Select      = Voordat het opnieuw wordt opgebouwd, wordt het alleen uitgevoerd als het niet is geladen. Het zal het opslaan forceren en vervolgens het aangekoppelde bestand ontkoppelen.
	ReconstructionTips              = Meer dan 520 MB, opnieuw opbouwen aanbevolen
	CreateASC                       = Voeg PGP-handtekening toe aan ISO
	NoPGPKey                        = Er bestaat geen bruikbare privésleutel in PGP.
	CreateASCPwd                    = Certificaatwachtwoord
	PasswordRenter                  = Voer het wachtwoord opnieuw in
	ShowPassword                    = Wachtwoord weergeven
	NewPasswordSome                 = Wachtwoord komt niet overeen.
	PwdPermanent                    = Permanente opslag
	PwdDecfailed                    = Ontsleuteling mislukt
	CreateASCAuthor                 = Ondertekenaar
	CreateASCAuthorTips             = Geen ondertekenaars geselecteerd.
	ISO_Sparse_Rename               = Voeg een hashtag toe aan de bestandsextensie.
	GenerateRandom                  = Genereer willekeurige getallen
	RandomNumberReset               = Regenereer
'@