ConvertFrom-StringData -StringData @'
	# pt-BR
	# Portuguese (Brazil)

	IsCreate                        = Criar
	Solution                        = Solução
	EnabledSoftwarePacker           = Coleção
	EnabledUnattend                 = Deveria responder com antecedência
	EnabledEnglish                  = Mecanismo de implantação
	UnattendSelectVer               = Selecione o idioma da solução 'Responder a'
	UnattendLangPack                = Selecione o pacote de idiomas 'Solução'
	UnattendSelectSingleInstl       = Multilíngue, opcional durante a instalação
	UnattendSelectMulti             = Multilíngue
	UnattendSelectDisk              = Selecione a solução Autounattend.xml
	UnattendSelectSemi              = Semiautomático é válido para todos os métodos de instalação
	UnattendSelectUefi              = UEFI é instalado automaticamente e precisa ser especificado
	UnattendSelectLegacy            = O legado é instalado automaticamente e precisa ser especificado
	NeedSpecified                   = Selecione o que precisa ser especificado:
	OOBESetupOS                     = Interface de instalação
	OOBEProductKey                  = Chave do produto
	OOBEOSImage                     = Selecione o sistema operacional para instalar
	OOBEEula                        = Aceite os termos da licença
	OOBEDoNotServerManager          = O Gerenciador do Servidor não inicia automaticamente no login
	OOBEIE                          = Configuração de segurança aprimorada do Internet Explorer
	OOBEIEAdmin                     = Fechar "Administrador"
	OObeIEUser                      = Fechar "Usuários"

	OOBE_Init_User                  = Usuário inicial durante a experiência de unboxing
	OOBE_init_Create                = Crie usuários personalizados
	OOBE_init_Specified             = Especifique o usuário
	OOBE_Init_Autologin             = Login automático

	InstlMode                       = Método de instalação
	Business                        = Versão empresarial
	BusinessTips                    = Depende de EI.cfg, o número do índice precisa ser especificado para instalação automática.
	Consumer                        = Versão do consumidor
	ConsumerTips                    = Não depende de EI.cfg. O número de série precisa ser especificado para instalação automática. Ao pausar na interface de seleção de versão, o número de índice precisa ser especificado.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [montar em]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Adicionar ao nome do diretório inicial do disco do sistema
	VerifyNameUse                   = Verifique se o nome do diretório não pode conter
	VerifyNameTips                  = Somente uma combinação de letras e números em inglês é permitida e não pode conter: espaços, o comprimento não pode ser superior a 260 caracteres, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Falha na verificação. Insira o número correto.
	VerifyNameSync                  = Definir o nome do diretório como nome de usuário principal
	VerifyNameSyncTips              = O administrador não é mais usado.
	ManualKey                       = Selecione ou insira sua chave de produto manualmente
	ManualKeyTips                   = Insira uma chave de produto válida. Se a região selecionada não estiver disponível, acesse o site oficial da Microsoft para verificar.
	ManualKeyError                  = A chave do produto que você inseriu é inválida.
	KMSLink1                        = Chave de configurações do cliente KMS
	KMSUnlock                       = Mostrar todos os números de série KMS conhecidos
	KMSSelect                       = Selecione o número de série do VOL
	KMSKey                          = Número de série
	KMSKeySelect                    = Alterar o número de série do produto
	ClearOld                        = Limpe arquivos antigos
	SolutionsSkip                   = Pular a criação da solução
	SolutionsTo                     = Adicione 'solução' a:
	SolutionsToMount                = Montado ou adicionado à fila
	SolutionsToError                = Algumas funções foram desativadas. Se você precisar forçá-las a usar, clique no botão "Desbloquear".\n\n
	UnlockBoot                      = Desbloquear
	SolutionsToSources              = Diretório inicial, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Selecione a versão do 'Deployment Engine'
	SolutionsEngineRegionaUTF8      = Beta: suporte global a idiomas usando Unicode UTF-8
	SolutionsEngineRegionaUTF8Tips  = Parece que pode causar novos problemas após abri-lo. Não recomendado.
	SolutionsEngineRegionaling      = Mude para a nova localidade:
	SolutionsEngineRegionalingTips  = Altere a localidade do sistema, que afeta todas as contas de usuário no computador.
	SolutionsEngineRegional         = Alterar localidade do sistema
	SolutionsEngineRegionalTips     = Padrão global: {0}, alterado para: {1}
	SolutionsEngineCopyPublic       = Copie público {0} para implantação
	SolutionsEngineCopyOpen         = Procure o local do repositório público {0}
	EnglineDoneReboot               = Reinicie seu computador
	SolutionsTipsArm64              = O pacote arm64 é o preferido e você seleciona na ordem: x64, x86.
	SolutionsTipsAMD64              = Prefira pacotes x64, na ordem: x86.
	SolutionsTipsX86                = Somente pacotes x86 são adicionados.
	SolutionsReport                 = Gerar relatório de pré-implantação
	SolutionsDeployOfficeInstall    = Implantar o pacote de instalação do Microsoft Office
	SolutionsDeployOfficeChange     = Alterar configuração de implantação
	SolutionsDeployOfficePre        = Versão do pacote pré-instalado
	SolutionsDeployOfficeNoSelect   = Nenhum pacote de pré-instalação do Office selecionado
	SolutionsDeployOfficeVersion    = {0} versão
	SolutionsDeployOfficeOnly       = Mantenha os pacotes de idiomas especificados
	SolutionsDeployOfficeSync       = Preservar a sincronização do idioma com a configuração de implantação
	SolutionsDeployOfficeSyncTips   = Após a sincronização, o script de instalação não consegue determinar o idioma preferencial.
	DeploySyncMainLanguage          = Sincronize com o idioma principal
	SolutionsDeployOfficeTo         = Implante o pacote de instalação em
	SolutionsDeployOfficeToPublic   = Área de trabalho pública
	DeployPackage                   = Implantar um pacote de coleta personalizado
	DeployPackageSelect             = Selecione um pacote de pré-coleta
	DeployPackageTo                 = Implante o pacote de pré-coleta para
	DeployToRoot                    = Disco do sistema
	DeployPackageToSolutions        = No diretório inicial da solução
	DeployTimeZone                  = Fuso horário
	DeployTimeZoneChange            = Alterar fuso horário
	DeployTimeZoneChangeTips        = Defina o intervalo de tempo padrão onde as pré-respostas devem ser respondidas, por área de idioma.

	Deploy_Tags                     = Etiqueta de implantação
	FirstExpProcess                 = Primeira experiência, durante os pré-requisitos de implantação:
	FirstExpProcessTips             = Depois de cumprir os pré-requisitos, reinicie o computador para resolver o problema de exigir uma reinicialização para entrar em vigor.
	FirstExpFinish                  = Experiência pela primeira vez, após completar os pré-requisitos
	FirstExpSyncMark                = Permitir pesquisa global e sincronização de tags de implantação
	FirstExpDefender                = Adicionar diretório inicial para defender diretórios excluídos
	FirstExpSyncLabel               = Rótulo do volume do disco do sistema: o nome do diretório inicial é o mesmo
	MultipleLanguages               = Ao encontrar vários idiomas:
	NetworkLocationWizard           = Assistente de localização de rede
	PreAppxCleanup                  = Bloquear tarefas de manutenção de limpeza do Appx
	LanguageComponents              = Impedir a limpeza de pacotes de idiomas de recursos sob demanda não utilizados
	PreventCleaningUnusedLP         = Impedir a limpeza de pacotes de idiomas não utilizados
	FirstExpContextCustomize        = Adicione um "menu de contexto" personalizado
	FirstExpContextCustomizeShift   = Mantenha pressionada a tecla Shift e clique com o botão direito

	FirstExpFinishTips              = Não há eventos importantes após a conclusão da implantação. É recomendável cancelar.
	FirstExpFinishPopup             = Abra a interface principal do mecanismo de implantação
	FirstExpFinishOnDemand          = Permitir a primeira visualização, conforme planejado
	SolutionsEngineRestricted       = Política de execução de restauração do Powershell: restrita
	EnglineDoneClearFull            = Exclua toda a solução
	EnglineDoneClear                = Exclua o mecanismo de implantação e mantenha os outros

	Unattend_Auto_Fix_Next          = Na próxima vez que você encontrar isso, selecione automaticamente os itens necessários para corrigi-lo automaticamente.
	Unattend_Auto_Fix               = Reparar automaticamente quando os pré-requisitos não forem selecionados
	Unattend_Auto_Fix_Tips          = Ao adicionar o mecanismo de implantação e não selecionar o primeiro comando de execução, ele é automaticamente reparado e selecionado: Política de execução do Powershell: execute o mecanismo de implantação sem quaisquer restrições.
	Unattend_Version_Tips           = Opcionalmente, inclua apenas, use o padrão para suportar ARM64, x64, x86.
	First_Run_Commmand              = Comandos a serem executados ao implantar pela primeira vez
	First_Run_Commmand_Setting      = Selecione o comando a ser executado
	Command_Not_Class               = Não é mais categorizado automaticamente ao filtrar
	Command_WinSetup                = Instalação do Windows
	Command_WinPE                   = Windows PE
	Command_Tips                    = Atribua o aplicativo First Run a: Instalação do Windows, Windows PE\n\nObserve que quando um mecanismo de implementação é adicionado, você precisa verificar o seguinte ao executar pela primeira vez: Política de Execução do Powershell: Restrita, permite a execução de scripts do mecanismo de implementação.
	Waring_Not_Select_Command       = Ao adicionar um mecanismo de implantação, a política de execução do Powershell não foi selecionada: Não defina nenhuma restrição e permita a execução do script do mecanismo de implantação. Selecione-o e tente novamente ou clique em "A correção rápida não está selecionada".
	Quic_Fix_Not_Select_Command     = Correção rápida, não opção

	PowerShell_Unrestricted         = Política de execução do Powershell: sem restrições
	Allow_Running_Deploy_Engine     = Permitir a execução de scripts do mecanismo de implementação
'@