ConvertFrom-StringData -StringData @'
	# lv-LV
	# Latvian (Latvia)

	FontsUI                   = Segoe UI
	Mainname                  = Izvēršanas dzinējs: Yi komplekts
	Learn                     = Pētījums
	MainHisName               = Bonusa risinājums
	Location                  = Atvērt atrašanās vietu
	About                     = Par
	Reset                     = Atiestatīt
	AddTo                     = Pievienot
	Instl                     = Instalējiet
	ItInstalled               = Uzstādīts
	Close                     = Slēgšana
	Auto                      = Automātiski
	Disable                   = Atspējot
	Enable                    = Iespējot
	Setting                   = Izveidot
	Restore                   = Atgūties
	Clean                     = Sakopt
	Operable                  = Darbināms
	Inoperable                = Nederīgs
	Optimize                  = Optimizācija
	Hide                      = Paslēpties
	Show                      = Parādīt
	Del                       = Dzēst
	Done                      = Pabeigt
	OK                        = Protams
	Cancel                    = Atcelt
	AllSel                    = Atlasiet visu
	AllClear                  = Notīrīt visu
	Refresh                   = Atsvaidzināt
	RefreshModules            = Visu moduļu karstā atsvaidzināšana
	Necessary                 = Būtiska programmatūra
	MostUsedSoftware          = Bieži lietotā programmatūra
	System                    = Sistēma
	Service                   = Pasniedziet
	TaskBar                   = Visas uzdevumjoslas ikonas
	DeskIcon                  = Darbvirsmas ikonas
	InstallFonts              = Instalējiet fontus
	SettingTo                 = Iestatīt uz {0}
	Command                   = Komandrinda
	RuleName                  = Noteikuma nosaukums
	Language                  = Valodu
	AvailableLanguages        = Pieejamās valodas
	SwitchLanguage            = Mainīt valodu
	LanguageReset             = Atiestatīt valodas iestatījumus
	LanguageCode              = Zonas atzīme
	LanguageSelRegion         = Izvēlieties savu valsti vai reģionu
	LanguageRemember          = Atcerieties izvēlēto valodu
	LanguageSearchNo          = Nav atrasta neviena pieejama valoda
	LanguageNoSel             = Lūdzu, atlasiet reģionu
	Search                    = Meklēt
	PleaseChoose              = Lūdzu, atlasiet
	FailedCreateFolder        = Neizdevās izveidot direktoriju
	Failed                    = Neizdoties
	ToMsg                     = {0} Pēc sekundēm automātiski atgriezieties galvenajā izvēlnē.
	Restart                   = Restartēšana stājas spēkā
	AdvOption                 = Izvēles funkcijas

	StartDown                 = Sāciet lejupielādi
	ConnectTo                 = Izveidojiet savienojumu ar
	FileName                  = Faila nosaukums
	SaveTo                    = Saglabāt uz
	NotAvailable              = Statuss: Nav pieejams
	ExistingPacker            = Jums jau ir instalācijas pakotne
	ExistingInstlPacker       = Jau ir saspiests iepakojums
	Unpacking                 = Izsaiņošana
	QucikRun                  = Ātrais skrējiens:
	WaitDone                  = Gaida pabeigšanu:
	Parameter                 = Parametrs:
	ErrorDown                 = Lejupielādes laikā radās kļūda
	UserCancel                = Lietotājs ir atcēlis darbību.

	VerifyNameTips            = Ir atļauta tikai angļu burtu un ciparu kombinācija, un nav atļautas citas rakstzīmes: atstarpes, garums nedrīkst būt lielāks par 16 rakstzīmēm, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Pielāgota direktorija prefikss
	NoSetFolderLabel          = Pielāgota direktorija prefikss nav iestatīts
	ISO9660TipsErrorSpace     = Nedrīkst saturēt: sākuma un beigu atstarpes
	ISO9660TipsErrorOther     = Nedrīkst saturēt: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Sējuma etiķete nedrīkst būt garāka par {0} rakstzīmēm
	Help                      = Palīdzēt
	WorkDone                  = Pabeigts, nospiediet jebkuru taustiņu, lai atgrieztos galvenajā saskarnē...
	Short_Cmd                 = Īsceļi
	Options                   = Iespējas
	LXPsWaitAssign            = Jāpiešķir
	Running                   = Palaist
	SpecialFunction           = PowerShell funkcijas
'@