ConvertFrom-StringData -StringData @'
	# ar-sa
	# Arabic (Saudi Arabia)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = لوحة القيادة
	Learn                           = يذاكر
	Menu                            = قائمة طعام
	Short_Cmd                       = الاختصارات
	Shortcut                        = الاختصار
	Update                          = تجديد
	CUpdate                         = التحديثات التراكمية
	Rebuild                         = إعادة الإعمار
	AddTo                           = اضف إليه
	Del                             = يمسح
	Copy                            = ينسخ
	Rename                          = إعادة تسمية
	Refresh                         = ينعش
	RefreshModules                  = التحديث الساخن لجميع الوحدات
	Done                            = ينهي
	OK                              = بالتأكيد
	Cancel                          = يلغي
	AllSel                          = حدد الكل
	AllClear                        = مسح الكل
	Setting                         = يثبت
	Change                          = يتغير
	Help                            = يساعد
	Logging                         = سجل
	AvailableLanguages              = اللغات المتاحة
	SwitchLanguage                  = تبديل اللغة
	LanguageSelRegion               = اختر بلدك أو منطقتك
	LanguageRemember                = تذكر اللغة المحددة
	LanguageSearchNo                = لم يتم العثور على اللغات المتاحة
	LanguageNoPack                  = إذا لم تكن هناك حزمة لغة محلية، فسيتم الخروج تلقائيًا.
	LanguageNoSel                   = الرجاء تحديد المنطقة
	Search                          = يبحث
	PleaseChoose                    = الرجاء التحديد
	Options                         = خيارات
	Choose                          = مختارة
	NoChoose                        = لم يتم التحديد
	AdvOption                       = ميزات اختيارية
	ExcludeItem                     = استبعاد حسب القاعدة
	DeDuplication                   = استبعاد التكرارات
	DeDuplication_Unlock            = فتح التكرارات المعطلة
	Existed                         = موجود بالفعل
	FailedCreateFolder              = فشل في إنشاء الدليل
	FailedCreateFile                = فشل في إنشاء الملف
	ToMsg                           = العودة تلقائيًا إلى القائمة الرئيسية بعد {0} ثانية.
	OnDemandPlanTask                = تخصيص مخصص للأحداث المعروفة
	Operable                        = قابلة للتشغيل
	Inoperable                      = غير صالح للعمل
	Hide                            = يخفي
	CuringUpdate                    = تحديث قوي
	CuringUpdateTips                = بمجرد ترسيخ التحديث، لا يمكن إلغاء تثبيته.
	Healthy                         = صحيح
	HealthyTips                     = من المهم بشكل خاص التحقق من الحالة الصحية عند ظهور عبارة "قابل للإصلاح" أو "غير قابل للإصلاح": أثناء عملية تحويل ESD، تتم المطالبة بالخطأ 13 ويتم الإبلاغ عن خطأ عند تثبيت النظام.
	Healthy_Save                    = عند ظهور ملف قابل للإصلاح أو غير قابل للإصلاح، لا تقم بالحفظ.
	Repair                          = بصلح
	IsAuto_Repair                   = السماح بالإصلاح التلقائي عند الخمول
	IsAuto_Repair_Tips              = التحقق تلقائيًا مما إذا كانت هناك أية مهام تثبيت بعد كل تشغيل للبرنامج النصي للتغليف. إذا تم تركيبه، فلن يتم إجراء أي إصلاح؛ وإذا لم يتم تركيبه، فسيتم تشغيل الإصلاح التلقائي.
	Repairable                      = قابلة للإصلاح
	NonRepairable                   = غير قابلة للإصلاح
	HealthyForceStop                = أثناء معالجة الحدث، تمت مواجهة خطأ لا يمكن إصلاحه وتم إنهاء العملية قسراً.\n\n   يسبب مشاكل رئيسية: \n\n      1. الأجهزة المادية تالفة، القرص الصلب؛\n\n      2. إذا كنت تستخدم القرص الظاهري لذاكرة RAMDISK (بما في ذلك الهجين)، فيرجى التحقق من الذاكرة الفعلية؛\n\n      3. تحقق من SHA256 الأصلي لـ MVS (MSDN). إذا كان متسقًا، فيرجى تغيير الدليل والمحاولة مرة أخرى. إذا كان SHA256 غير متسق، فيرجى تنزيله مرة أخرى والمحاولة مرة أخرى؛\n\n      4. لم يتم سرد الآخرين في هذا المثال.
	Superseded                      = تنظيف المستبدلة
	SupersededTips                  = يتضمن تحديثات ومكونات قديمة وما إلى ذلك.
	UnmountFailed                   = لقد جربت عدة طرق، ولكن لا يمكنني فعل أي شيء، أود فقط أن أراك في المرة القادمة.
	SaveTo                          = حفظ ل
	WorkDone                        = اكتمل، اضغط على أي مفتاح للعودة إلى الواجهة الرئيسية...
	UserCanel                       = لقد قام المستخدم بإلغاء الطلب.
	Uping                           = توليد
	Exclude_View                    = عرض قواعد الاستبعاد
	User_Interaction                = تفاعل المستخدم
	Ok_Go_To                        = متاح ل
	Ok_Go_To_No                     = لن أذهب

	Detailed                        = مفصل
	Detailed_View                   = عرض تفاصيل القاعدة المحددة

	AddEnv                          = إضافة وظيفة التوجيه إلى متغيرات النظام
	AddEnvTips                      = بعد الإضافة، أدخل Yi في أي جلسة PowerShell للرد، على سبيل المثال، أدخل "Yi -SIP" لتشغيل التغليف.

	Unzip_ISO                       = استخراج ISO
	Unzip_Search_Type               = دليل البحث ( {0} )
	ISO_Other                       = وثائق أخرى
	Unzip_Language                  = حزمة اللغة
	Unzip_Fod                       = حزمة الميزات
	FileName                        = اسم الملف

	UserCancel                      = لقد ألغى المستخدم العملية.
	MatchMode                       = مباراة
	Failed                          = يفشل
	RandomSelect                    = تم اختيارها عشوائيا
	RulePre                         = قواعد محددة مسبقا
	RuleOther                       = قواعد أخرى
	RuleCustomize                   = القواعد المخصصة
	RuleCustomize_Dont              = لا تستخدم قواعد مخصصة للدليل متعدد المستويات
	RuleCustomize_Dont_Tips         = بعد حذف الدليل القديم، انقر فوق "التحقق من قواعد التسمية".
	RuleMultistage                  = قواعد الدليل متعددة المستويات
	RuleMultistageFindFailed        = لم يتم العثور على قواعد دليل متعددة المستويات، انقر فوقي لإنشاء قالب.
	RuleMultistageFindCreateNew     = قم بإنشاء قالب قاعدة دليل متعدد المستويات جديد
	RuleMultistageTips              = تكييف قواعد الدليل متعددة المستويات تلقائيًا، تم تعطيل قاعدة الدليل {0}.
	RuleCustomizeNot                = لم يتم العثور على اسم الملحق (Solutions.Custom.Extension)، يرجى مراجعة وثائق المساعدة.
	RuleCustomizeTips               = لم يتم إنشاء قاعدة مخصصة، يرجى الاطلاع على وثائق المساعدة.
	RuleMatchNoFindFolder           = فشلت مطابقة الدليل، انقر فوقي لإنشاء الدليل.
	RuleNoFindFile                  = لم يتم العثور على ملفات متاحة، يرجى الإضافة والتحديث.
	RuleFindFolder                  = يتم تحديد الدليل تلقائيًا عند توفره
	RuleNameNewChange               = المزامنة تلقائيًا بعد التحديثات
	RuleNewTempate                  = إنشاء قالب
	RuleSkipFolderCheck             = لم يعد يتحقق مما إذا كان الملف موجودًا في الدليل ونوع الملف
	RuleAuthon                      = منشئ القواعد
	RuleGUID                        = GUID المعرف الفريد العالمي
	RuleName                        = اسم القاعدة
	RuleDescription                 = يصف
	RuleNameUse                     = مزامنة اسم القاعدة إلى: {0}
	RuleISO                         = تطابق حزمة التثبيت ISO الأصلية
	RuleInBoxApps                   = تطبيق كامل تم تكوينه مسبقًا
	RuleFileType                    = اسم الحزمة
	RuleFileFind                    = اسم البحث غامض
	RuleFindError                   = تم العثور على {0} من العناصر المطلوب معالجتها، انقر فوق "التحقق من التبعيات" لعرض التفاصيل.
	RuleSelectApps                  = التطبيقات التي يختارها المستخدم
	DependencyPackage               = حزمة التبعية
	RuleDependenciesRequired        = التبعيات المطلوبة
	RuleDependenciesUnselected      = التبعيات غير المحددة
	RuleDependenciesNoCheck         = لم يعد يتم التحقق من التبعيات
	RuleDependenciesFix             = لم يتم تحديد إصلاح التبعيات
	Extract_Tips                    = تَلمِيح\n\n   1. لا يمكن استخدام النتيجة بعد استخراج حزمة اللغة ككائن مرجعي رئيسي؛\n\n   2. يرجى استخدام قائمة المكونات ككائن مرجعي رئيسي. كيفية الإنشاء:\n\n       حدد المكون الذي تم إنشاؤه (احصل على الحزمة في الصورة المثبتة) في Functions، وحدد طباعة أو عرض على الفور؛\n\n   3. بعد تثبيت حزمة اللغة، يرجى إعادة إنشاء تقرير المكون للتحقق مما إذا كان مطابقًا أم لا؛

	DescendingRuleLang              = قم بإزالة حزم اللغات بترتيب عكسي
	OrderRuleLang                   = قم بتثبيت حزم اللغات بترتيب محدد مسبقًا
	OrderRuleLangTips               = أضف بالترتيب: أساسي، الخطوط، التعرف البصري على الأحرف، التعرف على الكتابة اليدوية، تحويل النص إلى كلام، التعرف على الكلام، تجربة البيع بالتجزئة، أخرى
	RuleLanguageTips                = يوضح:\n\n   بعد استخدام "تثبيت حزم اللغات بترتيب محدد مسبقًا"، تتم مطابقة الملفات تلقائيًا بأسماء غامضة بالترتيب التالي:\n
	Match_installed_List            = عند تثبيت حزمة لغة، قم بحرف البدل عليها من القائمة المثبتة
	Match_installed_List_Tips       = يتطابق فقط عند تثبيته: أساسي، التعرف البصري على الأحرف، التعرف على الكتابة اليدوية، تحويل النص إلى كلام، التعرف على الكلام.
	RuleLanguageTipsExt             = \n   عند عدم استخدام "تثبيت حزم اللغات بترتيب محدد مسبقًا":\n   البحث تلقائيًا في جميع الملفات الموجودة في الدليل حسب نوع الملف وتثبيتها.\n\n   ميزات اللغة والمنطقة حسب الطلب (FOD)\n   https://learn.microsoft.com/ar-sa/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = فئة
	Basic                           = أساسي
	Fonts                           = الخط
	OCR                             = التعرف البصري على الحروف
	Handwriting                     = التعرف على خط اليد
	TextToSpeech                    = النص إلى كلام
	Speech                          = التعرف على الكلام
	Retail                          = تجربة العرض التجريبي للبيع بالتجزئة
	Features_On_Demand              = الميزات حسب الطلب
	RegionSpecific                  = متطلبات أخرى خاصة بالمنطقة
	UnassignedLangFiles             = ملفات متنوعة غير مخصصة

	ProcessingImage                 = معالجة الصورة:
	NoInstallImage                  = غير موجود محليا
	ConvertChk                      = التحقق من الملف
	WindowsFeature                  = Windows مميزات
	Enable                          = يُمكَِن
	Disable                         = إبطال
	EnableFeatureTips               = تَلمِيح\n\n    1. عرض NetFx3 وTelnetClient كعناصر وظيفية تم تمكينها مسبقًا؛\n\n    2. بعد "التركيب"، يمكن تمكين المزيد.
	ViewLanguage                    = عرض إعدادات لغة الصورة
	ImageLanguage                   = إعدادات لغة الصورة
	OnlyLangCleanup                 = المكونات النظيفة: علامة حسب اللغة
	Matched_Component_Names         = اسم المكون المطابق: 
	BootProcess                     = {0}.wim عند معالجة
	Sync_Language_To                = مزامنة ل
	BootSyncToISO                   = مزامنة حزم اللغات مع المثبت
	BootSyncToISOTips               = تتم مزامنة حزمة اللغة المثبتة للصورة غير المتصلة بالإنترنت مع برنامج تثبيت ISO.
	LangIni                         = إعادة إنشاء Lang.ini
	LangIniTips                     = بعد اكتمال المزامنة، يجب إعادة بناء Lang.ini في ISO.
	LangNewAutoSelect               = تحديد العناصر المقترحة تلقائيًا عند وقوع حدث ما
	LangNewAutoSelectTips           = هناك أحداث جديدة، "مزامنة حزم اللغات مع المثبت"، تم تحديد "إعادة بناء Lang.ini".
	LangNewAutoNoSelect             = هناك أحداث جديدة، فمن المستحسن تحديد "مزامنة حزمة اللغة مع المثبت" و"إعادة بناء Lang.ini".
	LangNewAutoNoNewSelect          = لا توجد أحداث جديدة يوصى بعدم تحديد "مزامنة حزمة اللغة مع المثبت" و"إعادة إنشاء Lang.ini".
	Drive                           = يقود
	ViewDrive                       = عرض برامج التشغيل المثبتة
	EditionsProductKey              = مفتاح المنتج
	Editions                        = نسخة الصورة
	Assign_Editions                 = توزيع التطبيقات تلقائيًا بناءً على إصدارات الصور
	EditionsChangeTips              = تحذير، يرجى فهم ما يلي قبل تبديل إصدارات الصور: \n\nMicrosoft اتفاقية الخدمة\nhttps://www.microsoft.com/ar-sa/servicesagreement/default.aspx\n\nنظرة عامة على اللغة\nhttps://learn.microsoft.com/ar-sa/windows-hardware/manufacture/desktop/languages-overview\n\nغير مسموح لك بإنشاء إصدارات من:\n   1. بلد محدد\n       ProfessionalCountrySpecific\n\n   2. الإصدار المنزلي الخاص بالمنطقة\n       ProfessionalSingleLanguage\n\nيرجى الالتزام الصارم لأنك قد تتعرض للملاحقة القضائية في حالة انتهاكها.\n\nإذا كنت تصر على التحويل، فانقر لقبول التحذير وانقر على "فتح نسخة الصورة المخفية".
	EditionsChangeHide              = فتح إصدارات الصور المخفية
	EditionsChangeAccect            = لقد قرأت التحذير وأنا مسؤول عن القوانين ذات الصلة الواردة في التحذير

	SelFile                         = حدد الملف
	Rebuilding                      = قيد الإعمار
	RebuildAll                      = إعادة بناء الكل
	Export_Image                    = يصدّر
	SelectFromError                 = خطأ
	SelectFileFormatError           = تنسيق الملف غير صحيح

	SearchDrive                     = البحث مدفوعة
	SearchUpdate                    = بحث في التحديثات، اكتب ( {0} )، المصدر:
	SelectFolder                    = حدد الدليل
	DropFolder                      = يمكن سحب الدلائل إلى النافذة الحالية
	DropFile                        = يمكن سحب الملفات إلى النافذة الحالية
	Sparse                          = نادر
	CRCSHA                          = يفحص
	Alternative                     = اسم الملف البديل
	ChangeInstallDisk               = تغيير التحديد التلقائي للقرص
	Backup                          = النسخ الاحتياطي
	Restore                         = الاستعادة

	# View
	ExportToLogs                    = طباعة التقرير للتسجيل
	ExportShow                      = عرض التقارير على الفور
	MoreFeature                     = المزيد من الميزات
	OpenFolder                      = افتح الدليل
	OpenFile                        = ملف مفتوح
	Running                         = يجري
	Paste                           = مسار النسخ
	Clipboard_Copy                  = تم النسخ إلى الحافظة
	ViewWIMFileInfo                 = عرض الصورة
	GetInBoxApps                    = InBox Apps: حزم التطبيقات المثبتة
	GetImagePackage                 = المكونات: جميع الحزم المثبتة في الصورة
	ViewMounted                     = الحصول على معلومات حول جميع الصور المثبتة
'@