ConvertFrom-StringData -StringData @'
	# nl-NL
	# Dutch (Netherlands)

	FontsUI                   = Segoe UI
	Mainname                  = Implementatie-engine: Yi's suite
	Learn                     = Studie
	MainHisName               = Bonus-oplossing
	Location                  = Open locatie
	About                     = Over
	Reset                     = Opnieuw instellen
	AddTo                     = Toevoegen aan
	Instl                     = Installeren
	ItInstalled               = Geïnstalleerd
	Close                     = Sluiting
	Auto                      = Automatisch
	Disable                   = Uitzetten
	Enable                    = Inschakelen
	Setting                   = Opgezet
	Restore                   = Herstellen
	CLearn                    = Opruimen
	Operable                  = Bedienbaar
	Inoperable                = Onbruikbaar
	Optimize                  = Optimalisatie
	Hide                      = Verbergen
	Show                      = Show
	Del                       = Verwijderen
	Done                      = Finish
	OK                        = Zeker
	Cancel                    = Annuleren
	AllSel                    = Selecteer alles
	AllClear                  = Alles wissen
	Refresh                   = Vernieuwen
	RefreshModules            = Heet vernieuw alle modules
	Necessary                 = Essentiële software
	MostUsedSoftware          = Veelgebruikte software
	System                    = Systeem
	Service                   = Dienen
	TaskBar                   = Alle taakbalkpictogrammen
	DeskIcon                  = Bureaubladpictogrammen
	InstallFonts              = Installeer lettertypen
	SettingTo                 = Instellen op {0}
	AvailableLanguages        = Beschikbare talen
	SwitchLanguage            = Van taal wisselen
	LanguageReset             = Taalinstellingen resetten
	LanguageCode              = Zonemarkering
	LanguageSelRegion         = Selecteer uw land of regio
	LanguageRemember          = Onthoud de geselecteerde taal
	LanguageSearchNo          = Geen beschikbare talen gevonden
	LanguageNoPack            = Als er lokaal geen taalpakket is, wordt het automatisch afgesloten.
	LanguageNoSel             = Selecteer een regio
	Search                    = Zoekopdracht
	PleaseChoose              = Selecteer alstublieft
	FailedCreateFolder        = Kan map niet maken
	Failed                    = Mislukking
	ToMsg                     = {0} Keer na enkele seconden automatisch terug naar het hoofdmenu.
	Restart                   = De herstart wordt van kracht
	AdvOption                 = Optionele functies

	StartDown                 = Begin met downloaden
	ConnectTo                 = Maak verbinding met
	FileName                  = Bestandsnaam
	SaveTo                    = Opslaan naar
	NotAvailable              = Status: Niet beschikbaar
	ExistingPacker            = Heb al een installatiepakket
	ExistingInstlPacker       = U hebt al een gecomprimeerd pakket
	Unpacking                 = Uitpakken
	QucikRun                  = Snel rennen:
	WaitDone                  = Wachten op voltooiing:
	Parameter                 = Parameter:
	ErrorDown                 = Er is een fout opgetreden tijdens het downloaden
	UserCancel                = De gebruiker heeft de bewerking geannuleerd.

	VerifyNameTips            = Alleen een combinatie van Engelse letters en cijfers is toegestaan, en er zijn geen andere tekens toegestaan: spaties, lengte mag niet groter zijn dan 16 tekens, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Aangepast mapvoorvoegsel
	NoSetFolderLabel          = Aangepast mapvoorvoegsel is niet ingesteld
	ISO9660TipsErrorSpace     = Mag niet bevatten: voorloop- en volgspaties
	ISO9660TipsErrorOther     = Mag het volgende niet bevatten: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Volumelabel mag niet langer zijn dan {0} tekens
	Help                      = Hulp
	WorkDone                  = Voltooid, druk op een willekeurige toets om terug te keren naar de hoofdinterface...
	Short_Cmd                 = Snelkoppelingen
	Options                   = Opties
'@