ConvertFrom-StringData -StringData @'
	# sr-latn-rs
	# Serbian (Latin, Serbia)

	IsCreate                        = Створити
	Solution                        = Решење
	EnabledSoftwarePacker           = Цоллецтион
	EnabledUnattend                 = Требало би одговорити унапред
	EnabledEnglish                  = Деплоимент енгине
	UnattendSelectVer               = Изаберите језик решења "Одговори на".
	UnattendLangPack                = Изаберите језички пакет "Решење".
	UnattendSelectSingleInstl       = Вишејезично, опционо током инсталације
	UnattendSelectMulti             = Вишејезичне
	UnattendSelectDisk              = Изаберите решење Autounattend.xml
	UnattendSelectSemi              = Полуаутоматски важи за све методе уградње
	UnattendSelectUefi              = UEFI Аутоматска инсталација, потребно је навести
	UnattendSelectLegacy            = Legacy Аутоматска инсталација, потребно је навести
	NeedSpecified                   = Молимо изаберите шта треба навести:
	OOBESetupOS                     = Интерфејс за инсталацију
	OOBEProductKey                  = Кључ производа
	OOBEOSImage                     = Изаберите оперативни систем који желите да инсталирате
	OOBEEula                        = Прихватите услове лиценце
	OOBEDoNotServerManager          = Сервер Манагер се не покреће аутоматски при пријави
	OOBEIE                          = Internet Explorer Побољшана безбедносна конфигурација
	OOBEIEAdmin                     = Затвори "Администратор"
	OObeIEUser                      = Затвори "Корисници"

	OOBE_Init_User                  = Први корисник током искуства распакивања
	OOBE_init_Create                = Креирајте прилагођене кориснике
	OOBE_init_Specified             = Наведите корисника
	OOBE_Init_Autologin             = Аутоматско пријављивање

	InstlMode                       = Начин уградње
	Business                        = Пословна верзија
	BusinessTips                    = У зависности од ЕИ.цфг, број индекса треба да буде наведен за аутоматску инсталацију.
	Consumer                        = Верзија за потрошаче
	ConsumerTips                    = Не ослања се на ЕИ.цфг. За аутоматску инсталацију потребно је навести серијски број.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [монтирати на]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Додај на системски диск назив матичног директорија
	VerifyNameUse                   = Проверите да име директоријума не може да садржи
	VerifyNameTips                  = Дозвољена је само комбинација енглеских слова и бројева и не може да садржи: размаке, дужина не може бити већа од 260 знакова, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Верификација није успела, унесите тачан број.
	VerifyNameSync                  = Подесите име директоријума као примарно корисничко име
	VerifyNameSyncTips              = Администратор се више не користи.
	ManualKey                       = Изаберите или унесите кључ производа ручно
	ManualKeyTips                   = Унесите важећи кључ производа Ако изабрани регион није доступан, идите на званичну веб локацију компаније Мицрософт да бисте проверили.
	ManualKeyError                  = Кључ производа који сте унели је неважећи.
	KMSLink1                        = Кључ за подешавања КМС клијента
	KMSUnlock                       = Прикажи све познате КМС серијске бројеве
	KMSSelect                       = Молимо изаберите ВОЛ серијски број
	KMSKey                          = Серијски број
	KMSKeySelect                    = Промените серијски број производа
	ClearOld                        = Очистите старе датотеке
	SolutionsSkip                   = Прескочите креирање решења
	SolutionsTo                     = Додајте 'решење' у:
	SolutionsToMount                = Монтиран или додат у ред чекања
	SolutionsToError                = Неке функције су онемогућене. Ако желите да их натерате да користе, кликните на дугме "Откључај".\n\n
	UnlockBoot                      = Откључај
	SolutionsToSources              = Кућни именик, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Изаберите верзију "Деплоимент Енгине".
	SolutionsEngineRegionaUTF8      = Бета: Глобална језичка подршка користећи Уницоде УТФ-8
	SolutionsEngineRegionaUTF8Tips  = Чини се да може изазвати нове проблеме након отварања. Не препоручује се.
	SolutionsEngineRegionaling      = Промени на нови локал:
	SolutionsEngineRegionalingTips  = Промените системски локал, што утиче на све корисничке налоге на рачунару.
	SolutionsEngineRegional         = Промените системски локал
	SolutionsEngineRegionalTips     = Глобално подразумевано: {0}, промењено у: {1}
	SolutionsEngineCopyPublic       = Копирајте јавни {0} за примену
	SolutionsEngineCopyOpen         = Прегледајте локацију јавног спремишта {0}
	EnglineDoneReboot               = Поново покрените рачунар
	SolutionsTipsArm64              = Пожељан је пакет арм64, а бирате по редоследу: к64, к86.
	SolutionsTipsAMD64              = Дајте предност к64 пакетима, редоследом: к86.
	SolutionsTipsX86                = Додати су само к86 пакети.
	SolutionsReport                 = Генеришите извештај пре имплементације
	SolutionsDeployOfficeInstall    = Поставите инсталациони пакет Мицрософт Оффице
	SolutionsDeployOfficeChange     = Промените конфигурацију примене
	SolutionsDeployOfficePre        = Претходно инсталирана верзија пакета
	SolutionsDeployOfficeNoSelect   = Није изабран пакет за прединсталацију система Оффице
	SolutionsDeployOfficeVersion    = {0} верзија
	SolutionsDeployOfficeOnly       = Задржите одређене језичке пакете
	SolutionsDeployOfficeSync       = Сачувајте синхронизацију језика са конфигурацијом примене
	SolutionsDeployOfficeSyncTips   = Након синхронизације, инсталациона скрипта не може да одреди жељени језик.
	DeploySyncMainLanguage          = Синхронизујте са главним језиком
	SolutionsDeployOfficeTo         = Поставите инсталациони пакет на
	SolutionsDeployOfficeToPublic   = Јавна радна површина
	DeployPackage                   = Поставите прилагођени пакет за прикупљање
	DeployPackageSelect             = Изаберите пакет пре прикупљања
	DeployPackageTo                 = Поставите пакет пре прикупљања на
	DeployToRoot                    = Системски диск
	DeployPackageToSolutions        = У матичном директоријуму решења
	DeployTimeZone                  = Временска зона
	DeployTimeZoneChange            = Промените временску зону
	DeployTimeZoneChangeTips        = Подесите подразумевану временску област у којој треба да се одговори на предодговоре, према области језика.

	Deploy_Tags                     = Ознака за примену
	FirstExpProcess                 = Искуство по први пут, током предуслова за имплементацију:
	FirstExpProcessTips             = Након што испуните предуслове, поново покрените рачунар да бисте решили проблем захтева поновног покретања да би ступио на снагу.
	FirstExpFinish                  = Искуство по први пут, након испуњавања предуслова
	FirstExpSyncMark                = Дозволите глобалну претрагу и синхронизацију ознака за примену
	FirstExpDefender                = Додајте почетни директоријум у Дефенд искључене директоријуме
	FirstExpSyncLabel               = Ознака волумена системског диска: Име матичног директоријума је исто
	MultipleLanguages               = Када наиђете на више језика:
	NetworkLocationWizard           = Чаробњак за мрежну локацију
	PreAppxCleanup                  = Блокирајте задатке одржавања чишћења Аппк-а
	LanguageComponents              = Спречите чишћење некоришћених језичких пакета функција на захтев
	PreventCleaningUnusedLP         = Спречите чишћење некоришћених језичких пакета
	FirstExpContextCustomize        = Додајте персонализовани "контекстуални мени"
	FirstExpContextCustomizeShift   = Држите притиснут тастер Схифт и кликните десним тастером миша

	FirstExpFinishTips              = Нема важних догађаја након завршетка имплементације. Препоручује се да откажете.
	FirstExpFinishPopup             = Отворите главни интерфејс механизма за примену
	FirstExpFinishOnDemand          = Дозволите први преглед, као што је планирано
	SolutionsEngineRestricted       = Враћање политике извршавања Поверсхелл-а: ограничено
	EnglineDoneClearFull            = Обришите цело решење
	EnglineDoneClear                = Избришите механизам за примену и задржите остале

	Unattend_Auto_Fix_Next          = Следећи пут када га наиђете, аутоматски изаберите потребне ставке да бисте га аутоматски поправили.
	Unattend_Auto_Fix               = Аутоматски поправи када предуслови нису изабрани
	Unattend_Auto_Fix_Tips          = Када додате машину за примену и не изаберете прву команду покретања, она се аутоматски поправља и бира: Политика извршавања Поверсхелл-а: покрените машину за примену без икаквих ограничења.
	Unattend_Version_Tips           = Опционо само укључите, користите подразумевани за подршку АРМ64, к64, к86.
	First_Run_Commmand              = Команде за покретање приликом првог постављања
	First_Run_Commmand_Setting      = Изаберите команду за покретање
	Command_Not_Class               = Више се не категорише аутоматски приликом филтрирања
	Command_WinSetup                = Виндовс инсталација
	Command_WinPE                   = Windows PE
	Command_Tips                    = Доделите апликацију Фирст Рун за: Виндовс инсталацију, Виндовс ПЕ\n\nИмајте на уму да када се дода механизам за примену, потребно је да проверите следеће када се покреће први пут: Поверсхелл Политика извршавања: Ограничено, дозволите покретање скрипти машине за примену.
	Waring_Not_Select_Command       = Приликом додавања механизма за примену, политика извршавања Поверсхелл-а није изабрана: Не постављајте никаква ограничења и дозволите да се скрипта за примену покрене. Изаберите је и покушајте поново или кликните на "Брзо решење није изабрано".
	Quic_Fix_Not_Select_Command     = Брза поправка није опција

	PowerShell_Unrestricted         = Политика извршавања Поверсхелл-а: нема ограничења
	Allow_Running_Deploy_Engine     = Дозволите покретање скрипти механизма за примену
'@