ConvertFrom-StringData -StringData @'
	# sr-latn-rs
	# Serbian (Latin, Serbia)

	UnpackISO                       = Генеришите ISO
	ISOLabel                        = Ознака запремине је постављена:
	ISOCustomize                    = Назив ознаке ISO волумена
	ISO9660                         = Проверите правила именовања
	ISO9660Tips                     = Јединствено име не може бити дуже од 260 знакова, ISO назив волумена не може бити дужи од 16 знакова и не може садржавати: размаке на почетку и на крају, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Прилагођено јединствено именовање
	ISOAddFlagsLang                 = Додајте вишејезичне ознаке
	ISOAddFlagsLangGet              = Сазнајте познате језике за инсталацију
	ISOAddFlagsVer                  = Додајте ознаку за више верзија
	ISOAddFlagsVerGet               = Добијте познату верзију слике
	ISOAddEICFG                     = Додајте тип верзије
	ISOAddEICFGTips                 = Када се ослањате на EI.cfg, то је комерцијална верзија.
	ISO9660TipsErrorSpace           = Не може да садржи: почетне и задње размаке
	ISO9660TipsErrorOther           = Не може да садржи: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Изаберите тип језика
	SelLabel                        = Кодно име
	ISOVerLabel                     = Изаберите назив ISO волумена
	NoSetLabel                      = Прилагођена ISO ознака запремине није подешена
	ISOLengthError                  = Ознака волумена не може бити дужа од {0} знакова
	RenameFailed                    = Исто као и стари директоријум, преименовање није успело
	ISOCreateAfter                  = Шта треба да урадите пре креирања ISO а
	ISOCreateRear                   = Шта треба да урадите након креирања ISO а
	BypassTPM                       = Заобиђите проверу инсталације ТПМ-а
	Disable_BitLocker               = Онемогућите шифровање БитЛоцкер уређаја током инсталације
	PublicDate                      = Датум издавања
	PublicDateGetCurrent            = Синхронизујте тренутни датум
	PublicYear                      = Година
	PublicMonth                     = Моон
	PublicYMSorting                 = Сортирај променом "месец-година" у "година-месец".
	PublicYMSortingTips             = Не додај доњу црту _ када користиш бројеве у AB.
	PublicYMUseShortNames           = Користи кратка имена.
	PublicYMUseNumbers              = Користи бројеве.
	ISOCreateFailed                 = Креирање није успело, директоријум није читљив или уписан.
	ISORefreshAuto                  = Освежите ISO  ознаке сваки пут
	ISOSaveTo                       = ISO подразумевана локација за чување
	ISOSaveSameGlobal               = Користите глобалну ISO подразумевану локацију за чување
	ISOSaveSync                     = Аутоматски синхронизујте нову локацију након што изаберете диск за претрагу извора слике
	ISOSaveSame                     = Претражите путању диска користећи извор слике
	ISOFolderWrite                  = Проверите да ли је директоријум читљив и уписан
	SelectAutoAvailable             = Приликом аутоматског одабира доступног диска
	SelectCheckAvailable            = Проверите минимални расположиви преостали простор
	ISOStructure                    = Нова структура директоријума
	ISOOSLevel                      = Додајте тип инсталације
	ISOUniqueNameDirectory          = Додајте јединствени именик
	NextDoOperate                   = Не креирајте ISO
	SelCreateISO                    = Генеришите ISO, извршите на захтев
	Reconstruction                  = Поново направите {0}.Wim са максималном компресијом
	Reconstruction_Tips_Select      = Пре поновног састављања, биће извршено само када није учитано. То ће приморати да се омогући чување, а затим демонтира монтирану датотеку.
	ReconstructionTips              = Преко 520 МБ, препоручује се реконструкција
	CreateASC                       = Додајте ПГП потпис у ISO
	NoPGPKey                        = У PGP-у не постоји употребљив приватни кључ.
	CreateASCPwd                    = Лозинка за сертификат
	PasswordRenter                  = Поново унесите лозинку
	ShowPassword                    = Прикажи лозинку
	NewPasswordSome                 = Лозинка се не поклапа.
	PwdPermanent                    = Трајно складиштење
	PwdDecfailed                    = Дешифровање није успело
	CreateASCAuthor                 = Потписник
	CreateASCAuthorTips             = Није изабран ниједан потписник.
	ISO_Sparse_Rename               = Додајте хеш екстензији имена датотеке
	GenerateRandom                  = Генеришите случајне бројеве
	RandomNumberReset               = Регенерисати
'@