ConvertFrom-StringData -StringData @'
	# ja-JP
	# Japanese (Japan)

	UnpackISO                       = 生む ISO
	ISOLabel                        = ボリューム・ラベルは既に設定されています：
	ISOCustomize                    = ISO ボリュームラベル名
	ISO9660                         = 名前付け規則を検証します
	ISO9660Tips                     = 一意の名前付けは 260 文字を超えることはできません, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = カスタム一意の名前付け
	ISOAddFlagsLang                 = 多言語タグを追加します
	ISOAddFlagsLangGet              = 既知のインストール言語を取得します
	ISOAddFlagsVer                  = 複数バージョンのタグを追加します
	ISOAddFlagsVerGet               = 既知のイメージのバージョンを取得します
	ISOAddEICFG                     = バージョンの種類を追加します
	ISOAddEICFGTips                 = EI.cfgに依存する場合, それは商用版です。
	ISO9660TipsErrorSpace           = 前と後のスペースを含めることはできません
	ISO9660TipsErrorOther           = 含めることはできません：\\ / : * ? & @ ! "" < > |
	SelOSver                        = 言語の種類を選択します
	SelLabel                        = コード名
	ISOVerLabel                     = ISO ボリュームラベル名を選択します
	NoSetLabel                      = カスタム ISO ボリューム ラベルが設定されていません
	ISOLengthError                  = ボリューム ラベルの長さは {0} 文字より大きくすることはできません
	RenameFailed                    = 古いディレクトリと同じですが, 名前の変更に失敗しました
	ISOCreateAfter                  = ISO を作成する前に行う必要があること
	ISOCreateRear                   = ISO を作成した後に行う必要がある処理
	BypassTPM                       = TPM インストール チェックをバイパスします
	Disable_BitLocker               = インストール中に BitLocker デバイス暗号化を無効にする
	PublicDate                      = 発行日
	PublicDateGetCurrent            = 現在の日付を同期します
	PublicYear                      = 年
	PublicMonth                     = 月
	PublicYMSorting                 = 「月_年」を「年_月」に変更して並べ替えます。
	PublicYMSortingTips             = AB: 数字を使用する場合は、アンダースコア (_) を追加しないでください。
	PublicYMUseShortNames           = 短い名前を使用します
	PublicYMUseNumbers              = 数字を使用します
	ISOCreateFailed                 = の作成に失敗し, ディレクトリが読み取り/書き込み不能になりました。
	ISORefreshAuto                  = ISO ラベルを毎回更新します
	ISOSaveTo                       = ISO は既定で保存場所になります
	ISOSaveSameGlobal               = グローバル ISO を使用して, 既定で場所を保存します
	ISOSaveSync                     = イメージ ソース検索ディスクを選択すると, 新しい場所が自動的に同期されます
	ISOSaveSame                     = イメージ ソースを使用してディスク パスを検索します
	ISOFolderWrite                  = ディレクトリが読み取り/書き込み可能であることを確認します
	SelectAutoAvailable             = 使用可能なディスクが自動的に選択されるとき
	SelectCheckAvailable            = 使用可能な最小残りの領域を確認します
	ISOStructure                    = 新しいディレクトリ構造
	ISOOSLevel                      = インストールの種類を追加します
	ISOUniqueNameDirectory          = 一意の名前のディレクトリを追加します
	NextDoOperate                   = ISO は作成されません
	SelCreateISO                    = ISO を生成し, オンデマンドで実行します
	Reconstruction                  = 最大圧縮で {0}.wim を再構築します
	Reconstruction_Tips_Select      = 再構築の前に, マウントされていない場合にのみ実行され, 強制的にセーブを開き, マウントされたものをアンマウントします。
	ReconstructionTips              = 520 MB を超える場合は, 再構築をお勧めします
	CreateASC                       = ISO に PGP 署名を追加します
	NoPGPKey                        = PGP には使用可能な秘密鍵がありません。
	CreateASCPwd                    = 証明書のパスワード
	PasswordRenter                  = パスワードを再入力してください
	ShowPassword                    = パスワードを表示
	NewPasswordSome                 = パスワードが一致しません。
	PwdPermanent                    = 永続ストレージ
	PwdDecfailed                    = 復号に失敗しました
	CreateASCAuthor                 = 署名者
	CreateASCAuthorTips             = 署名者が選択されていません。
	ISO_Sparse_Rename               = ファイル名拡張子にハッシュを追加する
	GenerateRandom                  = 乱数を生成します
	RandomNumberReset               = 再構築します
'@