ConvertFrom-StringData -StringData @'
	# nl-NL
	# Dutch (Netherlands)

	Main_quests                     = Hoofdtaken
	Side_quests                     = Subtaken
	SaveModeClear                   = Wis geselecteerde geschiedenis
	SaveModeTipsClear               = De geschiedenis is opgeslagen en kan worden gewist
	SelectTips                      = Hint\n\n    1. Selecteer de naam van de afbeelding die moet worden verwerkt;\n    2. Nadat u hebt geannuleerd, zijn taken die vóór gebruik moeten worden 'gemonteerd' niet langer van kracht.
	CacheDisk                       = Schijfcache
	CacheDiskCustomize              = Aangepast cachepad
	AutoSelectRAMDISK               = Automatische selectie van schijfvolumelabels toestaan
	AutoSelectRAMDISKFailed         = Volumelabel komt niet overeen
	ReFS_Find_Volume                = Wanneer schijfformaat REFS wordt aangetroffen, sluit u dit uit
	ReFS_Exclude                    = ReFS-partitie uitgesloten
	Disk_Not_satisfied_Exclude      = Minimale schijfvereisten niet gehaald
	RAMDISK_Change                  = Wijzig de naam van het volumelabel
	RAMDISK_Search                  = Zoek naar de naam van het volumelabel
	RAMDISK_Restore                 = Geïnitialiseerde volumenaam herstellen: {0}
	AllowTopMost                    = Laat geopende ramen aan de bovenkant vastzetten
	History                         = Duidelijke geschiedenis
	History_Del_Tips                = Als er een inkapselingstaak is, voer dan de volgende optionele opties niet uit, anders veroorzaakt dit onbekende problemen tijdens het uitvoeren van het inkapselingsscript.
	History_View                    = Geschiedenis bekijken
	HistoryLog                      = Sta automatisch opschonen toe van houtblokken die ouder zijn dan 7 dagen
	HistorySaveFolder               = Andere afbeeldingsbronpaden
	HistoryClearappxStage           = InBox Apps: verwijder tijdelijke bestanden die tijdens de installatie zijn gegenereerd
	DoNotCheckBoot                  = Wanneer de grootte van het Boot.wim-bestand groter is dan 520 MB, wordt opnieuw opbouwen automatisch geselecteerd bij het genereren van de ISO.
	HistoryClearDismSave            = Verwijder DISM-mountrecords die in het register zijn opgeslagen
	ImageSourcesClickShowKey        = Geef het menu 'Primaire sleutel selecteren' weer
	ImageSourcesClickShowKeyTips    = Nadat de gebruiker de bron van de afbeelding heeft geselecteerd: voeg rechts een menu 'Primaire sleutel selecteren' toe en voeg de opties 'Ga naar' toe: Koppelen, Opslaan, Pop-up.
	Clear_Bad_Mount                 = Verwijder alle bronnen die zijn gekoppeld aan de beschadigde gekoppelde afbeelding
	ShowCommand                     = Toon de volledige opdrachtregeluitvoering
	Command                         = Opdrachtregel
	SelectSettingImage              = Afbeelding bron
	NoSelectImageSource             = Geen afbeeldingsbron geselecteerd
	SettingImageRestore             = Herstel de standaard mountlocatie
	SettingImage                    = Wijzig de montagelocatie van de afbeeldingsbron
	SelectImageMountStatus          = Krijg de mount-status na het selecteren van de afbeeldingsbron
	SettingImageTempFolder          = Tijdelijke map
	SettingImageToTemp              = De tijdelijke map is dezelfde als de locatie waar deze is aangekoppeld
	SettingImagePathTemp            = Met behulp van de Temp directory
	SettingImageLow                 = Controleer de minimaal beschikbare resterende ruimte
	SettingImageNewPath             = Selecteer de mountschijf
	SettingImageNewPathTips         = Het wordt aanbevolen om het op een geheugenschijf te mounten, omdat dit het snelst is. U kunt virtuele geheugensoftware gebruiken, zoals Ultra RAMDisk en ImDisk.
	SelectImageSource               = "Deploy Engine Solution" is geselecteerd, klik op OK.
	NoImagePreSource                = Er is geen beschikbare bron gevonden. U moet: \n\n     1. Voeg meer afbeeldingsbronnen toe aan:\n          {0}\n\n     2. Selecteer "Instellingen" en selecteer opnieuw de zoekschijf voor de afbeeldingsbron;\n\n     3. Selecteer "ISO" en selecteer de ISO die moet worden gedecomprimeerd, de items die moeten worden gemonteerd, enz.
	NoImageOtherSource              = Klik op mij om andere paden toe te voegen of de map naar het huidige venster te slepen.
	SearchImageSource               = Zoekschijf voor beeldbron
	Kernel                          = Kernel
	Architecture                    = Architectuur
	ArchitecturePack                = Pakketarchitectuur, inzicht in het toevoegen van regels
	ImageLevel                      = Installatietype
	LevelDesktop                    = Bureaublad
	LevelServer                     = Server
	ImageCodename                   = Codenaam
	ImageCodenameNo                 = Niet herkend
	MainImageFolder                 = Thuismap
	MountImageTo                    = Ophangen
	Image_Path                      = Afbeelding pad
	MountedIndex                    = Index
	MountedIndexSelect              = Selecteer indexnummer
	AutoSelectIndexFailed           = Automatische selectie van index {0} is mislukt. Probeer het opnieuw.
	Apply                           = Sollicitatie
	Eject                           = Opduiken
	Mount                           = Monteren
	ReMount                         = Opnieuw monteren
	Unmount                         = Verwijderen
	Mounted                         = Gemonteerd
	NotMounted                      = Niet gemonteerd
	NotMountedSpecify               = Niet gemonteerd, u kunt de montagelocatie opgeven
	MountedIndexError               = Abnormale montage, verwijder en probeer het opnieuw.
	NeedsRemount                    = Opnieuw monteren is vereist
	Invalid                         = Ongeldig
	ImageSouresNoSelect             = Toon meer details na het selecteren van de afbeeldingsbron
	Mounted_Mode                    = Montagemodus
	Mounted_Status                  = Mount-status
	Status                          = Status
	Image_Popup_Default             = Standaard opslaan
	Image_Restore_Default           = Terug naar standaard
	Image_Popup_Tips                = Hint:\n\nToen u de gebeurtenis toewees, heeft u niet het indexnummer opgegeven dat moet worden verwerkt: {0};\n\nDe selectie-interface is momenteel verschenen. Geef het indexnummer op. Nadat de specificatie is voltooid, wordt aanbevolen dat u "Opslaan als standaard" selecteert.
	Rule_Show_Full                  = Toon alles
	Rule_Show_Only                  = Laat alleen regels zien
	Rule_Show_Only_Select           = Kies uit regels
	Image_Unmount_After             = Verwijder alle gemonteerde bestanden

	Wim_Rule_Update                 = Bestanden in de afbeelding uitpakken en bijwerken
	Wim_Rule_Extract                = Bestanden uitpakken
	Wim_Rule_Extract_Tips           = Nadat u de padregel hebt geselecteerd, pakt u het opgegeven bestand uit en slaat u het lokaal op.

	Wim_Rule_Verify                 = Verifiëren
	Wim_Rule_Check                  = Onderzoeken
	Wim_Rule_CheckIntegrity         = Integriteit controleren
	Wim_Rule_ReadOnly               = Alleen-lezen toegang
	Wim_Rule_Optimize               = Optimalisatie
	ResetBase                       = Grondige reiniging
	Wim_Rule_SupportEa              = Afbeeldingen met uitgebreide attributen toepassen
	Wim_Rule_WIMBoot                = Opstartbaar
	Wim_Rule_Compact                = Bestanden van het besturingssysteem comprimeren
	Win_Rule_Setbootable            = Volume-image markeren als opstartbaar
	Win_Rule_Setbootable_Tips       = Deze parameter is alleen van toepassing op Windows PE-images.\nSlechts één volume-image kan als opstartbaar worden gemarkeerd in een .wim-bestand.
	Destination                     = Bestemming

	Wim_Append                      = Toevoegen
	Wim_Capture                     = Vastleggen
	Wim_Capture_Tips                = Vastleggen van de schijfimage in een nieuw WIM-bestand.
	Wim_Capture_Sources             = Bron vastleggen
	Wim_Capture_Sources_Tips        = De vastgelegde map bevat alle submappen en gegevens.\nU kunt geen lege map vastleggen. De map moet ten minste één bestand bevatten.
	Wim_Config_File                 = Pad naar configuratiebestand ( uitsluitingen )
	Wim_Config_Edit                 = Bewerken
	Wim_Config_Learn                = Bestudeer de configuratielijst en het bestand WimScript.ini

	Wim_Rename                      = Afbeeldingsinformatie wijzigen
	Wim_Image_Name                  = Naam afbeelding
	Wim_Image_Description           = Afbeelding beschrijving
	Wim_Display_Name                = Weergavenaam
	Wim_Display_Description         = Beschrijving weergeven
	Wim_Edition                     = Afbeelding merk
	Wim_Edition_Select_Know         = Selecteer bekende afbeeldingsvlaggen
	Wim_CreatedTime                 = Aanmaakdatum
	Wim_ModifiedTime                = Laatst gewijzigde tijd
	Wim_FileCount                   = Aantal bestanden
	Wim_DirectoryCount              = Aantal mappen
	Wim_Expander_Space              = Uitbreidingsruimte

	IABSelectNo                     = Geen primaire sleutel geselecteerd: Install, WinRE, Boot
	Unique_Name                     = Unieke naamgeving
	Select_Path                     = Pad
	Setting_Pri_Key                 = Stel dit updatebestand in als hoofdsjabloon
	Pri_Key_Update_To               = Update vervolgens naar
	Pri_Key_Template                = Stel dit bestand in als de voorkeurssjabloon die met de geselecteerde items moet worden gesynchroniseerd
	Pri_key_Running                 = De primaire sleuteltaak is gesynchroniseerd en overgeslagen.
	ShowAllExclude                  = Toon alle beëindigde uitsluitingen

	Index_Process_All               = Verwerk alle bekende indexnummers
	Index_Is_Event_Select           = Wanneer er een gebeurtenis plaatsvindt, verschijnt de interface voor het selecteren van het indexnummer.
	Index_Pre_Select                = Vooraf toegewezen indexnummer
	Index_Select_Tips               = Hint: \n\n{0}.wim is momenteel niet aangekoppeld. U kunt het volgende doen:\n\n   1. Selecteer "Alle bekende indexnummers verwerken";\n\n   2. Selecteer "Als er een gebeurtenis plaatsvindt, verschijnt de interface voor het selecteren van het indexnummer";\n\n   3. Vooraf opgegeven indexnummer\n      Indexnummer 6 is opgegeven, het indexnummer bestaat niet tijdens de verwerking en de verwerking wordt overgeslagen.

	Index_Tips_Custom_Expand        = Groep: {0}\n\nBij het verwerken van {1} moet het indexnummer {2} worden toegewezen, anders kan het niet worden verwerkt.\n\nNadat u 'Bijwerkregels synchroniseren met alle indexnummers' hebt geselecteerd, hoeft u er slechts één aan te vinken als hoofdsjabloon.

	DefenderExclude                 = Uitsluitingen voor Windows Antivirus
	DefenderFolder                  = Voeg deze map toe aan de uitsluitingen voor Windows Antivirus.
	DefenderVolume                  = Nadat een overeenkomende volumelabelnaam is gevonden, voegt u deze schijf toe aan de uitsluitingen voor Windows Antivirus.
	DefenderIsAdd                   = Toegevoegd aan de uitsluitingen voor Windows Antivirus.
'@