ConvertFrom-StringData -StringData @'
	# cs-cz
	# Czech (Czech Republic)

	UnpackISO                       = Vygenerujte ISO
	ISOLabel                        = Označení svazku bylo nastaveno:
	ISOCustomize                    = Název štítku svazku ISO
	ISO9660                         = Ověřte pravidla pojmenování
	ISO9660Tips                     = Jedinečný název nesmí přesáhnout 260 znaků, název svazku ISO nesmí přesáhnout 16 znaků a nesmí obsahovat: úvodní a koncové mezery, \\ / : * ?
	ISOFolderName                   = Vlastní jedinečné pojmenování
	ISOAddFlagsLang                 = Přidejte vícejazyčné označení
	ISOAddFlagsLangGet              = Seznamte se se známými instalačními jazyky
	ISOAddFlagsVer                  = Přidejte značku pro více verzí
	ISOAddFlagsVerGet               = Seznamte se s verzí obrázku
	ISOAddEICFG                     = Přidejte typ verze
	ISOAddEICFGTips                 = Když se spoléháme na EI.cfg, jde o komerční verzi.
	ISO9660TipsErrorSpace           = Nesmí obsahovat: úvodní a koncové mezery
	ISO9660TipsErrorOther           = Nemůže obsahovat: \\ / : * ? & @ !
	SelOSver                        = Vyberte typ jazyka
	SelLabel                        = Krycí jméno
	ISOVerLabel                     = Vyberte název štítku svazku ISO
	NoSetLabel                      = Vlastní štítek svazku ISO není nastaven
	ISOLengthError                  = Jmenovka svazku nesmí být delší než {0} znaků
	RenameFailed                    = Stejné jako starý adresář, přejmenování se nezdařilo
	ISOCreateAfter                  = Co musíte udělat před vytvořením ISO
	ISOCreateRear                   = Co musíte udělat po vytvoření ISO
	BypassTPM                       = Obejít kontrolu instalace TPM
	Disable_BitLocker               = Během instalace zakažte šifrování zařízení BitLocker
	PublicDate                      = Datum vydání
	PublicDateGetCurrent            = Synchronizovat aktuální datum
	PublicYear                      = Rok
	PublicMonth                     = Měsíc
	PublicYMSorting                 = Řazení: Změnit "měsíc_rok" na "rok_měsíc"
	PublicYMSortingTips             = AB: Nepřidávat podtržítko _ při použití čísel.
	PublicYMUseShortNames           = Používat krátké názvy
	PublicYMUseNumbers              = Používat čísla
	ISOCreateFailed                 = Vytvoření se nezdařilo, adresář není čitelný ani zapisovatelný.
	ISORefreshAuto                  = Pokaždé obnovte ISO tagy
	ISOSaveTo                       = Výchozí umístění uložení ISO
	ISOSaveSameGlobal               = Použít globální výchozí umístění pro uložení ISO
	ISOSaveSync                     = Automaticky synchronizovat nové umístění po výběru disku pro vyhledávání zdroje obrazu
	ISOSaveSame                     = Vyhledejte cestu k disku pomocí zdroje obrazu
	ISOFolderWrite                  = Ověřte, zda je adresář čitelný a zapisovatelný
	SelectAutoAvailable             = Při automatickém výběru dostupného disku
	SelectCheckAvailable            = Zkontrolujte minimální dostupné zbývající místo
	ISOStructure                    = Nová adresářová struktura
	ISOOSLevel                      = Přidejte typ instalace
	ISOUniqueNameDirectory          = Přidejte adresář jedinečných jmen
	NextDoOperate                   = Nevytvářejte ISO
	SelCreateISO                    = Vygenerujte ISO, spusťte na vyžádání
	Reconstruction                  = Znovu vytvořte soubor {0}.wim s maximální kompresí
	Reconstruction_Tips_Select      = Před opětovným sestavením se provede pouze v případě, že není načten, vynutí povolení ukládání a poté odpojí připojený soubor.
	ReconstructionTips              = Více než 520 MB, doporučeno znovu sestavit
	CreateASC                       = Přidejte podpis PGP do ISO
	NoPGPKey                        = V PGP neexistuje žádný použitelný soukromý klíč.
	CreateASCPwd                    = Heslo certifikátu
	PasswordRenter                  = Znovu zadejte heslo
	ShowPassword                    = Zobrazit heslo
	NewPasswordSome                 = Heslo se neshoduje.
	PwdPermanent                    = Trvalé úložiště
	PwdDecfailed                    = Dešifrování se nezdařilo
	CreateASCAuthor                 = Signatář
	CreateASCAuthorTips             = Nebyli vybráni žádní signatáři.
	ISO_Sparse_Rename               = Přidat hash k příponě názvu souboru
	GenerateRandom                  = Generujte náhodná čísla
	RandomNumberReset               = Regenerovat
'@