ConvertFrom-StringData -StringData @'
	# el-GR
	# Greek (Greece)

	FontsUI                   = Segoe UI
	Mainname                  = Μηχανή ανάπτυξης: Η σουίτα του Yi
	Learn                     = Μελέτη
	MainHisName               = Λύση μπόνους
	Location                  = Ανοιχτή τοποθεσία
	About                     = Για
	Reset                     = Επαναφορά
	AddTo                     = Προσθήκη σε
	Instl                     = Εγκαθιστώ
	ItInstalled               = Εγκατεστημένο
	Close                     = Κλείσιμο
	Auto                      = Αυτόματο
	Disable                   = Καθιστώ ανίκανο
	Enable                    = Καθιστώ ικανό
	Setting                   = Στήνω
	Restore                   = Ανακτώ
	CLearn                    = Εκκαθάριση
	Operable                  = Εγχειρήσιμος
	Inoperable                = Μη χειρουργήσιμος
	Optimize                  = Βελτιστοποίηση
	Hide                      = Κρύβω
	Show                      = Επίδειξη
	Del                       = Διαγράφω
	Done                      = Φινίρισμα
	OK                        = Σίγουρος
	Cancel                    = Ματαίωση
	AllSel                    = Επιλέξτε όλα
	AllClear                  = Καθαρίστε όλα
	Refresh                   = Φρεσκάρω
	RefreshModules            = Ζεστή ανανέωση όλων των μονάδων
	Necessary                 = Βασικό λογισμικό
	MostUsedSoftware          = Λογισμικό που χρησιμοποιείται συνήθως
	System                    = Σύστημα
	Service                   = Σερβίρισμα
	TaskBar                   = Όλα τα εικονίδια της γραμμής εργασιών
	DeskIcon                  = Εικονίδια επιφάνειας εργασίας
	InstallFonts              = Εγκαταστήστε γραμματοσειρές
	SettingTo                 = Ορίστηκε σε {0}
	AvailableLanguages        = Διαθέσιμες γλώσσες
	SwitchLanguage            = Αλλαγή γλώσσας
	LanguageReset             = Επαναφορά ρυθμίσεων γλώσσας
	LanguageCode              = Σήμα ζώνης
	LanguageSelRegion         = Επιλέξτε τη χώρα ή την περιοχή σας
	LanguageRemember          = Θυμηθείτε την επιλεγμένη γλώσσα
	LanguageSearchNo          = Δεν βρέθηκαν διαθέσιμες γλώσσες
	LanguageNoPack            = Εάν δεν υπάρχει πακέτο γλώσσας τοπικά, θα βγει αυτόματα.
	LanguageNoSel             = Επιλέξτε μια περιοχή
	Search                    = Έρευνα
	PleaseChoose              = Επιλέξτε
	FailedCreateFolder        = Αποτυχία δημιουργίας καταλόγου
	Failed                    = Αποτυγχάνω
	ToMsg                     = {0} Αυτόματη επιστροφή στο κύριο μενού μετά από δευτερόλεπτα.
	Restart                   = Η επανεκκίνηση τίθεται σε ισχύ
	AdvOption                 = Προαιρετικά χαρακτηριστικά

	StartDown                 = Ξεκινήστε τη λήψη
	ConnectTo                 = Συνδεθείτε με
	FileName                  = Όνομα αρχείου
	SaveTo                    = Αποθήκευση σε
	NotAvailable              = Κατάσταση: Μη διαθέσιμο
	ExistingPacker            = Υπάρχει ήδη πακέτο εγκατάστασης
	ExistingInstlPacker       = Έχετε ήδη μια συμπιεσμένη συσκευασία
	Unpacking                 = Αποσυμπίεση
	QucikRun                  = Γρήγορο τρέξιμο:
	WaitDone                  = Αναμονή για ολοκλήρωση:
	Parameter                 = Παράμετρος:
	ErrorDown                 = Παρουσιάστηκε σφάλμα κατά τη λήψη
	UserCancel                = Ο χρήστης ακύρωσε τη λειτουργία.

	VerifyNameTips            = Επιτρέπεται μόνο ένας συνδυασμός αγγλικών γραμμάτων και αριθμών και δεν επιτρέπονται άλλοι χαρακτήρες: κενά, το μήκος δεν μπορεί να είναι μεγαλύτερο από 16 χαρακτήρες, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Πρόθεμα προσαρμοσμένου καταλόγου
	NoSetFolderLabel          = Το πρόθεμα προσαρμοσμένου καταλόγου δεν έχει οριστεί
	ISO9660TipsErrorSpace     = Δεν μπορεί να περιέχει: προπορευόμενους και πίσω χώρους
	ISO9660TipsErrorOther     = Δεν μπορεί να περιέχει: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Η ετικέτα τόμου δεν μπορεί να υπερβαίνει τους {0} χαρακτήρες
	Help                      = Βοήθεια
	WorkDone                  = Ολοκληρώθηκε, πατήστε οποιοδήποτε πλήκτρο για να επιστρέψετε στην κύρια διεπαφή...
	Short_Cmd                 = Εντολή συντόμευσης
	Options                   = Επιλογές
'@