ConvertFrom-StringData -StringData @'
	# ru-RU
	# Russian (Russia)

	UnpackISO                       = Создать ISO
	ISOLabel                        = Метка тома установлена:
	ISOCustomize                    = Имя метки тома ISO
	ISO9660                         = Проверьте правила именования
	ISO9660Tips                     = Уникальное имя не может превышать 260 символов, имя тома ISO не может превышать 16 символов и не может содержать: начальные и конечные пробелы, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Пользовательское уникальное имя
	ISOAddFlagsLang                 = Добавить многоязычную разметку
	ISOAddFlagsLangGet              = Получить известные языки установки
	ISOAddFlagsVer                  = Добавить тег нескольких версий
	ISOAddFlagsVerGet               = Получить известную версию образа
	ISOAddEICFG                     = Добавить тип версии
	ISOAddEICFGTips                 = Если использовать EI.cfg, это коммерческая версия.
	ISO9660TipsErrorSpace           = Не может содержать: начальные и конечные пробелы.
	ISO9660TipsErrorOther           = Не может содержать: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Выберите тип языка
	SelLabel                        = Кодовое имя
	ISOVerLabel                     = Выберите имя тома ISO
	NoSetLabel                      = Пользовательская метка тома ISO не установлена
	ISOLengthError                  = Метка тома не может содержать более {0} символов.
	RenameFailed                    = То же, что и старый каталог, переименовать не удалось.
	ISOCreateAfter                  = Что нужно сделать перед созданием ISO
	ISOCreateRear                   = Что вам нужно сделать после создания ISO
	BypassTPM                       = Обход проверки установки TPM
	Disable_BitLocker               = Отключить шифрование устройства BitLocker во время установки.
	PublicDate                      = Дата выпуска
	PublicDateGetCurrent            = Синхронизировать текущую дату
	PublicYear                      = Год
	PublicMonth                     = Луна
	PublicYMSorting                 = Сортировка производится путем замены "месяц-год" на "год-месяц".
	PublicYMSortingTips             = AB: Не добавляйте нижнее подчеркивание _ при использовании чисел.
	PublicYMUseShortNames           = Используйте короткие названия
	PublicYMUseNumbers              = Используйте числа
	ISOCreateFailed                 = Не удалось создать, каталог недоступен для чтения и записи.
	ISORefreshAuto                  = Обновляйте ISO-теги каждый раз
	ISOSaveTo                       = Место сохранения ISO по умолчанию
	ISOSaveSameGlobal               = Использовать глобальное местоположение сохранения ISO по умолчанию.
	ISOSaveSync                     = Автоматически синхронизировать новое местоположение после выбора диска поиска источника изображения.
	ISOSaveSame                     = Поиск пути к диску с использованием источника изображения
	ISOFolderWrite                  = Убедитесь, что каталог доступен для чтения и записи.
	SelectAutoAvailable             = При автоматическом выборе доступного диска
	SelectCheckAvailable            = Проверьте минимально доступное оставшееся пространство
	ISOStructure                    = Новая структура каталогов
	ISOOSLevel                      = Добавить тип установки
	ISOUniqueNameDirectory          = Добавить каталог с уникальным именем
	NextDoOperate                   = Не создавайте ISO
	SelCreateISO                    = Генерация ISO, выполнение по требованию
	Reconstruction                  = Пересоберите {0}.wim с максимальным сжатием.
	Reconstruction_Tips_Select      = Перед пересборкой он будет выполняться только тогда, когда он не загружен. Он принудительно включит сохранение, а затем отмонтирует смонтированный файл.
	ReconstructionTips              = Более 520 МБ, рекомендуется перестроить
	CreateASC                       = Добавить подпись PGP в ISO
	NoPGPKey                        = В PGP отсутствует пригодный для использования закрытый ключ.
	CreateASCPwd                    = Пароль сертификата
	PasswordRenter                  = Повторно введите пароль
	ShowPassword                    = Показать пароль
	NewPasswordSome                 = Пароль не совпадает
	PwdPermanent                    = Постоянное хранилище
	PwdDecfailed                    = Расшифровка не удалась
	CreateASCAuthor                 = Подписавший
	CreateASCAuthorTips             = Подписывающие стороны не выбраны.
	ISO_Sparse_Rename               = Добавьте хеш к расширению имени файла.
	GenerateRandom                  = Генерировать случайные числа
	RandomNumberReset               = Регенерировать
'@