ConvertFrom-StringData -StringData @'
	# cs-CZ
	# Czech (Czech Republic)

	FontsUI                   = Segoe UI
	Mainname                  = Deployment engine: Yi's suite
	Learn                     = Studie
	MainHisName               = Bonusové řešení
	Location                  = Otevřené umístění
	About                     = O
	Reset                     = Resetovat
	AddTo                     = Přidat do
	Instl                     = Instalovat
	ItInstalled               = Instalováno
	Close                     = Uzavření
	Auto                      = Automatický
	Disable                   = Zakázat
	Enable                    = Umožnit
	Setting                   = Nastavit
	Restore                   = Zotavit se
	CLearn                    = Uklidit
	Operable                  = Operativní
	Inoperable                = Nefunkční
	Optimize                  = Optimalizace
	Hide                      = Skrýt
	Show                      = Show
	Del                       = Vymazat
	Done                      = Dokončit
	OK                        = Jasně
	Cancel                    = Zrušit
	AllSel                    = Vyberte vše
	AllClear                  = Vymazat vše
	Refresh                   = Osvěžit
	RefreshModules            = Hot aktualizovat všechny moduly
	Necessary                 = Nezbytný software
	MostUsedSoftware          = Běžně používaný software
	System                    = Systém
	Service                   = Sloužit
	TaskBar                   = Všechny ikony na hlavním panelu
	DeskIcon                  = Ikony na ploše
	InstallFonts              = Nainstalujte písma
	SettingTo                 = Nastavit na {0}
	AvailableLanguages        = Dostupné jazyky
	SwitchLanguage            = Přepnout jazyk
	LanguageReset             = Obnovit nastavení jazyka
	LanguageCode              = Značka zóny
	LanguageSelRegion         = Vyberte svou zemi nebo oblast
	LanguageRemember          = Zapamatovat vybraný jazyk
	LanguageSearchNo          = Nebyly nalezeny žádné dostupné jazyky
	LanguageNoPack            = Pokud místně žádný jazykový balíček neexistuje, automaticky se ukončí.
	LanguageNoSel             = Vyberte prosím region
	Search                    = Vyhledávání
	PleaseChoose              = Vyberte prosím
	FailedCreateFolder        = Nepodařilo se vytvořit adresář
	Failed                    = Selhat
	ToMsg                     = {0} Po několika sekundách se automaticky vrátí do hlavní nabídky.
	Restart                   = Restart se projeví
	AdvOption                 = Volitelné funkce

	StartDown                 = Začněte stahovat
	ConnectTo                 = Připojte se k
	FileName                  = Název souboru
	SaveTo                    = Uložit do
	NotAvailable              = Stav: Není k dispozici
	ExistingPacker            = Již máte instalační balíček
	ExistingInstlPacker       = Již máte komprimovaný balíček
	Unpacking                 = Rozepínání
	QucikRun                  = Rychlý běh:
	WaitDone                  = Čekání na dokončení:
	Parameter                 = Parametr:
	ErrorDown                 = Při stahování došlo k chybě
	UserCancel                = Uživatel operaci zrušil.

	VerifyNameTips            = Je povolena pouze kombinace anglických písmen a číslic a nejsou povoleny žádné další znaky: mezery, délka nesmí být větší než 16 znaků, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Vlastní předpona adresáře
	NoSetFolderLabel          = Vlastní předpona adresáře není nastavena
	ISO9660TipsErrorSpace     = Nesmí obsahovat: úvodní a koncové mezery
	ISO9660TipsErrorOther     = Nesmí obsahovat: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Jmenovka svazku nesmí být delší než {0} znaků
	Help                      = Pomoc
	WorkDone                  = Dokončeno, stisknutím libovolné klávesy se vraťte do hlavního rozhraní...
	Short_Cmd                 = Zkratky
	Options                   = Možnosti
'@