ConvertFrom-StringData -StringData @'
	# sk-SK
	# Slovak (Slovakia)

	UnpackISO                       = Vygenerujte ISO
	ISOLabel                        = Menovka zväzku bola nastavená:
	ISOCustomize                    = Názov štítka zväzku ISO
	ISO9660                         = Overte pravidlá pomenovania
	ISO9660Tips                     = Jedinečný názov nemôže presiahnuť 260 znakov, názov zväzku ISO nemôže presiahnuť 16 znakov a nemôže obsahovať: medzery na začiatku a na konci, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Vlastné jedinečné pomenovanie
	ISOAddFlagsLang                 = Pridajte viacjazyčné označenie
	ISOAddFlagsLangGet              = Získajte známe inštalačné jazyky
	ISOAddFlagsVer                  = Pridajte značku viacerých verzií
	ISOAddFlagsVerGet               = Zoznámte sa s verziou obrázka
	ISOAddEICFG                     = Pridajte typ verzie
	ISOAddEICFGTips                 = Pri spoliehaní sa na EI.cfg ide o komerčnú verziu.
	ISO9660TipsErrorSpace           = Nemôže obsahovať: medzery na začiatku a na konci
	ISO9660TipsErrorOther           = Nemôže obsahovať: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Vyberte typ jazyka
	SelLabel                        = Kódové meno
	ISOVerLabel                     = Vyberte názov zväzku ISO
	NoSetLabel                      = Vlastné označenie zväzku ISO nie je nastavené
	ISOLengthError                  = Menovka zväzku nemôže byť dlhšia ako {0} znakov
	RenameFailed                    = Rovnako ako starý adresár, premenovanie zlyhalo
	ISOCreateAfter                  = Čo musíte urobiť pred vytvorením ISO
	ISOCreateRear                   = Čo musíte urobiť po vytvorení ISO
	BypassTPM                       = Vynechajte kontrolu inštalácie TPM
	Disable_BitLocker               = Počas inštalácie vypnite šifrovanie zariadenia BitLocker
	PublicDate                      = Dátum vydania
	PublicDateGetCurrent            = Synchronizovať aktuálny dátum
	PublicYear                      = Rok
	PublicMonth                     = Mesiac
	PublicYMSorting                 = Zoraďte zmenou "mesiac-rok" na "rok-mesiac".
	PublicYMSortingTips             = Pri použití čísel v AB nepridávajte podčiarkovník _.
	PublicYMUseShortNames           = Používajte krátke názvy.
	PublicYMUseNumbers              = Používajte čísla.
	ISOCreateFailed                 = Vytvorenie zlyhalo, adresár nie je čitateľný ani zapisovateľný.
	ISORefreshAuto                  = Zakaždým obnovujte značky ISO
	ISOSaveTo                       = Predvolené miesto uloženia ISO
	ISOSaveSameGlobal               = Použiť globálne predvolené miesto uloženia ISO
	ISOSaveSync                     = Automaticky synchronizovať nové umiestnenie po výbere disku na vyhľadávanie zdroja obrázkov
	ISOSaveSame                     = Vyhľadajte cestu k disku pomocou zdroja obrazu
	ISOFolderWrite                  = Skontrolujte, či je adresár čitateľný a zapisovateľný
	SelectAutoAvailable             = Pri automatickom výbere dostupného disku
	SelectCheckAvailable            = Skontrolujte minimálny zostávajúci priestor
	ISOStructure                    = Nová adresárová štruktúra
	ISOOSLevel                      = Pridajte typ inštalácie
	ISOUniqueNameDirectory          = Pridajte jedinečný názov adresára
	NextDoOperate                   = Nevytvárajte ISO
	SelCreateISO                    = Vygenerujte ISO, spustite na požiadanie
	Reconstruction                  = Obnovte súbor {0}.wim s maximálnou kompresiou
	Reconstruction_Tips_Select      = Pred opätovným zostavením sa vykoná iba vtedy, keď nie je načítaný, vynúti si povolenie ukladania a potom odpojí pripojený súbor.
	ReconstructionTips              = Viac ako 520 MB, odporúča sa prebudovanie
	CreateASC                       = Pridajte podpis PGP do ISO
	NoPGPKey                        = V PGP neexistuje žiadny použiteľný súkromný kľúč.
	CreateASCPwd                    = Heslo certifikátu
	PasswordRenter                  = Znovu zadajte heslo
	ShowPassword                    = Zobraziť heslo
	NewPasswordSome                 = Heslo sa nezhoduje.
	PwdPermanent                    = Trvalé úložisko
	PwdDecfailed                    = Dešifrovanie zlyhalo
	CreateASCAuthor                 = Podpisovateľ
	CreateASCAuthorTips             = Nie sú vybratí žiadni signatári.
	ISO_Sparse_Rename               = Pridajte hash k prípone názvu súboru
	GenerateRandom                  = Generujte náhodné čísla
	RandomNumberReset               = Regenerovať
'@