ConvertFrom-StringData -StringData @'
	# ko-KR
	# Korean (Korea)

	FontsUI                         = Malgun Gothic

	# Main page
	Dashboard                       = 계기반
	Learn                           = 공부하다
	Menu                            = 메뉴
	Short_Cmd                       = 바로 가기 명령
	Shortcut                        = 지름길
	Update                          = 고쳐 쓰다
	CUpdate                         = 누적 업데이트
	Rebuild                         = 재건
	AddTo                           = 에 추가
	Del                             = 삭제
	Copy                            = 복사
	Rename                          = 이름 바꾸기
	Refresh                         = 새로 고치다
	RefreshModules                  = 모든 모듈을 핫 리프레시
	Done                            = 마치다
	OK                              = 확신하는
	Cancel                          = 취소
	AllSel                          = 모두 선택
	AllClear                        = 모두 지우기
	Setting                         = 설정
	Change                          = 잔돈
	Help                            = 돕다
	Logging                         = 다음 위치에 로그 저장
	AvailableLanguages              = 사용 가능한 언어
	SwitchLanguage                  = 언어를 바꾸다
	LanguageSelRegion               = 국가 또는 지역을 선택하세요.
	LanguageRemember                = 선택한 언어 기억
	LanguageSearchNo                = 사용 가능한 언어가 없습니다
	LanguageNoPack                  = 로컬에 언어 팩이 없으면 자동으로 종료됩니다.
	LanguageNoSel                   = 지역을 선택해주세요
	Search                          = 찾다
	PleaseChoose                    = 선택해주세요
	Options                         = 옵션
	Choose                          = 선택된
	NoChoose                        = 선택되지 않은
	AdvOption                       = 옵션 기능
	ExcludeItem                     = 규칙에 따라 제외
	DeDuplication                   = 중복 제외
	DeDuplication_Unlock            = 비활성화된 중복 잠금 해제
	Existed                         = 존재했다
	FailedCreateFolder              = 디렉토리 생성 실패
	FailedCreateFile                = 파일 생성 실패
	ToMsg                           = {0} 몇 초 후에 자동으로 기본 메뉴로 돌아갑니다.
	OnDemandPlanTask                = 사용자 지정 알려진 이벤트 할당
	Operable                        = 운영
	Inoperable                      = 작동 불능
	Hide                            = 숨다
	CuringUpdate                    = 경화 업데이트
	CuringUpdateTips                = 펌웨어 업데이트 후에는 제거할 수 없습니다.
	Healthy                         = 건강한
	HealthyTips                     = 건강 상태를 확인하는 것이 특히 중요합니다. "repairable" 또는 "unrepairable" 이 표시되면 ESD 변환 프로세스 동안 오류 13 이 표시되고 데이터가 유효하지 않으며 시스템 설치 시 오류가 보고됩니다.
	Healthy_Save                    = 수리 가능 또는 수리 불가가 표시되면 저장하지 마십시오.
	Repair                          = 수리하다
	IsAuto_Repair                   = 유휴 상태일 때 자동 복구 허용
	IsAuto_Repair_Tips              = 패키징 스크립트를 실행할 때마다 탑재 작업이 있는지 자동으로 확인합니다. 마운트된 경우 복구가 수행되지 않으며, 마운트되지 않은 경우 자동 복구가 실행됩니다.
	Repairable                      = 수리 가능
	NonRepairable                   = 돌이킬 수 없는
	HealthyForceStop                = 이벤트 처리 중 되돌릴 수 없는 오류가 발생하여 강제 종료되었습니다.\n\n   주요 문제의 원인:\n\n      1. 물리적 하드웨어 손상, 하드 디스크;\n\n      2. RAMDISK 메모리 가상 디스크 (하이브리드 포함) 를 사용하는 경우 물리적 메모리를 확인하십시오.\n\n      3. 원본 MSDN 버전의 SHA256 을 확인하십시오.동일한 경우 디렉토리를 변경하고 다시 시도하십시오 .SHA256 이 일치하지 않으면 다운로드하여 다시 시도하십시오.\n\n      4. 이 예에 나열되지 않은 기타.
	Superseded                      = 청소 교체
	SupersededTips                  = 오래된 업데이트, 구성 요소 등이 포함됩니다
	UnmountFailed                   = 이미 여러 방법을 써봤지만 할 수 있는 게 없어요. 동생은 이때만 공격할 수 있어요. 다음에 영웅들과 함께 뵙고 싶어요.
	SaveTo                          = 저장 위치
	WorkDone                        = 완료, 기본 인터페이스로 돌아가려면 아무 키나 누르십시오...
	UserCanel                       = 사용자가 요청을 취소했습니다.
	Uping                           = 생성
	Exclude_View                    = 제외 규칙 보기
	User_Interaction                = 사용자 상호 작용
	Ok_Go_To                        = 사용할 수
	Ok_Go_To_No                     = 안 가요

	Detailed                        = 자세한 내용
	Detailed_View                   = 선택한 규칙 세부 정보를 봅니다

	AddEnv                          = 시스템 변수에 라우팅 기능을 추가합니다
	AddEnvTips                      = PowerShell 세션에 Yi를 입력하여 응답합니다. 예를 들어 "Yi -SIP"를 입력하여 캡슐화를 실행합니다.

	Unzip_ISO                       = 발췌 ISO
	Unzip_Search_Type               = 검색 디렉토리 ( {0} )
	ISO_Other                       = 다른 파일들
	Unzip_Language                  = 언어 팩
	Unzip_Fod                       = 기능 팩
	FileName                        = 파일

	UserCancel                      = 사용자가 작업을 취소했습니다.
	MatchMode                       = 성냥
	Failed                          = 실패하다
	RandomSelect                    = 임의 선택
	RulePre                         = 사전 설정 규칙입니다
	RuleOther                       = 기타 규칙
	RuleCustomize                   = 규칙을 사용자 지정합니다
	RuleCustomize_Dont              = 다단계 카탈로그 사용자 지정 규칙을 사용하지 않음
	RuleCustomize_Dont_Tips         = 이전 디렉토리를 삭제한 후 "명명 규칙 유효성 검사"를 클릭합니다.
	RuleMultistage                  = 다단계 디렉터리 규칙입니다
	RuleMultistageFindFailed        = 다단계 디렉터리 규칙이 발견되지 않았습니다.
	RuleMultistageFindCreateNew     = 새 다중 수준 디렉터리 규칙 템플릿 만들기
	RuleMultistageTips              = 다단계 카탈로그 규칙에 자동으로 적응하고 {0} 카탈로그 규칙을 비활성화합니다.
	RuleCustomizeNot                = 확장 이름 (Solutions.Custom.Extension) 을 찾을 수 없습니다. 도움말 설명서를 참조하십시오.
	RuleCustomizeTips               = 새 사용자 지정 규칙이 만들어지지 않았습니다.
	RuleMatchNoFindFolder           = 우선 순위 일치 후, 찾을 수 없습니다, 내가 카탈로그를 만들 수 있습니다.
	RuleNoFindFile                  = 사용할 수 있는 파일을 찾을 수 없습니다.
	RuleFindFolder                  = 카탈로그를 사용할 수 있게 되면 자동으로 선택됩니다
	RuleNameNewChange               = 업데이트 후 자동으로 동기화
	RuleNewTempate                  = 템플릿 만들기
	RuleSkipFolderCheck             = 더 이상 디렉토리에 파일이 있는지 확인하지 않습니다. 파일 유형
	RuleAuthon                      = 규칙 작성자입니다
	RuleGUID                        = GUID 전역 고유 식별자입니다
	RuleName                        = 규칙 이름입니다
	RuleDescription                 = 설명입니다
	RuleNameUse                     = 규칙 이름을 다음에 동기화: {0}
	RuleISO                         = 원래 InBox Apps 설치 패키지와 일치합니다
	RuleInBoxApps                   = 전체 프로비전된 응용 프로그램입니다
	RuleFileType                    = 패키지 이름입니다
	RuleFileFind                    = 퍼지 조회 이름입니다
	RuleFindError                   = {0} 항목을 찾을 수 있습니다., 자세한 내용을 보려면 "종속성 확인"을 클릭.
	RuleSelectApps                  = 사용자가 선택한 응용 프로그램입니다
	DependencyPackage               = 依存関係パッケージ
	RuleDependenciesRequired        = 필요한 종속성입니다
	RuleDependenciesUnselected      = 선택되지 않은 종속성입니다
	RuleDependenciesNoCheck         = 종속성은 더 이상 검사되지 않습니다
	RuleDependenciesFix             = 선택되지 않은 종속성을 수정합니다
	Extract_Tips                    = 힌트\n\n   1. 언어 팩을 추출한 후의 결과는 기본 참조 개체로 사용할 수 없습니다.\n\n   2. 구성 요소 목록을 주요 참조 개체로 사용하십시오. 생성 방법: \n\n       존재하다 Functions 구성 요소 빌드(설치된 이미지에서 패키지 가져오기)를 선택하고 인쇄 또는 인스턴트 보기를 선택합니다.\n\n   3. 언어 팩을 설치한 후 구성 요소 보고서를 재생성하여 일치하는지 확인하십시오.

	DescendingRuleLang              = 언어 팩을 역순으로 제거
	OrderRuleLang                   = 사전 규정된 순서로 언어 팩 설치
	OrderRuleLangTips               = 순서대로 추가됨: 기본, 글꼴, 광학 문자 인식, 필기 인식, 텍스트 음성 변환, 음성 인식, 소매 데모 체험, 기타
	RuleLanguageTips                = 예시: \n\n   "규칙 이전 순서로 언어 팩 설치"를 사용한 후 파일은 다음 순서로 모호한 이름으로 자동 일치됩니다.\n
	Match_installed_List            = 언어 팩을 설치할 때 설치된 목록에서 와일드카드 지정
	Match_installed_List_Tips       = 일치하도록 설치: 기본, 광학 문자 인식, 필기 인식, 텍스트 음성 변환, 음성 인식.
	RuleLanguageTipsExt             = \n   "사전 규칙 순서로 언어 팩 설치"를 사용하지 않는 경우:\n   디렉터리의 모든 파일을 파일 형식으로 자동 검색하여 설치합니다.\n\n   언어 및 지역 주문형 기능 (FOD)\n   https://learn.microsoft.com/ko-kr/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = 분류에서
	Basic                           = 기초적인
	Fonts                           = 폰트
	OCR                             = 광학 문자 인식
	Handwriting                     = 필기 인식
	TextToSpeech                    = 텍스트 음성 변환
	Speech                          = 음성 인식
	Retail                          = 소매 데모 경험
	Features_On_Demand              = 주문형 기능
	RegionSpecific                  = 기타 지역별 요구 사항
	UnassignedLangFiles             = 할당되지 않은 기타 파일입니다

	ProcessingImage                 = 이미지 처리: \
	NoInstallImage                  = 로컬에 존재하지 않음
	ConvertChk                      = 파일 확인
	WindowsFeature                  = Windows 기능
	Enable                          = 할 수 있게 하다
	Disable                         = 장애가 있는
	EnableFeatureTips               = 힌트\n\n    1. NetFx3 및 TelnetClient 가 미리 활성화된 기능 항목임을 보여줍니다.\n\n    2. "마운트" 후 더 활성화할 수 있습니다.
	ViewLanguage                    = 이미지 언어 설정 보기
	ImageLanguage                   = 이미지 언어 설정
	OnlyLangCleanup                 = 정리 구성요소: 언어별 태그 지정
	Matched_Component_Names         = 일치하는 구성 요소 이름: \
	BootProcess                     = {0}.wim 을 처리할 때
	Extract_Rule_Only_And_Full      = 선택한 언어만 추출됩니다
	Sync_Language_To                = 동기화 대상
	BootSyncToISO                   = 설치 프로그램에 언어 팩 동기화
	BootSyncToISOTips               = ISO 설치 프로그램과 동기화된 설치된 언어 팩의 오프라인 이미지.
	Setup_Fix_Missing               = 설치 프로그램 누락 항목 자동 수정
	Setup_Fix_Missing_Tips          = 설치 관리자에 arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui 가 없는 경우 추출을 열고 규칙을 선택한 다음 설치 프로그램 누락된 항목 자동 수정을 클릭합니다.
	Setup_Fix_Missing_Extract       = 설치 프로그램이 누락 된 추출을 추출합니다
	Setup_Fix_Missing_Extract_Tips  = 모든 로컬 언어 팩에서 설치 프로그램 누락 항목 추출: arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui.
	LangIni                         = Lang.ini 재생성
	LangIniTips                     = 동기화가 완료되면 ISO에서 Lang.ini 를 다시 빌드해야 합니다.
	LangNewAutoSelect               = 이벤트가 있을 때 자동으로 제안 선택
	LangNewAutoSelectTips           = "설치 프로그램에 언어 팩 동기화", "Lang.ini 재구축"이라는 새 이벤트가 선택되었습니다.
	LangNewAutoNoSelect             = 새로운 이벤트가 있습니다. "설치 프로그램에 언어 팩 동기화", "Lang.ini 다시 빌드"를 선택하는 것이 좋습니다.
	LangNewAutoNoNewSelect          = 새로운 이벤트가 없습니다. "를 선택하지 않는 것이 좋습니다. 설치 프로그램에 언어 팩 동기화", "Lang.ini 다시 빌드".
	Drive                           = 드라이브
	ViewDrive                       = 설치된 드라이버 보기
	EditionsProductKey              = 이미지 제품 키 변경
	Editions                        = 이미지 버전
	Assign_Editions                 = 이미지 버전을 기반으로 애플리케이션을 자동으로 배포합니다
	EditionsChangeTips              = 경고, 이미지 버전을 전환하기 전에 알아두십시오:\n\nMicrosoft 약관 동의\nhttps://www.microsoft.com/ko-kr/servicesagreement/default.aspx\n\n언어 개요\nhttps://learn.microsoft.com/ko-kr/windows-hardware/manufacture/desktop/languages-overview\n\n다음 버전을 만들 수 없습니다.\n   1. 국가별\n       ProfessionalCountrySpecific\n\n   2. 지역별 홈 버전\n       ProfessionalSingleLanguage\n\n이를 어길 경우 법적 처벌을 받을 수 있으니 엄정히 지켜주시기 바랍니다.\n\n변환을 계속하려면 클릭하여 경고를 수락한 다음 "숨겨진 이미지 버전 잠금 해제"를 클릭하십시오.
	EditionsChangeHide              = 숨겨진 이미지 버전 잠금 해제
	EditionsChangeAccect            = 나는 경고를 읽었으며 경고의 관련 법률에 대한 전적인 책임이 있습니다.

	SelFile                         = 파일 선택
	Rebuilding                      = 재건축 중
	RebuildAll                      = 모두 재건하다
	Export_Image                    = 수출
	SelectFromError                 = 오류
	SelectFileFormatError           = 파일 형식이 잘못되었습니다

	SearchDrive                     = 검색 주도
	SearchUpdate                    = 업데이트 검색, 입력 ( {0} ), 원천: \
	SelectFolder                    = 디렉토리 선택
	DropFolder                      = 디렉토리를 현재 창으로 드래그할 수 있습니다.
	DropFile                        = 파일을 현재 창으로 드래그할 수 있습니다.
	Sparse                          = 얇다
	CRCSHA                          = 확인
	Alternative                     = 대체 파일 이름
	ChangeInstallDisk               = 자동 디스크 선택 변경

	# View
	ExportToLogs                    = 로그에 보고서 인쇄
	ExportShow                      = 보고서를 보여주다
	MoreFeature                     = 더 많은 기능
	OpenFolder                      = 디렉토리 열기
	OpenFile                        = 파일 열기
	Running                         = 달리다
	Paste                           = 복사 경로
	Clipboard_Copy                  = 클립보드에 복사됨
	ViewWIMFileInfo                 = 이미지 보기
	GetInBoxApps                    = InBox Apps: 설치된 애플리케이션 패키지
	GetImagePackage                 = 구성요소: 이미지에 설치된 모든 패키지
	ViewMounted                     = 탑재된 모든 이미지에 대한 정보 가져오기
'@