ConvertFrom-StringData -StringData @'
	# sv-SE
	# Swedish (Sweden)

	Main_quests                     = Huvuduppgifter
	Side_quests                     = Deluppgifter
	SaveModeClear                   = Rensa vald historik
	SaveModeTipsClear               = Historiken har sparats och kan rensas
	SelectTips                      = Antydan\n\n    1. Välj namnet på bilden som ska bearbetas;\n    2. När du avbryter kommer uppgifter som kräver "montering" innan operation inte längre att träda i kraft.
	CacheDisk                       = Diskcache
	CacheDiskCustomize              = Anpassad cache-sökväg
	AutoSelectRAMDISK               = Tillåt automatiskt val av skivvolymetikett
	AutoSelectRAMDISKFailed         = Volymetikett matchade inte
	ReFS_Find_Volume                = När diskformatet REFS påträffas, exkludera
	ReFS_Exclude                    = ReFS-partition utesluten
	Disk_Not_satisfied_Exclude      = Minimikrav för disken är inte uppfyllda
	RAMDISK_Change                  = Ändra volymetikettens namn
	RAMDISK_Search                  = Sök volymetikettnamn
	RAMDISK_Restore                 = Återställ initierat volymnamn: {0}
	AllowTopMost                    = Tillåt öppna fönster att fästas på toppen
	History                         = Tydlig historia
	History_Del_Tips                = När det finns en inkapslingsuppgift, kör inte följande valfria alternativ, annars kommer det att orsaka okända problem under körningen av inkapslingsskriptet.
	History_View                    = Visa historik
	HistoryLog                      = Tillåt automatisk rengöring av stockar äldre än 7 dagar
	HistorySaveFolder               = Andra sökvägar för bildkälla
	HistoryClearappxStage           = InBox Apps: Ta bort temporära filer som genererades under installationen
	DoNotCheckBoot                  = När storleken på filen Boot.wim överstiger 520 MB, väljs ombyggnad automatiskt när ISO genereras.
	HistoryClearDismSave            = Ta bort DISM-monteringsposter som sparats i registret
	ImageSourcesClickShowKey        = Tillåt visning av menyn "Välj primärnyckel"
	ImageSourcesClickShowKeyTips    = Efter att användaren har valt bildkällan: Lägg till en meny för "Välj primärnyckel" till höger och lägg till alternativ för "Gå till": Montera, Spara, Popup.
	Clear_Bad_Mount                 = Ta bort alla resurser som är associerade med den skadade monterade bilden
	ShowCommand                     = Visa hela kommandoraden
	Command                         = Kommandoraden
	SelectSettingImage              = Bildkälla
	NoSelectImageSource             = Ingen bildkälla har valts
	SettingImageRestore             = Återställ standardmonteringsplats
	SettingImage                    = Ändra bildkällans monteringsplats
	SelectImageMountStatus          = Få monteringsstatus efter att ha valt bildkälla
	SettingImageTempFolder          = Tillfällig katalog
	SettingImageToTemp              = Den tillfälliga katalogen är densamma som den plats där den monterades
	SettingImagePathTemp            = Använda Temp-katalogen
	SettingImageLow                 = Kontrollera det minsta tillgängliga återstående utrymmet
	SettingImageNewPath             = Välj monteringsskiva
	SettingImageNewPathTips         = Det rekommenderas att du monterar den på en minnesdisk, vilket är det snabbaste. Du kan använda virtuella minnesprogram som Ultra RAMDisk och ImDisk.
	SelectImageSource               = "Deploy Engine Solution" har valts, klicka på OK.
	NoImagePreSource                = Ingen tillgänglig källa hittades, du bör: \n\n     1. Lägg till fler bildkällor till: \n          {0}\n\n     2. Välj "Inställningar" och välj igen bildkällans sökdisk;\n\n     3. Välj "ISO" och välj ISO som ska dekomprimeras, föremål som ska monteras osv.
	NoImageOtherSource              = Klicka på mig för att "Lägg till" andra sökvägar eller "Dra katalog" till det aktuella fönstret.
	SearchImageSource               = Sökskiva för bildkälla
	Kernel                          = Kärna
	Architecture                    = Arkitektur
	ArchitecturePack                = Paketarkitektur, förståelse för att lägga till regler
	ImageLevel                      = Installationstyp
	LevelDesktop                    = Skrivbordet
	LevelServer                     = Server
	ImageCodename                   = Kodnamn
	ImageCodenameNo                 = Inte igenkänd
	MainImageFolder                 = Hemkatalog
	MountImageTo                    = Montera till
	Image_Path                      = Bildväg
	MountedIndex                    = Index
	MountedIndexSelect              = Välj indexnummer
	AutoSelectIndexFailed           = Automatiskt val av index {0} misslyckades, försök igen.
	Apply                           = Ansökan
	Eject                           = Dyker upp
	Mount                           = Montera
	ReMount                         = Ommontera
	Unmount                         = Avinstallera
	Mounted                         = Monterad
	NotMounted                      = Ej monterad
	NotMountedSpecify               = Ej monterad, du kan ange monteringsplats
	MountedIndexError               = Onormal montering, radera och försök igen.
	NeedsRemount                    = Kräver ommontering
	Invalid                         = Ogiltig
	ImageSouresNoSelect             = Visa mer information efter att ha valt bildkälla
	Mounted_Mode                    = Monteringsläge
	Mounted_Status                  = Monteringsstatus
	Status                          = Status
	Image_Popup_Default             = Spara som standard
	Image_Restore_Default           = Återgå till standard
	Image_Popup_Tips                = Antydan:\n\nNär du tilldelade händelsen angav du inte indexnumret som skulle behandlas {0};\n\nUrvalsgränssnittet har för närvarande dykt upp Vänligen ange indexnumret. Efter att specifikationen är klar, rekommenderas det att du väljer "Spara som standard".
	Rule_Show_Full                  = Visa alla
	Rule_Show_Only                  = Visa bara regler
	Rule_Show_Only_Select           = Välj bland regler
	Image_Unmount_After             = Avinstallera alla monterade

	Wim_Rule_Update                 = Extrahera och uppdatera filer i bilden
	Wim_Rule_Extract                = Extrahera filer
	Wim_Rule_Extract_Tips           = Efter att ha valt sökvägsregeln, extrahera den angivna filen och spara den lokalt.

	Wim_Rule_Verify                 = Kontrollera
	Wim_Rule_Check                  = Undersöka
	Wim_Rule_CheckIntegrity         = Kontrollera integritet
	Wim_Rule_ReadOnly               = Skrivskyddad behörighet
	Wim_Rule_Optimize               = Optimering
	ResetBase                       = Djuprengöring
	Wim_Rule_SupportEa              = Tillämpa bilder med utökade attribut
	Wim_Rule_WIMBoot                = Startbar
	Wim_Rule_Compact                = Komprimera operativsystemfiler
	Win_Rule_Setbootable            = Markera volymavbildning som startbar
	Win_Rule_Setbootable_Tips       = Denna parameter gäller endast Windows PE-avbildningar.\nEndast en volymavbildning kan markeras som startbar i en .wim-fil.
	Destination                     = Destination

	Wim_Append                      = Lägg till
	Wim_Capture                     = Skapa
	Wim_Capture_Tips                = Skapa enhetsavbildningen till en ny WIM-fil.
	Wim_Capture_Sources             = Skapa källa
	Wim_Capture_Sources_Tips        = Den hämtade katalogen innehåller alla undermappar och data.\nDu kan inte spara en tom katalog. Katalogen måste innehålla minst en fil.
	Wim_Config_File                 = Konfigurationsfilens sökväg ( undantag )
	Wim_Config_Edit                 = Redigera
	Wim_Config_Learn                = Studera konfigurationslistan och WimScript.ini-filen

	Wim_Rename                      = Ändra bildinformation
	Wim_Image_Name                  = Bildens namn
	Wim_Image_Description           = Bildbeskrivning
	Wim_Display_Name                = Visningsnamn
	Wim_Display_Description         = Visa beskrivning
	Wim_Edition                     = Bildmärke
	Wim_Edition_Select_Know         = Välj kända bildflaggor
	Wim_CreatedTime                 = Skapandedatum
	Wim_ModifiedTime                = Senast ändrad tid
	Wim_FileCount                   = Antal filer
	Wim_DirectoryCount              = Antal kataloger
	Wim_Expander_Space              = Expansionsutrymme

	IABSelectNo                     = Ingen primärnyckel vald: Install, WinRE, Boot
	Unique_Name                     = Unikt namn
	Select_Path                     = Väg
	Setting_Pri_Key                 = Ställ in den här uppdateringsfilen som huvudmall
	Pri_Key_Update_To               = Uppdatera sedan till
	Pri_Key_Template                = Ställ in den här filen som den föredragna mallen som ska synkroniseras med de valda objekten
	Pri_key_Running                 = Den primära nyckeluppgiften har synkroniserats och har hoppats över.
	ShowAllExclude                  = Visa alla föråldrade uteslutningar

	Index_Process_All               = Bearbeta alla kända indexnummer
	Index_Is_Event_Select           = När det finns en händelse dyker gränssnittet för val av indexnummer upp.
	Index_Pre_Select                = Förinställt indexnummer
	Index_Select_Tips               = Antydan: \n\n{0}.wim är för närvarande inte monterad, du kan: \n\n   1. Välj "Bearbeta alla kända indexnummer";\n\n   2. Välj "När det finns en händelse kommer gränssnittet för val av indexnummer att dyka upp";\n\n   3. Förutbestämt indexnummer\n      Indexnummer 6 anges, indexnumret existerar inte under bearbetningen och bearbetningen hoppas över.

	Index_Tips_Custom_Expand        = Grupp: {0}\n\nVid bearbetning av {1} måste indexnumret {2} tilldelas, annars kan det inte bearbetas.\n\nEfter att ha valt "Synkronisera uppdateringsregler till alla indexnummer" behöver du bara markera någon som huvudmall.

	DefenderExclude                 = Windows Antivirus-undantag
	DefenderFolder                  = Lägg till den här katalogen i Windows Antivirus-undantag.
	DefenderVolume                  = När du har hittat ett matchande volymetikettnamn lägger du till den här disken i Windows Antivirus-undantag.
	DefenderIsAdd                   = Lägg till i Windows Antivirus-undantag
'@