ConvertFrom-StringData -StringData @'
	# sv-SE
	# Swedish (Sweden)

	UnpackISO                       = Skapa ISO
	ISOLabel                        = Volymetikett har ställts in:
	ISOCustomize                    = Namn på ISO-volymetikett
	ISO9660                         = Verifiera namnregler
	ISO9660Tips                     = Det unika namnet får inte överstiga 260 tecken, ISO-volymnamnet får inte överstiga 16 tecken och får inte innehålla: inledande och efterföljande mellanslag, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = Anpassad unik namngivning
	ISOAddFlagsLang                 = Lägg till flerspråkig uppmärkning
	ISOAddFlagsLangGet              = Få kända installationsspråk
	ISOAddFlagsVer                  = Lägg till tagg för flera versioner
	ISOAddFlagsVerGet               = Få känd bildversion
	ISOAddEICFG                     = Lägg till versionstyp
	ISOAddEICFGTips                 = När man förlitar sig på EI.cfg är det en kommersiell version.
	ISO9660TipsErrorSpace           = Kan inte innehålla: ledande och efterföljande utrymmen
	ISO9660TipsErrorOther           = Kan inte innehålla: \\ / : * ? & @ ! "" < > |
	SelOSver                        = Välj språktyp
	SelLabel                        = Kodnamn
	ISOVerLabel                     = Välj ISO-volymnamn
	NoSetLabel                      = Anpassad ISO-volymetikett inte inställd
	ISOLengthError                  = Volymetiketten får inte vara längre än {0} tecken
	RenameFailed                    = Samma som gammal katalog, byta namn misslyckades
	ISOCreateAfter                  = Vad du behöver göra innan du skapar en ISO
	ISOCreateRear                   = Vad du behöver göra efter att du har skapat ISO
	BypassTPM                       = Förbigå TPM installationskontroll
	Disable_BitLocker               = Inaktivera BitLocker-enhetskryptering under installationen
	PublicDate                      = Utfärdandedatum
	PublicDateGetCurrent            = Synkronisera aktuellt datum
	PublicYear                      = År
	PublicMonth                     = Månen
	PublicYMSorting                 = Sortera genom att ändra "månad-år" till "år-månad".
	PublicYMSortingTips             = Lägg inte till understreck _ när du använder siffror i AB.
	PublicYMUseShortNames           = Använd korta namn
	PublicYMUseNumbers              = Använd siffror
	ISOCreateFailed                 = Skapandet misslyckades, katalogen är inte läsbar eller skrivbar.
	ISORefreshAuto                  = Uppdatera ISO-taggar varje gång
	ISOSaveTo                       = ISO standard spara plats
	ISOSaveSameGlobal               = Använd den globala ISO-standardlagringsplatsen
	ISOSaveSync                     = Synkronisera automatiskt den nya platsen efter att ha valt bildkällans sökdisk
	ISOSaveSame                     = Sök disksökväg med bildkälla
	ISOFolderWrite                  = Kontrollera att katalogen är läsbar och skrivbar
	SelectAutoAvailable             = När du automatiskt väljer en tillgänglig disk
	SelectCheckAvailable            = Kontrollera det minsta tillgängliga återstående utrymmet
	ISOStructure                    = Ny katalogstruktur
	ISOOSLevel                      = Lägg till installationstyp
	ISOUniqueNameDirectory          = Lägg till unik namnkatalog
	NextDoOperate                   = Skapa inte ISO
	SelCreateISO                    = Generera ISO, exekvera på begäran
	Reconstruction                  = Bygg om {0}.wim med maximal komprimering
	Reconstruction_Tips_Select      = Innan du bygger om kommer den bara att köras när den inte är laddad. Det kommer att tvinga lagringen att aktiveras och sedan avmontera den monterade filen.
	ReconstructionTips              = Över 520 MB, ombyggnad rekommenderas
	CreateASC                       = Lägg till PGP-signatur till ISO
	NoPGPKey                        = Det finns ingen användbar privat nyckel i PGP.
	CreateASCPwd                    = Certifikatlösenord
	PasswordRenter                  = Ange lösenordet igen
	ShowPassword                    = Visa lösenord
	NewPasswordSome                 = Lösenordet matchar inte.
	PwdPermanent                    = Permanent lagring
	PwdDecfailed                    = Avkrypteringen misslyckades
	CreateASCAuthor                 = Undertecknare
	CreateASCAuthorTips             = Inga undertecknare har valts.
	ISO_Sparse_Rename               = Lägg till hash till filnamnstillägget
	GenerateRandom                  = Generera slumpmässiga tal
	RandomNumberReset               = Regenerera
'@