ConvertFrom-StringData -StringData @'
	# lv-LV
	# Latvian (Latvia)

	IsCreate                        = Izveidot
	Solution                        = Risinājums
	EnabledSoftwarePacker           = Kolekcija
	EnabledUnattend                 = Jāatbild iepriekš
	EnabledEnglish                  = Izvēršanas dzinējs
	UnattendSelectVer               = Atlasiet risinājuma valodu "Atbilde uz".
	UnattendLangPack                = Atlasiet valodas pakotni "Risinājums".
	UnattendSelectSingleInstl       = Vairākas valodas, pēc izvēles uzstādīšanas laikā
	UnattendSelectMulti             = Daudzvalodu
	UnattendSelectDisk              = Atlasiet risinājumu Autounattend.xml
	UnattendSelectSemi              = Pusautomātiska ir derīga visām uzstādīšanas metodēm
	UnattendSelectUefi              = UEFI tiek instalēts automātiski, un tas ir jānorāda
	UnattendSelectLegacy            = Mantojums tiek instalēts automātiski, un tas ir jānorāda
	NeedSpecified                   = Lūdzu, atlasiet, kas jānorāda:
	OOBESetupOS                     = Instalācijas interfeiss
	OOBEProductKey                  = Produkta atslēga
	OOBEOSImage                     = Izvēlieties instalējamo operētājsistēmu
	OOBEEula                        = Pieņemiet licences noteikumus
	OOBEDoNotServerManager          = Servera pārvaldnieks netiek startēts automātiski, piesakoties
	OOBEIE                          = Internet Explorer uzlabotās drošības konfigurācija
	OOBEIEAdmin                     = Aizvērt "Administrators"
	OObeIEUser                      = Aizvērt "Lietotāji"

	OOBE_Init_User                  = Sākotnējais lietotājs izpakošanas laikā
	OOBE_init_Create                = Izveidojiet pielāgotus lietotājus
	OOBE_init_Specified             = Norādiet lietotāju
	OOBE_Init_Autologin             = Automātiska pieteikšanās

	InstlMode                       = Uzstādīšanas metode
	Business                        = Biznesa versija
	BusinessTips                    = Atkarībā no EI.cfg, automātiskai instalēšanai ir jānorāda indeksa numurs.
	Consumer                        = Patērētāju versija
	ConsumerTips                    = Tas nav atkarīgs no EI.cfg. Automātiskajai instalēšanai ir jānorāda sērijas numurs.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [piestiprināt pie]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Pievienojiet sistēmas diskam mājas direktorijas nosaukumu
	VerifyNameUse                   = Pārbaudiet, vai direktorija nosaukumā nedrīkst būt
	VerifyNameTips                  = Ir atļauta tikai angļu burtu un ciparu kombinācija, un tajā nedrīkst būt: atstarpes, garums nedrīkst būt lielāks par 260 rakstzīmēm, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Verifikācija neizdevās, lūdzu, ievadiet pareizo numuru.
	VerifyNameSync                  = Iestatiet direktorija nosaukumu kā primāro lietotājvārdu
	VerifyNameSyncTips              = Administrators vairs netiek izmantots.
	ManualKey                       = Atlasiet vai ievadiet produkta atslēgu manuāli
	ManualKeyTips                   = Ievadiet derīgu produkta atslēgu. Ja atlasītais reģions nav pieejams, lūdzu, apmeklējiet Microsoft oficiālo vietni, lai pārbaudītu.
	ManualKeyError                  = Ievadītā produkta atslēga nav derīga.
	KMSLink1                        = KMS klienta iestatījumu atslēga
	KMSUnlock                       = Rādīt visus zināmos KMS sērijas numurus
	KMSSelect                       = Lūdzu, atlasiet VOL sērijas numuru
	KMSKey                          = Sērijas numurs
	KMSKeySelect                    = Mainiet izstrādājuma sērijas numuru
	ClearOld                        = Notīriet vecos failus
	SolutionsSkip                   = Izlaist risinājuma izveidi
	SolutionsTo                     = Pievienojiet "risinājumu":
	SolutionsToMount                = Uzstādīts vai pievienots rindai
	SolutionsToError                = Dažas funkcijas ir atspējotas Ja vēlaties tās izmantot, lūdzu, noklikšķiniet uz pogas "Atbloķēt".\n\n
	UnlockBoot                      = Atbloķēt
	SolutionsToSources              = Mājas direktorijs, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Atlasiet "Izvietošanas programmas" versiju
	SolutionsEngineRegionaUTF8      = Beta: globāls valodu atbalsts, izmantojot Unicode UTF-8
	SolutionsEngineRegionaUTF8Tips  = Šķiet, ka pēc atvēršanas tas var radīt jaunas problēmas. Nav ieteicams.
	SolutionsEngineRegionaling      = Mainīt uz jaunu lokalizāciju:
	SolutionsEngineRegionalingTips  = Mainiet sistēmas lokalizāciju, kas ietekmē visus datora lietotāju kontus.
	SolutionsEngineRegional         = Mainiet sistēmas lokalizāciju
	SolutionsEngineRegionalTips     = Globālais noklusējuma: {0}, mainīts uz: {1}
	SolutionsEngineCopyPublic       = Kopēt publisko {0} uz izvietošanu
	SolutionsEngineCopyOpen         = Pārlūkojiet publiskās krātuves {0} atrašanās vietu
	EnglineDoneReboot               = Restartējiet datoru
	SolutionsTipsArm64              = Priekšroka tiek dota arm64 pakotnei, un jūs izvēlaties secībā: x64, x86.
	SolutionsTipsAMD64              = Dodiet priekšroku x64 pakotnēm, secībā: x86.
	SolutionsTipsX86                = Tiek pievienotas tikai x86 pakotnes.
	SolutionsReport                 = Izveidojiet pārskatu pirms izvietošanas
	SolutionsDeployOfficeInstall    = Izvietojiet Microsoft Office instalācijas pakotni
	SolutionsDeployOfficeChange     = Mainiet izvietošanas konfigurāciju
	SolutionsDeployOfficePre        = Iepriekš instalēta pakotnes versija
	SolutionsDeployOfficeNoSelect   = Nav atlasīta neviena Office priekšinstalēšanas pakotne
	SolutionsDeployOfficeVersion    = {0} versija
	SolutionsDeployOfficeOnly       = Saglabājiet norādītās valodu pakotnes
	SolutionsDeployOfficeSync       = Saglabājiet valodas sinhronizāciju ar izvietošanas konfigurāciju
	SolutionsDeployOfficeSyncTips   = Pēc sinhronizācijas instalācijas skripts nevar noteikt vēlamo valodu.
	DeploySyncMainLanguage          = Sinhronizējiet ar galveno valodu
	SolutionsDeployOfficeTo         = Izvietojiet instalācijas pakotni uz
	SolutionsDeployOfficeToPublic   = Publiska darbvirsma
	DeployPackage                   = Izvietojiet pielāgotu savākšanas pakotni
	DeployPackageSelect             = Izvēlieties iepriekšējas savākšanas paketi
	DeployPackageTo                 = Izvietojiet pirmssavākšanas pakotni uz
	DeployToRoot                    = Sistēmas disks
	DeployPackageToSolutions        = Risinājuma mājas direktorijā
	DeployTimeZone                  = Laika josla
	DeployTimeZoneChange            = Mainīt laika joslu
	DeployTimeZoneChangeTips        = Iestatiet noklusējuma laika apgabalu, kurā jāatbild uz iepriekšējām atbildēm, pēc valodas apgabala.

	Deploy_Tags                     = Izvietošanas tags
	FirstExpProcess                 = Pirmā pieredze izvietošanas laikā, priekšnosacījumi:
	FirstExpProcessTips             = Pēc priekšnoteikumu izpildes restartējiet datoru, lai atrisinātu problēmu, kas saistīta ar restartēšanas nepieciešamību.
	FirstExpFinish                  = Pirmā pieredze, pēc priekšnoteikumu izpildes
	FirstExpSyncMark                = Atļaut globālo meklēšanu un izvietošanas tagu sinhronizāciju
	FirstExpDefender                = Pievienojiet mājas direktoriju izslēgto direktoriju aizsardzībai
	FirstExpSyncLabel               = Sistēmas diska sējuma etiķete: mājas direktorija nosaukums ir vienāds
	MultipleLanguages               = Saskaroties ar vairākām valodām:
	NetworkLocationWizard           = Tīkla atrašanās vietas vednis
	PreAppxCleanup                  = Bloķēt Appx tīrīšanas uzturēšanas uzdevumus
	LanguageComponents              = Novērsiet neizmantoto funkciju valodu pakotņu tīrīšanu pēc pieprasījuma
	PreventCleaningUnusedLP         = Novērst neizmantoto valodu pakotņu tīrīšanu
	FirstExpContextCustomize        = Pievienojiet personalizētu kontekstizvēlni
	FirstExpContextCustomizeShift   = Turiet nospiestu taustiņu Shift un ar peles labo pogu noklikšķiniet

	FirstExpFinishTips              = Pēc izvietošanas pabeigšanas nav svarīgu notikumu. Ieteicams to atcelt.
	FirstExpFinishPopup             = Uznirst izvietošanas dzinēja galvenā saskarne
	FirstExpFinishOnDemand          = Atļaut pirmo priekšskatījumu, kā plānots
	SolutionsEngineRestricted       = Atjaunot Powershell izpildes politiku: ierobežota
	EnglineDoneClearFull            = Izdzēsiet visu risinājumu
	EnglineDoneClear                = Izdzēsiet izvietošanas programmu un saglabājiet pārējos

	Unattend_Auto_Fix_Next          = Nākamreiz, kad ar to saskaraties, automātiski atlasiet vajadzīgos vienumus, lai to automātiski labotu.
	Unattend_Auto_Fix               = Automātiski labot, ja nav atlasīti priekšnosacījumi
	Unattend_Auto_Fix_Tips          = Pievienojot izvietošanas dzinēju un neizvēloties pirmo palaišanas komandu, tā tiek automātiski salabota un atlasīta: Powershell izpildes politika: palaist izvietošanas dzinēju bez ierobežojumiem.
	Unattend_Version_Tips           = Pēc izvēles iekļaut tikai, izmantojiet noklusējuma iestatījumu, lai atbalstītu ARM64, x64, x86.
	First_Run_Commmand              = Komandas izpildīt, izvietojot pirmo reizi
	First_Run_Commmand_Setting      = Atlasiet komandu, kuru palaist
	Command_Not_Class               = Filtrēšanas laikā vairs netiek automātiski iedalītas kategorijās
	Command_WinSetup                = Windows instalēšana
	Command_WinPE                   = Windows PE
	Command_Tips                    = Lūdzu, piešķiriet First Run App: Windows Installation, Windows PE\n\nŅemiet vērā, ka, pievienojot izvietošanas programmu, pirmo reizi palaižot, ir jāpārbauda tālāk norādītā informācija: Powershell izpildes politika: ierobežota, ļaut palaist izvietošanas programmas skriptus.
	Waring_Not_Select_Command       = Pievienojot izvietošanas programmu, Powershell izpildes politika netika atlasīta: Neiestatiet nekādus ierobežojumus un ļaujiet izvietošanas programmas skriptam palaist, lūdzu, atlasiet to un mēģiniet vēlreiz vai noklikšķiniet uz "Ātrā labošana nav atlasīta".
	Quic_Fix_Not_Select_Command     = Ātrais labojums nav iespēja

	PowerShell_Unrestricted         = Powershell izpildes politika: bez ierobežojumiem
	Allow_Running_Deploy_Engine     = Ļaujiet palaist izvietošanas programmas skriptus
'@