ConvertFrom-StringData -StringData @'
	# da-DK
	# Danish (Denmark)

	FontsUI                   = Segoe UI
	Mainname                  = Implementeringsmotor: Yi's suite
	Learn                     = Studere
	MainHisName               = Bonus løsning
	Location                  = Åben placering
	About                     = Om
	Reset                     = Nulstilles
	AddTo                     = Tilføj til
	Instl                     = Installere
	ItInstalled               = Installeret
	Close                     = Lukning
	Auto                      = Automatisk
	Disable                   = Deaktiver
	Enable                    = Aktivere
	Setting                   = Sætte op
	Restore                   = Genvinde
	Clean                     = Rydde op
	Operable                  = Kan betjenes
	Inoperable                = Ubrugelig
	Optimize                  = Optimering
	Hide                      = Skjule
	Show                      = Vise
	Del                       = Slette
	Done                      = Slutte
	OK                        = Sikker
	Cancel                    = Ophæve
	AllSel                    = Vælg alle
	AllClear                  = Ryd alt
	Refresh                   = Opfriske
	RefreshModules            = Hot opdater alle moduler
	Necessary                 = Vigtig software
	MostUsedSoftware          = Almindelig brugt software
	System                    = System
	Service                   = Tjene
	TaskBar                   = Alle proceslinjeikoner
	DeskIcon                  = Skrivebordsikoner
	InstallFonts              = Installer skrifttyper
	SettingTo                 = Indstil til {0}
	Command                   = Kommandolinje
	RuleName                  = Regelnavn
	Language                  = Sprog
	AvailableLanguages        = Tilgængelige sprog
	SwitchLanguage            = Skifte sprog
	LanguageReset             = Nulstil sprogindstillinger
	LanguageCode              = Zonemærke
	LanguageSelRegion         = Vælg dit land eller område
	LanguageRemember          = Husk det valgte sprog
	LanguageSearchNo          = Ingen tilgængelige sprog fundet
	LanguageNoSel             = Vælg venligst en region
	Search                    = Søge
	PleaseChoose              = Vælg venligst
	FailedCreateFolder        = Kunne ikke oprette mappe
	Failed                    = Svigte
	ToMsg                     = {0} Vend automatisk tilbage til hovedmenuen efter sekunder.
	Restart                   = Genstart træder i kraft
	AdvOption                 = Valgfrie funktioner

	StartDown                 = Begynd at downloade
	ConnectTo                 = Opret forbindelse til
	FileName                  = Filnavn
	SaveTo                    = Gemme til
	NotAvailable              = Status: Ikke tilgængelig
	ExistingPacker            = Har allerede en installationspakke
	ExistingInstlPacker       = Har allerede en komprimeret pakke
	Unpacking                 = Udpakker
	QucikRun                  = Hurtigt løb:
	WaitDone                  = Venter på færdiggørelse:
	Parameter                 = Parameter:
	ErrorDown                 = Der opstod en fejl under download
	UserCancel                = Brugeren har annulleret handlingen.

	VerifyNameTips            = Kun en kombination af engelske bogstaver og tal er tilladt, og ingen andre tegn er tilladt: mellemrum, længden må ikke være større end 16 tegn, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Brugerdefineret mappepræfiks
	NoSetFolderLabel          = Tilpasset bibliotekspræfiks ikke angivet
	ISO9660TipsErrorSpace     = Må ikke indeholde: førende og efterfølgende mellemrum
	ISO9660TipsErrorOther     = Kan ikke indeholde: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Volumeetiketten må ikke være længere end {0} tegn
	Help                      = Hjælp
	WorkDone                  = Fuldført, tryk på en vilkårlig tast for at vende tilbage til hovedgrænsefladen...
	Short_Cmd                 = Genveje
	Options                   = Valgmuligheder
	LXPsWaitAssign            = Skal tildeles
	Running                   = Løbe
	SpecialFunction           = PowerShell funktioner
'@