ConvertFrom-StringData -StringData @'
	# fr-ca
	# French (Canada)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Tableau de bord
	Learn                           = Étude
	Menu                            = Menu
	Short_Cmd                       = Raccourcis
	Shortcut                        = Raccourci
	Update                          = Renouveler
	CUpdate                         = Mises à jour cumulatives
	Rebuild                         = Reconstruction
	AddTo                           = Ajouter à
	Del                             = Supprimer
	Copy                            = Copie
	Rename                          = Rebaptiser
	Refresh                         = Rafraîchir
	RefreshModules                  = Rafraîchir à chaud tous les modules
	Done                            = Finition
	OK                              = Bien sûr
	Cancel                          = Annuler
	AllSel                          = Sélectionner tout
	AllClear                        = Effacer tout
	Setting                         = Installation
	Change                          = Changement
	Help                            = Aide
	Logging                         = Enregistrer le journal dans
	AvailableLanguages              = Langues offertes
	SwitchLanguage                  = Changer de langue
	LanguageSelRegion               = Choisissez votre pays ou région
	LanguageRemember                = Mémoriser la langue sélectionnée
	LanguageSearchNo                = Aucune langue disponible trouvée
	LanguageNoPack                  = S'il n'y a pas de module linguistique localement, il se fermera automatiquement.
	LanguageNoSel                   = Veuillez choisir une région
	Search                          = Recherche
	PleaseChoose                    = Veuillez choisir
	Options                         = Possibilités
	Choose                          = Choisi
	NoChoose                        = Non sélectionné
	AdvOption                       = Fonctionnalités optionnelles
	ExcludeItem                     = Exclure par règle
	DeDuplication                   = Exclure les doublons
	DeDuplication_Unlock            = Déverrouiller les doublons désactivés
	Existed                         = Existe déjà
	FailedCreateFolder              = Échec de la création du répertoire
	FailedCreateFile                = Échec de la création du fichier
	ToMsg                           = {0} Retour automatique au menu principal après quelques secondes.
	OnDemandPlanTask                = Affectation personnalisée des événements connus
	Operable                        = Opérable
	Inoperable                      = Inopérable
	Hide                            = Cacher
	CuringUpdate                    = Mise à jour solide
	CuringUpdateTips                = Une fois la mise à jour solidifiée, elle ne peut plus être désinstallée.
	Healthy                         = En santé
	HealthyTips                     = Il est particulièrement important de vérifier l'état de santé lorsque " réparable " ou " irréparable " apparaît : pendant le processus de conversion ESD, l'erreur 13 s'affiche et les données sont invalides. du système.
	Healthy_Save                    = Lorsque réparable ou irréparable apparaît, n'enregistrez pas.
	Repair                          = Réparation
	IsAuto_Repair                   = Autoriser la réparation automatique en cas d'inactivité
	IsAuto_Repair_Tips              = Vérifiez automatiquement s'il y a des tâches de montage après chaque exécution du script d'empaquetage. S'il est monté, aucune réparation ne sera effectuée ; s'il n'est pas monté, une réparation automatique sera exécutée.
	Repairable                      = Réparable
	NonRepairable                   = Non réparable
	HealthyForceStop                = Lors du traitement de l'événement, une erreur irréversible s'est produite et le processus a été interrompu de force.\n\n   Provoque les principaux problèmes: \n\n      1. Le matériel physique est endommagé, le disque dur;\n\n      2. Si vous utilisez un disque virtuel de mémoire RAMDISK (y compris hybride), veuillez vérifier la mémoire physique;\n\n      3. Vérifiez le SHA256 d'origine de MVS (MSDN). S'il est cohérent, veuillez modifier le répertoire et réessayez.\n\n      4. D'autres ne sont pas énumérés dans cet exemple.
	Superseded                      = Nettoyer le remplacé
	SupersededTips                  = Inclut les mises à jour, les composants, etc.
	UnmountFailed                   = J'ai essayé plusieurs méthodes, mais rien ne peut être fait.
	SaveTo                          = Enregistrer dans
	WorkDone                        = Terminé, appuyez sur n'importe quelle touche pour retourner à l'interface principale...
	UserCanel                       = L'utilisateur a annulé la demande.
	Uping                           = Générateur
	Exclude_View                    = Afficher les règles d'exclusion
	User_Interaction                = Interaction avec l'utilisateur
	Ok_Go_To                        = Disponible pour
	Ok_Go_To_No                     = J'y vais pas

	Detailed                        = Détaillé
	Detailed_View                   = Afficher les détails de la règle sélectionnée

	AddEnv                          = Ajouter une fonctionnalité de routage aux variables système
	AddEnvTips                      = Après l'ajout, entrez Yi dans n'importe quelle session PowerShell pour répondre. Par exemple, entrez "Yi -SIP" pour exécuter l'encapsulation.

	Unzip_ISO                       = Extraire ISO
	Unzip_Search_Type               = Répertoire de recherche ( {0} )
	ISO_Other                       = Autres documents
	Unzip_Language                  = Paquet de langue
	Unzip_Fod                       = Ensemble de fonctionnalités
	FileName                        = Nom du fichier

	UserCancel                      = L'utilisateur a annulé l'opération.
	MatchMode                       = Correspondre
	Failed                          = Échouer
	RandomSelect                    = Sélectionné au hasard
	RulePre                         = Règles prédéfinies
	RuleOther                       = Autres règles
	RuleCustomize                   = Règles personnalisées
	RuleCustomize_Dont              = N'utilisez pas de règles personnalisées d'annuaire à plusieurs niveaux
	RuleCustomize_Dont_Tips         = Après avoir supprimé l'ancien répertoire, cliquez sur "Vérifier les règles de nommage".
	RuleMultistage                  = Règles de répertoire à niveaux multiples
	RuleMultistageFindFailed        = Aucune règle de répertoire multi-niveaux trouvée, cliquez sur moi pour créer un modèle.
	RuleMultistageFindCreateNew     = Créer un nouveau modèle de règle de répertoire à niveaux multiples
	RuleMultistageTips              = Adaptez automatiquement les règles d'annuaire à plusieurs niveaux, la règle d'annuaire {0} a été désactivée.
	RuleCustomizeNot                = Nom de l'extension (Solutions.Custom.Extension) introuvable, veuillez consulter la documentation d'aide.
	RuleCustomizeTips               = Aucune règle personnalisée créée, veuillez consulter la documentation d'aide.
	RuleMatchNoFindFolder           = Échec de la correspondance avec le répertoire, cliquez sur moi pour créer le répertoire.
	RuleNoFindFile                  = Aucun fichier disponible trouvé, veuillez ajouter et actualiser.
	RuleFindFolder                  = Répertoire automatiquement sélectionné lorsqu'il est disponible
	RuleNameNewChange               = Synchroniser automatiquement après les mises à jour
	RuleNewTempate                  = Créer un modèle
	RuleSkipFolderCheck             = Ne vérifie plus si le fichier existe dans le répertoire et le type de fichier
	RuleAuthon                      = Créateur de règles
	RuleGUID                        = GUID, identificateur unique au monde
	RuleName                        = Nom de la règle
	RuleDescription                 = Décrire
	RuleNameUse                     = Synchroniser le nom de la règle avec: {0}
	RuleISO                         = Correspondre au progiciel d'installation ISO d'origine
	RuleInBoxApps                   = Application complète et préconfigurée
	RuleFileType                    = Nom du paquet
	RuleFileFind                    = Nom flou de recherche
	RuleFindError                   = {0} éléments trouvés à traiter, cliquez sur " Vérifier les dépendances " pour voir les détails.
	RuleSelectApps                  = Applications sélectionnées par l'utilisateur
	DependencyPackage               = Paquet de dépendances
	RuleDependenciesRequired        = Dépendances requises
	RuleDependenciesUnselected      = Dépendances non sélectionnées
	RuleDependenciesNoCheck         = Les dépendances ne sont plus vérifiées
	RuleDependenciesFix             = Corriger les dépendances non sélectionnées
	Extract_Tips                    = Indice\n\n   1. Le résultat après l'extraction du paquet de langue ne peut pas être utilisé comme objet de référence principal;\n\n   2. Veuillez utiliser la liste des composants comme objet de référence principal. \n\n       Dans Fonctions, sélectionnez Générer un composant (obtenir le paquet dans l'image installée), sélectionnez Imprimer ou Afficher instantanément;\n\n   3. Après avoir installé le module linguistique, veuillez régénérer un rapport de composant pour vérifier s'il correspond;

	DescendingRuleLang              = Supprimez les modules linguistiques dans l'ordre inverse
	OrderRuleLang                   = Installer les modules linguistiques dans un ordre prédéfini
	OrderRuleLangTips               = Ajouter dans l'ordre: De base, Polices, Reconnaissance optique de caractères, Reconnaissance de l'écriture manuscrite, Synthèse vocale, Reconnaissance vocale, Expérience de démonstration détaillée, Autre
	RuleLanguageTips                = Illustrer:\n\n   Après avoir utilisé "Installer les modules linguistiques dans un ordre prédéfini", les fichiers sont automatiquement appariés par des noms flous dans l'ordre suivant:\n
	Match_installed_List            = Lors de l'installation d'un module linguistique, ajoutez-le à la liste des modules installés.
	Match_installed_List_Tips       = Ne correspond qu'une fois installé: Basic, reconnaissance optique de caractères, reconnaissance de l'écriture manuscrite, synthèse vocale, reconnaissance vocale.
	RuleLanguageTipsExt             = \n   Lorsque vous n'utilisez pas "Installer les modules linguistiques dans un ordre prédéfini":\n   Trouvez automatiquement tous les fichiers du répertoire par type de fichier et installez-les.\n\n   Fonctionnalités linguistiques et régionales sur demande (FOD)\n   https://learn.microsoft.com/fr-ca/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Catégorie
	Basic                           = Basique
	Fonts                           = Fonte
	OCR                             = Reconnaissance optique de caractères
	Handwriting                     = Reconnaissance de l'écriture manuscrite
	TextToSpeech                    = Synthèse vocale
	Speech                          = Reconnaissance vocale
	Retail                          = Expérience de démonstration détaillée
	Features_On_Demand              = Fonctionnalités sur demande
	RegionSpecific                  = Autres exigences propres à la région
	UnassignedLangFiles             = Fichiers divers non attribués

	ProcessingImage                 = Traiter l'image:
	NoInstallImage                  = N'existe pas localement
	ConvertChk                      = Vérifiez le fichier
	WindowsFeature                  = Fonctionnalités Windows
	Enable                          = Activer
	Disable                         = Désactiver
	EnableFeatureTips               = Indice\n\n    1. Afficher NetFx3 et TelnetClient comme éléments de fonction prédéfinis activés;\n\n    2. Après le "montage", d'autres peuvent être activés.
	ViewLanguage                    = Afficher les paramètres de langue de l'image
	ImageLanguage                   = Paramètres de langue des images
	OnlyLangCleanup                 = Nettoyer les composants: étiqueter par langue
	Matched_Component_Names         = Nom du composant correspondant:
	BootProcess                     = Lors du traitement de {0}.wim
	Extract_Rule_Only_And_Full      = Extraire uniquement les langues sélectionnées
	Sync_Language_To                = Synchroniser avec
	BootSyncToISO                   = Synchroniser les modules linguistiques avec le programme d'installation
	BootSyncToISOTips               = Le module linguistique installé de l'image hors ligne est synchronisé avec le programme d'installation ISO.
	Setup_Fix_Missing               = Corriger automatiquement les éléments d'installation manquants
	Setup_Fix_Missing_Tips          = S'il manque arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui dans le programme d'installation, ouvrez " Extraire ", sélectionnez " Règles " et cliquez sur " Extraire les éléments manquants du programme d'installation ".
	Setup_Fix_Missing_Extract       = Extraire les éléments manquants du programme d'installation
	Setup_Fix_Missing_Extract_Tips  = Extrayez les éléments manquants du programme d'installation de tous les progiciels de langue locale: arunres.dll.mui, spwizres.dll.mui, w32uires.dll.mui.
	LangIni                         = Régénérer Lang.ini
	LangIniTips                     = Une fois la synchronisation terminée, Lang.ini dans l'ISO doit être reconstruit.
	LangNewAutoSelect               = Sélectionnez automatiquement les éléments suggérés lorsqu'un événement se produit
	LangNewAutoSelectTips           = Il y a de nouveaux événements, " Synchroniser les modules linguistiques avec le programme d'installation ", " Reconstruire Lang.ini " sélectionné.
	LangNewAutoNoSelect             = Il y a de nouveaux événements, il est recommandé de sélectionner " Synchroniser le module linguistique avec le programme d'installation " et " Reconstruire Lang.ini ".
	LangNewAutoNoNewSelect          = Il n'y a pas de nouveaux événements.
	Drive                           = Conduire
	ViewDrive                       = Afficher les pilotes installés
	EditionsProductKey              = Clé de produit
	Editions                        = Version illustrée
	Assign_Editions                 = Distribuez automatiquement les applications en fonction des versions d'image
	EditionsChangeTips              = Attention, veuillez comprendre avant de changer la version de l'image: \n\nMicrosoft Contrat de service\nhttps://www.microsoft.com/fr-ca/servicesagreement/default.aspx\n\nAperçu de la langue\nhttps://learn.microsoft.com/fr-ca/windows-hardware/manufacture/desktop/languages-overview\n\nVous n'êtes pas autorisé à créer des versions de: \n   1. Spécifique au pays\n       ProfessionalCountrySpecific\n\n   2. Version résidentielle propre à la région\n       ProfessionalSingleLanguage\n\nVeuillez vous y conformer strictement, car vous pourriez faire l'objet de poursuites en cas de violation.\n\nSi vous insistez pour la conversion, cliquez pour accepter l'avertissement et cliquez sur "Déverrouiller la version de l'image cachée".
	EditionsChangeHide              = Déverrouillez les versions d'images cachées
	EditionsChangeAccect            = J'ai lu l'avertissement et je suis responsable des lois pertinentes contenues dans l'avertissement

	SelFile                         = Sélectionner un fichier
	Rebuilding                      = En reconstruction
	RebuildAll                      = Tout rebâtir
	Export_Image                    = Exporter
	SelectFromError                 = Erreur
	SelectFileFormatError           = Le format de fichier est incorrect

	SearchDrive                     = Axé sur la recherche
	SearchUpdate                    = Cherchez des mises à jour, entrez ( {0} ), source:
	SelectFolder                    = Sélectionnez le répertoire
	DropFolder                      = Peut faire glisser des répertoires vers la fenêtre actuelle
	DropFile                        = Les fichiers peuvent être glissés vers la fenêtre actuelle
	Sparse                          = Rare
	CRCSHA                          = Vérifier
	Alternative                     = Nom de fichier alternatif
	ChangeInstallDisk               = Modifier la sélection automatique du disque

	# View
	ExportToLogs                    = Imprimer le rapport pour enregistrer
	ExportShow                      = Afficher les rapports instantanément
	MoreFeature                     = Plus de fonctionnalités
	OpenFolder                      = Ouvrir le répertoire
	OpenFile                        = Ouvrir le fichier
	Running                         = Courir
	Paste                           = Copier le chemin
	Clipboard_Copy                  = Copié dans le presse-papiers
	ViewWIMFileInfo                 = Voir l'image
	GetInBoxApps                    = InBox Apps: packages d'applications installés
	GetImagePackage                 = Composants: tous les progiciels installés dans l'image
	ViewMounted                     = Obtenez des renseignements sur toutes les images montées
'@