ConvertFrom-StringData -StringData @'
	# sl-SI
	# Slovenian (Slovenia)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Nadzorna plošča
	Learn                           = Študija
	Menu                            = Meni
	Short_Cmd                       = Bližnjični ukaz
	Shortcut                        = Bližnjica
	Update                          = Obnoviti
	CUpdate                         = Kumulativne posodobitve
	Rebuild                         = Rekonstrukcija
	AddTo                           = Dodaj v
	Del                             = Izbrisati
	Copy                            = Kopija
	Rename                          = Preimenuj
	Refresh                         = Osveži
	RefreshModules                  = Vroča osvežitev vseh modulov
	Done                            = Končaj
	OK                              = Seveda
	Cancel                          = Prekliči
	AllSel                          = Izberi vse
	AllClear                        = Počisti vse
	Setting                         = Postaviti
	Change                          = Spremeniti
	Help                            = Pomoč
	Logging                         = Dnevnik
	AvailableLanguages              = Razpoložljivi jeziki
	SwitchLanguage                  = Preklopi jezik
	LanguageSelRegion               = Izberite svojo državo ali regijo
	LanguageRemember                = Zapomni si izbrani jezik
	LanguageSearchNo                = Ni razpoložljivih jezikov
	LanguageNoSel                   = Izberite regijo
	Search                          = Iskanje
	SearchAllDrives                 = Iskanje po vseh pogonih
	MountCategory                   = Vse najdene, nameščene datoteke ISO
	PleaseChoose                    = Prosim izberite
	Options                         = Možnosti
	Choose                          = Izbrano
	NoChoose                        = Ni izbrano
	AdvOption                       = Neobvezne funkcije
	ExcludeItem                     = Izključi po pravilu
	DeDuplication                   = Izključi dvojnike
	DeDuplication_Unlock            = Odkleni onemogočene dvojnike
	Existed                         = Že obstaja
	FailedCreateFolder              = Imenika ni bilo mogoče ustvariti
	FailedCreateFile                = Datoteke ni bilo mogoče ustvariti
	ToMsg                           = {0} Samodejna vrnitev v glavni meni po nekaj sekundah.
	OnDemandPlanTask                = Dodeljevanje znanih dogodkov po meri
	Operable                        = Operabilno
	Inoperable                      = Neoperabilen
	Hide                            = Skriti
	CuringUpdate                    = Solidna posodobitev
	CuringUpdateTips                = Ko je posodobitev utrjena, je ni več mogoče odstraniti.
	Healthy                         = Zdravo
	Healthy_Save                    = Ko se pojavi popravljivo ali nepopravljivo, ne shranjujte.
	Repair                          = Popravilo
	IsAuto_Repair                   = Dovoli samodejno popravilo med mirovanjem
	IsAuto_Repair_Tips              = Po vsakem zagonu skripta za pakiranje samodejno preveri, ali obstajajo opravila nameščanja. Če je nameščen, popravilo ne bo izvedeno; če ni nameščeno, se bo zagnalo samodejno popravilo.
	Repairable                      = Popravljivo
	NonRepairable                   = Ni popravljivo
	HealthyForceStop                = Med obdelavo dogodka je prišlo do nepopravljive napake in dogodek je bil prisilno prekinjen.\n\n   Povzroča glavne težave:\n\n      1. Fizična strojna oprema je poškodovana, trdi disk;\n\n      2. Če uporabljate navidezni disk pomnilnika RAMDISK (vključno s hibridnim), preverite fizični pomnilnik;\n\n      3. Preverite originalni SHA256 MVS (MSDN), prosimo, spremenite imenik in poskusite znova.\n\n      4. Drugi v tem primeru niso navedeni.
	Superseded                      = Očistite zamenjano
	SupersededTips                  = Vključuje zastarele posodobitve, komponente itd.
	UnmountFailed                   = Preizkusil sem več metod, vendar se ne da narediti nič. Rad bi te videl naslednjič.
	SaveTo                          = Shrani v
	WorkDone                        = Končano, pritisnite katero koli tipko za vrnitev v glavni vmesnik ...
	UserCanel                       = Uporabnik je preklical zahtevo.
	Uping                           = Ustvarjanje
	Exclude_View                    = Oglejte si pravila za izključitev
	User_Interaction                = Interakcija uporabnika
	Ok_Go_To                        = Na voljo za
	Ok_Go_To_No                     = Ne grem

	Detailed                        = Podrobno
	View                            = Pogled
	Detailed_View                   = Oglejte si podrobnosti izbranega pravila

	AddEnv                          = Sistemskim spremenljivkam dodajte funkcijo usmerjanja
	AddEnvTips                      = Po dodajanju vnesite Yi v katero koli sejo PowerShell, če želite na primer vnesti "Yi -SIP", da zaženete enkapsulacijo.

	Unzip_ISO                       = Izvlecite ISO
	Unzip_Search_Type               = Imenik iskanja ( {0} )
	ISO_Other                       = Drugi dokumenti
	Unzip_Language                  = Jezikovni paket
	Unzip_Fod                       = Paket funkcij
	FileName                        = Ime datoteke

	UserCancel                      = Uporabnik je preklical operacijo.
	MatchMode                       = Tekma
	Failed                          = Spodleteti
	RandomSelect                    = Naključno izbrani
	RulePre                         = Prednastavljena pravila
	RuleOther                       = Druga pravila
	RuleCustomize                   = Pravila po meri
	RuleCustomize_Dont              = Ne uporabljajte pravil po meri za večnivojski imenik
	RuleCustomize_Dont_Tips         = Ko izbrišete stari imenik, kliknite "Preveri pravila poimenovanja".
	RuleMultistage                  = Večnivojska pravila imenika
	RuleMultistageFindFailed        = Ni večnivojskih pravil imenika, kliknite me, da ustvarite predlogo.
	RuleMultistageFindCreateNew     = Ustvarite novo večnivojsko predlogo pravila imenika
	RuleMultistageTips              = Samodejno prilagodi večnivojska pravila imenika, pravilo imenika {0} je onemogočeno.
	RuleCustomizeNot                = Imena razširitve (Solutions.Custom.Extension) ni mogoče najti, glejte dokumentacijo za pomoč.
	RuleCustomizeTips               = Ni ustvarjenega pravila po meri, glejte dokumentacijo pomoči.
	RuleMatchNoFindFolder           = Imenika ni bilo mogoče ujemati, kliknite me, da ustvarite imenik.
	RuleNoFindFile                  = Ni razpoložljivih datotek, dodajte in osvežite.
	RuleFindFolder                  = Imenik je samodejno izbran, ko je na voljo
	RuleNameNewChange               = Samodejna sinhronizacija po posodobitvah
	RuleNewTempate                  = Ustvari predlogo
	RuleSkipFolderCheck             = Ne preverja več, ali datoteka obstaja v imeniku in vrste datoteke
	RuleAuthon                      = Ustvarjalec pravil
	RuleGUID                        = Globalni enolični identifikator GUID
	RuleName                        = Ime pravila
	RuleDescription                 = Opisati
	RuleNameUse                     = Sinhroniziraj ime pravila z: {0}
	RuleISO                         = Ujemanje z izvirnim namestitvenim paketom ISO
	RuleInBoxApps                   = Popolna, vnaprej konfigurirana aplikacija
	RuleFileType                    = Ime paketa
	RuleFileFind                    = Mehko iskalno ime
	RuleFindError                   = Najdenih {0} elementov za obdelavo, kliknite "Preveri odvisnosti" za ogled podrobnosti.
	RuleSelectApps                  = Aplikacije, ki jih izbere uporabnik
	DependencyPackage               = Paket odvisnosti
	RuleDependenciesRequired        = Zahtevane odvisnosti
	RuleDependenciesUnselected      = Neizbrane odvisnosti
	RuleDependenciesNoCheck         = Odvisnosti se ne preverjajo več
	RuleDependenciesFix             = Popravi odvisnosti, ki niso izbrane
	Extract_Tips                    = Namig\n\n   1. Rezultata po ekstrahiranju jezikovnega paketa ni mogoče uporabiti kot glavni referenčni objekt;\n\n   2. Uporabite seznam komponent kot glavni referenčni objekt. Kako ustvariti:\n\n       V Funkcijah izberite Generate Component (pridobite paket v nameščeni sliki), izberite Print ali View Instantly;\n\n   3. Po namestitvi jezikovnega paketa ponovno ustvarite poročilo o komponenti, da preverite, ali ustreza;

	DescendingRuleLang              = Jezikovne pakete odstranite v obratnem vrstnem redu
	OrderRuleLang                   = Namestite jezikovne pakete v vnaprej določenem vrstnem redu
	OrderRuleLangTips               = Dodajte po vrstnem redu: osnovno, pisave, optično prepoznavanje znakov, prepoznavanje rokopisa, pretvorba besedila v govor, prepoznavanje govora, maloprodajna predstavitvena izkušnja, drugo
	RuleLanguageTips                = Ilustrirati:\n\n   Po uporabi "Namesti jezikovne pakete v vnaprej določenem vrstnem redu" se datoteke samodejno ujemajo z nejasnimi imeni v naslednjem vrstnem redu:\n
	Match_installed_List            = Ko nameščate jezikovni paket, ga dodajte nadomestni znak s seznama nameščenih
	Match_installed_List_Tips       = Ujema se samo, ko je nameščeno: osnovno, optično prepoznavanje znakov, prepoznavanje rokopisa, pretvorba besedila v govor, prepoznavanje govora.
	RuleLanguageTipsExt             = \n   Če ne uporabljate "Namesti jezikovne pakete v vnaprej določenem vrstnem redu":\n   Samodejno poiščite vse datoteke v imeniku glede na vrsto datoteke in jih namestite.\n\n   Funkcije jezika in regije na zahtevo (FOD)\n   https://learn.microsoft.com/sl-si/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Kategorija
	Basic                           = Osnovni
	Fonts                           = Pisava
	OCR                             = Optično prepoznavanje znakov
	Handwriting                     = Prepoznavanje rokopisa
	TextToSpeech                    = Besedilo v govor
	Speech                          = Prepoznavanje govora
	Retail                          = Maloprodajna predstavitvena izkušnja
	Features_On_Demand              = Funkcije na zahtevo
	RegionSpecific                  = Druge zahteve, specifične za regijo
	UnassignedLangFiles             = Nedodeljene razne datoteke

	ProcessingImage                 = Obdelaj sliko:
	NoInstallImage                  = Lokalno ne obstaja
	ConvertChk                      = Preverite datoteko
	WindowsFeature                  = Funkcije sistema Windows
	Enable                          = Omogočiti
	Disable                         = Onemogoči
	EnableFeatureTips               = Namigi\n\n    1. NetFx3 in TelnetClient sta prikazana kot prednastavljena omogočena elementa funkcij;\n\n    2. Po "namestitvi" je mogoče omogočiti več.
	ViewLanguage                    = Oglejte si nastavitve jezika slike
	ImageLanguage                   = Nastavitve jezika slike
	OnlyLangCleanup                 = Čiste komponente: oznake po jeziku
	Matched_Component_Names         = Ime ujemajoče se komponente:
	BootProcess                     = Pri obdelavi {0}.wim
	Sync_Language_To                = Sinhroniziraj z
	BootSyncToISO                   = Sinhronizirajte jezikovne pakete z namestitvenim programom
	BootSyncToISOTips               = Nameščen jezikovni paket slike brez povezave je sinhroniziran z namestitvenim programom ISO.
	LangIni                         = Ponovno ustvarite Lang.ini
	LangIniTips                     = Ko je sinhronizacija končana, je treba znova zgraditi Lang.ini v ISO.
	LangNewAutoSelect               = Samodejno izberite predlagane elemente, ko pride do dogodka
	LangNewAutoSelectTips           = Izbrani so novi dogodki, "Sinhroniziraj jezikovni paket z namestitvenim programom", "Obnovi Lang.ini".
	LangNewAutoNoSelect             = Obstajajo novi dogodki, priporočljivo je, da izberete "Sinhroniziraj jezikovni paket z namestitvenim programom" in "Znova zgradi Lang.ini".
	LangNewAutoNoNewSelect          = Ni novih dogodkov. Priporočljivo je, da ne izberete "Sinhroniziraj jezikovni paket z namestitvenim programom" ali "Obnovi Lang.ini".
	Drive                           = Pogon
	ViewDrive                       = Oglejte si nameščene gonilnike
	Editions                        = Slikovna različica
	Assign_Editions                 = Samodejno distribuirajte aplikacije na podlagi slikovnih različic

	SelFile                         = Izberite datoteko
	Rebuilding                      = V rekonstrukciji
	RebuildAll                      = Obnovi vse
	Export_Image                    = Izvozi
	SelectFromError                 = Napaka
	SelectFileFormatError           = Format datoteke ni pravilen

	SearchDrive                     = Usmerjeno v iskanje
	SearchUpdate                    = Iskanje posodobitev, vrsta ( {0} ), vir:
	SelectFolder                    = Izberite imenik
	DropFolder                      = Lahko povleče imenike v trenutno okno
	DropFile                        = Datoteke lahko povlečete v trenutno okno
	Sparse                          = Redko
	CRCSHA                          = Preverite
	Alternative                     = Alternativno ime datoteke
	ChangeInstallDisk               = Spremenite samodejno izbiro diska
	Backup                          = Varnostno kopiranje
	Restore                         = Obnovitev
	Import                          = Uvoz

	# View
	ExportToLogs                    = Natisnite poročilo v dnevnik
	ExportShow                      = Takojšen prikaz poročil
	MoreFeature                     = Več funkcij
	OpenFolder                      = Odpri imenik
	OpenFile                        = Odprta datoteka
	Running                         = Teči
	Paste                           = Kopirajte pot
	Clipboard_Copy                  = Kopirano v odložišče
	ViewWIMFileInfo                 = Ogled slike
	GetInBoxApps                    = InBox Apps: nameščeni paketi aplikacij
	GetImagePackage                 = Komponente: vsi paketi, nameščeni na sliki
	ViewMounted                     = Pridobite informacije o vseh nameščenih slikah
'@