ConvertFrom-StringData -StringData @'
	# hr-HR
	# Croatian (Croatia)

	FontsUI                   = Segoe UI
	Mainname                  = Motor za implementaciju: Yijev paket
	Learn                     = Studija
	MainHisName               = Bonus rješenje
	Location                  = Otvorena lokacija
	About                     = Oko
	Reset                     = Resetirati
	AddTo                     = Dodaj u
	Instl                     = Instalirati
	ItInstalled               = Instalirano
	Close                     = Zatvaranje
	Auto                      = Automatski
	Disable                   = Onemogući
	Enable                    = Omogućiti
	Setting                   = Postaviti
	Restore                   = Oporaviti se
	Clean                     = Pospremiti
	Operable                  = Operabilan
	Inoperable                = Neoperabilan
	Optimize                  = Optimizacija
	Hide                      = Sakriti
	Show                      = Pokazati
	Del                       = Izbrisati
	Done                      = Završiti
	OK                        = Naravno
	Cancel                    = Otkazati
	AllSel                    = Odaberite sve
	AllClear                  = Jasno sve
	Refresh                   = Osvježiti
	RefreshModules            = Vruće osvježite sve module
	Necessary                 = Osnovni softver
	MostUsedSoftware          = Često korišteni softver
	System                    = Sustav
	Service                   = Poslužiti
	TaskBar                   = Sve ikone programske trake
	DeskIcon                  = Ikone na radnoj površini
	InstallFonts              = Instalirajte fontove
	SettingTo                 = Postavljeno na {0}
	Command                   = Naredbeni redak
	RuleName                  = Naziv pravila
	Language                  = Jezik
	AvailableLanguages        = Dostupni jezici
	SwitchLanguage            = Promijeniti jezik
	LanguageReset             = Ponovno postavljanje jezičnih postavki
	LanguageCode              = Oznaka zone
	LanguageSelRegion         = Odaberite svoju zemlju ili regiju
	LanguageRemember          = Zapamti odabrani jezik
	LanguageSearchNo          = Nije pronađen nijedan dostupan jezik
	LanguageNoSel             = Odaberite regiju
	Search                    = Pretraživanje
	PleaseChoose              = Odaberite
	FailedCreateFolder        = Nije uspjelo stvaranje imenika
	Failed                    = Uspjeti
	ToMsg                     = {0} Automatski povratak na glavni izbornik nakon nekoliko sekundi.
	Restart                   = Ponovno pokretanje stupa na snagu
	AdvOption                 = Izborne značajke

	StartDown                 = Započnite preuzimanje
	ConnectTo                 = Poveži se s
	FileName                  = Naziv datoteke
	SaveTo                    = Spremiti u
	NotAvailable              = Status: Nije dostupno
	ExistingPacker            = Već imate instalacijski paket
	ExistingInstlPacker       = Već imate komprimirani paket
	Unpacking                 = Otpakiranje
	QucikRun                  = Brzo trčanje:
	WaitDone                  = Čeka se završetak:
	Parameter                 = Parametar:
	ErrorDown                 = Došlo je do pogreške tijekom preuzimanja
	UserCancel                = Korisnik je otkazao operaciju.

	VerifyNameTips            = Dopuštena je samo kombinacija engleskih slova i brojeva, a drugi znakovi nisu dopušteni: razmaci, duljina ne smije biti veća od 16 znakova, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Prilagođeni prefiks imenika
	NoSetFolderLabel          = Prilagođeni prefiks imenika nije postavljen
	ISO9660TipsErrorSpace     = Ne može sadržavati: razmake na početku i na kraju
	ISO9660TipsErrorOther     = Ne može sadržavati: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Oznaka sveska ne može biti duža od {0} znakova
	Help                      = Pomoć
	WorkDone                  = Završeno, pritisnite bilo koju tipku za povratak na glavno sučelje...
	Short_Cmd                 = Prečaci
	Options                   = Mogućnosti
	LXPsWaitAssign            = Za dodjelu
	Running                   = Trčanje
	SpecialFunction           = PowerShell funkcije
'@