ConvertFrom-StringData -StringData @'
	# fi-fi
	# Finnish (Finland)

	FontsUI                         = Segoe UI

	# Main page
	Dashboard                       = Kojelauta
	Learn                           = Opiskella
	Menu                            = Valikosta
	Short_Cmd                       = Pikanäppäimet
	Shortcut                        = Pikakuvake
	Update                          = Uusia
	CUpdate                         = Kumulatiiviset päivitykset
	Rebuild                         = Jälleenrakennus
	AddTo                           = Lisää
	Del                             = Poistaa
	Copy                            = Kopioida
	Rename                          = Nimeä uudelleen
	Refresh                         = Päivitä
	RefreshModules                  = Päivitä kaikki moduulit kuumana
	Done                            = Valmis
	OK                              = Varma
	Cancel                          = Peruuttaa
	AllSel                          = Valitse kaikki
	AllClear                        = Tyhjentää kaikki
	Setting                         = Perustaa
	Change                          = Muuttaa
	Help                            = Auttaa
	Logging                         = Loki
	AvailableLanguages              = Saatavilla olevat kielet
	SwitchLanguage                  = Vaihtaa kieltä
	LanguageSelRegion               = Valitse maasi tai alueesi
	LanguageRemember                = Muista valittu kieli
	LanguageSearchNo                = Saatavilla olevia kieliä ei löytynyt
	LanguageNoPack                  = Jos paikallista kielipakettia ei ole, se poistuu automaattisesti.
	LanguageNoSel                   = Valitse alue
	Search                          = Haku
	PleaseChoose                    = Ole hyvä ja valitse
	Options                         = Vaihtoehdot
	Choose                          = Valittu
	NoChoose                        = Ei valittu
	AdvOption                       = Valinnaiset ominaisuudet
	ExcludeItem                     = Sulje pois säännöllä
	DeDuplication                   = Sulje pois kaksoiskappaleet
	DeDuplication_Unlock            = Avaa käytöstä poistetut kaksoiskappaleet
	Existed                         = On jo olemassa
	FailedCreateFolder              = Hakemiston luominen epäonnistui
	FailedCreateFile                = Tiedoston luominen epäonnistui
	ToMsg                           = {0} Palaa automaattisesti päävalikkoon sekunnin kuluttua.
	OnDemandPlanTask                = Tunnettujen tapahtumien mukautettu määritys
	Operable                        = Toimiva
	Inoperable                      = Käyttökelvoton
	Hide                            = Piilottaa
	CuringUpdate                    = Varma päivitys
	CuringUpdateTips                = Kun päivitys on vahvistettu, sitä ei voi poistaa.
	Healthy                         = Terveitä
	HealthyTips                     = On erityisen tärkeää tarkistaa kunto Kun näyttöön tulee "korjattavissa" tai "korjaamaton": ESD muunnosprosessin aikana näyttöön tulee virhe 13 ja tiedot ovat virheellisiä järjestelmää asennettaessa.
	Healthy_Save                    = Kun korjattava tai korjaamaton näkyy, älä tallenna.
	Repair                          = Korjaus
	IsAuto_Repair                   = Salli automaattinen korjaus tyhjäkäynnillä
	IsAuto_Repair_Tips              = Tarkista automaattisesti jokaisen pakkauskomentosarjan ajon jälkeen, onko asennustehtäviä. Jos se on asennettu, korjausta ei suoriteta, jos sitä ei ole asennettu, automaattinen korjaus suoritetaan.
	Repairable                      = Korjattavissa
	NonRepairable                   = Ei korjattavissa
	HealthyForceStop                = Tapahtumaa käsiteltäessä havaittiin peruuttamaton virhe ja prosessi keskeytettiin väkisin.\n\n   Aiheuttaa tärkeimpiä ongelmia: \n\n      1. Fyysinen laitteisto on vaurioitunut, kiintolevy;\n\n      2. Jos käytät RAMDISK muistin virtuaalilevyä (mukaan lukien hybridi), tarkista fyysinen muisti;\n\n      3. Tarkista MVS:n (MSDN) alkuperäinen SHA256, jos se on johdonmukainen, vaihda hakemisto ja yritä uudelleen. Jos SHA256 on epäjohdonmukainen, lataa se uudelleen ja yritä uudelleen.\n\n      4. Muita ei ole lueteltu tässä esimerkissä.
	Superseded                      = Puhdista vaihdettu
	SupersededTips                  = Sisältää vanhentuneet päivitykset, komponentit jne.
	UnmountFailed                   = Olen kokeillut useita menetelmiä, mutta mitään ei voi tehdä. Haluaisin nähdä sinut seuraavan kerran.
	SaveTo                          = Tallenna kohteeseen
	WorkDone                        = Valmis, palaa pääliittymään painamalla mitä tahansa näppäintä...
	UserCanel                       = Käyttäjä on peruuttanut pyynnön.
	Uping                           = Luodaan
	Exclude_View                    = Katso poissulkemissäännöt
	User_Interaction                = Käyttäjän vuorovaikutusta
	Ok_Go_To                        = Saatavilla
	Ok_Go_To_No                     = Ei mene

	Detailed                        = Yksityiskohtainen
	Detailed_View                   = Näytä valitun säännön tiedot

	AddEnv                          = Lisää reititystoimintoja järjestelmämuuttujiin
	AddEnvTips                      = Lisäämisen jälkeen kirjoita Yi mihin tahansa PowerShell istuntoon vastataksesi kirjoittamalla esimerkiksi "Yi -SIP" suorittaaksesi kapseloinnin.

	Unzip_ISO                       = Pura ISO
	Unzip_Search_Type               = Hae hakemistosta ( {0} )
	ISO_Other                       = Muut asiakirjat
	Unzip_Language                  = Kielipaketti
	Unzip_Fod                       = Ominaisuuspaketti
	FileName                        = Tiedoston nimi

	UserCancel                      = Käyttäjä on peruuttanut toiminnon.
	MatchMode                       = Ottelu
	Failed                          = Epäonnistua
	RandomSelect                    = Satunnaisesti valittu
	RulePre                         = Esiasetetut säännöt
	RuleOther                       = Muut säännöt
	RuleCustomize                   = Mukautetut säännöt
	RuleCustomize_Dont              = Älä käytä monitasoisen hakemiston mukautettuja sääntöjä
	RuleCustomize_Dont_Tips         = Kun olet poistanut vanhan hakemiston, napsauta "Tarkista nimeämissäännöt".
	RuleMultistage                  = Monitasoiset hakemistosäännöt
	RuleMultistageFindFailed        = Monitasoisia hakemistosääntöjä ei löytynyt. Luo malli napsauttamalla minua.
	RuleMultistageFindCreateNew     = Luo uusi monitasoinen hakemistosääntömalli
	RuleMultistageTips              = Muokkaa monitasoisia hakemistosääntöjä automaattisesti, {0} hakemistosääntö on poistettu käytöstä.
	RuleCustomizeNot                = Laajennuksen nimeä (Solutions.Custom.Extension) ei löydy, katso ohjedokumentaatio.
	RuleCustomizeTips               = Mukautettua sääntöä ei ole luotu, katso ohjedokumentaatio.
	RuleMatchNoFindFolder           = Hakemiston täsmääminen epäonnistui. Luo hakemisto napsauttamalla minua.
	RuleNoFindFile                  = Saatavilla olevia tiedostoja ei löytynyt, lisää ja päivitä.
	RuleFindFolder                  = Hakemisto valitaan automaattisesti, kun se on saatavilla
	RuleNameNewChange               = Synkronoi automaattisesti päivitysten jälkeen
	RuleNewTempate                  = Luo malli
	RuleSkipFolderCheck             = Ei enää tarkista, onko tiedosto hakemistossa ja tiedostotyyppiä
	RuleAuthon                      = Säännön luoja
	RuleGUID                        = Globaalisti yksilöllinen GUID tunniste
	RuleName                        = Säännön nimi
	RuleDescription                 = Kuvata
	RuleNameUse                     = Synkronoi säännön nimi kohteeseen: {0}
	RuleISO                         = Vastaa alkuperäistä ISO asennuspakettia
	RuleInBoxApps                   = Täydellinen, esikonfiguroitu sovellus
	RuleFileType                    = Paketin nimi
	RuleFileFind                    = Sumea hakunimi
	RuleFindError                   = Löytyi {0} käsiteltävää kohdetta. Napsauta "Tarkista riippuvuudet" nähdäksesi tiedot.
	RuleSelectApps                  = Käyttäjän valitsemat sovellukset
	DependencyPackage               = Riippuvuuspaketti
	RuleDependenciesRequired        = Vaaditut riippuvuudet
	RuleDependenciesUnselected      = Valitsemattomat riippuvuudet
	RuleDependenciesNoCheck         = Riippuvuuksia ei enää tarkasteta
	RuleDependenciesFix             = Korjaa riippuvuuksia, joita ei ole valittu
	Extract_Tips                    = Vihje\n\n   1. Kielipaketin purkamisen jälkeistä tulosta ei voi käyttää pääviiteobjektina;\n\n   2. Käytä komponenttiluetteloa pääviiteobjektina Kuinka luodaan:\n\n       Valitse Functions kohdassa Luo komponentti (hae paketti asennetussa kuvassa), valitse Tulosta tai Näytä heti;\n\n   3. Kun olet asentanut kielipaketin, luo komponenttiraportti uudelleen tarkistaaksesi, vastaako se.

	DescendingRuleLang              = Poista kielipaketit käänteisessä järjestyksessä
	OrderRuleLang                   = Asenna kielipaketit ennalta määrätyssä järjestyksessä
	OrderRuleLangTips               = Lisää järjestyksessä: Perus, Fontit, Optinen merkin tunnistus, Käsinkirjoituksen tunnistus, Tekstistä puheeksi, Puheentunnistus, Vähittäiskaupan esittelykokemus, Muut
	RuleLanguageTips                = Havainnollistaa:\n\n   Kun olet valinnut "Asenna kielipaketit ennalta määrätyssä järjestyksessä", tiedostot yhdistetään automaattisesti sumeilla nimillä seuraavassa järjestyksessä:\n
	Match_installed_List            = Kun asennat kielipakettia, kirjoita se jokerimerkillä asennettujen luetteloon
	Match_installed_List_Tips       = Vastaa vain asennettuna: Perus, Optinen merkin tunnistus, Käsinkirjoituksen tunnistus, Tekstistä puheeksi, Puheentunnistus.
	RuleLanguageTipsExt             = \n   Kun et käytä "Asenna kielipaketit ennalta määrätyssä järjestyksessä":\n   Hae automaattisesti kaikista hakemiston tiedostoista tiedostotyypin mukaan ja asenna ne.\n\n   Kieli ja alue on demand ominaisuudet (FOD)\n   https://learn.microsoft.com/fi-fi/windows-hardware/manufacture/desktop/features-on-demand-language-fod
	InCategory                      = Luokka
	Basic                           = Perus
	Fonts                           = Fontti
	OCR                             = Optinen merkin tunnistus
	Handwriting                     = Käsialan tunnistus
	TextToSpeech                    = Tekstistä puheeksi
	Speech                          = Puheentunnistus
	Retail                          = Vähittäiskaupan demokokemus
	Features_On_Demand              = Ominaisuudet pyynnöstä
	RegionSpecific                  = Muut aluekohtaiset vaatimukset
	UnassignedLangFiles             = Määrittämättömät sekalaiset tiedostot

	ProcessingImage                 = Käsittele kuva:
	NoInstallImage                  = Ei ole paikallisesti olemassa
	ConvertChk                      = Tarkista tiedosto
	WindowsFeature                  = Windowsin ominaisuuksia
	Enable                          = Ota käyttöön
	Disable                         = Poista käytöstä
	EnableFeatureTips               = Vihje\n\n    1. Näytä NetFx3 ja TelnetClient esiasetettuina toimintokohdina;\n\n    2. "Asennuksen" jälkeen lisää voidaan ottaa käyttöön.
	ViewLanguage                    = Näytä kuvan kieliasetukset
	ImageLanguage                   = Kuvan kieliasetukset
	OnlyLangCleanup                 = Puhtaat komponentit: tagi kielen mukaan
	Matched_Component_Names         = Vastaava komponentin nimi:
	BootProcess                     = Käsiteltäessä tiedostoa {0}.wim
	Sync_Language_To                = Synkronoi kohteeseen
	BootSyncToISO                   = Synkronoi kielipaketit asennusohjelman kanssa
	BootSyncToISOTips               = Offline kuvan asennettu kielipaketti synkronoidaan ISO asennusohjelmaan.
	LangIni                         = Luo Lang.ini uudelleen
	LangIniTips                     = Kun synkronointi on valmis, ISO:n Lang.ini on rakennettava uudelleen.
	LangNewAutoSelect               = Valitse automaattisesti ehdotetut kohteet tapahtuman sattuessa
	LangNewAutoSelectTips           = Uusia tapahtumia, "Synkronoi kielipaketit asennusohjelmaan", "Rebuild Lang.ini" on valittu.
	LangNewAutoNoSelect             = Uusia tapahtumia on, on suositeltavaa valita "Synkronoi kielipaketti asennusohjelmaan" ja "Rebuild Lang.ini".
	LangNewAutoNoNewSelect          = Uusia tapahtumia ei ole. On suositeltavaa, että et valitse "Synkronoi kielipaketti asennusohjelmaan" ja "Rebuild Lang.ini".
	Drive                           = Ajaa
	ViewDrive                       = Näytä asennetut ohjaimet
	EditionsProductKey              = Tuoteavain
	Editions                        = Kuvan versio
	Assign_Editions                 = Jaa sovelluksia automaattisesti kuvaversioiden perusteella
	EditionsChangeTips              = Varoitus, ymmärrä ennen kuvaversion vaihtamista: \n\nMicrosoft Palvelusopimus\nhttps://www.microsoft.com/fi-fi/servicesagreement/default.aspx\n\nKielten yleiskatsaus\nhttps://learn.microsoft.com/fi-fi/windows-hardware/manufacture/desktop/languages-overview\n\nEt saa tehdä versioita seuraavista: \n   1. Maakohtainen\n       ProfessionalCountrySpecific\n\n   2. Aluekohtainen kotiversio\n       ProfessionalSingleLanguage\n\nNoudata tiukasti, sillä voit joutua syytteeseen, jos sinua rikotaan.\n\nJos vaadit muuntamista, napsauta hyväksyäksesi varoituksen ja napsauta "Avaa piilotetun kuvan versio".
	EditionsChangeHide              = Avaa piilotetut kuvaversiot
	EditionsChangeAccect            = Olen lukenut varoituksen ja olen vastuussa varoituksen sisältämistä asiaankuuluvista laeista

	SelFile                         = Valitse tiedosto
	Rebuilding                      = Rekonstruoinnissa
	RebuildAll                      = Rakenna kaikki uudelleen
	Export_Image                    = Viedä
	SelectFromError                 = Virhe
	SelectFileFormatError           = Tiedostomuoto on väärä

	SearchDrive                     = Haku ajettu
	SearchUpdate                    = Hae päivityksiä, tyyppi ( {0} ), lähde:
	SelectFolder                    = Valitse hakemisto
	DropFolder                      = Voi vetää hakemistoja nykyiseen ikkunaan
	DropFile                        = Tiedostot voidaan vetää nykyiseen ikkunaan
	Sparse                          = Harvinainen
	CRCSHA                          = Tarkista
	Alternative                     = Vaihtoehtoinen tiedostonimi
	ChangeInstallDisk               = Muuta automaattista levyvalintaa

	# View
	ExportToLogs                    = Tulosta raportti lokiin
	ExportShow                      = Näytä raportit välittömästi
	MoreFeature                     = Lisää ominaisuuksia
	OpenFolder                      = Avaa hakemisto
	OpenFile                        = Avaa tiedosto
	Running                         = Juosta
	Paste                           = Kopioi polku
	Clipboard_Copy                  = Kopioitu leikepöydälle
	ViewWIMFileInfo                 = Näytä kuva
	GetInBoxApps                    = InBox Apps: Asennetut sovelluspaketit
	GetImagePackage                 = Komponentit: Kaikki kuvaan asennetut paketit
	ViewMounted                     = Hanki tietoja kaikista asennetuista kuvista
'@