ConvertFrom-StringData -StringData @'
	# it-IT
	# Italian (Italy)

	FontsUI                   = Segoe UI
	Mainname                  = Motore di distribuzione: la suite di Yi
	Learn                     = Studio
	MainHisName               = Soluzione bonus
	Location                  = Posizione aperta
	About                     = Di
	Reset                     = Reset
	AddTo                     = Aggiungere a
	Instl                     = Installare
	ItInstalled               = Installato
	Close                     = Chiusura
	Auto                      = Automatico
	Disable                   = Disabilita
	Enable                    = Abilitare
	Setting                   = Impostare
	Restore                   = Recuperare
	Clean                     = Ripulire
	Operable                  = Operabile
	Inoperable                = Inoperabile
	Optimize                  = Ottimizzazione
	Hide                      = Nascondere
	Show                      = Spettacolo
	Del                       = Eliminare
	Done                      = Fine
	OK                        = Sicuro
	Cancel                    = Cancellare
	AllSel                    = Seleziona tutto
	AllClear                  = Cancella tutto
	Refresh                   = Aggiornare
	RefreshModules            = Aggiornamento a caldo di tutti i moduli
	Necessary                 = Software essenziale
	MostUsedSoftware          = Software comunemente utilizzato
	System                    = Sistema
	Service                   = Servire
	TaskBar                   = Tutte le icone della barra delle applicazioni
	DeskIcon                  = Icone del desktop
	InstallFonts              = Installa i caratteri
	SettingTo                 = Imposta su {0}
	Command                   = Riga di comando
	RuleName                  = Nome della regola
	Language                  = Lingua
	AvailableLanguages        = Lingue disponibili
	SwitchLanguage            = Cambiare lingua
	LanguageReset             = Ripristina le impostazioni della lingua
	LanguageCode              = Contrassegno di zona
	LanguageSelRegion         = Seleziona il tuo paese o regione
	LanguageRemember          = Ricorda la lingua selezionata
	LanguageSearchNo          = Nessuna lingua disponibile trovata
	LanguageNoSel             = Seleziona una regione
	Search                    = Ricerca
	PleaseChoose              = Seleziona
	FailedCreateFolder        = Impossibile creare la directory
	Failed                    = Fallire
	ToMsg                     = {0} Ritorna automaticamente al menu principale dopo secondi.
	Restart                   = Il riavvio ha effetto
	AdvOption                 = Funzionalità opzionali

	StartDown                 = Inizia a scaricare
	ConnectTo                 = Connettiti a
	FileName                  = Nome del file
	SaveTo                    = Salva in
	NotAvailable              = Stato: non disponibile
	ExistingPacker            = Hai già il pacchetto di installazione
	ExistingInstlPacker       = Hai già un pacchetto compresso
	Unpacking                 = Decompressione
	QucikRun                  = Corsa veloce:
	WaitDone                  = In attesa del completamento:
	Parameter                 = Parametro:
	ErrorDown                 = Si è verificato un errore durante il download
	UserCancel                = L'utente ha annullato l'operazione.

	VerifyNameTips            = È consentita solo una combinazione di lettere e numeri inglesi e non sono consentiti altri caratteri: spazi, la lunghezza non può essere superiore a 16 caratteri, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Prefisso di directory personalizzato
	NoSetFolderLabel          = Prefisso della directory personalizzata non impostato
	ISO9660TipsErrorSpace     = Non può contenere: spazi iniziali e finali
	ISO9660TipsErrorOther     = Non può contenere: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = L'etichetta del volume non può contenere più di {0} caratteri
	Help                      = Aiuto
	WorkDone                  = Completato, premere un tasto qualsiasi per tornare all'interfaccia principale...
	Short_Cmd                 = Scorciatoie
	Options                   = Opzioni
	LXPsWaitAssign            = Da destinare
	Running                   = Correre
	SpecialFunction           = Funzioni di PowerShell
'@