ConvertFrom-StringData -StringData @'
	# he-IL
	# Hebrew (Israel)

	UnpackISO                       = צור ISO
	ISOLabel                        = תווית עוצמת הקול הוגדרה:
	ISOCustomize                    = שם תווית נפח ISO
	ISO9660                         = אמת את כללי השמות
	ISO9660Tips                     = השם הייחודי אינו יכול לעלות על 260 תווים, שם אמצעי האחסון ISO אינו יכול לעלות על 16 תווים, ואינו יכול להכיל: רווחים מובילים ואחרים, \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = שם ייחודי מותאם אישית
	ISOAddFlagsLang                 = הוסף סימון רב לשוני
	ISOAddFlagsLangGet              = קבל שפות התקנה ידועות
	ISOAddFlagsVer                  = הוסף תג ריבוי גרסאות
	ISOAddFlagsVerGet               = קבל גרסת תמונה ידועה
	ISOAddEICFG                     = הוסף סוג גרסה
	ISOAddEICFGTips                 = כאשר מסתמכים על EI.cfg, זוהי גרסה מסחרית.
	ISO9660TipsErrorSpace           = לא יכול להכיל: חללים מובילים ונגררים
	ISO9660TipsErrorOther           = לא יכול להכיל: \\ / : * ? & @ ! "" < > |
	SelOSver                        = בחר סוג שפה
	SelLabel                        = שם קוד
	ISOVerLabel                     = בחר שם אמצעי אחסון ISO
	NoSetLabel                      = תווית עוצמת הקול ISO מותאמת אישית לא מוגדרת
	ISOLengthError                  = תווית נפח לא יכולה להיות ארוכה מ-{0} תווים
	RenameFailed                    = זהה לספרייה הישנה, שינוי השם נכשל
	ISOCreateAfter                  = מה אתה צריך לעשות לפני יצירת ISO
	ISOCreateRear                   = מה אתה צריך לעשות לאחר יצירת ה-ISO
	BypassTPM                       = עוקף את בדיקת התקנת TPM
	Disable_BitLocker               = השבת את הצפנת מכשיר BitLocker במהלך ההתקנה
	PublicDate                      = תאריך הנפקה
	PublicDateGetCurrent            = סנכרן את התאריך הנוכחי
	PublicYear                      = שָׁנָה
	PublicMonth                     = יָרֵחַ
	PublicYMSorting                 = מיין על ידי שינוי "חודש-שנה" ל"שנה-חודש".
	PublicYMSortingTips             = AB: אין להוסיף את הקו התחתון _ בעת שימוש במספרים.
	PublicYMUseShortNames           = השתמש בשמות קצרים
	PublicYMUseNumbers              = השתמש במספרים
	ISOCreateFailed                 = היצירה נכשלה, הספרייה אינה ניתנת לקריאה או כתיבה.
	ISORefreshAuto                  = רענן תגי ISO בכל פעם
	ISOSaveTo                       = ברירת המחדל של מיקום השמירה של ISO
	ISOSaveSameGlobal               = השתמש במיקום ברירת המחדל של ISO גלובלי לשמירה
	ISOSaveSync                     = סנכרן אוטומטית את המיקום החדש לאחר בחירת דיסק חיפוש מקור התמונה
	ISOSaveSame                     = חפש נתיב דיסק באמצעות מקור תמונה
	ISOFolderWrite                  = ודא שהספרייה ניתנת לקריאה ולכתיבה
	SelectAutoAvailable             = בעת בחירה אוטומטית של דיסק זמין
	SelectCheckAvailable            = בדוק את השטח המינימלי הנותר
	ISOStructure                    = מבנה ספריות חדש
	ISOOSLevel                      = הוסף סוג התקנה
	ISOUniqueNameDirectory          = הוסף ספריית שמות ייחודית
	NextDoOperate                   = אל תיצור ISO
	SelCreateISO                    = צור ISO, בצע לפי דרישה
	Reconstruction                  = בנה מחדש את {0}.wim עם דחיסה מקסימלית
	Reconstruction_Tips_Select      = לפני הבנייה מחדש, זה יבוצע רק כאשר הוא לא נטען זה יאלץ את השמירה להיות מופעלת ולאחר מכן יבטל את הטעינה של הקובץ הרכוב.
	ReconstructionTips              = מעל 520 MB, מומלץ לבנות מחדש
	CreateASC                       = הוסף חתימת PGP ל-ISO
	NoPGPKey                        = אין מפתח פרטי שמיש ב PGP.
	CreateASCPwd                    = סיסמת אישור
	PasswordRenter                  = הזן מחדש את הסיסמה
	ShowPassword                    = הצג סיסמה
	NewPasswordSome                 = הסיסמה אינה תואמת.
	PwdPermanent                    = אחסון קבוע
	PwdDecfailed                    = הפענוח נכשל
	CreateASCAuthor                 = חוֹתֵם
	CreateASCAuthorTips             = לא נבחרו חותמים.
	ISO_Sparse_Rename               = הוסף גיבוב לסיומת שם הקובץ
	GenerateRandom                  = צור מספרים אקראיים
	RandomNumberReset               = לְהִתְחַדֵשׁ
'@