ConvertFrom-StringData -StringData @'
	# sk-SK
	# Slovak (Slovakia)

	Main_quests                     = Hlavné úlohy
	Side_quests                     = Podúlohy
	SaveModeClear                   = Vymazať vybranú históriu
	SaveModeTipsClear               = História bola uložená a možno ju vymazať
	SelectTips                      = Tipy\n\n    1. Vyberte názov obrázka, ktorý je potrebné spracovať;\n    2. Po zrušení sa úlohy, ktoré vyžadujú "pripojenie", prestanú uplatňovať.
	CacheDisk                       = Disková vyrovnávacia pamäť
	CacheDiskCustomize              = Vlastná cesta vyrovnávacej pamäte
	AutoSelectRAMDISK               = Povoliť automatický výber menovky disku
	AutoSelectRAMDISKFailed         = Menovka zväzku sa nezhoduje
	ReFS_Find_Volume                = Keď narazíte na formát disku REFS, vylúčte
	ReFS_Exclude                    = Oblasť ReFS je vylúčená
	Disk_Not_satisfied_Exclude      = Minimálne požiadavky na disk neboli splnené
	RAMDISK_Change                  = Zmeňte názov štítka zväzku
	RAMDISK_Search                  = Vyhľadať názov zväzku
	RAMDISK_Restore                 = Obnoviť inicializovaný názov zväzku: {0}
	AllowTopMost                    = Povoliť pripnutie otvorených okien navrchu
	History                         = Vymazať históriu
	History_Del_Tips                = Ak existuje úloha zapuzdrenia, nevykonávajte nasledujúce voliteľné voľby, inak to spôsobí neznáme problémy počas spúšťania skriptu zapuzdrenia.
	History_View                    = Zobraziť históriu
	HistoryLog                      = Povoliť automatické čistenie protokolov starších ako 7 dní
	HistorySaveFolder               = Ďalšie cesty zdroja obrazu
	HistoryClearappxStage           = InBox Apps: Odstráňte dočasné súbory vygenerované počas inštalácie
	DoNotCheckBoot                  = Keď veľkosť súboru Boot.wim presiahne 520 MB, pri generovaní ISO sa automaticky vyberie opätovné zostavenie.
	HistoryClearDismSave            = Odstráňte záznamy pripojenia DISM uložené v registri
	ImageSourcesClickShowKey        = Povoliť zobrazenie ponuky "Vybrať primárny kľúč"
	ImageSourcesClickShowKeyTips    = Po výbere zdroja obrázka používateľom: Pridajte ponuku "Vybrať primárny kľúč" vpravo a pridajte možnosti "Prejsť na": Pripojiť, Uložiť, Vyskakovacie okno.
	Clear_Bad_Mount                 = Odstráňte všetky prostriedky spojené s poškodeným pripojeným obrazom
	ShowCommand                     = Ukážte úplné spustenie príkazového riadku
	Command                         = Príkazový riadok
	SelectSettingImage              = Zdroj obrazu
	NoSelectImageSource             = Nie je vybratý žiadny zdroj obrázka
	SettingImageRestore             = Obnovte predvolené umiestnenie pripojenia
	SettingImage                    = Zmeňte umiestnenie zdroja obrazu
	SelectImageMountStatus          = Po výbere zdroja obrazu získate stav pripojenia
	SettingImageTempFolder          = Dočasný adresár
	SettingImageToTemp              = Dočasný adresár je rovnaký ako umiestnenie, do ktorého bol pripojený
	SettingImagePathTemp            = Pomocou adresára Temp
	SettingImageLow                 = Skontrolujte minimálny zostávajúci priestor
	SettingImageNewPath             = Vyberte možnosť pripojenia disku
	SettingImageNewPathTips         = Odporúča sa pripojiť ho na pamäťový disk, ktorý je najrýchlejší. Môžete použiť softvér pre virtuálnu pamäť, ako je Ultra RAMDisk a ImDisk.
	SelectImageSource               = "Deploy Engine Solution" bolo vybraté, kliknite na tlačidlo OK.
	NoImagePreSource                = Nenašiel sa žiadny dostupný zdroj, mali by ste: \n\n     1. Pridajte ďalšie zdroje obrázkov do: \n          {0}\n\n     2. Vyberte "Nastavenia" a znova vyberte disk na vyhľadávanie zdroja obrázkov;\n\n     3. Vyberte "ISO" a vyberte ISO, ktoré sa má dekomprimovať, položky, ktoré sa majú pripojiť atď.
	NoImageOtherSource              = Kliknutím na mňa "Pridať" ďalšie cesty alebo "Pretiahnuť adresár" do aktuálneho okna.
	SearchImageSource               = Disk na vyhľadávanie zdroja obrázkov
	Kernel                          = Kernel
	Architecture                    = Architektúra
	ArchitecturePack                = Architektúra balíkov, pochopenie pravidiel pridávania
	ImageLevel                      = Typ inštalácie
	LevelDesktop                    = Pracovnej plochy
	LevelServer                     = Server
	ImageCodename                   = Kódové meno
	ImageCodenameNo                 = Nerozpoznané
	MainImageFolder                 = Domovský adresár
	MountImageTo                    = Namontovať na
	Image_Path                      = Obrazová cesta
	MountedIndex                    = Index
	MountedIndexSelect              = Vyberte indexové číslo
	AutoSelectIndexFailed           = Automatický výber indexu {0} zlyhal, skúste to znova.
	Apply                           = Aplikácie
	Eject                           = Vyskočiť
	Mount                           = Namontovať
	ReMount                         = Znovu pripojiť
	Unmount                         = Odinštalovať
	Mounted                         = Namontované
	NotMounted                      = Nie je namontované
	NotMountedSpecify               = Nie je namontované, môžete určiť miesto montáže
	MountedIndexError               = Abnormálna montáž, odstráňte ju a skúste to znova.
	NeedsRemount                    = Vyžaduje sa opätovná montáž
	Invalid                         = Neplatný
	ImageSouresNoSelect             = Zobrazte ďalšie podrobnosti po výbere zdroja obrazu
	Mounted_Mode                    = Režim montáže
	Mounted_Status                  = Stav pripojenia
	Status                          = Stav
	Image_Popup_Default             = Uložiť ako predvolené
	Image_Restore_Default           = Obnoviť predvolené nastavenie
	Image_Popup_Tips                = Nápoveda:\n\nKeď ste priradili udalosť, nezadali ste indexové číslo na spracovanie {0};\n\nRozhranie výberu sa práve objavilo. Po dokončení špecifikácie sa odporúča vybrať možnosť "Uložiť ako predvolené".
	Rule_Show_Full                  = Zobraziť všetky
	Rule_Show_Only                  = Ukázať iba pravidlá
	Rule_Show_Only_Select           = Vyberte si z pravidiel
	Image_Unmount_After             = Odinštalujte všetky namontované

	Wim_Rule_Update                 = Extrahujte a aktualizujte súbory v rámci obrázka
	Wim_Rule_Extract                = Extrahujte súbory
	Wim_Rule_Extract_Tips           = Po výbere pravidla cesty rozbaľte zadaný súbor a uložte ho lokálne.

	Wim_Rule_Verify                 = Overiť
	Wim_Rule_Check                  = Skúmať
	Wim_Rule_CheckIntegrity         = Skontrolovať integritu
	Wim_Rule_ReadOnly               = Povolenie iba na čítanie
	Wim_Rule_Optimize               = Optimalizácia
	ResetBase                       = ניקוי עמוק
	Wim_Rule_SupportEa              = Použiť obrázky s rozšírenými atribútmi
	Wim_Rule_WIMBoot                = Bootovacie
	Wim_Rule_Compact                = Komprimovať súbory operačného systému
	Win_Rule_Setbootable            = Označiť obraz zväzku ako bootovací
	Win_Rule_Setbootable_Tips       = Tento parameter sa vzťahuje iba na obrazy Windows PE.\nV súbore .wim je možné označiť ako bootovací iba jeden obraz zväzku.
	Destination                     = Cieľ

	Wim_Append                      = Pripojiť
	Wim_Capture                     = Zachytiť
	Wim_Capture_Tips                = Zachytiť obraz disku do nového súboru WIM.
	Wim_Capture_Sources             = Zdroj zachytenia
	Wim_Capture_Sources_Tips        = Zachytený adresár obsahuje všetky podpriečinky a údaje.\nNemôžete zachytiť prázdny adresár. Adresár musí obsahovať aspoň jeden súbor.
	Wim_Config_File                 = Cesta ku konfiguračnému súboru ( Výnimky )
	Wim_Config_Edit                 = Upraviť
	Wim_Config_Learn                = Preštudujte si zoznam konfigurácií a súbor WimScript.ini

	Wim_Rename                      = Upravte informácie o obrázku
	Wim_Image_Name                  = Názov obrázku
	Wim_Image_Description           = Popis obrázku
	Wim_Display_Name                = Zobrazovaný názov
	Wim_Display_Description         = Zobraziť popis
	Wim_Edition                     = Obrazová značka
	Wim_Edition_Select_Know         = Vyberte známe príznaky obrázka
	Wim_CreatedTime                 = Dátum vytvorenia
	Wim_ModifiedTime                = Čas poslednej úpravy
	Wim_FileCount                   = Počet súborov
	Wim_DirectoryCount              = Počet adresárov
	Wim_Expander_Space              = Priestor rozšírenia

	IABSelectNo                     = Nie je vybratý žiadny primárny kľúč: Install, WinRE, Boot
	Unique_Name                     = Jedinečné pomenovanie
	Select_Path                     = Cesta
	Setting_Pri_Key                 = Nastavte tento aktualizačný súbor ako hlavnú šablónu
	Pri_Key_Update_To               = Potom aktualizujte na
	Pri_Key_Template                = Nastavte tento súbor ako preferovanú šablónu na synchronizáciu s vybratými položkami
	Pri_key_Running                 = Úloha primárneho kľúča bola synchronizovaná a bola preskočená.
	ShowAllExclude                  = Zobraziť všetky vylúčenia s ukončenou podporou

	Index_Process_All               = Spracujte všetky známe indexové čísla
	Index_Is_Event_Select           = Keď dôjde k udalosti, zobrazí sa rozhranie výberu indexového čísla.
	Index_Pre_Select                = Vopred pridelené indexové číslo
	Index_Select_Tips               = Nápoveda: \n\n{0}.wim momentálne nie je pripojený, môžete:\n\n   1. Zvoľte "Spracovať všetky známe indexové čísla";\n\n   2. Zvoľte "Keď dôjde k udalosti, zobrazí sa rozhranie na výber indexového čísla";\n\n   3. Vopred špecifikované indexové číslo\n      Je zadané indexové číslo 6, indexové číslo počas spracovania neexistuje a spracovanie sa preskočí.

	Index_Tips_Custom_Expand        = Skupina: {0}\n\nPri spracovaní {1} je potrebné priradiť indexové číslo {2}, inak ho nemožno spracovať.\n\nPo výbere možnosti "Synchronizovať pravidlá aktualizácie na všetky čísla indexu" stačí ako hlavnú šablónu zaškrtnúť ľubovoľné.

	DefenderExclude                 = Vylúčenia antivírusu systému Windows
	DefenderFolder                  = Pridať tento adresár do vylúčení antivírusu systému Windows.
	DefenderVolume                  = Po nájdení zodpovedajúceho názvu zväzku pridať tento disk do vylúčení antivírusu systému Windows.
	DefenderIsAdd                   = Pridané do vylúčení antivírusu systému Windows
'@