ConvertFrom-StringData -StringData @'
	# fi-fi
	# Finnish (Finland)

	IsCreate                        = Luoda
	Solution                        = Ratkaisu
	EnabledSoftwarePacker           = Kokoelma
	EnabledUnattend                 = Pitäisi vastata etukäteen
	EnabledEnglish                  = Käyttöönottomoottori
	UnattendSelectVer               = Valitse vastauskieli
	UnattendLangPack                = Valitse "Ratkaisu"-kielipaketti
	UnattendSelectSingleInstl       = Monikielinen, valinnainen asennuksen aikana
	UnattendSelectMulti             = Monikielinen
	UnattendSelectDisk              = Valitse Autounattend.xml-ratkaisu
	UnattendSelectSemi              = Puoliautomaatti on voimassa kaikissa asennustavoissa
	UnattendSelectUefi              = UEFI asentuu automaattisesti ja se on määritettävä
	UnattendSelectLegacy            = Legacy asennetaan automaattisesti ja se on määritettävä
	NeedSpecified                   = Valitse määritettävät tiedot:
	OOBESetupOS                     = Asennusliittymä
	OOBEProductKey                  = Tuoteavain
	OOBEOSImage                     = Valitse asennettava käyttöjärjestelmä
	OOBEEula                        = Hyväksy lisenssiehdot
	OOBEDoNotServerManager          = Server Manager ei käynnisty automaattisesti sisäänkirjautumisen yhteydessä
	OOBEIE                          = Internet Explorerin Enhanced Security Configuration
	OOBEIEAdmin                     = Sulje "Järjestelmänvalvoja"
	OObeIEUser                      = Sulje "Käyttäjät"

	OOBE_Init_User                  = Ensimmäinen käyttäjä pakkauksen purkamisen aikana
	OOBE_init_Create                = Luo mukautettuja käyttäjiä
	OOBE_init_Specified             = Määritä käyttäjä
	OOBE_Init_Autologin             = Automaattinen sisäänkirjautuminen

	InstlMode                       = Asennusmenetelmä
	Business                        = Business versio
	BusinessTips                    = EI.cfg:stä riippuen indeksinumero on määritettävä automaattista asennusta varten.
	Consumer                        = Kuluttajaversio
	ConsumerTips                    = Se ei ole riippuvainen EI.cfg:stä. Automaattista asennusta varten on määritettävä indeksinumero.
	CreateUnattendISO               = [ISO]:\\Autounattend.xml
	CreateUnattendISOSources        = [ISO]:\\sources\\Unattend.xml
	CreateUnattendISOSourcesOEM     = [ISO]:\\sources\\$OEM$\\$$\\Panther\\unattend.xml
	CreateUnattendPanther           = [kiinnittää]:\\Windows\\Panther\\unattend.xml

	VerifyName                      = Lisää järjestelmälevyyn kotihakemiston nimi 
	VerifyNameUse                   = Varmista, että hakemiston nimi ei voi sisältää 
	VerifyNameTips                  = Vain englanninkielisten kirjainten ja numeroiden yhdistelmä on sallittu, eikä se saa sisältää välilyöntejä, pituus ei saa olla yli 260 merkkiä, \\ / : * ? & @ ! "" < > |
	VerifyNumberFailed              = Vahvistus epäonnistui, anna oikea numero.
	VerifyNameSync                  = Aseta hakemiston nimi ensisijaiseksi käyttäjänimeksi
	VerifyNameSyncTips              = Järjestelmänvalvoja ei ole enää käytössä.
	ManualKey                       = Valitse tai syötä tuoteavain manuaalisesti
	ManualKeyTips                   = Anna kelvollinen tuoteavain, jos valittu alue ei ole käytettävissä, tarkista asia Microsoftin viralliselta verkkosivustolta.
	ManualKeyError                  = Antamasi tuoteavain on virheellinen.
	KMSLink1                        = KMS-asiakkaan asetusavain
	KMSUnlock                       = Näytä kaikki tunnetut KMS-sarjanumerot
	KMSSelect                       = Valitse VOL-sarjanumero
	KMSKey                          = Sarjanumero
	KMSKeySelect                    = Vaihda tuotteen sarjanumero
	ClearOld                        = Siivoa vanhat tiedostot
	SolutionsSkip                   = Ohita ratkaisun luominen
	SolutionsTo                     = Lisää "ratkaisu" kohtaan:
	SolutionsToMount                = Asennettu tai lisätty jonoon
	SolutionsToError                = Jotkin toiminnot on poistettu käytöstä. Jos haluat pakottaa ne käyttämään, napsauta "Avaa" -painiketta.\n\n
	UnlockBoot                      = Avata
	SolutionsToSources              = Kotihakemisto, [ISO]:\\Sources\\$OEM$
	SolutionsScript                 = Valitse 'Deployment Engine' -versio
	SolutionsEngineRegionaUTF8      = Beta: Maailmanlaajuinen kielituki Unicode UTF-8:lla
	SolutionsEngineRegionaUTF8Tips  = Näyttää siltä, että se voi aiheuttaa uusia ongelmia avaamisen jälkeen. Ei suositella.
	SolutionsEngineRegionaling      = Vaihda uuteen paikkaan:
	SolutionsEngineRegionalingTips  = Muuta järjestelmän maa-asetusta, joka vaikuttaa kaikkiin tietokoneen käyttäjätileihin.
	SolutionsEngineRegional         = Muuta järjestelmän aluetta
	SolutionsEngineRegionalTips     = Yleinen oletus: {0}, muutettu muotoon: {1}
	SolutionsEngineCopyPublic       = Kopioi julkinen {0} käyttöönottoon
	SolutionsEngineCopyOpen         = Selaa julkisen arkiston {0} sijaintia
	EnglineDoneReboot               = Käynnistä tietokone uudelleen
	SolutionsTipsArm64              = Arm64-paketti on parempi, ja valitset järjestyksessä: x64, x86.
	SolutionsTipsAMD64              = Suosi x64-paketteja, järjestyksessä: x86.
	SolutionsTipsX86                = Vain x86-paketit lisätään.
	SolutionsReport                 = Luo käyttöönottoa edeltävä raportti
	SolutionsDeployOfficeInstall    = Ota käyttöön Microsoft Office -asennuspaketti
	SolutionsDeployOfficeChange     = Muuta käyttöönottoasetuksia
	SolutionsDeployOfficePre        = Esiasennettu pakettiversio
	SolutionsDeployOfficeNoSelect   = Office-esiasennuspakettia ei ole valittu
	SolutionsDeployOfficeVersion    = {0} versio
	SolutionsDeployOfficeOnly       = Säilytä määritetyt kielipaketit
	SolutionsDeployOfficeSync       = Säilytä kielen synkronointi käyttöönottokokoonpanoon
	SolutionsDeployOfficeSyncTips   = Synkronoinnin jälkeen asennusskripti ei voi määrittää ensisijaista kieltä.
	DeploySyncMainLanguage          = Synkronoi pääkielen kanssa
	SolutionsDeployOfficeTo         = Ota asennuspaketti käyttöön osoitteeseen
	SolutionsDeployOfficeToPublic   = Julkinen työpöytä
	DeployPackage                   = Ota mukautettu keräyspaketti käyttöön
	DeployPackageSelect             = Valitse esinottopaketti
	DeployPackageTo                 = Ota esikeräyspaketti käyttöön osoitteeseen
	DeployToRoot                    = Järjestelmälevy
	DeployPackageToSolutions        = Ratkaisun kotihakemistossa
	DeployTimeZone                  = Aikavyöhyke
	DeployTimeZoneChange            = Vaihda aikavyöhykettä
	DeployTimeZoneChangeTips        = Aseta oletusaika-alue, jossa esivastauksiin tulee vastata, kielialueen mukaan.

	Deploy_Tags                     = Käyttöönottotunniste
	FirstExpProcess                 = Ensimmäinen kokemus käyttöönoton aikana:
	FirstExpProcessTips             = Kun olet suorittanut edellytykset, käynnistä tietokone uudelleen ratkaistaksesi uudelleenkäynnistystä koskevan ongelman.
	FirstExpFinish                  = Ensimmäistä kertaa kokemus, esitiedot suoritettuaan
	FirstExpSyncMark                = Salli yleinen haku ja käyttöönottotunnisteiden synkronointi
	FirstExpDefender                = Lisää kotihakemisto Puolusta poissuljettuja hakemistoja
	FirstExpSyncLabel               = Järjestelmälevytaltion nimi: Kotihakemiston nimi on sama
	MultipleLanguages               = Kun kohtaat useita kieliä:
	NetworkLocationWizard           = Ohjattu verkkopaikannustoiminto
	PreAppxCleanup                  = Estä Appx-puhdistuksen ylläpitotehtävät
	LanguageComponents              = Estä käyttämättömien on-demand-ominaisuuskielipakettien puhdistaminen
	PreventCleaningUnusedLP         = Estä käyttämättömien kielipakettien puhdistaminen
	FirstExpContextCustomize        = Lisää henkilökohtainen "kontekstivalikko"
	FirstExpContextCustomizeShift   = Pidä Shift-näppäintä painettuna ja napsauta hiiren kakkospainikkeella

	FirstExpFinishTips              = Käyttöönoton jälkeen ei tapahdu tärkeitä tapahtumia. On suositeltavaa peruuttaa.
	FirstExpFinishPopup             = Avaa käyttöönottomoottorin pääliittymä
	FirstExpFinishOnDemand          = Salli ensimmäinen esikatselu suunnitellusti
	SolutionsEngineRestricted       = Palauta Powershell-suorituskäytäntö: rajoitettu
	EnglineDoneClearFull            = Poista koko ratkaisu
	EnglineDoneClear                = Poista käyttöönottomoottori ja säilytä muut

	Unattend_Auto_Fix_Next          = Kun seuraavan kerran kohtaat sen, valitse automaattisesti tarvittavat kohteet korjataksesi sen automaattisesti.
	Unattend_Auto_Fix               = Korjaa automaattisesti, kun edellytyksiä ei ole valittu
	Unattend_Auto_Fix_Tips          = Kun asennusmoottori lisätään eikä ensimmäistä ajokomentoa valitaan, se korjataan ja valitaan automaattisesti: Powershell-suorituskäytäntö: suorita käyttöönottomoottori ilman rajoituksia.
	Unattend_Version_Tips           = Vaihtoehtoisesti vain, käytä oletusarvoa ARM64-, x64-, x86-tukea varten.
	First_Run_Commmand              = Komennot käynnistymään, kun otetaan käyttöön ensimmäistä kertaa
	First_Run_Commmand_Setting      = Valitse suoritettava komento
	Command_Not_Class               = Ei enää automaattista luokittelua suodatettaessa
	Command_WinSetup                = Windowsin asennus
	Command_WinPE                   = Windows PE
	Command_Tips                    = Määritä First Run App: Windows Installation, Windows PE\n\nHuomaa, että kun käyttöönottomoottori lisätään, sinun on tarkistettava seuraavat seikat, kun suoritat sen ensimmäistä kertaa: Powershell-suorituskäytäntö: Rajoitettu, salli käyttöönottomoottorin komentosarjojen suorittaminen.
	Waring_Not_Select_Command       = Käyttöönottomoottoria lisättäessä Powershell-suorituskäytäntöä ei valittu: Älä aseta rajoituksia ja anna käyttöönottomoottorin komentosarjan suorittaa. Valitse se ja yritä uudelleen tai napsauta "Pikakorjausta ei ole valittu".
	Quic_Fix_Not_Select_Command     = Pikakorjaus ei vaihtoehto

	PowerShell_Unrestricted         = Powershell-suorituskäytäntö: ei rajoituksia
	Allow_Running_Deploy_Engine     = Salli käyttöönottomoottorin komentosarjojen suorittaminen
'@