ConvertFrom-StringData -StringData @'
	# fi-fi
	# Finnish (Finland)

	Main_quests                     = Päätehtävät
	Side_quests                     = Alitehtävät
	SaveModeClear                   = Tyhjennä valittu historia
	SaveModeTipsClear               = Historia on tallennettu ja voidaan tyhjentää
	SelectTips                      = Vihje\n\n    1. Valitse käsiteltävän kuvan nimi;\n    2. Peruuttamisen jälkeen tehtävät, jotka vaativat "asennusta" ennen käyttöä, eivät enää ole voimassa.
	CacheDisk                       = Levyn välimuisti
	CacheDiskCustomize              = Mukautettu välimuistipolku
	AutoSelectRAMDISK               = Salli automaattinen levytaltion otsikon valinta
	AutoSelectRAMDISKFailed         = Volyymi ei täsmää
	ReFS_Find_Volume                = Kun levymuoto REFS havaitaan, sulje pois
	ReFS_Exclude                    = ReFS osio poissuljettu
	Disk_Not_satisfied_Exclude      = Levyn vähimmäisvaatimuksia ei täytetty
	RAMDISK_Change                  = Muuta taltiotunnisteen nimi
	RAMDISK_Search                  = Hae aseman nimi
	RAMDISK_Restore                 = Palauta alustetun taltion nimi: {0}
	AllowTopMost                    = Salli avoimien ikkunoiden kiinnittäminen yläosaan
	History                         = Selkeä historia
	History_Del_Tips                = Kun käytössä on kapselointitehtävä, älä suorita seuraavia valinnaisia asetuksia, muuten se aiheuttaa tuntemattomia ongelmia kapselointikomentosarjan suorittamisen aikana.
	History_View                    = Näytä historia
	HistoryLog                      = Salli yli 7 päivää vanhojen tukien automaattinen puhdistus
	HistorySaveFolder               = Muut kuvan lähdepolut
	HistoryClearappxStage           = InBox Apps: Poista asennuksen aikana luodut väliaikaiset tiedostot
	DoNotCheckBoot                  = Kun Boot.wim tiedoston koko ylittää 520 Mt, uudelleenrakennus valitaan automaattisesti luotaessa ISO.
	HistoryClearDismSave            = Poista rekisteriin tallennetut DISM liitostietueet
	ImageSourcesClickShowKey        = Salli "Valitse ensisijainen avain" -valikon näyttäminen
	ImageSourcesClickShowKeyTips    = Kun käyttäjä on valinnut kuvalähteen: Lisää "Valitse ensisijainen avain" -valikko oikealle ja lisää "Siirry"-vaihtoehdot: Liitä, Tallenna, Ponnahdusikkuna.
	Clear_Bad_Mount                 = Poista kaikki resurssit, jotka liittyvät vioittuneeseen liitettyyn kuvaan
	ShowCommand                     = Näytä täydellinen komentorivikäyttö
	Command                         = Komentorivi
	SelectSettingImage              = Kuvan lähde
	NoSelectImageSource             = Kuvalähdettä ei ole valittu
	SettingImageRestore             = Palauta oletusasennuspaikka
	SettingImage                    = Muuta kuvalähteen kiinnityspaikkaa
	SelectImageMountStatus          = Hanki asennustila, kun olet valinnut kuvalähteen
	SettingImageTempFolder          = Väliaikainen hakemisto
	SettingImageToTemp              = Väliaikainen hakemisto on sama kuin sijainti, johon se liitettiin
	SettingImagePathTemp            = Temp hakemiston käyttäminen
	SettingImageLow                 = Tarkista käytettävissä oleva vähimmäistila
	SettingImageNewPath             = Valitse asennuslevy
	SettingImageNewPathTips         = On suositeltavaa liittää se muistilevylle, joka on nopein. Voit käyttää virtuaalimuistiohjelmistoja, kuten Ultra RAMDisk ja ImDisk.
	SelectImageSource               = "Deploy Engine Solution" on valittu, napsauta OK.
	NoImagePreSource                = Käytettävissä olevaa lähdettä ei löytynyt, sinun tulee: \n\n     1. Lisää kuvalähteitä kohteeseen: \n          {0}\n\n     2. Valitse "Asetukset" ja valitse uudelleen kuvalähteen hakulevy;\n\n     3. Valitse "ISO" ja valitse purettava ISO, asennettavat kohteet jne.
	NoImageOtherSource              = Napsauta minua "Lisää" muita polkuja tai "Vedä hakemisto" nykyiseen ikkunaan.
	SearchImageSource               = Kuvalähteen hakulevy
	Kernel                          = Ydin
	Architecture                    = Arkkitehtuuri
	ArchitecturePack                = Pakettiarkkitehtuuri, lisäyssääntöjen ymmärtäminen
	ImageLevel                      = Asennustyyppi
	LevelDesktop                    = Työpöytä
	LevelServer                     = Palvelin
	ImageCodename                   = Koodinimi
	ImageCodenameNo                 = Ei tunnistettu
	MainImageFolder                 = Kotihakemisto
	MountImageTo                    = Kiinnittää
	Image_Path                      = Kuvan polku
	MountedIndex                    = Indeksi
	MountedIndexSelect              = Valitse indeksinumero
	AutoSelectIndexFailed           = Hakemiston {0} automaattinen valinta epäonnistui, yritä uudelleen.
	Apply                           = Sovellus
	Eject                           = Ponnahtaa esiin
	Mount                           = Kiinnitys
	ReMount                         = Uudelleenasennus
	Unmount                         = Poista asennus
	Mounted                         = Asennettu
	NotMounted                      = Ei asennettu
	NotMountedSpecify               = Ei asennettu, voit määrittää asennuspaikan
	MountedIndexError               = Epänormaali asennus, poista ja yritä uudelleen.
	NeedsRemount                    = Vaatii uudelleenasennuksen
	Invalid                         = Virheellinen
	ImageSouresNoSelect             = Näytä lisätietoja kuvalähteen valitsemisen jälkeen
	Mounted_Mode                    = Asennustila
	Mounted_Status                  = Kiinnityksen tila
	Status                          = Tila
	Image_Popup_Default             = Tallenna oletuksena
	Image_Restore_Default           = Palauta oletusarvo
	Image_Popup_Tips                = Vihje: \n\nKun määritit tapahtuman, et määrittänyt indeksinumeroa käsiteltäväksi {0};\n\nValintaliittymä on nyt ponnahtanut esiin. Määritä indeksinumero, kun määrittely on valmis, valitse "Tallenna oletukseksi".
	Rule_Show_Full                  = Näytä kaikki
	Rule_Show_Only                  = Näytä vain säännöt
	Rule_Show_Only_Select           = Valitse säännöistä
	Image_Unmount_After             = Poista kaikki asennetut

	Wim_Rule_Update                 = Pura ja päivitä kuvan sisältämät tiedostot
	Wim_Rule_Extract                = Pura tiedostot
	Wim_Rule_Extract_Tips           = Kun olet valinnut polkusäännön, pura määritetty tiedosto ja tallenna se paikallisesti.

	Wim_Rule_Verify                 = Vahvistaa
	Wim_Rule_Check                  = Tutkia
	Wim_Rule_CheckIntegrity         = Tarkista eheys
	Wim_Rule_ReadOnly               = Vain lukuoikeus
	Wim_Rule_Optimize               = Optimointi
	ResetBase                       = Syväpuhdistus
	Wim_Rule_SupportEa              = Käytä kuvia laajennetuilla ominaisuuksilla
	Wim_Rule_WIMBoot                = Käynnistettävä
	Wim_Rule_Compact                = Pakkaa käyttöjärjestelmätiedostot
	Win_Rule_Setbootable            = Merkitse aseman levykuva käynnistettäväksi
	Win_Rule_Setbootable_Tips       = Tämä parametri koskee vain Windows PE -levykuvia.\nVain yksi aseman levykuva voidaan merkitä käynnistettäväksi .wim-tiedostossa.
	Destination                     = Määränpäähän

	Wim_Append                      = Lisää
	Wim_Capture                     = Kaappaus
	Wim_Capture_Tips                = Kaappaa aseman levykuva uuteen WIM-tiedostoon.
	Wim_Capture_Sources             = Kaappauslähde
	Wim_Capture_Sources_Tips        = Kaappaushakemisto sisältää kaikki alikansiot ja tiedot.\nEt voi kaapata tyhjää hakemistoa. Hakemiston on sisällettävä vähintään yksi tiedosto.
	Wim_Config_File                 = Konfiguraatiotiedoston polku (poikkeukset)
	Wim_Config_Edit                 = Muokkaa
	Wim_Config_Learn                = Tutki konfiguraatioluetteloa ja WimScript.ini-tiedostoa

	Wim_Rename                      = Muokkaa kuvan tietoja
	Wim_Image_Name                  = Kuvan nimi
	Wim_Image_Description           = Kuvan kuvaus
	Wim_Display_Name                = Näyttönimi
	Wim_Display_Description         = Näytä kuvaus
	Wim_Edition                     = Kuvan merkki
	Wim_Edition_Select_Know         = Valitse tunnetut kuvaliput
	Wim_CreatedTime                 = Luontipäivämäärä
	Wim_ModifiedTime                = Viimeksi muokattu aika
	Wim_FileCount                   = Tiedostojen lukumäärä
	Wim_DirectoryCount              = Hakemistojen lukumäärä
	Wim_Expander_Space              = Laajennustila

	IABSelectNo                     = Ensisijaista avainta ei ole valittu: Install, WinRE, Boot
	Unique_Name                     = Ainutlaatuinen nimitys
	Select_Path                     = Polku
	Setting_Pri_Key                 = Aseta tämä päivitystiedosto päämalliksi
	Pri_Key_Update_To               = Päivitä sitten osoitteeseen
	Pri_Key_Template                = Aseta tämä tiedosto ensisijaiseksi malliksi, joka synkronoidaan valittujen kohteiden kanssa
	Pri_key_Running                 = Ensisijainen avaintehtävä on synkronoitu ja ohitettu.
	ShowAllExclude                  = Näytä kaikki käytöstä poistetut poissulkemiset

	Index_Process_All               = Käsittele kaikki tunnetut indeksinumerot
	Index_Is_Event_Select           = Kun on tapahtuma, indeksinumeron valintaliittymä ponnahtaa esiin.
	Index_Pre_Select                = Ennalta määritetty indeksinumero
	Index_Select_Tips               = Vihje: \n\n{0}.wim ei ole tällä hetkellä asennettuna, voit: \n\n   1. Valitse "Käsittele kaikki tunnetut indeksinumerot";\n\n   2. Valitse "Kun on tapahtuma, indeksinumeron valintaliittymä avautuu";\n\n   3. Ennalta määritetty indeksinumero\n      Indeksinumero 6 on määritetty, indeksinumeroa ei ole olemassa käsittelyn aikana ja käsittely ohitetaan.

	Index_Tips_Custom_Expand        = Ryhmä: {0}\n\nKäsiteltäessä {1} indeksinumeroa {2} on määritettävä, muuten sitä ei voida käsitellä.\n\nKun olet valinnut "Synkronoi päivityssäännöt kaikkiin indeksinumeroihin", sinun tarvitsee vain valita mikä tahansa päämalliksi.

	DefenderExclude                 = Windowsin virustorjuntaohjelmien poissulkemiset
	DefenderFolder                  = Lisää tämä hakemisto Windowsin virustorjuntaohjelmien poissulkemisluetteloon.
	DefenderVolume                  = Kun löydät vastaavan aseman nimen, lisää tämä levy Windowsin virustorjuntaohjelmien poissulkemisluetteloon.
	DefenderIsAdd                   = Lisätty Windowsin virustorjuntaohjelmien poissulkemisluetteloon
'@