ConvertFrom-StringData -StringData @'
	# lt-LT
	# Lithuanian (Lithuania)

	FontsUI                   = Segoe UI
	Mainname                  = Diegimo variklis: Yi rinkinys
	Learn                     = studijuoti
	MainHisName               = Premijos sprendimas
	Location                  = Atidaryti vietą
	About                     = apie
	Reset                     = atstatyti
	AddTo                     = Pridėti prie
	Instl                     = Įdiegti
	ItInstalled               = Įdiegta
	Close                     = uždarymas
	Auto                      = automatinis
	Disable                   = Išjungti
	Enable                    = įjungti
	Setting                   = nustatyti
	Restore                   = atsigauti
	Clean                     = apsivalyti
	Operable                  = Veikiantis
	Inoperable                = Neveikiantis
	Optimize                  = optimizavimas
	Hide                      = paslėpti
	Show                      = parodyti
	Del                       = ištrinti
	Done                      = Baigti
	OK                        = Žinoma
	Cancel                    = Atšaukti
	AllSel                    = Pasirinkite viską
	AllClear                  = išvalyti viską
	Refresh                   = atnaujinti
	RefreshModules            = Karštas visų modulių atnaujinimas
	Necessary                 = Esminė programinė įranga
	MostUsedSoftware          = Dažniausiai naudojama programinė įranga
	System                    = sistema
	Service                   = Patiekite
	TaskBar                   = Visos užduočių juostos piktogramos
	DeskIcon                  = darbalaukio piktogramos
	InstallFonts              = Įdiekite šriftus
	SettingTo                 = Nustatyti į {0}
	Command                   = Komandinė eilutė
	RuleName                  = Taisyklės pavadinimas
	Language                  = Kalba
	Command                   = Riga di comando
	RuleName                  = Nome della regola
	Language                  = Lingua
	AvailableLanguages        = Galimos kalbos
	SwitchLanguage            = pakeisti kalbą
	LanguageReset             = Iš naujo nustatykite kalbos nustatymus
	LanguageCode              = zonos ženklas
	LanguageSelRegion         = Pasirinkite savo šalį arba regioną
	LanguageRemember          = Prisiminti pasirinktą kalbą
	LanguageSearchNo          = Galimų kalbų nerasta
	LanguageNoSel             = Pasirinkite regioną
	Search                    = Paieška
	PleaseChoose              = Prašome pasirinkti
	FailedCreateFolder        = Nepavyko sukurti katalogo
	Failed                    = Nepavyks
	ToMsg                     = {0} Po sekundžių automatiškai grįžkite į pagrindinį meniu.
	Restart                   = Paleidimas iš naujo įsigalios
	AdvOption                 = pasirenkamos funkcijos

	StartDown                 = Pradėkite atsisiųsti
	ConnectTo                 = Prisijunkite prie
	FileName                  = failo pavadinimas
	SaveTo                    = išsaugoti į
	NotAvailable              = Būsena: nėra
	ExistingPacker            = Jau turi diegimo paketą
	ExistingInstlPacker       = Jau turi suspaustą pakuotę
	Unpacking                 = Išpakavimas
	QucikRun                  = Greitas bėgimas:
	WaitDone                  = Laukia užbaigimo:
	Parameter                 = parametras:
	ErrorDown                 = Atsisiunčiant įvyko klaida
	UserCancel                = Vartotojas atšaukė operaciją.

	VerifyNameTips            = Leidžiamas tik angliškų raidžių ir skaičių derinys, neleidžiami jokie kiti simboliai: tarpai, ilgis negali būti didesnis nei 16 simbolių, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Pasirinktinis katalogo priešdėlis
	NoSetFolderLabel          = Pasirinktinis katalogo priešdėlis nenustatytas
	ISO9660TipsErrorSpace     = Negali būti tarpų priekyje ir gale
	ISO9660TipsErrorOther     = Negali būti: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = Tomo etiketė negali būti ilgesnė nei {0} simboliai
	Help                      = padėti
	WorkDone                  = Baigta, paspauskite bet kurį klavišą, kad grįžtumėte į pagrindinę sąsają...
	Short_Cmd                 = Spartieji klavišai
	Options                   = Parinktys
	LXPsWaitAssign            = Turi būti paskirta
	Running                   = Paleisti
	SpecialFunction           = PowerShell funkcijos
'@