ConvertFrom-StringData -StringData @'
	# ko-KR
	# Korean (Korea)

	UnpackISO                       = ISO 생성
	ISOLabel                        = 볼륨 레이블이 설정되었습니다: \
	ISOCustomize                    = ISO 볼륨 레이블 이름
	ISO9660                         = 명명 규칙 확인
	ISO9660Tips                     = 고유 이름은 260자를 초과할 수 없으며 ISO 볼륨 레이블 이름은 16자를 초과할 수 없으며 선행 및 후행 공백을 포함할 수 없습니다. \\ / : * ? & @ ! "" < > |
	ISOFolderName                   = 사용자 정의 고유 이름
	ISOAddFlagsLang                 = 다국어 마크업 추가
	ISOAddFlagsLangGet              = 알려진 설치 언어 얻기
	ISOAddFlagsVer                  = 다중 버전 태그 추가
	ISOAddFlagsVerGet               = 알려진 이미지 버전 가져오기
	ISOAddEICFG                     = 버전 유형 추가
	ISOAddEICFGTips                 = EI.cfg 에 의존할 때 상용 버전.
	ISO9660TipsErrorSpace           = 포함할 수 없음: 선행 및 후행 공백
	ISO9660TipsErrorOther           = 다음을 포함할 수 없음: \\ / : * ? & @ ! "" < > |
	SelOSver                        = 언어 유형 선택
	SelLabel                        = 암호
	ISOVerLabel                     = ISO 볼륨 레이블 이름 선택
	NoSetLabel                      = 사용자 정의 ISO 볼륨 레이블이 설정되지 않았습니다.
	ISOLengthError                  = 레이블 길이는 {0} 자를 초과할 수 없습니다.
	RenameFailed                    = 이전 디렉터리와 동일합니다. 이름 바꾸기에 실패했습니다
	ISOCreateAfter                  = ISO 를 만들기 전에 해야 할 일
	ISOCreateRear                   = ISO 를 생성한 후 해야 할 일
	BypassTPM                       = TPM 설치 확인 우회
	Disable_BitLocker               = 설치 중 BitLocker 장치 암호화 비활성화
	PublicDate                      = 발행일
	PublicDateGetCurrent            = 현재 날짜 동기화
	PublicYear                      = 년도
	PublicMonth                     = 달
	PublicYMSorting                 = "월_년" 을 "년_월" 로 변경하여 정렬하세요
	PublicYMSortingTips             = AB: 숫자를 사용할 때 밑줄 _ 을 추가하지 마세요.
	PublicYMUseShortNames           = 짧은 이름을 사용하세요
	PublicYMUseNumbers              = 숫자를 사용하세요
	ISOCreateFailed                 = 를 생성하지 못했습니다. 디렉토리를 읽고 쓸 수 없습니다.
	ISORefreshAuto                  = 매번 ISO 태그 새로 고침
	ISOSaveTo                       = ISO 기본 저장 위치
	ISOSaveSameGlobal               = 전역 ISO 기본 저장 위치 사용
	ISOSaveSync                     = 이미지 소스 검색 디스크 선택 후 자동으로 새 위치 동기화
	ISOSaveSame                     = 이미지 소스를 사용하여 디스크 경로 검색
	ISOFolderWrite                  = 디렉토리를 읽고 쓸 수 있는지 확인
	SelectAutoAvailable             = 사용 가능한 디스크가 자동으로 선택된 경우
	SelectCheckAvailable            = 최소 여유 공간 확인
	ISOStructure                    = 새로운 디렉토리 구조
	ISOOSLevel                      = 설치 유형 추가
	ISOUniqueNameDirectory          = 고유한 이름 디렉토리 추가
	NextDoOperate                   = ISO 를 생성하지 마십시오.
	SelCreateISO                    = ISO 생성, 요청 시 실행
	Reconstruction                  = 가장 높은 압축률로 {0}.wim 을 다시 빌드합니다
	Reconstruction_Tips_Select      = 재구축하기 전에는 마운트되지 않았을 때만 실행되며 강제로 세이브를 연 다음 마운트된 마운트를 해제합니다.
	ReconstructionTips              = 초과하다 520 MB, 재구축 권장
	CreateASC                       = ISO 에 PGP 서명 추가
	NoPGPKey                        = PGP 에는 사용 가능한 개인 키가 없습니다.
	CreateASCPwd                    = 인증서 비밀번호
	PasswordRenter                  = 비밀번호를 다시 입력하세요
	ShowPassword                    = 비밀번호 보기
	NewPasswordSome                 = 비밀번호가 일치하지 않습니다.
	PwdPermanent                    = 영구 저장소
	PwdDecfailed                    = 복호화 실패
	CreateASCAuthor                 = 서명자
	CreateASCAuthorTips             = 선택한 서명자가 없습니다.
	ISO_Sparse_Rename               = 파일 이름 확장자에 해시 기호를 추가하세요.
	GenerateRandom                  = 난수 생성
	RandomNumberReset               = 재생하다
'@