ConvertFrom-StringData -StringData @'
	# th-TH
	# Thai (Thailand)

	FontsUI                   = Leelawadee UI
	Mainname                  = กลไกการปรับใช้: ชุดของ Yi
	Learn                     = ศึกษา
	MainHisName               = โซลูชั่นโบนัส
	Location                  = เปิดสถานที่
	About                     = เกี่ยวกับ
	Reset                     = รีเซ็ต
	AddTo                     = เพิ่มไปที่
	Instl                     = ติดตั้ง
	ItInstalled               = ติดตั้งแล้ว
	Close                     = ปิด
	Auto                      = อัตโนมัติ
	Disable                   = ปิดการใช้งาน
	Enable                    = เปิดใช้งาน
	Setting                   = ตั้งค่า
	Restore                   = ฟื้นตัว
	CLearn                    = ทำความสะอาด
	Operable                  = ใช้งานได้
	Inoperable                = ใช้ไม่ได้
	Optimize                  = การเพิ่มประสิทธิภาพ
	Hide                      = ซ่อน
	Show                      = แสดง
	Del                       = ลบ
	Done                      = เสร็จ
	OK                        = แน่นอน
	Cancel                    = ยกเลิก
	AllSel                    = เลือกทั้งหมด
	AllClear                  = เคลียร์ทั้งหมด
	Refresh                   = รีเฟรช
	RefreshModules            = รีเฟรชทุกโมดูลอย่างรวดเร็ว
	Necessary                 = ซอฟต์แวร์ที่จำเป็น
	MostUsedSoftware          = ซอฟต์แวร์ที่ใช้กันทั่วไป
	System                    = ระบบ
	Service                   = ให้บริการ
	TaskBar                   = ไอคอนแถบงานทั้งหมด
	DeskIcon                  = ไอคอนเดสก์ท็อป
	InstallFonts              = ติดตั้งแบบอักษร
	SettingTo                 = ตั้งค่าเป็น {0}
	AvailableLanguages        = ภาษาที่ใช้ได้
	SwitchLanguage            = เปลี่ยนภาษา
	LanguageReset             = รีเซ็ตการตั้งค่าภาษา
	LanguageCode              = เครื่องหมายโซน
	LanguageSelRegion         = เลือกประเทศหรือภูมิภาคของคุณ
	LanguageRemember          = จำภาษาที่เลือก
	LanguageSearchNo          = ไม่พบภาษาที่ใช้ได้
	LanguageNoPack            = หากไม่มีชุดภาษาในเครื่อง ระบบจะออกโดยอัตโนมัติ
	LanguageNoSel             = โปรดเลือกภูมิภาค
	Search                    = ค้นหา
	PleaseChoose              = กรุณาเลือก
	FailedCreateFolder        = ไม่สามารถสร้างไดเร็กทอรี
	Failed                    = ล้มเหลว
	ToMsg                     = {0} กลับสู่เมนูหลักโดยอัตโนมัติหลังจากผ่านไปไม่กี่วินาที
	Restart                   = การรีสตาร์ทจะมีผล
	AdvOption                 = คุณสมบัติเสริม

	StartDown                 = เริ่มดาวน์โหลด
	ConnectTo                 = เชื่อมต่อไปยัง
	FileName                  = ชื่อไฟล์
	SaveTo                    = บันทึกไปที่
	NotAvailable              = สถานะ: ไม่สามารถใช้ได้
	ExistingPacker            = มีแพ็คเกจติดตั้งอยู่แล้ว
	ExistingInstlPacker       = มีแพ็คเกจบีบอัดอยู่แล้ว
	Unpacking                 = กำลังคลายซิป
	QucikRun                  = วิ่งเร็ว:
	WaitDone                  = กำลังรอดำเนินการให้เสร็จสิ้น:
	Parameter                 = พารามิเตอร์:
	ErrorDown                 = เกิดข้อผิดพลาดระหว่างการดาวน์โหลด
	UserCancel                = ผู้ใช้ได้ยกเลิกการดำเนินการ

	VerifyNameTips            = อนุญาตให้ใช้เฉพาะตัวอักษรภาษาอังกฤษและตัวเลขผสมกันเท่านั้น และไม่อนุญาตให้ใช้อักขระอื่น: ช่องว่าง ความยาวต้องไม่เกิน 16 ตัวอักษร, \\ / : * ? & @ ! "" < > |
	FolderLabel               = คำนำหน้าไดเรกทอรีที่กำหนดเอง
	NoSetFolderLabel          = ไม่ได้ตั้งค่าคำนำหน้าไดเรกทอรีที่กำหนดเอง
	ISO9660TipsErrorSpace     = ไม่สามารถมี: ช่องว่างนำหน้าและต่อท้าย
	ISO9660TipsErrorOther     = ไม่สามารถมี: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = ป้ายกำกับปริมาณต้องไม่ยาวเกิน {0} อักขระ
	Help                      = ช่วย
	WorkDone                  = เสร็จแล้วกดปุ่มใดก็ได้เพื่อกลับสู่หน้าจอหลัก...
	Short_Cmd                 = ทางลัด
	Options                   = ตัวเลือก
'@